import {
  Activity,
  BellRing,
  BrainCircuit,
  Briefcase,
  CalendarClock,
  CalendarDays,
  CheckSquare,
  FolderKanban,
  Globe2,
  HeartPulse,
  Home as HomeIcon,
  Inbox,
  LayoutGrid,
  LibraryBig,
  Link2,
  NotebookText,
  PanelsTopLeft,
  RefreshCw,
  Settings as SettingsIcon,
  SlidersHorizontal,
  Sparkles,
  Target,
  UploadCloud,
  Utensils,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

export type NavItem = { label:string; href:string; icon:LucideIcon; description:string };

export const navItems: NavItem[] = [
  { label:'Home', href:'/dashboard', icon:LayoutGrid, description:'Your daily command center' },
  { label:'Today', href:'/today', icon:Sparkles, description:'Act on what matters now' },
  { label:'Day Mode', href:'/day-mode', icon:SlidersHorizontal, description:'Adapt the day to your available energy and capacity' },
  { label:'Tomorrow', href:'/tomorrow', icon:CalendarClock, description:'Prepare the next day before it begins' },
  { label:'Planning', href:'/planning', icon:PanelsTopLeft, description:'Connect today, week, quarter, and year' },
  { label:'Calendar', href:'/calendar', icon:CalendarDays, description:'See day, week, month and timeline views' },
  { label:'Tasks', href:'/tasks', icon:CheckSquare, description:'Focus on what matters' },
  { label:'Reminders', href:'/reminders', icon:BellRing, description:'Keep small obligations from becoming mental clutter' },
  { label:'Alert Center', href:'/alerts', icon:BellRing, description:'Set reminder timing and delivery channels across Glow' },
  { label:'Routines', href:'/routines', icon:RefreshCw, description:'Run morning, evening, reset, wellness and care rituals' },
  { label:'Habits', href:'/habits', icon:Activity, description:'Build steady repeated behaviors' },
  { label:'Brain', href:'/brain', icon:BrainCircuit, description:'Ask, understand, connect and decide' },
  { label:'Concierge', href:'/concierge', icon:BrainCircuit, description:'Turn requests into organized next actions' },
  { label:'Memory', href:'/memory', icon:LibraryBig, description:'Your living archive of moments and context' },
  { label:'Observations', href:'/observations', icon:HeartPulse, description:'See evidence-based patterns across your life' },
  { label:'Graph', href:'/graph', icon:Link2, description:'Visualize how people, projects and life areas connect' },
  { label:'Brain Connection', href:'/brain-connection', icon:Link2, description:'See the people and connected rooms feeding Glow Brain' },
  { label:'Knowledge Web', href:'/knowledge', icon:LibraryBig, description:'Browse Notes and Memory with wikilinks and backlinks' },
  { label:'Timeline', href:'/timeline', icon:CalendarDays, description:'See your life story over time' },
  { label:'Briefings', href:'/briefings', icon:NotebookText, description:'Morning, evening, weekly and monthly reviews' },
  { label:'Glow Inbox', href:'/inbox', icon:Inbox, description:'Review and route captured information' },
  { label:'Universal Intake', href:'/intake', icon:UploadCloud, description:'Add files, screenshots, links, notes and voice' },
  { label:'Personal Rules', href:'/rules', icon:SlidersHorizontal, description:'Teach Glow how your life should be planned' },
  { label:'Wellness', href:'/wellness', icon:HeartPulse, description:'See care, energy and body signals together' },
  { label:'Fitness', href:'/fitness', icon:Activity, description:'Train around energy and recovery' },
  { label:'Workout Studio', href:'/workout-studio', icon:Activity, description:'Enter focused workout mode' },
  { label:'Food & Nutrition', href:'/food', icon:Utensils, description:'Plan meals, groceries, pantry and prep together' },
  { label:'Medications & Supplements', href:'/maintenance', icon:CalendarClock, description:'Track care schedules, refills and maintenance' },
  { label:'Sleep', href:'/sleep', icon:HeartPulse, description:'Review sleep as part of your wellness system' },
  { label:'Symptoms & Recovery', href:'/symptoms', icon:HeartPulse, description:'Track symptoms, recovery and trends' },
  { label:'Beauty', href:'/beauty', icon:Sparkles, description:'Your beauty system and daily care hub' },
  { label:'Beauty Lab', href:'/beauty/lab', icon:Sparkles, description:'Track products, ingredients and reactions' },
  { label:'Beauty Progress', href:'/beauty-progress', icon:Sparkles, description:'See long-term beauty consistency and progress' },
  { label:'Hair Studio', href:'/hair', icon:Sparkles, description:'Track hair cycles, treatments and appointments' },
  { label:'Hair Lifecycle', href:'/hair-lifecycle', icon:Sparkles, description:'See each wash, treatment and refresh cycle' },
  { label:'Beauty Calendar', href:'/beauty-calendar', icon:CalendarDays, description:'Keep treatments and beauty dates in one view' },
  { label:'Closet', href:'/closet', icon:HomeIcon, description:'Know what you own and wear' },
  { label:'Financial Brain', href:'/finance/brain', icon:Wallet, description:'Understand your money and make confident decisions' },
  { label:'Financial Overview', href:'/finance', icon:Wallet, description:'See accounts, spending, cash flow and obligations' },
  { label:'Spending', href:'/spending', icon:Wallet, description:'Review category spending and trends' },
  { label:'Subscriptions', href:'/subscriptions', icon:Wallet, description:'Manage recurring charges and renewals' },
  { label:'Forecast', href:'/forecast', icon:Wallet, description:'See your projected financial future' },
  { label:'Transactions', href:'/transactions', icon:Wallet, description:'Review purchases and money movement' },
  { label:'Goals', href:'/goals', icon:Target, description:'Move long-term goals forward' },
  { label:'Career & Work', href:'/work', icon:Briefcase, description:'Organize work, opportunities and professional progress' },
  { label:'Applications', href:'/applications', icon:Briefcase, description:'Track every job application and next step' },
  { label:'Interviews', href:'/interviews', icon:Briefcase, description:'Prepare and track interviews' },
  { label:'Interview Prep', href:'/interview-prep', icon:Briefcase, description:'Enter focused interview preparation mode' },
  { label:'Projects', href:'/projects', icon:FolderKanban, description:'Run projects, milestones and next actions' },
  { label:'Creative Studio', href:'/creative-studio', icon:Sparkles, description:'Build visual creative direction from real projects' },
  { label:'Home', href:'/home', icon:HomeIcon, description:'Care for your physical space' },
  { label:'All Rooms', href:'/all-rooms', icon:LayoutGrid, description:'Browse every part of Glow OS' },
  { label:'Life World', href:'/world', icon:Globe2, description:'See the bigger spatial picture of your life' },
  { label:'Travel', href:'/travel', icon:Globe2, description:'Plan trips, itineraries, packing and memories' },
  { label:'Deep Focus', href:'/focus', icon:Target, description:'Enter a distraction-reduced work mode' },
  { label:'Ambient Space', href:'/ambient', icon:Sparkles, description:'Set a focus, rest, sleep or creative environment' },
  { label:'Gmail', href:'/gmail', icon:Link2, description:'Bring important email context into Glow' },
  { label:'Notes', href:'/notes', icon:NotebookText, description:'Capture ideas beautifully' },
  { label:'Resources', href:'/resources', icon:LibraryBig, description:'Reusable life guides and reset routines' },
  { label:'Connections', href:'/connections', icon:Link2, description:'Connect your digital world' },
  { label:'Import', href:'/import', icon:UploadCloud, description:'Bring existing information into Glow OS' },
  { label:'Notices', href:'/notices', icon:BellRing, description:'Important updates and actionable intelligence' },
  { label:'System Overview', href:'/system-overview', icon:SettingsIcon, description:'Review connections, imports, alerts and system health' },
  { label:'Settings', href:'/settings', icon:SettingsIcon, description:'Tune your Glow OS environment' },
];