import {
  Activity,
  BellRing,
  BrainCircuit,
  Briefcase,
  CalendarClock,
  CalendarDays,
  CheckSquare,
  FolderKanban,
  Globe2,
  HeartPulse,
  Home as HomeIcon,
  Inbox,
  LayoutGrid,
  LibraryBig,
  Link2,
  NotebookText,
  PanelsTopLeft,
  RefreshCw,
  Settings as SettingsIcon,
  SlidersHorizontal,
  Sparkles,
  Target,
  UploadCloud,
  Utensils,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

export type NavItem = { label:string; href:string; icon:LucideIcon; description:string };

export const navItems: NavItem[] = [
  { label:'Home', href:'/dashboard', icon:LayoutGrid, description:'Plan the day with elegance' },
  { label:'Today', href:'/today', icon:Sparkles, description:'Act on what matters now' },
  { label:'Day Mode', href:'/day-mode', icon:SlidersHorizontal, description:'Choose Most Productive, Productive, Bare Minimum, or Clear Schedule' },
  { label:'Tomorrow', href:'/tomorrow', icon:CalendarClock, description:'Prepare the next day before it begins' },
  { label:'Brain', href:'/brain', icon:BrainCircuit, description:'See what matters next' },
  { label:'Concierge', href:'/concierge', icon:BrainCircuit, description:'Propose changes with approval' },
  { label:'Glow Inbox', href:'/inbox', icon:Inbox, description:'Review and route captured information' },
  { label:'Universal Intake', href:'/intake', icon:UploadCloud, description:'Drop files, screenshots, lists, and notes into Glow' },
  { label:'Personal Rules', href:'/rules', icon:SlidersHorizontal, description:'Teach Glow how your life should be planned' },
  { label:'Maintenance', href:'/maintenance', icon:CalendarClock, description:'See upcoming care and replacement forecasts' },
  { label:'Planning', href:'/planning', icon:PanelsTopLeft, description:'Connect today, week, quarter, and year' },
  { label:'Calendar', href:'/calendar', icon:CalendarDays, description:'Shape the week' },
  { label:'Reminders', href:'/reminders', icon:BellRing, description:'Bring Apple Reminders into Glow intelligence' },
  { label:'Alert Center', href:'/alerts', icon:BellRing, description:'Set reminder timing and delivery channels across Glow' },
  { label:'Work', href:'/work', icon:Briefcase, description:'Keep recurring work shifts visible' },
  { label:'Tasks', href:'/tasks', icon:CheckSquare, description:'Focus on what matters' },
  { label:'Routines', href:'/routines', icon:RefreshCw, description:'Enter adaptive morning, night, reset, and care rituals' },
  { label:'Habits', href:'/habits', icon:Activity, description:'Build steady rituals' },
  { label:'Observations', href:'/observations', icon:HeartPulse, description:'Notice evidence-based patterns' },
  { label:'Fitness', href:'/fitness', icon:Activity, description:'Train around energy and recovery' },
  { label:'Wellness', href:'/wellness', icon:HeartPulse, description:'Protect your energy' },
  { label:'Food & Nutrition', href:'/food', icon:Utensils, description:'Plan meals, groceries, pantry and prep together' },
  { label:'Beauty', href:'/beauty', icon:Sparkles, description:'Keep the routine refined' },
  { label:'Beauty Lab', href:'/beauty/lab', icon:Sparkles, description:'Track products and reactions' },
  { label:'Hair', href:'/hair', icon:Sparkles, description:'Track hair care and next actions' },
  { label:'Finance', href:'/finance', icon:Wallet, description:'Stay financially calm' },
  { label:'Financial Brain', href:'/finance/brain', icon:Wallet, description:'Track goals and direction' },
  { label:'Goals', href:'/goals', icon:Target, description:'Move your ambitions forward' },
  { label:'Projects', href:'/projects', icon:FolderKanban, description:'Run projects and Creative Studio' },
  { label:'Memory', href:'/memory', icon:LibraryBig, description:'Build your private life memory' },
  { label:'Knowledge Web', href:'/knowledge', icon:LibraryBig, description:'Browse Notes and Memory with wikilinks and backlinks' },
  { label:'Timeline', href:'/timeline', icon:CalendarDays, description:'See your life story over time' },
  { label:'Briefings', href:'/briefings', icon:NotebookText, description:'Morning, evening, and weekly reviews' },
  { label:'Closet', href:'/closet', icon:HomeIcon, description:'Know what you own and wear' },
  { label:'Gmail', href:'/gmail', icon:Link2, description:'See read-only inbox intelligence' },
  { label:'World', href:'/world', icon:Globe2, description:'Enter your Life World' },
  { label:'Home', href:'/home', icon:HomeIcon, description:'Care for your space' },
  { label:'Notes', href:'/notes', icon:NotebookText, description:'Capture ideas beautifully' },
  { label:'Resources', href:'/resources', icon:LibraryBig, description:'Reusable life guides and reset routines' },
  { label:'Connections', href:'/connections', icon:Link2, description:'Connect your digital world' },
  { label:'Import', href:'/import', icon:UploadCloud, description:'Bring in the Glow OS master system' },
  { label:'Settings', href:'/settings', icon:SettingsIcon, description:'Tune your environment' },
];
