import { Activity, BrainCircuit, CalendarDays, CheckSquare, FolderKanban, Globe2, HeartPulse, Home as HomeIcon, Inbox, LayoutGrid, LibraryBig, Link2, NotebookText, PanelsTopLeft, Settings as SettingsIcon, Sparkles, Target, UploadCloud, Wallet, Zap, BookOpen, type LucideIcon } from 'lucide-react';

export type NavItem = { label: string; href: string; icon: LucideIcon; description: string; };

export const navItems: NavItem[] = [
  { label: 'Home', href: '/dashboard', icon: LayoutGrid, description: 'Return to the living command center' },
  { label: 'Today', href: '/today', icon: Zap, description: 'Let Glow decide what matters now' },
  { label: 'Plan', href: '/planning', icon: PanelsTopLeft, description: 'Connect today, week, quarter, and year' },
  { label: 'World', href: '/world', icon: Globe2, description: 'Enter your connected Life World' },
  { label: 'Glow Brain', href: '/brain', icon: BrainCircuit, description: 'Ask across your whole life' },
  { label: 'Add Anything', href: '/intake', icon: UploadCloud, description: 'Universal intake for text, images and files' },
  { label: 'Glow Inbox', href: '/inbox', icon: Inbox, description: 'Review and route captured information' },
  { label: 'Tasks', href: '/tasks', icon: CheckSquare, description: 'Execute next actions and dependencies' },
  { label: 'Calendar', href: '/calendar', icon: CalendarDays, description: 'Shape time around commitments' },
  { label: 'Habits', href: '/habits', icon: Activity, description: 'Build steady rituals' },
  { label: 'Fitness', href: '/fitness', icon: Activity, description: 'Train around energy and recovery' },
  { label: 'Beauty', href: '/beauty', icon: Sparkles, description: 'Keep the routine refined' },
  { label: 'Beauty Lab', href: '/beauty/lab', icon: Sparkles, description: 'Track products and reactions' },
  { label: 'Hair', href: '/hair', icon: Sparkles, description: 'Track care cycles and next actions' },
  { label: 'Wellness', href: '/wellness', icon: HeartPulse, description: 'Protect energy and recovery' },
  { label: 'Finance', href: '/finance', icon: Wallet, description: 'Understand spending and budgets' },
  { label: 'Financial Brain', href: '/finance/brain', icon: Wallet, description: 'Forecast goals and decisions' },
  { label: 'Goals', href: '/goals', icon: Target, description: 'Connect ambitions to action' },
  { label: 'Projects', href: '/projects', icon: FolderKanban, description: 'Run projects and Creative Studio' },
  { label: 'Concierge', href: '/concierge', icon: BrainCircuit, description: 'Approve safe system changes' },
  { label: 'Glow Notices', href: '/observations', icon: HeartPulse, description: 'Notice evidence-based patterns' },
  { label: 'Memory', href: '/memory', icon: LibraryBig, description: 'Build your private life memory' },
  { label: 'Timeline', href: '/timeline', icon: CalendarDays, description: 'See your life story over time' },
  { label: 'Briefings', href: '/briefings', icon: NotebookText, description: 'Morning, evening, and weekly reviews' },
  { label: 'Closet', href: '/closet', icon: HomeIcon, description: 'Know what you own and wear' },
  { label: 'Gmail', href: '/gmail', icon: Link2, description: 'See read-only inbox intelligence' },
  { label: 'Home System', href: '/home', icon: HomeIcon, description: 'Care for your space' },
  { label: 'Resources', href: '/resources', icon: BookOpen, description: 'Reusable plans, guides and references' },
  { label: 'Notes', href: '/notes', icon: NotebookText, description: 'Capture and connect knowledge' },
  { label: 'Connections', href: '/connections', icon: Link2, description: 'Connect your digital world' },
  { label: 'Import', href: '/import', icon: UploadCloud, description: 'Bring in structured master data' },
  { label: 'Settings', href: '/settings', icon: SettingsIcon, description: 'Tune your environment' },
];
