export type GlowWorld = 'today' | 'mind' | 'wellness' | 'beauty' | 'money' | 'work' | 'home' | 'system';

export type WorldArchitecture = {
  world: GlowWorld;
  metaphor: string;
  eyebrow: string;
  title: string;
  statement: string;
  insight: string;
  actionLabel: string;
  actionHref: string;
  context: Array<{ label: string; href: string }>;
};

const rooms: Array<{ test: (path: string) => boolean; room: WorldArchitecture }> = [
  { test: p => p.startsWith('/dashboard') || p === '/today', room: { world:'today', metaphor:'atrium', eyebrow:'Today', title:'Your Day', statement:'See what matters now, move through it calmly, and keep the rest of your life connected.', insight:'Your home surface should summarize your life without making you hunt for the source.', actionLabel:'Open Morning Brief', actionHref:'/briefings', context:[{label:'Calendar',href:'/calendar'},{label:'Tasks',href:'/tasks'},{label:'Routines',href:'/routines'}] } },
  { test: p => p.startsWith('/planning') || p.startsWith('/tomorrow'), room: { world:'today', metaphor:'planning-table', eyebrow:'Planning', title:'Planning Room', statement:'Turn priorities, time, routines and responsibilities into one intentional plan.', insight:'Plan once. Let the same information appear everywhere it is relevant.', actionLabel:'Plan Today', actionHref:'/planning', context:[{label:'Calendar',href:'/calendar'},{label:'Tasks',href:'/tasks'},{label:'Goals',href:'/goals'}] } },
  { test: p => p.startsWith('/calendar'), room: { world:'today', metaphor:'time-wall', eyebrow:'Time', title:'Calendar', statement:'Shape your day, week and month from one connected time system.', insight:'Events can feed briefings, beauty, work, wellness and your life timeline automatically.', actionLabel:'Open Today', actionHref:'/today', context:[{label:'Timeline',href:'/timeline'},{label:'Planning',href:'/planning'},{label:'Reminders',href:'/reminders'}] } },
  { test: p => p.startsWith('/tasks'), room: { world:'today', metaphor:'action-board', eyebrow:'Action', title:'Tasks', statement:'Keep commitments clear, prioritized and attached to the right part of your life.', insight:'A task should live once, then surface in Home, Projects, Briefings and Focus when needed.', actionLabel:'Focus Now', actionHref:'/focus', context:[{label:'Projects',href:'/projects'},{label:'Planning',href:'/planning'},{label:'Goals',href:'/goals'}] } },
  { test: p => p.startsWith('/reminders'), room: { world:'today', metaphor:'reminder-wall', eyebrow:'Remember', title:'Reminders', statement:'Keep small obligations visible before they become mental clutter.', insight:'Reminders belong inside the same intelligence layer as tasks and calendar events.', actionLabel:'Review Today', actionHref:'/reminders', context:[{label:'Tasks',href:'/tasks'},{label:'Calendar',href:'/calendar'},{label:'Notices',href:'/notices'}] } },
  { test: p => p.startsWith('/brain'), room: { world:'mind', metaphor:'observatory', eyebrow:'Glow Intelligence', title:'Brain', statement:'Your personal intelligence chamber. Ask, understand, connect, remember and decide.', insight:'Brain interprets your connected life. It should not become a second copy of your data.', actionLabel:'Ask Glow', actionHref:'/brain', context:[{label:'Memory',href:'/memory'},{label:'Observations',href:'/observations'},{label:'Graph',href:'/graph'}] } },
  { test: p => p.startsWith('/concierge'), room: { world:'mind', metaphor:'concierge-desk', eyebrow:'Assistance', title:'Concierge', statement:'Turn requests into organized next steps across your life.', insight:'Concierge should propose actions, then use the real source systems when you approve them.', actionLabel:'New Request', actionHref:'/concierge', context:[{label:'Brain',href:'/brain'},{label:'Calendar',href:'/calendar'},{label:'Connections',href:'/connections'}] } },
  { test: p => p.startsWith('/memory'), room: { world:'mind', metaphor:'archive', eyebrow:'Remember', title:'Memory', statement:'A living archive of moments, people, places, projects, ideas and experiences.', insight:'Memory supplies context. Timeline supplies sequence. Graph supplies relationships.', actionLabel:'View Timeline', actionHref:'/timeline', context:[{label:'Timeline',href:'/timeline'},{label:'Notes',href:'/notes'},{label:'Brain',href:'/brain'}] } },
  { test: p => p.startsWith('/observations'), room: { world:'mind', metaphor:'pattern-wall', eyebrow:'Patterns', title:'Observations', statement:'See evidence-based patterns Glow finds across your routines, work, wellness and life.', insight:'An observation is useful only when it can show evidence and lead to a helpful next action.', actionLabel:'Open Graph', actionHref:'/graph', context:[{label:'Graph',href:'/graph'},{label:'Brain',href:'/brain'},{label:'Wellness',href:'/wellness'}] } },
  { test: p => p.startsWith('/graph'), room: { world:'mind', metaphor:'connection-map', eyebrow:'Connections', title:'Your Life Graph', statement:'Visualize how the people, projects, routines, goals and places in your life relate.', insight:'One object can participate in many views without being duplicated.', actionLabel:'Explore Memory', actionHref:'/memory', context:[{label:'Memory',href:'/memory'},{label:'Timeline',href:'/timeline'},{label:'Observations',href:'/observations'}] } },
  { test: p => p.startsWith('/timeline'), room: { world:'mind', metaphor:'life-ribbon', eyebrow:'Sequence', title:'Timeline', statement:'See your life beautifully unwound across days, months, years and milestones.', insight:'Important events from every room can become part of your personal history.', actionLabel:'Open Memory', actionHref:'/memory', context:[{label:'Memory',href:'/memory'},{label:'Calendar',href:'/calendar'},{label:'Goals',href:'/goals'}] } },
  { test: p => p.startsWith('/briefings'), room: { world:'mind', metaphor:'editorial-desk', eyebrow:'Briefings', title:'Briefings', statement:'Prepare for the day, close it clearly, and review longer patterns without dashboard overload.', insight:'Morning prepares. Evening reflects. Weekly and monthly reviews reveal direction.', actionLabel:'Open Briefings', actionHref:'/briefings', context:[{label:'Today',href:'/today'},{label:'Brain',href:'/brain'},{label:'Timeline',href:'/timeline'}] } },
  { test: p => p.startsWith('/wellness') || p.startsWith('/maintenance') || p.startsWith('/symptoms') || p.startsWith('/sleep') || p.startsWith('/medications'), room: { world:'wellness', metaphor:'wellness-garden', eyebrow:'Care', title:'Wellness', statement:'Listen to your body, organize care and see the signals that matter together.', insight:'Sleep, symptoms, medication, movement, food and routines should feed one wellness picture.', actionLabel:'Check In', actionHref:'/wellness', context:[{label:'Fitness',href:'/fitness'},{label:'Food',href:'/food'},{label:'Routines',href:'/routines'}] } },
  { test: p => p.startsWith('/fitness') || p.startsWith('/workout-studio'), room: { world:'wellness', metaphor:'movement-studio', eyebrow:'Movement', title:'Fitness', statement:'Train with structure while keeping energy, recovery and consistency in view.', insight:'Workouts can feed wellness, habits, calendar, debriefs and progress without duplicate logging.', actionLabel:'Start Workout', actionHref:'/fitness', context:[{label:'Wellness',href:'/wellness'},{label:'Habits',href:'/habits'},{label:'Food',href:'/food'}] } },
  { test: p => p.startsWith('/food'), room: { world:'wellness', metaphor:'kitchen', eyebrow:'Nourish', title:'Food & Nutrition', statement:'Plan meals, groceries, recipes and pantry needs as one practical workflow.', insight:'Meals should connect directly to groceries and prep, not exist as isolated cards.', actionLabel:'Open Meal Plan', actionHref:'/food', context:[{label:'Wellness',href:'/wellness'},{label:'Routines',href:'/routines'},{label:'Home',href:'/home'}] } },
  { test: p => p.startsWith('/habits'), room: { world:'wellness', metaphor:'habit-grid', eyebrow:'Consistency', title:'Habits', statement:'Track the small repeated actions that create your larger life patterns.', insight:'Habits become more useful when Glow can compare consistency with mood, energy and outcomes.', actionLabel:'Review Habits', actionHref:'/habits', context:[{label:'Routines',href:'/routines'},{label:'Wellness',href:'/wellness'},{label:'Observations',href:'/observations'}] } },
  { test: p => p.startsWith('/routines'), room: { world:'wellness', metaphor:'ritual-library', eyebrow:'Systems', title:'Routines', statement:'Build repeatable sequences for mornings, evenings, workouts, beauty, hair and resets.', insight:'Routines are reusable systems. Habits are individual repeated behaviors.', actionLabel:'Open Routines', actionHref:'/routines', context:[{label:'Habits',href:'/habits'},{label:'Beauty',href:'/beauty'},{label:'Home',href:'/home'}] } },
  { test: p => p.startsWith('/beauty/lab'), room: { world:'beauty', metaphor:'laboratory', eyebrow:'Beauty Intelligence', title:'Beauty Lab', statement:'Understand products, ingredients, compatibility, reactions and results.', insight:'Beauty Lab explains what you use. Beauty OS organizes what you do.', actionLabel:'Open Beauty', actionHref:'/beauty', context:[{label:'Beauty',href:'/beauty'},{label:'Hair',href:'/hair'},{label:'Wellness',href:'/wellness'}] } },
  { test: p => p.startsWith('/beauty'), room: { world:'beauty', metaphor:'vanity', eyebrow:'Care', title:'Beauty OS', statement:'Organize skincare, makeup, body care, fragrance, tools and progress beautifully.', insight:'Appointments, products, routines and progress should share one beauty timeline.', actionLabel:'Today’s Routine', actionHref:'/beauty', context:[{label:'Beauty Lab',href:'/beauty/lab'},{label:'Hair',href:'/hair'},{label:'Calendar',href:'/calendar'}] } },
  { test: p => p.startsWith('/hair'), room: { world:'beauty', metaphor:'hair-studio', eyebrow:'Hair', title:'Hair Studio', statement:'Track wash cycles, treatments, styling, appointments, goals and hair progress.', insight:'Hair care works best as a lifecycle, not a list of disconnected products.', actionLabel:'Open Hair Plan', actionHref:'/hair', context:[{label:'Beauty',href:'/beauty'},{label:'Routines',href:'/routines'},{label:'Calendar',href:'/calendar'}] } },
  { test: p => p.startsWith('/finance/brain'), room: { world:'money', metaphor:'financial-study', eyebrow:'Money Intelligence', title:'Financial Brain', statement:'Understand your position, tradeoffs, priorities and future options.', insight:'Financial Brain should reason over the same accounts, spending, goals and forecasts shown elsewhere.', actionLabel:'Open Finance', actionHref:'/finance', context:[{label:'Goals',href:'/goals'},{label:'Finance',href:'/finance'},{label:'Graph',href:'/graph'}] } },
  { test: p => p.startsWith('/finance') || p.startsWith('/spending') || p.startsWith('/subscriptions') || p.startsWith('/forecast') || p.startsWith('/transactions'), room: { world:'money', metaphor:'financial-journal', eyebrow:'Money', title:'Financial Overview', statement:'See accounts, spending, subscriptions, cash flow and upcoming obligations in one calm system.', insight:'Transactions are source data. Spending, subscriptions and forecasts are views of the same financial picture.', actionLabel:'Open Financial Brain', actionHref:'/finance/brain', context:[{label:'Goals',href:'/goals'},{label:'Financial Brain',href:'/finance/brain'},{label:'Notices',href:'/notices'}] } },
  { test: p => p.startsWith('/goals'), room: { world:'money', metaphor:'destination-wall', eyebrow:'Direction', title:'Goals', statement:'Turn long-term desires into visible destinations, milestones and next steps.', insight:'Goals should pull their progress from the real tasks, projects and financial actions that move them.', actionLabel:'Review Goals', actionHref:'/goals', context:[{label:'Projects',href:'/projects'},{label:'Finance',href:'/finance'},{label:'Planning',href:'/planning'}] } },
  { test: p => p.startsWith('/creative-studio'), room: { world:'work', metaphor:'creative-studio', eyebrow:'Create', title:'Creative Studio', statement:'Your ideas, brand work, moodboards and presentation-ready creative direction in one studio.', insight:'Creative Studio is a visual layer of Projects, not a separate project database.', actionLabel:'Open Projects', actionHref:'/projects', context:[{label:'Projects',href:'/projects'},{label:'Notes',href:'/notes'},{label:'Memory',href:'/memory'}] } },
  { test: p => p.startsWith('/projects'), room: { world:'work', metaphor:'project-studio', eyebrow:'Build', title:'Projects', statement:'Run active projects, milestones, files, decisions and next actions from one hub.', insight:'Deep dives should use the same project object shown on Home, Goals and Creative Studio.', actionLabel:'Open Creative Studio', actionHref:'/creative-studio', context:[{label:'Creative Studio',href:'/creative-studio'},{label:'Goals',href:'/goals'},{label:'Work',href:'/work'}] } },
  { test: p => p.startsWith('/work') || p.startsWith('/applications') || p.startsWith('/interviews') || p.startsWith('/interview-prep'), room: { world:'work', metaphor:'career-studio', eyebrow:'Career', title:'Career & Work', statement:'Organize applications, interviews, opportunities, contacts and professional goals.', insight:'A job opportunity can appear in Work, Calendar, Briefings and Interview Prep without being entered repeatedly.', actionLabel:'Open Work', actionHref:'/work', context:[{label:'Projects',href:'/projects'},{label:'Calendar',href:'/calendar'},{label:'Connections',href:'/connections'}] } },
  { test: p => p.startsWith('/home'), room: { world:'home', metaphor:'sanctuary', eyebrow:'Home', title:'Home', statement:'Care for your space, routines, supplies and the things that make home feel calm.', insight:'Home can organize physical spaces while Life World shows how every life domain connects.', actionLabel:'Open All Rooms', actionHref:'/all-rooms', context:[{label:'All Rooms',href:'/all-rooms'},{label:'Life World',href:'/world'},{label:'Routines',href:'/routines'}] } },
  { test: p => p.startsWith('/closet'), room: { world:'home', metaphor:'wardrobe', eyebrow:'Style', title:'Closet', statement:'Know what you own, build outfits and understand your personal style over time.', insight:'Closet can connect outfits to travel, weather, events and shopping decisions.', actionLabel:'Open Closet', actionHref:'/closet', context:[{label:'Travel',href:'/world?room=travel'},{label:'Calendar',href:'/calendar'},{label:'Home',href:'/home'}] } },
  { test: p => p.startsWith('/world') || p.startsWith('/life-world') || p.startsWith('/travel'), room: { world:'home', metaphor:'life-atrium', eyebrow:'Your World', title:'Life World', statement:'Step back and see the major rooms of your life as one connected personal world.', insight:'World is the spatial overview. All Rooms is the fast directory. Neither replaces the source pages.', actionLabel:'Open All Rooms', actionHref:'/all-rooms', context:[{label:'Home',href:'/home'},{label:'All Rooms',href:'/all-rooms'},{label:'Travel',href:'/world?room=travel'}] } },
  { test: p => p.startsWith('/all-rooms'), room: { world:'home', metaphor:'room-directory', eyebrow:'Directory', title:'All Rooms', statement:'Every part of Glow OS, organized into clear life domains.', insight:'Use this as the complete navigation index when you know where you want to go.', actionLabel:'Enter Life World', actionHref:'/world', context:[{label:'Today',href:'/dashboard'},{label:'Brain',href:'/brain'},{label:'Wellness',href:'/wellness'}] } },
  { test: p => p.startsWith('/focus') || p.startsWith('/ambient'), room: { world:'system', metaphor:'focus-chamber', eyebrow:'Special Mode', title:'Deep Focus', statement:'Reduce distraction and give one decision or task your full attention.', insight:'Modes change how Glow behaves temporarily. They are not separate databases.', actionLabel:'Start Focus', actionHref:'/focus?focus=1', context:[{label:'Tasks',href:'/tasks'},{label:'Projects',href:'/projects'},{label:'Brain',href:'/brain'}] } },
  { test: p => p.startsWith('/gmail'), room: { world:'system', metaphor:'inbox-bridge', eyebrow:'Integration', title:'Gmail', statement:'Bring important email context into Glow without turning Glow into another inbox.', insight:'Email intelligence should link messages to the people, projects, applications and tasks they affect.', actionLabel:'Open Gmail', actionHref:'/gmail', context:[{label:'Work',href:'/work'},{label:'Connections',href:'/connections'},{label:'Tasks',href:'/tasks'}] } },
  { test: p => p.startsWith('/import') || p.startsWith('/intake') || p.startsWith('/add-anything'), room: { world:'system', metaphor:'intake-dock', eyebrow:'Capture', title:'Add Anything', statement:'Drop in files, screenshots, links, notes or voice and let Glow route them to the right place.', insight:'Capture once, then organize into the real source system after review.', actionLabel:'Add Anything', actionHref:'/intake', context:[{label:'Inbox',href:'/inbox'},{label:'Brain',href:'/brain'},{label:'Import',href:'/import'}] } },
  { test: p => p.startsWith('/connections') || p.startsWith('/brain-connection'), room: { world:'system', metaphor:'connection-hub', eyebrow:'Connections', title:'Connections', statement:'Connect the services, people and data sources that make Glow useful.', insight:'Connections supply data. Glow decides where it belongs only after the appropriate permissions and review.', actionLabel:'Manage Connections', actionHref:'/connections', context:[{label:'Gmail',href:'/gmail'},{label:'Import',href:'/import'},{label:'Settings',href:'/settings'}] } },
  { test: p => p.startsWith('/notices'), room: { world:'system', metaphor:'notice-board', eyebrow:'Awareness', title:'Notices', statement:'Important updates, alerts and intelligence surfaced without constant noise.', insight:'A notice should be actionable, dismissible and tied to evidence.', actionLabel:'Review Notices', actionHref:'/notices', context:[{label:'Brain',href:'/brain'},{label:'Calendar',href:'/calendar'},{label:'Settings',href:'/settings'}] } },
  { test: p => p.startsWith('/settings') || p.startsWith('/system-overview'), room: { world:'system', metaphor:'control-room', eyebrow:'System', title:'System Overview', statement:'Manage your Glow OS environment, permissions, preferences and connected systems.', insight:'System health should describe real integrations and capabilities, never invented status.', actionLabel:'Open Settings', actionHref:'/settings', context:[{label:'Connections',href:'/connections'},{label:'Import',href:'/import'},{label:'Notices',href:'/notices'}] } },
];

const fallback: WorldArchitecture = {
  world:'system', metaphor:'glow-room', eyebrow:'Glow OS', title:'Glow OS',
  statement:'A connected personal operating system for planning, care, work, memory and everyday life.',
  insight:'Each room should use shared source data instead of creating disconnected copies.',
  actionLabel:'Open Home', actionHref:'/dashboard',
  context:[{label:'All Rooms',href:'/all-rooms'},{label:'Brain',href:'/brain'},{label:'Settings',href:'/settings'}],
};

export function getWorldArchitecture(pathname: string): WorldArchitecture {
  return rooms.find(item => item.test(pathname))?.room ?? fallback;
}
