export type WorldKey = 'today' | 'life' | 'mind' | 'wellness' | 'beauty' | 'money' | 'work' | 'home';

export type WorldArchitecture = {
  world: WorldKey;
  title: string;
  eyebrow: string;
  statement: string;
  insight: string;
  actionLabel: string;
  actionHref: string;
  metaphor: 'foyer' | 'editorial' | 'receding' | 'report' | 'orb' | 'archive' | 'timeline' | 'signal' | 'desk' | 'tabletop' | 'journey' | 'forecast' | 'dressing-room' | 'laboratory' | 'studio' | 'ritual' | 'kitchen' | 'sanctuary' | 'landscape' | 'time-wall' | 'workbench' | 'triggers' | 'career' | 'floorplan' | 'notices' | 'graph' | 'mail' | 'intake' | 'connections' | 'notebook';
  context: Array<{ label: string; href: string }>;
};

const registry: Array<{ match: (pathname: string) => boolean; config: WorldArchitecture }> = [
  { match: p => p.startsWith('/beauty/lab'), config: { world:'beauty', title:'Beauty Lab', eyebrow:'BEAUTY / LAB', statement:'Understand what you use, how it behaves, and what belongs together.', insight:'Glow keeps ingredients, compatibility, reactions and timing connected so your routine can stay simple.', actionLabel:'Open Beauty', actionHref:'/beauty', metaphor:'laboratory', context:[{label:'Beauty',href:'/beauty'},{label:'Hair',href:'/hair'},{label:'Wellness',href:'/wellness'}] } },
  { match: p => p.startsWith('/finance/brain'), config: { world:'money', title:'Financial Brain', eyebrow:'MONEY / FORECAST', statement:'See what happens next, not only what already happened.', insight:'Glow can connect cash flow, goals and upcoming decisions into one forward-looking view.', actionLabel:'Open Finance', actionHref:'/finance', metaphor:'forecast', context:[{label:'Finance',href:'/finance'},{label:'Goals',href:'/goals'},{label:'Projects',href:'/projects'}] } },
  { match: p => p.startsWith('/briefings/evening'), config: { world:'mind', title:'Evening Debrief', eyebrow:'GLOW / CLOSE THE DAY', statement:'Close the day with clarity. Carry forward only what matters.', insight:'Glow separates what is finished, what needs attention and what should deliberately move forward.', actionLabel:'Preview Tomorrow', actionHref:'/tomorrow', metaphor:'receding', context:[{label:'Morning Brief',href:'/briefings'},{label:'Weekly',href:'/briefings/weekly'},{label:'Tomorrow',href:'/tomorrow'}] } },
  { match: p => p.startsWith('/briefings/weekly'), config: { world:'mind', title:'Weekly Debrief', eyebrow:'GLOW / WEEK IN REVIEW', statement:'See the week as a story of movement, energy, choices and momentum.', insight:'Glow surfaces repeated patterns and meaningful changes instead of turning your week into a spreadsheet.', actionLabel:'Open Today', actionHref:'/today', metaphor:'report', context:[{label:'Monthly',href:'/briefings/monthly'},{label:'Observations',href:'/observations'},{label:'Goals',href:'/goals'}] } },
  { match: p => p.startsWith('/briefings/monthly'), config: { world:'mind', title:'Monthly Debrief', eyebrow:'GLOW / MONTH IN REVIEW', statement:'Zoom out far enough to notice what your days are becoming.', insight:'Glow connects milestones, money, health, projects and memories into a quieter monthly narrative.', actionLabel:'Open Goals', actionHref:'/goals', metaphor:'report', context:[{label:'Weekly',href:'/briefings/weekly'},{label:'Timeline',href:'/timeline'},{label:'Memory',href:'/memory'}] } },
  { match: p => p.startsWith('/briefings'), config: { world:'mind', title:'Morning Brief', eyebrow:'GLOW / MORNING', statement:'Know what matters before the day starts asking for your attention.', insight:'Glow prioritizes your day, schedule, body, meals and alerts into one calm editorial briefing.', actionLabel:'Open Today', actionHref:'/today', metaphor:'editorial', context:[{label:'Today',href:'/today'},{label:'Calendar',href:'/calendar'},{label:'Evening Debrief',href:'/briefings/evening'}] } },
  { match: p => p.startsWith('/dashboard') || p.startsWith('/today'), config: { world:'today', title:'Today', eyebrow:'YOUR LIFE / NOW', statement:'One calm foyer for what is happening now, what comes next and what can wait.', insight:'Glow keeps the first view intentionally small: your next move, your day shape and the life areas asking for attention.', actionLabel:'Plan My Day', actionHref:'/planning', metaphor:'foyer', context:[{label:'Calendar',href:'/calendar'},{label:'Tasks',href:'/tasks'},{label:'Morning Brief',href:'/briefings'}] } },
  { match: p => p.startsWith('/brain/connections') || p.startsWith('/graph'), config: { world:'mind', title:'Graph', eyebrow:'MIND / CONNECTIONS', statement:'See how the people, places, projects, habits and memories in your life connect.', insight:'Glow treats your information as relationships, not isolated records.', actionLabel:'Open Brain', actionHref:'/brain', metaphor:'graph', context:[{label:'Brain',href:'/brain'},{label:'Memory',href:'/memory'},{label:'Timeline',href:'/timeline'}] } },
  { match: p => p.startsWith('/brain'), config: { world:'mind', title:'Brain', eyebrow:'MIND / INTELLIGENCE', statement:'A personal intelligence chamber built around context, patterns, memory and decisions.', insight:'Ask what to do right now and Glow can reason across time, priorities, routines and connected life context.', actionLabel:'Open Observations', actionHref:'/observations', metaphor:'orb', context:[{label:'Memory',href:'/memory'},{label:'Observations',href:'/observations'},{label:'Timeline',href:'/timeline'}] } },
  { match: p => p.startsWith('/memory'), config: { world:'mind', title:'Memory', eyebrow:'MIND / ARCHIVE', statement:'Your personal archive of moments, people, places, projects, ideas and documents.', insight:'Glow preserves source, date, context and confidence so memory stays useful and correctable.', actionLabel:'Open Timeline', actionHref:'/timeline', metaphor:'archive', context:[{label:'Timeline',href:'/timeline'},{label:'Graph',href:'/graph'},{label:'Brain',href:'/brain'}] } },
  { match: p => p.startsWith('/timeline'), config: { world:'life', title:'Timeline', eyebrow:'LIFE / THROUGH TIME', statement:'Move from today to a lifetime without losing the meaning between the moments.', insight:'Glow lets events become simpler as you zoom out, while important chapters remain visible.', actionLabel:'Open Memory', actionHref:'/memory', metaphor:'timeline', context:[{label:'Memory',href:'/memory'},{label:'Goals',href:'/goals'},{label:'Life World',href:'/world'}] } },
  { match: p => p.startsWith('/observations'), config: { world:'mind', title:'Observations', eyebrow:'MIND / QUIET SIGNALS', statement:'The useful things Glow noticed without turning your life into an alert feed.', insight:'Every observation should show evidence, why it matters, confidence and a clear way to correct Glow.', actionLabel:'Open Brain', actionHref:'/brain', metaphor:'signal', context:[{label:'Brain',href:'/brain'},{label:'Notices',href:'/notices'},{label:'Memory',href:'/memory'}] } },
  { match: p => p.startsWith('/concierge'), config: { world:'life', title:'Concierge', eyebrow:'LIFE / PRIVATE DESK', statement:'A private lifestyle desk for planning, reservations, shopping, travel, errands and outreach.', insight:'Glow keeps requests attached to the decisions, people and dates that make them actionable.', actionLabel:'Open Requests', actionHref:'/inbox', metaphor:'desk', context:[{label:'Inbox',href:'/inbox'},{label:'Calendar',href:'/calendar'},{label:'Gmail',href:'/gmail'}] } },
  { match: p => p.startsWith('/creative-studio') || p.startsWith('/projects'), config: { world:'work', title:'Creative Studio', eyebrow:'WORK + CREATE / STUDIO', statement:'A tactile creative tabletop for projects, moodboards, ideas, research and experiments.', insight:'Glow keeps the active project and next meaningful action in front while deeper materials stay one layer away.', actionLabel:'Open Projects', actionHref:'/projects', metaphor:'tabletop', context:[{label:'Work',href:'/work'},{label:'Goals',href:'/goals'},{label:'Resources',href:'/resources'}] } },
  { match: p => p.startsWith('/goals'), config: { world:'money', title:'Goals', eyebrow:'MONEY + LIFE / JOURNEYS', statement:'Treat each goal as a destination with a path, not a percentage bar.', insight:'Glow connects destination, why, milestones, next move, obstacles and supporting habits into one journey.', actionLabel:'Open Projects', actionHref:'/projects', metaphor:'journey', context:[{label:'Finance',href:'/finance'},{label:'Projects',href:'/projects'},{label:'Habits',href:'/habits'}] } },
  { match: p => p.startsWith('/finance') || p.startsWith('/money'), config: { world:'money', title:'Money', eyebrow:'MONEY / CURRENT POSITION', statement:'A calm, analytical view of what is true now and what your choices change next.', insight:'Glow keeps spending, savings, cash flow and upcoming decisions connected without making the room feel like a bank portal.', actionLabel:'Open Financial Brain', actionHref:'/finance/brain', metaphor:'forecast', context:[{label:'Financial Brain',href:'/finance/brain'},{label:'Goals',href:'/goals'},{label:'Notices',href:'/notices'}] } },
  { match: p => p.startsWith('/beauty'), config: { world:'beauty', title:'Beauty', eyebrow:'BEAUTY / DRESSING ROOM', statement:'Today’s routine presented like a curated dressing room, not an inventory dashboard.', insight:'Glow brings forward only what you are doing now, tonight and at the next treatment point.', actionLabel:'Open Beauty Lab', actionHref:'/beauty/lab', metaphor:'dressing-room', context:[{label:'Beauty Lab',href:'/beauty/lab'},{label:'Hair',href:'/hair'},{label:'Wellness',href:'/wellness'}] } },
  { match: p => p.startsWith('/hair'), config: { world:'beauty', title:'Hair', eyebrow:'BEAUTY / HAIR STUDIO', statement:'Know your current hair phase, what comes next and how the cycle is changing over time.', insight:'Glow keeps wash cycle, treatments, heat, growth and appointments aligned around the next useful action.', actionLabel:'Open Beauty', actionHref:'/beauty', metaphor:'studio', context:[{label:'Beauty',href:'/beauty'},{label:'Beauty Lab',href:'/beauty/lab'},{label:'Calendar',href:'/calendar'}] } },
  { match: p => p.startsWith('/maintenance'), config: { world:'wellness', title:'Medications & Supplements', eyebrow:'WELLNESS / CARE RHYTHM', statement:'A calm, trustworthy place for today’s care rhythm, refills, adherence and questions.', insight:'Glow keeps timing and follow-up visible while advanced history stays out of the first view.', actionLabel:'Open Wellness', actionHref:'/wellness', metaphor:'ritual', context:[{label:'Wellness',href:'/wellness'},{label:'Calendar',href:'/calendar'},{label:'Notes',href:'/notes'}] } },
  { match: p => p.startsWith('/food'), config: { world:'wellness', title:'Food & Nutrition', eyebrow:'WELLNESS / KITCHEN', statement:'A kitchen editorial for today’s meals, planning, recipes, groceries and what you already have.', insight:'Glow can use schedule and available ingredients to make food planning feel practical instead of clinical.', actionLabel:'Open Meal Plan', actionHref:'/food', metaphor:'kitchen', context:[{label:'Wellness',href:'/wellness'},{label:'Fitness',href:'/fitness'},{label:'Reminders',href:'/reminders'}] } },
  { match: p => p.startsWith('/wellness'), config: { world:'wellness', title:'Wellness', eyebrow:'WELLNESS / QUIET ROOM', statement:'A quieter room for checking in with energy, mood, sleep, hydration, symptoms and recovery.', insight:'Glow waits for your check-in before crowding the page with recommendations.', actionLabel:'Open Fitness', actionHref:'/fitness', metaphor:'sanctuary', context:[{label:'Fitness',href:'/fitness'},{label:'Food',href:'/food'},{label:'Beauty',href:'/beauty'}] } },
  { match: p => p.startsWith('/fitness'), config: { world:'wellness', title:'Fitness', eyebrow:'WELLNESS / MOVEMENT', statement:'A kinetic training landscape centered on today’s workout and body readiness.', insight:'Glow can adapt what comes next around energy, soreness, recovery, schedule and equipment.', actionLabel:'Open Wellness', actionHref:'/wellness', metaphor:'landscape', context:[{label:'Wellness',href:'/wellness'},{label:'Food',href:'/food'},{label:'Habits',href:'/habits'}] } },
  { match: p => p.startsWith('/calendar'), config: { world:'life', title:'Calendar', eyebrow:'LIFE / TIME WALL', statement:'Treat time like architecture: dense periods compress, open time creates space.', insight:'Glow highlights protected focus windows, transitions and overload rather than adding more calendar chrome.', actionLabel:'Open Planning', actionHref:'/planning', metaphor:'time-wall', context:[{label:'Planning',href:'/planning'},{label:'Tasks',href:'/tasks'},{label:'Work',href:'/work'}] } },
  { match: p => p.startsWith('/tasks') || p.startsWith('/planning'), config: { world:'life', title:p.startsWith('/planning')?'Planning':'Tasks', eyebrow:'LIFE / WORKBENCH', statement:'A workbench where every task has context, purpose and an obvious next action.', insight:'Glow uses Now / Next / Later to reduce the amount you need to scan before starting.', actionLabel:'Open Calendar', actionHref:'/calendar', metaphor:'workbench', context:[{label:'Calendar',href:'/calendar'},{label:'Routines',href:'/routines'},{label:'Reminders',href:'/reminders'}] } },
  { match: p => p.startsWith('/reminders'), config: { world:'life', title:'Reminders', eyebrow:'LIFE / CONTEXT TRIGGERS', statement:'Remember things by the moment they become useful: time, place, person, routine or trigger.', insight:'Glow keeps reminders connected to context so they appear as help, not noise.', actionLabel:'Open Tasks', actionHref:'/tasks', metaphor:'triggers', context:[{label:'Tasks',href:'/tasks'},{label:'Calendar',href:'/calendar'},{label:'Connections',href:'/connections'}] } },
  { match: p => p.startsWith('/work'), config: { world:'work', title:'Work', eyebrow:'WORK + CREATE / CAREER', statement:'A career studio for your current work, opportunities, applications, contacts and next moves.', insight:'Glow keeps opportunities in a pipeline and connects follow-ups to the people and dates behind them.', actionLabel:'Open Creative Studio', actionHref:'/creative-studio', metaphor:'career', context:[{label:'Creative Studio',href:'/creative-studio'},{label:'Gmail',href:'/gmail'},{label:'Calendar',href:'/calendar'}] } },
  { match: p => p.startsWith('/home'), config: { world:'home', title:'Home', eyebrow:'HOME / DIGITAL HOUSE', statement:'Navigate the home as rooms, with tasks, inventory, routines, projects and reminders living where they belong.', insight:'Glow keeps household context spatial so maintenance and routines feel easier to locate.', actionLabel:'Open All Rooms', actionHref:'/all-rooms', metaphor:'floorplan', context:[{label:'All Rooms',href:'/all-rooms'},{label:'Reminders',href:'/reminders'},{label:'Resources',href:'/resources'}] } },
  { match: p => p.startsWith('/all-rooms') || p.startsWith('/world'), config: { world:'home', title:p.startsWith('/all-rooms')?'All Rooms':'Life World', eyebrow:'LIFE WORLD / ARCHITECTURE', statement:'Enter your personal digital world through spaces instead of a wall of app destinations.', insight:'Life World can be immersive and cinematic while operational rooms remain calm, legible and fast.', actionLabel:'Open Today', actionHref:'/today', metaphor:'floorplan', context:[{label:'Today',href:'/today'},{label:'Home',href:'/home'},{label:'Timeline',href:'/timeline'}] } },
  { match: p => p.startsWith('/notices'), config: { world:'mind', title:'Notices', eyebrow:'MIND / ATTENTION', statement:'Needs You, Coming Up, Worth Knowing and Glow Noticed, without a wall of red alerts.', insight:'Glow separates urgency from information and keeps every meaningful notice connected to a real destination.', actionLabel:'Open Observations', actionHref:'/observations', metaphor:'notices', context:[{label:'Observations',href:'/observations'},{label:'Today',href:'/today'},{label:'Calendar',href:'/calendar'}] } },
  { match: p => p.startsWith('/gmail') || p.startsWith('/inbox'), config: { world:'work', title:p.startsWith('/gmail')?'Gmail':'Inbox', eyebrow:'WORK + CREATE / COMMUNICATION', statement:'An intelligence layer above communication: what needs reply, what matters, what you are waiting on.', insight:'Glow extracts decisions, dates, tasks and follow-ups instead of recreating an email client.', actionLabel:'Open Work', actionHref:'/work', metaphor:'mail', context:[{label:'Work',href:'/work'},{label:'Tasks',href:'/tasks'},{label:'Calendar',href:'/calendar'}] } },
  { match: p => p.startsWith('/import') || p.startsWith('/intake'), config: { world:'life', title:'Import', eyebrow:'LIFE / INTAKE ROOM', statement:'Add anything, then let Glow help determine what it is and where it belongs.', insight:'Files, screenshots, notes, links and receipts stay in an intake flow until you confirm their destination.', actionLabel:'Open Connections', actionHref:'/connections', metaphor:'intake', context:[{label:'Connections',href:'/connections'},{label:'Inbox',href:'/inbox'},{label:'Resources',href:'/resources'}] } },
  { match: p => p.startsWith('/connections'), config: { world:'life', title:'Connections', eyebrow:'SYSTEM / CONNECTION MAP', statement:'See what is connected, when it last synced, what Glow can access and what remains private.', insight:'Connection status and permissions should be understandable before you ever need a settings screen.', actionLabel:'Open Import', actionHref:'/import', metaphor:'connections', context:[{label:'Gmail',href:'/gmail'},{label:'Calendar',href:'/calendar'},{label:'Import',href:'/import'}] } },
  { match: p => p.startsWith('/notes') || p.startsWith('/resources'), config: { world:'life', title:p.startsWith('/notes')?'Notes':'Resources', eyebrow:'LIFE / LIBRARY', statement:'A quiet library where writing, references and files stay easy to find and return to.', insight:'Glow keeps related people, projects and dates nearby without cluttering the core reading and writing experience.', actionLabel:'Open Search', actionHref:'/search', metaphor:'notebook', context:[{label:'Search',href:'/search'},{label:'Import',href:'/import'},{label:'Memory',href:'/memory'}] } },
];

const fallback: WorldArchitecture = { world:'life', title:'Glow OS', eyebrow:'PERSONAL DIGITAL WORLD', statement:'A calm architectural layer across the systems that run your life.', insight:'Glow keeps context, next actions and deeper power available without showing everything at once.', actionLabel:'Open Today', actionHref:'/today', metaphor:'foyer', context:[{label:'Today',href:'/today'},{label:'All Rooms',href:'/all-rooms'},{label:'Brain',href:'/brain'}] };

export function getWorldArchitecture(pathname: string): WorldArchitecture {
  return registry.find(entry => entry.match(pathname))?.config ?? fallback;
}
