'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { BookOpen, Check, ChevronRight, FlaskConical, Layers3, Package, Search, ShieldCheck, Sparkles } from 'lucide-react';

type Adoption='adopt'|'adapt'|'record'|'hold'|'reject';
type SourceItem={id:string;source:string;domain:string;statement:string;kind:'instruction'|'claim'|'product'|'framework';adoption:Adoption;safety?:string;sponsored?:boolean};
type Experiment={id:string;title:string;duration:string;metric:string;status:'idea'|'testing'|'keep'|'modify'|'drop'};
type RoutineTier={name:string;floor:string;standard:string;full:string};
type ProductState='mentioned'|'own'|'want'|'avoid';

type Persisted={adoption:Record<string,Adoption>;experiments:Experiment[];products:Record<string,ProductState>;reviewed:string[];query:string};

const seedSources:SourceItem[]=[
 {id:'closet-style',source:'Glow OS Closet & Fashion',domain:'Closet',statement:'Use inspiration to style what you already own before treating inspiration as a shopping list.',kind:'instruction',adoption:'adopt'},
 {id:'closet-buy',source:'Glow OS Closet & Fashion',domain:'Closet',statement:'Before buying, check lifestyle fit, long-term usefulness and whether the item works with pieces already owned.',kind:'framework',adoption:'adopt'},
 {id:'closet-repair',source:'Glow OS Closet & Fashion',domain:'Closet',statement:'Mend, alter, repair and upcycle items to extend wardrobe usefulness.',kind:'instruction',adoption:'adopt'},
 {id:'makeup-thin',source:'Glow OS Makeup',domain:'Makeup',statement:'For the supplied long-wear Douyin look, use thin complexion layers and target dark-circle coverage rather than automatically covering the whole under-eye.',kind:'instruction',adoption:'adapt'},
 {id:'makeup-products',source:'Glow OS Makeup',domain:'Makeup',statement:'A product mention or sponsored demonstration is not automatically a recommendation or shopping need.',kind:'framework',adoption:'adopt',sponsored:true},
 {id:'gua-claim',source:'Glow OS Gua Sha',domain:'Facial Practice',statement:'Creator descriptions of lifting, lymphatic effects or long-term structural change must remain source claims rather than Glow medical facts.',kind:'claim',adoption:'hold',safety:'Appearance/health claim. Preserve attribution and avoid guaranteed outcomes.'},
 {id:'gua-order',source:'Glow OS Gua Sha',domain:'Facial Practice',statement:'Preserve the demonstrated routine order when converting a follow-along massage into guided steps.',kind:'instruction',adoption:'adopt'},
 {id:'finance-frameworks',source:'Glow OS Financial',domain:'Finance',statement:'Budget percentages and emergency-fund targets are frameworks that may differ by source and should remain selectable rather than universal rules.',kind:'framework',adoption:'adopt'},
 {id:'finance-action',source:'Glow OS Financial',domain:'Finance',statement:'Never claim that money moved, a bill was paid, or an account was changed unless a real connected action completed successfully.',kind:'framework',adoption:'adopt',safety:'Financial action truthfulness.'},
 {id:'identity',source:'Glow OS Info',domain:'Brain',statement:'Convert useful future-self, standards, proof and identity exercises into structured reflection rather than more task clutter.',kind:'instruction',adoption:'adopt'},
 {id:'bare-minimum',source:'Glow OS Info',domain:'Routines',statement:'Important routines should support a minimum viable version so a long routine does not become all-or-nothing.',kind:'instruction',adoption:'adopt'},
 {id:'dopamine',source:'Glow OS Info',domain:'Attention',statement:'Translate dopamine-detox language into an Attention Reset focused on cues, friction and intentional alternatives.',kind:'claim',adoption:'adapt',safety:'Avoid presenting simplified dopamine language as a biological detox.'},
];

const routineTiers:RoutineTier[]=[
 {name:'Getting ready',floor:'Use one saved outfit + essential grooming',standard:'Closet + hair + makeup plan',full:'Contextual outfit, hair, makeup, beauty prep and leave-time sequence'},
 {name:'Makeup',floor:'Complexion touch-up + brows + lip',standard:'Saved daily look',full:'Guided procedural look with voice and technique notes'},
 {name:'Facial practice',floor:'2-minute neck/jaw release',standard:'5-minute full-face practice',full:'10-minute chest → neck → scalp → jaw → face sequence'},
 {name:'Finance review',floor:'Check obligations and recorded position',standard:'Weekly spending + goal review',full:'Monthly close, forecast, plan and Financial Brain review'},
 {name:'Closet',floor:'Use a saved outfit',standard:'Glow builds from clean owned pieces',full:'Style Lab with inspiration translation, formulas and accessory pass'},
];

const productSeeds=['Foundation / complexion base','Aegyo-sal cream or shadow','Individual or strip lashes','Facial massage cream or lotion','Needle + thread / repair kit','Statement accessory','Financial learning resource'];
const statusLabels:Record<Adoption,string>={adopt:'Adopt',adapt:'Adapt',record:'Record',hold:'Hold',reject:'Reject'};

function loadState():Persisted{
 if(typeof window==='undefined')return {adoption:{},experiments:[],products:{},reviewed:[],query:''};
 try{const raw=localStorage.getItem('glow:knowledge-corpus:v1');if(raw){const parsed=JSON.parse(raw) as Partial<Persisted>;return {adoption:parsed.adoption??{},experiments:parsed.experiments??[],products:parsed.products??{},reviewed:parsed.reviewed??[],query:parsed.query??''}}}catch{}
 return {adoption:{},experiments:[],products:{},reviewed:[],query:''};
}

export function GlowCorpusSystem({compact=false}:{compact?:boolean}){
 const [tab,setTab]=useState<'knowledge'|'routines'|'products'|'experiments'|'sources'|'adoption'>('knowledge');
 const [state,setState]=useState<Persisted>({adoption:{},experiments:[],products:{},reviewed:[],query:''});
 const [hydrated,setHydrated]=useState(false);
 useEffect(()=>{setState(loadState());setHydrated(true)},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem('glow:knowledge-corpus:v1',JSON.stringify(state))}catch{}},[hydrated,state]);
 const sources=useMemo(()=>seedSources.map(item=>({...item,adoption:state.adoption[item.id]??item.adoption})),[state.adoption]);
 const shown=useMemo(()=>{const q=state.query.trim().toLowerCase();return q?sources.filter(x=>`${x.source} ${x.domain} ${x.statement} ${x.kind}`.toLowerCase().includes(q)):sources},[sources,state.query]);
 const reviewedCount=state.reviewed.length;
 const testing=state.experiments.filter(x=>x.status==='testing').length;
 function setAdoption(id:string,value:Adoption){setState(s=>({...s,adoption:{...s.adoption,[id]:value}}))}
 function toggleReviewed(id:string){setState(s=>({...s,reviewed:s.reviewed.includes(id)?s.reviewed.filter(x=>x!==id):[...s.reviewed,id]}))}
 function addExperiment(){const id=`exp-${Date.now()}`;setState(s=>({...s,experiments:[...s.experiments,{id,title:'New 7-day experiment',duration:'7 days',metric:'How it felt + whether it helped',status:'testing'}]}))}
 function setProduct(name:string,value:ProductState){setState(s=>({...s,products:{...s.products,[name]:value}}))}

 if(compact)return <section className="rounded-[26px] border border-white/65 bg-white/58 p-5 shadow-[0_24px_80px_rgba(63,48,54,.08)] backdrop-blur-xl sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[9px] uppercase tracking-[.2em] text-[#9c7f89]">Glow Knowledge Layer</p><h2 className="mt-2 font-serif text-2xl text-[#3f3438]">This room is connected to the source corpus.</h2><p className="mt-2 max-w-3xl text-[11px] leading-5 text-[#756870]">Source teaching, creator claims, Glow recommendations and your personal adoption remain separate. Nothing becomes a habit, purchase or fact merely because it appeared in a transcript.</p></div><Link href="/create/source-library" className="inline-flex min-h-10 items-center gap-2 rounded-full bg-[#493d42] px-4 text-[10px] text-white">Open Source Library <ChevronRight size={13}/></Link></div><div className="mt-4 grid gap-2 sm:grid-cols-4"><Metric label="Source decisions" value={sources.length}/><Metric label="Reviewed" value={reviewedCount}/><Metric label="Testing" value={testing}/><Metric label="Safety holds" value={sources.filter(x=>x.adoption==='hold').length}/></div></section>;

 return <div className="mx-auto max-w-[1480px] space-y-5 pb-28">
  <header className="overflow-hidden rounded-[34px] border border-white/70 bg-[radial-gradient(circle_at_12%_0%,rgba(255,242,247,.95),transparent_38%),radial-gradient(circle_at_90%_8%,rgba(235,238,255,.9),transparent_40%),linear-gradient(145deg,#fff,#f8f5f3)] p-6 shadow-[0_30px_100px_rgba(53,44,53,.1)] sm:p-9">
   <p className="text-[9px] uppercase tracking-[.22em] text-[#9b7d89]">Create · Source Library · Glow Knowledge Corpus</p><h1 className="mt-3 max-w-4xl font-serif text-[42px] leading-[.98] text-[#352e33] sm:text-[58px]">Turn big files into living Glow intelligence, without losing what the source actually said.</h1><p className="mt-4 max-w-3xl text-[12px] leading-6 text-[#746a70]">This layer keeps source statements traceable, separates claims from instructions, routes ideas into the right rooms, and lets you decide what becomes part of your real life.</p>
   <div className="mt-6 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Seed source decisions" value={sources.length}/><Metric label="Reviewed" value={reviewedCount}/><Metric label="Active experiments" value={testing}/><Metric label="Product mentions adopted" value={Object.values(state.products).filter(v=>v==='own'||v==='want').length}/></div>
  </header>
  <nav className="flex gap-2 overflow-x-auto rounded-[18px] border border-white/70 bg-white/55 p-2 backdrop-blur" aria-label="Knowledge corpus workspace">{([['knowledge','Knowledge'],['routines','Routine DNA'],['products','Products'],['experiments','Experiments'],['sources','Sources'],['adoption','Adoption']] as const).map(([key,label])=><button key={key} type="button" aria-pressed={tab===key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-full px-4 py-2 text-[10px] ${tab===key?'bg-[#433840] text-white':'bg-white/65 text-[#756871]'}`}>{label}</button>)}</nav>
  {tab==='knowledge'&&<section className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Panel title="Knowledge → life" subtitle="Imported information is useful only when Glow knows what kind of thing it is."><div className="grid gap-3 sm:grid-cols-2"><Principle icon={<BookOpen size={16}/>} title="Source teaching" text="Preserve wording, sequence and framing from the uploaded material."/><Principle icon={<ShieldCheck size={16}/>} title="Evidence boundary" text="Creator claims stay attributed. Health and money claims do not silently become facts."/><Principle icon={<Layers3 size={16}/>} title="Route, do not duplicate" text="One routine or product can appear in several rooms while keeping a single source record."/><Principle icon={<Sparkles size={16}/>} title="Personal adoption" text="Glow asks whether an idea is adopted, adapted, reference-only, held or rejected."/></div></Panel><Panel title="System destinations" subtitle="The corpus now has explicit homes."><div className="space-y-2 text-[10px] text-[#6f6269]">{[['Closet','/closet/style'],['Makeup','/makeup'],['Facial Practice','/beauty/facial-practice'],['Financial School','/finance/school'],['Financial Plan','/finance/plan'],['Identity','/brain/identity'],['Learning','/brain/learning'],['Maintenance','/life/maintenance'],['Digital Life','/life/digital']].map(([label,href])=><Link key={href} href={href} className="flex items-center justify-between rounded-[14px] border border-[#eee5e8] bg-white/65 px-3 py-3 hover:bg-white"><span>{label}</span><ChevronRight size={13}/></Link>)}</div></Panel></section>}
  {tab==='routines'&&<Panel title="Routine DNA" subtitle="Every important practice can have Floor, Standard and Full versions instead of becoming all-or-nothing."><div className="grid gap-3 lg:grid-cols-2">{routineTiers.map(r=><div key={r.name} className="rounded-[20px] border border-[#eee4e8] bg-white/62 p-4"><h3 className="font-serif text-xl text-[#493d43]">{r.name}</h3><Tier label="Floor" text={r.floor}/><Tier label="Standard" text={r.standard}/><Tier label="Full" text={r.full}/></div>)}</div></Panel>}
  {tab==='products'&&<Panel title="Product Library" subtitle="Mentioned does not mean recommended, verified, owned or worth buying."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{productSeeds.map(name=><div key={name} className="rounded-[18px] border border-[#eee4e8] bg-white/62 p-4"><div className="flex items-center gap-2"><Package size={14}/><strong className="text-[11px] text-[#55484f]">{name}</strong></div><select value={state.products[name]??'mentioned'} onChange={e=>setProduct(name,e.target.value as ProductState)} className="mt-3 w-full rounded-[12px] border border-[#e7dde1] bg-white px-3 py-2 text-[10px]"><option value="mentioned">Mentioned only</option><option value="own">I own this</option><option value="want">Wishlist</option><option value="avoid">Do not recommend</option></select></div>)}</div></Panel>}
  {tab==='experiments'&&<Panel title="Experiment Mode" subtitle="Try a behavior before promoting it into a permanent habit."><button type="button" onClick={addExperiment} className="mb-4 inline-flex min-h-10 items-center gap-2 rounded-full bg-[#493d42] px-4 text-[10px] text-white"><FlaskConical size={13}/>Start 7-day experiment</button>{state.experiments.length?<div className="space-y-3">{state.experiments.map(exp=><div key={exp.id} className="rounded-[18px] border border-[#eee4e8] bg-white/62 p-4"><input value={exp.title} onChange={e=>setState(s=>({...s,experiments:s.experiments.map(x=>x.id===exp.id?{...x,title:e.target.value}:x)}))} className="w-full bg-transparent font-serif text-xl text-[#493d43] outline-none"/><div className="mt-2 grid gap-2 sm:grid-cols-3"><input value={exp.duration} onChange={e=>setState(s=>({...s,experiments:s.experiments.map(x=>x.id===exp.id?{...x,duration:e.target.value}:x)}))} className="rounded-[10px] border border-[#e9dfe3] bg-white px-3 py-2 text-[10px]"/><input value={exp.metric} onChange={e=>setState(s=>({...s,experiments:s.experiments.map(x=>x.id===exp.id?{...x,metric:e.target.value}:x)}))} className="rounded-[10px] border border-[#e9dfe3] bg-white px-3 py-2 text-[10px]"/><select value={exp.status} onChange={e=>setState(s=>({...s,experiments:s.experiments.map(x=>x.id===exp.id?{...x,status:e.target.value as Experiment['status']}:x)}))} className="rounded-[10px] border border-[#e9dfe3] bg-white px-3 py-2 text-[10px]"><option value="idea">Idea</option><option value="testing">Testing</option><option value="keep">Keep</option><option value="modify">Modify</option><option value="drop">Drop</option></select></div></div>)}</div>:<Empty text="No experiments yet. Use this for capsule-wardrobe trials, attention resets, finance tracking periods or routine changes before making them permanent."/>}</Panel>}
  {tab==='sources'&&<Panel title="Search the corpus" subtitle="Search only the structured source decisions currently imported into this build."><div className="relative mb-4"><Search size={14} className="absolute left-3 top-3 text-[#9b8a92]"/><input value={state.query} onChange={e=>setState(s=>({...s,query:e.target.value}))} placeholder="Search source, domain, claim or technique…" className="w-full rounded-[14px] border border-[#e9dfe3] bg-white/80 py-2.5 pl-9 pr-3 text-[11px] outline-none"/></div><div className="space-y-3">{shown.map(item=><SourceCard key={item.id} item={item} reviewed={state.reviewed.includes(item.id)} onReviewed={()=>toggleReviewed(item.id)} onAdoption={value=>setAdoption(item.id,value)}/>)}</div></Panel>}
  {tab==='adoption'&&<Panel title="What has actually been adopted?" subtitle="Reading is not the same as changing your life."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{(['adopt','adapt','record','hold','reject'] as Adoption[]).map(value=><Metric key={value} label={statusLabels[value]} value={sources.filter(x=>x.adoption===value).length}/>)}</div><p className="mt-4 text-[10px] leading-5 text-[#766970]">This count reflects the structured seed decisions in the current corpus layer, not every sentence in every PDF. Additional imports can be added without changing the distinction between source material and personal adoption.</p></Panel>}
 </div>;
}

function SourceCard({item,reviewed,onReviewed,onAdoption}:{item:SourceItem;reviewed:boolean;onReviewed:()=>void;onAdoption:(v:Adoption)=>void}){return <article className="rounded-[20px] border border-[#ede3e7] bg-white/65 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[8px] uppercase tracking-[.15em] text-[#a38792]">{item.domain} · {item.kind}</p><p className="mt-1 text-[9px] text-[#9b8c93]">{item.source}{item.sponsored?' · sponsorship/creator-product context present':''}</p></div><button type="button" onClick={onReviewed} className={`inline-flex min-h-9 items-center gap-1 rounded-full px-3 text-[9px] ${reviewed?'bg-[#e8f0e5] text-[#60735d]':'border border-[#e8dde2] bg-white text-[#756971]'}`}><Check size={12}/>{reviewed?'Reviewed':'Mark reviewed'}</button></div><p className="mt-3 text-[11px] leading-5 text-[#584c52]">{item.statement}</p>{item.safety&&<p className="mt-3 rounded-[12px] bg-[#fff5e8] px-3 py-2 text-[9px] leading-4 text-[#876a42]">Safety boundary: {item.safety}</p>}<div className="mt-3 flex flex-wrap gap-1.5">{(['adopt','adapt','record','hold','reject'] as Adoption[]).map(value=><button key={value} type="button" onClick={()=>onAdoption(value)} aria-pressed={item.adoption===value} className={`rounded-full px-2.5 py-1.5 text-[8px] ${item.adoption===value?'bg-[#4b3f45] text-white':'border border-[#e9dfe3] bg-white text-[#7a6d74]'}`}>{statusLabels[value]}</button>)}</div></article>}
function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="rounded-[26px] border border-white/70 bg-white/58 p-5 shadow-[0_20px_70px_rgba(62,48,57,.07)] backdrop-blur-xl sm:p-6"><h2 className="font-serif text-2xl text-[#463a40]">{title}</h2>{subtitle&&<p className="mt-1 mb-4 text-[10px] leading-5 text-[#82747b]">{subtitle}</p>}{children}</section>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-[16px] border border-white/75 bg-white/62 p-3"><p className="text-[8px] uppercase tracking-[.13em] text-[#9b8991]">{label}</p><p className="mt-1 font-serif text-2xl text-[#493e43]">{value}</p></div>}
function Principle({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-[18px] border border-[#eee4e8] bg-white/64 p-4"><div className="flex items-center gap-2 text-[#7c6872]">{icon}<strong className="text-[11px]">{title}</strong></div><p className="mt-2 text-[10px] leading-5 text-[#766970]">{text}</p></div>}
function Tier({label,text}:{label:string;text:string}){return <div className="mt-3 grid grid-cols-[72px_1fr] gap-2 text-[10px]"><span className="uppercase tracking-[.1em] text-[#a28491]">{label}</span><span className="text-[#6c6066]">{text}</span></div>}
function Empty({text}:{text:string}){return <div className="rounded-[18px] border border-dashed border-[#e1d5da] bg-white/44 p-5 text-[10px] leading-5 text-[#83757c]">{text}</div>}
