'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Brain, Clock3, Compass, FileText, Layers3, Play, Sparkles, Target } from 'lucide-react';

type Project={id:string;userId:string;title:string;area:string;status:string;priority:string;progress:number;nextAction:string|null;deadline:Date|null;notes:string|null;milestones:unknown[];relatedTaskIds:string[];activity:unknown[];createdAt:Date;updatedAt:Date};
type Task={id:string;title:string;description:string|null;status:string;priority:string;dueDate:Date|null;completedAt:Date|null};
type Goal={id:string;title:string;description:string|null;category:string;status:string;targetDate:Date|null;progress:number};
type Event={id:string;title:string;startAt:Date;endAt:Date|null;allDay:boolean};
type Memory={id:string;title:string;summary:string|null;sourceDate:Date|null;relatedProjectId:string|null;category:string;source:string};
type Planning={id:string;sourceType:string;sourceId:string|null;title:string;reason:string;startAt:Date;endAt:Date;status:string};
type Tab='today'|'active'|'workspace'|'roadmap'|'tasks'|'files'|'decisions'|'timeline'|'reviews'|'archive'|'insights'|'manage';
type Milestone={id:string;title:string;done:boolean};
type RefItem={id:string;title:string;url:string};
type PMemory={phase:string;brief:string;definition:string;scope:string;notNow:string;blockers:string[];decisions:string[];references:RefItem[];lessons:string[]};
type Store={projectMemory:Record<string,PMemory>};
const KEY='glow:project-execution:v1';
const phases=['Explore','Define','Design','Build','Review','Finish','Launch'];
const emptyMemory:PMemory={phase:'Explore',brief:'',definition:'',scope:'',notNow:'',blockers:[],decisions:[],references:[],lessons:[]};
const tabs:Tab[]=['today','active','workspace','roadmap','tasks','files','decisions','timeline','reviews','archive','insights','manage'];
function match(project:Project,text:string){const words=project.title.toLowerCase().split(/\s+/).filter(w=>w.length>3);const hay=text.toLowerCase();return words.some(w=>hay.includes(w))||hay.includes(project.title.toLowerCase());}
function milestoneRows(value:unknown[]):Milestone[]{return value.map((item,index)=>{if(typeof item==='string')return{id:`m-${index}`,title:item,done:false};if(item&&typeof item==='object'){const o=item as Record<string,unknown>;return{id:String(o.id??`m-${index}`),title:String(o.title??o.name??`Milestone ${index+1}`),done:Boolean(o.done??o.completed)};}return{id:`m-${index}`,title:`Milestone ${index+1}`,done:false};});}
function health(project:Project,mem:PMemory,now:Date){if(project.status==='completed')return 'Complete';if(mem.blockers.length)return 'Blocked';if(project.deadline&&project.deadline.getTime()<now.getTime())return 'At risk';const stale=(now.getTime()-new Date(project.updatedAt).getTime())/86400000;if(stale>21)return 'Stalled';if(project.progress>=85)return 'Ready to finish';if(stale>10)return 'Slow';return 'Moving';}
function fmt(date:Date|null){return date?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(date)):'Not set';}
function Panel({title,children,className=''}:{title:string;children:React.ReactNode;className?:string}){return <section className={`rounded-[26px] border border-white/70 bg-white/58 p-5 shadow-[0_18px_60px_rgba(83,73,82,.08)] backdrop-blur-xl ${className}`}><div className="mb-4 text-[10px] uppercase tracking-[.24em] text-[#76727d]">{title}</div>{children}</section>}
function openGlow(prompt:string){window.dispatchEvent(new CustomEvent('glow:open-conversation',{detail:{prompt}}));}

export function ProjectExecutionStudio({projects,tasks,goals,events,memories,planning,nowIso}:{projects:Project[];tasks:Task[];goals:Goal[];events:Event[];memories:Memory[];planning:Planning[];nowIso:string}){
 const now=useMemo(()=>new Date(nowIso),[nowIso]);
 const [tab,setTab]=useState<Tab>('today'); const [selectedId,setSelectedId]=useState(projects.find(p=>p.status==='active')?.id??projects[0]?.id??''); const [effort,setEffort]=useState(30); const [lowEnergy,setLowEnergy]=useState(false); const [mode,setMode]=useState<'creative'|'admin'|'normal'>('normal'); const [store,setStore]=useState<Store>({projectMemory:{}}); const [focus,setFocus]=useState<{projectId:string;title:string;action:string;seconds:number;steps:string[]}|null>(null); const [running,setRunning]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setStore(JSON.parse(raw));}catch{}},[]); useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(store));}catch{}},[store]);
 useEffect(()=>{if(!focus||!running)return;const id=window.setInterval(()=>setFocus(current=>current?{...current,seconds:Math.max(0,current.seconds-1)}:current),1000);return()=>window.clearInterval(id)},[focus,running]);
 useEffect(()=>{if(focus?.seconds===0)setRunning(false)},[focus?.seconds]);
 const active=projects.filter(p=>p.status==='active'); const archived=projects.filter(p=>p.status==='archived'||p.status==='completed'); const priorityRank=(p:Project)=>({urgent:4,high:3,medium:2,low:1}[p.priority]??0); const primary=active.slice().sort((a,b)=>priorityRank(b)-priorityRank(a)||(a.deadline?.getTime()??Infinity)-(b.deadline?.getTime()??Infinity))[0]??projects[0]; const selected=projects.find(p=>p.id===selectedId)??primary; const pm=selected?{...emptyMemory,...store.projectMemory[selected.id]}:emptyMemory;
 const exactTasks=selected?tasks.filter(t=>selected.relatedTaskIds.includes(t.id)):[]; const suggestedTasks=selected?tasks.filter(t=>!selected.relatedTaskIds.includes(t.id)&&match(selected,`${t.title} ${t.description??''}`)):[]; const relatedGoals=selected?goals.filter(g=>match(selected,`${g.title} ${g.description??''}`)):[]; const relatedEvents=selected?events.filter(e=>match(selected,e.title)):[]; const relatedMemory=selected?memories.filter(m=>m.relatedProjectId===selected.id):[]; const relatedPlanning=selected?planning.filter(p=>p.sourceId===selected.id||match(selected,p.title)):[]; const ms=selected?milestoneRows(selected.milestones):[]; const blocked=active.filter(p=>({...emptyMemory,...store.projectMemory[p.id]}).blockers.length>0); const stale=active.filter(p=>(now.getTime()-new Date(p.updatedAt).getTime())>14*86400000); const noNext=active.filter(p=>!p.nextAction?.trim());
 function patch(patch:Partial<PMemory>){if(!selected)return;setStore(s=>({...s,projectMemory:{...s.projectMemory,[selected.id]:{...emptyMemory,...s.projectMemory[selected.id],...patch}}}))}
 function startProject(project:Project){const mem={...emptyMemory,...store.projectMemory[project.id]};let action=project.nextAction?.trim()||`Define the next concrete action for ${project.title}.`;if(lowEnergy)action=`Keep ${project.title} alive with one 5-minute preparation step.`;if(mode==='admin')action=`Do one admin action that removes friction from ${project.title}.`;if(mode==='creative')action=`Do one visible creative step for ${project.title}.`;setSelectedId(project.id);setFocus({projectId:project.id,title:project.title,action,seconds:(lowEnergy?5:effort)*60,steps:[action,mem.blockers[0]?`Address blocker: ${mem.blockers[0]}`:'Record the exact next step before stopping.']});setRunning(true)}
 if(focus){const mm=Math.floor(focus.seconds/60),ss=String(focus.seconds%60).padStart(2,'0');return <div className="min-h-[78vh] rounded-[34px] border border-white/70 bg-[radial-gradient(circle_at_25%_10%,rgba(255,229,219,.9),transparent_34%),radial-gradient(circle_at_80%_20%,rgba(219,226,243,.88),transparent_36%),linear-gradient(145deg,#fbf8f3,#ececf2)] p-6 text-[#2d2a31]"><button onClick={()=>{setFocus(null);setRunning(false)}} className="text-[10px] uppercase tracking-[.2em]">Exit focus</button><div className="mx-auto mt-20 max-w-2xl text-center"><div className="text-[10px] uppercase tracking-[.3em] text-[#77717d]">Project Focus</div><h1 className="mt-4 glow-display text-4xl">{focus.title}</h1><div className="mt-7 text-6xl font-light tabular-nums">{mm}:{ss}</div><p className="mx-auto mt-8 max-w-xl text-lg">{focus.action}</p><div className="mt-8 flex flex-wrap justify-center gap-2"><button onClick={()=>{setRunning(false);setFocus(null)}} className="couture-primary">Done</button><button onClick={()=>setFocus(f=>f?{...f,steps:['Make the action smaller.','Do only the first visible piece.','Record what remains.']}:f)} className="couture-secondary">I’m stuck</button><button onClick={()=>setFocus(f=>f?{...f,steps:['Clarify done.','Choose the smallest deliverable.','Finish only that deliverable.']}:f)} className="couture-secondary">Break down</button><button onClick={()=>setFocus(f=>f?{...f,seconds:f.seconds+600}:f)} className="couture-secondary">+10 min</button><button onClick={()=>setRunning(v=>!v)} className="couture-secondary">{running?'Pause':'Resume'}</button></div><div className="mt-8 space-y-2 text-left">{focus.steps.map((s,i)=><div key={i} className="rounded-2xl bg-white/55 px-4 py-3 text-sm">{i+1}. {s}</div>)}</div></div></div>}
 return <div className="min-h-screen rounded-[34px] bg-[radial-gradient(circle_at_20%_0%,rgba(255,224,211,.78),transparent_28%),radial-gradient(circle_at_85%_12%,rgba(218,225,241,.82),transparent_32%),linear-gradient(150deg,#faf7f1_0%,#f1eef1_52%,#e8edf2_100%)] p-3 text-[#2f2b31] sm:p-5">
  <div className="rounded-[30px] border border-white/70 bg-white/36 p-5 shadow-[0_32px_100px_rgba(81,72,79,.11)] backdrop-blur-2xl sm:p-7">
   <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.32em] text-[#766f79]">Projects · Creative Operations</div><h1 className="mt-2 glow-display text-3xl sm:text-5xl">Creation in motion.</h1><p className="mt-3 max-w-2xl text-sm text-[#706b73]">What am I building, what is moving, what is stuck, and what should I do next to finish it?</p></div><button onClick={()=>openGlow('What project should I work on right now, considering my priorities, calendar, blockers, deadlines and energy?')} className="couture-secondary"><Sparkles className="mr-2 inline h-4 w-4"/>Ask Glow</button></div>
   <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 rounded-full px-4 py-2 text-[10px] capitalize ${tab===t?'bg-[#332f38] text-white':'border border-white/80 bg-white/50'}`}>{t}</button>)}</div>
  </div>
  <div className="mt-4 space-y-4">
   {tab==='today'?<><Panel title="Projects · Today"><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div><div className="text-xs text-[#77717a]">{new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(now)}</div><h2 className="mt-3 glow-display text-3xl">{primary?.title??'Create your first project'}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Best next move" value={primary?.nextAction||'Define a clear next action'}/><Metric label="Estimated effort" value={`${lowEnergy?5:effort} min`}/><Metric label="Current health" value={primary?health(primary,{...emptyMemory,...store.projectMemory[primary.id]},now):'Not set'}/><Metric label="Blocked" value={`${blocked.length} project${blocked.length===1?'':'s'}`}/></div><div className="mt-5 flex flex-wrap gap-2"><button disabled={!primary} onClick={()=>primary&&startProject(primary)} className="couture-primary"><Play className="mr-2 inline h-4 w-4"/>Move a project forward</button><button onClick={()=>openGlow('Just tell me what project to work on next. Choose one useful action and keep the answer concise.')} className="couture-secondary">Just tell me what to work on</button></div></div><div className="rounded-[26px] border border-white/70 bg-white/45 p-5"><div className="text-[10px] uppercase tracking-[.2em]">Work mode</div><div className="mt-3 flex flex-wrap gap-2">{[10,30,60].map(v=><button key={v} onClick={()=>{setEffort(v);setLowEnergy(false)}} className="couture-secondary">{v} min</button>)}<button onClick={()=>setLowEnergy(v=>!v)} className="couture-secondary">Low energy</button><button onClick={()=>setMode('creative')} className="couture-secondary">Creative</button><button onClick={()=>setMode('admin')} className="couture-secondary">Admin</button></div></div></div></Panel><Panel title="One thing"><div className="flex items-center justify-between gap-4"><div><div className="text-xl font-medium">{primary?.nextAction||'Give the most important active project a next action.'}</div><p className="mt-1 text-xs text-[#77717a]">{primary?`Supports ${primary.title}`:'Projects become useful when the next physical action is clear.'}</p></div>{primary?<button onClick={()=>startProject(primary)} className="couture-primary">Start</button>:null}</div></Panel></>:null}
   {tab==='active'?<Panel title="Your active work"><div className="relative grid gap-4 md:grid-cols-2 xl:grid-cols-3">{active.map((p,i)=>{const mem={...emptyMemory,...store.projectMemory[p.id]};return <button key={p.id} onClick={()=>{setSelectedId(p.id);setTab('workspace')}} className={`min-h-48 rounded-[30px] border border-white/70 bg-white/50 p-5 text-left shadow-[0_15px_45px_rgba(72,66,75,.08)] transition hover:-translate-y-1 ${mem.blockers.length?'opacity-75 backdrop-blur-xl':''}`}><div className="flex justify-between text-[10px] uppercase tracking-[.18em]"><span>{p.area}</span><span>{health(p,mem,now)}</span></div><h3 className="mt-5 glow-display text-2xl">{p.title}</h3><p className="mt-2 text-xs text-[#77717a]">{mem.phase} · {p.progress}%</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/80"><div className="h-full rounded-full bg-[#817c91]" style={{width:`${Math.max(2,p.progress)}%`}}/></div><div className="mt-5 text-xs">Next: {p.nextAction||'Needs a next action'}</div></button>})}</div></Panel>:null}
   {tab==='workspace'&&selected?<><Panel title="Project Workspace"><div className="flex flex-wrap justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.2em]">{selected.area} · {selected.status}</div><h2 className="mt-2 glow-display text-4xl">{selected.title}</h2><p className="mt-3 max-w-2xl text-sm text-[#706b73]">{pm.brief||selected.notes||'Add a project brief so the work has a clear purpose and boundary.'}</p></div><div className="grid grid-cols-2 gap-2 text-xs"><Metric label="Phase" value={pm.phase}/><Metric label="Progress" value={`${selected.progress}%`}/><Metric label="Deadline" value={fmt(selected.deadline)}/><Metric label="Health" value={health(selected,pm,now)}/></div></div><div className="mt-6 rounded-[24px] bg-white/52 p-5"><div className="text-[10px] uppercase tracking-[.2em]">Next action</div><div className="mt-2 text-xl">{selected.nextAction||'This project is active but has no clear next action.'}</div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>startProject(selected)} className="couture-primary">Start next action</button><button onClick={()=>setTab('roadmap')} className="couture-secondary">Open roadmap</button><button onClick={()=>setTab('tasks')} className="couture-secondary">Tasks</button><button onClick={()=>setTab('files')} className="couture-secondary">Files</button><button onClick={()=>setTab('decisions')} className="couture-secondary">Log decision</button></div></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><Panel title="Supports goals">{relatedGoals.length?relatedGoals.map(g=><div key={g.id} className="mb-2 text-sm">{g.title}</div>):<p className="text-xs text-[#77717a]">No explicit goal link exists in the current schema. These appear only when titles/context match.</p>}</Panel><Panel title="Blockers">{pm.blockers.length?pm.blockers.map((b,i)=><div key={i} className="mb-2 rounded-2xl bg-white/55 p-3 text-sm">{b}</div>):<p className="text-xs text-[#77717a]">No blocker recorded.</p>}<button onClick={()=>{const v=prompt('What is blocking this project?')?.trim();if(v)patch({blockers:[...pm.blockers,v]})}} className="mt-3 couture-secondary">Add blocker</button></Panel><Panel title="Project brief"><textarea value={pm.brief} onChange={e=>patch({brief:e.target.value})} placeholder="What are we making and why?" className="min-h-28 w-full rounded-2xl border border-white/80 bg-white/60 p-3 text-sm outline-none"/></Panel></div></Panel></>:null}
   {tab==='roadmap'&&selected?<Panel title="Roadmap"><div className="grid gap-3 md:grid-cols-7">{phases.map((phase,i)=><button key={phase} onClick={()=>patch({phase})} className={`rounded-[22px] border p-4 text-left ${pm.phase===phase?'border-[#817c91] bg-white/80':'border-white/70 bg-white/42'}`}><div className="text-[10px]">0{i+1}</div><div className="mt-2 text-sm font-medium">{phase}</div></button>)}</div><div className="mt-6 grid gap-3 md:grid-cols-2">{ms.length?ms.map(m=><div key={m.id} className="rounded-2xl bg-white/52 p-4 text-sm">{m.done?'✓':'○'} {m.title}</div>):<div className="text-sm text-[#77717a]">No stored milestones yet. Add milestones through project management until the schema gets richer milestone actions.</div>}</div></Panel>:null}
   {tab==='tasks'&&selected?<div className="grid gap-4 lg:grid-cols-2"><Panel title="Linked tasks">{exactTasks.length?exactTasks.map(t=><TaskRow key={t.id} task={t}/>):<p className="text-xs text-[#77717a]">No task IDs are explicitly linked to this project.</p>}<Link href="/tasks" className="mt-4 inline-flex couture-secondary">Open Tasks</Link></Panel><Panel title="Possible related tasks"><p className="mb-3 text-[10px] text-[#77717a]">Suggestions are text matches, not stored project links.</p>{suggestedTasks.length?suggestedTasks.slice(0,8).map(t=><TaskRow key={t.id} task={t}/>):<p className="text-xs text-[#77717a]">No likely matches found.</p>}</Panel></div>:null}
   {tab==='files'&&selected?<div className="grid gap-4 lg:grid-cols-2"><Panel title="References + files"><p className="text-xs text-[#77717a]">The current Projects database has no binary file table. This board stores explicit reference links in Project Memory instead of pretending uploads exist.</p><div className="mt-4 space-y-2">{pm.references.map(r=><a key={r.id} href={r.url} target="_blank" rel="noreferrer" className="block rounded-2xl bg-white/55 p-3 text-sm">{r.title}</a>)}</div><button onClick={()=>{const title=prompt('Reference title')?.trim();if(!title)return;const url=prompt('URL')?.trim();if(url)patch({references:[...pm.references,{id:crypto.randomUUID(),title,url}]})}} className="mt-4 couture-secondary">Add reference link</button></Panel><Panel title="Reference board"><div className="grid grid-cols-2 gap-3">{pm.references.length?pm.references.map(r=><div key={r.id} className="aspect-[4/3] rounded-[24px] border border-white/70 bg-[linear-gradient(145deg,rgba(255,255,255,.8),rgba(223,226,234,.65))] p-4"><FileText className="h-5 w-5"/><div className="mt-8 text-sm">{r.title}</div></div>):<div className="col-span-2 rounded-[24px] border border-dashed border-white bg-white/30 p-8 text-center text-sm text-[#77717a]">Add links, images or documents as references when a true project asset schema is added.</div>}</div></Panel></div>:null}
   {tab==='decisions'&&selected?<div className="grid gap-4 lg:grid-cols-2"><Panel title="Decisions needed"><button onClick={()=>openGlow(`Help me identify the decisions blocking ${selected.title}. Use the project context and make each decision concrete.`)} className="couture-primary">Find decisions with Glow</button><div className="mt-4 space-y-2">{pm.blockers.filter(b=>/decid|choose|select|approval/i.test(b)).map((b,i)=><div key={i} className="rounded-2xl bg-white/55 p-3 text-sm">{b}</div>)}</div></Panel><Panel title="Decision history">{pm.decisions.map((d,i)=><div key={i} className="mb-2 rounded-2xl bg-white/55 p-3 text-sm">{d}</div>)}<button onClick={()=>{const v=prompt('Decision + reason')?.trim();if(v)patch({decisions:[...pm.decisions,`${new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(now)} · ${v}`]})}} className="couture-secondary">Log decision</button></Panel></div>:null}
   {tab==='timeline'&&selected?<Panel title="Project timeline"><div className="space-y-3"><Timeline date={fmt(selected.createdAt)} title="Project created"/><>{Array.isArray(selected.activity)?selected.activity.slice().reverse().slice(0,12).map((a,i)=><Timeline key={i} date="Activity" title={typeof a==='string'?a:JSON.stringify(a)}/>):null}</>{relatedMemory.map(m=><Timeline key={m.id} date={fmt(m.sourceDate)} title={m.title}/>) }<Timeline date="Now" title={`${selected.progress}% · ${pm.phase}`}/>{selected.deadline?<Timeline date={fmt(selected.deadline)} title="Target"/>:null}</div></Panel>:null}
   {tab==='reviews'&&selected?<div className="grid gap-4 lg:grid-cols-3"><Panel title="Reality check"><Metric label="Deadline" value={fmt(selected.deadline)}/><Metric label="Blocked" value={`${pm.blockers.length}`}/><Metric label="Scheduled blocks" value={`${relatedPlanning.length}`}/><Metric label="Outlook" value={health(selected,pm,now)}/></Panel><Panel title="Scope control"><textarea value={pm.scope} onChange={e=>patch({scope:e.target.value})} placeholder="In scope" className="mb-2 min-h-24 w-full rounded-2xl bg-white/55 p-3 text-sm outline-none"/><textarea value={pm.notNow} onChange={e=>patch({notNow:e.target.value})} placeholder="Not now" className="min-h-24 w-full rounded-2xl bg-white/55 p-3 text-sm outline-none"/></Panel><Panel title="Definition of done"><textarea value={pm.definition} onChange={e=>patch({definition:e.target.value})} placeholder="What must be true for this to count as done?" className="min-h-44 w-full rounded-2xl bg-white/55 p-3 text-sm outline-none"/><button onClick={()=>openGlow(`Help me create the shortest realistic finish plan for ${selected.title}. Definition of done: ${pm.definition||'not yet defined'}.`)} className="mt-3 couture-primary">Finish mode</button></Panel></div>:null}
   {tab==='archive'?<Panel title="Archive"><div className="grid gap-3 md:grid-cols-2">{archived.length?archived.map(p=><button key={p.id} onClick={()=>{setSelectedId(p.id);setTab('workspace')}} className="rounded-[24px] bg-white/50 p-4 text-left"><div className="text-sm font-medium">{p.title}</div><div className="mt-2 text-xs text-[#77717a]">{p.status} · {p.progress}%</div></button>):<p className="text-sm text-[#77717a]">No completed or archived projects yet.</p>}</div></Panel>:null}
   {tab==='insights'?<div className="grid gap-4 lg:grid-cols-3"><Panel title="Attention"><Metric label="Blocked projects" value={`${blocked.length}`}/><Metric label="Stale 14+ days" value={`${stale.length}`}/><Metric label="No next action" value={`${noNext.length}`}/></Panel><Panel title="Execution"><Metric label="Active projects" value={`${active.length}`}/><Metric label="Scheduled project blocks" value={`${planning.filter(p=>p.sourceType.toLowerCase().includes('project')).length}`}/><Metric label="Completed / archived" value={`${archived.length}`}/></Panel><Panel title="What Glow can learn"><p className="text-xs leading-5 text-[#77717a]">Glow can eventually detect repeated blockers, over-scoping, best work windows and completion patterns. It should only make those claims after enough real project history exists.</p><Link href="/brain" className="mt-4 inline-flex couture-secondary"><Brain className="mr-2 h-4 w-4"/>Brain insights</Link></Panel></div>:null}
   {tab==='manage'?<Panel title="Project management"><p className="text-sm text-[#77717a]">Use the existing management controls below the studio to create projects and update status, priority, progress, deadline, next action and notes.</p><a href="#project-management" className="mt-3 inline-flex couture-primary">Open management</a></Panel>:null}
  </div>
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/70 bg-white/48 p-3"><div className="text-[9px] uppercase tracking-[.18em] text-[#817b84]">{label}</div><div className="mt-1 text-sm font-medium">{value}</div></div>}
function TaskRow({task}:{task:Task}){return <div className="mb-2 rounded-2xl bg-white/52 p-3"><div className="flex justify-between gap-3"><span className="text-sm">{task.title}</span><span className="text-[10px] uppercase">{task.status}</span></div>{task.dueDate?<div className="mt-1 text-[10px] text-[#77717a]">Due {fmt(task.dueDate)}</div>:null}</div>}
function Timeline({date,title}:{date:string;title:string}){return <div className="grid grid-cols-[80px_1fr] gap-3"><div className="text-[10px] uppercase tracking-[.14em] text-[#817b84]">{date}</div><div className="rounded-2xl border border-white/70 bg-white/48 p-3 text-sm">{title}</div></div>}
