export type UpgradeTool = {
  id: string;
  label: string;
  description: string;
  href?: string;
  mode?: 'workspace'|'proposal'|'focus'|'search'|'relationship'|'review'|'rule';
};

const tool = (id:string,label:string,description:string,href?:string,mode:UpgradeTool['mode']='workspace'):UpgradeTool=>({id,label,description,href,mode});

export const ROOM_UPGRADES:Record<string,UpgradeTool[]> = {
  dashboard:[
    tool('daily-hero','Dynamic Daily Hero','Tune the day around the current time, schedule and context.','/dashboard'),
    tool('top-three','Top 3 Intelligence','Surface the three most important things right now.','/brain/insights','search'),
    tool('free-time','Free-Time Finder','Find usable open windows between real calendar events.','/calendar','search'),
    tool('live-timeline','Live Day Timeline','Review what is completed, current and upcoming today.','/today'),
    tool('quick-life','Quick Life Controls','Capture wellness, meals, spending, habits and notes quickly.','/intake'),
    tool('attention','Risk & Attention Strip','Review overdue items, conflicts and attention signals.','/notices'),
    tool('energy-plan','Energy-Aware Planning','Plan demanding work around recorded energy patterns.','/planning','proposal'),
    tool('build-day','Build My Day','Create an editable proposed day plan before anything changes.','/planning','proposal'),
    tool('progress-story','Daily Progress Story','Review today as one coherent progress story.','/timeline'),
    tool('tomorrow-preview','Tomorrow Preview','See what should be prepared before the day ends.','/tomorrow'),
  ],
  calendar:[
    tool('event-editor','Intelligent Event Editor','Open the real event editor with planning context.','/calendar'),
    tool('time-zoom','Day / Week / Month / Year','Move between calendar scales.','/calendar'),
    tool('conflicts','Conflict Detector','Review overlapping or unrealistic time blocks.','/calendar','search'),
    tool('prep-layer','Preparation Layer','Store preparation and leave-by planning for an event.',undefined,'workspace'),
    tool('energy-overlay','Energy Overlay','Compare calendar load with recorded wellness energy.','/wellness','relationship'),
    tool('replan','Drag-to-Replan','Create a proposed replan before moving connected work.',undefined,'proposal'),
    tool('calendar-intelligence','Calendar Intelligence','Ask Glow to interpret schedule density and free time.','/brain/insights','search'),
    tool('event-connections','Connected Event Objects','Connect an event to tasks, goals, projects, routines or other Glow objects.',undefined,'relationship'),
    tool('event-templates','Event Templates','Save reusable event preparation templates.',undefined,'workspace'),
    tool('ask-calendar','Ask Calendar','Search your calendar in natural language.','/search','search'),
  ],
  tasks:[
    tool('task-editor','True Task Editor','Edit task details, dates, priority and relationships.','/tasks'),
    tool('priority-engine','Smart Priority Engine','Review urgency, importance, deadlines and available time.','/brain/insights','search'),
    tool('focus-mode','Focus Mode','Start a distraction-reduced focus session.','/focus','focus'),
    tool('decompose','Task Decomposition','Create an editable breakdown proposal.',undefined,'proposal'),
    tool('estimate-learning','Time Estimate Learning','Track estimated versus actual focus time.','/focus'),
    tool('task-lanes','Priority Lanes','Organize work across Do First, Today, Waiting and Someday.','/tasks'),
    tool('blocked','Blocked Task Detection','Inspect dependencies and stalled work.','/brain/insights','search'),
    tool('context-actions','Contextual Actions','Capture the next call, email, research or scheduling action.','/intake'),
    tool('relationships','Task Relationships','Connect a task to goals, projects, events, habits and routines.',undefined,'relationship'),
    tool('day-review','End-of-Day Task Review','Complete, move, keep or intentionally remove unfinished work.','/briefings/evening','review'),
  ],
  planning:[
    tool('life-zoom','Life Zoom','Move from year to quarter, month, week and day.','/planning'),
    tool('top-three','Top Three Planner','Store the three outcomes that matter for this planning period.',undefined,'workspace'),
    tool('capacity','Capacity Meter','Compare planned work with available schedule capacity.','/planning','search'),
    tool('planning-board','Planning Board','Organize planning blocks and proposals.','/planning'),
    tool('brain-dump-plan','Brain Dump → Plan','Route unstructured ideas into a proposed plan.','/intake','proposal'),
    tool('sunday-reset','Sunday Reset','Open the weekly reset workspace.','/routines'),
    tool('back-plan','Deadline Back-Planner','Generate a reversible plan backward from a deadline.',undefined,'proposal'),
    tool('scenarios','Planning Scenarios','Save Calm, Productive, Recovery or Busy-week scenarios.',undefined,'workspace'),
    tool('plan-vs-reality','Plan vs. Reality','Compare planned blocks with actual completion.','/timeline'),
    tool('planning-assistant','Glow Planning Assistant','Review proposals before changes are applied.','/concierge','proposal'),
  ],
  reminders:[
    tool('unified-inbox','Unified Reminder Inbox','Review Glow and imported Apple reminders.','/reminders'),
    tool('categories','Smart Categories','Organize reminders by list, urgency and context.','/reminders'),
    tool('context','Context-Aware Reminder','Save the context that should make a reminder relevant.',undefined,'workspace'),
    tool('relevant','Remind When Relevant','Create a conditional reminder rule.',undefined,'rule'),
    tool('recurring','Recurring Reminder Builder','Create recurring reminder patterns.','/reminders'),
    tool('convert','Reminder Conversion','Turn a reminder into a task, event or routine through Intake.','/intake'),
    tool('smart-snooze','Smart Snooze','Store a snooze proposal based on schedule context.',undefined,'proposal'),
    tool('history','Reminder History','Review imported and completed reminder history.','/reminders'),
    tool('recovery','Missed Reminder Recovery','Surface missed reminders that still matter.','/notices'),
    tool('natural-language','Natural-Language Reminder','Capture a reminder in your own words.','/intake'),
  ],
  routines:[
    tool('builder','Visual Routine Builder','Create and edit routine steps.','/routines'),
    tool('dayparts','Daypart Routines','Organize morning, midday, evening, night and weekly routines.','/routines'),
    tool('step-mode','Step-by-Step Mode','Run one routine step at a time.','/routines'),
    tool('lengths','Adaptive Routine Lengths','Save full, normal, quick and emergency variants.',undefined,'workspace'),
    tool('timers','Step Timers','Store timing guidance for routine steps.',undefined,'workspace'),
    tool('conditions','Conditional Steps','Define when special steps should appear.',undefined,'rule'),
    tool('stacking','Routine Stacking','Connect routines that should run together.',undefined,'relationship'),
    tool('analytics','Completion Analytics','Review routine completion patterns.','/graph'),
    tool('optimization','Routine Optimization','Create a proposal for routinely skipped steps.',undefined,'proposal'),
    tool('templates','Routine Templates','Save reusable routine templates.',undefined,'workspace'),
  ],
  habits:[
    tool('garden','Habit Garden','Use the existing habit garden as a visual consistency layer.','/habits'),
    tool('heatmap','Calendar Heat Map','Review habit consistency over time.','/habits'),
    tool('streaks','Streaks','Review streaks without punitive scoring.','/habits'),
    tool('difficulty','Difficulty Tracking','Record how hard a habit felt.',undefined,'workspace'),
    tool('goal-link','Habit → Goal','Connect habits to the goals they support.',undefined,'relationship'),
    tool('dayparts','Morning / Evening Grouping','Organize habits by useful time of day.',undefined,'workspace'),
    tool('triggers','Habit Triggers','Define after/before relationships between habits and routines.',undefined,'rule'),
    tool('patterns','Monthly Patterns','Review consistency by month.','/graph'),
    tool('experiments','Habit Experiments','Run a 14- or 30-day habit experiment.',undefined,'workspace'),
    tool('simplify','Simplification Suggestions','Create a proposal to simplify repeatedly missed habits.',undefined,'proposal'),
  ],
  fitness:[
    tool('today-workout','Today’s Workout','Open today’s real workout view.','/fitness'),
    tool('exercise-library','Exercise Library','Store and review exercise instructions.',undefined,'workspace'),
    tool('workout-builder','Workout Builder','Build an editable workout plan.',undefined,'workspace'),
    tool('sets-reps','Sets / Reps / Weight','Track structured workout details.',undefined,'workspace'),
    tool('rest-timer','Rest Timer','Use Focus timing for rest and work intervals.','/focus','focus'),
    tool('progress','Progress Charts','Review real fitness history.','/graph'),
    tool('recovery','Recovery / Readiness','Use logged soreness and energy for recovery context.','/fitness'),
    tool('body-region','Body Region View','Track training focus by body region.',undefined,'workspace'),
    tool('photos','Progress Photo Timeline','Connect progress images to the life timeline.',undefined,'workspace'),
    tool('ai-plan','AI Workout Planner','Create an editable next-workout proposal from real history.',undefined,'proposal'),
  ],
  wellness:[
    tool('checkin','Daily Emotional Check-In','Log mood, energy, stress and wellness.','/wellness'),
    tool('sleep','Sleep Overview','Review recorded sleep information.','/wellness'),
    tool('energy','Energy Tracker','Track and review energy.','/wellness'),
    tool('stress','Stress Tracker','Track and review stress.','/wellness'),
    tool('hydration','Hydration','Log and review hydration.','/wellness'),
    tool('journal','Mind / Body Journal','Capture a wellness note.','/notes'),
    tool('recovery','Recovery Recommendations','Review reversible recovery suggestions.','/brain/insights','search'),
    tool('correlations','Wellness Correlations','Explore relationships between wellness and other rooms.','/graph'),
    tool('calming','Reset Activities','Save personalized calming/reset activities.',undefined,'workspace'),
    tool('exhibit','Wellness Exhibit','Open a focused metric workspace.',undefined,'workspace'),
  ],
  medications:[
    tool('library','Medication & Supplement Library','Manage medication and supplement records.','/wellness/medications'),
    tool('schedule','Morning / Night Schedule','Organize care items by time of day.','/wellness/medications'),
    tool('taken','Taken / Skipped Logging','Log adherence.','/wellness/medications'),
    tool('refills','Refill Countdown','Track refill timing.','/wellness/medications'),
    tool('inventory','Supply Inventory','Track remaining supply.',undefined,'workspace'),
    tool('prescriptions','Prescription Information','Store prescription information without changing treatment advice.',undefined,'workspace'),
    tool('appointment-notes','Appointment Notes','Connect medication notes to appointments.',undefined,'relationship'),
    tool('adherence','Adherence History','Review adherence history.','/wellness/medications'),
    tool('questions','Questions for Appointment','Save questions for the next appointment.',undefined,'workspace'),
    tool('timeline','Medication Timeline','Record medication changes on the life timeline.','/timeline'),
  ],
  food:[
    tool('today-meals','Today’s Meals','Review today’s meal plan.','/food'),
    tool('weekly-plan','Weekly Meal Planner','Plan meals across the week.','/food'),
    tool('recipes','Recipe Library','Store and browse recipes.',undefined,'workspace'),
    tool('grocery','Grocery Generator','Turn planned meal ingredients into a grocery workspace.',undefined,'workspace'),
    tool('pantry','Pantry Inventory','Track pantry items.',undefined,'workspace'),
    tool('meal-prep','Meal-Prep Mode','Save preparation batches and tasks.',undefined,'workspace'),
    tool('favorites','Favorite Meals','Save favorite meal combinations.',undefined,'workspace'),
    tool('nutrition','Nutrition Summary','Store nutrition details only where actual values are available.',undefined,'workspace'),
    tool('substitutions','Ingredient Substitutions','Save ingredient alternatives.',undefined,'workspace'),
    tool('explorer','Meal Explorer','Open a deeper meal workspace with ingredients and preparation.',undefined,'workspace'),
  ],
  beauty:[
    tool('routine-hero','AM / PM Routine','Open your real beauty routines.','/beauty'),
    tool('skincare','Interactive Skincare Routine','Run and edit skincare steps.','/beauty'),
    tool('makeup','Makeup Routine Library','Save makeup routine templates.',undefined,'workspace'),
    tool('body-care','Body-Care Routines','Save body-care routine templates.',undefined,'workspace'),
    tool('treatments','Treatment Calendar','Connect beauty treatments to Calendar.',undefined,'relationship'),
    tool('inventory','Product Inventory','Review real Beauty Lab products.','/beauty/lab'),
    tool('usage','Product Usage','Track product usage notes.',undefined,'workspace'),
    tool('photos','Before / After Timeline','Connect beauty progress images to Timeline.',undefined,'workspace'),
    tool('spending','Beauty Spending','Review beauty-related finance activity.','/finance','search'),
    tool('coach','Beauty Coach','Create contextual beauty suggestions from stored routines and products.','/brain/insights','search'),
  ],
  'beauty-lab':[
    tool('laboratory','Product Laboratory','Open the real product testing cabinet.','/beauty/lab'),
    tool('ingredients','Ingredient Explorer','Explore stored ingredient text.',undefined,'workspace'),
    tool('comparison','Product Comparison','Compare stored products side by side.',undefined,'workspace'),
    tool('compatibility','Routine Compatibility','Connect products to AM/PM routines.',undefined,'relationship'),
    tool('lifecycle','Product Lifecycle','Track Testing → Active → Favorite → Finished → Retired.',undefined,'workspace'),
    tool('skin-journal','Skin Journal','Capture experiment observations.','/notes'),
    tool('progress','Progress Photography','Connect experiment photos to Timeline.',undefined,'workspace'),
    tool('experiments','Treatment Experiments','Create and track an experiment.',undefined,'workspace'),
    tool('analytics','Beauty Analytics','Review product and routine patterns.','/graph'),
    tool('inspection','Product Inspection','Open a focused cinematic product workspace.',undefined,'workspace'),
  ],
  hair:[
    tool('phase','Current Hair Phase','Review current hair state.','/hair'),
    tool('wash-plan','Wash-Day Planner','Plan wash-day steps and next wash.','/hair'),
    tool('routine-builder','Hair Routine Builder','Create and edit hair routines.','/hair'),
    tool('products','Product Shelf','Review products logged in hair history.','/hair'),
    tool('treatments','Treatment Calendar','Connect hair treatments to Calendar.',undefined,'relationship'),
    tool('styles','Style Library','Save styles and instructions.',undefined,'workspace'),
    tool('goals','Hair Goals','Connect hair activity to Goals.','/goals','relationship'),
    tool('journey','Photo Journey','Connect hair photos to Timeline.',undefined,'workspace'),
    tool('repurchase','Usage / Repurchase','Track product usage and repurchase notes.',undefined,'workspace'),
    tool('intelligence','Hair Intelligence','Review patterns from wash, heat, products and logged outcomes.','/brain/insights','search'),
  ],
  closet:[
    tool('wardrobe','Digital Wardrobe','Manage real closet items.','/closet'),
    tool('categories','Categories','Browse closet categories.','/closet'),
    tool('outfit-builder','Outfit Builder','Save an outfit composition.',undefined,'workspace'),
    tool('outfit-calendar','Outfit Calendar','Connect an outfit plan to an event.',undefined,'relationship'),
    tool('favorites','Favorite Combinations','Save favorite outfit combinations.',undefined,'workspace'),
    tool('laundry','Laundry State','Track clean/laundry/repair state.','/closet'),
    tool('packing','Packing Planner','Build a packing list from closet items.',undefined,'workspace'),
    tool('wishlist','Wishlist','Manage closet wishlist items.','/closet'),
    tool('cost-per-wear','Cost per Wear','Review tracked price and wear count.','/closet'),
    tool('wear-assistant','What Should I Wear?','Create an outfit proposal from real closet and calendar context.',undefined,'proposal'),
  ],
  finance:[
    tool('month','This Month','Review the real monthly finance summary.','/finance'),
    tool('timeline','Transaction Timeline','Review transaction history.','/finance'),
    tool('categories','Category Breakdown','Review spending categories.','/finance'),
    tool('budgets','Budget System','Store and review budget planning.',undefined,'workspace'),
    tool('bills','Bills / Subscriptions','Track recurring obligations.',undefined,'workspace'),
    tool('savings','Savings Tracker','Review finance goals.','/finance'),
    tool('goals','Financial Goals','Manage real finance goals.','/finance'),
    tool('search','Spending Search','Search finance history.','/search','search'),
    tool('compare','Month Comparison','Compare month-to-month totals.','/finance/brain'),
    tool('attention','Financial Attention','Review unusual or time-sensitive financial signals.','/finance/brain'),
  ],
  'financial-brain':[
    tool('patterns','Spending Patterns','Interpret real spending patterns.','/finance/brain'),
    tool('cash-flow','Cash-Flow Forecast','Create an assumption-labeled forecast workspace.',undefined,'workspace'),
    tool('pressure','Budget Pressure','Review categories approaching plan limits.','/finance/brain'),
    tool('subscriptions','Subscription Intelligence','Track recurring spending patterns.',undefined,'workspace'),
    tool('savings','Savings Trajectory','Project real finance-goal progress.','/finance/brain'),
    tool('goal-forecast','Goal Forecasting','Create an assumption-labeled goal forecast.',undefined,'workspace'),
    tool('afford','Can I Afford This?','Run an editable scenario using real available finance data.',undefined,'workspace'),
    tool('scenario','Scenario Simulator','Save and compare financial scenarios.',undefined,'workspace'),
    tool('narrative','Monthly Narrative','Generate a data-grounded monthly finance story.',undefined,'workspace'),
    tool('recommendation','Priority Recommendation','Keep one prioritized finance recommendation visible.','/finance/brain'),
  ],
  goals:[
    tool('life-goals','Life Goals','Manage active goals.','/goals'),
    tool('quarterly','Quarterly Goals','Organize goals by quarter.',undefined,'workspace'),
    tool('visual-cards','Visual Goal Cards','Review goal cards and progress.','/goals'),
    tool('milestones','Milestones','Manage real goal milestones.','/goals'),
    tool('project-link','Goal → Project','Connect goals to projects.',undefined,'relationship'),
    tool('habit-link','Goal → Habit','Connect goals to supporting habits.',undefined,'relationship'),
    tool('history','Progress History','Review progress changes.','/timeline'),
    tool('risks','Obstacles / Risks','Capture obstacles and risks.',undefined,'workspace'),
    tool('reflection','Reflection Journal','Save goal reflections.','/notes'),
    tool('path','Goal Path','Map Today → Next Milestone → Target.',undefined,'workspace'),
  ],
  projects:[
    tool('dashboard','Project Dashboard','Review active projects.','/projects'),
    tool('milestones','Milestones','Manage project milestones.','/projects'),
    tool('tasks','Tasks','Connect project work to tasks.','/tasks','relationship'),
    tool('files','Files / References','Store project links and reference notes.',undefined,'workspace'),
    tool('notes','Notes','Connect notes to projects.','/notes','relationship'),
    tool('decisions','Decisions','Track project decisions.',undefined,'workspace'),
    tool('deadlines','Deadlines','Review project deadlines.','/projects'),
    tool('people','People / Contacts','Store project contact context without fabricating a contact system.',undefined,'workspace'),
    tool('timeline','Project Timeline','Review milestones and activity over time.','/timeline'),
    tool('manager','AI Project Manager','Create next-action and blocked-work proposals.','/concierge','proposal'),
  ],
  work:[
    tool('dashboard','Work Dashboard','Review shifts, priorities and work projects.','/work'),
    tool('milestones','Milestones','Connect work milestones to projects.','/projects'),
    tool('tasks','Tasks','Review work-tagged tasks.','/tasks'),
    tool('files','Files / References','Store work references.',undefined,'workspace'),
    tool('notes','Notes','Capture work notes.','/notes'),
    tool('decisions','Decisions','Track work decisions.',undefined,'workspace'),
    tool('deadlines','Deadlines','Review deadlines from projects and tasks.','/work'),
    tool('people','People / Contacts','Store work contact context.',undefined,'workspace'),
    tool('timeline','Work Timeline','Review work events over time.','/timeline'),
    tool('manager','AI Work Manager','Create next-action proposals.','/concierge','proposal'),
  ],
  'creative-studio':[
    tool('moodboards','Mood Boards','Store visual direction and notes.',undefined,'workspace'),
    tool('inspiration','Inspiration Library','Capture references.','/resources'),
    tool('brand-boards','Brand Boards','Store brand direction boards.',undefined,'workspace'),
    tool('palette','Color Palette','Save project palettes.',undefined,'workspace'),
    tool('typography','Typography Collections','Save typography direction.',undefined,'workspace'),
    tool('references','Image / Reference Organization','Organize references and links.',undefined,'workspace'),
    tool('canvas','Project Canvas','Open project planning and notes.','/projects'),
    tool('stages','Idea Development','Track idea stages.',undefined,'workspace'),
    tool('archive','Creative Archive','Review completed creative projects.','/projects'),
    tool('presentation','Presentation Mode','Open a clean presentation workspace.',undefined,'workspace'),
  ],
  brain:[
    tool('mind-map','Your Mind Map','Add, edit and remove real Mind Map shortcuts.','/brain'),
    tool('search','Universal Glow Search','Search Glow OS.','/search','search'),
    tool('thoughts','Connected Thoughts','Explore Brain connections.','/brain/connections'),
    tool('captures','Recent Captures','Review recent Intake and Brain captures.','/inbox'),
    tool('interests','Current Interests','Save and organize current interests.',undefined,'workspace'),
    tool('questions','Open Questions','Track questions you are thinking about.',undefined,'workspace'),
    tool('decisions','Decision Tracker','Track decisions and outcomes.',undefined,'workspace'),
    tool('patterns','Detected Patterns','Review grounded observations.','/observations'),
    tool('dump','Brain Dump Processing','Capture and route unstructured thoughts.','/intake'),
    tool('ask-life','Ask Your Life','Search across connected Glow rooms.','/search','search'),
  ],
  'brain-connections':[
    tool('goal-task','Goal ↔ Task','Explore goal and task relationships.','/brain/connections'),
    tool('goal-habit','Goal ↔ Habit','Explore goal and habit relationships.','/brain/connections'),
    tool('wellness-sleep','Wellness ↔ Sleep','Explore wellness relationships.','/brain/connections'),
    tool('finance-beauty','Finance ↔ Beauty','Explore spending and beauty relationships.','/brain/connections'),
    tool('calendar-energy','Calendar ↔ Energy','Explore schedule and energy relationships.','/brain/connections'),
    tool('food-grocery','Food ↔ Grocery','Explore meal and grocery relationships.','/brain/connections'),
    tool('project-notes','Project ↔ Notes','Explore project and note relationships.','/brain/connections'),
    tool('memory-people','Memory ↔ People','Track person context where real records exist.',undefined,'workspace'),
    tool('hair-products','Hair ↔ Products','Explore hair/product relationships.','/brain/connections'),
    tool('explain','Connection Explanation','Review basis, evidence and confidence for a relationship.','/brain/connections'),
  ],
  memory:[
    tool('capture','Memory Capture','Create a real memory.','/memory'),
    tool('photos','Photos','Attach image-supported memory context where available.',undefined,'workspace'),
    tool('notes','Notes','Connect notes to memories.','/notes','relationship'),
    tool('dates','Dates','Store meaningful source dates.','/memory'),
    tool('people','People','Store person context in memory metadata.',undefined,'workspace'),
    tool('places','Places','Store place context in memory metadata.',undefined,'workspace'),
    tool('categories','Categories','Browse memory categories.','/memory'),
    tool('events','Related Life Events','Connect memories to Timeline events.',undefined,'relationship'),
    tool('search','Memory Search','Search memories.','/search','search'),
    tool('story','Memory Story','Build an editable chronological memory story.',undefined,'workspace'),
  ],
  timeline:[
    tool('today','Today','Filter the life timeline to today.','/timeline'),
    tool('week','Week','Review this week on the timeline.','/timeline'),
    tool('month','Month','Review this month on the timeline.','/timeline'),
    tool('year','Year','Review this year on the timeline.','/timeline'),
    tool('life','Life','Review the full life timeline.','/timeline'),
    tool('milestones','Major Milestones','Review milestone events.','/timeline'),
    tool('photos','Photos','Review image-supported timeline events.','/timeline'),
    tool('memories','Memories','Move between Timeline and Memory.','/memory'),
    tool('projects-goals','Projects / Goals','Explore project and goal history.','/timeline'),
    tool('scrubber','Life Scrubber','Save a date focus and review Glow around that period.',undefined,'workspace'),
  ],
  observations:[
    tool('new','New Observations','Review active observations.','/observations'),
    tool('important','Important','Filter important observations.','/observations'),
    tool('positive','Positive Patterns','Review constructive patterns.','/observations'),
    tool('risks','Risks','Review risk signals.','/observations'),
    tool('changes','Changes','Review meaningful changes.','/observations'),
    tool('cross-room','Cross-Room Patterns','Explore related domains.','/graph'),
    tool('evidence','Evidence','Inspect observation evidence.','/observations'),
    tool('confidence','Confidence','Review confidence and time window.','/observations'),
    tool('manage','Dismiss / Snooze / Save','Use the real observation state controls.','/observations'),
    tool('action','Turn Into Action','Create a reversible action proposal from an observation.','/concierge','proposal'),
  ],
  concierge:[
    tool('suggested','Suggested Actions','Review suggested actions.','/concierge'),
    tool('pending','Pending Approvals','Review pending AI proposals.','/concierge'),
    tool('completed','Completed Actions','Review completed proposals.','/concierge'),
    tool('followups','Follow-Ups','Track follow-up work.',undefined,'workspace'),
    tool('scheduling','Scheduling Proposals','Create reversible scheduling proposals.',undefined,'proposal'),
    tool('research','Research Proposals','Capture research requests and outputs.',undefined,'workspace'),
    tool('prep','Preparation Checklists','Build preparation checklists.',undefined,'workspace'),
    tool('drafts','Draft Communications','Prepare drafts without sending them automatically.',undefined,'workspace'),
    tool('plans','Multi-Step Action Plans','Build editable multi-step plans.',undefined,'workspace'),
    tool('approval','Approval Center','Review and decide consequential proposals.','/concierge'),
  ],
  briefings:[
    tool('hero','Today’s Hero','Open the current briefing.','/briefings'),
    tool('schedule','Schedule Highlights','Review today’s important events.','/calendar'),
    tool('priority','Top Priority','Review the highest-priority task.','/tasks'),
    tool('wellness','Wellness Reminder','Open today’s wellness status.','/wellness'),
    tool('meals','Meals','Review today’s meal plan.','/food'),
    tool('mood','Mood Check-In','Log today’s mood.','/wellness'),
    tool('alerts','Important Alerts','Review notices needing attention.','/notices'),
    tool('free-time','Free-Time Opportunities','Find open windows in the calendar.','/calendar','search'),
    tool('context','Weather / Context','Save context relevant to today.',undefined,'workspace'),
    tool('insight','Glow Insight','Review one concise grounded insight.','/brain/insights'),
  ],
  'evening-debrief':[
    tool('completed','Completed Today','Review completed work.','/briefings/evening'),
    tool('missed','Missed Today','Review unfinished items.','/briefings/evening'),
    tool('schedule','Schedule Recap','Review today’s calendar.','/calendar'),
    tool('habits','Habit / Routine Completion','Review habit and routine completion.','/habits'),
    tool('wellness','Wellness Summary','Review today’s wellness.','/wellness'),
    tool('mood','Mood Reflection','Save today’s mood reflection.','/briefings/evening','review'),
    tool('wins','Meaningful Wins','Capture wins worth remembering.','/memory'),
    tool('attention','Needs Attention','Review carry-forward decisions.','/briefings/evening'),
    tool('carry','Tomorrow Carry-Forward','Approve or edit tomorrow items.','/tomorrow'),
    tool('close','Close the Day','Finalize the real day review.','/briefings/evening','review'),
  ],
  'weekly-debrief':[
    tool('summary','Week Summary','Review the week.','/briefings'),
    tool('wins','Accomplishments','Capture meaningful wins.','/memory'),
    tool('missed','Missed Priorities','Review unfinished priorities.','/tasks'),
    tool('habits','Habit Consistency','Review weekly habit patterns.','/habits'),
    tool('wellness','Wellness','Review weekly wellness.','/wellness'),
    tool('spending','Spending','Review weekly finance activity.','/finance'),
    tool('fitness','Fitness','Review weekly fitness.','/fitness'),
    tool('projects','Project Progress','Review project status.','/projects'),
    tool('lessons','Lessons / Patterns','Capture a weekly reflection.',undefined,'review'),
    tool('next-week','Next-Week Recommendations','Create an editable next-week proposal.',undefined,'proposal'),
  ],
  'monthly-debrief':[
    tool('story','Month Story','Review the month as a narrative.','/timeline'),
    tool('wins','Major Accomplishments','Capture month highlights.','/memory'),
    tool('goals','Goal Progress','Review goals.','/goals'),
    tool('finance','Financial Summary','Review monthly finances.','/finance'),
    tool('wellness','Wellness Trends','Review wellness trends.','/graph'),
    tool('fitness','Fitness Progress','Review fitness history.','/fitness'),
    tool('beauty-hair','Beauty / Hair Progress','Review Beauty and Hair history.','/beauty'),
    tool('memories','Memories','Review memories from the month.','/memory'),
    tool('changes','Life Changes','Capture meaningful changes.','/timeline'),
    tool('next-chapter','Next Chapter','Create an editable plan for the next month.',undefined,'proposal'),
  ],
  home:[
    tool('dashboard','Home Dashboard','Review home-related tasks and routines.','/home'),
    tool('cleaning','Cleaning','Review cleaning tasks and routines.','/home'),
    tool('laundry','Laundry','Track laundry work.','/home'),
    tool('maintenance','Maintenance','Review home maintenance needs.','/maintenance'),
    tool('inventory','Inventory','Track household inventory.',undefined,'workspace'),
    tool('shopping','Shopping','Capture household shopping needs.','/intake'),
    tool('rooms','Rooms','Organize home responsibilities by room.',undefined,'workspace'),
    tool('projects','Home Projects','Connect household work to Projects.','/projects','relationship'),
    tool('routines','Household Routines','Review household routines.','/routines'),
    tool('reset','Home Reset','Create a prioritized reset proposal.',undefined,'proposal'),
  ],
  'all-rooms':[
    tool('all','Every Room','Browse every registered room.','/all-rooms'),
    tool('favorites','Favorites','Save room favorites.',undefined,'workspace'),
    tool('recent','Recently Used','Review recent destinations.',undefined,'workspace'),
    tool('suggested','Suggested Rooms','Create room suggestions from current context.',undefined,'proposal'),
    tool('categories','Categories','Browse room categories.','/all-rooms'),
    tool('search','Search Rooms','Search Glow OS rooms.','/search','search'),
    tool('reorder','Reordering','Save a preferred room order.',undefined,'workspace'),
    tool('pin','Pinning','Save pinned room shortcuts.',undefined,'workspace'),
    tool('descriptions','Room Status','Review descriptions and connection status.','/all-rooms'),
    tool('shortcuts','Custom Shortcuts','Create custom room shortcuts.',undefined,'workspace'),
  ],
  notices:[
    tool('today','Today','Review today’s notices.','/notices'),
    tool('important','Important','Review priority notices.','/notices'),
    tool('upcoming','Upcoming','Review upcoming notices.','/notices'),
    tool('overdue','Overdue','Review overdue attention items.','/notices'),
    tool('finance','Finance','Review financial notices.','/notices'),
    tool('health','Health & Care','Review health/care notices.','/notices'),
    tool('projects','Projects','Review project notices.','/notices'),
    tool('connections','Connections','Review connection/sync notices.','/connections'),
    tool('snoozed','Snoozed','Review snoozed notices.','/notices'),
    tool('resolve','Resolve Center','Act on notices instead of only dismissing them.','/notices'),
  ],
  graph:[
    tool('person','Person Node','Keep the user as the center of the relationship graph.','/graph'),
    tool('goals','Goals','Filter graph relationships to goals.','/graph'),
    tool('projects','Projects','Filter graph relationships to projects.','/graph'),
    tool('tasks','Tasks','Filter graph relationships to tasks.','/graph'),
    tool('habits','Habits','Filter graph relationships to habits.','/graph'),
    tool('people','People','Store person-context entities when real records exist.',undefined,'workspace'),
    tool('memories','Memories','Explore graph-connected memories.','/graph'),
    tool('places','Places','Store place-context entities when real records exist.',undefined,'workspace'),
    tool('domains','Life Domains','Filter by Glow domain.','/graph'),
    tool('filters','Relationship Filters','Use interactive graph filtering.','/graph'),
  ],
  gmail:[
    tool('priority','Priority Emails','Review the priority inbox.','/gmail'),
    tool('response','Needs Response','Review messages that need a reply.','/gmail'),
    tool('waiting','Waiting for Reply','Track conversations awaiting follow-up.',undefined,'workspace'),
    tool('appointments','Appointments','Convert relevant email context into Calendar.','/calendar'),
    tool('orders','Orders / Receipts','Capture order/receipt context.','/intake'),
    tool('career','Career Messages','Organize career-related mail context.',undefined,'workspace'),
    tool('projects','Project Messages','Connect email context to Projects.','/projects'),
    tool('search','Search Email','Search Gmail through the real integration.','/gmail'),
    tool('convert','Email → Action','Create a task, event or project from message context.','/gmail'),
    tool('intelligence','Inbox Intelligence','Summarize what truly needs attention.','/gmail'),
  ],
  import:[
    tool('files','Import Files','Use the real import surface.','/import'),
    tool('notes','Import Notes','Import note content.','/import'),
    tool('calendar','Import Calendars','Import supported calendar data.','/import'),
    tool('tasks','Import Tasks','Import task content.','/import'),
    tool('contacts','Import Contacts','Stage contact-like data without claiming a contact system.',undefined,'workspace'),
    tool('sheets','Import Spreadsheets','Import supported spreadsheet data.','/import'),
    tool('preview','Preview Mapping','Review proposed destination mapping.','/import'),
    tool('duplicates','Duplicate Detection','Review potential duplicates before routing.','/import'),
    tool('errors','Error Review','Review import failures.','/import'),
    tool('classification','Classification Preview','Preview Glow classification before committing.','/import'),
  ],
  connections:[
    tool('google','Google','Manage Google connection state.','/connections'),
    tool('gmail','Gmail','Review Gmail connection state.','/connections'),
    tool('calendar','Calendar','Review Calendar connection state.','/connections'),
    tool('apple','Apple Reminders','Manage Apple Reminders setup.','/connections'),
    tool('health','Health / Data Sources','Review supported health/data source status.','/connections'),
    tool('status','Connection Status','Review health and permission state.','/connections'),
    tool('last-sync','Last Sync','Review last synchronization timestamps.','/connections'),
    tool('permissions','Permissions','Review available scopes and permissions.','/connections'),
    tool('history','Sync History / Errors','Review connection problems.','/connections'),
    tool('flow','Data Flow Map','Document which rooms each connection supplies.',undefined,'workspace'),
  ],
  notes:[
    tool('rich','Rich Notes','Create and edit notes.','/notes'),
    tool('quick','Quick Notes','Capture a note quickly.','/notes'),
    tool('voice','Voice Notes','Use global Voice to capture note content.','/notes'),
    tool('files','Photos / Files','Store reference links or image-supported context.',undefined,'workspace'),
    tool('notebooks','Notebooks','Organize notes into collections.',undefined,'workspace'),
    tool('tags','Tags','Use note intelligence tags.','/notes'),
    tool('pinned','Pinned Notes','Review pinned notes.','/notes'),
    tool('search','Search Notes','Search notes.','/search','search'),
    tool('linking','Note Linking','Connect a note to another Glow object.',undefined,'relationship'),
    tool('convert','Convert Note','Route a note into task, project, goal, event, memory or Brain.','/intake'),
  ],
  intake:[
    tool('type','Type Anything','Capture text.','/intake'),
    tool('speak','Speak Anything','Use global Voice capture.','/intake'),
    tool('image','Upload Image','Upload supported image content.','/intake'),
    tool('document','Upload Document','Upload supported document content.','/intake'),
    tool('link','Paste Link','Capture a link for classification.','/intake'),
    tool('scan','Scan Information','Upload/capture information for classification.','/intake'),
    tool('classification','Glow Classification','Review classification output.','/intake'),
    tool('destination','Destination Recommendation','Review proposed destinations.','/intake'),
    tool('preview','Preview Before Saving','Review before routing.','/intake'),
    tool('route','Route It','Send the item to its real Glow destination.','/intake'),
  ],
  rules:[
    tool('planning','Planning Rules','Create planning behavior rules.','/rules'),
    tool('scheduling','Scheduling Rules','Create scheduling boundaries.','/rules'),
    tool('wellness','Wellness Boundaries','Create wellness-related rules.','/rules'),
    tool('spending','Spending Rules','Create finance boundaries.','/rules'),
    tool('work','Work Preferences','Save work behavior preferences.','/rules'),
    tool('routine','Routine Preferences','Save routine behavior rules.','/rules'),
    tool('notifications','Notification Preferences','Save notification behavior rules.','/rules'),
    tool('ai','AI Behavior Rules','Define how Glow may suggest or act.','/rules'),
    tool('temporary','Temporary Rules','Create time-bound rule notes.',undefined,'workspace'),
    tool('explain','Explain This Rule','Document where and why a rule is used.',undefined,'workspace'),
  ],
  world:[
    tool('model','Architectural Model','Explore the Life World.','/world'),
    tool('buildings','Domain Buildings','Navigate to major life domains.','/world'),
    tool('focus','Current Focus','Highlight the current focus domain.',undefined,'workspace'),
    tool('goals','Goal Landmarks','Connect Goals to Life World landmarks.',undefined,'relationship'),
    tool('memories','Memory Landmarks','Connect Memories to Life World landmarks.',undefined,'relationship'),
    tool('chapters','Life Chapters','Connect Timeline chapters to the world.',undefined,'relationship'),
    tool('timeline','Timeline Integration','Move between Life World and Timeline.','/timeline'),
    tool('zoom','World Zoom','Save preferred world focus/zoom state.',undefined,'workspace'),
    tool('explore','Explore Mode','Open the richer visual exploration mode.','/world'),
    tool('transitions','Room Transitions','Use clean object-continuity navigation.','/world'),
  ],
  search:[
    tool('everything','Search Everything','Search all indexed Glow entities.','/search'),
    tool('room','Filter by Room','Filter results by room/type.','/search'),
    tool('people','Search People','Search person-context entities where they exist.','/search'),
    tool('dates','Search Dates','Search date-oriented records.','/search'),
    tool('memories','Search Memories','Search memory records.','/search'),
    tool('tasks-projects','Tasks / Projects','Search tasks and projects.','/search'),
    tool('notes-files','Notes / Files','Search notes and references.','/search'),
    tool('recent','Recent Searches','Save recent search context.',undefined,'workspace'),
    tool('suggested','Suggested Queries','Save useful recurring queries.',undefined,'workspace'),
    tool('ask-glow','Ask Glow','Use natural-language search alongside exact matches.','/search'),
  ],
  settings:[
    tool('profile','Profile','Manage profile settings.','/settings?section=profile'),
    tool('appearance','Appearance','Manage appearance.','/settings?section=appearance'),
    tool('personality','Glow Personality','Manage intelligence style/preferences.','/settings'),
    tool('notifications','Notifications','Manage notification settings.','/settings'),
    tool('connections','Connections','Manage integrations.','/connections'),
    tool('privacy','Privacy','Manage privacy settings.','/settings'),
    tool('ai-permissions','AI Permissions','Control what Glow may suggest or act on.','/settings/intelligence'),
    tool('data','Data Controls','Manage imports/exports and data controls.','/settings'),
    tool('motion','Motion / Accessibility','Manage reduced motion and interface preferences.','/settings?section=appearance'),
    tool('control-center','Glow Control Center','Review intelligence capabilities and permissions.','/settings/intelligence'),
  ],
};

export function upgradesForRoom(roomKey:string){
  return ROOM_UPGRADES[roomKey] ?? [];
}
