export type SystemRoom = {
  key: string;
  label: string;
  path: string;
  purpose: string;
  atmosphere: string;
  accent: string;
  connected: string[];
  capabilities: string[];
};

export const SYSTEM_ROOMS: SystemRoom[] = [
  { key: 'dashboard', label: 'Home', path: '/dashboard', purpose: 'Living command center that decides what deserves attention.', atmosphere: 'Command salon', accent: 'rose', connected: ['today','brain','calendar','planning','world'], capabilities: ['Daily decision HUD','Adaptive widgets','Life health','Glow notices'] },
  { key: 'today', label: 'Today', path: '/today', purpose: 'Operational surface for the next best action and focus execution.', atmosphere: 'Focus desk', accent: 'rose', connected: ['tasks','calendar','habits','fitness','wellness','brain'], capabilities: ['Now Engine','Life Modes','Focus sessions','Finish My Day'] },
  { key: 'tasks', label: 'Tasks', path: '/tasks', purpose: 'Execution system for actions, dependencies, urgency, effort and next steps.', atmosphere: 'Execution desk', accent: 'slate', connected: ['calendar','projects','goals','brain','today'], capabilities: ['Dependencies','Time estimates','Context fit','Blocked/unblocked work'] },
  { key: 'calendar', label: 'Calendar', path: '/calendar', purpose: 'Scheduling intelligence that protects time and understands commitments.', atmosphere: 'Scheduling wall', accent: 'sky', connected: ['tasks','planning','fitness','beauty','projects','brain'], capabilities: ['Commitments','Travel buffers','Available blocks','Schedule conflict intelligence'] },
  { key: 'planning', label: 'Plan', path: '/planning', purpose: 'Connect today, week, month, quarter and year to goals and projects.', atmosphere: 'Planning atelier', accent: 'amber', connected: ['goals','projects','calendar','today','briefings'], capabilities: ['Today/Week/Quarter/Year','Build My Day','Prepare Tomorrow','Review cadence'] },
  { key: 'habits', label: 'Habits', path: '/habits', purpose: 'Behavior intelligence for consistency, context, streak quality and patterns.', atmosphere: 'Ritual garden', accent: 'emerald', connected: ['routines','wellness','today','observations','brain'], capabilities: ['Streaks','Context patterns','Friction signals','Adaptive targets'] },
  { key: 'fitness', label: 'Fitness', path: '/fitness', purpose: 'Training studio that adapts workouts to energy, time, recovery and schedule.', atmosphere: 'Training studio', accent: 'blue', connected: ['wellness','calendar','today','habits','goals'], capabilities: ['Workout intelligence','Recovery','Progress','Time-aware alternatives'] },
  { key: 'beauty', label: 'Beauty', path: '/beauty', purpose: 'Luxury vanity for routines, maintenance, appointments and visible progress.', atmosphere: 'Luxury vanity', accent: 'rose', connected: ['beauty-lab','hair','calendar','finance','wellness'], capabilities: ['AM/PM routines','Maintenance','Progress','Appointment intelligence'] },
  { key: 'beauty-lab', label: 'Beauty Lab', path: '/beauty/lab', purpose: 'Product laboratory for ingredients, inventory, reactions, cost and repurchase.', atmosphere: 'Skincare laboratory', accent: 'amber', connected: ['beauty','finance','wellness','memory'], capabilities: ['Inventory','Ingredients','Reactions','Expiration and repurchase'] },
  { key: 'hair', label: 'Hair', path: '/hair', purpose: 'Maintenance studio for wash cycles, products, heat, styles and appointments.', atmosphere: 'Hair studio', accent: 'amber', connected: ['beauty','calendar','finance','memory','today'], capabilities: ['Wash forecast','Style history','Product tracking','Maintenance timing'] },
  { key: 'wellness', label: 'Wellness', path: '/wellness', purpose: 'Energy and recovery intelligence spanning sleep, mood, hydration and care.', atmosphere: 'Recovery suite', accent: 'emerald', connected: ['fitness','habits','today','health','brain'], capabilities: ['Energy','Sleep','Mood','Hydration'] },
  { key: 'health', label: 'Health', path: '/health', purpose: 'Private care hub for medications, supplements and health routines.', atmosphere: 'Care cabinet', accent: 'emerald', connected: ['wellness','calendar','today','memory'], capabilities: ['Medication visibility','Supplements','Care schedule','Health context'] },
  { key: 'finance', label: 'Finance', path: '/finance', purpose: 'Calm money office for transactions, categories, budgets and spending context.', atmosphere: 'Private money office', accent: 'emerald', connected: ['financial-brain','beauty','projects','goals','closet'], capabilities: ['Spending','Budget context','Category trends','Expected costs'] },
  { key: 'financial-brain', label: 'Financial Brain', path: '/finance/brain', purpose: 'Forecasting and decision layer for savings, goals, cash flow and purchases.', atmosphere: 'Strategy office', accent: 'emerald', connected: ['finance','goals','projects','brain'], capabilities: ['Cash flow','Savings goals','Scenarios','Purchase decisions'] },
  { key: 'goals', label: 'Goals', path: '/goals', purpose: 'Outcome system connecting ambitions to projects, habits and measurable progress.', atmosphere: 'Vision gallery', accent: 'violet', connected: ['projects','planning','habits','finance','brain'], capabilities: ['Milestones','Progress quality','Support systems','Goal health'] },
  { key: 'projects', label: 'Projects', path: '/projects', purpose: 'Creative studio for milestones, blockers, files, velocity and next action.', atmosphere: 'Creative studio', accent: 'violet', connected: ['tasks','goals','calendar','memory','brain'], capabilities: ['Health signal','Velocity','Blockers','Next meaningful action'] },
  { key: 'brain', label: 'Glow Brain', path: '/brain', purpose: 'Central conductor that reasons across every Glow OS system.', atmosphere: 'Intelligence salon', accent: 'violet', connected: ['dashboard','today','world','observations','memory'], capabilities: ['Cross-system answers','Decision support','Recommendations','Context synthesis'] },
  { key: 'world', label: 'World', path: '/world', purpose: 'Spatial map of every life system as connected rooms in one digital world.', atmosphere: 'Life world', accent: 'stone', connected: ['dashboard','brain','projects','beauty','finance','memory'], capabilities: ['Room map','Status visualization','Spatial navigation','Future XR'] },
  { key: 'connections', label: 'Connections', path: '/connections', purpose: 'Control center for external accounts, sync health and data permissions.', atmosphere: 'Connection dock', accent: 'sky', connected: ['calendar','gmail','inbox','brain'], capabilities: ['Account status','Sync health','Permissions','Import bridges'] },
  { key: 'notes', label: 'Notes', path: '/notes', purpose: 'Knowledge workspace for ideas, references, brain dumps and linked thinking.', atmosphere: 'Writing library', accent: 'amber', connected: ['memory','projects','brain','inbox'], capabilities: ['Knowledge capture','Search','Linked notes','Reference storage'] },
  { key: 'settings', label: 'Settings', path: '/settings', purpose: 'Control how Glow behaves, looks, prioritizes and protects information.', atmosphere: 'Control wardrobe', accent: 'stone', connected: ['dashboard','world','brain'], capabilities: ['Rules','Visual preferences','Privacy','System behavior'] },
  { key: 'concierge', label: 'Concierge', path: '/concierge', purpose: 'Approval-based action layer that proposes safe changes across the OS.', atmosphere: 'Concierge desk', accent: 'violet', connected: ['brain','planning','calendar','tasks'], capabilities: ['Proposals','Approval','Reversible changes','Audit history'] },
  { key: 'observations', label: 'Glow Notices', path: '/observations', purpose: 'Pattern intelligence that explains evidence and suggests useful changes.', atmosphere: 'Observation gallery', accent: 'rose', connected: ['habits','wellness','finance','projects','brain'], capabilities: ['Pattern detection','Evidence','Apply/Snooze/Dismiss','Confidence'] },
  { key: 'memory', label: 'Memory', path: '/memory', purpose: 'Private archive of meaningful facts, experiences, decisions and context.', atmosphere: 'Memory library', accent: 'amber', connected: ['timeline','projects','notes','brain'], capabilities: ['Automatic capture','Privacy levels','Corrections','Related entities'] },
  { key: 'timeline', label: 'Timeline', path: '/timeline', purpose: 'Life gallery showing events, milestones, projects and memories over time.', atmosphere: 'Life gallery', accent: 'rose', connected: ['memory','projects','goals','briefings'], capabilities: ['Automatic events','Milestones','Zoomed history','Related memories'] },
  { key: 'briefings', label: 'Briefings', path: '/briefings', purpose: 'Morning, evening and weekly synthesis of what changed and what matters.', atmosphere: 'Editorial briefing room', accent: 'amber', connected: ['today','planning','brain','calendar'], capabilities: ['Morning brief','Evening review','Weekly review','Prepare Tomorrow'] },
  { key: 'closet', label: 'Closet', path: '/closet', purpose: 'Digital wardrobe for inventory, outfits, laundry, weather and cost-per-wear.', atmosphere: 'Wardrobe room', accent: 'rose', connected: ['calendar','finance','world','travel'], capabilities: ['Inventory','Outfits','Laundry','Cost per wear'] },
  { key: 'gmail', label: 'Gmail', path: '/gmail', purpose: 'Read-only communication intelligence that surfaces messages needing action.', atmosphere: 'Correspondence desk', accent: 'sky', connected: ['tasks','projects','calendar','inbox'], capabilities: ['Actionable mail','Task creation','Project linking','Follow-up cues'] },
  { key: 'home', label: 'Home', path: '/home', purpose: 'Household operating system for resets, maintenance, supplies and environment.', atmosphere: 'Home room', accent: 'stone', connected: ['tasks','calendar','finance','today'], capabilities: ['Resets','Maintenance','Supplies','Household rhythms'] },
  { key: 'import', label: 'Import', path: '/import', purpose: 'Structured migration center for bringing existing life data into Glow safely.', atmosphere: 'Intake dock', accent: 'sky', connected: ['inbox','connections','brain'], capabilities: ['Preview','Deduplication','Selection','Undo'] },
  { key: 'inbox', label: 'Glow Inbox', path: '/inbox', purpose: 'Universal capture layer that turns messy input into structured life data.', atmosphere: 'Universal intake desk', accent: 'rose', connected: ['tasks','notes','calendar','projects','brain'], capabilities: ['Text capture','Classification','Routing','Universal intake'] },
  { key: 'resources', label: 'Resources', path: '/resources', purpose: 'Reusable reference library for routines, reset plans, treatments and guides.', atmosphere: 'Reference library', accent: 'amber', connected: ['today','planning','fitness','beauty','travel'], capabilities: ['5/15/30 minute resets','Routine guides','Workout library','Travel and emergency references'] },
];

export function getSystemRoom(pathname: string) {
  return [...SYSTEM_ROOMS].sort((a, b) => b.path.length - a.path.length).find((room) => pathname === room.path || pathname.startsWith(`${room.path}/`)) ?? null;
}

export function getSystemRoomByKey(key: string) {
  return SYSTEM_ROOMS.find((room) => room.key === key) ?? null;
}
