export type SystemRoom = {
  key: string;
  label: string;
  path: string;
  purpose: string;
  atmosphere: string;
  accent: string;
  connected: string[];
  capabilities: string[];
};

export const SYSTEM_ROOMS: SystemRoom[] = [
  { key: 'dashboard', label: 'Today Gateway', path: '/dashboard', purpose: 'Legacy entry that resolves into the continuous Glow world rather than a separate dashboard.', atmosphere: 'Threshold into the Living Center', accent: 'pearl', connected: ['today','brain','calendar','planning','world','create'], capabilities: ['Orientation','Continuous-world entry','Glow presence'] },
  { key: 'today', label: 'Today · The Living Center', path: '/today', purpose: 'The live center of the present moment, organized as Now, Next, Later, Tonight and Tomorrow.', atmosphere: 'Pearlescent dawn with living light', accent: 'pearl-blush', connected: ['tasks','calendar','habits','fitness','wellness','brain','create'], capabilities: ['What Now','Capacity','Top three priorities','Routines due now','Time remaining','Leave-ready countdown','Replan preview'] },
  { key: 'tasks', label: 'Tasks · Action Workshop', path: '/tasks', purpose: 'Actions organized by readiness, energy, preparation, waiting and focus rather than a flat list.', atmosphere: 'Precise Glow Matter workbench', accent: 'cool-pearl', connected: ['calendar','projects','goals','brain','today'], capabilities: ['Readiness zones','Dependencies','Time estimates','Energy cost','Blocked/unblocked work','Pearl completion'] },
  { key: 'calendar', label: 'Calendar · Time Observatory', path: '/calendar', purpose: 'An architectural map of time where commitments, preparation, travel and free space remain connected.', atmosphere: 'Lilac-blue observatory', accent: 'lilac-blue', connected: ['tasks','planning','fitness','food','beauty','projects','brain'], capabilities: ['Time vessels','Preparation shadows','Travel buffers','Free-space visibility','Conflict intelligence','Schedule comparison'] },
  { key: 'planning', label: 'Plan · The Time Observatory', path: '/planning', purpose: 'The planning climate where present, near future and distant commitments become one navigable time surface.', atmosphere: 'Frosted pearl and cool silver architecture', accent: 'lilac-blue', connected: ['goals','projects','calendar','food','today','briefings'], capabilities: ['Daily planning','Weekly planning','Monthly planning','Scenario comparison','Guided planning','Approval before commitment'] },
  { key: 'habits', label: 'Habits · Rhythm Garden', path: '/habits', purpose: 'Behavior grows through rhythm and accumulated atmosphere without punitive streak visuals.', atmosphere: 'Organic rings of living light', accent: 'sage-pearl', connected: ['wellness','fitness','food','today','observations','brain'], capabilities: ['Flexible frequency','Minimum/ideal versions','Recovery rules','Context patterns','Optional streaks'] },
  { key: 'routines', label: 'Routines · Guided Pathway', path: '/routines', purpose: 'Sequences unfold as guided pathways with one active step illuminated.', atmosphere: 'Flowing pearl pathway', accent: 'champagne', connected: ['today','planning','beauty','hair','fitness'], capabilities: ['Full version','Quick version','Low-energy version','Timers','Voice guidance','Products','Adaptive skip behavior'] },
  { key: 'fitness', label: 'Fitness · Movement Studio', path: '/fitness', purpose: 'An active room where workout days open into ordered movement pathways.', atmosphere: 'Warm morning light and pale coral rhythm', accent: 'coral-silver', connected: ['wellness','food','calendar','today','habits','goals'], capabilities: ['Workout doors','Exercise sequence','Recovery','Rest timing','Spoken coaching','Low-energy modifications'] },
  { key: 'wellness', label: 'Wellness · Restoration Room', path: '/wellness', purpose: 'A slow restorative room for sleep, hydration, mood, recovery and gentle care.', atmosphere: 'Soft peach, mineral white and water light', accent: 'mineral-peach', connected: ['fitness','food','habits','today','brain'], capabilities: ['Rest','Sleep','Mood','Hydration','Recovery','Gentle check-ins'] },
  { key: 'food', label: 'Food · Personal Kitchen', path: '/food', purpose: 'A warm kitchen organized around what to eat, cook, prepare, use soon, shop and save.', atmosphere: 'Cream stone and afternoon light', accent: 'herb-cream', connected: ['fitness','wellness','calendar','finance','home','brain'], capabilities: ['Eat now','Cook','Prepare','Use soon','Shop','Saved recipes','Budget context'] },
  { key: 'beauty', label: 'Beauty · Command Center', path: '/beauty', purpose: 'Getting-ready intelligence organized around the current event and leave-ready time.', atmosphere: 'Refined vanity daylight and mirror reflections', accent: 'champagne-pearl', connected: ['beauty-lab','hair','calendar','finance','wellness'], capabilities: ['Skin','Hair','Makeup','Body','Fragrance','Final look','Event-aware preparation'] },
  { key: 'beauty-lab', label: 'Skincare · Treatment Laboratory', path: '/beauty/lab', purpose: 'Calm treatment intelligence where safety, prescriptions and compatibility outrank aesthetics.', atmosphere: 'Milk glass and cool water clarity', accent: 'milk-blue', connected: ['beauty','hair','finance','wellness','memory'], capabilities: ['Products','Prescriptions','Ingredient conflicts','Sensitivity','Rotation','Patch testing','Progress'] },
  { key: 'hair', label: 'Hair · Private Salon', path: '/hair', purpose: 'A salon and archive where today’s hair state, style, wash cycle, products and history stay connected.', atmosphere: 'Warm ivory with glossy directional reflections', accent: 'warm-ivory', connected: ['beauty','beauty-lab','calendar','finance','memory','today'], capabilities: ['Hair state','Style plan','Wash schedule','Routine pathway','Products','History','Section maps','Maintenance'] },
  { key: 'finance', label: 'Money · Clarity Chamber', path: '/finance', purpose: 'A private, precise money room where numbers remain primary and motion stays restrained.', atmosphere: 'Cool mint, ivory ledger and clean silver', accent: 'mint-silver', connected: ['financial-brain','food','beauty','projects','goals','closet'], capabilities: ['Available','Committed','Upcoming','Saving','Flexible spending','Financial attention'] },
  { key: 'financial-brain', label: 'Money · Decision Layer', path: '/finance/brain', purpose: 'Precise forecasting and scenario reasoning attached to the Money clarity chamber.', atmosphere: 'Stable cool mint layers', accent: 'mint', connected: ['finance','goals','projects','brain'], capabilities: ['Cash flow','Savings goals','Scenarios','Purchase decisions'] },
  { key: 'goals', label: 'Goals · Horizon', path: '/goals', purpose: 'Goals exist as distant illuminated landmarks that become clearer with real evidence.', atmosphere: 'Open horizon with distant living light', accent: 'violet-pearl', connected: ['projects','planning','habits','finance','brain'], capabilities: ['Emotional reason','Milestones','Evidence','Flexible/fixed targets','Review cadence'] },
  { key: 'projects', label: 'Projects · Project Room', path: '/projects', purpose: 'A project environment with a central working table and connected actions, notes, files, decisions and blockers.', atmosphere: 'Structured pearl project room', accent: 'violet', connected: ['tasks','goals','calendar','memory','brain','create'], capabilities: ['Next actions','Notes','Files','Timeline','Decisions','People','Inspiration','Blockers'] },
  { key: 'brain', label: 'Brain · The Inner Universe', path: '/brain', purpose: 'A deep navigable inner world of notes, memories, thoughts, ideas, insights and connections.', atmosphere: 'Midnight indigo, smoky violet and pearl-white lantern light', accent: 'indigo-violet', connected: ['today','food','world','observations','memory','notes','create'], capabilities: ['Constellations','Threads','Clusters','Pattern reasoning','Decision support','Context synthesis'] },
  { key: 'create', label: 'Create · The Transformation Studio', path: '/create', purpose: 'An open atelier where ideas move from mist into notes, images, plans, projects and other stable forms.', atmosphere: 'Bright neutral pearl with visible prismatic formation', accent: 'prismatic-pearl', connected: ['capture','projects','notes','inbox','import','gmail','today','brain'], capabilities: ['Capture','Creative Studio','Writing','Images','Mood boards','Import','File transformation','Mist to Structure'] },
  { key: 'concierge', label: 'Concierge · Planning Salon', path: '/concierge', purpose: 'A private cross-world planning salon that keeps one evolving master plan and requests approval for meaningful changes.', atmosphere: 'Composed private salon', accent: 'champagne-violet', connected: ['brain','planning','calendar','tasks','food'], capabilities: ['Master plan','Proposals','Approval','Reversible changes','Audit history'] },
  { key: 'observations', label: 'Attention · Quiet Signals', path: '/observations', purpose: 'Evidence-based attention separated into now, soon, waiting, possible concern, quiet suggestion and safe to ignore.', atmosphere: 'Composed briefing light', accent: 'rose-pearl', connected: ['habits','wellness','food','finance','projects','brain'], capabilities: ['Needs attention now','Soon','Waiting','Possible concern','Quiet suggestion','Safe to ignore'] },
  { key: 'notices', label: 'Attention Center', path: '/notices', purpose: 'A composed briefing room for what deserves attention without alarmist dashboard behavior.', atmosphere: 'Quiet briefing chamber', accent: 'rose-pearl', connected: ['today','observations','brain'], capabilities: ['Now','Soon','Waiting','Concern','Suggestion','Safe to ignore'] },
  { key: 'memory', label: 'Memory · Cinematic Archive', path: '/memory', purpose: 'A private cinematic archive where memories surface through photographs, film, sounds, places and atmosphere.', atmosphere: 'Cinematic twilight and subtle grain', accent: 'twilight', connected: ['timeline','projects','notes','brain'], capabilities: ['Timeline','Film roll','Map','Person','Life chapter','Sensitive-memory controls'] },
  { key: 'timeline', label: 'Timeline · River of Time', path: '/timeline', purpose: 'Past flows behind, present glows at center and plans extend lightly ahead.', atmosphere: 'Flowing cinematic time', accent: 'pearl-twilight', connected: ['memory','projects','goals','briefings'], capabilities: ['Life chapters','Event types','Scale','Photos','History','Privacy'] },
  { key: 'briefings', label: 'Today · Briefings', path: '/briefings', purpose: 'Morning, evening and weekly synthesis that opens and closes the day ceremonially.', atmosphere: 'Curtain light shifting toward twilight', accent: 'pearl', connected: ['today','planning','brain','calendar','food'], capabilities: ['Morning Brief','Evening Debrief','Weekly Review','Prepare Tomorrow'] },
  { key: 'closet', label: 'Closet · Personal Wardrobe', path: '/closet', purpose: 'A translucent wardrobe where clothing hangs and layers spatially rather than becoming database cards.', atmosphere: 'Ivory fabric, clear glass and silver rails', accent: 'ivory-silver', connected: ['calendar','finance','world','beauty'], capabilities: ['Inventory','Outfits','Laundry','Fit notes','Alterations','Weather/event coordination'] },
  { key: 'gmail', label: 'Gmail · Correspondence Source', path: '/gmail', purpose: 'Communication enters Glow as context for work, projects, planning and capture rather than becoming a separate productivity island.', atmosphere: 'Quiet correspondence edge of Create', accent: 'sky-pearl', connected: ['tasks','projects','calendar','inbox','create'], capabilities: ['Actionable mail','Task creation','Project linking','Follow-up cues'] },
  { key: 'world', label: 'Life · The Personal House', path: '/world', purpose: 'A connected suite of Body, Beauty, Closet, Food, Home, Money, Work, Relationships and Travel.', atmosphere: 'Private connected rooms with gradual thresholds', accent: 'pearl-stone', connected: ['today','brain','food','projects','beauty','finance','memory','create'], capabilities: ['Room thresholds','Life contexts','Spatial navigation','Glow adaptation'] },
  { key: 'home', label: 'Home · Living Floor Plan', path: '/home', purpose: 'Physical rooms themselves become navigation for cleaning, maintenance, inventory and design projects.', atmosphere: 'Polished stone and warm architectural daylight', accent: 'stone-champagne', connected: ['tasks','calendar','food','finance','today','world'], capabilities: ['Rooms','Cleaning','Maintenance','Inventory','Design projects','Household rhythms'] },
  { key: 'connections', label: 'Connections · Integration Dock', path: '/connections', purpose: 'A quiet system surface for account connections, sync health and permissions.', atmosphere: 'Neutral integration dock', accent: 'cool-silver', connected: ['calendar','gmail','inbox','brain'], capabilities: ['Account status','Sync health','Permissions','Import bridges'] },
  { key: 'notes', label: 'Notes · Refined Writing Desk', path: '/notes', purpose: 'Writing stays central while connections wait quietly in the margins until requested.', atmosphere: 'Refined writing desk', accent: 'ivory-amber', connected: ['memory','projects','brain','inbox','food','create'], capabilities: ['Writing','Search','Tags','Backlinks','Focus mode','Handwriting','AI initiative'] },
  { key: 'import', label: 'Import · Migration Room', path: '/import', purpose: 'A careful migration room showing source, extraction, destination, duplicates, conflicts and approval.', atmosphere: 'Clear migration surface', accent: 'cool-pearl', connected: ['inbox','connections','brain','create'], capabilities: ['Source','Extraction','Suggested destination','Duplicates','Conflicts','Approval','Undo'] },
  { key: 'capture', label: 'Capture · Fast Entrance', path: '/capture', purpose: 'The fastest possible entrance for speech, text, photo, video, files, scans, links and handwriting.', atmosphere: 'Open capture field', accent: 'white-prism', connected: ['create','inbox','notes','projects','brain'], capabilities: ['Speech','Text','Photo','Video','File','Scan','Link','Handwriting'] },
  { key: 'settings', label: 'Settings · Quiet Control Room', path: '/settings', purpose: 'A neutral place to tune appearance, climate, motion, voice, Aura, privacy, accessibility and Glow initiative.', atmosphere: 'Neutral pearl with minimal motion', accent: 'neutral-pearl', connected: ['today','world','brain','create'], capabilities: ['Appearance','Page climates','Motion','Voice','Aura intensity','AI initiative','Privacy','Accessibility','Navigation'] },
  { key: 'inbox', label: 'Inbox · Arrival Room', path: '/inbox', purpose: 'A temporary arrival room where new material visibly moves toward suggested destinations.', atmosphere: 'Soft arrival field', accent: 'pearl-rose', connected: ['tasks','notes','calendar','projects','brain','create'], capabilities: ['Automatic filing confidence','Review','Bulk actions','Source','Expiration','Archive'] },
  { key: 'resources', label: 'Resources · Reference Library', path: '/resources', purpose: 'Reusable guides and references stay available without becoming a duplicated dashboard.', atmosphere: 'Quiet reference library', accent: 'warm-ivory', connected: ['today','planning','fitness','beauty','food'], capabilities: ['Reset guides','Routine guides','Workout library','Travel and emergency references'] },
];

export function getSystemRoom(pathname: string) {
  return [...SYSTEM_ROOMS].sort((a, b) => b.path.length - a.path.length).find((room) => pathname === room.path || pathname.startsWith(`${room.path}/`)) ?? null;
}

export function getSystemRoomByKey(key: string) {
  return SYSTEM_ROOMS.find((room) => room.key === key) ?? null;
}
