import 'server-only';

import { getTasksByUser } from '@/lib/data/tasks';
import { getCalendarEventsByUser } from '@/lib/data/calendar-events';
import { getRoutinesByUser } from '@/lib/data/routines';
import { getWorkSchedulesByUser } from '@/lib/data/work-schedules';

export type TomorrowBrief={dateLabel:string;topThree:string[];events:{title:string;time:string;location:string|null}[];work:{title:string;time:string}[];routines:string[];wakeTarget:string;prepTonight:string[];summary:string};

export async function buildTomorrowBrief(userId:string,now=new Date()):Promise<TomorrowBrief>{const tomorrow=new Date(now);tomorrow.setDate(tomorrow.getDate()+1);const start=new Date(tomorrow);start.setHours(0,0,0,0);const end=new Date(tomorrow);end.setHours(23,59,59,999);const [tasks,events,routines,work]=await Promise.all([getTasksByUser(userId),getCalendarEventsByUser(userId),getRoutinesByUser(userId),getWorkSchedulesByUser(userId)]);const tomorrowEvents=events.filter(e=>e.startAt>=start&&e.startAt<=end).sort((a,b)=>a.startAt.getTime()-b.startAt.getTime());const candidates=tasks.filter(t=>t.status!=='done'&&t.status!=='cancelled').sort((a,b)=>{const ad=a.dueDate?.getTime()??Infinity;const bd=b.dueDate?.getTime()??Infinity;if(ad!==bd)return ad-bd;const w={urgent:4,high:3,medium:2,low:1};return (w[b.priority]??0)-(w[a.priority]??0)});const dueTomorrow=candidates.filter(t=>t.dueDate&&t.dueDate>=start&&t.dueDate<=end);const topThree=[...dueTomorrow,...candidates.filter(t=>!dueTomorrow.some(d=>d.id===t.id))].slice(0,3).map(t=>t.title);const weekday=tomorrow.toLocaleDateString('en-US',{weekday:'long'}).toLowerCase();const tomorrowRoutines=routines.filter(r=>!r.daysOfWeek?.length||r.daysOfWeek.some(d=>d.toLowerCase()===weekday)).slice(0,6).map(r=>r.name);const dayIndex=tomorrow.getDay();const tomorrowWork=work.filter(w=>w.dayOfWeek===dayIndex).map(w=>({title:w.title,time:`${w.startTime.slice(0,5)}–${w.endTime.slice(0,5)}`}));const firstTimed=tomorrowEvents.find(e=>!e.allDay);let wakeTarget='8:00 AM';if(firstTimed){const wake=new Date(firstTimed.startAt);wake.setHours(wake.getHours()-2);wakeTarget=wake.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});}const prepTonight:string[]=[];if(firstTimed)prepTonight.push(`Prepare for ${firstTimed.title}`);if(tomorrowWork.length)prepTonight.push('Set out what you need for work');if(topThree.length)prepTonight.push(`Make ${topThree[0]} easy to start`);if(tomorrowEvents.some(e=>e.location))prepTonight.push('Check travel time and what to bring');const summary=`Tomorrow has ${tomorrowEvents.length} calendar event${tomorrowEvents.length===1?'':'s'}, ${tomorrowWork.length} work block${tomorrowWork.length===1?'':'s'}, and ${topThree.length} priority action${topThree.length===1?'':'s'}.`;return{dateLabel:tomorrow.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}),topThree,events:tomorrowEvents.map(e=>({title:e.title,time:e.allDay?'All day':e.startAt.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}),location:e.location??null})),work:tomorrowWork,routines:tomorrowRoutines,wakeTarget,prepTonight,summary};}
