'use client';

import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import { usePathname } from 'next/navigation';
import { ArrowUp, Mic, MicOff, Sparkles, Volume2, VolumeX, X } from 'lucide-react';

type Message={id:string;role:'user'|'assistant';content:string;actions?:{label:string;href:string}[]};
type RecognitionAlternativeLike={transcript:string};
type RecognitionResultLike={isFinal:boolean;[index:number]:RecognitionAlternativeLike};
type RecognitionResultListLike={length:number;[index:number]:RecognitionResultLike};
type RecognitionEventLike={resultIndex:number;results:RecognitionResultListLike};
type RecognitionErrorLike={error?:string};
type RecognitionLike={continuous:boolean;interimResults:boolean;lang:string;start:()=>void;stop:()=>void;onresult:((event:RecognitionEventLike)=>void)|null;onend:(()=>void)|null;onerror:((event:RecognitionErrorLike)=>void)|null};
type RecognitionCtor=new()=>RecognitionLike;
type SpeechWindow=Window&{SpeechRecognition?:RecognitionCtor;webkitSpeechRecognition?:RecognitionCtor};

const STORAGE='glow-os:life-conversation:v1';
const VOICE_STORAGE='glow-os:human-voice:v1';
const STARTERS=['What should I do right now?','Plan my next hour','What can I ignore today?','Talk me through my day'];
const hello:Message={id:'hello',role:'assistant',content:'I’m here. Ask me anything about your day, your plans, or what to do next. I’ll use the rest of Glow instead of making you hunt through pages.'};

function readConversation(){try{const value=JSON.parse(localStorage.getItem(STORAGE)??'[]') as Message[];return Array.isArray(value)&&value.length?value.slice(-24):[hello]}catch{return[hello]}}
function saveConversation(messages:Message[]){try{localStorage.setItem(STORAGE,JSON.stringify(messages.slice(-24)))}catch{/* storage can be unavailable */}}
function readOpenAiKey(){try{const value=JSON.parse(localStorage.getItem(VOICE_STORAGE)??'{}') as {openAiKey?:unknown};return typeof value.openAiKey==='string'?value.openAiKey.trim():''}catch{return''}}
function id(){return`${Date.now()}-${Math.random().toString(36).slice(2,7)}`}

export function GlowLifeIntelligence(){
 const pathname=usePathname();const[open,setOpen]=useState(false);const[messages,setMessages]=useState<Message[]>([hello]);const[input,setInput]=useState('');const[thinking,setThinking]=useState(false);const[listening,setListening]=useState(false);const[speakBack,setSpeakBack]=useState(true);const recognition=useRef<RecognitionLike|null>(null);const scroller=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{setMessages(readConversation())},[]);
 useEffect(()=>{saveConversation(messages);if(open)requestAnimationFrame(()=>scroller.current?.scrollTo({top:scroller.current.scrollHeight,behavior:'smooth'}))},[messages,open]);
 useEffect(()=>{const handler=()=>setOpen(true);document.addEventListener('glow:open-conversation',handler);return()=>document.removeEventListener('glow:open-conversation',handler)},[]);
 const canListen=useMemo(()=>{if(typeof window==='undefined')return false;const speechWindow=window as SpeechWindow;return Boolean(speechWindow.SpeechRecognition||speechWindow.webkitSpeechRecognition)},[]);
 function speak(text:string){if(!speakBack||typeof document==='undefined')return;document.dispatchEvent(new CustomEvent('glow:speak',{detail:{text}}))}
 async function send(raw=input){const text=raw.trim();if(!text||thinking)return;const user:Message={id:id(),role:'user',content:text};const history=[...messages,user];setMessages(history);setInput('');setThinking(true);
  try{const openAiKey=readOpenAiKey();const response=await fetch('/api/glow/conversation',{method:'POST',headers:{'Content-Type':'application/json',...(openAiKey?{'x-glow-openai-key':openAiKey}:{})},body:JSON.stringify({messages:history.map(({role,content})=>({role,content})),page:pathname})});const payload=await response.json();const reply=response.ok&&payload?.reply?String(payload.reply):'I hit a connection problem, but I’m still here. Open the page you need or try that again.';const assistant:Message={id:id(),role:'assistant',content:reply,actions:Array.isArray(payload?.actions)?payload.actions:undefined};setMessages(current=>[...current,assistant]);speak(reply)}catch{const reply='I could not reach the Glow intelligence service just then. Your information is still safe. Try the request again.';setMessages(current=>[...current,{id:id(),role:'assistant',content:reply}]);speak(reply)}finally{setThinking(false)}}
 function toggleListen(){if(!canListen)return;if(listening){recognition.current?.stop();setListening(false);return}const speechWindow=window as SpeechWindow;const Ctor=speechWindow.SpeechRecognition||speechWindow.webkitSpeechRecognition;if(!Ctor)return;const rec=new Ctor();rec.continuous=false;rec.interimResults=true;rec.lang='en-US';rec.onresult=(event:RecognitionEventLike)=>{let transcript='';for(let i=event.resultIndex;i<event.results.length;i++)transcript+=event.results[i][0]?.transcript??'';setInput(transcript);if(event.results[event.results.length-1]?.isFinal){setListening(false);void send(transcript)}};rec.onend=()=>setListening(false);rec.onerror=()=>setListening(false);recognition.current=rec;setListening(true);rec.start()}
 return <>
  <button type="button" onClick={()=>setOpen(true)} className="fixed bottom-[calc(env(safe-area-inset-bottom)+82px)] right-4 z-[2147483050] flex h-14 items-center gap-2 rounded-full border border-white/80 bg-[#4f4552]/95 px-4 text-white shadow-[0_18px_50px_rgba(45,34,43,.25)] backdrop-blur-xl lg:bottom-5 lg:right-5" aria-label="Talk to Glow"><span className="grid h-8 w-8 place-items-center rounded-full bg-white/14"><Sparkles size={16}/></span><span className="hidden text-[11px] font-semibold tracking-[.01em] sm:block">Talk to Glow</span></button>
  {open?<div className="fixed inset-0 z-[2147483640] bg-[#1d171c]/20 p-2 backdrop-blur-[6px] sm:p-4" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section className="ml-auto flex h-[min(760px,calc(100vh-1rem))] w-full max-w-[470px] flex-col overflow-hidden rounded-[30px] border border-white/70 bg-[rgba(255,252,250,.96)] shadow-[0_28px_100px_rgba(42,30,38,.28)] sm:h-[min(760px,calc(100vh-2rem))]">
   <header className="flex items-center justify-between border-b border-[#eee5e2] px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#5f5260] text-white shadow-sm"><Sparkles size={17}/></span><div><p className="font-serif text-[21px] leading-none text-[#373036]">Glow</p><p className="mt-1 text-[8px] uppercase tracking-[.14em] text-[#96888f]">Life Intelligence · {pathname.replace('/','')||'today'}</p></div></div><div className="flex items-center gap-1"><button type="button" onClick={()=>setSpeakBack(value=>!value)} className="grid h-9 w-9 place-items-center rounded-full border border-[#eadfdb] bg-white text-[#645961]" aria-label={speakBack?'Turn spoken replies off':'Turn spoken replies on'}>{speakBack?<Volume2 size={14}/>:<VolumeX size={14}/>}</button><button type="button" onClick={()=>setOpen(false)} className="grid h-9 w-9 place-items-center rounded-full border border-[#eadfdb] bg-white text-[#645961]" aria-label="Close Glow"><X size={15}/></button></div></header>
   <div ref={scroller} className="min-h-0 flex-1 overflow-y-auto px-4 py-5 sm:px-5">{messages.map(message=><div key={message.id} className={`mb-4 flex ${message.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[88%] ${message.role==='user'?'rounded-[22px_22px_7px_22px] bg-[#554957] px-4 py-3 text-white':'text-[#40383d]'}`}><p className={`whitespace-pre-wrap text-[12px] leading-[1.7] ${message.role==='assistant'?'font-normal':''}`}>{message.content}</p>{message.actions?.length?<div className="mt-3 flex flex-wrap gap-2">{message.actions.map(action=><Link key={`${message.id}-${action.href}`} href={action.href} onClick={()=>setOpen(false)} className="rounded-full border border-[#e6d9d7] bg-white px-3 py-2 text-[8px] font-semibold text-[#604e58] shadow-sm">{action.label}</Link>)}</div>:null}</div></div>)}{thinking?<div className="mb-4 flex justify-start"><div className="rounded-full border border-[#eadfdb] bg-white px-4 py-2 text-[9px] text-[#887b82]">Glow is looking across your life…</div></div>:null}</div>
   {messages.length<=2?<div className="px-4 pb-2 sm:px-5"><div className="flex gap-2 overflow-x-auto pb-1">{STARTERS.map(item=><button key={item} type="button" onClick={()=>void send(item)} className="shrink-0 rounded-full border border-[#e8ddda] bg-[#fffaf8] px-3 py-2 text-[8px] text-[#6e6067]">{item}</button>)}</div></div>:null}
   <footer className="border-t border-[#eee5e2] bg-white/70 p-3 sm:p-4"><div className="flex items-end gap-2 rounded-[24px] border border-[#ded3d1] bg-white p-2 pl-4 shadow-[0_10px_30px_rgba(74,57,64,.06)]"><textarea value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send()}}} rows={1} placeholder="Say or type anything…" className="max-h-28 min-h-[38px] flex-1 resize-none bg-transparent py-2 text-[11px] leading-5 text-[#3c3539] outline-none placeholder:text-[#a89ca1]"/><button type="button" onClick={toggleListen} disabled={!canListen} className={`grid h-10 w-10 shrink-0 place-items-center rounded-full ${listening?'bg-[#8f5266] text-white':'bg-[#f5efed] text-[#655960]'} disabled:opacity-30`} aria-label={listening?'Stop listening':'Speak to Glow'}>{listening?<MicOff size={15}/>:<Mic size={15}/>}</button><button type="button" onClick={()=>void send()} disabled={!input.trim()||thinking} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#4f4552] text-white disabled:opacity-35" aria-label="Send to Glow"><ArrowUp size={16}/></button></div><p className="mt-2 px-2 text-[7.5px] leading-4 text-[#9a8f94]">Glow compares your live systems before answering. It will not claim an action happened unless the app confirms it.</p></footer>
  </section></div>:null}
 </>;
}
