'use client';

import { useEffect, useMemo, useRef, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { Activity, BarChart3, Check, ChevronRight, Clock3, Dumbbell, Flame, HeartPulse, Mic2, Pause, Play, Plus, RotateCcw, Sparkles, TimerReset, Volume2, X } from 'lucide-react';
import { advanceWorkoutAction, createWorkoutProgramAction, createWorkoutTemplateAction, finishWorkoutRunAction, logWorkoutSetAction, saveWorkoutReadinessAction, startWorkoutRunAction } from '@/app/actions/advanced-fitness';

type Template={id:string;name:string;category:string;equipment:string;fullMinutes:number;quickMinutes:number;minimumMinutes:number;difficulty:number;primaryMuscles:string[];lowImpact:boolean;notes:string|null};
type Exercise={id:string;templateId:string;name:string;position:number;sets:number;reps:number;seconds:number|null;restSeconds:number;weightLb:number|null;muscleGroup:string|null;equipment:string|null;formCue:string|null;instructions:string|null;substitutions:string[];optional:boolean};
type Run={id:string;templateId:string|null;name:string;version:string;status:string;currentExerciseIndex:number;startedAt:Date;completedAt:Date|null;activeSeconds:number;energyBefore:number|null;sorenessBefore:number|null;readiness:string|null;equipment:string|null;notes:string|null;feelingAfter:string|null;sessionId:string|null};
type SetLog={id:string;runId:string;exerciseId:string|null;exerciseName:string;setNumber:number;reps:number|null;seconds:number|null;weightLb:number|null;rpe:number|null;completed:boolean;skipped:boolean;completedAt:Date};
type Readiness={energy:number;sleep:number;soreness:number;stress:number;availableMinutes:number;equipment:string;locationMode:string}|null;
type Session={id:string;workoutType:string;occurredAt:Date;durationMinutes:number|null;energy:number|null;soreness:number|null;equipment:string|null;notes:string|null};
type Program={id:string;name:string;weeks:number;currentWeek:number;status:string;templateIds:string[];goalId:string|null};
type CalendarEvent={id:string;title:string;startAt:Date;endAt:Date|null;allDay:boolean};
type Version='full'|'quick'|'minimum';
type Energy='high'|'normal'|'low'|'exhausted';
type Body='great'|'normal'|'sore'|'very_sore';
type SpeechRecognitionEventLike={results:ArrayLike<{0:{transcript:string}}>};
type SpeechRecognitionLike={continuous:boolean;interimResults:boolean;lang:string;onresult:((event:SpeechRecognitionEventLike)=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void};
type SpeechCtor=new()=>SpeechRecognitionLike;

const TIME_OPTIONS=[5,10,20,30,45];
const ENERGY_OPTIONS:Energy[]=['high','normal','low','exhausted'];
const BODY_OPTIONS:Body[]=['great','normal','sore','very_sore'];
const EQUIPMENT=['gym','dumbbells','resistance bands','bodyweight','hotel room','no equipment'];
const MUSCLES=['glutes','quads','hamstrings','back','shoulders','arms','core'];

function localDateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function energyNumber(value:Energy){return value==='high'?5:value==='normal'?4:value==='low'?2:1}
function sorenessNumber(value:Body){return value==='great'?1:value==='normal'?2:value==='sore'?4:5}
function duration(template:Template,version:Version){return version==='full'?template.fullMinutes:version==='quick'?template.quickMinutes:template.minimumMinutes}
function versionFor(template:Template,energy:Energy,minutes:number,body:Body):Version{if(energy==='exhausted'||body==='very_sore'||minutes<=template.minimumMinutes)return'minimum';if(energy==='low'||body==='sore'||minutes<template.fullMinutes)return'quick';return'full'}
function compatible(template:Template,equipment:string){if(template.equipment==='bodyweight')return true;if(equipment==='gym')return true;if(equipment==='no equipment'||equipment==='bodyweight'||equipment==='hotel room')return template.equipment==='bodyweight';if(equipment==='dumbbells')return /dumbbell|bodyweight/i.test(template.equipment);if(equipment==='resistance bands')return /band|bodyweight/i.test(template.equipment);return true}
function categoryTone(category:string){if(/mobility|recovery/i.test(category))return'bg-[#edf3e8] text-[#5f735a]';if(/pilates|core/i.test(category))return'bg-[#f0ebf6] text-[#756781]';if(/cardio|walk|run/i.test(category))return'bg-[#f7e8e4] text-[#9a665e]';return'bg-[#e8eef4] text-[#5f7388]'}
function sessionCategory(name:string){if(/lower|leg|glute/i.test(name))return'Lower Body';if(/upper|arm|back|shoulder|chest/i.test(name))return'Upper Body';if(/core|pilates/i.test(name))return'Core';if(/mobility|stretch|yoga|recovery/i.test(name))return'Mobility';if(/walk|run|cardio/i.test(name))return'Cardio';return'Other'}

export function AdaptiveWorkoutStudio({templates,exercises,runs,setLogs,readiness:initialReadiness,sessions,programs,calendarEvents}:{templates:Template[];exercises:Exercise[];runs:Run[];setLogs:SetLog[];readiness:Readiness;sessions:Session[];programs:Program[];calendarEvents:CalendarEvent[]}){
 const router=useRouter();
 const [energy,setEnergy]=useState<Energy>(initialReadiness?.energy&&initialReadiness.energy<=2?'low':'normal');
 const [body,setBody]=useState<Body>(initialReadiness?.soreness&&initialReadiness.soreness>=4?'sore':'normal');
 const [minutes,setMinutes]=useState(initialReadiness?.availableMinutes??30);
 const [equipment,setEquipment]=useState(initialReadiness?.equipment??'dumbbells');
 const [locationMode,setLocationMode]=useState(initialReadiness?.locationMode??'home');
 const [activeRun,setActiveRun]=useState<Run|null>(runs.find(r=>r.status==='active')??null);
 const [logs,setLogs]=useState(setLogs);
 const [playerOpen,setPlayerOpen]=useState(Boolean(runs.find(r=>r.status==='active')));
 const [restSeconds,setRestSeconds]=useState(0);
 const [restRunning,setRestRunning]=useState(false);
 const [weight,setWeight]=useState(0);
 const [reps,setReps]=useState(10);
 const [rpe,setRpe]=useState(7);
 const [notice,setNotice]=useState('');
 const [voice,setVoice]=useState(false);
 const [handsFree,setHandsFree]=useState(false);
 const [builder,setBuilder]=useState('');
 const [isPending,startTransition]=useTransition();
 const speechRef=useRef<SpeechRecognitionLike|null>(null);
 const startedRef=useRef(Date.now());
 const activeElapsedRef=useRef(0);
 const activeTickRef=useRef<number|null>(null);
 const [elapsed,setElapsed]=useState(activeRun?.activeSeconds??0);
 const now=new Date();

 useEffect(()=>{if(!notice)return;const id=window.setTimeout(()=>setNotice(''),4200);return()=>window.clearTimeout(id)},[notice]);
 useEffect(()=>{if(!restRunning||restSeconds<=0)return;const id=window.setInterval(()=>setRestSeconds(s=>Math.max(0,s-1)),1000);return()=>window.clearInterval(id)},[restRunning,restSeconds]);
 useEffect(()=>{if(restRunning&&restSeconds===0){setRestRunning(false);if('speechSynthesis'in window)window.speechSynthesis.speak(new SpeechSynthesisUtterance('Rest complete. Ready for the next set.'))}},[restRunning,restSeconds]);
 useEffect(()=>{if(!playerOpen)return;activeTickRef.current=window.setInterval(()=>{activeElapsedRef.current+=1;setElapsed((activeRun?.activeSeconds??0)+activeElapsedRef.current)},1000);return()=>{if(activeTickRef.current)window.clearInterval(activeTickRef.current)}},[playerOpen,activeRun?.activeSeconds]);
 useEffect(()=>()=>speechRef.current?.stop(),[]);

 const weekStart=useMemo(()=>{const d=new Date();const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);d.setHours(0,0,0,0);return d},[]);
 const weekSessions=sessions.filter(s=>s.occurredAt>=weekStart);
 const weeklyBalance=useMemo(()=>weekSessions.reduce<Record<string,number>>((acc,s)=>{const c=sessionCategory(s.workoutType);acc[c]=(acc[c]??0)+1;return acc},{}),[weekSessions]);
 const nextEvent=calendarEvents.filter(e=>!e.allDay&&e.startAt>now).sort((a,b)=>a.startAt.getTime()-b.startAt.getTime())[0]??null;
 const calendarMinutes=nextEvent?Math.max(0,Math.floor((nextEvent.startAt.getTime()-Date.now())/60000)):999;

 const scored=templates.map(template=>{
   let score=40;
   const version=versionFor(template,energy,minutes,body);
   if(duration(template,version)<=minutes)score+=20;else score-=20;
   if(compatible(template,equipment))score+=18;else score-=50;
   if(body==='very_sore'&&template.lowImpact)score+=45;
   if(body==='sore'&&template.lowImpact)score+=25;
   if(energy==='exhausted'&&template.lowImpact)score+=30;
   if(now.getHours()>=20&&template.lowImpact)score+=18;
   const cat=sessionCategory(template.name);score-=((weeklyBalance[cat]??0)*8);
   if(calendarMinutes<duration(template,version)+10)score-=25;
   return{template,score,version};
 }).sort((a,b)=>b.score-a.score);
 const recommendation=scored[0]??null;
 const alternative=scored[1]??null;
 const recovery=scored.find(x=>x.template.lowImpact)??recommendation;

 const runTemplate=activeRun?.templateId?templates.find(t=>t.id===activeRun.templateId)??null:null;
 const allRunExercises=runTemplate?exercises.filter(e=>e.templateId===runTemplate.id).sort((a,b)=>a.position-b.position):[];
 const runExercises=activeRun?.version==='minimum'?allRunExercises.slice(0,3):activeRun?.version==='quick'?allRunExercises.slice(0,Math.min(5,allRunExercises.length)):allRunExercises;
 const currentIndex=Math.min(activeRun?.currentExerciseIndex??0,Math.max(0,runExercises.length-1));
 const currentExercise=runExercises[currentIndex]??null;
 const currentLogs=currentExercise&&activeRun?logs.filter(l=>l.runId===activeRun.id&&l.exerciseName===currentExercise.name&&!l.skipped):[];
 const nextSet=(currentLogs.length?Math.max(...currentLogs.map(l=>l.setNumber)):0)+1;
 const history=currentExercise?setLogs.filter(l=>l.exerciseName===currentExercise.name&&l.runId!==activeRun?.id&&l.completed&&!l.skipped).slice(0,8):[];
 const lastHistory=history[0]??null;
 const suggestedWeight=lastHistory?.weightLb!=null?(lastHistory.rpe!=null&&lastHistory.rpe<=7?lastHistory.weightLb+5:lastHistory.weightLb):currentExercise?.weightLb??0;
 const volume=logs.filter(l=>l.runId===activeRun?.id&&l.completed&&!l.skipped).reduce((sum,l)=>sum+(l.weightLb??0)*(l.reps??0),0);

 function persistReadiness(){startTransition(async()=>{const result=await saveWorkoutReadinessAction({dateKey:localDateKey(),energy:energyNumber(energy),sleep:3,soreness:sorenessNumber(body),stress:3,availableMinutes:minutes,equipment,locationMode});if(result.error)setNotice(result.error)})}
 useEffect(()=>{const id=window.setTimeout(persistReadiness,500);return()=>window.clearTimeout(id)},[energy,body,minutes,equipment,locationMode]);

 function startTemplate(template:Template,forced?:Version){const version=forced??versionFor(template,energy,minutes,body);startTransition(async()=>{const result=await startWorkoutRunAction({templateId:template.id,version,energy:energyNumber(energy),soreness:sorenessNumber(body),equipment});if(!result.data)return setNotice(result.error??'Could not start workout.');setActiveRun(result.data as Run);setPlayerOpen(true);setElapsed(result.data.activeSeconds??0);activeElapsedRef.current=0;startedRef.current=Date.now();router.refresh()})}
 function saveSet(skipped=false){if(!activeRun||!currentExercise)return;const setNumber=Math.min(nextSet,currentExercise.sets);startTransition(async()=>{const result=await logWorkoutSetAction({runId:activeRun.id,exerciseId:currentExercise.id,exerciseName:currentExercise.name,setNumber,reps,weightLb:weight||undefined,rpe,skipped});if(!result.data)return setNotice(result.error??'Could not save set.');setLogs(cur=>[result.data as SetLog,...cur.filter(x=>x.id!==(result.data as SetLog).id)]);if(!skipped&&currentExercise.restSeconds>0){setRestSeconds(currentExercise.restSeconds);setRestRunning(true)}setNotice(skipped?'Exercise skipped for this run.':`Set ${setNumber} saved.`);router.refresh()})}
 function nextExercise(){if(!activeRun)return;const next=Math.min(runExercises.length-1,currentIndex+1);startTransition(async()=>{await advanceWorkoutAction(activeRun.id,next,elapsed);setActiveRun(cur=>cur?{...cur,currentExerciseIndex:next,activeSeconds:elapsed}:cur);setRestRunning(false);setRestSeconds(0);router.refresh()})}
 function finish(feeling='good'){if(!activeRun)return;startTransition(async()=>{const result=await finishWorkoutRunAction({runId:activeRun.id,activeSeconds:Math.max(60,elapsed),feelingAfter:feeling});if(!result.data)return setNotice(result.error??'Could not finish workout.');setActiveRun(null);setPlayerOpen(false);setNotice('Training complete. Glow updated Fitness and connected Habits automatically.');router.refresh()})}
 function swapExercise(){if(!currentExercise)return;const options=currentExercise.substitutions.length?currentExercise.substitutions:['Reverse Lunge','Step-Up','Glute Bridge','Bodyweight Squat'];const replacement=options[0];setNotice(`Swap suggestion: ${replacement}. This changes this run only.`)}
 function toggleVoice(){if(voice){speechRef.current?.stop();setVoice(false);return}const w=window as unknown as{SpeechRecognition?:SpeechCtor;webkitSpeechRecognition?:SpeechCtor};const C=w.SpeechRecognition??w.webkitSpeechRecognition;if(!C)return setNotice('Voice workout control is not supported by this browser.');const r=new C();r.continuous=true;r.interimResults=false;r.lang='en-US';r.onresult=(event)=>{const text=event.results[event.results.length-1]?.[0]?.transcript?.toLowerCase()??'';if(/done|next set/.test(text))saveSet(false);else if(/skip/.test(text))saveSet(true);else if(/next exercise|what's next/.test(text))nextExercise();else if(/add five/.test(text))setWeight(w=>w+5);else if(/ten reps/.test(text))setReps(10);else if(/thirty more/.test(text))setRestSeconds(s=>s+30);else if(/pause/.test(text))setRestRunning(false);else if(/resume|start rest/.test(text))setRestRunning(true);else if(/swap/.test(text))swapExercise();else if(/make.*short|quick/.test(text)){setNotice('Use Finish after the current exercise, or restart the workout in Quick mode next time.')}else setNotice(`Glow heard “${text}”.`)};r.onerror=()=>{setVoice(false);setNotice('Voice control stopped because the browser reported a microphone/speech error.')};r.onend=()=>setVoice(false);r.start();speechRef.current=r;setVoice(true)}

 function buildWorkout(){const raw=builder.trim();if(!raw)return;const lower=raw.toLowerCase();const foundMinutes=Number(lower.match(/(\d{1,3})\s*(?:min|minute)/)?.[1]??25);const eq=lower.includes('dumbbell')?'dumbbells':lower.includes('band')?'resistance bands':'bodyweight';const focus=lower.includes('glute')?'glutes':lower.includes('upper')?'upper body':lower.includes('core')?'core':'full body';const category=lower.includes('pilates')?'pilates':lower.includes('mobility')?'mobility':'strength';const exerciseNames=focus==='glutes'?['Goblet Squat','Romanian Deadlift','Hip Thrust','Reverse Lunge','Glute Bridge']:focus==='upper body'?['Dumbbell Row','Shoulder Press','Chest Press','Biceps Curl','Triceps Extension']:focus==='core'?['Dead Bug','Bird Dog','Plank','Glute Bridge','Side Plank']:['Squat','Push-Up','Row','Glute Bridge','Dead Bug'];startTransition(async()=>{const result=await createWorkoutTemplateAction({name:`${foundMinutes}-Minute ${focus.replace(/^./,c=>c.toUpperCase())}`,category,equipment:eq,minutes:Math.max(5,Math.min(120,foundMinutes)),exercises:exerciseNames.map((name,i)=>({name,sets:i<3?3:2,reps:i===3&&/Plank/.test(name)?30:10,restSeconds:category==='strength'?75:30,muscleGroup:focus==='full body'?(i<2?'legs':i===2?'back':'core'):focus}))});if(!result.data)return setNotice(result.error??'Could not build workout.');setNotice('Workout saved to your library.');setBuilder('');router.refresh()})}
 function createProgram(){startTransition(async()=>{const result=await createWorkoutProgramAction({name:'6-Week Adaptive Training Block',weeks:6,templateIds:templates.slice(0,4).map(t=>t.id)});if(!result.data)return setNotice(result.error??'Could not create training block.');setNotice('6-week training block created.');router.refresh()})}

 const recoveryMap=MUSCLES.map(m=>{const recent=sessions.find(s=>s.occurredAt.getTime()>Date.now()-48*3600000&&sessionCategory(s.workoutType).toLowerCase().includes(m==='glutes'||m==='quads'||m==='hamstrings'?'lower':m==='back'||m==='shoulders'||m==='arms'?'upper':m));return{muscle:m,state:recent?'moderate':'recovered'}});
 const trainingMinutes=weekSessions.reduce((sum,s)=>sum+(s.durationMinutes??0),0);
 const load=trainingMinutes>=180?'High':trainingMinutes>=75?'Moderate':'Light';
 const recentCompleted=runs.filter(r=>r.status==='complete').slice(0,4);

 return <div className="mx-auto max-w-[1380px] space-y-6 pb-28">
  {notice?<div aria-live="polite" className="fixed left-1/2 top-5 z-[220] max-w-[92vw] -translate-x-1/2 rounded-full border border-[#dfe6ea] bg-white px-4 py-2.5 text-[11px] text-[#56636b] shadow-xl">{notice}</div>:null}
  <section className="overflow-hidden rounded-[34px] border border-[#e5e7e6] bg-[radial-gradient(circle_at_top_left,#fffdf8,#eef2f4_58%,#f4f0eb)] p-5 shadow-[0_30px_80px_rgba(54,67,74,.07)] sm:p-8">
   <div className="grid gap-7 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#728697]">Workout Right Now · {now.toLocaleDateString('en-US',{weekday:'long'})} · {now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</p><h1 className="glow-display mt-2 text-[44px] leading-[.95] text-[#273139] sm:text-[60px]">Train for the day you actually have.</h1><p className="mt-4 max-w-2xl text-[12px] leading-6 text-[#6d787e]">Plan → Train → Track → Recover → Adapt. Glow uses your time, energy, soreness, equipment, Calendar and recent training balance to narrow the choice.</p>{recommendation?<div className="mt-6 rounded-[26px] border border-white/80 bg-white/76 p-5 backdrop-blur"><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[#748a9d]">Best workout for right now</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h2 className="glow-display text-[29px] text-[#273139]">{recommendation.template.name}</h2><p className="mt-1 text-[10.5px] text-[#748087]">{duration(recommendation.template,recommendation.version)} min · {recommendation.version} · {recommendation.template.lowImpact?'Recovery-friendly':'Training'}</p><div className="mt-3 flex flex-wrap gap-1.5">{[duration(recommendation.template,recommendation.version)<=minutes&&'Fits your time',compatible(recommendation.template,equipment)&&'Matches equipment',body==='sore'||body==='very_sore'?'Soreness considered':null,calendarMinutes>duration(recommendation.template,recommendation.version)+10?'No Calendar conflict':'Calendar is tight'].filter(Boolean).map(x=><span key={String(x)} className="rounded-full bg-[#f1f4f5] px-2.5 py-1 text-[8.5px] text-[#66767f]">{x}</span>)}</div></div><div className="flex flex-wrap gap-2"><button disabled={isPending} onClick={()=>startTemplate(recommendation.template)} className="rounded-full bg-[#354653] px-5 py-3 text-[10.5px] font-semibold text-white disabled:opacity-50"><Play size={12} className="mr-1 inline"/>Start Workout</button><button onClick={()=>startTemplate(recommendation.template,'quick')} className="rounded-full border border-[#d8dfe3] bg-white px-4 py-3 text-[10px]">Quick Version</button><button onClick={()=>recovery&&startTemplate(recovery.template,'minimum')} className="rounded-full border border-[#d8e2d3] bg-[#f3f7ef] px-4 py-3 text-[10px] text-[#62755d]">Recovery Instead</button></div></div></div>:null}</div>
   <div className="space-y-3 rounded-[28px] border border-[#e0e5e6] bg-white/82 p-5"><Control label="Energy" values={ENERGY_OPTIONS} value={energy} onChange={v=>setEnergy(v as Energy)}/><Control label="I have…" values={TIME_OPTIONS.map(v=>`${v}${v===45?'+':''} min`)} value={`${minutes}${minutes===45?'+':''} min`} onChange={v=>setMinutes(Number(v.replace(/\D/g,'')))}/><Control label="How does your body feel?" values={BODY_OPTIONS.map(v=>v.replace('_',' '))} value={body.replace('_',' ')} onChange={v=>setBody(v.replace(' ','_') as Body)}/><div><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#7a858b]">Equipment</p><select value={equipment} onChange={e=>setEquipment(e.target.value)} className="mt-2 w-full rounded-xl border border-[#e1e5e6] bg-[#fafcfc] px-3 py-2.5 text-[10px]">{EQUIPMENT.map(x=><option key={x}>{x}</option>)}</select></div></div>
   </div>
  </section>

  {activeRun?<section className="rounded-[24px] border border-[#d9e3ea] bg-[#f4f8fb] p-5 sm:flex sm:items-center sm:justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[#6d8292]">Continue</p><h2 className="glow-display mt-1 text-[26px] text-[#2b3740]">{activeRun.name}</h2><p className="mt-1 text-[10px] text-[#73808a]">{activeRun.version} · exercise {Math.min(currentIndex+1,runExercises.length)} of {runExercises.length} · {Math.floor(elapsed/60)} min active</p></div><button onClick={()=>setPlayerOpen(true)} className="mt-3 rounded-full bg-[#354653] px-5 py-2.5 text-[10.5px] font-semibold text-white sm:mt-0">Resume Workout</button></section>:null}

  <section><div className="flex items-end justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[#7d8c94]">Today’s Training</p><h2 className="glow-display mt-1 text-[30px] text-[#29343b]">One clear choice, with options</h2></div></div><div className="mt-4 grid gap-3 md:grid-cols-3">{[[recommendation,'Recommended'],[alternative,'Alternative'],[recovery,'Recovery']].map(([entry,label],i)=>{const x=entry as typeof recommendation;return x?<button key={`${label}`} onClick={()=>startTemplate(x.template,i===2?'minimum':x.version)} className="rounded-[22px] border border-[#e4e7e7] bg-white p-5 text-left transition hover:-translate-y-0.5 hover:shadow-lg"><span className={`rounded-full px-2.5 py-1 text-[8.5px] ${categoryTone(x.template.category)}`}>{label as string}</span><h3 className="glow-display mt-4 text-[23px] text-[#2e393f]">{x.template.name}</h3><p className="mt-1 text-[9.5px] text-[#7a858b]">{duration(x.template,i===2?'minimum':x.version)} min · {x.template.primaryMuscles.join(', ')||x.template.category}</p><div className="mt-4 flex items-center gap-2 text-[9px] text-[#647681]"><Play size={11}/>Start {i===2?'minimum':x.version}</div></button>:null})}</div></section>

  <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
   <section className="rounded-[24px] border border-[#e4e7e7] bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#7d8b92]">Weekly Training Rhythm</p><h2 className="glow-display mt-1 text-[26px]">Balance before volume</h2></div><BarChart3 size={18} className="text-[#72899a]"/></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{['Lower Body','Upper Body','Core','Mobility','Cardio'].map(cat=><div key={cat} className="rounded-[16px] bg-[#f6f8f8] p-3 text-center"><p className="glow-display text-[22px]">{weeklyBalance[cat]??0}</p><p className="mt-1 text-[8.5px] text-[#7d898e]">{cat}</p></div>)}</div><p className="mt-4 text-[10.5px] leading-5 text-[#6d787e]">{Object.values(weeklyBalance).length?`Glow sees ${weekSessions.length} session${weekSessions.length===1?'':'s'} this week. ${weeklyBalance['Lower Body']??0>(weeklyBalance['Upper Body']??0)?'Upper body is currently less represented than lower body.':'Training looks reasonably balanced so far.'}`:'Your first completed workout will begin the weekly balance.'}</p></section>
   <section className="rounded-[24px] border border-[#e4e7e7] bg-white p-5"><div className="flex items-center gap-2"><HeartPulse size={17} className="text-[#7f9677]"/><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#798b73]">Body Recovery</p><h2 className="glow-display mt-1 text-[25px]">Soft recovery map</h2></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{recoveryMap.map(x=><div key={x.muscle} className={`rounded-[14px] p-3 ${x.state==='recovered'?'bg-[#f0f5ec]':'bg-[#f7eee7]'}`}><p className="text-[10px] capitalize text-[#56645c]">{x.muscle}</p><p className="mt-1 text-[8.5px] text-[#849087]">{x.state==='recovered'?'Recovered':'Moderate fatigue'}</p></div>)}</div><p className="mt-3 text-[9px] leading-4 text-[#8a8580]">This is training-context recovery from recent workouts, not an injury assessment.</p></section>
  </div>

  <div className="grid gap-4 lg:grid-cols-3">
   <Metric title="Training Load" value={load} detail={`${trainingMinutes} min this week`} icon={<Flame size={16}/>}/><Metric title="Consistency" value={`${weekSessions.length}`} detail="sessions this week" icon={<Activity size={16}/>}/><Metric title="Calendar Fit" value={nextEvent?`${calendarMinutes}m`:'Open'} detail={nextEvent?`until ${nextEvent.title}`:'No upcoming timed event'} icon={<Clock3 size={16}/>}/>
  </div>

  <section className="rounded-[24px] border border-[#e4e7e7] bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#7d8b92]">Workout Library</p><h2 className="glow-display mt-1 text-[28px]">Full · Quick · Minimum</h2></div><Dumbbell size={18} className="text-[#72879a]"/></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{templates.map(t=><div key={t.id} className="rounded-[18px] border border-[#e8ebeb] bg-[#fbfcfc] p-4"><span className={`rounded-full px-2 py-1 text-[8px] ${categoryTone(t.category)}`}>{t.category}</span><h3 className="mt-3 text-[11.5px] font-medium text-[#344047]">{t.name}</h3><p className="mt-1 text-[9px] text-[#859096]">{t.equipment} · {t.primaryMuscles.join(', ')}</p><div className="mt-3 grid grid-cols-3 gap-1 text-center"><Small v={`${t.fullMinutes}m`} l="Full"/><Small v={`${t.quickMinutes}m`} l="Quick"/><Small v={`${t.minimumMinutes}m`} l="Minimum"/></div><button onClick={()=>startTemplate(t)} className="mt-4 w-full rounded-full bg-[#eef2f4] px-3 py-2 text-[9.5px] text-[#536873]">Start</button></div>)}</div></section>

  <div className="grid gap-4 lg:grid-cols-2">
   <section className="rounded-[24px] border border-[#e4e7e7] bg-[linear-gradient(135deg,#fffdfa,#eef3f6)] p-5"><div className="flex items-center gap-2"><Sparkles size={15} className="text-[#71899a]"/><h2 className="glow-display text-[25px]">Build with Glow</h2></div><p className="mt-2 text-[10px] leading-5 text-[#778289]">Describe the time, focus and equipment. Glow creates an editable workout template instead of leaving the idea as chat text.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={builder} onChange={e=>setBuilder(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')buildWorkout()}} placeholder="25-minute glute workout at home with dumbbells" className="min-w-0 flex-1 rounded-2xl border border-[#dfe5e7] bg-white px-4 py-3 text-[10.5px] outline-none"/><button onClick={buildWorkout} disabled={isPending} className="rounded-2xl bg-[#354653] px-5 py-3 text-[10px] font-semibold text-white disabled:opacity-50">Build + Save</button></div></section>
   <section className="rounded-[24px] border border-[#e4e7e7] bg-white p-5"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#7d8b92]">Program</p>{programs.find(p=>p.status==='active')?<div className="mt-2"><h2 className="glow-display text-[25px]">{programs.find(p=>p.status==='active')?.name}</h2><p className="mt-1 text-[10px] text-[#7c878d]">Week {programs.find(p=>p.status==='active')?.currentWeek} of {programs.find(p=>p.status==='active')?.weeks}</p></div>:<div className="mt-2"><h2 className="glow-display text-[25px]">No active training block</h2><p className="mt-1 text-[10px] text-[#7c878d]">Create a six-week block from your current library.</p><button onClick={createProgram} disabled={!templates.length||isPending} className="mt-4 rounded-full border border-[#dce3e6] px-4 py-2 text-[9.5px] text-[#5c707b]">Create 6-week block</button></div>}</section>
  </div>

  <section className="rounded-[24px] border border-[#e4e7e7] bg-white p-5"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#7d8b92]">Recent Workouts</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{recentCompleted.length?recentCompleted.map(r=><div key={r.id} className="rounded-[16px] bg-[#f7f9f9] p-4"><p className="text-[10.5px] font-medium">{r.name}</p><p className="mt-1 text-[8.5px] text-[#849096]">{r.completedAt?.toLocaleDateString()} · {Math.max(1,Math.round(r.activeSeconds/60))} min · {r.version}</p></div>):<p className="text-[10px] text-[#879198]">Completed guided workouts will appear here.</p>}</div></section>

  {playerOpen&&activeRun&&runTemplate&&currentExercise?<div className="fixed inset-0 z-[210] overflow-y-auto bg-[#f4f3ef]/98 backdrop-blur-xl"><div className={`mx-auto min-h-screen max-w-[1050px] p-4 sm:p-7 ${handsFree?'flex items-center':''}`}><div className="w-full rounded-[30px] border border-[#dde3e5] bg-white p-5 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[#738895]">{activeRun.name} · {activeRun.version}</p><h2 className={`glow-display mt-2 text-[#28343b] ${handsFree?'text-[54px] sm:text-[72px]':'text-[38px] sm:text-[50px]'}`}>{currentExercise.name}</h2><p className="mt-2 text-[10px] text-[#7a858b]">Exercise {currentIndex+1} of {runExercises.length} · Set {Math.min(nextSet,currentExercise.sets)} of {currentExercise.sets}</p></div><button onClick={()=>setPlayerOpen(false)} aria-label="Close workout player" className="rounded-full border border-[#e0e5e6] p-2"><X size={16}/></button></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div><div className="rounded-[24px] bg-[#eef3f6] p-5"><div className="grid grid-cols-3 gap-3 text-center"><Big v={`${reps}`} l="Reps"/><Big v={`${weight||suggestedWeight||0} lb`} l="Weight"/><Big v={`RPE ${rpe}`} l="Effort"/></div>{currentExercise.formCue?<p className="mt-4 rounded-xl bg-white/70 p-3 text-[10px] text-[#5f6f77]"><b>Form cue:</b> {currentExercise.formCue}</p>:null}{lastHistory?<p className="mt-3 text-[9.5px] text-[#718087]">Last time: {lastHistory.weightLb??0} lb × {lastHistory.reps??'—'} · RPE {lastHistory.rpe??'—'}. Suggested today: {suggestedWeight} lb.</p>:<p className="mt-3 text-[9.5px] text-[#718087]">No prior set history yet. Start conservatively and log how it feels.</p>}</div>
     <div className="mt-4 grid grid-cols-3 gap-2"><label className="text-[8.5px] text-[#78858b]">Weight<input type="number" value={weight||suggestedWeight||0} onChange={e=>setWeight(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-[#dfe4e6] px-3 py-2 text-[11px]"/></label><label className="text-[8.5px] text-[#78858b]">Reps<input type="number" value={reps} onChange={e=>setReps(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-[#dfe4e6] px-3 py-2 text-[11px]"/></label><label className="text-[8.5px] text-[#78858b]">RPE<input type="number" min="1" max="10" value={rpe} onChange={e=>setRpe(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-[#dfe4e6] px-3 py-2 text-[11px]"/></label></div>
     <div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>saveSet(false)} disabled={isPending||nextSet>currentExercise.sets} className="rounded-full bg-[#354653] px-5 py-3 text-[10.5px] font-semibold text-white disabled:opacity-40"><Check size={12} className="mr-1 inline"/>Complete Set</button><button onClick={()=>{setReps(lastHistory?.reps??reps);setWeight(lastHistory?.weightLb??weight)}} className="rounded-full border border-[#dce3e6] px-4 py-3 text-[10px]">Repeat Last</button><button onClick={swapExercise} className="rounded-full border border-[#dce3e6] px-4 py-3 text-[10px]">Swap Exercise</button><button onClick={()=>saveSet(true)} className="rounded-full border border-[#eadbd7] px-4 py-3 text-[10px] text-[#916b63]">Skip</button></div>
     <div className="mt-5 rounded-[20px] border border-[#e6e9e9] p-4"><div className="flex items-center justify-between"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#7b878c]">Set history in this workout</p><span className="text-[9px] text-[#7b878c]">Volume {Math.round(volume).toLocaleString()} lb</span></div><div className="mt-2 space-y-1.5">{currentLogs.length?currentLogs.sort((a,b)=>a.setNumber-b.setNumber).map(l=><div key={l.id} className="flex justify-between rounded-xl bg-[#f7f9f9] px-3 py-2 text-[9.5px]"><span>Set {l.setNumber}</span><span>{l.reps??'—'} reps · {l.weightLb??0} lb · RPE {l.rpe??'—'}</span></div>):<p className="text-[9.5px] text-[#8a9498]">No sets completed yet.</p>}</div></div>
    </div>
    <aside className="space-y-3"><div className="rounded-[22px] bg-[#f5f2ec] p-5"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#837c70]">Smart Rest</p><p className="glow-display mt-2 text-[42px]">{String(Math.floor(restSeconds/60)).padStart(2,'0')}:{String(restSeconds%60).padStart(2,'0')}</p><p className="mt-1 text-[9px] text-[#8c857b]">Recommended for this exercise: {currentExercise.restSeconds}s</p><div className="mt-3 flex gap-2"><button onClick={()=>setRestRunning(v=>!v)} className="rounded-full bg-white p-2.5">{restRunning?<Pause size={13}/>:<Play size={13}/>}</button><button onClick={()=>setRestSeconds(s=>s+30)} className="rounded-full bg-white px-3 py-2 text-[9px]">+30 sec</button><button onClick={()=>{setRestSeconds(0);setRestRunning(false)}} className="rounded-full bg-white px-3 py-2 text-[9px]">Skip rest</button></div></div>
     <div className="rounded-[22px] bg-[#f1f4f6] p-5"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#74838b]">Next</p><p className="mt-2 text-[11px] font-medium">{runExercises[currentIndex+1]?.name??'Workout summary'}</p><button onClick={nextExercise} disabled={currentIndex>=runExercises.length-1} className="mt-3 inline-flex items-center gap-1 rounded-full bg-white px-3 py-2 text-[9px] disabled:opacity-40">Next exercise <ChevronRight size={10}/></button></div>
     <div className="rounded-[22px] border border-[#e2e7e8] p-5"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#74838b]">Hands-free</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={toggleVoice} className={`rounded-full px-3 py-2 text-[9px] ${voice?'bg-[#354653] text-white':'bg-[#f1f4f5]'}`}><Mic2 size={11} className="mr-1 inline"/>{voice?'Listening':'Voice controls'}</button><button onClick={()=>setHandsFree(v=>!v)} className="rounded-full bg-[#f1f4f5] px-3 py-2 text-[9px]"><Volume2 size={11} className="mr-1 inline"/>Large glance</button></div><p className="mt-2 text-[8.5px] leading-4 text-[#899398]">Say “done”, “next exercise”, “add five”, “skip”, “swap exercise”, or “thirty more”.</p></div>
     <button onClick={()=>finish('good')} disabled={isPending} className="w-full rounded-[18px] border border-[#d7e1d2] bg-[#f0f6ed] px-4 py-3 text-[10px] font-semibold text-[#60745a]">Finish Workout</button></aside></div>
   </div></div></div>:null}
 </div>
}

function Control({label,values,value,onChange}:{label:string;values:string[];value:string;onChange:(value:string)=>void}){return <div><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#7a858b]">{label}</p><div className="mt-2 grid grid-cols-2 gap-1.5 sm:grid-cols-4">{values.map(v=><button key={v} type="button" onClick={()=>onChange(v)} className={`rounded-xl px-2 py-2 text-[9px] capitalize ${value===v?'bg-[#354653] text-white':'bg-[#f2f5f5] text-[#69787f]'}`}>{v}</button>)}</div></div>}
function Metric({title,value,detail,icon}:{title:string;value:string;detail:string;icon:React.ReactNode}){return <section className="rounded-[22px] border border-[#e4e7e7] bg-white p-5"><div className="flex items-center justify-between"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#7e8a90]">{title}</p><span className="text-[#74899a]">{icon}</span></div><p className="glow-display mt-3 text-[32px] text-[#2f3a41]">{value}</p><p className="mt-1 text-[9.5px] text-[#879198]">{detail}</p></section>}
function Small({v,l}:{v:string;l:string}){return <div className="rounded-xl bg-white p-2"><p className="text-[10px] font-medium">{v}</p><p className="mt-0.5 text-[7.5px] text-[#8a9499]">{l}</p></div>}
function Big({v,l}:{v:string;l:string}){return <div><p className="glow-display text-[30px] text-[#2d3b43]">{v}</p><p className="text-[8.5px] text-[#7b8990]">{l}</p></div>}
