import type { GlowWorld } from '@/lib/glow-world/room-experience';

export type GlowPageLevel = 'world' | 'room' | 'studio' | 'experience' | 'object' | 'detail' | 'overlay';
export type GlowSyncDimension = 'data' | 'state' | 'time' | 'navigation' | 'intelligence' | 'action' | 'visual' | 'history';
export type GlowPageManifest={id:string;match:string;label:string;world:GlowWorld;level:GlowPageLevel;parent?:string|null;family:string;designFamily:string;layoutFamily:'open'|'structured'|'protected';objectTypes:string[];specialists:string[];sync:GlowSyncDimension[];preservesReturnContext:boolean};
export const REQUIRED_SYNC_DIMENSIONS:GlowSyncDimension[]=['data','state','time','navigation','intelligence','action','visual','history'];
const m=(id:string,match:string,label:string,world:GlowWorld,level:GlowPageLevel,parent:string|null,family:string,designFamily:string,layoutFamily:GlowPageManifest['layoutFamily'],objectTypes:string[]):GlowPageManifest=>({id,match,label,world,level,parent,family,designFamily,layoutFamily,objectTypes,specialists:['glow-kernel'],sync:[...REQUIRED_SYNC_DIMENSIONS],preservesReturnContext:true});

export const GLOW_PAGE_MANIFESTS:GlowPageManifest[]=[
 m('today.world','/today','Today','today','world',null,'today','today-living','open',['day','task','event','routine']),
 m('plan.world','/planning','Plan','plan','world',null,'planning','planning-studio','open',['plan','task','event','goal']),
 m('plan.studio','/planning/studio','Horizon Studio','plan','studio','/planning','planning','planning-studio','open',['planning-period','task','event','routine']),
 m('plan.planner','/planning/planner','Planner','plan','room','/planning','planner-v1','planning-studio','structured',['planning-period','task','event']),
 ...['today','tomorrow','week','month','archive','insights'].map((mch)=>m(`plan.planner.${mch}`,`/planning/planner/${mch}`,mch,'plan','experience','/planning/planner','planner-v1',mch==='archive'||mch==='insights'?'history-room':'planning-studio','structured',['planning-period','task','event'])),
 m('plan.calendar','/calendar','Calendar','plan','room','/planning','planning','temporal-observatory','structured',['event','appointment']),m('plan.tasks','/tasks','Tasks','plan','room','/planning','planning','planning-studio','structured',['task']),m('plan.reminders','/reminders','Reminders','plan','room','/planning','planning','planning-studio','structured',['reminder']),m('plan.routines','/routines','Routines','plan','room','/planning','routines','routine-world','structured',['routine']),m('plan.habits','/habits','Habits','plan','room','/planning','habits','routine-world','structured',['habit']),m('plan.goals','/goals','Goals','plan','room','/planning','goals','future-landscape','open',['goal','milestone']),
 m('life.world','/life','Life','life','world',null,'life','inhabited-world','open',['person','place','resource']),
 m('life.wellness','/wellness','Wellness','life','room','/life','wellness','wellness-room','structured',['wellness-entry','medication','supplement']),m('life.fitness','/fitness','Fitness','life','room','/life','fitness','fitness-room','structured',['workout','exercise','recovery-signal']),m('life.food','/food','Food','life','room','/life','food','food-room','structured',['meal','food']),m('life.closet','/closet','Closet','life','room','/life','closet','dressing-room','open',['clothing-item','outfit','wear-history']),m('life.finance','/finance','Money','life','room','/life','money','money-room','structured',['transaction','account','bill']),m('life.money','/money','Money','life','room','/life','money','money-room','structured',['transaction','account','bill']),m('home.executive','/home','Home','today','world',null,'home','executive-home','open',['day','task','event','routine','goal','wellness-entry']),m('life.work','/work','Work','life','room','/life','work','work-room','structured',['work-shift','job']),m('life.travel','/travel','Travel','life','room','/life','travel','travel-room','open',['trip','reservation','place']),m('life.relationships','/relationships','Relationships','life','room','/life','relationships','relationship-room','open',['person','relationship']),
 m('beauty.world','/beauty','Beauty','beauty','world',null,'beauty','personal-atelier','open',['product','routine','look']),m('beauty.today','/beauty/today','Beauty Today','beauty','room','/beauty','beauty','personal-atelier','structured',['routine','product']),m('beauty.skincare','/beauty/skincare','Skincare','beauty','studio','/beauty','skincare','skincare-studio','open',['routine','product']),m('beauty.gua-sha','/beauty/gua-sha','Gua Sha Studio','beauty','studio','/beauty','gua-sha','gua-sha-studio','open',['routine','tool','session']),m('beauty.makeup','/beauty/makeup','Makeup','beauty','studio','/beauty','makeup','makeup-studio','open',['product','look']),m('beauty.body','/beauty/body','Body Care','beauty','studio','/beauty','body-care','beauty-studio','open',['product','routine']),m('beauty.fragrance','/beauty/fragrance','Fragrance','beauty','studio','/beauty','fragrance','beauty-studio','open',['product']),m('beauty.maintenance','/beauty/maintenance','Beauty Maintenance','beauty','studio','/beauty','beauty-maintenance','beauty-studio','structured',['routine','appointment']),m('beauty.devices','/beauty/devices','Devices','beauty','room','/beauty','beauty-devices','beauty-studio','structured',['device','tool']),m('beauty.inventory','/beauty/inventory','Inventory','beauty','room','/beauty','beauty-inventory','inventory-room','structured',['product','device','tool']),m('beauty.progress','/beauty/progress','Progress','beauty','room','/beauty','beauty-progress','history-room','structured',['history','routine','product']),
 m('brain.world','/brain','Brain','brain','world',null,'brain','knowledge-world','open',['note','memory','connection']),m('brain.search','/search','Universal Search','brain','room','/brain','search','universal-lens','open',['glow-object']),m('brain.notes','/notes','Notes','brain','room','/brain','notes','knowledge-room','structured',['note']),m('brain.memory','/memory','Memory','brain','room','/brain','memory','knowledge-room','open',['memory']),m('brain.timeline','/timeline','Timeline','brain','room','/brain','timeline','history-room','open',['history']),m('brain.connections','/connections','Connections','brain','room','/brain','connections','knowledge-room','open',['relationship']),m('brain.observations','/observations','Observations','brain','room','/brain','observations','knowledge-room','open',['observation']),m('brain.inbox','/inbox','Capture Inbox','brain','room','/brain','capture','knowledge-room','structured',['capture','note','task']),
 m('create.world','/create','Create','create','world',null,'create','creation-world','open',['creation']),m('create.import','/import','Import','create','room','/create','import','creation-room','structured',['source','document']),m('create.concierge','/concierge','Concierge','create','room','/create','concierge','creation-room','open',['glow-object']),m('create.projects','/projects','Projects','create','room','/create','projects','creation-room','structured',['project','creation']),m('create.resources','/resources','Resources','create','room','/create','resources','creation-room','structured',['resource','reference']),
];
function normalize(path:string){return(path.split('?')[0]||'/').replace(/\/$/,'')||'/'}
export function pageManifestFor(path:string){const pathname=normalize(path);const exact=GLOW_PAGE_MANIFESTS.find(i=>i.match===pathname);if(exact)return exact;return[...GLOW_PAGE_MANIFESTS].filter(i=>pathname.startsWith(`${i.match}/`)).sort((a,b)=>b.match.length-a.match.length)[0]??null}
export function pageManifestChainFor(path:string){const current=pageManifestFor(path);if(!current)return[];const chain:GlowPageManifest[]=[current];let parent=current.parent?pageManifestFor(current.parent):null;const seen=new Set([current.id]);while(parent&&!seen.has(parent.id)){seen.add(parent.id);chain.unshift(parent);parent=parent.parent?pageManifestFor(parent.parent):null}return chain}
export function pageContractViolations(path:string){const manifest=pageManifestFor(path);if(!manifest)return[`UNREGISTERED_PAGE:${normalize(path)}`];const missing=REQUIRED_SYNC_DIMENSIONS.filter(i=>!manifest.sync.includes(i));return[...missing.map(i=>`MISSING_SYNC:${i}`),...(manifest.preservesReturnContext?[]:['RETURN_CONTEXT_DISABLED'])]}
