import Link from 'next/link';
import { cookies } from 'next/headers';
import { auth } from '@/auth';
import { redirect } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { Batch10RemindersView } from '@/components/batch10/special-features-reference';
import { getAppleReminderConnection, getAppleRemindersByUser } from '@/lib/apple-reminders/service';
import { understandAppleReminder } from '@/lib/apple-reminders/intelligence';
import { BellRing, CalendarDays, CircleAlert, Clock3, Crosshair, HeartPulse, ListTodo, MapPin, Repeat2, ShoppingBasket, Sparkles, Target, Workflow } from 'lucide-react';

export const dynamic='force-dynamic';
type Mode='very-productive'|'normal'|'low'|'cancel-everything';
type Audit=Record<string,unknown>;

function readAudit(audit:Audit|null,key:string){return audit?.[key];}
function modeLabel(mode:Mode){return mode==='very-productive'?'Very Productive':mode==='low'?'Low Productive':mode==='cancel-everything'?'Cancel Everything':'Normal Productive';}

export default async function RemindersPage(){
  const session=await auth();if(!session?.user?.id)redirect('/sign-in');
  const userId=session.user.id;const cookieStore=await cookies();const rawMode=cookieStore.get('glow-os-productivity-mode')?.value;const mode:Mode=rawMode==='very-productive'||rawMode==='low'||rawMode==='cancel-everything'?rawMode:'normal';
  const[rows,connection]=await Promise.all([getAppleRemindersByUser(userId),getAppleReminderConnection(userId)]);
  const rich=rows.map(row=>{
    const audit=row.importAudit as Audit|null;
    const recurrence=typeof readAudit(audit,'recurrence')==='string'?String(readAudit(audit,'recurrence')):null;
    const locationName=typeof readAudit(audit,'locationName')==='string'?String(readAudit(audit,'locationName')):null;
    const locationTrigger=readAudit(audit,'locationTrigger')==='arrive'||readAudit(audit,'locationTrigger')==='leave'?readAudit(audit,'locationTrigger') as 'arrive'|'leave':null;
    const priority=['none','low','medium','high'].includes(String(readAudit(audit,'priority')))?String(readAudit(audit,'priority')) as 'none'|'low'|'medium'|'high':'none';
    const flagged=Boolean(readAudit(audit,'flagged'));const snoozeCount=Number(readAudit(audit,'snoozeCount')??0);
    const intelligence=understandAppleReminder({title:row.title,notes:row.notes,dueAt:row.dueAt,completed:row.completed,listName:row.listName,recurrence,locationName,locationTrigger,priority,flagged,snoozeCount});
    return {...row,recurrence,locationName,locationTrigger,priority,flagged,snoozeCount,...intelligence};
  });
  const reminders=rich.map(row=>({id:row.id,title:row.title,notes:row.notes,listName:row.listName,dueAt:row.dueAt?.toISOString()??null,completed:row.completed,lastSyncedAt:row.lastSyncedAt.toISOString(),domain:row.domain,destinations:row.destinations,intent:row.intent,urgency:row.urgency,nextAction:row.nextAction}));
  const now=new Date();const start=new Date(now);start.setHours(0,0,0,0);const end=new Date(now);end.setHours(23,59,59,999);const week=new Date(end);week.setDate(week.getDate()+7);
  const open=rich.filter(x=>!x.completed);const overdue=open.filter(x=>x.dueAt&&x.dueAt<start);const today=open.filter(x=>x.dueAt&&x.dueAt>=start&&x.dueAt<=end);const upcoming=open.filter(x=>x.dueAt&&x.dueAt>end&&x.dueAt<=week);const noDate=open.filter(x=>!x.dueAt);const essential=open.filter(x=>x.essential);const escalation=open.filter(x=>x.escalationCandidate);const location=open.filter(x=>x.triggerType==='location');const recurring=open.filter(x=>x.triggerType==='recurring');
  const visible=mode==='cancel-everything'?open.filter(x=>x.essential):mode==='low'?open.filter(x=>x.essential||x.urgency==='today'||x.urgency==='overdue'):open;
  const safeToMove=mode==='low'||mode==='cancel-everything'?open.filter(x=>!visible.some(v=>v.id===x.id)):[];
  const listCounts=Array.from(open.reduce((m,x)=>m.set(x.listName,(m.get(x.listName)||0)+1),new Map<string,number>()).entries()).sort((a,b)=>b[1]-a[1]).slice(0,6);
  const workflows=Array.from(open.reduce((m,x)=>m.set(x.workflow,(m.get(x.workflow)||0)+1),new Map<string,number>()).entries()).sort((a,b)=>b[1]-a[1]);

  return <AppShell><div className="mx-auto max-w-[1180px] space-y-4 pb-24">
    <section className="rounded-[26px] border border-[#eadfdb] bg-[linear-gradient(135deg,#fff9f8,#f6ece9)] p-5 sm:p-7"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-white shadow-sm"><BellRing size={19} className="text-[#b85d70]"/></span><div className="min-w-0"><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[#b85d70]">Apple Reminders × Glow Intelligence</p><h1 className="mt-1 font-serif text-[34px] sm:text-[44px]">Reminder Command Center</h1><p className="mt-2 max-w-3xl text-[11px] leading-5 text-[#776d68]">Tasks are what you need to do. Reminders are the moment Glow brings something back to your attention. Apple Reminders stays the fast iOS capture source while Glow decides what matters, when it should surface, and which room should understand it.</p><div className="mt-3 inline-flex rounded-full border border-[#eadfdb] bg-white px-3 py-1.5 text-[9px] text-[#7c6f69]">Today · {modeLabel(mode)} · {visible.length} visible reminder{visible.length===1?'':'s'}</div></div></div></section>

    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-6"><Metric label="Essential" value={essential.length} icon={<HeartPulse size={14}/>}/><Metric label="Overdue" value={overdue.length} icon={<CircleAlert size={14}/>}/><Metric label="Due Today" value={today.length} icon={<BellRing size={14}/>}/><Metric label="Next 7 Days" value={upcoming.length} icon={<CalendarDays size={14}/>}/><Metric label="Location" value={location.length} icon={<MapPin size={14}/>}/><Metric label="Recurring" value={recurring.length} icon={<Repeat2 size={14}/>}/></section>

    {(mode==='low'||mode==='cancel-everything')?<section className="rounded-[20px] border border-[#e8e2dc] bg-[#fbf8f5] p-4"><div className="flex items-start gap-3"><Sparkles size={16} className="mt-0.5 text-[#9b6a76]"/><div><h2 className="font-serif text-[21px]">Mode-protected reminders</h2><p className="mt-1 text-[10px] leading-5 text-[#746963]">Glow is showing {visible.length} reminder{visible.length===1?'':'s'} that are essential, overdue, or due today. {safeToMove.length} nonessential reminder{safeToMove.length===1?' is':'s are'} held in Safe to Move so the day stays lighter. Nothing is deleted.</p></div></div></section>:null}

    <section className="grid gap-3 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-[20px] border border-[#eee5e1] bg-white p-4"><div className="flex items-center gap-2"><Workflow size={15} className="text-[#b85d70]"/><h2 className="font-serif text-[20px]">Capture → Glow decides → action system</h2></div><div className="mt-3 grid gap-2 sm:grid-cols-4 text-[10px]"><Step n="1" title="Capture" body="Siri, Apple Reminders, Add Anything or Concierge."/><Step n="2" title="Understand" body="Glow detects care, appointment, follow-up, shopping, goal, routine or maintenance context."/><Step n="3" title="Trigger" body="Time, place, recurrence or contextual moment determines when it should return."/><Step n="4" title="Route" body="Glow connects it to Today, Calendar, Routine, Task, Goal, Food, Home, Fitness, Beauty, Work or Brain."/></div><div className="mt-4 flex flex-wrap gap-2"><Link href="/intake" className="rounded-full bg-[#c86679] px-4 py-2 text-[10px] text-white">Add Anything</Link><Link href="/concierge" className="rounded-full border border-[#eadfdb] px-4 py-2 text-[10px]">Ask Glow to remind me</Link><Link href="/planning" className="rounded-full border border-[#eadfdb] px-4 py-2 text-[10px]">Plan around reminders</Link></div></div>
      <div className="rounded-[20px] border border-[#eee5e1] bg-white p-4"><h2 className="font-serif text-[20px]">Trigger mix</h2><div className="mt-3 space-y-2"><Tiny label="Time based" value={open.filter(x=>x.triggerType==='time').length}/><Tiny label="Location based" value={location.length}/><Tiny label="Recurring" value={recurring.length}/><Tiny label="Context aware" value={open.filter(x=>x.triggerType==='context').length}/><Tiny label="Unscheduled" value={noDate.length}/></div></div></section>

    <details open className="rounded-[20px] border border-[#eee5e1] bg-white p-4"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.14em] text-[#a09088]">15-system upgrade</p><h2 className="mt-1 font-serif text-[23px]">What Reminders now powers</h2></div><Sparkles size={16} className="text-[#b85d70]"/></div></summary><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">
      <Capability n="01" title="Time triggers" body="Due times, tomorrow prompts, pre-event timing and recurring weekly prompts feed Today and planning."/>
      <Capability n="02" title="Location triggers" body="Arrival/leave metadata can be preserved from the iOS bridge and routed to Home, Food, Fitness or Work."/>
      <Capability n="03" title="Routine-step prompts" body="Routine-like reminders are classified as routine triggers instead of becoming duplicate task inventory."/>
      <Capability n="04" title="Care prompts" body="Medication, refill, hydration and care reminders are marked essential and stay visible on low-capacity days."/>
      <Capability n="05" title="Appointment preparation" body="Appointment reminders connect to Calendar, Today and Briefings so preparation and follow-up stay around the event."/>
      <Capability n="06" title="Follow-ups" body="Email, call, application, order and renewal reminders are grouped as follow-up workflows."/>
      <Capability n="07" title="Shopping + groceries" body="Shopping reminders are classified into Food, Home, Beauty, prescriptions and errand contexts instead of one random pile."/>
      <Capability n="08" title="Concierge context" body="Glow can reason about phrases such as after my appointment, next Hair day or when I have time tomorrow."/>
      <Capability n="09" title="Goal prompts" body="Goal reminders become strategic milestone/check-in prompts and can surface in Planning and Briefings."/>
      <Capability n="10" title="Glow Mode filtering" body="Low shows essentials + due items. Cancel Everything shows essentials only and moves the rest into Safe to Move."/>
      <Capability n="11" title="Life maintenance" body="Cleaning, restocks, subscriptions, renewals and recurring upkeep are understood as maintenance systems."/>
      <Capability n="12" title="Remind from anywhere" body="Add Anything and Concierge are the universal entry points so you do not need to hunt for the Reminders page first."/>
      <Capability n="13" title="Reminder → Task escalation" body="Four or more postponements can mark a reminder as an escalation candidate for Task, Project or Calendar review."/>
      <Capability n="14" title="Brain intelligence" body="Glow tracks reminder load, split capture, location-trigger use and reminders that are becoming real tasks."/>
      <Capability n="15" title="Morning + Evening Briefings" body="Due and essential reminders now feed the same personal-context engine used by Glow Briefings and Attention Center."/>
    </div></details>

    <section className="grid gap-3 lg:grid-cols-3"><div className="rounded-[20px] border border-[#eee5e1] bg-white p-4"><div className="flex items-center gap-2"><Crosshair size={15} className="text-[#b85d70]"/><h2 className="font-serif text-[20px]">Workflow routing</h2></div><div className="mt-3 space-y-2">{workflows.length?workflows.map(([name,count])=><Tiny key={name} label={name.replace('-', ' ')} value={count}/>):<p className="text-[10px] text-[#8a817b]">Sync reminders to populate workflow intelligence.</p>}</div></div>
      <div className="rounded-[20px] border border-[#eee5e1] bg-white p-4"><div className="flex items-center gap-2"><ShoppingBasket size={15} className="text-[#b85d70]"/><h2 className="font-serif text-[20px]">Apple lists</h2></div><div className="mt-3 space-y-2">{listCounts.length?listCounts.map(([name,count])=><Tiny key={name} label={name} value={count}/>):<p className="text-[10px] text-[#8a817b]">No open reminders have synced yet.</p>}</div></div>
      <div className="rounded-[20px] border border-[#eee5e1] bg-white p-4"><div className="flex items-center gap-2"><Target size={15} className="text-[#b85d70]"/><h2 className="font-serif text-[20px]">Escalation review</h2></div><p className="mt-2 text-[10px] leading-5 text-[#746963]">A reminder should stop behaving like a reminder when it repeatedly needs planning.</p><div className="mt-3 rounded-xl bg-[#faf6f4] p-3"><strong className="font-serif text-[25px] font-normal">{escalation.length}</strong><p className="text-[9px] text-[#8a817b]">candidate{escalation.length===1?'':'s'} for Task / Project / Calendar review</p></div><Link href="/tasks" className="mt-3 inline-flex text-[10px] text-[#874555]">Open Tasks →</Link></div></section>

    <section className="rounded-[20px] border border-[#eee5e1] bg-white p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] uppercase tracking-[.14em] text-[#a09088]">Visible in {modeLabel(mode)} mode</p><h2 className="mt-1 font-serif text-[22px]">What Glow is protecting right now</h2></div><Clock3 size={16} className="text-[#b85d70]"/></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{visible.slice(0,6).map(item=><div key={item.id} className="rounded-[14px] border border-[#f0e8e4] bg-[#fffdfc] p-3"><div className="flex items-center justify-between gap-2"><strong className="truncate text-[10px] font-medium">{item.title}</strong>{item.essential?<span className="rounded-full bg-[#f7e7e9] px-2 py-1 text-[8px] text-[#a44f63]">Essential</span>:null}</div><p className="mt-1 text-[9px] text-[#948780]">{item.workflow} · {item.triggerType} · {item.listName}</p></div>)}{!visible.length?<p className="text-[10px] text-[#8a817b]">Nothing requires reminder attention right now.</p>:null}</div>{safeToMove.length?<div className="mt-4 border-t border-[#f0e8e4] pt-3"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#a09088]">Safe to Move · {safeToMove.length}</p><p className="mt-1 text-[10px] leading-5 text-[#80736d]">These stay out of the main cognitive load in the current Glow Mode. They remain available below and in Apple Reminders.</p></div>:null}</section>

    <Batch10RemindersView reminders={reminders}/>
    <div className="flex flex-col gap-2 rounded-[12px] border border-[#ebe4df] bg-white px-4 py-3 text-[9px] leading-5 text-[#8a817b] sm:flex-row sm:items-center sm:justify-between"><span><b>Apple boundary:</b> Glow can now import, understand, rank, route and adapt reminder metadata. Editing/completing the original Apple reminder still happens in Apple Reminders until the iOS bridge supports safe write-back.</span><Link href="/connections#apple-reminders" className="shrink-0 text-[#874555]">{connection?.status==='connected'?'Sync settings':'Set up Apple Reminders sync'} →</Link></div>
  </div></AppShell>;
}
function Metric({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div className="rounded-[18px] border border-[#eee5e1] bg-white p-4"><div className="flex items-center gap-2 text-[#b85d70]">{icon}<span className="text-[9px] uppercase tracking-[.12em] text-[#958881]">{label}</span></div><strong className="mt-2 block font-serif text-[28px] font-normal">{value}</strong></div>}
function Step({n,title,body}:{n:string;title:string;body:string}){return <div className="rounded-[14px] bg-[#fcf8f6] p-3"><span className="text-[8px] font-semibold text-[#b85d70]">{n}</span><strong className="mt-1 block text-[10px]">{title}</strong><p className="mt-1 text-[9px] leading-4 text-[#80736d]">{body}</p></div>}
function Capability({n,title,body}:{n:string;title:string;body:string}){return <div className="rounded-[15px] border border-[#f0e8e4] bg-[#fffdfc] p-3"><div className="flex items-center gap-2"><span className="text-[8px] font-semibold text-[#b85d70]">{n}</span><strong className="text-[10px]">{title}</strong></div><p className="mt-1.5 text-[9px] leading-4 text-[#80736d]">{body}</p></div>}
function Tiny({label,value}:{label:string;value:number}){return <div className="flex items-center justify-between rounded-xl bg-[#faf6f4] px-3 py-2 text-[10px]"><span className="capitalize">{label}</span><b>{value}</b></div>}
