'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Eye, EyeOff, PiggyBank, ReceiptText, ShieldCheck, Sparkles, WalletCards } from 'lucide-react';
import type { FinanceEntry } from '@/lib/types';

type FinanceGoal={id:string;name:string;goalType:string;targetCents:number;currentCents:number;targetDate:Date|string|null;notes?:string|null};
type ProjectLite={id:string;title:string;status:string;priority:string;progress:number;nextAction:string|null;deadline:Date|string|null};
type LifeGoalLite={id:string;title:string;status:string;category:string;progress:number;targetDate:Date|string|null};
type Tab='today'|'cashflow'|'spending'|'budget'|'bills'|'savings'|'goals'|'forecast'|'decisions'|'subscriptions'|'income'|'reviews'|'memory'|'insights';
type ForecastMode='Conservative'|'Expected'|'Optimistic';
type SpendMode='Normal'|'Low-spend · 3 days'|'Low-spend · 1 week'|'Low-spend · until payday'|'Low-spend · rest of month';
type MoneyMemory={buffer:number;essentials:number;privacy:boolean;forecast:ForecastMode;spendMode:SpendMode;decisions:string[];notes:string[];purchasePrice:number;purchaseCategory:string};

const KEY='glow:financial-intelligence:v1';
const TZ='America/New_York';
const tabs:Tab[]=['today','cashflow','spending','budget','bills','savings','goals','forecast','decisions','subscriptions','income','reviews','memory','insights'];
const defaults:MoneyMemory={buffer:250,essentials:0,privacy:false,forecast:'Expected',spendMode:'Normal',decisions:[],notes:[],purchasePrice:0,purchaseCategory:'shopping'};
const currency=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const monthKey=(s:string)=>s.slice(0,7);
const lower=(s?:string|null)=>(s??'').trim().toLowerCase();
function dateKey(d:Date){const p=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`;}
function isRecurring(e:FinanceEntry){const h=`${lower(e.title)} ${lower(e.category)} ${lower(e.notes)}`;return ['subscription','rent','mortgage','insurance','phone','internet','utility','utilities','membership','bill'].some(t=>h.includes(t));}
function openGlow(prompt:string){window.dispatchEvent(new CustomEvent('glow:open-conversation',{detail:{prompt}}));}
function normalize(v:unknown):MoneyMemory{if(!v||typeof v!=='object')return defaults;const x=v as Partial<MoneyMemory>;return{buffer:typeof x.buffer==='number'?Math.max(0,Math.min(100000,x.buffer)):defaults.buffer,essentials:typeof x.essentials==='number'?Math.max(0,Math.min(100000,x.essentials)):0,privacy:Boolean(x.privacy),forecast:['Conservative','Expected','Optimistic'].includes(x.forecast??'')?x.forecast as ForecastMode:'Expected',spendMode:['Normal','Low-spend · 3 days','Low-spend · 1 week','Low-spend · until payday','Low-spend · rest of month'].includes(x.spendMode??'')?x.spendMode as SpendMode:'Normal',decisions:Array.isArray(x.decisions)?x.decisions.filter((n):n is string=>typeof n==='string').slice(-30):[],notes:Array.isArray(x.notes)?x.notes.filter((n):n is string=>typeof n==='string').slice(-40):[],purchasePrice:typeof x.purchasePrice==='number'?Math.max(0,x.purchasePrice):0,purchaseCategory:typeof x.purchaseCategory==='string'?x.purchaseCategory:'shopping'};}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[28px] border border-white/70 bg-white/48 p-5 shadow-[0_20px_70px_rgba(73,72,66,.08)] backdrop-blur-2xl"><div className="mb-4 text-[10px] uppercase tracking-[.24em] text-[#77756f]">{title}</div>{children}</section>}

export function FinancialIntelligenceStudio({entries,financeGoals,projects,lifeGoals}:{entries:FinanceEntry[];financeGoals:FinanceGoal[];projects:ProjectLite[];lifeGoals:LifeGoalLite[]}){
 const now=useMemo(()=>new Date(),[]);const currentMonth=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;const today=dateKey(now);
 const [tab,setTab]=useState<Tab>('today');const [memory,setMemory]=useState<MoneyMemory>(defaults);const [hydrated,setHydrated]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setMemory(normalize(JSON.parse(raw)));}catch{}setHydrated(true);},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(KEY,JSON.stringify(memory));}catch{}},[memory,hydrated]);
 const current=entries.filter(e=>monthKey(e.entryDate)===currentMonth);const income=current.filter(e=>e.type==='income').reduce((s,e)=>s+Number(e.amount),0);const spent=current.filter(e=>e.type==='expense').reduce((s,e)=>s+Number(e.amount),0);const saved=current.filter(e=>e.type==='saving').reduce((s,e)=>s+Number(e.amount),0);const invested=current.filter(e=>e.type==='investment').reduce((s,e)=>s+Number(e.amount),0);
 const recordedPosition=income-spent-saved-invested;const safe=Math.max(0,recordedPosition-memory.essentials-memory.buffer);const purchaseAfter=safe-memory.purchasePrice;
 const expenses=current.filter(e=>e.type==='expense');const todaySpent=expenses.filter(e=>e.entryDate===today).reduce((s,e)=>s+Number(e.amount),0);
 const byCat=[...expenses.reduce<Map<string,number>>((m,e)=>m.set(e.category,(m.get(e.category)??0)+Number(e.amount)),new Map()).entries()].sort((a,b)=>b[1]-a[1]);
 const recurring=[...entries.filter(e=>e.type==='expense'&&isRecurring(e)).sort((a,b)=>b.entryDate.localeCompare(a.entryDate)).reduce<Map<string,FinanceEntry>>((m,e)=>{const k=`${lower(e.title)}|${e.category}`;if(!m.has(k))m.set(k,e);return m;},new Map()).values()];
 const subscriptions=recurring.filter(e=>`${lower(e.title)} ${lower(e.category)} ${lower(e.notes)}`.includes('subscription')||`${lower(e.title)} ${lower(e.notes)}`.includes('membership'));
 const recurringTotal=recurring.reduce((s,e)=>s+Number(e.amount),0);const savingsProgress=financeGoals.length?Math.round(financeGoals.reduce((s,g)=>s+Math.min(1,g.targetCents>0?g.currentCents/g.targetCents:0),0)/financeGoals.length*100):0;
 const monthDays=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();const elapsed=Math.max(1,now.getDate());const projectedSpend=spent/elapsed*monthDays;
 const historicalMonths=[...new Set(entries.filter(e=>e.type==='expense'&&monthKey(e.entryDate)!==currentMonth).map(e=>monthKey(e.entryDate)))];const histAvg=historicalMonths.length?entries.filter(e=>e.type==='expense'&&monthKey(e.entryDate)!==currentMonth).reduce((s,e)=>s+Number(e.amount),0)/historicalMonths.length:0;
 const state=recordedPosition<0?'Needs adjustment':safe===0&&recordedPosition>0?'Watch closely':safe<memory.buffer?'Tight':safe>Math.max(500,memory.buffer*2)?'Comfortable':'Stable';
 const recent=[...entries].sort((a,b)=>b.entryDate.localeCompare(a.entryDate)).slice(0,12);const incomeEntries=current.filter(e=>e.type==='income');const expenseRatio=income>0?spent/income:0;
 const display=(n:number)=>memory.privacy?'••••':currency(n);
 function note(text:string){setMemory(m=>({...m,notes:[...m.notes,`${new Intl.DateTimeFormat('en-US',{timeZone:TZ,month:'short',day:'numeric'}).format(now)} · ${text}`].slice(-40)}));}
 function ask(text:string){openGlow(text);note(text.slice(0,130));}
 const decisionText=memory.purchasePrice>0?(purchaseAfter>=0?`Recorded-data check: this purchase fits inside the current safe-to-spend estimate and would leave ${display(purchaseAfter)}.`:`Recorded-data check: this purchase is ${display(Math.abs(purchaseAfter))} above the current safe-to-spend estimate.`):'Enter a price to preview its impact on the recorded-data estimate.';
 return <div className="min-h-screen rounded-[38px] bg-[radial-gradient(circle_at_12%_3%,rgba(255,244,224,.85),transparent_29%),radial-gradient(circle_at_84%_12%,rgba(216,228,226,.78),transparent_31%),radial-gradient(circle_at_58%_84%,rgba(226,214,224,.72),transparent_32%),linear-gradient(150deg,#fbf9f3_0%,#eef2f0_48%,#f2ecee_100%)] p-3 text-[#343430] sm:p-5">
  <header className="rounded-[32px] border border-white/75 bg-white/35 p-5 shadow-[0_35px_110px_rgba(72,72,65,.11)] backdrop-blur-2xl sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.32em] text-[#77756f]">Finance · Financial Intelligence</div><h1 className="mt-2 glow-display text-3xl sm:text-5xl">Your liquid treasury.</h1><p className="mt-3 max-w-3xl text-sm text-[#74736e]">What is my money doing, what needs my attention, what can I safely spend, and what should I do next to make my financial life stronger?</p></div><div className="flex gap-2"><button onClick={()=>setMemory(m=>({...m,privacy:!m.privacy}))} className="couture-secondary">{memory.privacy?<Eye className="mr-2 inline h-4 w-4"/>:<EyeOff className="mr-2 inline h-4 w-4"/>}{memory.privacy?'Show amounts':'Hide amounts'}</button><button onClick={()=>ask('What should I do with my money right now? Use only my recorded Glow Finance data, clearly label estimates, and tell me the strongest next move.')} className="couture-secondary"><Sparkles className="mr-2 inline h-4 w-4"/>Ask Glow</button></div></div>
   <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 rounded-full px-4 py-2 text-[10px] capitalize ${tab===t?'bg-[#4c504b] text-white':'border border-white/75 bg-white/45'}`}>{t}</button>)}</div></header>
  <div className="mt-4 space-y-4">
   {tab==='today'?<><Panel title="Money · Today"><div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div><div className="text-[10px] uppercase tracking-[.2em] text-[#817d75]">Current money state</div><h2 className="mt-2 glow-display text-4xl">{state}</h2><p className="mt-2 max-w-xl text-sm text-[#73736e]">Based only on entries recorded in Glow this month. This is not a live bank balance and does not assume unrecorded bills or income.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Mini label="Recorded position" value={display(recordedPosition)}/><Mini label="Safe-to-spend estimate" value={display(safe)}/><Mini label="Recurring detected" value={`${recurring.length}`}/><Mini label="Savings goals" value={financeGoals.length?`${savingsProgress}% avg`:'None yet'}/></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>ask('Can I spend today? Use my recorded Finance entries, current safe-to-spend assumptions, current month pace and savings. Do not assume bank balances I have not recorded.')} className="couture-primary">What should I do with my money?</button><button onClick={()=>ask('Review my recorded spending this month and tell me what deserves attention.')} className="couture-secondary">Review spending</button><button onClick={()=>setMemory(m=>({...m,spendMode:m.spendMode==='Normal'?'Low-spend · 1 week':'Normal'}))} className="couture-secondary">{memory.spendMode==='Normal'?'Low-spend mode':'End low-spend mode'}</button><button onClick={()=>setTab('income')} className="couture-secondary">Plan next paycheck</button></div></div><div className="rounded-[26px] border border-white/75 bg-white/48 p-5"><div className="text-[10px] uppercase tracking-[.18em]">Safe to spend</div><div className="mt-3 glow-display text-4xl">{display(safe)}</div><div className="mt-4 space-y-2 text-xs text-[#72726d]"><Row k="Recorded position" v={display(recordedPosition)}/><Row k="Protected savings logged" v={display(saved)}/><Row k="Planned essentials assumption" v={`−${display(memory.essentials)}`}/><Row k="Safety buffer" v={`−${display(memory.buffer)}`}/></div><p className="mt-4 text-[10px] leading-4 text-[#8b8880]">Estimate only. Glow currently does not have live account balances or a dedicated bills table.</p></div></div></Panel><Panel title="Quick actions"><div className="flex flex-wrap gap-2"><a href="#finance-manager" className="couture-secondary">＋ Transaction</a><button onClick={()=>setTab('decisions')} className="couture-secondary">Can I buy this?</button><button onClick={()=>setTab('savings')} className="couture-secondary">Save for something</button><button onClick={()=>setTab('bills')} className="couture-secondary">Review bills</button><button onClick={()=>ask('I have a money question. Use my Finance records and clearly distinguish recorded facts from estimates.')} className="couture-secondary">Money question</button></div></Panel></>:null}
   {tab==='cashflow'?<Panel title="Cash Flow River"><div className="grid gap-4 md:grid-cols-4"><Pool label="Income current month" value={display(income)} strength={income}/><Pool label="Expenses" value={display(spent)} strength={spent}/><Pool label="Savings" value={display(saved)} strength={saved}/><Pool label="Investments" value={display(invested)} strength={invested}/></div><div className="mt-6 rounded-[26px] border border-white/70 bg-white/40 p-5"><div className="mb-3 text-sm font-medium">Recent money current</div>{recent.length?recent.map(e=><Link href={`/finance?entryId=${e.id}`} key={e.id} className="flex items-center gap-3 border-t border-white/55 py-3 first:border-0"><span className="w-16 text-[10px] text-[#89867f]">{e.entryDate.slice(5)}</span><span className="flex-1 text-sm">{e.title}</span><span className="text-xs">{e.type==='income'?'+':e.type==='expense'?'−':''}{display(Number(e.amount))}</span></Link>):<div className="text-sm text-[#7e7c76]">No Finance entries yet.</div>}</div></Panel>:null}
   {tab==='spending'?<><Panel title="Spending Pulse"><div className="grid gap-3 sm:grid-cols-3"><Mini label="Spent today" value={display(todaySpent)}/><Mini label="Spent this month" value={display(spent)}/><Mini label="Projected month-end" value={display(projectedSpend)}/></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{byCat.length?byCat.map(([c,a])=><div key={c} className="rounded-[24px] bg-white/45 p-4"><div className="text-[10px] uppercase tracking-[.18em]">{c}</div><div className="mt-2 glow-display text-2xl">{display(a)}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-[#a9b9ae]" style={{width:`${Math.min(100,spent>0?a/spent*100:0)}%`}}/></div></div>):<div className="text-sm text-[#77756f]">No expenses recorded this month.</div>}</div></Panel><Panel title="Low-spend mode"><div className="flex flex-wrap gap-2">{(['Normal','Low-spend · 3 days','Low-spend · 1 week','Low-spend · until payday','Low-spend · rest of month'] as SpendMode[]).map(m=><button key={m} onClick={()=>{setMemory(v=>({...v,spendMode:m}));note(`Spending mode set to ${m}.`);}} className={`rounded-full px-4 py-2 text-xs ${memory.spendMode===m?'bg-[#505650] text-white':'bg-white/55'}`}>{m}</button>)}</div></Panel></>:null}
   {tab==='budget'?<><Panel title="Adaptive Budget"><p className="text-sm text-[#73716b]">Because Glow does not yet have a dedicated budget table, the guide below compares this month with your prior logged monthly average. It is a trend guide, not a spending limit.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{byCat.map(([c,a])=>{const hist=historicalMonths.length?entries.filter(e=>e.type==='expense'&&e.category===c&&monthKey(e.entryDate)!==currentMonth).reduce((s,e)=>s+Number(e.amount),0)/historicalMonths.length:0;const ratio=hist>0?a/hist:0;return <div key={c} className="rounded-[22px] bg-white/45 p-4"><div className="flex justify-between gap-3"><span className="capitalize">{c}</span><span className="text-xs">{hist?`${Math.round(ratio*100)}% of history guide`:'No history guide'}</span></div><div className="mt-2 text-xs text-[#77756f]">{display(a)} spent · prior avg {display(hist)}</div></div>})}</div><div className="mt-4 flex gap-2"><button onClick={()=>ask('My budget feels off. Rebuild the rest of this month from my recorded entries. Ask only for missing information that materially changes the plan.')} className="couture-primary">My budget is off</button><button onClick={()=>ask('Adjust the rest of my spending week using my recorded category pace and current low-spend setting.')} className="couture-secondary">Adjust week</button></div></Panel><Panel title="Planning assumptions"><div className="grid gap-3 sm:grid-cols-2"><MoneyInput label="Protected essential spending not yet recorded" value={memory.essentials} onChange={v=>setMemory(m=>({...m,essentials:v}))}/><MoneyInput label="Safety buffer" value={memory.buffer} onChange={v=>setMemory(m=>({...m,buffer:v}))}/></div></Panel></>:null}
   {tab==='bills'?<Panel title="Bills Center"><p className="text-sm text-[#73716b]">These are recurring-looking expenses detected from titles, categories and notes. Glow does not invent due dates or autopay status that you have not recorded.</p><div className="mt-4 space-y-2">{recurring.length?recurring.map(e=><Link href={`/finance?entryId=${e.id}`} key={e.id} className="flex items-center gap-3 rounded-[20px] bg-white/45 p-4"><ReceiptText className="h-4 w-4"/><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{e.title}</div><div className="text-[10px] text-[#85827b]">Last recorded {e.entryDate} · {e.category}</div></div><span className="text-sm">{display(Number(e.amount))}</span></Link>):<div className="text-sm text-[#77756f]">No recurring obligations detected yet.</div>}</div><div className="mt-4 flex gap-2"><a href="#finance-manager" className="couture-primary">Add bill record</a><Link href="/calendar" className="couture-secondary">Show Calendar</Link></div></Panel>:null}
   {tab==='subscriptions'?<Panel title="Subscription Intelligence"><div className="grid gap-3 sm:grid-cols-3"><Mini label="Detected subscriptions" value={`${subscriptions.length}`}/><Mini label="Latest monthly-looking total" value={display(subscriptions.reduce((s,e)=>s+Number(e.amount),0))}/><Mini label="Usage data" value="Not connected"/></div><div className="mt-4 space-y-2">{subscriptions.length?subscriptions.map(e=><div key={e.id} className="rounded-[20px] bg-white/45 p-4"><div className="flex justify-between"><span>{e.title}</span><span>{display(Number(e.amount))}</span></div><div className="mt-1 text-[10px] text-[#85827b]">Last recorded {e.entryDate}. Glow cannot label this used/unused without usage data.</div><button onClick={()=>ask(`Review whether I should keep or cancel this recurring expense: ${e.title}. Use only my recorded finance context and ask me about value/usage if needed.`)} className="mt-3 text-xs underline">Review cancellation</button></div>):<div className="text-sm text-[#77756f]">No subscription-like records detected.</div>}</div></Panel>:null}
   {tab==='savings'?<><Panel title="Savings Command Center"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{financeGoals.length?financeGoals.map(g=>{const p=g.targetCents>0?Math.min(100,Math.round(g.currentCents/g.targetCents*100)):0;return <div key={g.id} className="rounded-[26px] border border-white/75 bg-white/45 p-5"><PiggyBank className="h-5 w-5"/><div className="mt-3 text-lg font-medium">{g.name}</div><div className="mt-1 text-xs text-[#77756f]">{display(g.currentCents/100)} of {display(g.targetCents/100)}</div><div className="mt-4 h-24 rounded-[28px] bg-white/55 p-1 flex items-end"><div className="w-full rounded-[24px] bg-[#b7c7ba]/80" style={{height:`${Math.max(4,p)}%`}}/></div><div className="mt-2 text-xs">{p}% protected</div></div>}):<div className="text-sm text-[#77756f]">No Finance savings goals yet.</div>}</div><button onClick={()=>ask('I have extra money. Compare safe, balanced and goal-focused places to put it using my recorded savings goals and current Finance entries.')} className="couture-primary mt-5">I have extra money</button></Panel><Panel title="Savings rules"><p className="text-sm text-[#73716b]">Savings rules here are proposals only. Glow will not silently transfer money.</p><div className="mt-3 flex flex-wrap gap-2">{['Save a fixed amount each paycheck','Save a percentage of variable income','Move leftover category money to savings','Move unused weekly spending to savings'].map(x=><button key={x} onClick={()=>ask(`Help me design this savings rule as a proposal: ${x}. Do not execute transfers.`)} className="couture-secondary">{x}</button>)}</div></Panel></>:null}
   {tab==='goals'?<Panel title="Financial Goals"><div className="grid gap-4 lg:grid-cols-2"><div><div className="text-sm font-medium">Finance goals</div><div className="mt-3 space-y-2">{financeGoals.map(g=><div key={g.id} className="rounded-[20px] bg-white/45 p-4"><div className="flex justify-between"><span>{g.name}</span><span>{g.targetCents?Math.round(g.currentCents/g.targetCents*100):0}%</span></div><div className="mt-1 text-xs text-[#77756f]">Target {display(g.targetCents/100)}{g.targetDate?` · ${String(g.targetDate).slice(0,10)}`:''}</div></div>)}</div></div><div><div className="text-sm font-medium">Life goals available for context</div><div className="mt-3 space-y-2">{lifeGoals.filter(g=>g.status==='active').slice(0,8).map(g=><Link href="/goals" key={g.id} className="block rounded-[20px] bg-white/45 p-4"><div>{g.title}</div><div className="mt-1 text-xs text-[#77756f]">{g.category} · {g.progress}%</div></Link>)}</div><p className="mt-3 text-[10px] text-[#85827b]">Finance goals and Life goals do not yet have an explicit relational link in the database, so this page does not invent one.</p></div></div></Panel>:null}
   {tab==='forecast'?<Panel title="Money Forecast"><div className="flex flex-wrap gap-2">{(['Conservative','Expected','Optimistic'] as ForecastMode[]).map(m=><button key={m} onClick={()=>setMemory(v=>({...v,forecast:m}))} className={`rounded-full px-4 py-2 text-xs ${memory.forecast===m?'bg-[#505650] text-white':'bg-white/55'}`}>{m}</button>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Mini label="Recorded position" value={display(recordedPosition)}/><Mini label="Current spending pace" value={display(projectedSpend)}/><Mini label="Prior monthly avg" value={display(histAvg)}/><Mini label="Forecast confidence" value={historicalMonths.length>=3?'Medium':historicalMonths.length?'Low':'Insufficient data'}/></div><p className="mt-4 text-xs text-[#77756f]">Forecast uses recorded entries and simple pace/history math only. It does not know future paychecks or bills unless they are separately recorded.</p><button onClick={()=>ask(`Build a ${memory.forecast.toLowerCase()} 30-day money forecast. Use my recorded Finance data, state assumptions explicitly, and do not invent income or bills.`)} className="couture-primary mt-4">Build forecast with Glow</button></Panel>:null}
   {tab==='decisions'?<><Panel title="Can I buy this?"><div className="grid gap-3 sm:grid-cols-2"><MoneyInput label="Purchase price" value={memory.purchasePrice} onChange={v=>setMemory(m=>({...m,purchasePrice:v}))}/><label className="rounded-[20px] bg-white/45 p-4"><div className="text-[9px] uppercase tracking-[.18em]">Category</div><select value={memory.purchaseCategory} onChange={e=>setMemory(m=>({...m,purchaseCategory:e.target.value}))} className="mt-3 w-full bg-transparent text-sm outline-none"><option>shopping</option><option>beauty</option><option>food</option><option>transport</option><option>health</option><option>entertainment</option><option>other</option></select></label></div><div className="mt-4 rounded-[24px] bg-white/48 p-5"><div className="text-[10px] uppercase tracking-[.18em]">Purchase impact preview</div><div className="mt-2 text-lg font-medium">{decisionText}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Mini label="Before" value={display(safe)}/><Mini label="Purchase" value={`−${display(memory.purchasePrice)}`}/><Mini label="After" value={display(purchaseAfter)}/></div><p className="mt-3 text-[10px] text-[#87847d]">This is a recorded-data estimate, not an affordability guarantee.</p></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>ask(`Can I buy ${currency(memory.purchasePrice)} in ${memory.purchaseCategory}? Use my recorded safe-to-spend estimate and goals. Preview tradeoffs and do not assume unrecorded bank balances.`)} className="couture-primary">Analyze with Glow</button><button onClick={()=>{const text=`Purchase decision: ${currency(memory.purchasePrice)} ${memory.purchaseCategory} · chose wait.`;setMemory(m=>({...m,decisions:[...m.decisions,text].slice(-30)}));}} className="couture-secondary">Wait until later</button><button onClick={()=>ask(`Turn a ${currency(memory.purchasePrice)} ${memory.purchaseCategory} purchase into a savings plan.`)} className="couture-secondary">Save for it</button></div></Panel><Panel title="Decision Queue"><div className="grid gap-2 sm:grid-cols-2">{['Increase savings?','Cancel a recurring expense?','Make a large purchase?','Adjust spending mode?'].map(x=><button key={x} onClick={()=>ask(`Financial decision: ${x} Compare options using my recorded data.`)} className="rounded-[20px] bg-white/45 p-4 text-left text-sm">{x}<ArrowRight className="mt-2 h-4 w-4"/></button>)}</div></Panel></>:null}
   {tab==='income'?<Panel title="Income Intelligence"><div className="grid gap-3 sm:grid-cols-3"><Mini label="Received this month" value={display(income)}/><Mini label="Income records" value={`${incomeEntries.length}`}/><Mini label="Future income certainty" value="Not modeled yet"/></div><div className="mt-4 space-y-2">{incomeEntries.length?incomeEntries.map(e=><div key={e.id} className="rounded-[20px] bg-white/45 p-4"><div className="flex justify-between"><span>{e.title}</span><span>{display(Number(e.amount))}</span></div><div className="text-[10px] text-[#85827b]">Recorded {e.entryDate}</div></div>):<div className="text-sm text-[#77756f]">No income recorded this month.</div>}</div><p className="mt-4 text-xs text-[#77756f]">Guaranteed / likely / possible income requires dedicated future-income records. Current entries represent money already logged, not promised income.</p><button onClick={()=>ask('Plan my next paycheck. Ask me for expected amount and reliability if those are not recorded, then build balanced, save-aggressively and catch-up allocations.')} className="couture-primary mt-4">Build paycheck plan</button></Panel>:null}
   {tab==='reviews'?<Panel title="Monthly Financial Review"><div className="grid gap-3 sm:grid-cols-4"><Mini label="Income" value={display(income)}/><Mini label="Spent" value={display(spent)}/><Mini label="Saved" value={display(saved)}/><Mini label="Expense / income" value={income?`${Math.round(expenseRatio*100)}%`:'No income baseline'}/></div><div className="mt-5 flex flex-wrap gap-2">{['What felt easy?','What felt tight?','What changed?','What should next month do differently?'].map(x=><button key={x} onClick={()=>ask(`Monthly money review: ${x} Use my recorded entries and help me write a short reflection.`)} className="couture-secondary">{x}</button>)}</div><button onClick={()=>{note('Weekly Money Reset completed: reviewed recorded transactions, recurring costs, safe-to-spend, savings goals and one money decision.');}} className="couture-primary mt-5">Money reset complete</button></Panel>:null}
   {tab==='memory'?<Panel title="Money Memory"><div className="space-y-2">{[...memory.decisions,...memory.notes].length?[...memory.decisions,...memory.notes].slice().reverse().map((n,i)=><div key={`${n}-${i}`} className="rounded-[20px] bg-white/45 p-3 text-sm">{n}</div>):<div className="text-sm text-[#77756f]">No local Money Decision Studio memory yet.</div>}</div><p className="mt-4 text-[10px] text-[#87847d]">This Studio memory is stored in this browser. Finance entries and Finance Goals remain server-backed.</p></Panel>:null}
   {tab==='insights'?<Panel title="Financial Brain"><div className="grid gap-3 sm:grid-cols-2"><Mini label="Largest category" value={byCat[0]?`${byCat[0][0]} · ${display(byCat[0][1])}`:'No spending data'}/><Mini label="Recurring-looking costs" value={`${recurring.length} · ${display(recurringTotal)}`}/><Mini label="Prior expense months" value={`${historicalMonths.length}`}/><Mini label="Active projects" value={`${projects.filter(p=>p.status==='active').length}`}/></div><div className="mt-5 rounded-[24px] border border-white/70 bg-white/45 p-4 text-sm text-[#74726c]">Glow only surfaces patterns supported by recorded history. Project budgeting, bills, subscriptions, refunds, cards and debt need dedicated Finance relations before this Studio can make authoritative cross-system claims about them.</div><div className="mt-4 flex flex-wrap gap-2"><Link href="/finance/brain" className="couture-primary">Open Financial Brain</Link><button onClick={()=>ask('What changed in my finances, why, what is unusual, what should I do, and what decisions are waiting? Use only patterns supported by my recorded data.')} className="couture-secondary">Analyze now</button></div></Panel>:null}
  </div>
 </div>;
}

function Mini({label,value}:{label:string;value:string}){return <div className="rounded-[20px] border border-white/75 bg-white/45 p-4"><div className="text-[9px] uppercase tracking-[.17em] text-[#817e77]">{label}</div><div className="mt-2 text-sm font-medium">{value}</div></div>}
function Row({k,v}:{k:string;v:string}){return <div className="flex justify-between gap-3"><span>{k}</span><span>{v}</span></div>}
function Pool({label,value,strength}:{label:string;value:string;strength:number}){return <div className="rounded-[28px] border border-white/75 bg-white/45 p-5"><WalletCards className="h-5 w-5"/><div className="mt-3 text-xs text-[#79766f]">{label}</div><div className="mt-1 glow-display text-2xl">{value}</div><div className="mt-4 h-24 rounded-[26px] bg-white/55 p-1 flex items-end"><div className="w-full rounded-[22px] bg-[#b9c8c0]/80" style={{height:`${Math.max(5,Math.min(100,strength>0?35+Math.log10(strength+1)*18:5))}%`}}/></div></div>}
function MoneyInput({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="rounded-[20px] bg-white/45 p-4"><div className="text-[9px] uppercase tracking-[.18em]">{label}</div><div className="mt-3 flex items-center gap-2"><span>$</span><input type="number" min="0" step="1" value={value} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))onChange(Math.max(0,n));}} className="w-full bg-transparent text-sm outline-none"/></div></label>}
