'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Brain, CircleHelp, Eye, EyeOff, Orbit, Sparkles } from 'lucide-react';
import type { FinanceEntry } from '@/lib/types';

type FinanceGoal={id:string;name:string;goalType:string;targetCents:number;currentCents:number;targetDate:Date|string|null;notes:string|null};
type Tab='now'|'signals'|'decisions'|'scenarios'|'patterns'|'goals'|'forecast'|'risk'|'opportunities'|'reviews'|'memory';
type Lens='All'|'Cash'|'Spending'|'Savings'|'Goals'|'Future'|'Risk'|'Opportunity';
type Confidence='High'|'Medium'|'Low';
type BrainMemory={privacy:boolean;months:number;lens:Lens;decisions:{date:string;decision:string;why:string;expected:string;actual?:string}[];notes:string[];scenarioAmount:number};
type Signal={title:string;detail:string;kind:'Needs attention'|'Worth reviewing'|'Healthy'|'Watching'|'Opportunity';confidence:Confidence;evidence:string[];action?:string};

const KEY='glow:financial-brain:v1';
const TZ='America/New_York';
const tabs:Tab[]=['now','signals','decisions','scenarios','patterns','goals','forecast','risk','opportunities','reviews','memory'];
const lenses:Lens[]=['All','Cash','Spending','Savings','Goals','Future','Risk','Opportunity'];
const defaults:BrainMemory={privacy:false,months:6,lens:'All',decisions:[],notes:[],scenarioAmount:500};
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const lower=(s?:string|null)=>(s??'').trim().toLowerCase();
const monthKey=(s:string)=>s.slice(0,7);
const isRecurring=(e:FinanceEntry)=>/subscription|rent|mortgage|insurance|phone|internet|utility|utilities|membership|bill/.test(`${lower(e.title)} ${lower(e.category)} ${lower(e.notes)}`);
const monthStart=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1);
const addMonths=(d:Date,n:number)=>new Date(d.getFullYear(),d.getMonth()+n,1);
const fmtMonth=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
function openGlow(prompt:string){window.dispatchEvent(new CustomEvent('glow:open-conversation',{detail:{prompt}}));}
function dateLabel(iso:string){return new Intl.DateTimeFormat('en-US',{timeZone:TZ,month:'short',day:'numeric'}).format(new Date(iso));}
function normalize(v:unknown):BrainMemory{if(!v||typeof v!=='object')return defaults;const x=v as Partial<BrainMemory>;return{privacy:Boolean(x.privacy),months:[3,6,12].includes(x.months??0)?x.months as number:6,lens:lenses.includes(x.lens as Lens)?x.lens as Lens:'All',decisions:Array.isArray(x.decisions)?x.decisions.filter((d):d is BrainMemory['decisions'][number]=>Boolean(d&&typeof d==='object'&&typeof (d as {decision?:unknown}).decision==='string')).slice(-30):[],notes:Array.isArray(x.notes)?x.notes.filter((n):n is string=>typeof n==='string').slice(-50):[],scenarioAmount:typeof x.scenarioAmount==='number'?Math.max(0,Math.min(1000000,x.scenarioAmount)):500};}

export function FinancialBrainObservatory({entries,goals,generatedAt}:{entries:FinanceEntry[];goals:FinanceGoal[];generatedAt:string}){
 const now=useMemo(()=>new Date(generatedAt),[generatedAt]);const currentKey=fmtMonth(monthStart(now));const prevKey=fmtMonth(addMonths(monthStart(now),-1));
 const [tab,setTab]=useState<Tab>('now');const [memory,setMemory]=useState<BrainMemory>(defaults);const [hydrated,setHydrated]=useState(false);const [evidence,setEvidence]=useState<Signal|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setMemory(normalize(JSON.parse(raw)));}catch{}setHydrated(true);},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(KEY,JSON.stringify(memory));}catch{}},[memory,hydrated]);
 const display=(n:number)=>memory.privacy?'••••':money(n);
 const current=entries.filter(e=>monthKey(e.entryDate)===currentKey);const previous=entries.filter(e=>monthKey(e.entryDate)===prevKey);
 const sum=(list:FinanceEntry[],type:FinanceEntry['type'])=>list.filter(e=>e.type===type).reduce((s,e)=>s+Number(e.amount),0);
 const income=sum(current,'income'),spent=sum(current,'expense'),saved=sum(current,'saving'),invested=sum(current,'investment');const position=income-spent-saved-invested;
 const prevIncome=sum(previous,'income'),prevSpent=sum(previous,'expense'),prevSaved=sum(previous,'saving');
 const currentCats=current.filter(e=>e.type==='expense').reduce<Map<string,{amount:number,count:number,max:number}>>((m,e)=>{const b=m.get(e.category)??{amount:0,count:0,max:0};const a=Number(e.amount);b.amount+=a;b.count++;b.max=Math.max(b.max,a);m.set(e.category,b);return m;},new Map());
 const prevCats=previous.filter(e=>e.type==='expense').reduce<Map<string,number>>((m,e)=>m.set(e.category,(m.get(e.category)??0)+Number(e.amount)),new Map());
 const catChanges=[...new Set([...currentCats.keys(),...prevCats.keys()])].map(c=>({category:c,current:currentCats.get(c)?.amount??0,previous:prevCats.get(c)??0,change:(currentCats.get(c)?.amount??0)-(prevCats.get(c)??0)})).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change));
 const historyStart=fmtMonth(addMonths(monthStart(now),-(memory.months-1)));const history=entries.filter(e=>monthKey(e.entryDate)>=historyStart&&monthKey(e.entryDate)<=currentKey);
 const historyMonths=[...new Set(history.map(e=>monthKey(e.entryDate)))].sort();
 const monthlyExpense=historyMonths.map(k=>({key:k,value:sum(history.filter(e=>monthKey(e.entryDate)===k),'expense')}));const monthlySaving=historyMonths.map(k=>({key:k,value:sum(history.filter(e=>monthKey(e.entryDate)===k),'saving') }));
 const expenseAvg=monthlyExpense.length?monthlyExpense.reduce((s,x)=>s+x.value,0)/monthlyExpense.length:0;const savingsAvg=monthlySaving.length?monthlySaving.reduce((s,x)=>s+x.value,0)/monthlySaving.length:0;
 const recurringGroups=entries.filter(e=>e.type==='expense'&&isRecurring(e)).sort((a,b)=>b.entryDate.localeCompare(a.entryDate)).reduce<Map<string,FinanceEntry[]>>((m,e)=>{const k=`${lower(e.title)}|${e.category}`;m.set(k,[...(m.get(k)??[]),e]);return m;},new Map());
 const recurring=[...recurringGroups.values()].map(group=>({latest:group[0],previous:group[1],count:group.length}));const recurringTotal=recurring.reduce((s,g)=>s+Number(g.latest.amount),0);const recurringChanges=recurring.filter(g=>g.previous&&Number(g.latest.amount)!==Number(g.previous.amount));
 const small=current.filter(e=>e.type==='expense'&&Number(e.amount)<15);const smallTotal=small.reduce((s,e)=>s+Number(e.amount),0);
 const savingsProgress=goals.length?Math.round(goals.reduce((s,g)=>s+Math.min(1,g.targetCents>0?g.currentCents/g.targetCents:0),0)/goals.length*100):null;
 const state=position<0?'Needs adjustment':position<250?'Tight':position>1000?'Comfortable':'Stable';
 const spendChange=prevSpent>0?(spent-prevSpent)/prevSpent*100:null;const incomeChange=prevIncome>0?(income-prevIncome)/prevIncome*100:null;const savingChange=prevSaved>0?(saved-prevSaved)/prevSaved*100:null;
 const confidence:Confidence=historyMonths.length>=6?'High':historyMonths.length>=3?'Medium':'Low';
 const largestRise=catChanges.find(x=>x.change>0);const largestDrop=catChanges.find(x=>x.change<0);
 const signals:Signal[]=[
  spendChange===null?{title:'Spending comparison is still forming',detail:'A complete prior-month expense baseline is not available.',kind:'Watching',confidence:'Low',evidence:[`${current.filter(e=>e.type==='expense').length} current-month expense records`,`${previous.filter(e=>e.type==='expense').length} prior-month expense records`]}:{title:`Recorded spending is ${Math.abs(spendChange).toFixed(0)}% ${spendChange>=0?'higher':'lower'} than last month`,detail:largestRise&&spendChange>0?`${largestRise.category} is the largest upward category driver.`:largestDrop&&spendChange<0?`${largestDrop.category} is the largest downward category driver.`:'The change is spread across categories.',kind:spendChange>20?'Needs attention':spendChange>5?'Worth reviewing':spendChange<0?'Healthy':'Watching',confidence:previous.length>=4?'High':'Medium',evidence:[`This month: ${money(spent)}`,`Last month: ${money(prevSpent)}`,`${current.filter(e=>e.type==='expense').length} vs ${previous.filter(e=>e.type==='expense').length} expense records`],action:'Show the purchases'},
  recurringChanges.length?{title:`${recurringChanges.length} recurring-looking cost${recurringChanges.length===1?' has':'s have'} changed`,detail:'The latest recorded amount differs from an earlier matching entry.',kind:'Worth reviewing',confidence:'Medium',evidence:recurringChanges.slice(0,4).map(g=>`${g.latest.title}: ${money(Number(g.previous!.amount))} → ${money(Number(g.latest.amount))}`),action:'Review recurring costs'}:{title:'No recurring price change is detected',detail:recurring.length?'Repeated recurring-looking records are currently stable where a prior match exists.':'Not enough recurring-looking history exists yet.',kind:recurring.length?'Healthy':'Watching',confidence:recurring.length>=3?'Medium':'Low',evidence:[`${recurring.length} recurring-looking pattern${recurring.length===1?'':'s'} detected`]},
  goals.length?{title:`Financial goals average ${savingsProgress}% funded`,detail:'This is the average recorded progress across Finance Goals, not a recommendation about priority.',kind:(savingsProgress??0)>=70?'Healthy':(savingsProgress??0)>=35?'Worth reviewing':'Opportunity',confidence:'High',evidence:[`${goals.length} Finance Goal${goals.length===1?'':'s'} recorded`],action:'Review goals'}:{title:'No Finance Goals are recorded yet',detail:'Goal intelligence becomes stronger after at least one target is saved.',kind:'Opportunity',confidence:'High',evidence:['Finance Goals: 0'],action:'Add a goal'},
  small.length>=6?{title:'Small-spending cluster detected',detail:`${small.length} purchases under $15 total ${money(smallTotal)} this month.`,kind:'Worth reviewing',confidence:'High',evidence:[...small.slice(0,5).map(e=>`${e.entryDate} · ${e.title} · ${money(Number(e.amount))}`)],action:'See transactions'}:{title:'Small purchases are not a major signal right now',detail:`${small.length} recorded purchases under $15 this month.`,kind:'Healthy',confidence:'High',evidence:[`Under-$15 total: ${money(smallTotal)}`]},
 ];
 const ranked=[...signals].sort((a,b)=>rank(a.kind)-rank(b.kind));
 const risk=position<0?'Needs attention':recurringTotal>Math.max(1,income)*.45?'Elevated':spendChange!==null&&spendChange>25?'Moderate':'Low';
 const monthDays=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();const elapsed=Math.max(1,now.getDate());const projectedSpend=spent/elapsed*monthDays;const projectedPosition=income-projectedSpend-saved-invested;
 const scenarioAfter=position-memory.scenarioAmount;
 function ask(text:string){openGlow(`${text} Use only my recorded Glow Finance data. Explain ANSWER, WHY, IMPACT, and NEXT MOVE. Clearly label estimates and unknowns.`);}
 function rememberDecision(decision:string,why:string,expected:string){setMemory(m=>({...m,decisions:[...m.decisions,{date:new Date(generatedAt).toISOString(),decision,why,expected}].slice(-30)}));}
 return <div className="min-h-screen overflow-hidden rounded-[40px] bg-[radial-gradient(circle_at_18%_7%,rgba(146,151,181,.23),transparent_26%),radial-gradient(circle_at_79%_16%,rgba(220,194,144,.13),transparent_25%),radial-gradient(circle_at_53%_88%,rgba(124,157,145,.17),transparent_30%),linear-gradient(155deg,#171922_0%,#20232d_42%,#181b24_100%)] p-3 text-[#f5f2e9] sm:p-6">
  <header className="relative overflow-hidden rounded-[34px] border border-white/10 bg-white/[.055] p-5 shadow-[0_34px_110px_rgba(0,0,0,.28)] backdrop-blur-2xl sm:p-7"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-[#c7b78f]/10 blur-3xl"/><div className="relative flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.34em] text-[#c9c2b3]">Financial Brain · Midnight Observatory</div><h1 className="mt-2 glow-display text-4xl sm:text-5xl">Understand your money, not just the numbers.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#b9bbc4]">What changed, why it changed, how certain Glow is, what it affects, and which decision matters next.</p></div><div className="flex gap-2"><button onClick={()=>setMemory(m=>({...m,privacy:!m.privacy}))} className="rounded-full border border-white/15 bg-white/[.06] px-4 py-2 text-xs">{memory.privacy?<Eye className="mr-2 inline h-4 w-4"/>:<EyeOff className="mr-2 inline h-4 w-4"/>}{memory.privacy?'Show':'Hide'} amounts</button><Link href="/finance" className="rounded-full border border-white/15 bg-white/[.06] px-4 py-2 text-xs">Finance</Link></div></div>
   <div className="relative mt-6 flex gap-2 overflow-x-auto pb-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 rounded-full px-4 py-2 text-[10px] capitalize transition ${tab===t?'bg-[#eee7d6] text-[#252730]':'border border-white/10 bg-white/[.04] text-[#c6c7cc]'}`}>{t}</button>)}</div>
  </header>

  <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-[30px] border border-white/10 bg-white/[.055] p-5 backdrop-blur-xl"><div className="text-[10px] uppercase tracking-[.24em] text-[#c8bea8]">What matters now</div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Recorded position" value={display(position)}/><Metric label="Money state" value={state}/><Metric label="Risk" value={risk}/><Metric label="History lens" value={`${historyMonths.length} month${historyMonths.length===1?'':'s'}`}/></div><div className="mt-5 rounded-[24px] border border-[#d1bd8c]/15 bg-[#d1bd8c]/[.055] p-4"><div className="text-[9px] uppercase tracking-[.2em] text-[#d5c59d]">Top signal</div><div className="mt-2 text-lg">{ranked[0]?.title}</div><div className="mt-1 text-xs text-[#b7b8bf]">{ranked[0]?.detail}</div><button onClick={()=>ranked[0]&&setEvidence(ranked[0])} className="mt-3 text-[11px] text-[#e3d6b5]">Show me why →</button></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>ask('What should I pay attention to financially right now?')} className="rounded-full bg-[#eee7d6] px-4 py-2 text-xs font-medium text-[#242630]">What should I pay attention to?</button>{['What changed?','What looks unusual?','What can I improve?','What can I safely ignore?','What decision should I make?'].map(q=><button key={q} onClick={()=>ask(q)} className="rounded-full border border-white/12 bg-white/[.04] px-4 py-2 text-xs">{q}</button>)}</div></section>
   <section className="rounded-[30px] border border-white/10 bg-white/[.055] p-5 backdrop-blur-xl"><div className="flex items-center gap-2"><Orbit className="h-4 w-4 text-[#d6c79f]"/><div className="text-[10px] uppercase tracking-[.24em] text-[#c8bea8]">Money constellation</div></div><div className="relative mt-4 h-64 overflow-hidden rounded-[26px] border border-white/10 bg-[#11131a]/45"><Constellation center={display(position)} income={income} spending={spent} savings={saved} goals={goals.length} recurring={recurring.length}/></div></section></div>

  <div className="mt-4 rounded-[28px] border border-white/10 bg-white/[.045] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[9px] uppercase tracking-[.22em] text-[#aaa79f]">Analysis controls</div><div className="mt-1 text-xs text-[#c7c8cd]">Change the evidence window and focus without changing any Finance records.</div></div><div className="flex flex-wrap gap-2">{[3,6,12].map(n=><button key={n} onClick={()=>setMemory(m=>({...m,months:n}))} className={`rounded-full px-3 py-1.5 text-[10px] ${memory.months===n?'bg-[#d9d0b8] text-[#23252d]':'border border-white/10'}`}>{n} months</button>)}{lenses.map(l=><button key={l} onClick={()=>setMemory(m=>({...m,lens:l}))} className={`rounded-full px-3 py-1.5 text-[10px] ${memory.lens===l?'bg-[#8fa89c]/55':'border border-white/10'}`}>{l}</button>)}</div></div></div>

  {tab==='now'?<div className="mt-4 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><Panel title="Since last month"><ChangeRow label="Income" current={income} previous={prevIncome} hidden={memory.privacy}/><ChangeRow label="Spending" current={spent} previous={prevSpent} hidden={memory.privacy}/><ChangeRow label="Savings" current={saved} previous={prevSaved} hidden={memory.privacy}/><div className="mt-4 rounded-[20px] bg-white/[.04] p-4 text-sm text-[#c1c2c8]">{spendChange===null?'More prior-month data is needed to explain spending movement confidently.':spendChange<0?'Recorded cash flow improved on the spending side because expenses are lower than last month.':largestRise?`${largestRise.category} is the strongest upward category driver at +${display(largestRise.change)}.`:'Spending changed, but no single category dominates the movement.'}</div></Panel><Panel title="Safe to ignore">{signals.filter(s=>s.kind==='Healthy').length?signals.filter(s=>s.kind==='Healthy').map(s=><SignalCard key={s.title} signal={s} onEvidence={()=>setEvidence(s)}/>):<div className="text-sm text-[#b9bbc2]">No signal can be confidently marked safe to ignore yet. Glow needs more stable history first.</div>}</Panel></div>:null}

  {tab==='signals'?<div className="mt-4 grid gap-4 lg:grid-cols-[1fr_.8fr]"><Panel title="Signal center"><div className="space-y-3">{ranked.map((s,i)=><div key={s.title} className="rounded-[22px] border border-white/8 bg-white/[.04] p-4"><div className="flex items-start gap-3"><span className="mt-0.5 rounded-full border border-white/10 px-2 py-1 text-[9px]">{i+1}</span><div className="flex-1"><div className="text-[9px] uppercase tracking-[.16em] text-[#cbbd9f]">{s.kind} · {s.confidence} confidence</div><div className="mt-1 text-sm font-medium">{s.title}</div><div className="mt-1 text-xs text-[#b7b8bf]">{s.detail}</div><button onClick={()=>setEvidence(s)} className="mt-3 text-[11px] text-[#decfa8]">Show evidence</button></div></div></div>)}</div></Panel><Panel title="Change drivers"><div className="space-y-2">{catChanges.length?catChanges.slice(0,8).map(c=><div key={c.category} className="flex items-center justify-between rounded-[18px] bg-white/[.04] p-3"><div><div className="text-sm capitalize">{c.category}</div><div className="text-[10px] text-[#9fa0a8]">{memory.privacy?'••••':`${money(c.previous)} → ${money(c.current)}`}</div></div><div className={`text-xs ${c.change>0?'text-[#d8b792]':'text-[#a9c6b5]'}`}>{c.change>=0?'+':''}{memory.privacy?'••••':money(c.change)}</div></div>):<div className="text-sm text-[#aaaab1]">No comparable categories yet.</div>}</div><Link href="/finance#finance-manager" className="mt-4 inline-flex items-center gap-1 text-[11px] text-[#decfa8]">Show transactions <ArrowRight className="h-3 w-3"/></Link></Panel></div>:null}

  {tab==='decisions'?<div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="Decision queue"><Decision title="Review recurring costs" detail={`${recurring.length} recurring-looking patterns · ${display(recurringTotal)} latest recorded total`} onDecide={()=>rememberDecision('Review recurring costs','Recurring-looking costs deserve a value check.','Keep only costs that still feel worthwhile.')}/><Decision title="Increase savings?" detail={`Current savings ${display(saved)} · recent ${memory.months}-month average ${display(savingsAvg)}`} onDecide={()=>rememberDecision('Review savings contribution','Compare current savings with recent recorded pace.','Choose a contribution that does not rely on unrecorded income.')}/><Decision title="Delay a purchase?" detail="Use Scenario Lab to compare buy now, wait, and save-first paths." onDecide={()=>setTab('scenarios')}/></Panel><Panel title="Decision memory">{memory.decisions.length?memory.decisions.slice().reverse().slice(0,8).map((d,i)=><div key={`${d.date}-${i}`} className="mb-2 rounded-[18px] bg-white/[.04] p-3"><div className="text-[9px] text-[#a7a5a0]">{dateLabel(d.date)}</div><div className="mt-1 text-sm">{d.decision}</div><div className="mt-1 text-xs text-[#adaeb5]">Why: {d.why}</div><div className="mt-1 text-xs text-[#adaeb5]">Expected: {d.expected}</div></div>):<div className="text-sm text-[#aaaab1]">No Financial Brain decisions saved yet.</div>}</Panel></div>:null}

  {tab==='scenarios'?<div className="mt-4"><Panel title="Scenario Lab"><div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><div><label className="text-[10px] uppercase tracking-[.18em] text-[#b4b0a7]">Scenario amount</label><input type="number" min={0} max={1000000} value={memory.scenarioAmount} onChange={e=>setMemory(m=>({...m,scenarioAmount:Math.max(0,Number(e.target.value)||0)}))} className="mt-2 w-full rounded-[18px] border border-white/10 bg-white/[.06] px-4 py-3 text-lg outline-none"/><p className="mt-2 text-xs text-[#9fa0a8]">Uses the current recorded position only. It is not a live account-balance forecast.</p></div><div className="grid gap-3 md:grid-cols-3"><Path title="Buy now" value={display(scenarioAfter)} detail={scenarioAfter<0?'Recorded position turns negative':'Recorded position remains positive'}/><Path title="Wait" value={display(position)} detail="Recorded position unchanged until a future event is actually recorded"/><Path title="Save first" value={memory.scenarioAmount>0?`${Math.ceil(memory.scenarioAmount/4/25)*25}/wk × ~4`:'$0'} detail="Illustrative four-week save-first path"/></div></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>ask(`What happens if I spend ${money(memory.scenarioAmount)}? Compare buy now, wait, and save-first using my recorded Finance data.`)} className="rounded-full bg-[#eee7d6] px-4 py-2 text-xs text-[#242630]">Ask Financial Brain</button><button onClick={()=>rememberDecision(`Scenario: ${money(memory.scenarioAmount)} purchase`,'Compared buy-now, wait, and save-first paths.','Reassess after the next recorded income or savings change.')} className="rounded-full border border-white/12 px-4 py-2 text-xs">Save scenario decision</button></div></Panel></div>:null}

  {tab==='patterns'?<div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="Category fingerprints">{[...currentCats.entries()].sort((a,b)=>b[1].amount-a[1].amount).slice(0,8).map(([c,b])=>{const hist=history.filter(e=>e.type==='expense'&&e.category===c).map(e=>Number(e.amount));const lo=hist.length?Math.min(...hist):0,hi=hist.length?Math.max(...hist):0;return <div key={c} className="mb-2 rounded-[20px] bg-white/[.04] p-4"><div className="flex justify-between"><div className="capitalize">{c}</div><div>{display(b.amount)}</div></div><div className="mt-2 grid grid-cols-3 gap-2 text-[10px] text-[#a8a9b0]"><span>{b.count} purchase{b.count===1?'':'s'}</span><span>largest {display(b.max)}</span><span>{hist.length} records in lens</span></div><div className="mt-2 text-xs text-[#b9bbc1]">Recorded transaction range: {display(lo)}–{display(hi)}. This is not a monthly budget range.</div></div>})}</Panel><Panel title="Income reliability"><IncomeReliability entries={history.filter(e=>e.type==='income')} hidden={memory.privacy}/><div className="mt-4 text-[10px] leading-4 text-[#92949c]">Reliability labels use recurrence and amount variation in recorded entries only. They do not guarantee future income.</div></Panel></div>:null}

  {tab==='goals'?<div className="mt-4"><Panel title="Savings Goal Brain"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{goals.length?goals.map(g=><GoalCard key={g.id} goal={g} now={now} savingsAvg={savingsAvg} hidden={memory.privacy}/>):<div className="text-sm text-[#aaaab1]">No Finance Goals recorded yet. Use the goal form below the observatory to create one.</div>}</div>{goals.length>1&&<div className="mt-5 rounded-[22px] border border-[#d4b47d]/15 bg-[#d4b47d]/[.05] p-4 text-sm text-[#c7c5bf]">Goal conflict checks remain conservative because Glow does not yet have a dedicated monthly contribution plan per goal. Financial Brain will not invent one.</div>}</Panel></div>:null}

  {tab==='forecast'?<div className="mt-4 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><Panel title="30-day outlook"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Current recorded position" value={display(position)}/><Metric label="Spending pace projection" value={display(projectedSpend)}/><Metric label="Projected recorded position" value={display(projectedPosition)}/></div><div className="mt-4 rounded-[20px] bg-white/[.04] p-4 text-xs leading-5 text-[#b8bac1]">Projection holds current-month recorded income, savings and investments constant and extends only the observed spending pace. It does not include unknown bills, unrecorded income, bank changes or future purchases.</div></Panel><Panel title="What could change this?"><Sensitivity label="Income $200 lower" value={display(projectedPosition-200)}/><Sensitivity label="Spending $100 lower" value={display(projectedPosition+100)}/><Sensitivity label={`Purchase ${money(memory.scenarioAmount)}`} value={display(projectedPosition-memory.scenarioAmount)}/><div className="mt-3 text-[10px] text-[#989aa2]">Confidence: {confidence}. Based on {historyMonths.length} recorded month{historyMonths.length===1?'':'s'} in the current lens.</div></Panel></div>:null}

  {tab==='risk'?<div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="Financial stability map"><Stability label="Cash flow" value={position>=0?'Stable':'Under pressure'} detail={`${display(position)} recorded position`}/><Stability label="Buffer" value={position>1000?'Strong':position>250?'Moderate':'Thin'} detail="Uses recorded position, not bank cash"/><Stability label="Savings" value={saved>=savingsAvg&&saved>0?'Building':saved>0?'Present':'Not recorded'} detail={`${display(saved)} this month`}/><Stability label="Fixed-cost load" value={income>0&&recurringTotal/income>.45?'High':income>0?'Moderate':'Unknown'} detail={`${display(recurringTotal)} latest recurring-looking total`}/></Panel><Panel title="Pressure + unknowns"><div className="rounded-[20px] bg-white/[.04] p-4"><div className="text-[9px] uppercase tracking-[.18em] text-[#d8c291]">Current risk</div><div className="mt-2 text-2xl">{risk}</div></div><ul className="mt-4 space-y-2 text-xs text-[#b8bac0]"><li>• No live account balance is available.</li><li>• No dedicated future-bills table is available.</li><li>• Recurring costs are detected from repeated titles/categories/notes.</li><li>• Future income is not assumed.</li></ul></Panel></div>:null}

  {tab==='opportunities'?<div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="Opportunities"><Opportunity title="Review recurring costs" value={recurring.length?`${display(recurringTotal)} latest total`:'Need more data'} detail="Financial impact only. Usage/value is unknown unless you tell Glow."/><Opportunity title="Capture under-spend if it remains" value={expenseAvg>0&&spent<expenseAvg?display(expenseAvg-spent):'Not currently indicated'} detail="Current spending compared with the selected history lens."/><Opportunity title="Strengthen savings pace" value={savingsAvg?`${display(savingsAvg)} recent avg`:'Need more savings history'} detail="Compare current recorded savings with recent history before changing contributions."/><Opportunity title="Review small-spend cluster" value={small.length>=6?display(smallTotal):'No major cluster'} detail={`${small.length} purchases under $15 this month.`}/></Panel><Panel title="Working well">{signals.filter(s=>s.kind==='Healthy').map(s=><SignalCard key={s.title} signal={s} onEvidence={()=>setEvidence(s)}/>)}{!signals.some(s=>s.kind==='Healthy')&&<div className="text-sm text-[#aaaab1]">Glow does not have enough stable evidence to call out a strength yet.</div>}</Panel></div>:null}

  {tab==='reviews'?<div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="Month story"><div className="text-lg">{new Intl.DateTimeFormat('en-US',{month:'long',timeZone:TZ}).format(now)} money story</div><div className="mt-4 space-y-2 text-sm leading-6 text-[#bec0c6]"><p>{incomeChange===null?'Income comparison needs a prior-month baseline.':`Recorded income is ${Math.abs(incomeChange).toFixed(0)}% ${incomeChange>=0?'higher':'lower'} than last month.`}</p><p>{spendChange===null?'Spending comparison needs more history.':`Recorded spending is ${Math.abs(spendChange).toFixed(0)}% ${spendChange>=0?'higher':'lower'} than last month.`}</p><p>{savingChange===null?'Savings comparison needs a prior-month baseline.':`Recorded savings are ${Math.abs(savingChange).toFixed(0)}% ${savingChange>=0?'higher':'lower'} than last month.`}</p>{largestRise&&<p>Largest upward category movement: <span className="capitalize">{largestRise.category}</span> {display(largestRise.change)}.</p>}{largestDrop&&<p>Largest downward category movement: <span className="capitalize">{largestDrop.category}</span> {display(Math.abs(largestDrop.change))}.</p>}</div></Panel><Panel title="Weekly / monthly ritual"><div className="space-y-2">{['Review new transactions','Review strongest signal','Check recurring-cost changes','Review Finance Goals','Run one scenario','Save one decision or context note'].map((x,i)=><div key={x} className="flex gap-3 rounded-[18px] bg-white/[.04] p-3 text-sm"><span className="text-[#cdbd96]">{i+1}</span><span>{x}</span></div>)}</div><button onClick={()=>setMemory(m=>({...m,notes:[...m.notes,`${dateLabel(generatedAt)} · Completed Financial Brain review`].slice(-50)}))} className="mt-4 rounded-full bg-[#eee7d6] px-4 py-2 text-xs text-[#242630]">Complete review</button></Panel></div>:null}

  {tab==='memory'?<div className="mt-4 grid gap-4 lg:grid-cols-[1fr_.8fr]"><Panel title="Money Memory"><div className="space-y-2">{[...memory.notes,...memory.decisions.map(d=>`${dateLabel(d.date)} · ${d.decision} — ${d.why}`)].length?[...memory.notes,...memory.decisions.map(d=>`${dateLabel(d.date)} · ${d.decision} — ${d.why}`)].slice().reverse().slice(0,20).map((n,i)=><div key={`${n}-${i}`} className="rounded-[18px] bg-white/[.04] p-3 text-sm text-[#c0c1c7]">{n}</div>):<div className="text-sm text-[#aaaab1]">No Financial Brain memory yet.</div>}</div></Panel><Panel title="Add context"><p className="text-xs leading-5 text-[#aaaab1]">Save context such as “started low-spend week” or “unexpected repair.” It stays as Financial Brain local memory and does not alter the server-backed ledger.</p><div className="mt-4 flex flex-wrap gap-2">{['Started low-spend period','Unexpected expense happened','A savings goal became priority','Delayed a purchase','Income situation changed'].map(x=><button key={x} onClick={()=>setMemory(m=>({...m,notes:[...m.notes,`${dateLabel(generatedAt)} · ${x}`].slice(-50)}))} className="rounded-full border border-white/12 px-3 py-2 text-xs">{x}</button>)}</div></Panel></div>:null}

  <section className="mt-4 rounded-[30px] border border-white/10 bg-white/[.055] p-5"><div className="flex items-center gap-2"><Brain className="h-4 w-4 text-[#d5c49a]"/><div className="text-[10px] uppercase tracking-[.22em] text-[#c8bea8]">Ask Financial Brain</div></div><div className="mt-4 flex flex-wrap gap-2">{['Why is this month tighter?','What can I cut without affecting my priorities?','Which goal should I fund first?','What happens if I spend $500?','How do I make next month easier?'].map(q=><button key={q} onClick={()=>ask(q)} className="rounded-full border border-white/12 bg-white/[.04] px-4 py-2 text-xs">{q}</button>)}</div><p className="mt-3 text-[10px] text-[#8f9199]">Financial Brain asks the universal Glow conversation so follow-up questions can continue in the same assistant experience.</p></section>

  {evidence?<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45 p-3 sm:items-center" onMouseDown={e=>{if(e.target===e.currentTarget)setEvidence(null)}}><div role="dialog" aria-modal="true" aria-label="Financial evidence" className="w-full max-w-xl rounded-[30px] border border-white/15 bg-[#20232d] p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.18em] text-[#cdbd98]">Evidence · {evidence.confidence} confidence</div><div className="mt-2 text-xl">{evidence.title}</div><div className="mt-1 text-sm text-[#b4b5bc]">{evidence.detail}</div></div><button onClick={()=>setEvidence(null)} className="rounded-full border border-white/10 px-3 py-1.5 text-xs">Close</button></div><div className="mt-5 space-y-2">{evidence.evidence.map((x,i)=><div key={`${x}-${i}`} className="rounded-[18px] bg-white/[.045] p-3 text-sm text-[#c7c8cd]">{x}</div>)}</div><div className="mt-4 flex gap-2"><Link href="/finance#finance-manager" className="rounded-full bg-[#eee7d6] px-4 py-2 text-xs text-[#242630]">See Finance records</Link><button onClick={()=>ask(`Explain this Financial Brain signal: ${evidence.title}. Evidence: ${evidence.evidence.join('; ')}`)} className="rounded-full border border-white/12 px-4 py-2 text-xs">Ask about this</button></div></div></div>:null}
 </div>;
}

function rank(k:Signal['kind']){return {'Needs attention':0,'Worth reviewing':1,'Opportunity':2,'Watching':3,'Healthy':4}[k]}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[30px] border border-white/10 bg-white/[.055] p-5 backdrop-blur-xl"><div className="mb-4 text-[10px] uppercase tracking-[.22em] text-[#c8bea8]">{title}</div>{children}</section>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-[20px] border border-white/8 bg-white/[.045] p-4"><div className="text-[9px] uppercase tracking-[.16em] text-[#9fa0a8]">{label}</div><div className="mt-2 text-lg font-medium">{value}</div></div>}
function SignalCard({signal,onEvidence}:{signal:Signal;onEvidence:()=>void}){return <div className="mb-2 rounded-[20px] bg-white/[.04] p-4"><div className="text-[9px] uppercase tracking-[.16em] text-[#c5b790]">{signal.kind} · {signal.confidence}</div><div className="mt-1 text-sm">{signal.title}</div><div className="mt-1 text-xs text-[#adaeb5]">{signal.detail}</div><button onClick={onEvidence} className="mt-2 text-[10px] text-[#decfa8]">Show why</button></div>}
function ChangeRow({label,current,previous,hidden}:{label:string;current:number;previous:number;hidden:boolean}){const d=current-previous;return <div className="mb-2 grid grid-cols-[1fr_auto_auto] items-center gap-3 rounded-[18px] bg-white/[.04] p-3"><span className="text-sm">{label}</span><span className="text-xs text-[#aaaab1]">{hidden?'••••':money(previous)} → {hidden?'••••':money(current)}</span><span className={`text-xs ${d>=0?'text-[#d6b78f]':'text-[#a7c2b2]'}`}>{d>=0?'+':''}{hidden?'••••':money(d)}</span></div>}
function Decision({title,detail,onDecide}:{title:string;detail:string;onDecide:()=>void}){return <div className="mb-3 rounded-[20px] bg-white/[.04] p-4"><div className="text-sm font-medium">{title}</div><div className="mt-1 text-xs text-[#adaeb5]">{detail}</div><button onClick={onDecide} className="mt-3 rounded-full border border-white/12 px-3 py-1.5 text-[10px]">Decide now</button></div>}
function Path({title,value,detail}:{title:string;value:string;detail:string}){return <div className="relative overflow-hidden rounded-[24px] border border-white/10 bg-white/[.045] p-4"><div className="absolute left-0 top-0 h-full w-1 bg-gradient-to-b from-[#d1bc8b]/60 to-[#8eaa9c]/20"/><div className="text-[9px] uppercase tracking-[.18em] text-[#c9b98e]">{title}</div><div className="mt-3 text-2xl">{value}</div><div className="mt-2 text-xs leading-5 text-[#aaaab1]">{detail}</div></div>}
function Sensitivity({label,value}:{label:string;value:string}){return <div className="mb-2 flex items-center justify-between rounded-[18px] bg-white/[.04] p-3"><span className="text-xs text-[#b5b6bd]">{label}</span><span className="text-sm">{value}</span></div>}
function Stability({label,value,detail}:{label:string;value:string;detail:string}){return <div className="mb-2 grid grid-cols-[1fr_auto] gap-3 rounded-[20px] bg-white/[.04] p-4"><div><div className="text-[9px] uppercase tracking-[.16em] text-[#9fa0a8]">{label}</div><div className="mt-1 text-xs text-[#adaeb5]">{detail}</div></div><div className="text-sm">{value}</div></div>}
function Opportunity({title,value,detail}:{title:string;value:string;detail:string}){return <div className="mb-2 rounded-[20px] border border-[#91ad9e]/12 bg-[#91ad9e]/[.055] p-4"><div className="text-[9px] uppercase tracking-[.16em] text-[#a8c0b3]">Opportunity</div><div className="mt-1 text-sm">{title}</div><div className="mt-2 text-lg">{value}</div><div className="mt-1 text-xs text-[#aeb0b6]">{detail}</div></div>}
function GoalCard({goal,now,savingsAvg,hidden}:{goal:FinanceGoal;now:Date;savingsAvg:number;hidden:boolean}){const target=goal.targetCents/100,current=goal.currentCents/100,remaining=Math.max(0,target-current),pct=target>0?Math.min(100,Math.round(current/target*100)):0;const date=goal.targetDate?new Date(goal.targetDate):null;const months=date?Math.max(1,(date.getFullYear()-now.getFullYear())*12+date.getMonth()-now.getMonth()):null;const required=months?remaining/months:null;return <div className="rounded-[22px] bg-white/[.04] p-4"><div className="flex justify-between gap-3"><div className="font-medium">{goal.name}</div><div>{pct}%</div></div><div className="mt-2 text-xs text-[#adaeb5]">{hidden?'••••':money(current)} of {hidden?'••••':money(target)}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#9cb5a8]" style={{width:`${pct}%`}}/></div><div className="mt-3 space-y-1 text-[10px] text-[#9fa0a8]">{required!==null&&<div>Required average pace: {hidden?'••••':money(required)}/month</div>}<div>Recent recorded savings average: {hidden?'••••':money(savingsAvg)}/month</div>{required!==null&&<div>{required>savingsAvg&&savingsAvg>0?`Gap: ${hidden?'••••':money(required-savingsAvg)}/month`:'Current recorded savings pace does not show a gap.'}</div>}</div></div>}
function IncomeReliability({entries,hidden}:{entries:FinanceEntry[];hidden:boolean}){const groups=[...entries.reduce<Map<string,FinanceEntry[]>>((m,e)=>{const k=lower(e.title)||'income';m.set(k,[...(m.get(k)??[]),e]);return m;},new Map()).entries()];if(!groups.length)return <div className="text-sm text-[#aaaab1]">No income history in this lens.</div>;return <div className="space-y-2">{groups.slice(0,8).map(([k,list])=>{const vals=list.map(e=>Number(e.amount));const avg=vals.reduce((s,v)=>s+v,0)/vals.length;const min=Math.min(...vals),max=Math.max(...vals);const variation=avg>0?(max-min)/avg:1;const label=list.length>=4&&variation<.15?'Consistent':list.length>=3?'Variable':list.length===2?'Occasional':'Unknown';const conf:list[number] extends never?never:Confidence=list.length>=5?'High':list.length>=3?'Medium':'Low';return <div key={k} className="rounded-[20px] bg-white/[.04] p-4"><div className="flex justify-between"><div className="capitalize">{list[0].title}</div><div className="text-xs">{label}</div></div><div className="mt-2 text-[10px] text-[#a7a8af]">Average {hidden?'••••':money(avg)} · range {hidden?'••••':`${money(min)}–${money(max)}`} · {list.length} records · {conf} confidence</div></div>})}</div>}
function Constellation({center,income,spending,savings,goals,recurring}:{center:string;income:number;spending:number;savings:number;goals:number;recurring:number}){const nodes=[['Income',income,18,22],['Spending',spending,76,24],['Savings',savings,20,72],['Goals',goals*100,74,73],['Recurring',recurring*100,50,12]] as const;return <div className="relative h-full w-full"><div className="absolute left-1/2 top-1/2 z-10 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#d5c69e]/25 bg-[#d5c69e]/10 px-5 py-4 text-center shadow-[0_0_50px_rgba(211,196,154,.12)]"><div className="text-[8px] uppercase tracking-[.18em] text-[#c9b98d]">Current position</div><div className="mt-1 text-sm">{center}</div></div>{nodes.map(([name,value,x,y])=><div key={name} className="absolute z-10 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/10 bg-white/[.055] px-3 py-2 text-center" style={{left:`${x}%`,top:`${y}%`,boxShadow:`0 0 ${Math.min(42,14+Math.log10(Math.max(1,Number(value)))*7)}px rgba(161,187,177,.12)`}}><div className="text-[8px] text-[#aeb0b8]">{name}</div></div>)}<svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none">{nodes.map(([name,,x,y])=><line key={name} x1="50" y1="50" x2={x} y2={y} stroke="rgba(210,201,177,.16)" strokeWidth=".45"/>)}</svg></div>}
