'use client';

import { usePathname, useRouter } from 'next/navigation';
import { AlertTriangle, CheckCircle2, Mic, Paperclip, Search, Send, ShieldCheck, Sparkles, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

type RecognitionEvent={results:ArrayLike<{0:{transcript:string}}>};
type RecognitionError={error:string};
type Recognition={continuous:boolean;interimResults:boolean;lang:string;start():void;stop():void;onresult:((event:RecognitionEvent)=>void)|null;onend:(()=>void)|null;onerror:((event:RecognitionError)=>void)|null};
type RecognitionCtor=new()=>Recognition;
type Risk='low'|'medium'|'high';

const NAV:Record<string,string>={today:'/today',dashboard:'/dashboard',home:'/dashboard',tasks:'/tasks',planner:'/planning',calendar:'/calendar',planning:'/planning',routines:'/routines',habits:'/habits',fitness:'/fitness',wellness:'/wellness',food:'/food',nutrition:'/food',beauty:'/beauty','beauty lab':'/beauty/lab',hair:'/hair',finance:'/finance','financial brain':'/finance/brain',goals:'/goals',projects:'/projects',notes:'/notes',settings:'/settings',world:'/world',glow:'/brain'};

function commandRisk(text:string):Risk{const value=text.toLowerCase();if(/delete|remove all|erase|cancel appointment|cancel event|clear all|archive all|send email|purchase|pay bill|transfer|external account/.test(value))return'high';if(/move|reschedule|change|edit|update|replace|bulk|everything|all unfinished|budget|financial/.test(value))return'medium';return'low';}
function navigationTarget(text:string){const value=text.toLowerCase().replace(/[^a-z ]/g,' ').trim();const exact=Object.entries(NAV).sort((a,b)=>b[0].length-a[0].length).find(([label])=>value===label);if(exact)return exact[1];if(!/^(open|go to|show me|take me to|navigate to)\b/.test(value))return null;return Object.entries(NAV).sort((a,b)=>b[0].length-a[0].length).find(([label])=>value.includes(label))?.[1]??null;}

export function GlowVoiceCommand(){
  const pathname=usePathname();const router=useRouter();const recognitionRef=useRef<Recognition|null>(null);const fileRef=useRef<HTMLInputElement>(null);
  const [open,setOpen]=useState(false);const [listening,setListening]=useState(false);const [text,setText]=useState('');const [status,setStatus]=useState('');const [pending,setPending]=useState(false);const risk=commandRisk(text);

  useEffect(()=>{const openGlow=()=>setOpen(true);const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setOpen(true);}if(event.key==='Escape')setOpen(false);};document.addEventListener('glow:voice-open',openGlow);document.addEventListener('keydown',key);return()=>{document.removeEventListener('glow:voice-open',openGlow);document.removeEventListener('keydown',key);};},[]);

  function startListening(){setStatus('');const browser=window as Window&{SpeechRecognition?:RecognitionCtor;webkitSpeechRecognition?:RecognitionCtor};const Ctor=browser.SpeechRecognition??browser.webkitSpeechRecognition;if(!Ctor){setStatus('Voice recognition is not available here. Type your command instead.');return;}const recognition=new Ctor();recognition.continuous=false;recognition.interimResults=false;recognition.lang='en-US';recognition.onresult=(event)=>{setText(Array.from(event.results).map(result=>result[0]?.transcript??'').join(' ').trim());setListening(false);};recognition.onend=()=>setListening(false);recognition.onerror=(event)=>{setListening(false);setStatus(`Glow could not hear that clearly (${event.error}).`);};recognitionRef.current=recognition;setListening(true);recognition.start();}
  function stopListening(){recognitionRef.current?.stop();setListening(false);}

  async function runCommand(){const command=text.trim();if(!command||pending)return;const lower=command.toLowerCase();const destination=navigationTarget(command);if(destination){router.push(destination);setOpen(false);setText('');return;}if(/^(new task|add a task|add task)$/.test(lower)){document.dispatchEvent(new CustomEvent('glow:quick-add',{detail:{module:'task'}}));setOpen(false);return;}if(/^(new event|add event|add an event)$/.test(lower)){document.dispatchEvent(new CustomEvent('glow:quick-add',{detail:{module:'event'}}));setOpen(false);return;}if(/plan tomorrow/.test(lower)){router.push('/planning?view=tomorrow');setOpen(false);return;}if(/search/.test(lower)&&/doctor|note|notes/.test(lower)){router.push(`/brain?mode=search&q=${encodeURIComponent(command)}`);setOpen(false);return;}setPending(true);setStatus('Glow is routing this to the right part of your life…');try{const response=await fetch('/api/voice/command',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({text:command,sourceRoute:pathname,risk})});const payload=await response.json() as {ok?:boolean;message?:string};if(!response.ok||!payload.ok)throw new Error(payload.message||'Glow could not run that command.');setStatus(payload.message||'Done.');setText('');router.refresh();}catch(error){setStatus(error instanceof Error?error.message:'Glow could not run that command.');}finally{setPending(false);}}

  if(!open)return null;
  return <div className="fixed inset-0 z-[110] flex items-start justify-center bg-black/20 px-3 pt-[10vh] backdrop-blur-[2px]" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false);}}>
    <section className="w-full max-w-[640px] overflow-hidden rounded-[22px] border border-[#E7E7E7] bg-white shadow-[0_28px_90px_rgba(0,0,0,.18)]">
      <div className="flex items-start justify-between border-b border-[#EFEFEF] px-5 py-5 sm:px-6"><div><div className="flex items-center gap-2 text-[#B86F7D]"><Sparkles size={14}/><p className="text-[11px] font-semibold uppercase tracking-[.16em]">Glow</p></div><h2 className="glow-display mt-2 text-[28px] leading-tight text-[#1C1C1E]">What do you want to do?</h2><p className="mt-2 text-[13px] leading-5 text-[#6E6E73]">Type, speak, search, create, move, log, plan or ask. Glow uses the room you are in as context.</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close Glow" className="rounded-full p-2 text-[#77777B] hover:bg-[#F5F5F5]"><X size={18}/></button></div>
      <div className="space-y-4 p-5 sm:p-6">
        <div className="relative"><Search className="absolute left-4 top-4 text-[#9A9A9F]" size={17}/><textarea autoFocus value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void runCommand();}}} rows={3} placeholder="Add a task, open Hair, plan tomorrow, search doctor notes…" className="w-full resize-none rounded-[16px] border border-[#E4E4E4] bg-[#FAFAFA] py-3.5 pl-11 pr-4 text-[14px] leading-6 text-[#1C1C1E] outline-none focus:border-[#B86F7D]"/></div>
        <div className="flex flex-wrap gap-2"><button type="button" onClick={listening?stopListening:startListening} className="glow-command-chip"><Mic size={14}/>{listening?'Listening…':'Speak'}</button><button type="button" onClick={()=>fileRef.current?.click()} className="glow-command-chip"><Paperclip size={14}/>Attach</button><button type="button" onClick={()=>document.dispatchEvent(new CustomEvent('glow:quick-add'))} className="glow-command-chip">+ Create</button><span className="ml-auto hidden self-center text-[11px] text-[#A0A0A5] sm:inline">⌘K / Ctrl-K</span></div>
        <input ref={fileRef} type="file" className="sr-only" onChange={event=>{const file=event.target.files?.[0];if(file)setStatus(`${file.name} is ready to use with this Glow command.`);}}/>
        {text?<div className={`flex items-start gap-2 rounded-[12px] px-3 py-2.5 text-[12px] leading-5 ${risk==='high'?'bg-amber-50 text-amber-900':risk==='medium'?'bg-[#FAF4F0] text-[#705A4C]':'bg-[#F4F8F4] text-[#436047]'}`}>{risk==='high'?<AlertTriangle size={14}/>:risk==='medium'?<ShieldCheck size={14}/>:<CheckCircle2 size={14}/>}<span>{risk==='high'?<><b>Confirmation required.</b> Glow will ask before destructive or external changes.</>:risk==='medium'?<><b>Review first.</b> Glow will preserve context before larger changes.</>:<><b>Ready.</b> This can be routed safely.</>}</span></div>:null}
        {status?<div role="status" className="rounded-[12px] bg-[#F7F7F7] px-3 py-2.5 text-[12px] leading-5 text-[#5F5F64]">{status}</div>:null}
        <button type="button" disabled={!text.trim()||pending} onClick={()=>void runCommand()} className="inline-flex h-12 w-full items-center justify-center gap-2 rounded-[12px] bg-[#1C1C1E] px-4 text-[13px] font-semibold text-white disabled:opacity-40"><Send size={14}/>{pending?'Working…':risk==='high'?'Review action':'Do it'}</button>
        <div className="grid gap-2 sm:grid-cols-3">{['Add a task','Plan tomorrow','Log my water','Open Hair','Move my workout','Search doctor notes'].map(example=><button type="button" key={example} onClick={()=>setText(example)} className="rounded-[11px] border border-[#ECECEC] bg-white px-3 py-2.5 text-left text-[12px] text-[#59595E] hover:bg-[#FAFAFA]">{example}</button>)}</div>
      </div>
    </section>
  </div>;
}
