'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Home, Leaf, Network, Search, Sparkles, Target, Shield, Plus, Minus, Check, Clock3, AlertTriangle, Sunrise, Moon, Zap } from 'lucide-react';
import type { PlanPlanningItem, PlanStudioEvent } from './plan-planning-studio-reference-v4';
import styles from './horizon-studio-reference.module.css';

type Horizon='quarter'|'month'|'week'|'day';
const HORIZONS: {id:Horizon;label:string}[]=[{id:'quarter',label:'Quarter'},{id:'month',label:'Month'},{id:'week',label:'Week'},{id:'day',label:'Day'}];
const copy={
 day:{date:'Wednesday, Sep 16',center:'Today',sub:'Wednesday · September 16',feel:'Focused, calm, and in control. Make meaningful progress and enjoy the in-betweens.',focus:'Finish product copy with clarity and quality',priority:'Priority mode · Top 3',protect:'My energy, focused blocks, and an early wind down',inbox:'Day Inbox',capacity:'28%',used:'2.5 of 9 hrs free',commit:'Preview & Commit Day'},
 week:{date:'Sep 14–20, 2026',center:'This Week',sub:'September 14–20',feel:'Focused, energized, and balanced. Making meaningful progress without burnout.',focus:'Launch v1.0 with quality while staying healthy',priority:'Priority mode · Top 3',protect:'Deep work, workouts, family time, and sleep.',inbox:'Weekly Task Bank',capacity:'68%',used:'24 of 75 hrs used',commit:'Preview & Commit Week'},
 month:{date:'September 2026',center:'September',sub:'2026',feel:'Focused, grounded, and proud. Making steady progress while enjoying the season.',focus:'Launch the new product with clarity and balance.',priority:'More of · Deep work, movement, time outdoors, quality time',protect:'My health, creative time, and time with people I love',inbox:'Planning Inbox',capacity:'42%',used:'70 of 120 hrs used',commit:'Preview & Commit Plan'},
 quarter:{date:'Q4 · Oct–Dec 2026',center:'Q4',sub:'October–December 2026',feel:'Meaningful progress, steady energy, more presence with people I love, and space to recover.',focus:'Sustainable growth across work, health, and relationships.',priority:'Priority mode · Ranked 6',protect:'My health, recovery time, and creative energy.',inbox:'Quarter Backlog',capacity:'68%',used:'270 of 400 hrs used',commit:'Preview & Commit Quarter'}
} as const;

const inbox={day:['Reply to partnership email','Review design feedback','Plan weekend trip','Order anniversary gift','Read new research article'],week:['Draft launch email','Update investor deck','Plan fall trip','Organize photos','Refresh portfolio'],month:['Look into offsite venue options','Send Q4 partnership draft','Book fall family trip','Explore new design tools'],quarter:['Explore spring retreat options','Upgrade home workspace','Plan a weekend with friends','Research new camera gear','Build personal website v2']};

function Orb({tone,title,subtitle,items}:{tone:string;title:string;subtitle:string;items:string[]}){return <article className={`${styles.orb} ${styles[tone]}`}><Target/><h2>{title}</h2><p>{subtitle}</p>{items.map((x,i)=><div className={styles.orbItem} key={x}><span className={i===0?styles.done:''}>{i===0?<Check/>:null}</span>{x}</div>)}<button aria-label={`Open ${title}`}><ChevronRight/></button></article>}

export function HorizonStudioReference({events,planning}:{events:PlanStudioEvent[];planning:PlanPlanningItem[]}){
 const [horizon,setHorizon]=useState<Horizon>('month'); const c=copy[horizon];
 const energy=[['Mental',horizon==='day'?76:74],['Physical',68],['Creative',horizon==='month'?85:72],['Social',60]];
 const liveItems=useMemo(()=>planning.slice(0,4).map(x=>x.title),[planning]);
 const openGlow=(intent:string)=>document.dispatchEvent(new CustomEvent('glow:open',{detail:{context:{room:'Plan · Horizon Studio',horizon,intent}}}));
 return <main className={styles.root}><section className={styles.shell}>
  <aside className={styles.nav}><b>Glow OS</b><nav><Link href="/today"><Home/>Today</Link><Link className={styles.active} href="/planning"><span className={styles.pearl}/>Plan</Link><Link href="/life"><Leaf/>Life</Link><Link href="/brain"><Network/>Brain</Link><Link href="/create"><Sparkles/>Create</Link></nav><div className={styles.navFoot}><span className={styles.pearl}/><p>A calmer<br/>tomorrow<br/>together.</p></div></aside>
  <header className={styles.header}><div><h1>PLAN · HORIZON STUDIO</h1><p>Turn intention into a life well lived.</p></div><button className={styles.date}><CalendarDays/>{c.date}<ChevronLeft/><ChevronRight/></button><div className={styles.energy}><i/> <b>Steady</b><small>Your energy today</small></div><button className={styles.ask} onClick={()=>openGlow('Help me shape this horizon')}><Search/>Ask Glow…</button><span className={styles.pearl}/></header>
  <aside className={styles.direction}><h2>Direction</h2><p>Set the tone. Everything flows from here.</p><Card title={`How I want this ${horizon} to feel`} text={c.feel}/><Card icon={<Target/>} title={horizon==='quarter'?'Quarter focus':'Main focus'} text={c.focus}/><Card icon={<Plus/>} title={c.priority} text={horizon==='month'?'Deep work, movement, time outdoors, quality time':'Focus on what matters most.'}/><Card icon={<Shield/>} title="Protect" text={c.protect}/><div className={styles.inbox}><h3>{c.inbox}<span>{inbox[horizon].length}</span></h3>{inbox[horizon].map(x=><button key={x}><i/>{x}<ChevronRight/></button>)}<button><Plus/>Add to {horizon==='week'?'task bank':horizon==='quarter'?'backlog':'inbox'}</button></div></aside>
  <section className={styles.center}><div className={styles.tabs}>{HORIZONS.map(x=><button key={x.id} className={horizon===x.id?styles.selected:''} onClick={()=>setHorizon(x.id)}>{x.label}</button>)}</div><div className={styles.landscape}><Orb tone="green" title={horizon==='week'?'Driver 1':'Must Move'} subtitle={horizon==='week'?'Ship product v1.0':horizon==='quarter'?'Launch v2 and reach more people.':`Key outcomes ${horizon==='day'?'today':`this ${horizon}`}`} items={horizon==='day'?['Finish product copy','Workout','Tidy inbox']:['Launch with clarity','Grow with intention','Finalize next step']}/><article className={styles.core}><span className={styles.leaf}>❧</span><h2>{c.center}</h2><p>{c.sub}</p><small>Focus · Progress · Balance</small></article><Orb tone="purple" title={horizon==='week'?'Driver 2':'Build'} subtitle={horizon==='week'?'Wellness & energy':'Invest in long-term growth'} items={['Systemize what works','Review progress','Set up next step']}/><Orb tone="peach" title={horizon==='week'?'Driver 3':'Experience'} subtitle="Make it meaningful" items={['Quality time','Outdoor moment','Rest and reflect']}/><span className={`${styles.drop} ${styles.d1}`}/><span className={`${styles.drop} ${styles.d2}`}/><span className={`${styles.drop} ${styles.d3}`}/></div><Timeline horizon={horizon} events={events} liveItems={liveItems}/></section>
  <aside className={styles.fit}><h2>Capacity & Fit</h2><p>Align your time, energy and commitments.</p><div className={styles.gauge}><b>{c.capacity}</b><span>capacity remaining</span><small>{c.used}</small></div><h3>Energy {horizon==='day'?'today':horizon==='quarter'?'forecast (Q4)':`this ${horizon}`}</h3>{energy.map(([label,value])=><div className={styles.meter} key={label as string}><span>{label}</span><i><b style={{width:`${value}%`}}/></i><em>{value}%</em></div>)}<div className={styles.summary}><p><CalendarDays/>Fixed commitments <b>{Math.max(6,events.length)} items</b></p><p><Clock3/>Open space <b>{c.capacity}</b></p><p className={styles.warning}><AlertTriangle/>1 conflict <b>Review schedule fit</b></p></div><h3>✧ Glow proposals <span>3</span></h3>{['Move a flexible task','Protect a deep work block','Add a transition buffer'].map(x=><button className={styles.proposal} key={x}><span>{x}<small>Thoughtful adjustment for a smoother {horizon}.</small></span><b>Apply</b></button>)}</aside>
  <footer className={styles.handoff}><div><Sunrise/><b>{horizon==='day'?'First Move':horizon==='week'?"Monday’s First Move":horizon==='month'?'First Week':'First Month'}</b><small>Start intentionally. A clear first step creates momentum.</small></div><div><b>Top 3 priorities</b><ol><li>Meaningful progress <em>High</em></li><li>Protect wellness <em>High</em></li><li>Quality time <em>Medium</em></li></ol></div><div><Zap/><b>Start here</b><small>Your next action</small><button>Finalize the next meaningful step <span>Start</span></button></div><div className={styles.commit}><button onClick={()=>openGlow(`Preview and commit my ${horizon} plan`)}>{c.commit}<ChevronRight/></button><small>This plan will sync across all horizons.</small><span>✓ All changes saved</span></div></footer>
 </section></main>
}

function Card({title,text,icon}:{title:string;text:string;icon?:React.ReactNode}){return <button className={styles.card}>{icon}<span><b>{title}</b><small>{text}</small></span><ChevronRight/></button>}

function Timeline({horizon,events,liveItems}:{horizon:Horizon;events:PlanStudioEvent[];liveItems:string[]}){const columns=horizon==='day'?['Morning · 5–10','Between · 10–4','Evening · 4–8:30','Night · 8:30–11']:horizon==='week'?['Mon 14','Tue 15','Wed 16','Thu 17','Fri 18','Sat 19','Sun 20']:horizon==='month'?['Week 1','Week 2','Week 3','Week 4']:['October · Foundation','November · Build','December · Complete & Reflect'];const fallback=['Deep work','Workout','Planning reset','Quality time'];return <section className={styles.timeline}><header><div><CalendarDays/><b>{horizon==='day'?"Today’s Plan":horizon==='week'?'Week Map':horizon==='month'?'September · 4-Week Plan':'12-Week Roadmap'}</b><small>{horizon==='week'?'Seven days. A balanced, meaningful week.':'A clear rhythm for meaningful progress.'}</small></div><nav><button>Tasks</button><button>Projects</button><button>Appointments</button><button>Routines</button></nav></header><div className={styles.columns}>{columns.map((label,i)=><article key={label}><h3>{label}</h3><small>{horizon==='week'?['Foundation','Fitness','Wellness','Creative','Beauty & Planning','Recovery','Reset'][i]:''}</small>{[0,1,2,3].map((_,j)=>{const event=events[(i+j)%Math.max(1,events.length)];const text=event?.title||liveItems[(i+j)%Math.max(1,liveItems.length)]||fallback[j];return <p key={`${label}-${j}`}><i className={j===0?styles.dotDone:''}/>{text}</p>})}<button><Plus/>Add item</button></article>)}</div></section>}
