import Link from 'next/link';
import {redirect} from 'next/navigation';
import {auth} from '@/auth';
import {AppShell} from '@/components/app-shell';
import {SpecialUpgradeGrid} from '@/components/special-upgrade-grid';
import {getProjectsByUser} from '@/lib/data/user-scope';
import {getNotesByUser} from '@/lib/data/notes';
export const dynamic='force-dynamic';
export default async function CreativeStudioPage(){const s=await auth();if(!s?.user?.id)redirect('/sign-in');const [projects,notes]=await Promise.all([getProjectsByUser(s.user.id),getNotesByUser(s.user.id)]);const active=projects.filter(p=>p.status==='active').slice(0,6);return <AppShell><div className="space-y-6"><header className="grid gap-5 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="glow-eyebrow">Creative Studio</p><h1 className="glow-display mt-2 text-4xl sm:text-5xl">Make ideas tangible.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#83756D]">A visual layer for the same real Projects system: direction, references, ideas, creative decisions and presentation-ready work.</p></div><div className="rounded-[24px] border border-[#EDE1DC] bg-[#FFF8F6] p-5"><p className="text-[10px] uppercase tracking-[.14em] text-[#B66D77]">Studio now</p><p className="glow-display mt-2 text-3xl">{active.length}</p><p className="text-xs text-[#8B7C74]">active creative project{active.length===1?'':'s'} · {notes.length} notes available</p></div></header><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{active.length?active.map(project=><Link key={project.id} href="/projects" className="rounded-[24px] border border-[#EDE1DC] bg-white p-5 hover:bg-[#FFF9F7]"><p className="text-[10px] uppercase tracking-[.12em] text-[#B66D77]">{project.area}</p><h2 className="glow-display mt-2 text-2xl">{project.title}</h2><p className="mt-2 text-xs text-[#8B7C74]">{project.nextAction??'Open the project desk to define the next creative move.'}</p><div className="mt-4 h-1.5 rounded-full bg-[#F3E9E5]"><div className="h-full rounded-full bg-[#C9727E]" style={{width:`${Math.max(0,Math.min(100,project.progress))}%`}}/></div></Link>):<div className="rounded-[24px] border border-[#EDE1DC] bg-white p-6 text-sm text-[#8B7C74]">No active projects yet. Create one in Projects, then use Studio tools to develop its creative direction.</div>}</div><SpecialUpgradeGrid room="creative-studio"/><Link href="/projects" className="inline-flex text-xs font-semibold text-[#B66D77]">Open full Projects system →</Link></div></AppShell>}
