import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { AppShell } from '@/components/app-shell';
import { UtilityFrame, styles as shell } from '@/components/system-reference/utility-frame';
import { createConciergeProposalAction, decideConciergeProposalAction, reverseConciergeProposalAction } from '@/app/actions/concierge';
import { getAiProposals, getAuditEvents } from '@/lib/data/completion-v1';
import { Check, RotateCcw, ShieldCheck, Sparkles, X } from 'lucide-react';

export const dynamic='force-dynamic';
const field='w-full rounded-[16px] border border-white/70 bg-white/45 px-4 py-3 text-[11px] outline-none';
type Payload=Record<string,unknown>&{actionType?:string;task?:{title?:string;priority?:string;dueDate?:string|null};execution?:{entityType?:string;entityId?:string;executedAt?:string;reversedAt?:string}};
function payload(value:unknown):Payload{return value&&typeof value==='object'?value as Payload:{}}

export default async function ConciergeApprovalsPage(){
  const session=await auth();if(!session?.user?.id)redirect('/sign-in');
  const [proposals,audit]=await Promise.all([getAiProposals(session.user.id),getAuditEvents(session.user.id)]);
  const pending=proposals.filter(p=>p.status==='pending').length;
  return <AppShell><UtilityFrame title="Concierge · Approvals" backHref="/concierge" backLabel="Journey"><div style={{padding:'24px 4px',display:'grid',gap:14}}>
    <section className={shell.glass} style={{padding:20,position:'relative',overflow:'hidden'}}><ShieldCheck size={58} strokeWidth={.8} style={{position:'absolute',right:22,top:12,opacity:.14}}/><p className={shell.eyebrow}>Approval desk</p><h1 style={{margin:'4px 0 0',fontSize:30,fontWeight:570,letterSpacing:'-.04em'}}>Glow can suggest. You stay in control.</h1><p className={shell.sectionNote}>{pending} proposal{pending===1?'':'s'} waiting. Nothing in this queue changes your data until you approve it.</p></section>
    <div style={{display:'grid',gridTemplateColumns:'minmax(280px,.75fr) minmax(0,1.25fr)',gap:14}}>
      <section className={shell.glass} style={{padding:18}}><div style={{display:'flex',gap:8,alignItems:'center'}}><Sparkles size={15}/><h2 className={shell.sectionTitle}>Create a proposal</h2></div><form action={createConciergeProposalAction} style={{display:'grid',gap:9,marginTop:13}}><select name="actionType" defaultValue="advisory" className={field}><option value="advisory">Advisory only — no data change</option><option value="create_task">Create a task after approval</option></select><input name="intent" required placeholder="Intent, e.g. Make today lighter" className={field}/><textarea name="summary" required rows={3} placeholder="What should change?" className={field}/><textarea name="reason" required rows={3} placeholder="Why is this recommended?" className={field}/><div className={shell.well} style={{padding:12}}><p className={shell.eyebrow}>Optional executable task</p><div style={{display:'grid',gap:8,marginTop:8}}><input name="taskTitle" placeholder="Task title" className={field}/><select name="taskPriority" defaultValue="medium" className={field}><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option><option value="urgent">Urgent priority</option></select><input name="taskDueDate" type="datetime-local" className={field}/></div></div><button className={`${shell.btn} ${shell.btnPrimary}`}>Create proposal</button></form></section>
      <section className={shell.glass} style={{overflow:'hidden'}}><div style={{padding:'16px 18px',borderBottom:'1px solid rgba(100,90,86,.08)'}}><p className={shell.eyebrow}>Approval queue</p><h2 className={shell.sectionTitle}>Proposals</h2></div>{proposals.length?<div>{proposals.map(proposal=>{const p=payload(proposal.payload);const canReverse=proposal.status==='approved'&&proposal.reversible&&p.execution?.entityType==='task'&&p.execution.entityId&&!p.execution.reversedAt;return <article key={proposal.id} style={{padding:'14px 18px',borderBottom:'1px solid rgba(100,90,86,.08)'}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong style={{fontSize:12}}>{proposal.summary}</strong><p className={shell.sectionNote}>{proposal.reason}</p></div><span className={shell.capsule}>{proposal.status}</span></div><p className={shell.tiny} style={{marginTop:7}}>{p.actionType==='create_task'?'Create task':'Advisory only'} · Confidence {Math.round(proposal.confidence*100)}% · {proposal.reversible?'Safe undo supported':'No data write'}</p>{p.task?.title?<div className={shell.well} style={{padding:10,marginTop:9,fontSize:9}}>Planned task: {p.task.title}{p.task.priority?` · ${p.task.priority}`:''}</div>:null}{proposal.status==='pending'?<div style={{display:'flex',gap:8,marginTop:10}}><form action={decideConciergeProposalAction.bind(null,proposal.id,'approved')}><button className={`${shell.btn} ${shell.btnPrimary}`}><Check size={12}/>Approve</button></form><form action={decideConciergeProposalAction.bind(null,proposal.id,'rejected')}><button className={shell.btn}><X size={12}/>Reject</button></form></div>:null}{canReverse?<form action={reverseConciergeProposalAction.bind(null,proposal.id)} style={{marginTop:10}}><button className={shell.btn}><RotateCcw size={12}/>Undo applied task</button></form>:null}</article>})}</div>:<div className={shell.empty}>No proposals yet.</div>}</section>
    </div>
    <section className={shell.glass} style={{padding:16}}><p className={shell.eyebrow}>Audit ribbon</p><h2 className={shell.sectionTitle}>Decision + execution history</h2><div style={{marginTop:10,display:'grid',gap:6}}>{audit.length?audit.slice(0,12).map(event=><div key={event.id} className={shell.row}><span style={{flex:1,fontSize:9}}>{event.action.replaceAll('_',' ')}</span><span className={shell.tiny}>{event.createdAt.toLocaleString()}</span></div>):<div className={shell.empty}>No approved, rejected, or reversed actions yet.</div>}</div></section>
  </div></UtilityFrame></AppShell>;
}
