import { and, eq } from 'drizzle-orm';
import { db } from '@/db';
import { taskDependencies } from '@/db/schema/adaptive-os';
import { createDependencyAction, deleteDependencyAction } from '@/app/actions/dependencies';
import { Link2, Trash2 } from 'lucide-react';

type TaskLite={id:string;title:string;status:string};

export async function TaskDependencyPanel({userId,tasks}:{userId:string;tasks:TaskLite[]}){
  let dependencies;
  try{dependencies=await db.select().from(taskDependencies).where(eq(taskDependencies.userId,userId));}catch{return <section className="rounded-[18px] border border-amber-200 bg-amber-50/65 p-4"><p className="text-[9px] font-medium text-amber-900">Dependency Engine is ready after intelligence activation.</p><a href="/settings/intelligence" className="mt-2 inline-block text-[8px] text-amber-800">Activate intelligence →</a></section>;}
  const open=tasks.filter(t=>t.status!=='done'&&t.status!=='cancelled');
  const names=new Map(tasks.map(t=>[t.id,t.title]));
  return <section className="editorial-surface overflow-hidden"><div className="flex items-center justify-between border-b border-[#eadfd6] px-4 py-3"><div className="flex items-center gap-2"><Link2 size={13} className="text-[#a46b74]"/><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#745f58]">Dependency Engine</p></div><span className="text-[8px] text-[#9c8780]">{dependencies.length} link{dependencies.length===1?'':'s'}</span></div><div className="grid gap-4 p-4 lg:grid-cols-[.8fr_1.2fr]"><form action={createDependencyAction} className="space-y-2 rounded-[14px] bg-[#faf5f1] p-3"><p className="text-[8px] font-medium text-[#66534d]">Define what must happen first.</p><select name="predecessorId" required className="w-full rounded-lg border border-[#e1d4cc] bg-white px-3 py-2 text-[8px]"><option value="">First task…</option>{open.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><select name="successorId" required className="w-full rounded-lg border border-[#e1d4cc] bg-white px-3 py-2 text-[8px]"><option value="">Then unlock…</option>{open.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><select name="dependencyType" className="w-full rounded-lg border border-[#e1d4cc] bg-white px-3 py-2 text-[8px]"><option value="blocks">Blocks</option><option value="precedes">Precedes</option><option value="requires">Requires</option></select><button type="submit" disabled={open.length<2} className="w-full rounded-lg bg-[#40352f] py-2 text-[8px] text-white disabled:opacity-40">Connect tasks</button></form><div className="space-y-2">{dependencies.length?dependencies.map(dep=><div key={dep.id} className="flex items-center gap-2 rounded-[12px] border border-[#eadfd7] bg-white/65 p-3"><div className="min-w-0 flex-1"><p className="truncate text-[9px] font-medium text-[#4b3d37]">{names.get(dep.predecessorId)??'Task'}</p><p className="my-1 text-[7px] uppercase tracking-[.12em] text-[#a1847d]">{dep.dependencyType} ↓</p><p className="truncate text-[9px] text-[#725f58]">{names.get(dep.successorId)??'Task'}</p></div><form action={deleteDependencyAction.bind(null,dep.id)}><button type="submit" aria-label="Remove dependency" className="rounded-full border border-[#e4d7cf] p-2 text-[#a0887f]"><Trash2 size={11}/></button></form></div>):<p className="rounded-[12px] border border-dashed border-[#ddd0c8] p-5 text-center text-[8px] leading-4 text-[#8d7972]">No dependencies yet. Connect tasks to reveal the next meaningful action instead of showing an overwhelming project list.</p>}</div></div></section>;
}
