export type ReferenceRoomBlueprint = {
  title: string;
  script: string;
  accent: string;
  soft: string;
  layout: 'command'|'desk'|'calendar'|'board'|'ritual'|'garden'|'studio'|'sanctuary'|'kitchen'|'vanity'|'lab'|'atelier'|'money'|'money-brain'|'goals'|'notes'|'settings'|'world';
  tabs: string[];
  heroTitle: string;
  heroCopy: string;
  metrics: [string,string][];
  primary: string[];
  secondary: string[];
  rail: string[];
};

export const REFERENCE_ROOM_BLUEPRINTS: Record<string, ReferenceRoomBlueprint> = {
  dashboard:{title:'Good evening, Tatiyana',script:'Every day is a new chapter of the life you’re creating.',accent:'#c9838f',soft:'#f6e4e1',layout:'command',tabs:['Today','My World','Focus','Insights'],heroTitle:'My Mood Board',heroCopy:'Pin what feels like you. Anchor one priority early and keep your pace intentional.',metrics:[['Top priority','Finish Glow OS'],['Tasks today','8 / 14'],['Habit score','85%'],['Focus time','2h 15m'],['Water','5 / 8']],primary:["Today's plan",'Upcoming',"Today's meals",'Habit tracker'],secondary:['Build My Day','Plan My Meals','Grocery List','Prepare My Reset'],rail:['8:48 PM · Monday, August 10',"Today's focus · Faith · Discipline · Soft Life",'Ritual of the day · Evening Wind-Down','Finance overview · 61%']},
  tasks:{title:'Tasks & Planner',script:'your life, organized beautifully.',accent:'#c9828d',soft:'#f4dfda',layout:'desk',tabs:['Tasks','Planner','Inbox','Waiting On','Someday','Completed'],heroTitle:'Priority Desk',heroCopy:'A tactile planning desk for what comes first, what belongs today, and what can wait.',metrics:[['Do first','4'],['Do today','6'],['Inbox','4'],['Waiting on','3']],primary:['Finish Glow OS Calendar','Client Call – Glow OS','Workout','Deep Work Block','Lunch & Reset','Review Hair Routine Plan'],secondary:['Inbox','Waiting On','Someday'],rail:['Today overview','Task progress · 8 of 14','Focus timer · 2h 15m','Daily affirmation']},
  calendar:{title:'Calendar',script:'your time, intentionally designed.',accent:'#c7828e',soft:'#f6dfdf',layout:'calendar',tabs:['Day','Week','Month','Year','Timeline'],heroTitle:'August 10 – 16, 2026',heroCopy:'A visual planning wall where time moves left to right and detail deepens vertically.',metrics:[['Morning','5AM – 10AM'],['Afternoon','10AM – 4PM'],['Evening','4PM – 8:30PM'],['Night','8:30PM – 11PM']],primary:['Morning Routine','Workout','Protein Breakfast + Hydration','Deep Work','Lunch + Reset','Content Work','Evening Routine','Dinner','Night Routine'],secondary:['Mon 10','Tue 11','Wed 12','Thu 13','Fri 14','Sat 15','Sun 16'],rail:['Mini month · August 2026','Upcoming events','Day overview · 8 events','AI schedule insight']},
  planning:{title:'Planning',script:'design your days, then your destiny.',accent:'#c9828d',soft:'#f4e2dd',layout:'board',tabs:['Today','This Week','This Month','Quarter','Year'],heroTitle:'Life Planning Surface',heroCopy:'Priorities, appointments, deadlines, groceries, ideas and projects in one strategic workspace.',metrics:[['Top Three','3'],['Appointments','3'],['Deadlines','3'],['Things to buy','3']],primary:['Groceries','Things to Remember','Waiting On','Ideas','Meals to Make','Projects to Move'],secondary:['Mon · 80%','Tue · 70%','Wed · 75%','Thu · 60%','Fri · 80%','Sat · 65%','Sun · 50%'],rail:['Sunday Reset · reset, realign, refocus','Notes','Quick Add']},
  routines:{title:'Routines & Rituals',script:'small rituals, big transformations.',accent:'#c27f8a',soft:'#f3e3df',layout:'ritual',tabs:['My Rituals','Morning','Night','Weekly','Hair Days','Events','Everything Shower','Custom'],heroTitle:'Morning Ritual',heroCopy:'Start your day with intention. Choose a full, normal, short, express or emergency version.',metrics:[['Steps','11'],['Full routine','60–90 min'],['Quick version','20 min'],['Completion','87%']],primary:['Hydrate + Supplements','Journal & Brain Dump','Movement','Shower','Hair Care','Skincare','Get Ready','Nutrition: Breakfast','Plan My Day','Review Calendar','Affirmations & Visualization'],secondary:['Morning Ritual','Night Ritual','Wash Day Ritual','Everything Shower','Sunday Reset'],rail:['Up next · Movement','Ritual library','Ritual stats','Today’s intention','Quick actions']},
  habits:{title:'Habits',script:'small daily choices, big life transformation.',accent:'#b97984',soft:'#f4e4df',layout:'garden',tabs:['Garden View','Today','Week','Month','Year','Insights'],heroTitle:'Your Habit Garden',heroCopy:'Nurture consistency. Watch your life grow.',metrics:[['Day streak','28'],['Weekly score','87%'],['Habits tracked','56'],['Total completions','512']],primary:['Morning Routine · 85%','Workout · 72%','Water · 90%','Reading · 60%','Skincare · 80%','No Spend Day · 67%','Journaling · 75%','Meditation · 50%'],secondary:["Today's Habits",'Habit Focus · Drink Water'],rail:['Streak Tree · 28 days strong',"Today's progress · 7 of 8",'Habit Insights','Quick Actions','AI Habit Coach']},
  fitness:{title:'Fitness Studio',script:'strong body, strong mind, strong you.',accent:'#c47e8a',soft:'#f1dfdb',layout:'studio',tabs:['Today','Workouts','Programs','Progress','Body Stats','Mobility','Recovery','Challenges'],heroTitle:'Lower Body',heroCopy:'Build strength. Shape. Power. Today’s workout adapts to energy, recovery, soreness and available time.',metrics:[['Focus','Glutes, Hamstrings, Quads'],['Duration','48 min'],['Exercises','6'],['Est. calories','420 kcal']],primary:['Hip Thrust · 115 lbs','Romanian Deadlift · 60 lbs','Bulgarian Split Squat · 25 lbs','Leg Press · 140 lbs','Cable Kickback · 25 lbs','Standing Calf Raise · Bodyweight'],secondary:['This Week','Progress Photos','PR Program'],rail:['Weekly activity · 4 of 6','Body stats','Recovery status · 82%','Hydration · 6 of 8']},
  wellness:{title:'Wellness Sanctuary',script:'Your peace is your power.',accent:'#7e966b',soft:'#e9eee1',layout:'sanctuary',tabs:['Today','Check-In','Sleep','Mood','Mind','Body','Recovery','Journal'],heroTitle:'Rest is productive. Peace is powerful.',heroCopy:'Check in with yourself. Nourish your body, calm your mind, and protect your energy.',metrics:[['Energy','4 / 5'],['Stress','2 / 5'],['Mood','4 / 5'],['Sleep','7h 21m']],primary:['Breathing · 3 min','Meditation · 10 min','Journal · Write freely','Gratitude · 3 things','Stretch · 8 min','Sound Bath · 15 min'],secondary:['Wellness Journal','Sleep Overview · 88','Wellness Insights'],rail:["Today's wellness focus",'Wellness streak · 18 days','Self care ideas']},
  food:{title:'Food & Nutrition',script:'Nourish your body. Fuel your glow.',accent:'#c47e88',soft:'#f5e4dd',layout:'kitchen',tabs:['Today','Meals','Meal Plan','Pantry','Recipes','Nutrition','Groceries','Hydration','Favorites'],heroTitle:"Today's Meals",heroCopy:'Whole foods, balanced meals, and mindful choices for a vibrant life.',metrics:[['Breakfast','Greek Yogurt Bowl'],['Lunch','Salmon Power Bowl'],['Dinner','Chicken Stir Fry'],['Snack','Apple & Almond Butter']],primary:['Pantry Overview','Quick Recipes','Nutrition Insights','Meal Plan – This Week','Shopping List'],secondary:['Spinach','Eggs','Greek Yogurt','Salmon','Quinoa'],rail:['Nutrition overview · 1,652 calories','Hydration tracker · 5 of 8','Favorite recipes','AI Nutrition Coach']},
  beauty:{title:'Beauty OS',script:'Enhance your natural glow. Inside & out.',accent:'#ca7f90',soft:'#f5e2e1',layout:'vanity',tabs:['Overview','Skincare','Makeup','Body Care','Fragrance','Treatments','Prescriptions','Progress','Inspiration'],heroTitle:'Hydrate, Protect, Glow',heroCopy:'Consistency is the luxury. Your routine, appointments, products and progress in one private beauty headquarters.',metrics:[['Morning skincare','Done'],['SPF 50','Done'],['Hydrate','2L water'],['Evening skincare','Next']],primary:['Skincare Routine','Beauty Habits','Recent Progress','Beauty Inventory','Top Categories','Wishlist','Beauty Budget'],secondary:['Cleanser','Serum','Moisturizer','SPF','Treatment'],rail:['Skin health score · 87','Upcoming treatments','Products expiring soon']},
  'beauty-lab':{title:'Beauty Lab',script:'Track. Test. Transform.',accent:'#c47b89',soft:'#f4e1df',layout:'lab',tabs:['Overview','Inventory','Ingredients','Routines','Skin Journal','Hair Lab','Prescriptions','Compatibility','Analytics'],heroTitle:'Today in Your Lab',heroCopy:'Your personal beauty laboratory. Know what works, what doesn’t, and what’s next.',metrics:[['Skin status','Balanced'],['Hydration','Good'],['Sensitivity','Low'],['Breakouts','Clear']],primary:['Your Inventory · 78 products','Active Routines','Skin Journal Progress','Most Used Ingredients'],secondary:['Cleansers','Serums','Moisturizers','Treatments','Sunscreens','Masks','Hair Care','Body Care','Makeup'],rail:['Product usage · 87% consistency','Expiring soon','Reactions & notes','Product categories']},
  hair:{title:'Hair',script:'Healthy hair, healthy you.',accent:'#b87382',soft:'#f4e0dc',layout:'atelier',tabs:['Overview','Wash Days','Treatments','Hair Goals','Products','Scalp Care','Styles','Inspiration','History'],heroTitle:'Healthy Roots, Long Term Growth',heroCopy:'Your hair is your crown. Track the full lifecycle from wash day through scalp health, treatments, styles and growth.',metrics:[['Scalp massage','5 min'],['Hydrate','Done'],['Protect ends','Done'],['Silk scarf','Tonight']],primary:['Wash Day Schedule','Hair Goals','Hair Stats','Product Shelf','Recent Treatments'],secondary:['Shampoos','Conditioners','Leave-Ins','Treatments','Oils & Serums','Stylers','Supplements','Tools'],rail:['Hair health score · 83%','Next wash day · 2 days left','Products running low','Hair inspiration']},
  finance:{title:'Finance',script:'Take control. Build freedom. Create abundance.',accent:'#788866',soft:'#e8eadf',layout:'money',tabs:['Overview','Accounts','Budget','Goals','Investments','Bills & Subscriptions','Transactions','Taxes','Reports'],heroTitle:'Financial Overview',heroCopy:'A calm private money journal that turns spending, saving, bills and cash flow into a clear story.',metrics:[['Income','$4,850.00'],['Expenses','$2,693.42'],['Savings','$2,156.58'],['Savings rate','44%']],primary:['Spending Breakdown','Net Worth','Budget Progress','Recent Transactions','Cash Flow','Investment Overview'],secondary:['Housing','Food','Transportation','Beauty & Self Care','Health','Entertainment','Shopping'],rail:['Savings Goals','Upcoming Bills','Subscriptions']},
  'financial-brain':{title:'Financial Brain',script:'Smart money decisions. Future you is watching.',accent:'#758762',soft:'#e8eadf',layout:'money-brain',tabs:['Overview','Spending Intelligence','Cash Flow','Budget Planner','Goals & Savings','Investments','Net Worth','Big Purchases','Reports','AI Advisor'],heroTitle:'Your Financial Health Score',heroCopy:'AI insights, cash flow forecasting, spending intelligence, and goal tracking — all in one place.',metrics:[['Health score','89 / 100'],['Cash Flow','92 / 100'],['Savings','90 / 100'],['Debt Mgmt','93 / 100']],primary:['Cash Flow Overview','AI Financial Insight','Spending Breakdown','Budget Progress','Net Worth','Savings Goals','Subscriptions','Cash Flow Forecast','Top Spending Triggers','Big Purchases Planner'],secondary:['Projected Savings · $6,780','End Balance · $14,250'],rail:['Opportunity · save $120/mo','Invest Smart','AI Financial Coach']},
  goals:{title:'Goals',script:'Dream it. Plan it. Achieve it.',accent:'#be7685',soft:'#f3e0df',layout:'goals',tabs:['Overview','Life Goals','Quarterly Goals','Goal Planner','Vision Board','Milestones','Habit Goals','Achievements','Reflections'],heroTitle:'Grow into the future version of you.',heroCopy:'Make the future visible enough to move toward it. Connect vision to milestones, habits, projects and next actions.',metrics:[['Overall progress','68%'],['Completed','12'],['In progress','5'],['Not started','3']],primary:['Goals by Category','Top Goals','Upcoming Milestones','Goal Timeline','Vision Board','Goal Reflection'],secondary:['Personal Growth','Health & Wellness','Financial','Career & Business','Relationships','Travel & Experiences','Home & Lifestyle'],rail:['Daily Goal Reminder','Goal Streaks','Achievements']},
  notes:{title:'Notes',script:'Capture your thoughts. Organize your world.',accent:'#bb7482',soft:'#f3e1de',layout:'notes',tabs:['All Notes','Notebooks','Pinned','Shared','Trash'],heroTitle:'Morning Thoughts',heroCopy:'Capture first. Organize second. Keep writing expressive while Glow makes every thought searchable and useful.',metrics:[['Recent notes','5'],['Notebooks','12'],['Pinned','4'],['Tags','15']],primary:['Life Vision','Weekly Plan','Brand Concept','Italy Itinerary','Life Journal','Business & Branding','Travel','Wellness & Health','Finance','Ideas & Inspiration'],secondary:['Good morning, Tatiyana.','Top 3 Intentions for Today','Notes to self'],rail:['Quick Capture','Today’s Reminders','Tags','Templates']},
  settings:{title:'Settings',script:'Customize your Glow. Control your world.',accent:'#b87382',soft:'#f3e1dd',layout:'settings',tabs:['My Account','Preferences','Notifications','Integrations','Security & Privacy','Data Management','About Glow OS'],heroTitle:'My Account',heroCopy:'Control identity, appearance, privacy, connected systems and data without touching code.',metrics:[['Level','27'],['XP','2,450'],['Status','On Track'],['Version','2.1.0']],primary:['Preferences','Notifications','Integrations','Security & Privacy','Data Management','About Glow OS'],secondary:['Light','Dark','Auto','Accent Color'],rail:['Quick Actions','Daily Affirmation','App Appearance','Need Help?']},
  world:{title:'Life World',script:'Your life. Your world. All in one place.',accent:'#9d6ca8',soft:'#eee4f1',layout:'world',tabs:['World','Map','People','Bookmarks','Memories','Playlist','Immersive'],heroTitle:'Your World. Your Life.',heroCopy:'Step outside your dashboard and into the full experience of your life.',metrics:[['Days intentional','22'],['Workouts','18'],['Books read','3'],['Money saved','$2,156']],primary:['The Sanctuary · Home','Inner World · Mind','Body World · Fitness','Glow World · Beauty','Wealth World · Finance','Adventure World · Travel','Purpose World · Career','Creation World · Creativity'],secondary:['World Map','Memory Vault','Current Chapter','Today’s World Focus','World Playlist','World Journal'],rail:['Places visited · 18 countries','Memories · 2,317','Current chapter · Building My Dream Life','Enter Immersive Mode']},
};

export function blueprintForRoom(room: string) {
  return REFERENCE_ROOM_BLUEPRINTS[room] ?? REFERENCE_ROOM_BLUEPRINTS.dashboard;
}
