'use client';

import Link from 'next/link';
import { useMemo, useState, useTransition } from 'react';
import { Check, ChefHat, ChevronLeft, Clock3, Heart, Mic2, PackageCheck, Refrigerator, Search, ShoppingBasket, Utensils, X } from 'lucide-react';
import { addAllFoodDraftGroceriesAction, addFoodGroceryAction, addFoodLeftoverAction, completeFoodMealPrepAction, createFoodCustomRecipeAction, recordFoodMealPrepStepAction, recordFoodRecipeUseAction, saveFoodMealPlanAction, setFoodGroceryStatusAction, setFoodRecipePreferenceAction, startFoodMealPrepAction, updateFoodInventoryAction, useFoodLeftoverAction as consumeFoodLeftoverAction } from '@/app/actions/food-intelligence';

type Recipe={id:string;title:string;categories:string[];tags:string[];recipeStatus:string;servings:string|null;prepMinutes:number|null;cookMinutes:number|null;totalMinutes:number|null;ingredients:Array<{name:string;amount?:string;note?:string}>;instructions:Array<{text:string;seconds?:number;parallelHint?:string}>;notes:string|null;favorite:boolean;rotation:string;rating:string|null;feedback:string[];useCount:number;lastUsedAt:string|null};
type Pantry={id:string;normalizedName:string;name:string;category:string;state:string;quantity:number|null;unit:string|null;minimumQuantity:number|null;expiresAt:string|null;groceryDraft:boolean};
type Grocery={id:string;normalizedName:string;name:string;category:string;status:string};
type Meal={id:string;mealDate:string;mealType:string;recipeId:string|null;title:string;status:string};
type Leftover={id:string;recipeId:string|null;title:string;servingsRemaining:number;expiresAt:string|null};
type Prep={id:string;title:string;status:string;queue:Array<{id:string;title:string;seconds:number;parallelHint?:string}>;completedStepIds:string[];skippedStepIds:string[];currentIndex:number;actualSeconds:number};
type State={recipes:Recipe[];inventory:Pantry[];groceries:Grocery[];mealPlans:Meal[];leftovers:Leftover[];prepRuns:Prep[];events:Array<{id:string;title:string;occurredAt:string}>};
type Tab='Today'|'Recipes'|'Pantry'|'Groceries'|'Meal Plan'|'Meal Prep'|'Food Studio';
const TABS:Tab[]=['Today','Recipes','Pantry','Groceries','Meal Plan','Meal Prep','Food Studio'];
const MEALS=['breakfast','lunch','dinner','snack'] as const;
const SMOOTHIE=['Water','Almond milk','Milk','Frozen fruit','Strawberries','Blueberries','Spinach','Kale','Collagen powder','Honey','Vanilla protein powder','Sea moss gel'];
const BOWL=['Shrimp','Extra-firm tofu','Salmon','Butter beans','White rice','Quinoa','Potatoes','Greens','Spinach','Bell peppers','Cucumber','Carrots','Soy sauce','Miso paste','Lemon','Garlic'];
function day(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function mealType(h:number):typeof MEALS[number]{return h<11?'breakfast':h<15?'lunch':h<20?'dinner':'snack'}
function mins(r:Recipe){if(r.totalMinutes!=null)return r.totalMinutes;const v=(r.prepMinutes??0)+(r.cookMinutes??0);return v||null}
function groups<T>(rows:T[],key:(r:T)=>string){return rows.reduce<Record<string,T[]>>((a,r)=>{const k=key(r);if(!a[k])a[k]=[];a[k].push(r);return a},{})}
function match(r:Recipe,p:Pantry[]){if(!r.ingredients.length)return{have:0,total:0};const stock=p.filter(x=>x.state==='in_stock'||x.state==='use_soon').map(x=>x.name.toLowerCase());let have=0;for(const i of r.ingredients){const tokens=i.name.toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2);if(stock.some(s=>tokens.some(t=>s.includes(t))))have++}return{have,total:r.ingredients.length}}

export function FoodIntelligenceLive({initial,nextEvent,foodSpendCents,foodPurchaseCount}:{initial:State;nextEvent:{id:string;title:string;startAt:string}|null;foodSpendCents:number;foodPurchaseCount:number}){
 const [tab,setTab]=useState<Tab>('Today');const [recipes,setRecipes]=useState(initial.recipes);const [pantry,setPantry]=useState(initial.inventory);const [groceries,setGroceries]=useState(initial.groceries);const [meals,setMeals]=useState(initial.mealPlans);const [leftovers,setLeftovers]=useState(initial.leftovers);const [prep,setPrep]=useState<Prep|null>(initial.prepRuns.find(x=>x.status==='active')??null);const [selected,setSelected]=useState<Recipe|null>(null);const [cook,setCook]=useState<{recipe:Recipe;index:number}|null>(null);const [query,setQuery]=useState('');const [time,setTime]=useState(15);const [smoothie,setSmoothie]=useState<string[]>([]);const [bowl,setBowl]=useState<string[]>([]);const [notice,setNotice]=useState('');const [pending,startTransition]=useTransition();
 const now=new Date(),today=day(now),currentMeal=mealType(now.getHours());const todays=meals.filter(x=>x.mealDate===today),draft=groceries.filter(x=>x.status==='draft'),listed=groceries.filter(x=>x.status==='listed'),review=pantry.filter(x=>x.state==='review'),soon=pantry.filter(x=>x.state==='use_soon'),activeLeftovers=leftovers.filter(x=>x.servingsRemaining>0);const beforeNext=nextEvent?Math.max(0,Math.floor((new Date(nextEvent.startAt).getTime()-Date.now())/60000)):999;const spend=(foodSpendCents/100).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});const prepStep=prep?.queue[prep.currentIndex]??null;
 const recommended=useMemo(()=>recipes.filter(r=>r.recipeStatus==='complete').map(r=>({r,m:match(r,pantry),minutes:mins(r)})).filter(x=>x.minutes==null||x.minutes<=time||time===60).sort((a,b)=>{const ap=a.m.total?a.m.have/a.m.total:0,bp=b.m.total?b.m.have/b.m.total:0;return bp-ap||((a.minutes??999)-(b.minutes??999))}).slice(0,6),[recipes,pantry,time]);
 const shown=recipes.filter(r=>!query||`${r.title} ${r.categories.join(' ')} ${r.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||a.title.localeCompare(b.title));
 const toast=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(''),3200)};const speak=(s:string)=>window.dispatchEvent(new CustomEvent('glow:speak',{detail:{text:s}}));
 function setStock(item:Pantry,state:'in_stock'|'use_soon'|'out'){startTransition(async()=>{const r=await updateFoodInventoryAction({id:item.id,state});if(!r.data)return toast(r.error??'Could not update Pantry.');setPantry(x=>x.map(v=>v.id===item.id?r.data as Pantry:v));if(state==='out')toast(`${item.name} added to grocery draft.`)})}
 function addGrocery(name:string,category='Other'){startTransition(async()=>{const r=await addFoodGroceryAction({name,category,status:'listed'});if(r.data){const row=r.data as Grocery;setGroceries(x=>x.some(v=>v.id===row.id)?x:[...x,row])}else toast(r.error??'Could not add grocery.')})}
 function bought(g:Grocery){startTransition(async()=>{const r=await setFoodGroceryStatusAction({id:g.id,status:'completed'});if(!r.data)return toast(r.error??'Could not update grocery.');setGroceries(x=>x.filter(v=>v.id!==g.id));setPantry(x=>x.map(v=>v.normalizedName===g.normalizedName?{...v,state:'in_stock',groceryDraft:false}:v))})}
 function favorite(r:Recipe){startTransition(async()=>{const x=await setFoodRecipePreferenceAction({id:r.id,favorite:!r.favorite});if(x.data){const row=x.data as Recipe;setRecipes(v=>v.map(y=>y.id===row.id?row:y));if(selected?.id===row.id)setSelected(row)}})}
 function plan(r:Recipe){startTransition(async()=>{const x=await saveFoodMealPlanAction({mealDate:today,mealType:currentMeal,recipeId:r.id,title:r.title,status:'planned'});if(x.data){const row=x.data as Meal;setMeals(v=>[...v.filter(y=>!(y.mealDate===today&&y.mealType===currentMeal)),row]);toast(`${r.title} planned.`)}})}
 function ate(m:Meal){startTransition(async()=>{const x=await saveFoodMealPlanAction({mealDate:m.mealDate,mealType:m.mealType,recipeId:m.recipeId,title:m.title,status:'ate'});if(x.data){const row=x.data as Meal;setMeals(v=>v.map(y=>y.id===row.id?row:y))}})}
 function startCook(r:Recipe){if(!r.instructions.length)return toast('Original complete instructions are not available for this recipe.');setCook({recipe:r,index:0});speak(`Starting ${r.title}. ${r.instructions[0].text}`)}
 function nextCook(){if(!cook)return;const n=cook.index+1;if(n<cook.recipe.instructions.length){setCook({...cook,index:n});speak(cook.recipe.instructions[n].text);return}startTransition(async()=>{await recordFoodRecipeUseAction(cook.recipe.id);setRecipes(x=>x.map(r=>r.id===cook.recipe.id?{...r,useCount:r.useCount+1,lastUsedAt:new Date().toISOString()}:r));setCook(null);toast(`${cook.recipe.title} saved to meal history.`)})}
 function startPrep(){startTransition(async()=>{const x=await startFoodMealPrepAction();if(x.data){setPrep(x.data as Prep);setTab('Meal Prep')}else toast(x.error??'Could not start Meal Prep.')})}
 function prepDone(status:'completed'|'skipped'){if(!prep||!prepStep)return;startTransition(async()=>{const x=await recordFoodMealPrepStepAction({runId:prep.id,stepId:prepStep.id,status,actualSeconds:0});if(!x.data)return toast(x.error??'Could not save prep step.');let row=x.data as Prep;if(row.currentIndex>=row.queue.length){const done=await completeFoodMealPrepAction(row.id);if(done.data)row=done.data as Prep}setPrep(row);if(row.status==='completed')toast('Meal Prep complete.')})}
 function saveBuilder(kind:'smoothie'|'bowl'){const items=kind==='smoothie'?smoothie:bowl;if(!items.length)return toast('Choose ingredients first.');const title=`My ${kind==='smoothie'?'Smoothie':'Bowl'} · ${new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'})}`;startTransition(async()=>{const x=await createFoodCustomRecipeAction({title,primaryCategory:kind==='smoothie'?'drinks':'meal',categories:kind==='smoothie'?['Drinks & Smoothies']:['Lunch','Dinner'],tags:[kind,'created in Glow'],ingredients:items,notes:'Built from selected Food Studio ingredients. No quantities were invented.'});if(x.data){setRecipes(v=>[x.data as Recipe,...v]);toast(`${title} saved.`)}})}
 if(cook){const s=cook.recipe.instructions[cook.index];return <div className="fixed inset-0 z-[130] overflow-y-auto bg-[linear-gradient(145deg,#fffdf7,#efe5d7,#e3eadb)] p-5"><div className="mx-auto max-w-2xl"><div className="flex items-center justify-between"><button type="button" aria-label="Close Cook Mode" onClick={()=>setCook(null)} className="rounded-full bg-white/70 p-3"><ChevronLeft size={18}/></button><span className="text-xs">Cook Mode · {cook.recipe.title}</span><button type="button" aria-label="Read step aloud" onClick={()=>speak(s.text)} className="rounded-full bg-white/70 p-3"><Mic2 size={17}/></button></div><div className="mt-20 text-center"><ChefHat className="mx-auto text-[#936a50]"/><p className="mt-4 text-xs">{cook.index+1} / {cook.recipe.instructions.length}</p><h1 className="glow-display mx-auto mt-4 max-w-xl text-4xl">{s.text}</h1>{s.parallelHint?<p className="mx-auto mt-5 max-w-md rounded-2xl bg-white/60 p-4 text-sm"><b>Parallel:</b> {s.parallelHint}</p>:null}<button type="button" onClick={nextCook} className="mt-7 rounded-full bg-[#765b45] px-7 py-3.5 text-sm text-white">{cook.index===cook.recipe.instructions.length-1?'Finish':'Next'}</button></div></div></div>}
 return <div className="space-y-5 pb-24">{notice?<div role="status" className="fixed right-4 top-4 z-[140] rounded-2xl bg-[#3c372f] px-4 py-3 text-xs text-white">{notice}</div>:null}
 <section className="rounded-[32px] border border-[#eadfce] bg-[linear-gradient(135deg,#fffaf1,#f1e7d8_58%,#e2e9da)] p-6 sm:p-8"><div className="grid gap-7 lg:grid-cols-[1.2fr_.8fr]"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#807366]">Food · Decide → Prepare → Eat → Restock → Learn</p><h1 className="glow-display mt-3 text-[44px] leading-none sm:text-[58px]">Food Right Now</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#71675e]">Nourishment, not restriction. Your complete Food-folder catalog is connected to persistent recipes, Pantry, groceries, meal planning, Meal Prep and leftovers.</p><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={()=>setTab('Food Studio')} className="rounded-full bg-[#836049] px-5 py-3 text-sm text-white">Make Something</button><button type="button" onClick={()=>{setTime(5);setTab('Food Studio')}} className="rounded-full bg-white/75 px-5 py-3 text-sm">Quick Meal</button><button type="button" onClick={()=>setTab('Pantry')} className="rounded-full bg-white/75 px-5 py-3 text-sm">Use What I Have</button></div></div><div className="rounded-[26px] bg-white/60 p-5"><p className="text-xs">Best next food action</p><h2 className="glow-display mt-2 text-2xl">{activeLeftovers[0]?.title?`Use ${activeLeftovers[0].title}`:recommended[0]?.r.title??'Review your Pantry'}</h2><p className="mt-2 text-sm">{review.length} imported items still need stock confirmation.</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span className="rounded-xl bg-white p-3">Before next event<br/><b>{beforeNext>=999?'Open':`${beforeNext} min`}</b></span><span className="rounded-xl bg-white p-3">Food spend<br/><b>{spend}</b> · {foodPurchaseCount} entries</span></div></div></div></section>
 <nav className="flex gap-1.5 overflow-x-auto rounded-[18px] bg-white p-1.5">{TABS.map(t=><button type="button" key={t} onClick={()=>setTab(t)} className={`min-w-max rounded-full px-4 py-2.5 text-xs ${tab===t?'bg-[#eee0cf]':'text-[#857a70]'}`}>{t}</button>)}</nav>
 {tab==='Today'?<><div className="grid gap-3 sm:grid-cols-4">{MEALS.map(mt=>{const m=todays.find(x=>x.mealType===mt);return <article key={mt} className="rounded-[24px] bg-white p-5"><small className="uppercase">{mt}</small><h3 className="glow-display mt-2 text-xl">{m?.title??'Not planned'}</h3><p className="mt-2 text-xs">{m?.status??'No meal record yet'}</p>{m?<button type="button" disabled={pending||m.status==='ate'} onClick={()=>ate(m)} className="mt-4 rounded-full bg-[#e8efe2] px-3 py-2 text-xs">Ate this</button>:<button type="button" onClick={()=>setTab('Recipes')} className="mt-4 text-xs underline">Plan meal</button>}</article>})}</div><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-[26px] bg-[#f3f6ec] p-5"><h2 className="glow-display text-2xl">Food Attention</h2><p className="mt-3 text-sm">Use soon · {soon.length?soon.slice(0,5).map(x=>x.name).join(' · '):'nothing confirmed'}</p><p className="mt-2 text-sm">Grocery draft · {draft.length}</p><p className="mt-2 text-sm">Needs Pantry review · {review.length}</p><p className="mt-2 text-sm">Leftovers · {activeLeftovers.length}</p></section><section className="rounded-[26px] bg-[#fff8ee] p-5"><h2 className="glow-display text-2xl">Food Compass</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><span className="rounded-xl bg-white p-3">Protein with meals</span><span className="rounded-xl bg-white p-3">Fiber + produce</span><span className="rounded-xl bg-white p-3">Enough food to recover</span><span className="rounded-xl bg-white p-3">Consistency over perfection</span></div><Link href="/wellness" className="mt-4 inline-block text-xs underline">Hydration is logged in Wellness →</Link></section></div></>:null}
 {tab==='Recipes'?<><div className="flex items-center gap-2 rounded-[22px] bg-white p-4"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search every Food-folder recipe" className="w-full bg-transparent text-sm outline-none"/></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{shown.map(r=>{const m=match(r,pantry);return <article key={r.id} className="rounded-[24px] bg-white p-4"><div className="flex justify-between"><div><h3 className="glow-display text-xl">{r.title}</h3><p className="text-xs">{r.categories.join(' · ')}</p></div><button type="button" onClick={()=>favorite(r)} aria-label={r.favorite?'Remove favorite':'Favorite'}><Heart size={17} className={r.favorite?'fill-[#b66d68] text-[#b66d68]':''}/></button></div>{r.recipeStatus==='missing_measurements'?<p className="mt-3 rounded-xl bg-[#f8eee5] p-3 text-xs">Original complete measurements were not recoverable. Glow does not invent them.</p>:<p className="mt-3 text-xs">{r.ingredients.length} ingredients · {m.have}/{m.total} confirmed in Pantry</p>}<div className="mt-4 flex gap-2"><button type="button" onClick={()=>setSelected(r)} className="text-xs underline">View</button><button type="button" onClick={()=>plan(r)} className="text-xs underline">Plan</button>{r.instructions.length?<button type="button" onClick={()=>startCook(r)} className="rounded-full bg-[#765b45] px-3 py-2 text-xs text-white">Cook</button>:null}</div></article>})}</div></>:null}
 {tab==='Pantry'?<><section className="rounded-[24px] bg-[#f8f5ec] p-5"><div className="flex gap-3"><Refrigerator/><div><h2 className="glow-display text-2xl">Master Grocery Catalog → Pantry</h2><p className="text-sm">All imported items begin as Needs review. Only you can confirm In stock, Use soon or Out.</p></div></div></section>{Object.entries(groups(pantry,x=>x.category)).map(([category,items])=><section key={category} className="rounded-[24px] bg-white p-5"><h3 className="glow-display text-xl">{category}</h3><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><div key={item.id} className="rounded-2xl bg-[#faf8f3] p-3"><b className="text-sm">{item.name}</b><p className="text-[10px] capitalize">{item.state.replace('_',' ')}</p><div className="mt-3 flex gap-1.5"><button type="button" onClick={()=>setStock(item,'in_stock')} className="rounded-full bg-[#e7efe1] px-2.5 py-1.5 text-[10px]">In stock</button><button type="button" onClick={()=>setStock(item,'use_soon')} className="rounded-full bg-[#f3ead6] px-2.5 py-1.5 text-[10px]">Use soon</button><button type="button" onClick={()=>setStock(item,'out')} className="rounded-full bg-[#f4e4df] px-2.5 py-1.5 text-[10px]">Out</button></div></div>)}</div></section>)}</>:null}
 {tab==='Groceries'?<><section className="rounded-[24px] bg-white p-5"><div className="flex justify-between"><div><h2 className="glow-display text-2xl">Groceries</h2><p className="text-sm">Out-of-stock Pantry items become drafts. Review them before Shopping Mode.</p></div><ShoppingBasket/></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={!draft.length||pending} onClick={()=>startTransition(async()=>{const r=await addAllFoodDraftGroceriesAction();setGroceries(g=>g.map(x=>x.status==='draft'?{...x,status:'listed'}:x));toast(`${r.data.length} drafts moved to shopping.`)})} className="rounded-full bg-[#78614d] px-4 py-2.5 text-xs text-white disabled:opacity-40">Add all {draft.length} drafts</button><button type="button" onClick={()=>{const n=window.prompt('Add grocery item');if(n)addGrocery(n)}} className="rounded-full border px-4 py-2.5 text-xs">+ Add item</button></div></section>{[['Draft',draft],['Shopping List',listed]].map(([title,rows])=><section key={String(title)} className="rounded-[24px] bg-white p-5"><h3 className="glow-display text-xl">{String(title)}</h3>{Object.entries(groups(rows as Grocery[],x=>x.category)).map(([category,items])=><div key={category} className="mt-4"><small className="uppercase">{category}</small>{items.map(item=><div key={item.id} className="mt-1 flex justify-between rounded-xl bg-[#faf7f2] p-3 text-sm"><span>{item.name}</span>{item.status==='listed'?<button type="button" aria-label={`Mark ${item.name} bought`} onClick={()=>bought(item)}><Check size={14}/></button>:<small>draft</small>}</div>)}</div>)}</section>)}</>:null}
 {tab==='Meal Plan'?<section className="rounded-[24px] bg-white p-5"><h2 className="glow-display text-2xl">This Week</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-7">{Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(now.getDate()+i);const k=day(d);return <div key={k} className="rounded-2xl bg-[#faf7f1] p-3"><b>{d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</b>{MEALS.map(mt=>{const m=meals.find(x=>x.mealDate===k&&x.mealType===mt);return <div key={mt} className="mt-2"><small>{mt}</small><p className="text-[10px]">{m?.title??'—'}</p></div>})}</div>})}</div><button type="button" onClick={()=>setTab('Recipes')} className="mt-4 rounded-full bg-[#80634d] px-4 py-2.5 text-xs text-white">Plan from Recipes</button></section>:null}
 {tab==='Meal Prep'?<section className="rounded-[26px] bg-[#f3f7ed] p-5"><div className="flex gap-3"><PackageCheck/><div><h2 className="glow-display text-3xl">Meal Prep Mode</h2><p className="text-sm">Prepare components with parallel hints while longer steps run.</p></div></div>{prep?.status==='active'?<div className="mt-5 rounded-[24px] bg-white p-5"><p className="text-xs">{prep.currentIndex+1} / {prep.queue.length}</p><h3 className="glow-display mt-2 text-2xl">{prepStep?.title}</h3>{prepStep?.parallelHint?<p className="mt-3 rounded-xl bg-[#eef4e8] p-3 text-sm"><b>Parallel:</b> {prepStep.parallelHint}</p>:null}<div className="mt-4 flex gap-2"><button type="button" onClick={()=>prepDone('skipped')} className="rounded-full border px-3 py-2 text-xs">Skip</button><button type="button" onClick={()=>prepDone('completed')} className="rounded-full bg-[#6c7c62] px-4 py-2 text-xs text-white">Done</button>{prepStep?<button type="button" aria-label="Read prep step aloud" onClick={()=>speak(`${prepStep.title}. ${prepStep.parallelHint??''}`)} className="rounded-full border p-2"><Mic2 size={14}/></button>:null}</div></div>:prep?.status==='completed'?<p className="mt-4 rounded-xl bg-white p-4">Meal Prep complete ✓</p>:<button type="button" onClick={startPrep} className="mt-5 rounded-full bg-[#6c7c62] px-5 py-3 text-sm text-white">Start Meal Prep</button>}</section>:null}
 {tab==='Food Studio'?<><section className="rounded-[26px] bg-white p-5"><h2 className="glow-display text-2xl">What Should I Eat?</h2><div className="mt-4 flex gap-2">{[5,15,30,60].map(n=><button type="button" key={n} onClick={()=>setTime(n)} className={`rounded-full px-3 py-2 text-xs ${time===n?'bg-[#6e7b63] text-white':'bg-[#eef2e8]'}`}>{n===60?'More':`${n} min`}</button>)}</div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{recommended.map(({r,m,minutes:rm})=><article key={r.id} className="rounded-[22px] bg-[#fffaf4] p-4"><h3 className="glow-display text-xl">{r.title}</h3><p className="text-xs">{rm?`${rm} min`:'Time not stored'} · {m.total?`${m.have}/${m.total} Pantry match`:'ingredient list unavailable'}</p><button type="button" onClick={()=>setSelected(r)} className="mt-3 text-xs underline">View recipe</button></article>)}</div></section><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-[26px] bg-white p-5"><h2 className="glow-display text-2xl">Build a Smoothie</h2><div className="mt-4 flex flex-wrap gap-2">{SMOOTHIE.map(x=><button type="button" key={x} onClick={()=>setSmoothie(smoothie.includes(x)?smoothie.filter(v=>v!==x):[...smoothie,x])} className={`rounded-full px-3 py-2 text-xs ${smoothie.includes(x)?'bg-[#6e7b63] text-white':'bg-[#f2f0e8]'}`}>{x}</button>)}</div><button type="button" onClick={()=>saveBuilder('smoothie')} className="mt-4 rounded-full bg-[#78604b] px-4 py-2.5 text-xs text-white">Save Smoothie</button></section><section className="rounded-[26px] bg-white p-5"><h2 className="glow-display text-2xl">Build a Bowl</h2><div className="mt-4 flex flex-wrap gap-2">{BOWL.map(x=><button type="button" key={x} onClick={()=>setBowl(bowl.includes(x)?bowl.filter(v=>v!==x):[...bowl,x])} className={`rounded-full px-3 py-2 text-xs ${bowl.includes(x)?'bg-[#6e7b63] text-white':'bg-[#f2f0e8]'}`}>{x}</button>)}</div><button type="button" onClick={()=>saveBuilder('bowl')} className="mt-4 rounded-full bg-[#78604b] px-4 py-2.5 text-xs text-white">Save Bowl</button></section></div><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('glow:open-conversation',{detail:{prompt:'I do not want to cook. Use my Food data to help me choose the easiest real option without judgment.'}}))} className="w-full rounded-[24px] bg-[#f7efe4] p-5 text-left"><b className="glow-display text-xl">I don’t want to cook</b></button></>:null}
 <section className="rounded-[26px] bg-white p-5"><div className="flex justify-between"><h2 className="glow-display text-2xl">Leftovers</h2><button type="button" onClick={()=>{const title=window.prompt('What did you make?');if(!title)return;const servings=Number(window.prompt('How many servings remain?','2')||0);if(servings>0)startTransition(async()=>{const r=await addFoodLeftoverAction({title,servingsRemaining:servings});if(r.data)setLeftovers(v=>[r.data as Leftover,...v])})}} className="text-xs underline">+ Save leftovers</button></div>{activeLeftovers.map(l=><div key={l.id} className="mt-2 rounded-xl bg-[#faf7f1] p-3"><b>{l.title}</b><p className="text-xs">{l.servingsRemaining} servings · {l.expiresAt?`expiry ${new Date(l.expiresAt).toLocaleDateString()}`:'freshness not tracked'}</p><button type="button" onClick={()=>startTransition(async()=>{const r=await consumeFoodLeftoverAction(l.id,1);if(r.data)setLeftovers(v=>v.map(x=>x.id===l.id?r.data as Leftover:x))})} className="mt-2 text-xs underline">Use 1 serving</button></div>)}</section>
 {selected?<div className="fixed inset-0 z-[120] overflow-y-auto bg-black/20 p-4 backdrop-blur-sm"><div className="mx-auto mt-8 max-w-3xl rounded-[30px] bg-[#fffdf8] p-6"><div className="flex justify-between"><div><h2 className="glow-display text-3xl">{selected.title}</h2><p className="text-sm">{selected.categories.join(' · ')}</p></div><button type="button" aria-label="Close recipe" onClick={()=>setSelected(null)}><X/></button></div>{selected.recipeStatus==='missing_measurements'?<p className="mt-5 rounded-2xl bg-[#f7eee6] p-4 text-sm">This title is preserved from your Food folder. Original complete measurements were not recoverable, so Glow does not invent them.</p>:<div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="glow-display text-xl">Ingredients</h3>{selected.ingredients.map((i,n)=><div key={n} className="mt-2 rounded-xl bg-white p-3 text-sm">{i.amount?<b>{i.amount} </b>:null}{i.name}{i.note?<small className="block">{i.note}</small>:null}</div>)}</div><div><h3 className="glow-display text-xl">Instructions</h3>{selected.instructions.map((s,n)=><div key={n} className="mt-2 rounded-xl bg-white p-3 text-sm">{n+1}. {s.text}</div>)}<button type="button" onClick={()=>startCook(selected)} className="mt-4 rounded-full bg-[#775b45] px-5 py-3 text-sm text-white">Start Cook Mode</button></div></div>}<div className="mt-5 flex gap-2">{['reliable','try_again','new','retired'].map(v=><button type="button" key={v} onClick={()=>startTransition(async()=>{const r=await setFoodRecipePreferenceAction({id:selected.id,rotation:v});if(r.data){const row=r.data as Recipe;setSelected(row);setRecipes(x=>x.map(y=>y.id===row.id?row:y))}})} className={`rounded-full px-3 py-2 text-xs ${selected.rotation===v?'bg-[#775f4b] text-white':'bg-[#f2eee7]'}`}>{v.replace('_',' ')}</button>)}</div></div></div>:null}
 <div className="fixed inset-x-3 bottom-3 z-40 mx-auto flex max-w-xl justify-around rounded-[22px] border border-white/80 bg-[#fffaf3]/92 p-2 shadow-xl backdrop-blur"><button type="button" onClick={()=>setTab('Food Studio')} className="flex flex-col items-center gap-1 px-3 py-2 text-[10px]"><Utensils size={16}/>Eat Next</button><button type="button" onClick={()=>{setTime(5);setTab('Food Studio')}} className="flex flex-col items-center gap-1 px-3 py-2 text-[10px]"><Clock3 size={16}/>Quick Meal</button><button type="button" onClick={()=>{const n=window.prompt('Add grocery item');if(n)addGrocery(n)}} className="flex flex-col items-center gap-1 px-3 py-2 text-[10px]"><ShoppingBasket size={16}/>Add Grocery</button><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('glow:open-conversation',{detail:{prompt:'Help me with Food right now. Use my saved recipes, confirmed Pantry, groceries, meal plan, leftovers and Calendar context. Never invent what is in stock.'}}))} className="flex flex-col items-center gap-1 px-3 py-2 text-[10px]"><Mic2 size={16}/>Ask Glow</button></div>
 </div>
}
