'use client';

import { useMemo, useState, useTransition } from 'react';
import Link from 'next/link';
import { ArrowRight, Check, ChefHat, ChevronLeft, Clock3, Heart, Mic2, PackageCheck, Pause, Play, Refrigerator, Search, ShoppingBasket, TimerReset, Utensils, X } from 'lucide-react';
import { addAllFoodDraftGroceriesAction, addFoodGroceryAction, addFoodLeftoverAction, completeFoodMealPrepAction, createFoodCustomRecipeAction, recordFoodMealPrepStepAction, recordFoodRecipeUseAction, saveFoodMealPlanAction, setFoodGroceryStatusAction, setFoodRecipePreferenceAction, startFoodMealPrepAction, updateFoodInventoryAction, useFoodLeftoverAction } from '@/app/actions/food-intelligence';

type Ingredient={name:string;amount?:string;note?:string};
type RecipeStep={text:string;seconds?:number;parallelHint?:string};
type Recipe={id:string;title:string;primaryCategory:string;categories:string[];tags:string[];recipeStatus:string;servings:string|null;prepMinutes:number|null;cookMinutes:number|null;totalMinutes:number|null;ingredients:Ingredient[];instructions:RecipeStep[];notes:string|null;favorite:boolean;rotation:string;rating:string|null;feedback:string[];useCount:number;lastUsedAt:string|null};
type Inventory={id:string;normalizedName:string;name:string;category:string;state:string;quantity:number|null;unit:string|null;minimumQuantity:number|null;expiresAt:string|null;groceryDraft:boolean;updatedAt:string};
type Grocery={id:string;normalizedName:string;name:string;category:string;quantity:number|null;unit:string|null;status:string;source:string};
type MealPlan={id:string;mealDate:string;mealType:string;recipeId:string|null;title:string;status:string;servings:number|null};
type Leftover={id:string;recipeId:string|null;title:string;servingsRemaining:number;expiresAt:string|null};
type PrepStep={id:string;title:string;seconds:number;parallelHint?:string};
type PrepRun={id:string;title:string;status:string;queue:PrepStep[];completedStepIds:string[];skippedStepIds:string[];currentIndex:number;actualSeconds:number};
type FoodEvent={id:string;title:string;occurredAt:string};
type FoodState={recipes:Recipe[];inventory:Inventory[];groceries:Grocery[];mealPlans:MealPlan[];leftovers:Leftover[];prepRuns:PrepRun[];events:FoodEvent[]};
type Tab='Today'|'Meal Plan'|'Recipes'|'Pantry'|'Groceries'|'Meal Prep'|'Smoothies'|'Food Studio';
const TABS:Tab[]=['Today','Meal Plan','Recipes','Pantry','Groceries','Meal Prep','Smoothies','Food Studio'];
const MEALS=['breakfast','lunch','dinner','snack'] as const;
const SMOOTHIE={Liquid:['Water','Almond milk','Milk'],Fruit:['Frozen fruit','Strawberries','Blueberries'],Greens:['Spinach','Kale'],'Add-ons':['Collagen powder','Honey','Vanilla protein powder','Sea moss gel']};
const BOWL={Protein:['Shrimp','Extra-firm tofu','Salmon','Butter beans'],Base:['White rice','Quinoa','Potatoes','Greens'],Vegetables:['Spinach','Bell peppers','Cucumber','Carrots'],Flavor:['Soy sauce','Miso paste','Lemon','Garlic']};
function dateKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function stamp(v:string){return new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function recipeMinutes(r:Recipe){if(r.totalMinutes!=null)return r.totalMinutes;const total=(r.prepMinutes??0)+(r.cookMinutes??0);return total>0?total:null}
function words(v:string){return v.toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>2)}
function pantryMatch(recipe:Recipe,inventory:Inventory[]){const stocked=inventory.filter(i=>i.state==='in_stock'||i.state==='use_soon');if(!recipe.ingredients.length)return{have:0,total:0,missing:[] as string[]};let have=0;const missing:string[]=[];for(const ingredient of recipe.ingredients){const iw=words(ingredient.name);const matched=stocked.some(item=>{const n=item.name.toLowerCase();return iw.some(w=>n.includes(w)||words(n).includes(w))});if(matched)have++;else missing.push(ingredient.name)}return{have,total:recipe.ingredients.length,missing}}
function mealTypeFor(hour:number):typeof MEALS[number]{if(hour<11)return'breakfast';if(hour<15)return'lunch';if(hour<20)return'dinner';return'snack'}
function groupBy<T>(items:T[],key:(item:T)=>string){return items.reduce<Record<string,T[]>>((acc,item)=>{const k=key(item);(acc[k]??=[]).push(item);return acc},{})}
function Builder({title,groups,selected,setSelected,onSave}:{title:string;groups:Record<string,string[]>;selected:string[];setSelected:(v:string[])=>void;onSave:()=>void}){return <section className="rounded-[26px] border border-[#e5e2d7] bg-white p-5"><p className="text-[10px] uppercase tracking-[.15em] text-[#7c796f]">Food Studio</p><h2 className="glow-display mt-1 text-2xl">{title}</h2><div className="mt-4 space-y-4">{Object.entries(groups).map(([group,items])=><div key={group}><p className="text-xs font-medium">{group}</p><div className="mt-2 flex flex-wrap gap-2">{items.map(x=><button type="button" key={x} onClick={()=>setSelected(selected.includes(x)?selected.filter(v=>v!==x):[...selected,x])} className={`rounded-full px-3 py-2 text-xs ${selected.includes(x)?'bg-[#6e7b63] text-white':'bg-[#f2f0e8]'}`}>{x}</button>)}</div></div>)}</div><p className="mt-4 text-xs text-[#8d857c]">Selected: {selected.length?selected.join(' · '):'none yet'}</p><button type="button" onClick={onSave} className="mt-4 rounded-full bg-[#78604b] px-4 py-2.5 text-xs text-white">Save to Recipes</button></section>}

export function FoodIntelligenceStudioV2({initial,nextEvent,foodSpendCents,foodPurchaseCount}:{initial:FoodState;nextEvent:{id:string;title:string;startAt:string}|null;foodSpendCents:number;foodPurchaseCount:number}){
 const [tab,setTab]=useState<Tab>('Today');const [recipes,setRecipes]=useState(initial.recipes);const [inventory,setInventory]=useState(initial.inventory);const [groceries,setGroceries]=useState(initial.groceries);const [mealPlans,setMealPlans]=useState(initial.mealPlans);const [leftovers,setLeftovers]=useState(initial.leftovers);const [prepRuns,setPrepRuns]=useState(initial.prepRuns);const [notice,setNotice]=useState('');const [query,setQuery]=useState('');const [selected,setSelected]=useState<Recipe|null>(null);const [cook,setCook]=useState<{recipe:Recipe;index:number}|null>(null);const [minutes,setMinutes]=useState(15);const [smoothie,setSmoothie]=useState<string[]>([]);const [bowl,setBowl]=useState<string[]>([]);const [prep,setPrep]=useState<PrepRun|null>(initial.prepRuns.find(r=>r.status==='active')??null);const [prepSeconds,setPrepSeconds]=useState(0);const [shopping,setShopping]=useState(false);const [pending,startTransition]=useTransition();
 const now=new Date();const today=dateKey(now);const mealType=mealTypeFor(now.getHours());const todaysMeals=mealPlans.filter(m=>m.mealDate===today);const reviewCount=inventory.filter(i=>i.state==='review').length;const useSoon=inventory.filter(i=>i.state==='use_soon');const out=inventory.filter(i=>i.state==='out');const draft=groceries.filter(g=>g.status==='draft');const listed=groceries.filter(g=>g.status==='listed');const activeLeftovers=leftovers.filter(l=>l.servingsRemaining>0);const availableMinutes=nextEvent?Math.max(0,Math.floor((new Date(nextEvent.startAt).getTime()-Date.now())/60000)):999;const foodSpend=(foodSpendCents/100).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});const currentPrepStep=prep?.queue[prep.currentIndex]??null;
 const recommendations=useMemo(()=>recipes.filter(r=>r.recipeStatus==='complete').map(r=>({r,match:pantryMatch(r,inventory),mins:recipeMinutes(r)})).filter(x=>x.mins==null||x.mins<=minutes||minutes>=60).sort((a,b)=>{const am=a.match.total?a.match.have/a.match.total:0;const bm=b.match.total?b.match.have/b.match.total:0;const ac=a.r.categories.some(c=>c.toLowerCase().includes(mealType))?1:0;const bc=b.r.categories.some(c=>c.toLowerCase().includes(mealType))?1:0;return(bc-ac)||(bm-am)||((a.mins??999)-(b.mins??999))}).slice(0,6),[recipes,inventory,minutes,mealType]);
 const filteredRecipes=recipes.filter(r=>!query||`${r.title} ${r.categories.join(' ')} ${r.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||a.title.localeCompare(b.title));
 function say(text:string){window.dispatchEvent(new CustomEvent('glow:speak',{detail:{text}}))}function toast(text:string){setNotice(text);window.setTimeout(()=>setNotice(''),3500)}
 function changeInventory(item:Inventory,state:'in_stock'|'out'|'use_soon'|'review'){startTransition(async()=>{const result=await updateFoodInventoryAction({id:item.id,state});if(!result.data){toast(result.error??'Could not update pantry.');return}setInventory(c=>c.map(i=>i.id===item.id?{...i,...result.data}:i));if(state==='out')toast(`${item.name} moved to the grocery draft.`)})}
 function addGrocery(name:string,category='Other'){startTransition(async()=>{const result=await addFoodGroceryAction({name,category,status:'listed'});if(result.data){const row=result.data as Grocery;setGroceries(c=>c.some(g=>g.id===row.id)?c:[...c,row]);toast(`${name} added to groceries.`)}else toast(result.error??'Could not add grocery.')})}
 function groceryDone(item:Grocery){startTransition(async()=>{const result=await setFoodGroceryStatusAction({id:item.id,status:'completed'});if(result.data){setGroceries(c=>c.filter(g=>g.id!==item.id));setInventory(c=>c.map(i=>i.normalizedName===item.normalizedName?{...i,state:'in_stock',groceryDraft:false}:i))}else toast(result.error??'Could not update grocery.')})}
 function toggleFavorite(r:Recipe){startTransition(async()=>{const result=await setFoodRecipePreferenceAction({id:r.id,favorite:!r.favorite});if(result.data)setRecipes(c=>c.map(x=>x.id===r.id?{...x,favorite:result.data.favorite}:x))})}
 function planRecipe(r:Recipe,type:typeof MEALS[number]=mealType){startTransition(async()=>{const result=await saveFoodMealPlanAction({mealDate:today,mealType:type,recipeId:r.id,title:r.title,status:'planned'});if(result.data){const row=result.data as MealPlan;setMealPlans(c=>[...c.filter(m=>!(m.mealDate===today&&m.mealType===type)),row]);toast(`${r.title} planned for ${type}.`)}})}
 function markMeal(m:MealPlan,status:'ate'|'changed'){startTransition(async()=>{const result=await saveFoodMealPlanAction({mealDate:m.mealDate,mealType:m.mealType,recipeId:m.recipeId,title:m.title,status});if(result.data){const row=result.data as MealPlan;setMealPlans(c=>c.map(x=>x.id===m.id?row:x))}})}
 function startCook(r:Recipe){if(r.recipeStatus!=='complete'||!r.instructions.length){toast('The original complete instructions are not available for this recipe yet.');return}setCook({recipe:r,index:0});say(`Starting ${r.title}. ${r.instructions[0].text}`)}
 function nextCook(){if(!cook)return;const n=cook.index+1;if(n>=cook.recipe.instructions.length){startTransition(async()=>{await recordFoodRecipeUseAction(cook.recipe.id);setRecipes(c=>c.map(r=>r.id===cook.recipe.id?{...r,useCount:r.useCount+1,lastUsedAt:new Date().toISOString()}:r));toast(`${cook.recipe.title} cooked.`);setCook(null)});return}setCook({...cook,index:n});say(cook.recipe.instructions[n].text)}
 function startPrep(){startTransition(async()=>{const result=await startFoodMealPrepAction();if(result.data){const run=result.data as PrepRun;setPrep(run);setPrepRuns(c=>[run,...c.filter(x=>x.id!==run.id)]);setTab('Meal Prep')}else toast(result.error??'Could not start Meal Prep.')})}
 function savePrepStep(status:'completed'|'skipped'){if(!prep||!currentPrepStep)return;startTransition(async()=>{const result=await recordFoodMealPrepStepAction({runId:prep.id,stepId:currentPrepStep.id,status,actualSeconds:prepSeconds});if(!result.data){toast(result.error??'Could not save prep step.');return}let run=result.data as PrepRun;setPrepSeconds(0);if(run.currentIndex>=run.queue.length){const finished=await completeFoodMealPrepAction(run.id);if(finished.data)run=finished.data as PrepRun;}setPrep(run);setPrepRuns(c=>[run,...c.filter(x=>x.id!==run.id)]);if(run.status==='completed')toast('Meal Prep complete.')})}
 function saveBuilder(kind:'smoothie'|'bowl'){const items=kind==='smoothie'?smoothie:bowl;if(!items.length){toast('Choose ingredients first.');return}const title=kind==='smoothie'?`My Smoothie · ${new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'})}`:`My Bowl · ${new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'})}`;startTransition(async()=>{const result=await createFoodCustomRecipeAction({title,primaryCategory:kind==='smoothie'?'drinks':'meal',categories:kind==='smoothie'?['Drinks & Smoothies']:['Lunch','Dinner'],tags:[kind,'created in Glow'],ingredients:items,notes:'Built from ingredients selected in Glow Food Studio.'});if(result.data){setRecipes(c=>[result.data as Recipe,...c]);toast(`${title} saved.`)}})}
 if(cook){const step=cook.recipe.instructions[cook.index];return <div className="fixed inset-0 z-[130] overflow-y-auto bg-[radial-gradient(circle_at_30%_15%,#fffdf5,#f3eadb_48%,#dfe8d8)] p-5"><div className="mx-auto max-w-2xl"><div className="flex items-center justify-between"><button type="button" onClick={()=>setCook(null)} aria-label="Close Cook Mode" className="rounded-full bg-white/70 p-3"><ChevronLeft size={18}/></button><p className="text-xs uppercase tracking-[.16em]">Cook Mode · {cook.recipe.title}</p><button type="button" onClick={()=>say(step.text)} aria-label="Read step aloud" className="rounded-full bg-white/70 p-3"><Mic2 size={17}/></button></div><div className="mt-20 text-center"><p className="text-xs text-[#9b8c7c]">{cook.index+1} / {cook.recipe.instructions.length}</p><div className="mx-auto mt-5 max-w-lg rounded-[34px] bg-white/65 p-8 shadow-xl"><ChefHat className="mx-auto text-[#a06d54]"/><h1 className="glow-display mt-4 text-3xl">{step.text}</h1>{step.parallelHint?<p className="mt-4 rounded-2xl bg-[#eef2e6] p-3 text-sm"><b>While this cooks:</b> {step.parallelHint}</p>:null}</div><button type="button" onClick={nextCook} className="mt-7 rounded-full bg-[#765b45] px-7 py-3.5 text-sm text-white">{cook.index===cook.recipe.instructions.length-1?'Finish cooking':'Next step'}</button></div></div></div>}
 return <div className="space-y-5 pb-24">{notice?<div role="status" className="fixed right-4 top-4 z-[140] max-w-xs rounded-2xl bg-[#3f3a32] px-4 py-3 text-xs text-white shadow-xl">{notice}</div>:null}
 <section className="rounded-[32px] border border-[#ece3d7] bg-[radial-gradient(circle_at_85%_10%,rgba(187,205,166,.46),transparent_28%),linear-gradient(135deg,#fffaf1,#f3eadc_58%,#e5eadc)] p-6 sm:p-8"><div className="grid gap-7 lg:grid-cols-[1.2fr_.8fr]"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#817466]">Food · Decide → Prepare → Eat → Restock → Learn</p><h1 className="glow-display mt-3 text-[44px] leading-none sm:text-[58px]">Food Right Now</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#746b61]">Nourishment, not restriction. Every recovered recipe and grocery item is preserved, while real pantry state stays separate from the source catalog.</p><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={()=>setTab('Food Studio')} className="rounded-full bg-[#84634c] px-5 py-3 text-sm text-white">Make Something</button><button type="button" onClick={()=>{setMinutes(5);setTab('Food Studio')}} className="rounded-full bg-white/75 px-5 py-3 text-sm">Quick Meal</button><button type="button" onClick={()=>setTab('Pantry')} className="rounded-full bg-white/75 px-5 py-3 text-sm">Use What I Have</button></div></div><div className="rounded-[26px] border border-white/80 bg-white/58 p-5"><p className="text-xs text-[#8a7d70]">Best next food action</p><h2 className="glow-display mt-2 text-2xl">{activeLeftovers.length?'Use a saved leftover':recommendations[0]?.r.title??'Review your pantry'}</h2><p className="mt-2 text-sm text-[#786f66]">{activeLeftovers.length?`${activeLeftovers[0].servingsRemaining} servings of ${activeLeftovers[0].title} remain.`:`${reviewCount} master-list items still need stock confirmation.`}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-2xl bg-[#fffdf8] p-3">Time before next event<br/><b>{availableMinutes>=999?'Open':`${availableMinutes} min`}</b></div><div className="rounded-2xl bg-[#fffdf8] p-3">Food spend this month<br/><b>{foodSpend}</b> · {foodPurchaseCount}</div></div></div></div></section>
 <div className="flex gap-1.5 overflow-x-auto rounded-[18px] border border-[#ece3d7] bg-white p-1.5">{TABS.map(t=><button type="button" key={t} onClick={()=>setTab(t)} className={`min-w-max rounded-full px-4 py-2.5 text-xs ${tab===t?'bg-[#efe2d1] text-[#624a39]':'text-[#857a70]'}`}>{t}</button>)}</div>
 {tab==='Today'?<div className="space-y-4"><section className="grid gap-3 sm:grid-cols-4">{MEALS.map(type=>{const m=todaysMeals.find(x=>x.mealType===type);return <article key={type} className="rounded-[24px] border border-[#eee6da] bg-white p-5"><p className="text-[10px] uppercase tracking-[.14em] text-[#9a8d7e]">{type}</p><h3 className="glow-display mt-2 text-xl">{m?.title??'Not planned'}</h3><p className="mt-2 text-xs text-[#83796f]">{m?.status??'No meal record yet'}</p>{m?<div className="mt-4 flex gap-2"><button type="button" disabled={pending||m.status==='ate'} onClick={()=>markMeal(m,'ate')} className="rounded-full bg-[#e9efe3] px-3 py-2 text-xs">Ate this</button><button type="button" onClick={()=>setTab('Recipes')} className="text-xs underline">Change</button></div>:<button type="button" onClick={()=>setTab('Recipes')} className="mt-4 text-xs underline">Plan {type}</button>}</article>})}</section><section className="grid gap-4 lg:grid-cols-2"><div className="rounded-[26px] bg-[#f5f7ef] p-5"><h2 className="glow-display text-2xl">Food Attention</h2><p className="mt-3 text-sm">Use soon · {useSoon.length?useSoon.slice(0,5).map(i=>i.name).join(' · '):'nothing confirmed'}</p><p className="mt-2 text-sm">Restock draft · {draft.length}</p><p className="mt-2 text-sm">Pantry review · {reviewCount}</p><p className="mt-2 text-sm">Leftovers · {activeLeftovers.length}</p></div><div className="rounded-[26px] bg-[#fffaf2] p-5"><h2 className="glow-display text-2xl">Nutrition Compass</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><span className="rounded-xl bg-white p-3">Protein with meals</span><span className="rounded-xl bg-white p-3">Fiber + produce</span><span className="rounded-xl bg-white p-3">Enough food to recover</span><span className="rounded-xl bg-white p-3">Consistency over perfection</span></div><Link href="/wellness" className="mt-4 inline-flex items-center gap-1 text-xs underline">Hydration lives in Wellness <ArrowRight size={12}/></Link></div></section><section className="rounded-[26px] bg-white p-5"><h2 className="glow-display text-2xl">Recent Food</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{initial.events.slice(0,8).map(e=><div key={e.id} className="flex justify-between rounded-xl bg-[#faf7f2] p-3 text-sm"><span>{e.title}</span><small>{stamp(e.occurredAt)}</small></div>)}</div></section></div>:null}
 {tab==='Food Studio'?<div className="space-y-4"><section className="rounded-[26px] bg-white p-5"><h2 className="glow-display text-2xl">What Should I Eat?</h2><div className="mt-4 flex flex-wrap gap-2">{[5,15,30,60].map(x=><button type="button" key={x} onClick={()=>setMinutes(x)} className={`rounded-full px-3 py-2 text-xs ${minutes===x?'bg-[#6d7b61] text-white':'bg-[#eef2e8]'}`}>{x===60?'More':`${x} min`}</button>)}</div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{recommendations.map(({r,match,mins})=><article key={r.id} className="rounded-[22px] bg-[#fffaf4] p-4"><div className="flex justify-between"><div><h3 className="glow-display text-xl">{r.title}</h3><p className="text-xs">{mins?`${mins} min`:'Time not stored'} · {match.total?`${match.have}/${match.total} pantry match`:'ingredient list unavailable'}</p></div><button type="button" onClick={()=>toggleFavorite(r)} aria-label={r.favorite?'Remove favorite':'Favorite recipe'}><Heart size={17} className={r.favorite?'fill-[#b96d68] text-[#b96d68]':''}/></button></div><div className="mt-3 flex gap-2"><button type="button" onClick={()=>setSelected(r)} className="text-xs underline">View</button>{r.instructions.length?<button type="button" onClick={()=>startCook(r)} className="rounded-full bg-[#765b45] px-3 py-2 text-xs text-white">Cook</button>:null}</div></article>)}</div></section><div className="grid gap-4 lg:grid-cols-2"><Builder title="Build a Smoothie" groups={SMOOTHIE} selected={smoothie} setSelected={setSmoothie} onSave={()=>saveBuilder('smoothie')}/><Builder title="Build a Bowl" groups={BOWL} selected={bowl} setSelected={setBowl} onSave={()=>saveBuilder('bowl')}/></div></div>:null}
 {tab==='Recipes'?<div className="space-y-4"><div className="flex items-center gap-2 rounded-[24px] bg-white p-4"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search every Food-folder recipe" className="w-full bg-transparent text-sm outline-none"/></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filteredRecipes.map(r=>{const match=pantryMatch(r,inventory);return <article key={r.id} className="rounded-[24px] bg-white p-4"><div className="flex justify-between"><div><h3 className="glow-display text-xl">{r.title}</h3><p className="text-xs">{r.categories.join(' · ')}</p></div><button type="button" onClick={()=>toggleFavorite(r)} aria-label={r.favorite?'Remove favorite':'Favorite recipe'}><Heart size={17} className={r.favorite?'fill-[#b96d68] text-[#b96d68]':''}/></button></div>{r.recipeStatus==='missing_measurements'?<p className="mt-3 rounded-xl bg-[#f8efe7] p-3 text-xs">Original measurements were not recoverable. Glow will not invent them.</p>:<p className="mt-3 text-xs">{r.ingredients.length} ingredients · {match.have}/{match.total} confirmed in pantry</p>}<div className="mt-4 flex gap-2"><button type="button" onClick={()=>setSelected(r)} className="text-xs underline">View</button><button type="button" onClick={()=>planRecipe(r)} className="text-xs underline">Plan</button>{r.instructions.length?<button type="button" onClick={()=>startCook(r)} className="rounded-full bg-[#775c46] px-3 py-2 text-xs text-white">Cook</button>:null}</div></article>})}</div></div>:null}
 {tab==='Pantry'?<div className="space-y-4"><section className="rounded-[24px] bg-[#faf7ef] p-5"><div className="flex gap-3"><Refrigerator/><div><h2 className="glow-display text-2xl">Master Grocery Catalog → Pantry</h2><p className="text-sm">Imported items start as Needs review. Confirm what is actually in your kitchen.</p></div></div><div className="mt-4 grid grid-cols-4 gap-2 text-center text-xs"><span>In stock<br/><b>{inventory.filter(i=>i.state==='in_stock').length}</b></span><span>Use soon<br/><b>{useSoon.length}</b></span><span>Out<br/><b>{out.length}</b></span><span>Review<br/><b>{reviewCount}</b></span></div></section>{Object.entries(groupBy(inventory,i=>i.category)).map(([category,items])=><section key={category} className="rounded-[24px] bg-white p-5"><h3 className="glow-display text-xl">{category}</h3><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><div key={item.id} className="rounded-2xl bg-[#faf8f3] p-3"><b className="text-sm">{item.name}</b><p className="text-[10px] capitalize">{item.state.replace('_',' ')}</p><div className="mt-3 flex flex-wrap gap-1.5"><button type="button" onClick={()=>changeInventory(item,'in_stock')} className="rounded-full bg-[#e8efe2] px-2.5 py-1.5 text-[10px]">In stock</button><button type="button" onClick={()=>changeInventory(item,'use_soon')} className="rounded-full bg-[#f3ead6] px-2.5 py-1.5 text-[10px]">Use soon</button><button type="button" onClick={()=>changeInventory(item,'out')} className="rounded-full bg-[#f4e5e0] px-2.5 py-1.5 text-[10px]">Out</button></div></div>)}</div></section>)}</div>:null}
 {tab==='Groceries'?<div className="space-y-4"><section className="rounded-[24px] bg-white p-5"><div className="flex justify-between"><div><h2 className="glow-display text-2xl">Groceries</h2><p className="text-sm">Draft → review → shopping.</p></div><ShoppingBasket/></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={!draft.length||pending} onClick={()=>startTransition(async()=>{const result=await addAllFoodDraftGroceriesAction();setGroceries(c=>c.map(g=>g.status==='draft'?{...g,status:'listed'}:g));toast(`${result.data.length} draft items moved to shopping.`)})} className="rounded-full bg-[#78614d] px-4 py-2.5 text-xs text-white disabled:opacity-40">Add all {draft.length} draft items</button><button type="button" onClick={()=>setShopping(v=>!v)} className="rounded-full border px-4 py-2.5 text-xs">{shopping?'Exit Shopping Mode':'Shopping Mode'}</button><button type="button" onClick={()=>{const name=window.prompt('Add grocery item');if(name)addGrocery(name)}} className="rounded-full border px-4 py-2.5 text-xs">+ Add item</button></div></section>{[['Draft',draft],['Shopping List',listed]] as [string,Grocery[]][] .map(([title,items])=><section key={title} className="rounded-[24px] bg-white p-5"><h3 className="glow-display text-xl">{shopping&&title==='Shopping List'?`${items.length} remaining`:title}</h3>{Object.entries(groupBy(items,i=>i.category)).map(([category,group])=><div key={category} className="mt-4"><p className="text-[9px] uppercase">{category}</p>{group.map(item=><div key={item.id} className="mt-1 flex justify-between rounded-xl bg-[#faf7f2] p-3 text-sm"><span>{item.name}</span>{title==='Shopping List'?<button type="button" onClick={()=>groceryDone(item)} aria-label={`Mark ${item.name} bought`}><Check size={14}/></button>:<small>draft</small>}</div>)}</div>)}</section>)}</div>:null}
 {tab==='Meal Plan'?<section className="rounded-[24px] bg-white p-5"><h2 className="glow-display text-2xl">This Week</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-7">{Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(now.getDate()+i);const key=dateKey(d);const items=mealPlans.filter(m=>m.mealDate===key);return <div key={key} className="rounded-2xl bg-[#faf7f1] p-3"><b>{d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</b>{MEALS.map(type=>{const m=items.find(x=>x.mealType===type);return <div key={type} className="mt-2"><small className="uppercase">{type}</small><p className="text-[10px]">{m?.title??'—'}</p></div>})}</div>})}</div><button type="button" onClick={()=>setTab('Recipes')} className="mt-4 rounded-full bg-[#80634d] px-4 py-2.5 text-xs text-white">Plan from Recipes</button></section>:null}
 {tab==='Meal Prep'?<section className="rounded-[26px] bg-[#f4f7ee] p-5"><div className="flex gap-3"><PackageCheck/><div><h2 className="glow-display text-3xl">Meal Prep Mode</h2><p className="text-sm">One step at a time with parallel work when it helps.</p></div></div>{prep?.status==='active'?<div className="mt-5 rounded-[24px] bg-white p-5"><p className="text-xs">{prep.currentIndex+1} / {prep.queue.length}</p><h3 className="glow-display mt-2 text-2xl">{currentPrepStep?.title}</h3>{currentPrepStep?.parallelHint?<p className="mt-3 rounded-xl bg-[#eef4e8] p-3 text-sm"><b>Parallel:</b> {currentPrepStep.parallelHint}</p>:null}{currentPrepStep?<div className="mt-4 flex gap-2"><button type="button" onClick={()=>setPrepSeconds(v=>v+60)} className="rounded-full border px-3 py-2 text-xs"><TimerReset size={13} className="inline"/> +1 min</button><button type="button" onClick={()=>savePrepStep('skipped')} className="rounded-full border px-3 py-2 text-xs">Skip</button><button type="button" onClick={()=>savePrepStep('completed')} className="rounded-full bg-[#6c7c62] px-4 py-2 text-xs text-white">Done</button><button type="button" onClick={()=>say(`${currentPrepStep.title}. ${currentPrepStep.parallelHint??''}`)} aria-label="Read Meal Prep step" className="rounded-full border p-2"><Mic2 size={14}/></button></div>:null}</div>:prep?.status==='completed'?<p className="mt-4 rounded-xl bg-white p-4">Meal Prep complete ✓</p>:<button type="button" onClick={startPrep} className="mt-5 rounded-full bg-[#6c7c62] px-5 py-3 text-sm text-white">Start Meal Prep</button>}</section>:null}
 {tab==='Smoothies'?<Builder title="Smoothie Studio" groups={SMOOTHIE} selected={smoothie} setSelected={setSmoothie} onSave={()=>saveBuilder('smoothie')}/>:null}
 {tab==='Food Studio'?<div className="grid gap-4 lg:grid-cols-2"><Builder title="Build a Smoothie" groups={SMOOTHIE} selected={smoothie} setSelected={setSmoothie} onSave={()=>saveBuilder('smoothie')}/><Builder title="Build a Bowl" groups={BOWL} selected={bowl} setSelected={setBowl} onSave={()=>saveBuilder('bowl')}/></div>:null}
 <section className="rounded-[26px] bg-white p-5"><div className="flex justify-between"><h2 className="glow-display text-2xl">Leftovers</h2><button type="button" onClick={()=>{const title=window.prompt('What did you make?');if(!title)return;const servings=Number(window.prompt('How many servings remain?','2')||0);if(servings>0)startTransition(async()=>{const result=await addFoodLeftoverAction({title,servingsRemaining:servings});if(result.data)setLeftovers(c=>[result.data as Leftover,...c])})}} className="text-xs underline">+ Save leftovers</button></div><div className="mt-3 grid gap-2 md:grid-cols-3">{activeLeftovers.map(l=><div key={l.id} className="rounded-xl bg-[#faf7f1] p-3"><b>{l.title}</b><p className="text-xs">{l.servingsRemaining} servings · {l.expiresAt?`expiry ${new Date(l.expiresAt).toLocaleDateString()}`:'freshness not tracked'}</p><button type="button" onClick={()=>startTransition(async()=>{const result=await useFoodLeftoverAction(l.id,1);if(result.data)setLeftovers(c=>c.map(x=>x.id===l.id?result.data as Leftover:x))})} className="mt-2 text-xs underline">Use 1 serving</button></div>)}</div></section>
 {selected?<div className="fixed inset-0 z-[120] overflow-y-auto bg-black/20 p-4 backdrop-blur-sm"><div className="mx-auto mt-8 max-w-3xl rounded-[30px] bg-[#fffdf8] p-6"><div className="flex justify-between"><div><h2 className="glow-display text-3xl">{selected.title}</h2><p className="text-sm">{selected.categories.join(' · ')}</p></div><button type="button" onClick={()=>setSelected(null)} aria-label="Close recipe"><X/></button></div>{selected.recipeStatus==='missing_measurements'?<p className="mt-5 rounded-2xl bg-[#f7eee6] p-4 text-sm">Original complete measurements were not preserved in the source. Glow does not reconstruct them.</p>:<div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="glow-display text-xl">Ingredients</h3>{selected.ingredients.map((i,n)=><div key={n} className="mt-2 rounded-xl bg-white p-3 text-sm">{i.amount?<b>{i.amount} </b>:null}{i.name}{i.note?<small className="block">{i.note}</small>:null}</div>)}</div><div><h3 className="glow-display text-xl">Instructions</h3>{selected.instructions.map((s,n)=><div key={n} className="mt-2 rounded-xl bg-white p-3 text-sm">{n+1}. {s.text}</div>)}<button type="button" onClick={()=>startCook(selected)} className="mt-4 rounded-full bg-[#775b45] px-5 py-3 text-sm text-white">Start Cook Mode</button></div></div>}<div className="mt-5 flex flex-wrap gap-2">{['reliable','try_again','new','retired'].map(x=><button type="button" key={x} onClick={()=>startTransition(async()=>{const result=await setFoodRecipePreferenceAction({id:selected.id,rotation:x});if(result.data){const row=result.data as Recipe;setSelected(row);setRecipes(c=>c.map(r=>r.id===row.id?row:r))}})} className={`rounded-full px-3 py-2 text-xs ${selected.rotation===x?'bg-[#7b654f] text-white':'bg-[#f2eee7]'}`}>{x.replace('_',' ')}</button>)}</div></div></div>:null}
 <div className="fixed inset-x-3 bottom-3 z-40 mx-auto flex max-w-xl justify-around rounded-[22px] border border-white/80 bg-[#fffaf3]/92 p-2 shadow-xl backdrop-blur"><button type="button" onClick={()=>setTab('Food Studio')} className="flex flex-col items-center gap-1 px-3 py-2 text-[10px]"><Utensils size={16}/>Eat Next</button><button type="button" onClick={()=>{setMinutes(5);setTab('Food Studio')}} className="flex flex-col items-center gap-1 px-3 py-2 text-[10px]"><Clock3 size={16}/>Quick Meal</button><button type="button" onClick={()=>{const name=window.prompt('Add grocery item');if(name)addGrocery(name)}} className="flex flex-col items-center gap-1 px-3 py-2 text-[10px]"><ShoppingBasket size={16}/>Add Grocery</button><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('glow:open-conversation',{detail:{prompt:'Help me with Food right now. Use my saved recipes, pantry, groceries, meal plan, leftovers and Calendar context. Do not invent what is in stock.'}}))} className="flex flex-col items-center gap-1 px-3 py-2 text-[10px]"><Mic2 size={16}/>Ask Glow</button></div>
 </div>
}
