import Link from 'next/link';
import { ArrowRight, CalendarDays, Plus } from 'lucide-react';
import { EditableRoomImage } from '@/components/media/editable-room-image';

type Project={id:string;title:string;area:string;status:string;priority:string;progress:number;nextAction:string|null;deadline:Date|null;notes:string|null;updatedAt:Date};
const pct=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));
const date=(value:Date|null)=>value?value.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'No date';
function Head({eyebrow,title,sub,action,href}:{eyebrow:string;title:string;sub:string;action?:string;href?:string}){return <header className="b6-head"><div><p className="b6-eyebrow">{eyebrow}</p><h1 className="glow-display">{title}</h1><p>{sub}</p></div>{action&&href?<Link href={href} className="b6-primary"><Plus size={11}/>{action}</Link>:null}</header>}
function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`b6-card ${className}`}>{children}</section>}
function Progress({value}:{value:number}){return <div className="b6-progress"><i style={{width:`${pct(value)}%`}}/></div>}

export function AuditedProjectsView({projects}:{projects:Project[]}){
 const active=projects.filter(p=>p.status==='active');const paused=projects.filter(p=>p.status==='paused');const completed=projects.filter(p=>p.status==='completed');const archived=projects.filter(p=>p.status==='archived');const planned=projects.filter(p=>!['active','paused','completed','archived'].includes(p.status));const now=Date.now();const deadlines=projects.filter(p=>p.deadline&&p.deadline.getTime()>=now).sort((a,b)=>(a.deadline?.getTime()??0)-(b.deadline?.getTime()??0)).slice(0,4);const counts=[['Active Projects',active.length],['On Hold',paused.length],['Completed',completed.length],['Planned',planned.length]] as const;const slices=[active.length,paused.length,completed.length,planned.length];const total=slices.reduce((a,b)=>a+b,0);let at=0;const colors=['#87606a','#b99f93','#72806b','#dfd5ca'];const donut=total?slices.map((value,index)=>{const start=at/total*100;at+=value;return`${colors[index]} ${start}% ${at/total*100}%`}).join(','):'#eee7e2 0 100%';
 return <div className="b6-root b6-audited"><Head eyebrow="1. PROJECTS" title="Projects" sub="All your projects, in one beautiful hub." action="New Project" href="#new-project"/>
  <div className="b6-metrics">{counts.map(([label,value])=><Card className="b6-metric" key={label}><strong>{value}</strong><span>{label}</span></Card>)}</div>
  <div className="b6-project-layout"><section><div className="b6-section-head"><h2>Active Projects</h2><span>{active.length} active</span></div><div className="b6-project-list">{active.length?active.slice(0,5).map((project,index)=><Link key={project.id} href={`/projects/deep-dive?projectId=${encodeURIComponent(project.id)}`} className="b6-project-row"><EditableRoomImage slot={`project:${project.id}:batch6-list-${index}`} label={`${project.title} editorial cover`} className="b6-project-thumb"/><div className="b6-project-copy"><strong>{project.title}</strong><small>{project.nextAction||project.area||'Open project details'}</small><div className="b6-project-tags"><span>{project.area||'Project'}</span><span>{project.priority}</span></div></div><div className="b6-project-pct"><b>{pct(project.progress)}%</b><Progress value={project.progress}/></div><ArrowRight size={11}/></Link>):<div className="b6-empty">No project is currently marked Active. Use Project management below to change a real project status.</div>}</div></section>
  <aside className="b6-project-aside"><Card><div className="b6-section-head"><h2>Upcoming Deadlines</h2><Link href="/calendar">View Calendar</Link></div><div className="b6-deadlines">{deadlines.length?deadlines.map(project=><Link key={project.id} href={`/projects/deep-dive?projectId=${encodeURIComponent(project.id)}`}><span><CalendarDays size={10}/></span><div><strong>{project.title}</strong><small>{project.area||'Project'}</small></div><time>{date(project.deadline)}</time></Link>):<div className="b6-empty">No future project deadlines are saved.</div>}</div></Card><Card className="b6-overview"><div className="b6-section-head"><h2>Project Overview</h2></div><div className="b6-donut" style={{background:`conic-gradient(${donut})`}}><span>{projects.length}</span></div><div className="b6-legend">{[['In Progress',active.length],['On Hold',paused.length],['Completed',completed.length],['Planned',planned.length]].map(([label,value],index)=><div key={String(label)}><i style={{background:colors[index]}}/><span>{label}</span><b>{value}</b></div>)}</div>{archived.length?<small className="b6-audit-note">{archived.length} archived project{archived.length===1?'':'s'} excluded from the status ring.</small>:null}</Card></aside></div>
  <div className="b6-quote"><div><strong>Discipline turns ideas into assets.</strong><span>Studio note</span></div><EditableRoomImage slot="batch6:projects:quote" label="soft botanical project still life" className="b6-quote-image"/></div>
 </div>
}

export function AuditedCreativeStudioView({projects}:{projects:Project[]}){
 const active=projects.filter(p=>p.status==='active').slice(0,4);const feature=active[0]??projects.find(p=>p.status!=='archived')??null;
 return <div className="b6-root b6-audited"><Head eyebrow="2. CREATIVE STUDIO" title="Creative Studio" sub="Your ideas. Your brand. Your creative world." action="New Project" href="/projects#new-project"/>
  <nav className="b6-pills b6-reference-pills" aria-label="Creative disciplines">{['Branding','Design','Content','Photography','Video','Moodboards'].map(label=><span aria-disabled="true" key={label}>{label}</span>)}</nav>
  <section className="b6-studio-hero"><div><p className="b6-eyebrow">Featured project</p><h2 className="glow-display">{feature?.title||'Creative Studio'}</h2><p>{feature?.nextAction||feature?.area||'Create a project to give this studio a live focus.'}</p><Link href={feature?`/projects/deep-dive?projectId=${encodeURIComponent(feature.id)}`:'/projects#new-project'} className="b6-primary">{feature?'Open Project':'Create Project'}</Link></div><EditableRoomImage slot="batch6:creative-studio:hero" label="warm minimal creative desk with laptop candle ceramics" className="b6-studio-hero-image"/></section>
  <section><div className="b6-section-head"><h2>Current Work</h2><Link href="/projects">View All</Link></div><div className="b6-current-work">{active.length?active.map(project=><Link key={project.id} href={`/projects/deep-dive?projectId=${encodeURIComponent(project.id)}`} className="b6-card"><strong>{project.title}</strong><small>{project.nextAction||project.area||'Open project'}</small><Progress value={project.progress}/><b>{pct(project.progress)}%</b></Link>):<div className="b6-empty">No active creative projects are saved.</div>}</div></section>
  <section><div className="b6-section-head"><h2>Inspiration Board</h2><small>Editable image slots</small></div><div className="b6-inspiration">{['rose','shell','portrait','architecture','stone','arches','botanical'].map(slot=><EditableRoomImage key={slot} slot={`batch6:studio:${slot}`} label={`${slot} inspiration image`} className="b6-inspiration-image"/>)}<Link href="/notes" className="b6-inspiration-add" aria-label="Open Notes to capture inspiration">+</Link></div></section>
 </div>
}
