import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, CalendarDays, Check, Circle, FileText, Plus } from 'lucide-react';
import { EditableRoomImage } from '@/components/media/editable-room-image';

type Task={id:string;title:string;description:string|null;status:'pending'|'in_progress'|'done'|'cancelled';priority:string;dueDate:Date|null};
type Event={id:string;title:string;description:string|null;startAt:Date;endAt:Date|null;location:string|null};
type Goal={id:string;title:string;category:string;status:string;progress:number};
type Note={id:string;title:string;content:string};

const lower=(value?:string|null)=>(value||'').toLowerCase();
const has=(value:string,words:string[])=>words.some(word=>value.includes(word));
const date=(value:Date|null)=>value?value.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'No date';
const time=(value:Date)=>value.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});
const pct=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));

function Head({eyebrow,title,sub,action,href}:{eyebrow:string;title:string;sub:string;action?:string;href?:string}){return <header className="b6-head"><div><p className="b6-eyebrow">{eyebrow}</p><h1 className="glow-display">{title}</h1><p>{sub}</p></div>{action&&href?<Link href={href} className="b6-primary"><Plus size={11}/>{action}</Link>:null}</header>}
function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`b6-card ${className}`}>{children}</section>}
function isApplication(task:Task){const text=`${lower(task.title)} ${lower(task.description)}`;return has(text,['application','apply','applied','resume','cover letter','job','career','candidate','recruiter'])}
function isInterviewEvent(event:Event){const text=`${lower(event.title)} ${lower(event.description)}`;return has(text,['interview','phone screen','screening','recruiter call','hiring'])}
function isInterviewTask(task:Task){const text=`${lower(task.title)} ${lower(task.description)}`;return has(text,['interview','phone screen','screening','recruiter','hiring'])}
function inferredStage(task:Task){const text=`${lower(task.title)} ${lower(task.description)}`;if(has(text,['rejected','declined','not moving forward']))return'Rejected';if(has(text,['offer','offer letter']))return'Offer';if(has(text,['interview','phone screen','screening']))return'Interviewing';if(has(text,['applied','submitted','application sent']))return'Applied';if(task.status==='done')return'Closed';return'Active'}
function isOffer(task:Task){return has(`${lower(task.title)} ${lower(task.description)}`,['offer','offer letter','accepted offer'])}

export function AuditedWorkView({tasks,events,goals,notes}:{tasks:Task[];events:Event[];goals:Goal[];notes:Note[]}){
 const apps=tasks.filter(isApplication);const now=Date.now();const upcoming=events.filter(isInterviewEvent).filter(e=>(e.endAt?.getTime()??e.startAt.getTime())>=now).sort((a,b)=>a.startAt.getTime()-b.startAt.getTime());const careerGoals=goals.filter(g=>g.category==='career').slice(0,5);const careerNotes=notes.filter(n=>has(`${lower(n.title)} ${lower(n.content)}`,['career','job','interview','recruiter','network','portfolio']));
 const metrics=[['Applications',apps.length,'Matched task records'],['Interviews',upcoming.length,'Upcoming calendar events'],['Offers',tasks.filter(isOffer).length,'Matched task records'],['Career Notes',careerNotes.length,'Saved notes']] as const;
 return <div className="b6-root b6-audited"><Head eyebrow="3. CAREER / WORK" title="Career & Work" sub="Your professional journey, organized." action="Add Item" href="/work/applications"/>
  <div className="b6-metrics">{metrics.map(([label,value,sub])=><Card className="b6-metric" key={label}><span>{label}</span><strong>{value}</strong><small>{sub}</small></Card>)}</div>
  <div className="b6-work-top"><Card><div className="b6-section-head"><h2>Upcoming Interviews</h2><Link href="/calendar">Calendar</Link></div><div className="b6-upcoming">{upcoming.length?upcoming.slice(0,3).map(event=><Link key={event.id} href={`/calendar?eventId=${encodeURIComponent(event.id)}&view=day`}><span><BriefcaseBusiness size={11}/></span><div><strong>{event.title}</strong><small>{date(event.startAt)} · {time(event.startAt)}{event.location?` · ${event.location}`:''}</small></div><b>Open</b></Link>):<div className="b6-empty">No upcoming interview events are saved.</div>}</div></Card><Card><div className="b6-section-head"><h2>Career Goals</h2><Link href="/goals">View Goals</Link></div><div className="b6-career-goals">{careerGoals.length?careerGoals.map(goal=><Link href="/goals" key={goal.id}><span>{goal.status==='achieved'?<Check size={9}/>:<Circle size={9}/>}</span><strong>{goal.title}</strong><b>{pct(goal.progress)}%</b></Link>):<div className="b6-empty">No career-category goals are saved yet.</div>}</div></Card></div>
  <div className="b6-work-bottom"><Card><div className="b6-section-head"><h2>Job Search Tracker</h2><Link href="/work/applications">Open applications</Link></div><div className="b6-table"><div className="b6-table-head"><span>Item</span><span>Stage</span><span>Due</span><span>Next Step</span></div>{apps.slice(0,6).map(task=><Link key={task.id} href={`/tasks?taskId=${encodeURIComponent(task.id)}&view=all`}><strong>{task.title}</strong><span>{inferredStage(task)}</span><span>{date(task.dueDate)}</span><span>{task.description||'Open task'}</span></Link>)}{!apps.length?<div className="b6-empty">No task currently matches Glow’s application/job-search classifier.</div>:null}</div><p className="b6-audit-note">Stages are inferred from your task text. Glow does not invent employers, application dates, offers, or contacts.</p></Card><section className="b6-daily-focus"><div><p>Daily Focus</p><strong className="glow-display">Focus on the next real step.<br/>Keep the record honest.</strong><small>{careerNotes.length?`${careerNotes.length} career notes available`:'Use Notes for prep, contacts, and follow-ups.'}</small></div><EditableRoomImage slot="batch6:work:focus" label="warm desk journal flowers career focus" className="b6-focus-image"/></section></div>
 </div>
}

export function AuditedApplicationsView({tasks,notes,status='active'}:{tasks:Task[];notes:Note[];status?:string}){
 const apps=tasks.filter(isApplication);const allowed=['active','applied','interviewing','offers','rejected'];const filter=allowed.includes(status)?status:'active';const filtered=apps.filter(task=>{const stage=inferredStage(task).toLowerCase();if(filter==='active')return !['rejected','offer','closed'].includes(stage);if(filter==='offers')return stage==='offer';return stage===filter});
 return <div className="b6-root b6-audited"><Head eyebrow="4. APPLICATIONS" title="Applications" sub="Track application-related tasks without inventing missing job data." action="New Application Task" href="/tasks"/>
  <nav className="b6-pills" aria-label="Application filters">{allowed.map(tab=><Link key={tab} href={`/work/applications?status=${tab}`} className={filter===tab?'active':''}>{tab[0].toUpperCase()+tab.slice(1)}</Link>)}</nav>
  <Card className="b6-application-table"><div className="b6-table b6-table-app"><div className="b6-table-head"><span>Position / item</span><span>Stage</span><span>Due</span><span>Next Step</span></div>{filtered.length?filtered.map(task=><Link key={task.id} href={`/tasks?taskId=${encodeURIComponent(task.id)}&view=all`}><strong>{task.title}</strong><span>{inferredStage(task)}</span><span>{date(task.dueDate)}</span><span>{task.description||'Open in Tasks'}</span></Link>):<div className="b6-empty">No application-related tasks match this filter.</div>}</div></Card>
  <div className="b6-app-lower"><Card className="b6-tip"><h2>Application Practice</h2><p>Tailor the resume to the actual role.</p><p>Keep employer and applied-date details in the task or note.</p><p>Use follow-up dates only when you have really set them.</p><EditableRoomImage slot="batch6:applications:tip" label="resume desk neutral still life" className="b6-tip-image"/></Card><Card><div className="b6-section-head"><h2>Career Documents & Notes</h2><Link href="/notes">Open Notes</Link></div><div className="b6-docs">{notes.slice(0,5).map(note=><Link href="/notes" key={note.id}><FileText size={11}/><span>{note.title||'Untitled note'}</span><ArrowRight size={10}/></Link>)}{!notes.length?<div className="b6-empty">No saved notes yet.</div>:null}</div></Card></div>
 </div>
}

export function AuditedInterviewsView({tasks,events,notes,view='upcoming'}:{tasks:Task[];events:Event[];notes:Note[];view?:string}){
 const all=events.filter(isInterviewEvent).sort((a,b)=>a.startAt.getTime()-b.startAt.getTime());const now=Date.now();const upcoming=all.filter(e=>(e.endAt?.getTime()??e.startAt.getTime())>=now);const past=all.filter(e=>(e.endAt?.getTime()??e.startAt.getTime())<now).reverse();const mode=view==='past'?'past':'upcoming';const shown=mode==='past'?past:upcoming;const featured=shown[0];const prep=tasks.filter(isInterviewTask).filter(t=>t.status!=='done'&&t.status!=='cancelled').slice(0,5);const interviewNotes=notes.filter(n=>has(`${lower(n.title)} ${lower(n.content)}`,['interview','career','job','question','recruiter'])).slice(0,5);
 return <div className="b6-root b6-audited"><Head eyebrow="5. INTERVIEWS" title="Interviews" sub="Prepare. Practice. Perform."/><nav className="b6-pills" aria-label="Interview views"><Link href="/work/interviews?view=upcoming" className={mode==='upcoming'?'active':''}>Upcoming</Link><Link href="/work/interviews?view=past" className={mode==='past'?'active':''}>Past</Link></nav>
  <section className="b6-interview-hero"><div><p>{featured?mode==='past'?'Past interview':'Next interview':'Interview calendar'}</p><h2 className="glow-display">{featured?.title||`No ${mode} interview saved`}</h2>{featured?<><small><CalendarDays size={10}/>{date(featured.startAt)} · {time(featured.startAt)}</small><small>{featured.location||'Location not saved'}</small><Link href={`/calendar?eventId=${encodeURIComponent(featured.id)}`} className="b6-primary">View Details</Link></>:<Link href="/calendar" className="b6-primary">Open Calendar</Link>}</div><EditableRoomImage slot="batch6:interviews:hero" label="warm editorial interview location" className="b6-interview-image"/></section>
  <div className="b6-interview-grid"><Card><h2>Open Preparation Tasks</h2><div className="b6-checklist">{prep.length?prep.map(task=><Link href={`/tasks?taskId=${encodeURIComponent(task.id)}`} key={task.id}><Circle size={10}/><span>{task.title}</span></Link>):<div className="b6-empty">No open interview-prep tasks.</div>}</div><p className="b6-audit-note">Open tasks stay visually open. Glow only shows completion when the task record is actually done.</p></Card><Card><h2>Interview Notes</h2><div className="b6-notes-list">{interviewNotes.length?interviewNotes.map(note=><Link href="/notes" key={note.id}><strong>{note.title||'Untitled note'}</strong><small>{note.content.slice(0,100)}</small></Link>):<div className="b6-empty">No interview notes saved.</div>}</div></Card></div>
  <Card className="b6-questions"><div><h2>Questions to Ask</h2><p>What does success look like in this role?</p><p>What are the next steps?</p><p>How would you describe the team?</p></div><EditableRoomImage slot="batch6:interviews:questions" label="interview journal botanical still life" className="b6-questions-image"/></Card>
 </div>
}
