import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { AppShell } from '@/components/app-shell';
import { SectionPage } from '@/components/section-page';
import { Card } from '@/components/ui/card';
import { createTimelineEventAction } from '@/app/actions/completion-v1';
import { updateTimelineEventAction } from '@/app/actions/detail-records';
import { getFitnessSessions, getHairLogs, getTimelineEvents } from '@/lib/data/completion-v1';
import { CalendarDays, Dumbbell, Scissors, Sparkles } from 'lucide-react';

export const dynamic = 'force-dynamic';
const fieldClass='w-full rounded-[12px] border border-[#F7D1D8] bg-white px-3 py-2.5 text-[12px] text-[#2B2420] outline-none focus:border-[#C9727E]';
type Story={id:string;rawId:string;title:string;category:string;occurredAt:Date;summary:string|null;source:'timeline'|'fitness'|'hair';href:string};
const dateTimeLocal=(value:Date)=>{const offset=value.getTimezoneOffset();return new Date(value.getTime()-offset*60000).toISOString().slice(0,16);};

export default async function TimelinePage({ searchParams }: { searchParams: Promise<{ eventId?: string }> }){
  const session=await auth();
  if(!session?.user?.id) redirect('/sign-in');
  const [events,fitness,hair,params]=await Promise.all([getTimelineEvents(session.user.id),getFitnessSessions(session.user.id),getHairLogs(session.user.id),searchParams]);
  const selected=params.eventId?events.find((event)=>event.id===params.eventId)??null:null;
  const story:Story[]=[
    ...events.map(e=>({id:`t-${e.id}`,rawId:e.id,title:e.title,category:e.category,occurredAt:e.occurredAt,summary:e.summary,source:'timeline' as const,href:`/timeline?eventId=${encodeURIComponent(e.id)}`})),
    ...fitness.map(e=>({id:`f-${e.id}`,rawId:e.id,title:`${e.workoutType} workout`,category:'Fitness',occurredAt:e.occurredAt,summary:e.notes||`${e.durationMinutes??0} minutes`,source:'fitness' as const,href:`/fitness?sessionId=${encodeURIComponent(e.id)}`})),
    ...hair.map(e=>({id:`h-${e.id}`,rawId:e.id,title:e.style?`${e.eventType}: ${e.style}`:e.eventType,category:'Hair',occurredAt:e.occurredAt,summary:e.notes,source:'hair' as const,href:`/hair?logId=${encodeURIComponent(e.id)}`})),
  ].sort((a,b)=>b.occurredAt.getTime()-a.occurredAt.getTime());
  const years=new Map<number,Story[]>();story.forEach(item=>years.set(item.occurredAt.getFullYear(),[...(years.get(item.occurredAt.getFullYear())??[]),item]));
  const upcoming=story.filter(item=>item.occurredAt.getTime()>Date.now()).slice(0,4);

  return <AppShell><SectionPage eyebrow="Timeline" title="Timeline" description="Your life, beautifully mapped. Every moment shapes your story."><div className="space-y-4">
    {params.eventId&&!selected?<div role="status" className="rounded-[14px] border border-[#F7D1D8] bg-[#F7EEED] px-4 py-3 text-[11px] text-[#7B535C]">That saved timeline event is no longer available.</div>:null}
    {selected?<Card className="border-[#C9727E]"><div className="flex items-start justify-between gap-3"><div><p className="glow-eyebrow">Selected timeline event</p><h2 className="glow-display mt-1 text-[22px] text-[#2B2420]">{selected.title}</h2></div><Link href="/timeline" className="text-[10px] text-[#C9727E]">Close</Link></div><form action={updateTimelineEventAction.bind(null,selected.id)} className="mt-4 grid gap-2 sm:grid-cols-2"><input name="title" required defaultValue={selected.title} className={fieldClass}/><input name="category" required defaultValue={selected.category} className={fieldClass}/><input name="occurredAt" type="datetime-local" required defaultValue={dateTimeLocal(selected.occurredAt)} className={fieldClass}/><input name="relatedEntityType" defaultValue={selected.relatedEntityType??''} placeholder="Related type" className={fieldClass}/><input name="relatedEntityId" defaultValue={selected.relatedEntityId??''} placeholder="Related record ID" className={fieldClass}/><textarea name="summary" rows={3} defaultValue={selected.summary??''} placeholder="What should you remember?" className={`${fieldClass} sm:col-span-2`}/><button type="submit" className="w-fit rounded-full bg-[#C9727E] px-4 py-2.5 text-[11px] text-white">Save timeline event</button></form></Card>:null}
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-[10.5px] text-[#8A8078]">{story.length} saved and connected moments</p><details className="relative"><summary className="list-none rounded-full bg-[#D86F83] px-4 py-2.5 text-[11px] font-medium text-white">+ Add Event</summary><form action={createTimelineEventAction} className="absolute right-0 z-20 mt-2 w-[min(360px,82vw)] space-y-2 rounded-[16px] border border-[#F7D1D8] bg-white p-4 shadow-xl"><input name="title" required placeholder="What happened?" className={fieldClass}/><input name="category" required placeholder="Category" className={fieldClass}/><input name="occurredAt" required type="datetime-local" className={fieldClass}/><textarea name="summary" rows={4} placeholder="What should you remember?" className={fieldClass}/><button type="submit" className="w-full rounded-full bg-[#2B2420] px-4 py-2.5 text-[11px] text-white">Add to Timeline</button></form></details></div>
    <Card className="overflow-hidden p-0"><div className="p-5 sm:p-7">{story.length===0?<p className="py-10 text-center text-[12px] text-[#9A9088]">Your timeline is ready for its first moment.</p>:[...years.entries()].sort((a,b)=>b[0]-a[0]).map(([year,items])=><section key={year} className="grid gap-4 border-b border-[#F7EEED] py-5 last:border-0 lg:grid-cols-[90px_1fr]"><p className="glow-display text-[22px] text-[#C9727E]">{year}</p><div className="relative space-y-3 border-l border-[#F7D1D8] pl-6">{items.map((item,index)=>{const Icon=item.source==='fitness'?Dumbbell:item.source==='hair'?Scissors:Sparkles;const isSelected=item.source==='timeline'&&item.rawId===params.eventId;return <Link href={item.href} key={item.id} className={`relative grid gap-3 rounded-[14px] border bg-[#FFFEFD] p-4 transition hover:bg-[#F7EEED] sm:grid-cols-[90px_1fr] ${isSelected?'border-[#C9727E]':'border-[#F7D1D8]'}`}><span className="absolute -left-[31px] top-6 h-3 w-3 rounded-full border-2 border-white bg-[#D86F83]"/><div className={`flex h-[72px] items-center justify-center rounded-[10px] ${index%2?'bg-[#FAE6E7]':'bg-[#F7EEED]'}`}><Icon size={22} className="text-[#B68D80]"/></div><div><div className="flex flex-wrap items-center justify-between gap-2"><p className="glow-display text-[15px] text-[#2B2420]">{item.title}</p><span className="text-[10px] text-[#B5ACA5]">{item.occurredAt.toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span></div><p className="mt-1 text-[9.5px] uppercase tracking-[.1em] text-[#C9727E]">{item.category}</p>{item.summary?<p className="mt-2 line-clamp-2 text-[11px] leading-4 text-[#8A8078]">{item.summary}</p>:null}</div></Link>})}</div></section>)}</div></Card>
    <div className="grid gap-4 lg:grid-cols-3"><Card><div className="flex items-center gap-2"><CalendarDays size={14} className="text-[#C9727E]"/><h2 className="glow-display text-[18px]">Upcoming Events</h2></div><div className="mt-4 space-y-3">{upcoming.length?upcoming.map(item=><Link href={item.href} key={item.id} className="flex gap-3 rounded-lg px-1 py-1 text-[11px] hover:bg-[#F7EEED]"><span className="text-[#C9727E]">{item.occurredAt.toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span><span>{item.title}</span></Link>):<p className="text-[11px] text-[#9A9088]">No future events yet.</p>}</div></Card><Card><h2 className="glow-display text-[18px]">Major Milestones</h2><p className="mt-4 text-[11.5px] leading-5 text-[#8A8078]">{events.length} saved timeline milestone{events.length===1?'':'s'}.</p><p className="mt-2 text-[11px] text-[#9A9088]">Fitness and Hair add context automatically without duplicating ownership.</p></Card><Card><h2 className="glow-display text-[18px]">Memory Highlights</h2><div className="mt-4 grid grid-cols-3 gap-2">{story.slice(0,6).map((item,index)=><Link href={item.href} key={item.id} title={item.title} className={`aspect-square rounded-[10px] ${index%2?'bg-[#FAE6E7]':'bg-[#F7EEED]'}`}/>)}</div></Card></div>
    <Card className="grid gap-4 bg-[linear-gradient(90deg,#FFF,#F7EEED)] lg:grid-cols-[160px_1fr_auto] lg:items-center"><div className="flex items-center gap-2"><Sparkles size={14} className="text-[#C9727E]"/><span className="glow-display text-[18px]">Glow Insight</span></div><p className="glow-display text-[17px] italic text-[#4A4440]">Your story is not a list of dates. It is a pattern of growth, rituals, and meaningful change.</p><span className="text-[10px] text-[#9A9088]">{story.length} moments</span></Card>
  </div></SectionPage></AppShell>;
}
