import Link from 'next/link';
import { AppShell } from '@/components/app-shell';
import { BrainCircuit, CalendarDays, CheckCircle2, Circle, FolderKanban, NotebookPen, PiggyBank, Sparkles, Target, UserRound } from 'lucide-react';

const pill='rounded-[18px] border border-[#eee5e1] bg-white p-5 shadow-[0_12px_32px_rgba(67,48,42,.05)]';
const row='grid min-h-[48px] grid-cols-[22px_1fr] items-center gap-3 border-b border-[#f0e8e5] text-[11px] last:border-b-0';

export default function SecondBrainPage(){
 return <AppShell><div className="mx-auto max-w-[1240px] space-y-5 pb-24">
  <header className="overflow-hidden rounded-[30px] border border-[#eadfdb] bg-[linear-gradient(135deg,#fff9f8,#f5e9e7)] p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white shadow-sm"><BrainCircuit className="text-[#b95e71]"/></span><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#b95e71]">Your old template, rebuilt as an operating system</p><h1 className="mt-1 font-serif text-[38px] sm:text-[52px]">Second Brain</h1><p className="mt-2 max-w-3xl text-[12px] leading-6 text-[#766c66]">The screenshots work best as a single capture-and-review layer. Glow OS keeps the original logic, but routes each item into the correct live system so you do not maintain the same information twice.</p></div></div></header>

  <section className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div className={pill}><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.16em] text-[#a4938c]">Daily operating page</p><h2 className="mt-1 font-serif text-[26px]">Today • Focus • Anchors</h2></div><CalendarDays className="text-[#b95e71]"/></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Anchor title="Body" items={['Meds / essentials','Water','Food / smoothie','Movement']}/><Anchor title="Mind" items={['Brain dump','Plan day','Learn / note','Protect focus']}/><Anchor title="Soul" items={['Something I enjoy','Training / practice','Subliminals / reflection','Plan with intention']}/></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Link href="/today" className="rounded-full bg-[#c86679] px-4 py-3 text-center text-[11px] font-medium text-white">Open Today</Link><Link href="/tasks" className="rounded-full border border-[#eadfdb] px-4 py-3 text-center text-[11px]">Task&apos;n To-Do&apos;s</Link><Link href="/notes" className="rounded-full border border-[#eadfdb] px-4 py-3 text-center text-[11px]">Brain Dump</Link></div></div>
  <div className={pill}><div className="flex items-center gap-2"><Sparkles size={16} className="text-[#b95e71]"/><h2 className="font-serif text-[22px]">Top 3 Non-negotiables</h2></div><div className="mt-4">{[1,2,3].map(n=><div key={n} className={row}><Circle size={17} className="text-[#c9bbb4]"/><span>Choose priority {n} in Tasks or Today</span></div>)}</div><Link href="/tasks" className="mt-4 inline-flex text-[10px] font-medium text-[#b95e71]">Set today&apos;s top three →</Link></div></section>

  <section className="grid gap-4 lg:grid-cols-2"><div className={pill}><div className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[#b95e71]"/><h2 className="font-serif text-[22px]">Actionable plan</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] border-collapse text-left text-[10px]"><thead><tr className="border-y border-[#eee5e1]"><th className="p-3">Task</th><th className="p-3">How To Steps</th><th className="p-3">When</th><th className="p-3">Add to Calendar</th></tr></thead><tbody>{[1,2,3].map(n=><tr key={n} className="border-b border-[#f1eae7]"><td className="p-4 text-[#9b8c85]">Task {n}</td><td className="p-4 text-[#9b8c85]">Break into steps</td><td className="p-4 text-[#9b8c85]">Schedule</td><td className="p-4"><Link href="/calendar" className="text-[#b95e71]">Open Calendar</Link></td></tr>)}</tbody></table></div></div>
  <div className={pill}><div className="flex items-center gap-2"><UserRound size={16} className="text-[#b95e71]"/><h2 className="font-serif text-[22px]">Contact + conversation prep</h2></div><div className="mt-4 grid grid-cols-4 gap-px overflow-hidden rounded-[14px] border border-[#eee5e1] bg-[#eee5e1] text-[10px]"><Cell t="Who"/><Cell t="Why"/><Cell t="How"/><Cell t="Contact info"/><Cell t="Person"/><Cell t="Purpose"/><Cell t="Call / text / email"/><Cell t="What to say"/></div><p className="mt-4 text-[10px] leading-5 text-[#847871]">Use this before calls, interviews, doctor follow-ups or difficult conversations. Save the actual note in Notes so it is searchable.</p><Link href="/notes" className="mt-2 inline-flex text-[10px] text-[#b95e71]">Open Notes →</Link></div></section>

  <section className={pill}><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.16em] text-[#a4938c]">Weekly reset layer</p><h2 className="mt-1 font-serif text-[26px]">Weekly Focus + Top 3 Goals</h2></div><Target className="text-[#b95e71]"/></div><div className="mt-5 grid gap-4 md:grid-cols-4"><Mini title="Weekly Focus" body="One sentence that defines the week."/><Mini title="Top 3 Goals" body="Three outcomes, not a giant task list."/><Mini title="Appointments" body="Calendar is the single source of truth."/><Mini title="Weekly Task Bank" body="Tasks that can be pulled into open time."/></div><div className="mt-4 flex flex-wrap gap-2"><Link href="/planning" className="rounded-full bg-[#c86679] px-4 py-2.5 text-[10px] text-white">Weekly Planning</Link><Link href="/calendar" className="rounded-full border border-[#eadfdb] px-4 py-2.5 text-[10px]">Appointments</Link><Link href="/tasks" className="rounded-full border border-[#eadfdb] px-4 py-2.5 text-[10px]">Task Bank</Link></div></section>

  <section className="grid gap-4 lg:grid-cols-3"><div className={pill}><div className="flex items-center gap-2"><FolderKanban size={16} className="text-[#b95e71]"/><h2 className="font-serif text-[22px]">Projects</h2></div><p className="mt-3 text-[10px] leading-5 text-[#80746e]">The screenshot columns Project / ETA / Info / Notes become the Projects room. Keep project status there, then pull only next actions into Tasks.</p><Link href="/projects" className="mt-4 inline-flex text-[10px] text-[#b95e71]">Open Projects →</Link></div><div className={pill}><div className="flex items-center gap-2"><PiggyBank size={16} className="text-[#b95e71]"/><h2 className="font-serif text-[22px]">Budget</h2></div><div className="mt-4 space-y-2 text-[10px]"><Budget name="Needs" pct="50%"/><Budget name="Savings / Emergency" pct="20%"/><Budget name="Personal / Fun" pct="20%"/><Budget name="Long-term Goals" pct="10%"/></div><Link href="/finance" className="mt-4 inline-flex text-[10px] text-[#b95e71]">Open Money →</Link></div><div className={pill}><div className="flex items-center gap-2"><NotebookPen size={16} className="text-[#b95e71]"/><h2 className="font-serif text-[22px]">Weekly Reflection</h2></div><div className="mt-4 space-y-3 text-[10px] text-[#80746e]"><p>What moved forward?</p><p>What felt harder than expected?</p><p>What should be simplified next week?</p><p>What deserves more room?</p></div><Link href="/briefings/evening" className="mt-4 inline-flex text-[10px] text-[#b95e71]">Reflect in Glow →</Link></div></section>
 </div></AppShell>;
}
function Anchor({title,items}:{title:string;items:string[]}){return <div className="rounded-[16px] border border-[#eee5e1] bg-[#fffdfc] p-4"><h3 className="font-serif text-[18px]">{title}</h3><div className="mt-3 space-y-2">{items.map(x=><div key={x} className="flex items-center gap-2 text-[10px]"><Circle size={13} className="text-[#c8b9b3]"/>{x}</div>)}</div></div>}
function Cell({t}:{t:string}){return <div className="min-h-[56px] bg-white p-3">{t}</div>}
function Mini({title,body}:{title:string;body:string}){return <div className="rounded-[16px] border border-[#eee5e1] bg-[#fffdfc] p-4"><h3 className="text-[11px] font-semibold">{title}</h3><p className="mt-2 text-[9px] leading-4 text-[#8a7e77]">{body}</p></div>}
function Budget({name,pct}:{name:string;pct:string}){return <div className="flex items-center justify-between rounded-xl bg-[#faf5f3] px-3 py-2.5"><span>{name}</span><b>{pct}</b></div>}
