import { auth } from '@/auth';
import { redirect } from 'next/navigation';
import { desc, eq } from 'drizzle-orm';
import { AppShell } from '@/components/app-shell';
import { getTasksByUser } from '@/lib/data/tasks';
import { getActiveFocusSession } from '@/lib/intelligence/adaptive-os';
import { finishFocusSessionFormAction, startFocusSessionAction } from '@/app/actions/adaptive-os';
import { db } from '@/db';
import { focusSessions } from '@/db/schema/adaptive-os';
import { EditableRoomImage } from '@/components/media/editable-room-image';
import { FocusCountdown } from '@/components/batch8/focus-countdown';
import { Check, Circle, Clock3, Play, Square } from 'lucide-react';

export const dynamic='force-dynamic';
const FOCUS_PHOTO='https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1500&q=88';
function formatMinutes(minutes:number){if(minutes<60)return`${minutes}m`;const h=Math.floor(minutes/60);const r=minutes%60;return r?`${h}h ${r}m`:`${h}h`}

export default async function FocusPage({searchParams}:{searchParams?:Promise<{task?:string}>}){
 const session=await auth();if(!session?.user?.id)redirect('/sign-in');const userId=session.user.id;const requestedTaskId=(await searchParams)?.task??null;
 let active=null;let history:(typeof focusSessions.$inferSelect)[]=[];try{[active,history]=await Promise.all([getActiveFocusSession(userId),db.select().from(focusSessions).where(eq(focusSessions.userId,userId)).orderBy(desc(focusSessions.startedAt)).limit(24)])}catch{return <AppShell><div className="b8-focus-page rounded-[8px] border border-[#eee5e1] bg-white p-5"><p className="text-[11px] font-semibold">Focus Sessions need intelligence activation.</p><a href="/settings/intelligence" className="mt-3 inline-block text-[9px] text-[#8e495a]">Activate intelligence →</a></div></AppShell>}
 const openTasks=(await getTasksByUser(userId)).filter(t=>t.status!=='done'&&t.status!=='cancelled');const requestedTask=requestedTaskId?openTasks.find(t=>t.id===requestedTaskId)??null:null;const tasks=(requestedTask?[requestedTask,...openTasks.filter(t=>t.id!==requestedTask.id)]:openTasks).slice(0,4);const finished=history.filter(x=>x.endedAt);const totalMinutes=finished.reduce((s,x)=>s+(x.actualMinutes??0),0);const sevenDaysAgo=new Date();sevenDaysAgo.setDate(sevenDaysAgo.getDate()-7);const weekly=finished.filter(x=>x.startedAt>=sevenDaysAgo);const weeklyMinutes=weekly.reduce((s,x)=>s+(x.actualMinutes??0),0);const planned=active?.plannedMinutes??25;
 return <AppShell><div className="b8-focus-page space-y-3">
  <header className="flex items-start justify-between gap-3"><div><p className="b8-eyebrow">5. FOCUS MODE</p><h1>Focus Mode</h1><p className="mt-1 text-[10px] text-[#8A8078]">Eliminate distractions. Get deep work done.</p></div>{active?<form action={finishFocusSessionFormAction.bind(null,active.id)}><button name="outcome" value="stopped" className="b8-soft-btn">End Focus</button></form>:null}</header>
  <section className="relative h-[235px] overflow-hidden rounded-[8px] border border-[#e7ded8]"><EditableRoomImage slot="batch8:focus:hero" label="Focus room" fallbackUrl={FOCUS_PHOTO} className="absolute inset-0 h-full"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(61,37,45,.42),rgba(61,37,45,.18))]"/><div className="absolute inset-0 flex flex-col items-center justify-center text-white"><span className="rounded-full border border-white/30 bg-white/15 px-3 py-1 text-[8px] backdrop-blur">Deep Focus</span><FocusCountdown plannedMinutes={planned} startedAt={active?.startedAt.toISOString()??null}/>{active?<form action={finishFocusSessionFormAction.bind(null,active.id)} className="mt-3"><button name="outcome" value="completed" className="rounded-full border border-white/50 bg-[#7f3850] px-6 py-2 text-[9px]"><Check size={11} className="mr-1 inline"/>Complete</button></form>:tasks[0]?<form action={startFocusSessionAction.bind(null,'task',tasks[0].id,tasks[0].title,25)} className="mt-3"><button className="rounded-full border border-white/50 bg-[#7f3850] px-6 py-2 text-[9px]"><Play size={11} className="mr-1 inline"/>Start</button></form>:<a href="/tasks" className="mt-3 rounded-full border border-white/50 bg-[#7f3850] px-6 py-2 text-[9px]">Choose a task</a>}<div className="mt-4 flex gap-5 text-[7px] text-white/75"><span><Clock3 size={10} className="mr-1 inline"/>Pomodoro</span><span>⌁ No Notifications</span><span>◌ Do Not Disturb</span></div></div></section>
  <div className="grid gap-3 lg:grid-cols-[1.15fr_.85fr]">
   <section className="rounded-[8px] border border-[#eee5e1] bg-white p-3"><h2 className="font-serif text-[13px]">Today’s Focus Goals</h2><div className="mt-3 grid gap-2">{tasks.length?tasks.map((t,i)=><div key={t.id} className="flex items-center justify-between text-[9px]"><a href={`/tasks?taskId=${encodeURIComponent(t.id)}`} className="flex items-center gap-2">{i===0?<Check size={10} className="text-[#7b554f]"/>:<Circle size={10}/>}<span>{t.title}</span></a>{!active?<form action={startFocusSessionAction.bind(null,'task',t.id,t.title,25)}><button className="text-[8px] text-[#8e495a]">Focus</button></form>:null}</div>):<p className="text-[9px] text-[#9A9088]">No open tasks. Add a focus goal in Tasks.</p>}</div></section>
   <section className="rounded-[8px] border border-[#eee5e1] bg-white p-3"><h2 className="font-serif text-[13px]">Focus Stats</h2><div className="mt-3 grid gap-2 text-[9px]"><p className="flex justify-between"><span>Focus Sessions</span><strong>{finished.length}</strong></p><p className="flex justify-between"><span>Focus Time</span><strong>{formatMinutes(totalMinutes)}</strong></p><p className="flex justify-between"><span>This Week</span><strong>{formatMinutes(weeklyMinutes)}</strong></p><p className="flex justify-between"><span>Recent streak</span><strong>{weekly.length} sessions</strong></p></div><div className="mt-3 flex h-12 items-end gap-1">{finished.slice(0,8).reverse().map((x,i)=><i key={x.id} className="flex-1 rounded-t bg-[#d7bcc7]" style={{height:`${Math.max(12,Math.min(100,(x.actualMinutes??0)*2))}%`}} aria-label={`Session ${i+1}`}/>)}</div></section>
  </div>
  {active?<section className="rounded-[8px] border border-[#eadfda] bg-[#fbf7f5] p-3"><p className="b8-eyebrow">Active now</p><p className="mt-1 font-serif text-[16px]">{active.title}</p><form action={finishFocusSessionFormAction.bind(null,active.id)} className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><textarea name="notes" rows={2} placeholder="What did you accomplish?" className="rounded-[7px] border border-[#eee5e1] bg-white p-2 text-[9px] outline-none"/><div className="flex gap-2"><button name="outcome" value="completed" className="b8-primary"><Check size={10}/>Complete</button><button name="outcome" value="stopped" className="b8-soft-btn"><Square size={10}/>Stop</button></div></form></section>:null}
  <section className="grid min-h-[95px] grid-cols-[1fr_180px] overflow-hidden rounded-[8px] border border-[#eee5e1] bg-[linear-gradient(90deg,#fff,#f8efeb)]"><blockquote className="self-center px-4 font-serif text-[10px] leading-5">Discipline is choosing between what you want now<br/>and what you want most.<br/><span className="text-[8px] text-[#9A9088]">— Unknown</span></blockquote><EditableRoomImage slot="batch8:focus:quote" label="Focus candles" fallbackUrl={FOCUS_PHOTO} className="h-[95px]"/></section>
 </div></AppShell>
}
