'use client';

import Link from 'next/link';
import { useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { GitBranch, Link2, RefreshCw, Sparkles, Trash2 } from 'lucide-react';
import { connectBrainItemsAction, disconnectBrainItemsAction } from '@/app/actions/second-brain';

type Item={id:string;title:string;type:string;updatedAt?:Date;createdAt?:Date};
type Relation={id:string;fromType:string;fromId:string;toType:string;toId:string;relation:string;reason:string|null};
type Props={items:Item[];relationships:Relation[];weeklyCounts:{decisions:number;ideas:number;openLoops:number;closedLoops:number;workspaces:number};monthTitles:string[];replayTitles:string[]};
const RELATIONS=['supports','part_of','depends_on','related_to','created_by','blocked_by','inspired_by'] as const;

export function SecondBrainConnectionsSynthesis({items,relationships,weeklyCounts,monthTitles,replayTitles}:Props){
 const router=useRouter();
 const [pending,startTransition]=useTransition();
 const [from,setFrom]=useState(items[0]?`${items[0].type}:${items[0].id}`:'');
 const [to,setTo]=useState(items[1]?`${items[1].type}:${items[1].id}`:'');
 const [relation,setRelation]=useState<(typeof RELATIONS)[number]>('related_to');
 const [reason,setReason]=useState('');
 const [notice,setNotice]=useState('');
 const thisMonth=new Date().toLocaleDateString('en-US',{month:'long'});
 const weeklyText=useMemo(()=>weeklyCounts.decisions||weeklyCounts.ideas||weeklyCounts.openLoops||weeklyCounts.closedLoops?`${weeklyCounts.decisions} decision${weeklyCounts.decisions===1?'':'s'} created this week · ${weeklyCounts.ideas} idea${weeklyCounts.ideas===1?'':'s'} captured · ${weeklyCounts.closedLoops} loop${weeklyCounts.closedLoops===1?'':'s'} closed · ${weeklyCounts.openLoops} currently open.`:'Your Second Brain is still building enough activity for a useful weekly synthesis.',[weeklyCounts]);
 const monthlyText=useMemo(()=>monthTitles.length?`Most active recent records this month: ${monthTitles.slice(0,3).join(' · ')}.`:'No Second Brain records have changed this month yet.',[monthTitles]);
 function connect(){if(!from||!to||from===to)return setNotice('Choose two different items.');const [fromType,...fromIdParts]=from.split(':');const [toType,...toIdParts]=to.split(':');startTransition(async()=>{const result=await connectBrainItemsAction({fromType,fromId:fromIdParts.join(':'),toType,toId:toIdParts.join(':'),relation,reason:reason.trim()||undefined});if(result.error)return setNotice(result.error);setNotice('Connection saved.');setReason('');router.refresh()})}
 function remove(id:string){startTransition(async()=>{const result=await disconnectBrainItemsAction(id);if(result.error)return setNotice(result.error);setNotice('Connection removed.');router.refresh()})}
 return <div className="mx-auto max-w-[1420px] space-y-4 pb-10">
  {notice?<p aria-live="polite" className="rounded-full border border-[#e6ddd5] bg-[#fffdfa] px-4 py-2 text-center text-[9px]">{notice}</p>:null}
  <section className="grid gap-4 xl:grid-cols-[1.05fr_.95fr]">
   <div className="rounded-[24px] border border-[#e7dfd7] bg-[#fffdfa] p-5"><div className="flex items-center gap-2"><Link2 size={15}/><div><p className="text-[8px] font-semibold uppercase tracking-[.15em] text-[#8d8178]">Connect These</p><h2 className="font-serif text-[25px]">Make the relationship explicit</h2></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><SelectItem value={from} setValue={setFrom} items={items}/><SelectItem value={to} setValue={setTo} items={items}/></div><div className="mt-2 grid gap-2 sm:grid-cols-[.7fr_1.3fr]"><select value={relation} onChange={e=>setRelation(e.target.value as typeof relation)} className="rounded-xl border border-[#e2dad2] bg-white px-3 py-2.5 text-[9px]">{RELATIONS.map(r=><option key={r} value={r}>{r.replace('_',' ')}</option>)}</select><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why are these connected?" className="rounded-xl border border-[#e2dad2] px-3 py-2.5 text-[9px]"/></div><button onClick={connect} disabled={pending||items.length<2||from===to} className="mt-3 rounded-full bg-[#57504b] px-4 py-2.5 text-[9px] text-white disabled:opacity-40">Save Connection</button><p className="mt-3 text-[8px] leading-4 text-[#958980]">Every edge in the Brain Map comes from a stored relationship. Connections are reversible and validated against real records before they are saved.</p>
   {relationships.length?<div className="mt-4 space-y-2">{relationships.slice(0,8).map(r=><div key={r.id} className="flex items-start justify-between gap-3 rounded-[14px] border border-[#e6ded6] bg-[#faf7f3] p-3"><p className="min-w-0 text-[8.5px] leading-4"><span className="font-semibold capitalize">{r.fromType}</span> → {r.relation.replace('_',' ')} → <span className="font-semibold capitalize">{r.toType}</span>{r.reason?<span className="block text-[#8b8178]">Why: {r.reason}</span>:null}</p><button onClick={()=>remove(r.id)} disabled={pending} aria-label="Remove connection" className="shrink-0 rounded-full border border-[#e2d8d0] p-2 text-[#8a716d] disabled:opacity-40"><Trash2 size={11}/></button></div>)}</div>:null}
   </div>
   <div className="rounded-[24px] border border-[#e7dfd7] bg-[linear-gradient(135deg,#fffdf8,#f0eaf1)] p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] font-semibold uppercase tracking-[.15em] text-[#897a86]">Spatial Brain</p><h2 className="font-serif text-[25px]">ACTION ↔ WORLD</h2></div><GitBranch size={16}/></div><p className="mt-3 text-[9.5px] leading-5 text-[#776f76]">Second Brain is the fast list-and-thinking surface. Open the cinematic Brain to explore the immersive intelligence environment without losing the ACTION MODE underneath.</p><Link href="/brain" className="mt-4 inline-flex rounded-full bg-[#766575] px-4 py-2.5 text-[9px] text-white">Open Spatial Brain</Link><p className="mt-3 text-[8px] text-[#938893]">Stored relationship edges: {relationships.length}</p></div>
  </section>
  <section className="grid gap-4 lg:grid-cols-3"><Synthesis title="Your Mind This Week" eyebrow="WEEKLY BRAIN REVIEW" body={weeklyText} foot={`${weeklyCounts.workspaces} thinking workspace${weeklyCounts.workspaces===1?'':'s'} created this week.`}/><Synthesis title={`${thisMonth} Brain Report`} eyebrow="MONTHLY SYNTHESIS" body={monthlyText} foot="This summary is deterministic from records changed during the current month, not an invented AI narrative."/><Synthesis title="Replay the Last 30 Days" eyebrow="RECENT MENTAL TIMELINE" body={replayTitles.length?replayTitles.slice(0,5).join(' → '):'No Second Brain thoughts, decisions, or loop changes were recorded in the last 30 days.'} foot="Use Timeline for the broader life chronology."/></section>
  <section className="rounded-[20px] border border-[#e7dfd7] bg-[#faf6f1] p-4"><div className="flex items-center gap-2"><Sparkles size={13}/><b className="text-[9px] uppercase tracking-[.13em]">Confidence + provenance rule</b></div><p className="mt-2 text-[8.5px] leading-4 text-[#837971]">Strong claims should come from stored evidence. Frequency-only topic signals stay labeled as frequency signals. Keyword search stays labeled keyword search. Semantic similarity, contradiction detection, and causal claims are not presented as real until their underlying engines exist.</p><Link href="/timeline" className="mt-3 inline-flex items-center gap-1 text-[8.5px] font-semibold">Open full Timeline <RefreshCw size={9}/></Link></section>
 </div>
}
function SelectItem({value,setValue,items}:{value:string;setValue:(v:string)=>void;items:Item[]}){return <select value={value} onChange={e=>setValue(e.target.value)} disabled={!items.length} className="min-w-0 rounded-xl border border-[#e2dad2] bg-white px-3 py-2.5 text-[9px] disabled:opacity-50">{items.length?items.map(x=><option key={`${x.type}:${x.id}`} value={`${x.type}:${x.id}`}>{x.type}: {x.title}</option>):<option value="">No connectable items yet</option>}</select>}
function Synthesis({title,eyebrow,body,foot}:{title:string;eyebrow:string;body:string;foot:string}){return <div className="rounded-[22px] border border-[#e7dfd7] bg-[#fffdfa] p-5"><p className="text-[7.5px] font-semibold uppercase tracking-[.15em] text-[#8d8178]">{eyebrow}</p><h3 className="mt-1 font-serif text-[22px]">{title}</h3><p className="mt-3 text-[9px] leading-5 text-[#776e67]">{body}</p><p className="mt-3 text-[7.5px] leading-4 text-[#9a8e85]">{foot}</p></div>}
