'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Check, Heart, Plus, RotateCcw, Sparkles } from 'lucide-react';

type RoomKind='Body'|'Nails'|'Fragrance';
type Item={name:string;detail:string};

const content:Record<RoomKind,{eyebrow:string;description:string;sections:{title:string;items:Item[]}[]}>={
 Body:{eyebrow:'Beauty / Body',description:'Body care that connects moisture, exfoliation, shaving, SPF, fragrance and reset routines.',sections:[{title:'Today',items:[{name:'Moisture',detail:'Lotion or body cream after shower'},{name:'Exfoliation',detail:'Keep strong exfoliation on its own cadence'},{name:'Polish',detail:'Deodorant · body oil · fragrance'}]},{title:'Weekly care',items:[{name:'Everything Shower',detail:'Hair + shave + exfoliation + moisture'},{name:'Body reset',detail:'Tools, restock and treatment check'}]}]},
 Nails:{eyebrow:'Beauty / Nails',description:'Track your current manicure, color ideas, appointments and at-home maintenance without losing them in notes.',sections:[{title:'Current manicure',items:[{name:'Status',detail:'Save color, date and condition'},{name:'Next refresh',detail:'Plan around upcoming events'}]},{title:'Nail care',items:[{name:'At-home routine',detail:'File · cuticle care · oil · hand cream'},{name:'Inspiration',detail:'Save colors and future sets'}]}]},
 Fragrance:{eyebrow:'Beauty / Fragrance',description:'A fragrance wardrobe organized by mood, season, occasion and what completes the rest of your look.',sections:[{title:'Wardrobe',items:[{name:'Day',detail:'Clean · bright · easy'},{name:'Night',detail:'Warm · romantic · deeper'},{name:'Signature',detail:'Your repeat favorites'}]},{title:'Match the look',items:[{name:'Romantic',detail:'Pair with Soft Romantic makeup and polished hair'},{name:'Special occasion',detail:'Save scent + outfit + makeup as one memory'}]}]},
};

export function BeautySpecialtyRoom({kind}:{kind:RoomKind}){
 const data=content[kind];
 const storageKey=`glow:beauty:${kind.toLowerCase()}`;
 const [done,setDone]=useState<string[]>([]);
 const [note,setNote]=useState('');
 const [ready,setReady]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw){const saved=JSON.parse(raw) as {done?:string[];note?:string};setDone(saved.done??[]);setNote(saved.note??'')}}catch{}finally{setReady(true)}},[storageKey]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(storageKey,JSON.stringify({done,note,updatedAt:new Date().toISOString()}))}catch{}},[done,note,ready,storageKey]);
 return <div className="mx-auto max-w-[1200px] space-y-4 pb-28"><section className="rounded-[30px] border border-[#eadfda] bg-[radial-gradient(circle_at_15%_0%,rgba(255,231,238,.9),transparent_35%),linear-gradient(135deg,#fff,#faf5f2)] p-6 shadow-[0_24px_80px_rgba(65,41,35,.07)] sm:p-8"><p className="text-[9px] uppercase tracking-[.22em] text-[#b87888]">{data.eyebrow}</p><h1 className="mt-2 font-serif text-[40px] leading-none text-[#2f2927] sm:text-[48px]">{kind}</h1><p className="mt-3 max-w-2xl text-[12px] leading-6 text-[#7d726d]">{data.description}</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/beauty" className="rounded-full border border-[#eadfda] bg-white px-4 py-2 text-[11px]">Beauty Today</Link><Link href="/beauty/lab" className="rounded-full border border-[#eadfda] bg-white px-4 py-2 text-[11px]">Beauty Lab</Link><button type="button" onClick={()=>document.dispatchEvent(new CustomEvent('glow:open-conversation'))} className="rounded-full bg-[#2f2927] px-4 py-2 text-[11px] text-white">Ask Glow</button></div></section><div className="grid gap-4 md:grid-cols-2">{data.sections.map(section=><section key={section.title} className="rounded-[26px] border border-[#eadfda] bg-white p-5"><div className="flex items-center gap-2"><Sparkles size={15} className="text-[#b87989]"/><h2 className="font-serif text-xl">{section.title}</h2></div><div className="mt-4 space-y-2">{section.items.map(item=>{const key=`${section.title}:${item.name}`;const complete=done.includes(key);return <button type="button" key={key} onClick={()=>setDone(current=>complete?current.filter(value=>value!==key):[...current,key])} aria-pressed={complete} className={`flex min-h-14 w-full items-center gap-3 rounded-[18px] p-3 text-left ${complete?'bg-[#eef4ec]':'bg-[#faf7f5]'}`}><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white">{complete?<Check size={14}/>:<Plus size={14}/>}</span><span><strong className="block font-serif text-base font-normal">{item.name}</strong><span className="mt-1 block text-[10px] text-[#817671]">{item.detail}</span></span></button>})}</div></section>)}</div><section className="rounded-[26px] border border-[#eadfda] bg-[#fff8fa] p-5"><div className="flex items-center gap-2"><Heart size={15} className="text-[#b87989]"/><h2 className="font-serif text-xl">Remember this</h2></div><label htmlFor={`${kind}-note`} className="mt-3 block text-[10px] text-[#756a66]">Notes, favorites, reactions or what you want Glow to remember</label><textarea id={`${kind}-note`} value={note} onChange={event=>setNote(event.target.value)} className="mt-2 min-h-24 w-full rounded-[18px] border border-[#eadfda] bg-white p-3 text-[12px] outline-none focus:ring-2 focus:ring-[#e8c9d1]"/><button type="button" onClick={()=>{setDone([]);setNote('')}} className="mt-3 inline-flex items-center gap-2 rounded-full border border-[#eadfda] bg-white px-4 py-2 text-[11px]"><RotateCcw size={13}/>Reset room</button></section></div>
}
