'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Beaker, Camera, CircleUserRound, FlaskConical, Heart, ImagePlus, Play, Scale, Sparkles, WandSparkles } from 'lucide-react';
import { createBeautyProductAction } from '@/app/actions/completion-v1';
import type { BeautyRoutine } from '@/lib/types';

type BeautyProductLite={id:string;name:string;category:string;ingredients:string|null;openedAt:Date|null;expiresAt:Date|null;routinePosition:string|null;reaction:string|null;costCents:number|null;repurchase:string|null;usageFrequency:string|null};
const fieldClass='w-full rounded-xl border border-[#F7D1D8] bg-white px-3 py-2.5 text-[11px] text-[#2B2420]';
const occasions=['Work','Date','Dinner','Interview','Casual','Party'];
const moods=['Soft','Romantic','Natural','Glam','Editorial'];
const faceZones=['Forehead','Under-eye','Cheeks','Nose','Lips','Chin','Jaw'];
const techniques=['Blush','Contour','Bronzer','Highlight','Concealer','Lip liner','Eyeshadow'];

function status(p:BeautyProductLite){if(p.repurchase==='yes')return 'Loved';if(p.repurchase==='no')return 'No';if(p.repurchase==='maybe')return 'Unsure';return 'Testing'}
function dateText(d:Date|null){return d?new Date(d).toLocaleDateString('en-US',{month:'short',day:'numeric'}):'No date'}

export function BeautyLabExperience({products,routines}:{products:BeautyProductLite[];routines:BeautyRoutine[]}){
  const [tab,setTab]=useState<'experiments'|'look'|'compare'|'face'|'learn'>('experiments');
  const [occasion,setOccasion]=useState('Dinner'); const [mood,setMood]=useState('Soft'); const [minutes,setMinutes]=useState(20); const [face,setFace]=useState('Cheeks'); const [technique,setTechnique]=useState('Blush'); const [placement,setPlacement]=useState('Lifted');
  const [before,setBefore]=useState<string|null>(null); const [after,setAfter]=useState<string|null>(null); const [split,setSplit]=useState(50); const [skinPhoto,setSkinPhoto]=useState<string|null>(null); const [confidence,setConfidence]=useState('');
  const experiments=useMemo(()=>products.filter(p=>!p.repurchase||p.repurchase==='maybe').slice(0,8),[products]);
  const timeline=useMemo(()=>[...products].filter(p=>p.openedAt||p.reaction).sort((a,b)=>(new Date(b.openedAt??0).getTime()-new Date(a.openedAt??0).getTime())).slice(0,8),[products]);
  const favorites=products.filter(p=>p.repurchase==='yes'); const reactions=products.filter(p=>p.reaction?.trim());
  const matching=products.filter(p=>['makeup','lip','blush','liner','mascara','foundation','concealer'].some(k=>p.category.toLowerCase().includes(k)||p.name.toLowerCase().includes(k))).slice(0,6);
  const lookSteps=minutes<=10?['Skin tint / spot conceal','Cream blush','Mascara','Lip combo']:minutes<=20?['Prep + base','Concealer','Cream blush','Soft eye','Mascara','Lip combo']:['Skin prep','Base','Concealer','Bronzer','Blush','Highlight','Eye look','Liner','Mascara','Lip combo'];
  function objectUrl(file:File|undefined,setter:(v:string)=>void){if(file)setter(URL.createObjectURL(file))}
  return <div className="space-y-6">
    <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="flex flex-col justify-center"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#B85D72]">Beauty Lab</p><h1 className="glow-display mt-2 text-[38px] leading-[1.02] sm:text-[48px]">Experiment. Compare.<br/>Learn what works.</h1><p className="mt-3 max-w-xl text-[12.5px] leading-5 text-[#8A8078]">Beauty Lab is your creative testing space. Daily routines stay in Beauty; experiments, photos, looks, comparisons, technique practice, and product decisions live here.</p></div><div className="rounded-[24px] border border-[#F7D1D8] bg-[radial-gradient(circle_at_30%_30%,#fff,#f9e7e8_50%,#eee5f4)] p-5"><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/75 p-4"><Beaker size={14} className="text-[#B85D72]"/><p className="glow-display mt-2 text-[24px]">{experiments.length}</p><p className="text-[9.5px] text-[#8A8078]">active tests</p></div><div className="rounded-2xl bg-white/75 p-4"><Heart size={14} className="text-[#B85D72]"/><p className="glow-display mt-2 text-[24px]">{favorites.length}</p><p className="text-[9.5px] text-[#8A8078]">repurchase favorites</p></div><div className="rounded-2xl bg-white/75 p-4"><Sparkles size={14} className="text-[#B85D72]"/><p className="glow-display mt-2 text-[24px]">{reactions.length}</p><p className="text-[9.5px] text-[#8A8078]">reaction notes</p></div><div className="rounded-2xl bg-white/75 p-4"><Scale size={14} className="text-[#B85D72]"/><p className="glow-display mt-2 text-[24px]">{products.length}</p><p className="text-[9.5px] text-[#8A8078]">products tracked</p></div></div></div></section>

    <nav className="flex gap-2 overflow-x-auto pb-1">{([['experiments','Experiments'],['look','Look Builder'],['compare','Before / After'],['face','Face Map'],['learn','Learn Mode']] as const).map(([id,label])=><button key={id} type="button" onClick={()=>setTab(id)} className={`shrink-0 rounded-full border px-4 py-2 text-[10.5px] ${tab===id?'border-[#B85D72] bg-[#FAE6E7] text-[#8B5864]':'border-[#F7D1D8] bg-white text-[#8A8078]'}`}>{label}</button>)}</nav>

    {tab==='experiments'?<>
      <section className="grid gap-4 lg:grid-cols-[1fr_.8fr]"><div className="rounded-[20px] border border-[#F7D1D8] bg-white p-5"><div className="flex items-center justify-between"><div><p className="glow-eyebrow">Current experiments</p><h2 className="glow-display mt-1 text-[21px]">Testing queue</h2></div><FlaskConical size={16} className="text-[#B85D72]"/></div><div className="mt-4 space-y-3">{experiments.length?experiments.map(p=><Link key={p.id} href={`/beauty/lab?productId=${p.id}`} className="block rounded-2xl bg-[#FDF8F6] p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-[12px] font-medium">{p.name}</p><p className="mt-1 text-[9.5px] text-[#9A9088]">{p.category} · started {dateText(p.openedAt)}</p></div><span className="rounded-full bg-white px-2 py-1 text-[9px] text-[#B85D72]">{status(p)}</span></div><p className="mt-2 line-clamp-2 text-[10.5px] leading-4 text-[#7A6F69]">{p.reaction||'No observations yet. Open this test to add immediate, wear, or next-day notes.'}</p></Link>):<p className="text-[11px] text-[#9A9088]">No active tests. Add a product below and leave its decision as “Still testing.”</p>}</div></div>
      <div className="rounded-[20px] border border-[#F7D1D8] bg-[#FFF8F7] p-5"><div className="flex items-center gap-2"><Camera size={14} className="text-[#B85D72]"/><h2 className="glow-display text-[19px]">How does my skin look?</h2></div><p className="mt-2 text-[10.5px] leading-4 text-[#8A8078]">Upload a photo for your own visual check-in. Glow keeps this non-diagnostic: it can help you track appearance and routine context, not diagnose a skin condition.</p><label className="mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-dashed border-[#E6BFC7] bg-white p-5 text-[10.5px]"><ImagePlus size={14}/>Add today’s photo<input type="file" accept="image/*" className="sr-only" onChange={e=>objectUrl(e.target.files?.[0],v=>setSkinPhoto(v))}/></label>{skinPhoto?<div className="mt-3 overflow-hidden rounded-2xl"><img src={skinPhoto} alt="Today's beauty check-in" className="h-48 w-full object-cover"/><div className="bg-white p-3"><p className="text-[10px] font-medium">Today’s visual check-in</p><p className="mt-1 text-[9.5px] leading-4 text-[#8A8078]">Photo loaded for this session. Add your own observations in a product reaction note or compare it below.</p></div></div>:null}</div></section>
      <section className="rounded-[20px] border border-[#F7D1D8] bg-white p-5"><div className="flex items-center justify-between"><div><p className="glow-eyebrow">Skin + product timeline</p><h2 className="glow-display mt-1 text-[20px]">What changed over time</h2></div><Link href="/beauty" className="text-[10px] text-[#B85D72]">Back to Beauty</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{timeline.map(p=><div key={p.id} className="rounded-2xl bg-[#FDF8F6] p-4"><p className="text-[9px] uppercase tracking-[.1em] text-[#B85D72]">{dateText(p.openedAt)}</p><p className="mt-1 text-[11.5px] font-medium">{p.name}</p><p className="mt-2 line-clamp-3 text-[10px] leading-4 text-[#8A8078]">{p.reaction||`${p.category} added to testing`}</p></div>)}</div></section>
      <details className="rounded-[20px] border border-[#F7D1D8] bg-white p-5"><summary className="cursor-pointer text-[12px] font-medium">+ Start a new product experiment</summary><form action={createBeautyProductAction} className="mt-4 grid gap-2 sm:grid-cols-2"><input name="name" required placeholder="Product name" className={fieldClass}/><input name="category" required placeholder="Category" className={fieldClass}/><textarea name="ingredients" rows={2} placeholder="Ingredients / actives" className={`${fieldClass} sm:col-span-2`}/><input name="openedAt" type="date" className={fieldClass}/><input name="expiresAt" type="date" className={fieldClass}/><input name="routinePosition" placeholder="Routine position" className={fieldClass}/><input name="cost" inputMode="decimal" placeholder="Cost" className={fieldClass}/><button type="submit" className="w-fit rounded-xl bg-[#B85D72] px-4 py-2.5 text-[11px] text-white sm:col-span-2">Start testing</button></form></details>
    </>:null}

    {tab==='look'?<section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[20px] border border-[#F7D1D8] bg-white p-5"><div className="flex items-center gap-2"><WandSparkles size={15} className="text-[#B85D72]"/><h2 className="glow-display text-[21px]">Makeup Look Builder</h2></div><label className="mt-4 block text-[10px] text-[#8A8078]">Occasion</label><div className="mt-2 flex flex-wrap gap-1.5">{occasions.map(x=><button key={x} type="button" onClick={()=>setOccasion(x)} className={`rounded-full border px-3 py-1.5 text-[9.5px] ${occasion===x?'bg-[#FAE6E7] border-[#B85D72]':'border-[#F7D1D8]'}`}>{x}</button>)}</div><label className="mt-4 block text-[10px] text-[#8A8078]">Mood</label><div className="mt-2 flex flex-wrap gap-1.5">{moods.map(x=><button key={x} type="button" onClick={()=>setMood(x)} className={`rounded-full border px-3 py-1.5 text-[9.5px] ${mood===x?'bg-[#FAE6E7] border-[#B85D72]':'border-[#F7D1D8]'}`}>{x}</button>)}</div><label className="mt-4 block text-[10px] text-[#8A8078]">Time available · {minutes} min</label><input type="range" min="10" max="45" step="5" value={minutes} onChange={e=>setMinutes(Number(e.target.value))} className="mt-2 w-full"/></div><div className="rounded-[20px] border border-[#F7D1D8] bg-[linear-gradient(145deg,#fff,#fff5f4)] p-5"><p className="text-[9px] uppercase tracking-[.12em] text-[#B85D72]">Generated from your choices</p><h3 className="glow-display mt-1 text-[26px]">{mood} {occasion} Look</h3><p className="mt-1 text-[10.5px] text-[#8A8078]">{minutes} minutes · {lookSteps.length} steps</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{lookSteps.map((x,i)=><div key={x} className="rounded-xl bg-white p-3 text-[10.5px]"><span className="mr-2 text-[#B85D72]">{i+1}</span>{x}</div>)}</div><div className="mt-4"><p className="text-[10px] font-medium">Products already in your Beauty cabinet</p><div className="mt-2 flex flex-wrap gap-2">{matching.length?matching.map(p=><span key={p.id} className="rounded-full bg-[#FAE6E7] px-3 py-1.5 text-[9.5px]">✓ {p.name}</span>):<span className="text-[10px] text-[#9A9088]">No makeup-tagged products found yet.</span>}</div></div><div className="mt-5 flex gap-2"><Link href="/beauty" className="flex items-center gap-1.5 rounded-full bg-[#2B2420] px-4 py-2.5 text-[10.5px] text-white"><Play size={11}/>Use in Beauty</Link><button type="button" className="rounded-full border border-[#F7D1D8] px-4 py-2.5 text-[10.5px]">Save look idea</button></div></div></section>:null}

    {tab==='compare'?<section className="rounded-[20px] border border-[#F7D1D8] bg-white p-5"><div className="flex items-center gap-2"><Scale size={15} className="text-[#B85D72]"/><h2 className="glow-display text-[21px]">Before / After Comparison</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-center justify-center rounded-2xl border border-dashed border-[#F7D1D8] bg-[#FFF9F8] p-6 text-[10.5px]">Add before<input type="file" accept="image/*" className="sr-only" onChange={e=>objectUrl(e.target.files?.[0],v=>setBefore(v))}/></label><label className="flex cursor-pointer items-center justify-center rounded-2xl border border-dashed border-[#F7D1D8] bg-[#FFF9F8] p-6 text-[10.5px]">Add after<input type="file" accept="image/*" className="sr-only" onChange={e=>objectUrl(e.target.files?.[0],v=>setAfter(v))}/></label></div>{before&&after?<div className="mt-4"><div className="relative h-[320px] overflow-hidden rounded-2xl bg-[#F5EFEC]"><img src={before} alt="Before beauty comparison" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-y-0 right-0 overflow-hidden" style={{width:`${100-split}%`}}><img src={after} alt="After beauty comparison" className="absolute inset-y-0 right-0 h-full w-full object-cover"/></div><div className="absolute inset-y-0 w-px bg-white" style={{left:`${split}%`}}/></div><input type="range" min="5" max="95" value={split} onChange={e=>setSplit(Number(e.target.value))} className="mt-3 w-full"/><p className="text-center text-[9.5px] text-[#8A8078]">Drag to compare. Photos remain local to this session unless you separately save them elsewhere in Glow.</p></div>:null}</section>:null}

    {tab==='face'?<section className="grid gap-4 lg:grid-cols-[.75fr_1.25fr]"><div className="rounded-[20px] border border-[#F7D1D8] bg-white p-5"><div className="flex items-center gap-2"><CircleUserRound size={15} className="text-[#B85D72]"/><h2 className="glow-display text-[20px]">Interactive Face Map</h2></div><div className="mx-auto mt-5 flex h-64 w-48 flex-col items-center justify-center rounded-[50%_50%_45%_45%] border border-[#E8C9CF] bg-[#FFF8F7] p-4 text-center"><p className="glow-display text-[24px]">{face}</p><p className="mt-2 text-[10px] text-[#8A8078]">{technique} · {placement}</p></div><div className="mt-4 flex flex-wrap justify-center gap-1.5">{faceZones.map(x=><button key={x} type="button" onClick={()=>setFace(x)} className={`rounded-full border px-2.5 py-1 text-[9px] ${face===x?'border-[#B85D72] bg-[#FAE6E7]':'border-[#F7D1D8]'}`}>{x}</button>)}</div></div><div className="rounded-[20px] border border-[#F7D1D8] bg-white p-5"><p className="text-[10px] uppercase tracking-[.1em] text-[#8A8078]">Placement studio</p><div className="mt-3 flex flex-wrap gap-1.5">{techniques.map(x=><button key={x} type="button" onClick={()=>setTechnique(x)} className={`rounded-full border px-3 py-1.5 text-[9.5px] ${technique===x?'border-[#B85D72] bg-[#FAE6E7]':'border-[#F7D1D8]'}`}>{x}</button>)}</div><div className="mt-4 grid grid-cols-2 gap-2">{['Natural','Lifted','Round','Sculpted'].map(x=><button key={x} type="button" onClick={()=>setPlacement(x)} className={`rounded-xl border p-3 text-[10px] ${placement===x?'border-[#B85D72] bg-[#FFF5F4]':'border-[#F7D1D8]'}`}>{x}</button>)}</div><div className="mt-5 rounded-2xl bg-[#FFF8F7] p-4"><p className="text-[10px] font-medium">Your map note</p><p className="mt-2 text-[11px] leading-5 text-[#6F6460]">Apply {technique.toLowerCase()} using a {placement.toLowerCase()} placement on the {face.toLowerCase()}. Save product-specific observations in the product record so Glow can remember what worked.</p></div></div></section>:null}

    {tab==='learn'?<section className="grid gap-4 lg:grid-cols-[1fr_.7fr]"><div className="rounded-[20px] border border-[#F7D1D8] bg-white p-5"><p className="glow-eyebrow">Learn Mode</p><h2 className="glow-display mt-1 text-[23px]">Winged liner practice</h2><div className="mt-4 space-y-2">{['Mark the outer angle','Draw the wing','Connect to the lash line','Fill the shape','Clean the edge'].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl bg-[#FFF8F7] p-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-white text-[9px] text-[#B85D72]">{i+1}</span><span className="text-[11px]">{x}</span></div>)}</div><button type="button" className="mt-4 rounded-full bg-[#2B2420] px-4 py-2.5 text-[10.5px] text-white">Start Practice Mode</button></div><div className="rounded-[20px] border border-[#F7D1D8] bg-[#FFF8F7] p-5"><p className="text-[10px] uppercase tracking-[.1em] text-[#8A8078]">Confidence check</p><div className="mt-4 grid gap-2">{[['😍','Loved it'],['🙂','Good'],['😐','Okay'],['🙁','Needs practice']].map(([e,l])=><button key={l} type="button" onClick={()=>setConfidence(l)} className={`rounded-xl border p-3 text-left text-[10.5px] ${confidence===l?'border-[#B85D72] bg-white':'border-[#F7D1D8]'}`}>{e} {l}</button>)}</div>{confidence?<p className="mt-4 text-[10px] text-[#8A8078]">Marked “{confidence}” for this session. Persistent confidence history can be stored next when a dedicated look-log table is added.</p>:null}</div></section>:null}

    <section className="rounded-[20px] border border-[#F7D1D8] bg-[linear-gradient(145deg,#fff,#fff5f4)] p-5"><div className="flex items-center gap-2"><Sparkles size={14} className="text-[#B85D72]"/><p className="text-[10px] font-semibold uppercase tracking-[.1em]">Beauty Insights</p></div><p className="glow-display mt-3 text-[18px] italic leading-7">Glow currently has {reactions.length} personal reaction notes, {favorites.length} products you would repurchase, {experiments.length} products still being tested, and {routines.length} saved beauty routine steps. Those are the signals it should use when helping you choose products and routines.</p></section>

    <section className="rounded-[20px] border border-[#F7D1D8] bg-white p-5"><p className="text-[12px] font-medium">Product decision table</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{products.slice(0,12).map(p=><div key={p.id} className="rounded-xl bg-[#FDF8F6] p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-[10.5px] font-medium">{p.name}</p><p className="text-[9px] text-[#9A9088]">{p.category}</p></div><span className="text-[9px] text-[#B85D72]">{status(p)}</span></div><p className="mt-2 text-[9.5px] text-[#8A8078]">Use: {p.usageFrequency||'not logged'} · Cost: {p.costCents==null?'—':`$${(p.costCents/100).toFixed(2)}`}</p><Link href={`/beauty/lab?productId=${p.id}`} className="mt-2 inline-flex text-[9.5px] text-[#B85D72]">Open details →</Link></div>)}</div></section>
  </div>
}
