'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import {
  CalendarClock, Check, ChevronLeft, ChevronRight, Clock3, FlaskConical, Heart,
  Mic, MoonStar, Package, Play, ShoppingBag, Sparkles, SunMedium, TimerReset, X,
} from 'lucide-react';
import type { BeautyRoutine } from '@/lib/types';

type BeautyProductLite={id:string;name:string;category:string;repurchase:string|null;expiresAt:Date|null;reaction?:string|null;usageFrequency?:string|null;photoUrl?:string|null};
type EventLite={id:string;title:string;startAt:Date;location:string|null};
type Mode='luxury'|'full'|'quick'|'minimum';

type PlayerStep={id:string;name:string;products:string[];notes:string|null;minutes:number};

const modeMeta:Record<Mode,{label:string;range:string;limit:number}>={
  luxury:{label:'Luxury',range:'45–60 min',limit:99},full:{label:'Full',range:'30–40 min',limit:9},quick:{label:'Quick',range:'15–20 min',limit:5},minimum:{label:'Minimum',range:'5–10 min',limit:3},
};
const shelves=[['Skincare','Cleansers · serums · moisturizers'],['Makeup','Complexion · eyes · lips'],['Hair','Care · styling · protection'],['Body','Moisture · treatments · tools'],['Fragrance','Daily · evening · favorites'],['Tools','Brushes · rollers · accessories']];

function dayLabel(date:Date){return new Date(date).toLocaleDateString('en-US',{month:'short',day:'numeric'})}
function normalize(s:string){return s.toLowerCase().replace(/[^a-z0-9]/g,'')}
function minutesFor(step:BeautyRoutine){
  const n=step.name.toLowerCase();
  if(n.includes('clean')) return 3;if(n.includes('mask')||n.includes('treatment')) return 10;if(n.includes('makeup')) return 20;if(n.includes('hair')) return 15;if(n.includes('shower')) return 12;return 4;
}

function BeautyPlayer({title,steps,onClose}:{title:string;steps:PlayerStep[];onClose:()=>void}){
  const [index,setIndex]=useState(0); const [done,setDone]=useState(0); const [seconds,setSeconds]=useState(0); const [why,setWhy]=useState(false); const [swap,setSwap]=useState(false);
  const step=steps[index]; const finished=index>=steps.length;
  const progress=steps.length?Math.min(100,(index/steps.length)*100):0;
  function next(completed=true){if(completed)setDone(v=>v+1);setIndex(v=>v+1);setSeconds(0);setWhy(false);setSwap(false)}
  function speak(){if(typeof window==='undefined'||!step)return;window.speechSynthesis?.speak(new SpeechSynthesisUtterance(`${step.name}. ${step.notes??''}`))}
  function tick(){if(!step)return;setSeconds(v=>v?0:step.minutes*60)}
  return <div className="fixed inset-0 z-[180] overflow-y-auto bg-[#fffaf8] text-[#2B2420]" role="dialog" aria-modal="true" aria-label={`${title} Beauty Player`}>
    <div className="sticky top-0 z-10 border-b border-[#F1E7E3] bg-[#fffaf8]/95 px-4 py-3 backdrop-blur sm:px-7"><div className="mx-auto flex max-w-3xl items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-[#C9727E]">Beauty Player</p><p className="glow-display text-[18px]">{title}</p></div><button type="button" onClick={onClose} className="rounded-full border border-[#F1E7E3] bg-white p-2.5" aria-label="Close Beauty Player"><X size={16}/></button></div><div className="absolute bottom-0 left-0 h-1 bg-[#C9727E] transition-all" style={{width:`${progress}%`}}/></div>
    <div className="mx-auto max-w-3xl px-4 py-8 sm:px-7 sm:py-12">
      {finished?<div className="py-20 text-center"><Sparkles className="mx-auto text-[#C9727E]"/><h2 className="glow-display mt-4 text-[34px]">Beauty routine complete.</h2><p className="mt-2 text-[13px] text-[#8A8078]">{done} of {steps.length} steps completed.</p><div className="mt-6 flex justify-center gap-2"><button onClick={onClose} className="rounded-full bg-[#2B2420] px-5 py-3 text-[12px] text-white">Finish</button><Link href="/beauty/lab" className="rounded-full border border-[#F1E7E3] px-5 py-3 text-[12px]">Log how it went</Link></div></div>:
      step?<div className="grid gap-6 lg:grid-cols-[1fr_240px]">
        <section className="rounded-[28px] border border-[#F1E7E3] bg-white p-6 sm:p-8"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#C9727E]">Step {index+1} of {steps.length}</p><h2 className="glow-display mt-2 text-[36px] leading-tight">{step.name}</h2>{step.notes?<p className="mt-3 text-[13px] leading-6 text-[#6B6560]">{step.notes}</p>:null}
          <div className="mt-5 flex flex-wrap gap-2">{step.products.length?step.products.map(p=><span key={p} className="rounded-full bg-[#FDF3F2] px-3 py-1.5 text-[10.5px] text-[#8B5864]">Use · {p}</span>):<span className="rounded-full bg-[#F7F2EF] px-3 py-1.5 text-[10.5px] text-[#8A8078]">No product linked</span>}</div>
          <div className="mt-6 grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>next(true)} className="flex items-center justify-center gap-2 rounded-2xl bg-[#2B2420] px-4 py-3 text-[12px] font-medium text-white"><Check size={14}/>Done</button><button type="button" onClick={()=>next(false)} className="rounded-2xl border border-[#F1E7E3] px-4 py-3 text-[12px]">Skip</button><button type="button" onClick={()=>setWhy(v=>!v)} className="rounded-2xl border border-[#F1E7E3] px-4 py-3 text-[12px]">Why this step?</button><button type="button" onClick={()=>setSwap(v=>!v)} className="rounded-2xl border border-[#F1E7E3] px-4 py-3 text-[12px]">Swap product</button></div>
          {why?<div className="mt-3 rounded-2xl bg-[#FFF5F4] p-4 text-[11.5px] leading-5 text-[#6B6560]">This step is placed here based on your saved routine order. Glow keeps product guidance conservative and does not treat routine ordering as medical advice.</div>:null}
          {swap?<div className="mt-3 rounded-2xl bg-[#F8F5F2] p-4 text-[11.5px] text-[#6B6560]">Open your Virtual Vanity after this routine to choose another product from the same category.</div>:null}
        </section>
        <aside className="space-y-3"><div className="rounded-[20px] border border-[#F1E7E3] bg-white p-4"><div className="flex items-center justify-between"><p className="text-[10px] uppercase tracking-[.1em] text-[#8A8078]">Timer</p><Clock3 size={13} className="text-[#C9727E]"/></div><p className="glow-display mt-2 text-[30px]">{seconds?`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`:`~${step.minutes}:00`}</p><div className="mt-3 flex gap-2"><button type="button" onClick={tick} className="rounded-full bg-[#FDF3F2] px-3 py-2 text-[10.5px]">{seconds?'Reset':'Start'}</button><button type="button" onClick={()=>setSeconds(v=>v+300)} className="rounded-full border border-[#F1E7E3] px-3 py-2 text-[10.5px]">+5 min</button></div></div><button type="button" onClick={speak} className="flex w-full items-center justify-center gap-2 rounded-[18px] border border-[#F1E7E3] bg-white p-4 text-[11px]"><Mic size={13}/>Read this step aloud</button></aside>
        <div className="lg:col-span-2 flex justify-between"><button type="button" disabled={index===0} onClick={()=>setIndex(v=>Math.max(0,v-1))} className="flex items-center gap-1 text-[11px] disabled:opacity-30"><ChevronLeft size={13}/>Previous</button><button type="button" onClick={()=>next(false)} className="flex items-center gap-1 text-[11px]">Next<ChevronRight size={13}/></button></div>
      </div>:null}
    </div>
  </div>
}

export function BeautyExperience({routines,products,upcomingAppointments}:{routines:BeautyRoutine[];products:BeautyProductLite[];upcomingAppointments:EventLite[]}){
  const [mode,setMode]=useState<Mode>('full'); const [player,setPlayer]=useState<{title:string;steps:PlayerStep[]}|null>(null); const [vanity,setVanity]=useState('Skincare'); const [readyBy,setReadyBy]=useState('18:00');
  const hour=new Date().getHours(); const isPm=hour>=15; const am=routines.filter(r=>r.timeOfDay==='morning').sort((a,b)=>a.stepOrder-b.stepOrder); const pm=routines.filter(r=>r.timeOfDay==='evening'||r.timeOfDay==='night').sort((a,b)=>a.stepOrder-b.stepOrder); const base=isPm?(pm.length?pm:am):(am.length?am:pm);
  const selected=base.slice(0,modeMeta[mode].limit); const playerSteps=selected.map(r=>({id:r.id,name:r.name,products:r.products??[],notes:r.notes,minutes:minutesFor(r)})); const total=playerSteps.reduce((s,x)=>s+x.minutes,0);
  const favorites=products.filter(p=>p.repurchase==='yes'); const low=products.filter(p=>p.expiresAt&&new Date(p.expiresAt).getTime()<Date.now()+30*86400000).slice(0,3); const notes=products.filter(p=>p.reaction?.trim()).slice(0,3);
  const vanityProducts=useMemo(()=>products.filter(p=>normalize(p.category).includes(normalize(vanity))||normalize(vanity).includes(normalize(p.category))).slice(0,8),[products,vanity]);
  const nextEvent=upcomingAppointments[0]??null;
  const gettingReady=[['Shower / prep',12],['Hair',15],['Skin prep',5],['Makeup',20],['Fragrance + finish',5]] as const; const readyTotal=gettingReady.reduce((s,x)=>s+x[1],0);
  function startCurrent(){setPlayer({title:isPm?'Tonight’s Beauty Plan':'Morning Beauty Plan',steps:playerSteps})}
  return <div className="space-y-6">
    {player?<BeautyPlayer title={player.title} steps={player.steps} onClose={()=>setPlayer(null)}/>:null}
    <section className="overflow-hidden rounded-[26px] border border-[#F1E7E3] bg-[linear-gradient(135deg,#fffaf8,#f9e9e8_48%,#eee5f4)] p-5 sm:p-7"><div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#C9727E]">Beauty · Right Now</p><h1 className="glow-display mt-2 text-[38px] leading-[1.03] sm:text-[48px]">{isPm?'Tonight’s Beauty Plan':'Your Morning Glow'}</h1><p className="mt-2 text-[12px] text-[#7A6F69]">{new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})} · {total} min · {playerSteps.length} steps</p><div className="mt-4 space-y-2">{playerSteps.slice(0,5).map((s,i)=><div key={s.id} className="flex items-center gap-3 text-[12px]"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-white/80 text-[9px] text-[#C9727E]">{i+1}</span><span>{s.name}</span><span className="ml-auto text-[10px] text-[#9A9088]">{s.minutes}m</span></div>)}{!playerSteps.length?<p className="text-[12px] text-[#8A8078]">Add beauty routine steps below and Glow will turn them into a guided plan.</p>:null}</div><div className="mt-5 flex flex-wrap gap-2"><button type="button" disabled={!playerSteps.length} onClick={startCurrent} className="flex items-center gap-2 rounded-full bg-[#2B2420] px-4 py-2.5 text-[11.5px] text-white disabled:opacity-40"><Play size={12}/>Start Beauty Routine</button><Link href="/concierge" className="flex items-center gap-2 rounded-full border border-white/80 bg-white/65 px-4 py-2.5 text-[11.5px]"><Sparkles size={12}/>Ask Glow</Link><button type="button" onClick={()=>setMode('quick')} className="rounded-full border border-white/80 bg-white/65 px-4 py-2.5 text-[11.5px]">Make It Quick</button></div></div>
      <div className="rounded-[22px] border border-white/80 bg-white/70 p-4 backdrop-blur"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#8A8078]">Routine intensity</p><div className="mt-3 grid grid-cols-2 gap-2">{(Object.keys(modeMeta) as Mode[]).map(m=><button key={m} type="button" onClick={()=>setMode(m)} className={`rounded-xl border p-3 text-left ${mode===m?'border-[#C9727E] bg-[#FDF3F2]':'border-[#F1E7E3] bg-white'}`}><span className="block text-[11px] font-medium">{modeMeta[m].label}</span><span className="mt-1 block text-[9.5px] text-[#9A9088]">{modeMeta[m].range}</span></button>)}</div>{nextEvent?<div className="mt-4 rounded-xl bg-[#fffaf8] p-3"><p className="text-[9px] uppercase tracking-[.1em] text-[#C9727E]">Event-aware prep</p><p className="mt-1 text-[11px] font-medium">{nextEvent.title}</p><p className="text-[9.5px] text-[#9A9088]">{dayLabel(nextEvent.startAt)} · {new Date(nextEvent.startAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</p></div>:null}</div></div></section>

    <section><div className="flex items-end justify-between gap-3"><div><p className="glow-eyebrow">Virtual vanity</p><h2 className="glow-display mt-1 text-[25px]">Open a shelf</h2></div><Link href="/beauty/lab" className="text-[10.5px] text-[#C9727E]">Manage products →</Link></div><div className="mt-3 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{shelves.map(([name,sub])=><button key={name} type="button" onClick={()=>setVanity(name)} className={`rounded-[18px] border p-4 text-left transition ${vanity===name?'border-[#C9727E] bg-[#FFF5F4]':'border-[#F1E7E3] bg-white'}`}><Package size={14} className="text-[#C9727E]"/><p className="mt-3 text-[12px] font-medium">{name}</p><p className="mt-1 text-[9.5px] leading-4 text-[#9A9088]">{sub}</p></button>)}</div><div className="mt-3 rounded-[18px] border border-[#F1E7E3] bg-white p-4"><p className="text-[11px] font-medium">{vanity} shelf</p><div className="mt-3 flex flex-wrap gap-2">{vanityProducts.length?vanityProducts.map(p=><Link key={p.id} href={`/beauty/lab?productId=${p.id}`} className="rounded-full bg-[#FDF3F2] px-3 py-2 text-[10.5px]">{p.name}</Link>):<p className="text-[10.5px] text-[#9A9088]">No products are tagged to this shelf yet. Category tags in Beauty Lab control what appears here.</p>}</div></div></section>

    <section className="grid gap-4 lg:grid-cols-[1fr_1fr]">
      <div className="rounded-[20px] border border-[#F1E7E3] bg-white p-5"><div className="flex items-center gap-2"><TimerReset size={14} className="text-[#C9727E]"/><h2 className="glow-display text-[19px]">Getting Ready Mode</h2></div><label className="mt-4 block text-[10px] uppercase tracking-[.1em] text-[#8A8078]">I need to be ready by</label><div className="mt-2 flex gap-2"><input type="time" value={readyBy} onChange={e=>setReadyBy(e.target.value)} className="rounded-xl border border-[#F1E7E3] px-3 py-2 text-[12px]"/><button type="button" onClick={()=>setPlayer({title:`Ready by ${readyBy}`,steps:gettingReady.map(([name,m],i)=>({id:String(i),name,products:[],notes:null,minutes:m}))})} className="rounded-xl bg-[#2B2420] px-4 py-2 text-[11px] text-white">Start plan</button></div><p className="mt-3 text-[10.5px] text-[#9A9088]">Planned duration · {readyTotal} min. If you’re running late, switch the Beauty Player to a shorter routine.</p><div className="mt-4 space-y-2">{gettingReady.map(([name,m])=><div key={name} className="flex justify-between text-[11px]"><span>{name}</span><span className="text-[#9A9088]">{m} min</span></div>)}</div></div>
      <div className="rounded-[20px] border border-[#F1E7E3] bg-white p-5"><div className="flex items-center gap-2"><ShoppingBag size={14} className="text-[#C9727E]"/><h2 className="glow-display text-[19px]">Smart Restock + Maintenance</h2></div><div className="mt-4 space-y-3">{low.length?low.map(p=><div key={p.id} className="flex items-center justify-between gap-3 rounded-xl bg-[#FDF8F6] p-3"><div><p className="text-[11px] font-medium">{p.name}</p><p className="text-[9.5px] text-[#9A9088]">Review by {p.expiresAt?dayLabel(p.expiresAt):'soon'}</p></div><Link href="/shopping" className="rounded-full border border-[#F1E7E3] bg-white px-3 py-1.5 text-[9.5px]">Add to Shopping</Link></div>):<p className="text-[11px] text-[#9A9088]">No products are close to their tracked review/expiration date.</p>}</div></div>
    </section>

    <section className="grid gap-4 lg:grid-cols-3"><div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#8A8078]">Beauty Maintenance</p><div className="mt-4 space-y-3 text-[11px]"><p className="flex justify-between"><span>AM routine</span><span>{am.length} steps</span></p><p className="flex justify-between"><span>PM routine</span><span>{pm.length} steps</span></p><p className="flex justify-between"><span>Repurchase favorites</span><span>{favorites.length}</span></p><p className="flex justify-between"><span>Upcoming appointments</span><span>{upcomingAppointments.length}</span></p></div></div><div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#8A8078]">Beauty Memory</p><div className="mt-3 space-y-2">{notes.length?notes.map(p=><div key={p.id}><p className="text-[11px] font-medium">{p.name}</p><p className="text-[10px] text-[#9A9088]">{p.reaction}</p></div>):<p className="text-[11px] text-[#9A9088]">Reaction notes you save in Beauty Lab will appear here and inform future choices.</p>}</div></div><div className="rounded-[18px] border border-[#F1E7E3] bg-[linear-gradient(145deg,#fff,#fff5f4)] p-4"><div className="flex items-center gap-2"><Heart size={13} className="text-[#C9727E]"/><p className="text-[10px] font-semibold uppercase tracking-[.1em]">Glow noticed</p></div><p className="glow-display mt-4 text-[16px] italic leading-6">You have {products.length} tracked products, {favorites.length} repurchase favorites, and {notes.length} recent personal reaction notes. Glow can use those facts instead of inventing a beauty score.</p><Link href="/beauty/lab" className="mt-4 inline-flex items-center gap-1 text-[10.5px] text-[#C9727E]"><FlaskConical size={11}/>Open Beauty Lab</Link></div></section>
  </div>
}
