'use client';

import Link from 'next/link';
import { useMemo, useState, useTransition } from 'react';
import { CheckCircle2, HeartPulse, ShowerHead, Sparkles } from 'lucide-react';
import { logBeautyReadinessAction } from '@/app/actions/advanced-beauty';

type StepLog={id:string;stepName:string;status:string;actualSeconds:number;completedAt:Date};
type Readiness={id:string;context:string;checks:Record<string,boolean>;completedCount:number;totalCount:number;occurredAt:Date};
const CHECKS=['Face','Hair','Oral','SPF','Deodorant','Fragrance','Bag beauty items'];

export function BeautySupportPanels({stepLogs,readiness}:{stepLogs:StepLog[];readiness:Readiness[]}){
  const [checks,setChecks]=useState<Record<string,boolean>>(()=>Object.fromEntries(CHECKS.map(x=>[x,false])));const [notice,setNotice]=useState('');const [pending,startTransition]=useTransition();
  const doctor=useMemo(()=>{const recent=stepLogs.filter(s=>new Date(s.completedAt).getTime()>=Date.now()-30*86400000);const skipped=recent.filter(s=>s.status==='skipped');const counts=new Map<string,number>();skipped.forEach(s=>counts.set(s.stepName,(counts.get(s.stepName)??0)+1));const top=[...counts.entries()].sort((a,b)=>b[1]-a[1])[0]??null;const completed=recent.filter(s=>s.status==='completed');const avg=completed.length?Math.round(completed.reduce((sum,s)=>sum+s.actualSeconds,0)/completed.length/60):null;return{sample:recent.length,top,avg}},[stepLogs]);
  const checked=Object.values(checks).filter(Boolean).length;
  function save(){startTransition(async()=>{const result=await logBeautyReadinessAction({context:'leaving',checks});setNotice(result.data?'Polished Check saved.':result.error??'Could not save Polished Check.');if(result.data)setChecks(Object.fromEntries(CHECKS.map(x=>[x,false])))})}
  return <section className="mx-auto grid max-w-7xl gap-4 pb-6 lg:grid-cols-3">
    <article className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><div className="flex items-center gap-2"><CheckCircle2 size={16}/><h2 className="font-serif text-2xl">Polished Check</h2></div><p className="mt-2 text-xs leading-5 text-[#8d7f87]">A quick leaving-ready check, not a perfection score.</p><div className="mt-4 grid grid-cols-2 gap-2">{CHECKS.map(item=><button key={item} type="button" onClick={()=>setChecks(c=>({...c,[item]:!c[item]}))} className={`rounded-2xl border px-3 py-3 text-left text-[10px] ${checks[item]?'border-[#c8a1b0] bg-[#fff2f5]':'border-[#eee4e7]'}`}><span className="font-semibold">{checks[item]?'✓ ':''}{item}</span>{item==='Fragrance'?<span className="block text-[8px] text-[#9a8d94]">optional</span>:null}</button>)}</div><button type="button" disabled={!checked||pending} onClick={save} className="mt-4 w-full rounded-full bg-[#4b3d46] px-4 py-2.5 text-xs text-white disabled:opacity-40">I’m Ready · {checked}/{CHECKS.length}</button>{notice?<p role="status" className="mt-2 text-[10px] text-[#776a72]">{notice}</p>:null}{readiness[0]?<p className="mt-3 text-[9px] text-[#9a8d94]">Last saved check: {new Date(readiness[0].occurredAt).toLocaleString()} · {readiness[0].completedCount}/{readiness[0].totalCount}</p>:null}</article>
    <article className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><div className="flex items-center gap-2"><HeartPulse size={16}/><h2 className="font-serif text-2xl">Beauty Doctor</h2></div><p className="mt-2 text-xs leading-5 text-[#8d7f87]">Evidence from the last 30 days of saved Beauty steps. Glow does not invent a pattern before data exists.</p>{doctor.sample?<div className="mt-4 space-y-2"><div className="rounded-2xl bg-[#faf6f4] p-3"><p className="text-[9px] uppercase text-[#978891]">Evidence</p><p className="mt-1 text-xs">{doctor.sample} recorded step event{doctor.sample===1?'':'s'}</p></div>{doctor.top?<div className="rounded-2xl bg-[#fff4f5] p-3"><p className="text-[9px] uppercase text-[#a07484]">Most skipped</p><p className="mt-1 text-xs font-semibold">{doctor.top[0]}</p><p className="text-[9px] text-[#958790]">{doctor.top[1]} intentional skip{doctor.top[1]===1?'':'s'}</p></div>:<div className="rounded-2xl bg-[#f3f6ef] p-3 text-xs">No repeated skipped Beauty step yet.</div>}{doctor.avg!=null?<div className="rounded-2xl bg-[#faf6f4] p-3 text-xs">Average completed step time: ~{Math.max(1,doctor.avg)} min</div>:null}</div>:<p className="mt-4 text-xs text-[#91848b]">Complete Beauty rituals to build a real friction map.</p>}<Link href="/beauty/progress" className="mt-4 inline-flex items-center gap-1 text-[10px] font-semibold">Open full evidence <span>→</span></Link></article>
    <article className="rounded-[26px] border border-[#e5ebe0] bg-[linear-gradient(145deg,#fbfdf8,#edf3e8)] p-5"><div className="flex items-center gap-2"><ShowerHead size={16}/><h2 className="font-serif text-2xl">Everything Shower</h2></div><p className="mt-2 text-xs leading-5 text-[#7e8778]">A dedicated guided surface for Prep → Hair → Body → Treat → Post-Shower → Finish, with one-step-at-a-time execution and parallel-waiting suggestions.</p><Link href="/beauty/everything-shower" className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#5c6854] px-4 py-2.5 text-xs text-white"><Sparkles size={12}/>Open Everything Shower</Link></article>
  </section>;
}
