'use client';

import Link from 'next/link';
import { useMemo, useState, useTransition } from 'react';
import { Beaker, CalendarDays, FlaskConical, Heart, Package, Play, Plus, Sparkles, SprayCan, WandSparkles } from 'lucide-react';
import { createBeautyProductAction } from '@/app/actions/completion-v1';
import { createBeautyFragranceAction, createBeautyLookAction, createBeautyTreatmentScheduleAction, toggleBeautyTreatmentScheduleAction, useBeautyLookAction } from '@/app/actions/advanced-beauty';
import type { BeautyRoutine } from '@/lib/types';

type Product={id:string;name:string;category:string;ingredients:string|null;openedAt:Date|null;expiresAt:Date|null;routinePosition:string|null;reaction:string|null;costCents:number|null;repurchase:string|null;usageFrequency:string|null};
type Look={id:string;name:string;occasion:string;mood:string;plannedMinutes:number;steps:string[];productIds:string[];notes:string|null;useCount:number;lastUsedAt:Date|null;createdAt:Date};
type Fragrance={id:string;name:string;family:string|null;dayparts:string[];seasons:string[];moods:string[];occasions:string[];favorite:boolean;notes:string|null};
type Schedule={id:string;treatmentKey:string;treatmentName:string;area:string;weekdays:number[];cadenceDays:number|null;nextDueAt:Date|null;strongTreatment:boolean;enabled:boolean;notes:string|null};
type Intelligence={looks:Look[];fragrances:Fragrance[];schedules:Schedule[]};
type Tab='products'|'looks'|'fragrance'|'treatments'|'learn';
const field='w-full rounded-xl border border-[#eadde2] bg-white px-3 py-2.5 text-xs outline-none focus:border-[#c99aac]';
const occasions=['Everyday','Work','Interview','Dinner','Date','Event','Photo'];
const moods=['Natural','Soft','Romantic','Glam','Editorial'];
const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
function stepsFor(minutes:number){return minutes<=10?['Skin tint / spot conceal','Cream blush','Mascara','Lip combo']:minutes<=20?['Prep + base','Concealer','Cream blush','Soft eye','Mascara','Lip combo']:['Skin prep','Base','Concealer','Bronzer','Blush','Highlight','Eye look','Liner','Mascara','Lip combo']}

export function BeautyLabStudio({products,routines,intelligence}:{products:Product[];routines:BeautyRoutine[];intelligence:Intelligence}){
  const [tab,setTab]=useState<Tab>('products'); const [occasion,setOccasion]=useState('Everyday'); const [mood,setMood]=useState('Natural'); const [minutes,setMinutes]=useState(20);
  const [looks,setLooks]=useState(intelligence.looks); const [fragrances,setFragrances]=useState(intelligence.fragrances); const [schedules,setSchedules]=useState(intelligence.schedules);
  const [fragranceName,setFragranceName]=useState(''); const [family,setFamily]=useState(''); const [daypart,setDaypart]=useState('day'); const [fragranceOccasion,setFragranceOccasion]=useState('Everyday');
  const [treatmentName,setTreatmentName]=useState(''); const [treatmentArea,setTreatmentArea]=useState('face'); const [selectedDays,setSelectedDays]=useState<number[]>([]); const [strong,setStrong]=useState(false);
  const [notice,setNotice]=useState(''); const [pending,startTransition]=useTransition();
  const makeupProducts=useMemo(()=>products.filter(p=>/makeup|foundation|concealer|blush|mascara|liner|lip|bronzer|highlight/i.test(`${p.category} ${p.name}`)).slice(0,10),[products]);
  const currentSteps=stepsFor(minutes); const experiments=products.filter(p=>!p.repurchase||p.repurchase==='maybe'); const favorites=products.filter(p=>p.repurchase==='yes'); const reactions=products.filter(p=>p.reaction?.trim());
  function flash(text:string){setNotice(text);window.setTimeout(()=>setNotice(''),4500)}
  function saveLook(){startTransition(async()=>{const result=await createBeautyLookAction({name:`${mood} ${occasion} Look`,occasion,mood,plannedMinutes:minutes,steps:currentSteps,productIds:makeupProducts.map(p=>p.id)});if(result.data){setLooks(c=>[result.data as Look,...c]);flash('Look saved across Glow.')}else flash(result.error??'Could not save look.')})}
  function repeatLook(id:string){startTransition(async()=>{const result=await useBeautyLookAction(id);if(result.data){setLooks(c=>c.map(x=>x.id===id?result.data as Look:x));flash('Look marked as repeated.')}else flash(result.error??'Could not update look history.')})}
  function addFragrance(){if(!fragranceName.trim())return;startTransition(async()=>{const result=await createBeautyFragranceAction({name:fragranceName.trim(),family:family.trim()||undefined,dayparts:[daypart],occasions:[fragranceOccasion]});if(result.data){setFragrances(c=>[result.data as Fragrance,...c]);setFragranceName('');setFamily('');flash('Fragrance added to your wardrobe.')}else flash(result.error??'Could not save fragrance.')})}
  function addSchedule(){if(!treatmentName.trim())return;startTransition(async()=>{const result=await createBeautyTreatmentScheduleAction({treatmentKey:treatmentName.toLowerCase().replace(/[^a-z0-9]+/g,'-'),treatmentName:treatmentName.trim(),area:treatmentArea,weekdays:selectedDays,strongTreatment:strong});if(result.data){setSchedules(c=>[result.data as Schedule,...c]);setTreatmentName('');setSelectedDays([]);setStrong(false);flash('Treatment schedule saved to Beauty Calendar.')}else flash(result.error??'Could not save treatment schedule.')})}
  function toggleSchedule(item:Schedule){startTransition(async()=>{const result=await toggleBeautyTreatmentScheduleAction(item.id,!item.enabled);if(result.data)setSchedules(c=>c.map(x=>x.id===item.id?result.data as Schedule:x));else flash(result.error??'Could not update schedule.')})}

  return <div className="space-y-6 pb-24 text-[#493e45]">{notice?<div role="status" className="sticky top-3 z-40 mx-auto w-fit rounded-full bg-white px-4 py-2 text-xs shadow-lg">{notice}</div>:null}
    <section className="rounded-[32px] border border-white/80 bg-[linear-gradient(135deg,#fffaf5,#f0e6ea)] p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#a47f91]">Beauty Lab</p><h1 className="mt-2 font-serif text-4xl sm:text-5xl">Experiment. Save. Repeat. Learn.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#7f7178]">Daily execution stays in Beauty. Products, persistent makeup looks, fragrance, treatment scheduling, and your own observations live here.</p><div className="mt-5 grid gap-2 grid-cols-2 sm:grid-cols-4">{[[Beaker,experiments.length,'active tests'],[Heart,favorites.length,'favorites'],[Sparkles,reactions.length,'reaction notes'],[Package,products.length,'products']].map(([Icon,value,label])=>{const C=Icon as typeof Beaker;return <div key={String(label)} className="rounded-2xl bg-white/70 p-4"><C size={14}/><p className="mt-2 font-serif text-2xl">{String(value)}</p><p className="text-[9px] text-[#91848b]">{String(label)}</p></div>})}</div></section>
    <nav className="flex gap-2 overflow-x-auto pb-1">{([['products','Products'],['looks','Look Builder'],['fragrance','Fragrance'],['treatments','Treatments'],['learn','Learn']] as const).map(([key,label])=><button key={key} type="button" onClick={()=>setTab(key)} className={`shrink-0 rounded-full px-4 py-2 text-xs ${tab===key?'bg-[#4b3d46] text-white':'border border-[#eadde2] bg-white'}`}>{label}</button>)}</nav>

    {tab==='products'?<div className="grid gap-4 lg:grid-cols-[1fr_.7fr]"><section className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><h2 className="font-serif text-2xl">Product shelf</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{products.slice(0,16).map(p=><Link key={p.id} href={`/beauty/lab?productId=${p.id}`} className="rounded-2xl bg-[#faf6f4] p-4"><p className="text-xs font-semibold">{p.name}</p><p className="mt-1 text-[9px] text-[#93858d]">{p.category}{p.openedAt?` · opened ${new Date(p.openedAt).toLocaleDateString()}`:''}</p>{p.reaction?<p className="mt-2 line-clamp-2 text-[10px]">{p.reaction}</p>:null}</Link>)}</div></section><details className="h-fit rounded-[26px] border border-[#eee2e6] bg-white p-5" open><summary className="cursor-pointer font-serif text-2xl">Start a product test</summary><form action={createBeautyProductAction} className="mt-4 space-y-2"><input name="name" required placeholder="Product name" className={field}/><input name="category" required placeholder="Category" className={field}/><textarea name="ingredients" rows={2} placeholder="Ingredients / actives" className={field}/><input name="openedAt" type="date" className={field}/><input name="expiresAt" type="date" className={field}/><input name="routinePosition" placeholder="Routine position" className={field}/><button type="submit" className="rounded-full bg-[#4b3d46] px-4 py-2.5 text-xs text-white">Start testing</button></form></details></div>:null}

    {tab==='looks'?<div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><section className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><div className="flex items-center gap-2"><WandSparkles size={16}/><h2 className="font-serif text-2xl">Look Builder</h2></div><p className="mt-4 text-[10px] text-[#91848b]">Occasion</p><div className="mt-2 flex flex-wrap gap-1.5">{occasions.map(x=><button key={x} type="button" onClick={()=>setOccasion(x)} className={`rounded-full border px-3 py-1.5 text-[10px] ${occasion===x?'border-[#c99aac] bg-[#fff1f5]':'border-[#eadde2]'}`}>{x}</button>)}</div><p className="mt-4 text-[10px] text-[#91848b]">Mood</p><div className="mt-2 flex flex-wrap gap-1.5">{moods.map(x=><button key={x} type="button" onClick={()=>setMood(x)} className={`rounded-full border px-3 py-1.5 text-[10px] ${mood===x?'border-[#c99aac] bg-[#fff1f5]':'border-[#eadde2]'}`}>{x}</button>)}</div><label className="mt-4 block text-[10px] text-[#91848b]">Time · {minutes} min<input type="range" min={10} max={45} step={5} value={minutes} onChange={e=>setMinutes(Number(e.target.value))} className="mt-2 w-full"/></label></section><section className="rounded-[26px] border border-[#eee2e6] bg-[#fff8fa] p-5"><p className="text-[9px] uppercase tracking-[.14em] text-[#a47f91]">Proposed look</p><h3 className="mt-1 font-serif text-3xl">{mood} {occasion} Look</h3><div className="mt-4 grid gap-2 sm:grid-cols-2">{currentSteps.map((x,i)=><div key={x} className="rounded-xl bg-white p-3 text-xs"><span className="mr-2 text-[#b17c91]">{i+1}</span>{x}</div>)}</div><div className="mt-4 flex flex-wrap gap-2">{makeupProducts.map(p=><span key={p.id} className="rounded-full bg-white px-3 py-1.5 text-[9px]">{p.name}</span>)}</div><button type="button" disabled={pending} onClick={saveLook} className="mt-5 rounded-full bg-[#4b3d46] px-5 py-2.5 text-xs text-white disabled:opacity-40">Save look</button></section><section className="lg:col-span-2 rounded-[26px] border border-[#eee2e6] bg-white p-5"><h2 className="font-serif text-2xl">Recent Looks</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{looks.length?looks.map(x=><div key={x.id} className="rounded-2xl bg-[#faf6f4] p-4"><p className="text-xs font-semibold">{x.name}</p><p className="mt-1 text-[9px] text-[#91848b]">{x.occasion} · {x.plannedMinutes}m · used {x.useCount}×</p><div className="mt-2 space-y-1">{x.steps.slice(0,4).map(s=><p key={s} className="text-[9px]">• {s}</p>)}</div><button type="button" disabled={pending} onClick={()=>repeatLook(x.id)} className="mt-3 inline-flex items-center gap-1 rounded-full bg-white px-3 py-2 text-[10px]"><Play size={10}/>Repeat Look</button></div>):<p className="text-xs text-[#91848b]">Save your first look to build history.</p>}</div></section></div>:null}

    {tab==='fragrance'?<div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><section className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><div className="flex items-center gap-2"><SprayCan size={16}/><h2 className="font-serif text-2xl">Add fragrance</h2></div><div className="mt-4 space-y-2"><input value={fragranceName} onChange={e=>setFragranceName(e.target.value)} placeholder="Fragrance name" className={field}/><input value={family} onChange={e=>setFamily(e.target.value)} placeholder="Family · floral, woody…" className={field}/><select value={daypart} onChange={e=>setDaypart(e.target.value)} className={field}><option value="day">Day</option><option value="evening">Evening</option><option value="anytime">Anytime</option></select><select value={fragranceOccasion} onChange={e=>setFragranceOccasion(e.target.value)} className={field}>{occasions.map(x=><option key={x}>{x}</option>)}</select><button type="button" disabled={!fragranceName.trim()||pending} onClick={addFragrance} className="rounded-full bg-[#4b3d46] px-4 py-2.5 text-xs text-white disabled:opacity-40">Add fragrance</button></div></section><section className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><h2 className="font-serif text-2xl">Fragrance wardrobe</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fragrances.length?fragrances.map(x=><div key={x.id} className="rounded-2xl bg-[linear-gradient(145deg,#fffaf7,#f1e9f3)] p-4"><p className="font-serif text-xl">{x.name}</p><p className="mt-1 text-[9px] text-[#91848b]">{x.family??'Family not tagged'}</p><div className="mt-3 flex flex-wrap gap-1">{[...x.dayparts,...x.occasions].map(tag=><span key={tag} className="rounded-full bg-white px-2 py-1 text-[8px]">{tag}</span>)}</div></div>):<p className="text-xs text-[#91848b]">Your fragrance wardrobe is empty.</p>}</div></section></div>:null}

    {tab==='treatments'?<div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><section className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><div className="flex items-center gap-2"><CalendarDays size={16}/><h2 className="font-serif text-2xl">Treatment Scheduler</h2></div><div className="mt-4 space-y-2"><input value={treatmentName} onChange={e=>setTreatmentName(e.target.value)} placeholder="Treatment name" className={field}/><select value={treatmentArea} onChange={e=>setTreatmentArea(e.target.value)} className={field}><option value="face">Face</option><option value="body">Body</option><option value="hair">Hair</option></select><div className="flex flex-wrap gap-1.5">{days.map((d,i)=><button key={d} type="button" onClick={()=>setSelectedDays(c=>c.includes(i)?c.filter(x=>x!==i):[...c,i])} className={`rounded-full border px-2.5 py-1.5 text-[9px] ${selectedDays.includes(i)?'border-[#c99aac] bg-[#fff1f5]':'border-[#eadde2]'}`}>{d}</button>)}</div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={strong} onChange={e=>setStrong(e.target.checked)}/>Mark as strong treatment for Compatibility Guard</label><button type="button" disabled={!treatmentName.trim()||pending} onClick={addSchedule} className="rounded-full bg-[#4b3d46] px-4 py-2.5 text-xs text-white disabled:opacity-40">Save schedule</button></div></section><section className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><h2 className="font-serif text-2xl">Saved schedules</h2><div className="mt-4 space-y-2">{schedules.length?schedules.map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-2xl bg-[#faf6f4] p-4"><div><p className="text-xs font-semibold">{x.treatmentName}</p><p className="mt-1 text-[9px] text-[#91848b]">{x.area} · {x.weekdays.length?x.weekdays.map(d=>days[d]).join(', '):'No weekdays'}{x.strongTreatment?' · strong':''}</p></div><button type="button" disabled={pending} onClick={()=>toggleSchedule(x)} className={`rounded-full px-3 py-2 text-[9px] ${x.enabled?'bg-[#edf3e9] text-[#62715d]':'bg-white border'}`}>{x.enabled?'On':'Off'}</button></div>):<p className="text-xs text-[#91848b]">No treatment schedule saved.</p>}</div><Link href="/beauty/calendar" className="mt-4 inline-flex items-center gap-1 text-[10px] font-semibold">Open Beauty Calendar <ArrowRight size={10}/></Link></section></div>:null}

    {tab==='learn'?<section className="grid gap-4 lg:grid-cols-2"><article className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><h2 className="font-serif text-2xl">What worked?</h2><p className="mt-2 text-xs text-[#91848b]">Glow separates your notes from claims about efficacy.</p><div className="mt-4 space-y-2">{reactions.length?reactions.map(p=><div key={p.id} className="rounded-2xl bg-[#faf6f4] p-4"><p className="text-xs font-semibold">{p.name}</p><p className="mt-1 text-[10px] leading-4">{p.reaction}</p><p className="mt-2 text-[9px] text-[#91848b]">Decision: {p.repurchase==='yes'?'Keep / repurchase':p.repurchase==='no'?'Stopped':p.repurchase==='maybe'?'Unsure':'Still testing'}</p></div>):<p className="text-xs text-[#91848b]">Add product reaction notes to build evidence.</p>}</div></article><article className="rounded-[26px] border border-[#eee2e6] bg-white p-5"><h2 className="font-serif text-2xl">Specialist tools</h2><div className="mt-4 space-y-2"><Link href="/beauty/gua-sha" className="block rounded-2xl bg-[#eff4ea] p-4 text-xs font-semibold">Guided Gua Sha →</Link><Link href="/beauty/progress" className="block rounded-2xl bg-[#f6eff4] p-4 text-xs font-semibold">Evidence-based Beauty Progress →</Link><Link href="/skincare" className="block rounded-2xl bg-[#fff7ed] p-4 text-xs font-semibold">Skincare specialist workspace →</Link><Link href="/hair" className="block rounded-2xl bg-[#f4e7dc] p-4 text-xs font-semibold">Hair specialist workspace →</Link></div><p className="mt-4 text-[10px] leading-4 text-[#91848b]">{routines.length} saved Beauty routine step{routines.length===1?'':'s'} currently feed Ritual Mode.</p></article></section>:null}
  </div>;
}
