import Link from 'next/link';
import { CalendarClock, CheckCircle2, FlaskConical, Heart, MoonStar, Package, Sparkles, SunMedium } from 'lucide-react';
import type { BeautyRoutine } from '@/lib/types';

type BeautyProductLite={id:string;name:string;category:string;repurchase:string|null;expiresAt:Date|null;reaction?:string|null;usageFrequency?:string|null;photoUrl?:string|null};
type EventLite={id:string;title:string;startAt:Date;location:string|null};
function dayLabel(date:Date){return date.toLocaleDateString('en-US',{month:'short',day:'numeric'})}

export function BeautyExperience({routines,products,upcomingAppointments}:{routines:BeautyRoutine[];products:BeautyProductLite[];upcomingAppointments:EventLite[]}){
  const am=routines.filter(r=>r.timeOfDay==='morning').sort((a,b)=>a.stepOrder-b.stepOrder);
  const pm=routines.filter(r=>r.timeOfDay==='evening'||r.timeOfDay==='night').sort((a,b)=>a.stepOrder-b.stepOrder);
  const reactions=products.filter(p=>Boolean(p.reaction?.trim())).slice(0,4);
  const favorites=products.filter(p=>p.repurchase==='yes').slice(0,4);
  const nextTreatment=upcomingAppointments[0]??null;
  const activeProducts=products.filter(p=>p.repurchase!=='no').length;

  return <div className="space-y-5">
    <header className="grid gap-5 lg:grid-cols-[1fr_320px] lg:items-end"><div><p className="glow-eyebrow text-[#C9727E]">Beauty</p><h1 className="glow-display mt-1 text-[42px] leading-[1.02] tracking-[-.025em] sm:text-[54px]">Beauty ✧</h1><p className="mt-2 text-[13px] text-[#8A8078]">Care for your skin. Elevate your glow.</p></div><div className="rounded-[18px] bg-[linear-gradient(145deg,#F7E7E4,#EAD8D0)] p-5"><p className="glow-display text-[15px] italic leading-6 text-[#4A3D37]">“Beauty is about being comfortable in your own skin.”</p></div></header>

    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><div className="flex items-center justify-between"><p className="text-[9.5px] font-semibold uppercase tracking-[.1em] text-[#8A8078]">AM Routine Steps</p><SunMedium size={13} className="text-[#C9727E]"/></div><p className="glow-display mt-3 text-[28px]">{am.length}</p><div className="mt-3 h-1 rounded-full bg-[#F1E7E3]"><div className="h-full rounded-full bg-[#C9727E]" style={{width:`${Math.min(100,am.length*15)}%`}}/></div></div>
      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><div className="flex items-center justify-between"><p className="text-[9.5px] font-semibold uppercase tracking-[.1em] text-[#8A8078]">PM Routine Steps</p><MoonStar size={13} className="text-[#7C6B9C]"/></div><p className="glow-display mt-3 text-[28px]">{pm.length}</p><div className="mt-3 h-1 rounded-full bg-[#F1E7E3]"><div className="h-full rounded-full bg-[#B9A8CB]" style={{width:`${Math.min(100,pm.length*15)}%`}}/></div></div>
      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><div className="flex items-center justify-between"><p className="text-[9.5px] font-semibold uppercase tracking-[.1em] text-[#8A8078]">Products in Use</p><Package size={13} className="text-[#C9727E]"/></div><p className="glow-display mt-3 text-[28px]">{activeProducts}</p><p className="mt-1 text-[9.5px] text-[#9A9088]">{favorites.length} marked repurchase</p></div>
      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><div className="flex items-center justify-between"><p className="text-[9.5px] font-semibold uppercase tracking-[.1em] text-[#8A8078]">Upcoming Treatments</p><CalendarClock size={13} className="text-[#C9727E]"/></div><p className="glow-display mt-3 text-[28px]">{upcomingAppointments.length}</p><p className="mt-1 truncate text-[9.5px] text-[#9A9088]">{nextTreatment?`${nextTreatment.title} · ${dayLabel(nextTreatment.startAt)}`:'None scheduled'}</p></div>
    </section>

    <section className="grid gap-4 xl:grid-cols-[1fr_1fr_1fr_.8fr]">
      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><div className="flex items-center justify-between"><h2 className="glow-display text-[17px]">Today’s Routine</h2><Link href="/beauty/lab" className="text-[10px] text-[#C9727E]">View full</Link></div><div className="mt-3 flex gap-4 text-[10.5px]"><span className="border-b border-[#C9727E] pb-2 font-medium text-[#C9727E]">AM Routine</span><span className="pb-2 text-[#9A9088]">PM Routine</span></div><div className="mt-3 space-y-2.5">{am.length?am.slice(0,6).map(step=><div key={step.id} className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-[8px] bg-[#FDF3F2] text-[#C9727E]"><Sparkles size={11}/></span><span className="min-w-0 flex-1"><span className="block text-[11px] font-medium">{step.name}</span>{step.products?.length?<span className="block truncate text-[9.5px] text-[#9A9088]">{step.products.join(', ')}</span>:null}</span><CheckCircle2 size={12} className="text-[#C9727E]"/></div>):<p className="text-[11px] text-[#9A9088]">No AM routine steps yet.</p>}</div></div>

      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><h2 className="glow-display text-[17px]">Skin Insights</h2><div className="mx-auto mt-5 flex h-44 w-44 items-center justify-center rounded-full border border-[#EAD9D4] bg-[radial-gradient(circle,#FDEBED_0_18%,#F9E4E7_19%_35%,#FFF_36%)]"><div className="text-center"><p className="glow-display text-[26px]">{reactions.length}</p><p className="text-[9px] uppercase tracking-[.1em] text-[#9A9088]">reaction notes</p></div></div><p className="mt-4 text-center text-[10px] leading-4 text-[#8A8078]">Glow uses your real product reactions and repurchase choices instead of inventing a skin-health score.</p><Link href="/beauty/lab" className="mt-3 inline-flex text-[10px] text-[#C9727E]">View Trends →</Link></div>

      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><div className="flex items-center justify-between"><h2 className="glow-display text-[17px]">Recent Progress</h2><Link href="/beauty/lab" className="text-[10px] text-[#C9727E]">View all</Link></div><div className="mt-4 space-y-3">{reactions.length?reactions.map(product=><div key={product.id} className="flex items-center gap-3"><div className="h-10 w-10 shrink-0 rounded-[10px] bg-[linear-gradient(145deg,#E8D7CF,#F6EEE8)]"/><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-medium">{product.name}</p><p className="truncate text-[9.5px] text-[#9A9088]">{product.reaction}</p></div><span className="text-[9px] text-[#5A6E52]">Logged</span></div>):<p className="text-[11px] text-[#9A9088]">Add product reaction notes in Beauty Lab to build progress history.</p>}</div></div>

      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><h2 className="glow-display text-[17px]">This Week</h2><div className="mt-4 space-y-4">{[...am.slice(0,2),...pm.slice(0,2)].map((step,index)=><div key={step.id} className="flex items-start gap-2"><span className="flex h-5 w-5 items-center justify-center rounded-[5px] border border-[#F1D4D9] text-[#C9727E]">✓</span><div><p className="text-[10.5px] font-medium">{step.name}</p><div className="mt-2 flex gap-1">{'MTWTFSS'.split('').map((d,i)=><span key={`${d}-${i}`} className={`flex h-4 w-4 items-center justify-center rounded-full text-[7px] ${i<=index+2?'bg-[#FBE4E8] text-[#C9727E]':'text-[#B5ACA5]'}`}>{d}</span>)}</div></div></div>)}</div><Link href="/beauty/lab" className="mt-4 inline-flex text-[10px] text-[#C9727E]">View Weekly Plan →</Link></div>
    </section>

    <section className="grid gap-4 lg:grid-cols-[1.2fr_.7fr_.85fr]">
      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><h2 className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#4A4440]">Quick Actions</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">{[['Log Treatment','/beauty/lab'],['Add Product','/beauty/lab'],['Compare Progress','/beauty/lab'],['Scan Ingredient','/beauty/lab'],['Set Reminder','/reminders']].map(([label,href])=><Link key={label} href={href} className="text-center"><span className="mx-auto flex h-9 w-9 items-center justify-center rounded-full bg-[#FDF3F2] text-[#C9727E]"><FlaskConical size={13}/></span><span className="mt-2 block text-[9.5px] text-[#4A4440]">{label}</span></Link>)}</div></div>
      <div className="rounded-[18px] border border-[#F1E7E3] bg-white p-4"><h2 className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#4A4440]">Upcoming Treatments</h2><div className="mt-4 space-y-3">{upcomingAppointments.length?upcomingAppointments.slice(0,3).map(event=><div key={event.id}><p className="text-[11px] font-medium">{event.title}</p><p className="text-[9.5px] text-[#9A9088]">{dayLabel(event.startAt)} · {event.startAt.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</p></div>):<p className="text-[11px] text-[#9A9088]">No treatments scheduled.</p>}</div><Link href="/calendar" className="mt-4 inline-flex text-[10px] text-[#C9727E]">View All →</Link></div>
      <div className="rounded-[18px] border border-[#F1E7E3] bg-[linear-gradient(145deg,#FFF,#FFF5F4)] p-5"><div className="flex items-center gap-2"><Heart size={13} className="text-[#C9727E]"/><h2 className="text-[10px] font-semibold uppercase tracking-[.1em]">Glow Insight</h2></div><p className="glow-display mt-5 text-[17px] italic leading-6 text-[#4A4440]">Your routine is built from {am.length+pm.length} real steps and {products.length} tracked products. Consistency starts with knowing what you actually use.</p><Link href="/beauty/lab" className="mt-4 inline-flex text-[10px] text-[#C9727E]">View Recommendations →</Link></div>
    </section>
  </div>;
}
