'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Brain, CalendarDays, Camera, CheckCircle2, Clock3, Compass, FlaskConical, Heart, Layers3, ListChecks, Mic, Moon, Search, ShieldCheck, Sparkles, Sun, Target, WandSparkles } from 'lucide-react';

type Mode = 'Today' | 'Blueprint' | 'Study Map' | 'Observations' | 'Experiments' | 'Playbook' | 'Routines + Habits' | 'System Map' | 'Evidence' | 'Progress' | 'Archive';
type Confidence = 'Source idea' | 'Trying' | 'Promising' | 'Works for me' | 'Retired';
type StudyArea = 'Identity' | 'Productivity' | 'Energy' | 'Mindset' | 'Digital Life' | 'Environment' | 'Relationships' | 'Career + Money' | 'Face' | 'Skin' | 'Hair' | 'Makeup' | 'Brows + Lashes' | 'Smile' | 'Body + Grooming' | 'Style' | 'Color + Contrast' | 'Posture + Presence' | 'Photos + Angles' | 'Expression + Voice';

type StudyNote = { id:string; createdAt:string; area:StudyArea; title:string; detail:string; source:string; confidence:Confidence; evidence:string; archived:boolean };
type Experiment = { id:string; createdAt:string; area:StudyArea; title:string; change:string; measure:string; result:string; status:'Planned'|'Testing'|'Complete' };
type MemoryState = { notes:StudyNote[]; experiments:Experiment[]; focusAreas:StudyArea[]; adoptedPackKeys:string[]; completedPackSteps:string[]; favoriteLook:string };
type SourceSection = { source:string; theme:string; points:string[] };
type HabitPack = { key:string; title:string; kind:'Routine'|'Habit pack'|'Review'|'Experiment'; frequency:string; purpose:string; steps:string[]; caution?:string; links:string[] };
type SystemUpgrade = { page:string; href:string; role:string; upgrades:string[] };

const STORAGE_KEY='glow:study-yourself-hotter:v2';
const LEGACY_KEY='glow:study-yourself-hotter:v1';
const MODES:Mode[]=['Today','Blueprint','Study Map','Observations','Experiments','Playbook','Routines + Habits','System Map','Evidence','Progress','Archive'];
const AREAS:StudyArea[]=['Identity','Productivity','Energy','Mindset','Digital Life','Environment','Relationships','Career + Money','Face','Skin','Hair','Makeup','Brows + Lashes','Smile','Body + Grooming','Style','Color + Contrast','Posture + Presence','Photos + Angles','Expression + Voice'];
const CONFIDENCE:Confidence[]=['Source idea','Trying','Promising','Works for me','Retired'];
const DEFAULTS:MemoryState={notes:[],experiments:[],focusAreas:['Identity','Productivity','Energy','Face','Hair','Style'],adoptedPackKeys:[],completedPackSteps:[],favoriteLook:''};

const areaDescriptions:Record<StudyArea,string>={
 Identity:'Who you are becoming, values, mission, signature identity, standards and repeatable choices.',
 Productivity:'Priorities, planning, time blocking, master lists, themes, batching and sustainable output.',
 Energy:'Mental vs physical energy, sleep, movement, rest, friction and capacity planning.',
 Mindset:'Self-talk, gratitude, reflection, beliefs, emotional energy and how you respond to setbacks.',
 'Digital Life':'Doom scrolling, phone friction, social feeds, camera roll, email, files and digital clean-up.',
 Environment:'Clean-slate resets, object homes, room systems, visual clutter and spaces that support you.',
 Relationships:'Energy-giving vs draining relationships, boundaries, reciprocity and social bandwidth.',
 'Career + Money':'Work direction, job goals, income, financial calm, growth and high-leverage work.',
 Face:'Balance, facial styling, massage, framing and appearance observations.',
 Skin:'SPF, texture, hydration, finish, skincare tolerance and long-term skin habits.',
 Hair:'Part, volume, length, porosity, scalp health, heat, damage, framing and styling patterns.',
 Makeup:'Placement, coverage, contrast, symmetry, finishes and repeatable looks.',
 'Brows + Lashes':'Shape, balance, curl, lift, density and eye framing.',
 Smile:'Teeth, lips, lip color, expression, smile balance and grooming observations.',
 'Body + Grooming':'Body care, fragrance, exfoliation, nails, grooming and polish.',
 Style:'Silhouette, proportions, capsule wardrobe, signature pieces, shoes, bags and outfit formulas.',
 'Color + Contrast':'Undertone experiments, red, colors near the face, eye-color echoes and visual harmony.',
 'Posture + Presence':'Body language, shoulder/neck position, movement, confidence cues and how you carry a look.',
 'Photos + Angles':'Lighting, softness, catchlights, camera height, 45° body angle, pose and repeatable setups.',
 'Expression + Voice':'Smile, eye expression, pacing, warmth, vocal presence and social presentation.',
};

const sourceLibrary:SourceSection[]=[
 {source:'How I plan & organize my entire life',theme:'Productivity as efficiency for more rest and life',points:[
  'Productivity is framed as working smarter so goals are reached with more room for rest and play, not as personal worth or endless output.',
  'Planning system requirements: daily planner, weekly planner, monthly calendar, habit tracker and a place to time block.',
  'Use whatever capture tool works in the moment, including Notes, Calendar, Reminders, physical paper and temporary mental-to-do capture, then organize later.',
  'Avoid an overflowing daily to-do list. Separate the daily plan from long-horizon ideas so overplanning does not create paralysis.',
  'Maintain a master “fluff list” with buckets for important/time-sensitive fluff, general fluff, nice-to-do and future.',
  'Normal-energy days use three priorities. High-energy days can use a six-task ranked Carnegie-style sequence. Low-energy days can use one true priority.',
  'Study mental energy and physical energy separately. Schedule cognitively demanding work when mental energy is strongest and physical work when physical energy is strongest.',
  'The first 15–20 minutes of the morning set the tone. The source favors walking or meditation over immediate scrolling.',
  'Identify procrastination triggers and add friction. Examples in the source include app blockers, physical phone-blocking tools and scheduled social-media limits.',
  'Use daily themes so similar work is batched and decisions are reduced.',
  'Anchor recurring routines to similar times to reduce decision fatigue.',
  'Use one weekly plan/reset/reflection day. Ask what worked and what did not, then change the system instead of blaming yourself.',
  'Weekly planning order: review monthly/calendar commitments → weekly items → next day → priorities → time blocks.',
  'Time blocking translates priorities into reality and exposes an overloaded list. Overestimate time slightly and deliberately leave rest and spontaneity.',
  'Use “only this after this” rewards cautiously as behavioral friction/reward, plus habit stacking to pair a new behavior with an established one.',
  'Advanced organization ideas: clear camera roll regularly, label email and files, keep space clean, make the bed, give every object a home, use baskets for recurring piles, implement changes gradually and outsource when it truly saves high-value time.'
 ]},
 {source:'December Lock-In challenge',theme:'30-day momentum, clean slate and visible proof',points:[
  'Treat a 30-day period as a launchpad rather than waiting for an arbitrary fresh start.',
  'Start with a clean slate: choose one overdue physical clean-up and one digital clean-up rather than trying to overhaul everything at once.',
  'Digital clean-up ideas from the source: unfollow accounts that do not align, archive old social content, delete unused apps/contacts/notes and reduce visual/digital clutter.',
  'Create a private 30-day capsule that holds goals, memories, check-ins, wins, thoughts, links, photos and motivating references.',
  'Choose a small number of micro goals instead of dozens. The source uses four categories: fitness, discipline, career and mental health.',
  'Use a daily 3-2-1 check-in: three gratitudes, two pieces of proof that you showed up, one answer to “What did I do today that made me 1% better?”',
  'Make proof private and low-pressure. Screenshots, photos, links, journaling, step count, applications or a cleaned room can all count as evidence.',
  'Romanticize the process with photos, music, quotes and aesthetic cues so discipline feels more inviting.',
  'No-doom-scroll practices in the source: charge the phone away from bed, redirect the scrolling urge toward your own life, and use a short timer when you intentionally scroll.',
  'Identity question: “What would the next version of me be doing right now?” Use it as a prompt, not as permission to ignore capacity or rest.'
 ]},
 {source:'2026 successful year / treat life like a business',theme:'Life strategy, identity, systems and operating procedures',points:[
  'Treat your life as something worthy of systems, feedback and intentional investment rather than relying on motivation.',
  'Build a yearly “CEO vision”: what do I stand for, what should my life represent, what am I prioritizing and how do I want to feel?',
  'Organize life into departments such as mind, body, money, relationships and lifestyle so goals have a home.',
  'Define a personal brand identity: look, feel, voice, energy and signature presentation. The source suggests a recognizable signature look most of the time while leaving room for variation.',
  'Build a capsule wardrobe and digital presence that reflect the chosen identity instead of stale versions of yourself.',
  'Think of health/energy as infrastructure: hydration, daylight, movement, sleep and nourishing meals are presented as baseline operating habits.',
  'Sponsored supplement/product recommendations are source material only and should not be silently adopted into Glow routines.',
  'Use an “emotional CFO” review: what drains energy, who drains it, what gives energy back and which personal policies protect against burnout or impulsive reactions?',
  'Create SOPs for mornings, workdays, lifestyle and nights. Systems should reduce reliance on motivation.',
  'Morning SOP examples in the source: wake, hydrate, mindfulness/gratitude, make bed, daylight/walk, movement, nourishing intake, intentional energy cue, aesthetic touch, top three.',
  'Workday SOP examples: time blocks, batching, notifications off during deep work, breaks outside and a tidy work area.',
  'Lifestyle automation examples: visible water, 10-minute nightly tidy, digital boundaries, recurring essentials, savings transfers, grocery/meal systems and cleaning support.',
  'Habit stacking examples: affirmations while brushing teeth, motivating audio during a walk/workout, journaling with an established morning drink and audiobooks during walking.'
 ]},
 {source:'Reinvent your identity / complete life audit',theme:'Audit → pattern autopsy → release → identity design → micro practice',points:[
  'Audit the current state before adding goals. For each life area ask: Where am I now? What one change would have the biggest impact? What am I avoiding?',
  'Areas discussed include health/energy, career/money, mindset/personal development, relationships, self-care, home/environment and free time; the source describes eight areas even though the transcript supplied here does not fully enumerate an eighth distinct label.',
  'Look at whether movement feels supportive or punitive, food/sleep/hydration patterns, symptoms being ignored, work meaning/growth, money fear, willingness to learn, relationship reciprocity, self-talk, physical environment and how free time is actually spent.',
  'Autopsy recurring identities and ask what each identity protected you from, what it helped you survive and whether it still serves you.',
  'Allow closure for an old identity rather than instantly forcing a new one. The source suggests gratitude/farewell writing as a symbolic practice.',
  'Design the next identity by asking what that version naturally does in each life area. Keep the description simple and behavioral rather than making it only a distant goal.',
  'Use micro identity practices: choose a few small repeated behaviors that make the new identity familiar and track whether they become easier over time.',
  'Start with the area that creates the most leverage across the rest of life rather than changing everything at once.'
 ]},
 {source:'Scientific Ways To Look Hotter (transcript supplied)',theme:'Appearance tactics and creator-stated research claims',points:[
  'The transcript strongly prioritizes daily sunscreen and retinoids for long-term skin appearance, but all percentages and study claims remain source claims until independently verified.',
  'The transcript recommends consistency over intensity and explicitly says retinoid tolerance matters; it gives a creator protocol of gradual use rather than expecting instant results.',
  'Sleep is presented as an appearance and functioning input; the source recommends 7–9 hours and lower-friction pillow fabrics for skin/hair.',
  'Hair sections emphasize healthy-looking hair, scalp care, lower heat, heat protectant, avoiding very tight styles, deep conditioning and matching products to porosity/density/damage rather than assuming one routine fits everyone.',
  'The rosemary-oil discussion is cautious even within the source: it cites one study, says it may help some people, and says not to assume growth beyond biological capacity.',
  'Makeup is framed as enhancement: even tone, defined lashes/eyes, lip color, brow balance and lighter strategic coverage rather than masking everything.',
  'Symmetry suggestions in the source include testing hair part, brow balance, eye makeup and smile practice. These belong in personal experiments, not permanent rules.',
  'Color ideas include testing the right red for context/undertone and echoing eye color in an outfit. Vein-based undertone identification is source advice and should be treated as an experiment rather than a diagnostic test.',
  'Style ideas include monochrome vertical lines, high-waisted proportions, nude/skin-adjacent shoes for leg-line continuity and a rule-of-thirds approach to outfit proportions.',
  'Posture sequence in the transcript: feet about hip-width, weight shifted, core engaged, lengthen through crown, shoulders back/down, arms relaxed. It also suggests chin-tuck awareness for forward-head posture.',
  'Photo ideas: soft window light or a large close light source, 45° lighting, catchlights, body turned about 45°, chin slightly out/down, slight eye narrowing, hand separated from torso and camera a little above eye level.',
  'The source rejects permanent bone-structure claims for gua sha/jade rollers and says temporary de-puffing may occur. It also rejects claims that trims speed root growth, biotin helps everyone, collagen is a “time machine” or pores can be permanently shrunk.',
  'The creator 7-day protocol includes gathering SPF/retinoid/hair mask/heat protectant/whitening products, then skin, hair, brows/lashes, posture, color and photo documentation days. Glow should treat product/medical-adjacent items as review-before-adopting rather than automatically installing them.',
  'Advanced tactics supplied: gentle jaw release/massage for tension, gentle facial massage for circulation rather than permanent contouring, fragrance layering by similar scent profiles and pulse points, hair-porosity-specific care and exfoliating-glove body care 2–3 times per week with non-aggressive pressure.'
 ]},
];

const routinePacks:HabitPack[]=[
 {key:'daily-priority-engine',title:'Daily Priority Engine',kind:'Routine',frequency:'Daily · adapts to energy',purpose:'Keep the day small enough to finish while protecting meaningful work.',steps:['Brain dump into the master list, not directly into today.','Choose capacity: Low → 1 priority; Normal → 3 priorities; High → up to 6 ranked tasks.','Make the first priority something tied to a goal, income, deadline or important life movement.','Time block priorities before secondary tasks.','Overestimate duration slightly and leave open space for recovery/spontaneity.','At day close, move unfinished work intentionally instead of silently rolling everything forward.'],links:['/today','/planning','/tasks','/goals']},
 {key:'master-fluff-list',title:'Master Fluff List',kind:'Habit pack',frequency:'Capture anytime · review weekly',purpose:'Get mental clutter out of the daily plan without losing it.',steps:['Capture anything that enters your head.','Sort into Important / Time-sensitive fluff.','Sort into General fluff.','Sort into Nice to do.','Sort into Future.','Pull into a day only when there is actual time/capacity.'],links:['/notes','/tasks','/inbox','/planning']},
 {key:'energy-mapping',title:'Mental + Physical Energy Mapping',kind:'Experiment',frequency:'2 weeks, then seasonal re-check',purpose:'Learn when your brain and body work best instead of using one generic “energy” score.',steps:['Rate mental energy in morning, afternoon, evening and night.','Rate physical energy separately.','Note sleep, meals, calendar load and workout timing.','Compare when deep work feels easiest versus when movement feels easiest.','Move work and workouts only after a repeated pattern appears.'],links:['/brain','/wellness','/fitness','/planning']},
 {key:'morning-tone',title:'First 20 Minutes',kind:'Routine',frequency:'Morning',purpose:'Set the tone without building a 500-step routine.',steps:['Do not open infinite-scroll feeds first.','Hydrate.','Choose one grounding input: short walk, daylight, meditation, gratitude or quiet.','Make bed / do one tiny completion cue.','Review today’s priority count only after the grounding cue.'],links:['/today','/routines','/habits','/wellness']},
 {key:'weekly-reset-review',title:'Weekly Plan + Reflect',kind:'Review',frequency:'Weekly',purpose:'Turn mistakes into system improvements.',steps:['Ask: What worked this week?','Ask: What did not work?','Review monthly/calendar commitments first.','Review weekly tasks and goals.','Choose next week’s themes and non-negotiables.','Build Monday from the weekly plan, then time block.','Change routines that repeatedly fail instead of adding guilt.'],links:['/planning','/calendar','/goals','/routines','/brain']},
 {key:'digital-friction',title:'No Doom Scroll System',kind:'Habit pack',frequency:'Daily boundaries + weekly clean-up',purpose:'Protect focus and reduce automatic comparison/overstimulation.',steps:['Charge phone away from immediate bed reach when practical.','Use app limits/blockers for known trigger windows.','When intentionally scrolling, use a short timer.','Replace reflex scrolling with a concrete alternative: walk, capture your own memory, note, music or task.','Weekly: unfollow/mute stale feeds, delete unused apps and clear digital clutter.','Keep mornings and the last hour before bed as protected low-scroll windows when feasible.'],links:['/habits','/settings','/brain','/notes']},
 {key:'clean-slate',title:'Clean Slate Reset',kind:'Routine',frequency:'Monthly or seasonal',purpose:'Remove physical and digital drag without launching a giant overhaul.',steps:['Choose one physical space that has been avoided.','Finish that one space before adding another.','Choose one digital category: apps, contacts, notes, photos, files or social following.','Archive/delete what no longer serves the current season.','Give recurring piles a container or “home.”','Record what created clutter so Home can improve the system.'],links:['/home','/notes','/settings','/brain']},
 {key:'321-proof',title:'3-2-1 Proof Check-In',kind:'Habit pack',frequency:'Evening during a 30-day sprint',purpose:'Make progress visible without relying on motivation.',steps:['Write 3 things you are grateful for.','Save 2 pieces of proof that you showed up.','Answer 1 question: What did I do today that made me 1% better?','Keep proof private unless you choose otherwise.','At day 30, review the archive for patterns instead of judging isolated days.'],links:['/today','/memory','/timeline','/brain']},
 {key:'life-audit',title:'Life Audit + Identity Autopsy',kind:'Review',frequency:'Quarterly or at a major transition',purpose:'Understand the current system before forcing a new identity.',steps:['For each life area: Where am I now?','What one change would have the biggest impact?','What am I avoiding?','Name recurring identities/patterns.','Ask what each pattern protected or solved.','Decide what still serves you and what can be released.','Describe the next identity behaviorally: what does this version naturally do?','Choose only 3 micro identity practices for the next month.'],links:['/brain','/goals','/memory','/planning']},
 {key:'signature-identity',title:'Signature Identity + Look',kind:'Experiment',frequency:'Seasonal review',purpose:'Build a recognizable personal formula without locking yourself into one aesthetic.',steps:['Define how you want to look, feel, sound and carry yourself.','Choose signature hair variables to test.','Choose signature makeup variables to test.','Choose nail/grooming defaults.','Build repeatable outfit formulas and a capsule around what you actually wear.','Review digital presence for stale content that no longer represents you.','Keep variation available; a signature is a shortcut, not a cage.'],links:['/beauty/study-yourself-hotter','/closet','/hair','/makeup']},
 {key:'appearance-lab-7day',title:'7-Day Appearance Lab',kind:'Experiment',frequency:'Optional test week',purpose:'Test the supplied creator protocol without silently treating every claim/product as established fact.',steps:['Day 1 · Inventory only: what SPF, hair conditioning, heat protection and dental-care items are already owned? Mark anything medical/adjuvant for review before changing routines.','Day 2 · Skin foundation review: document the current AM/PM routine, tolerance and sun protection. Do not add actives automatically.','Day 3 · Hair condition test: deep-condition only if compatible with the existing hair plan; record softness, frizz and breakage feel.','Day 4 · Face framing: compare brow grooming, lash curl/mascara and symmetry choices in the same light.','Day 5 · Presence: practice posture sequence and photograph neutral vs intentional posture.','Day 6 · Color: test one red or another high-impact color near the face in context.','Day 7 · Document: repeat day-1 lighting/angle and write what actually changed.'],caution:'Source-derived beauty protocol. Product percentages, supplement/medication-adjacent claims and skincare active changes are not independently verified here and should not overwrite existing clinical skincare directions.',links:['/beauty/study-yourself-hotter','/skincare','/hair','/makeup','/closet']},
 {key:'photo-presence',title:'Photo + Presence Practice',kind:'Experiment',frequency:'Before events or monthly practice',purpose:'Learn your repeatable lighting, posture and camera setup.',steps:['Compare soft window light vs overhead light.','Try light about 45° off center and look for catchlights.','Compare straight-on vs body turned about 45°.','Compare neutral chin vs slightly out/down.','Keep lens distance and camera height consistent.','Test slightly-above-eye camera position.','Save what works as a personal photo formula, not a universal rule.'],links:['/beauty/study-yourself-hotter','/creative-studio','/closet']},
 {key:'ten-minute-tidy',title:'10-Minute Night Tidy',kind:'Routine',frequency:'Night',purpose:'Wake into a lower-friction environment.',steps:['Return objects to their homes.','Put recurring piles in assigned baskets/containers.','Clear one visible surface.','Set out what tomorrow needs.','Stop when the 10-minute reset is complete; deep cleaning belongs elsewhere.'],links:['/home','/routines','/today']},
];

const systemUpgrades:SystemUpgrade[]=[
 {page:'Today',href:'/today',role:'Capacity-aware command center',upgrades:['Show Low / Normal / High capacity and automatically suggest 1 / 3 / up to 6 priorities.','Keep Master Fluff off the main day unless there is room.','Show protected first-20-min morning cue and evening 3-2-1 check-in during active sprints.']},
 {page:'Planning',href:'/planning',role:'Reality-based time design',upgrades:['Planning order becomes commitments → weekly priorities → day theme → capacity → time blocks.','Warn when the task list cannot fit the available hours.','Overestimate blocks slightly and preserve blank recovery/spontaneity windows.']},
 {page:'Calendar',href:'/calendar',role:'Time truth',upgrades:['Layer daily themes and energy windows over fixed commitments.','Mark deep-work, movement, reset and open-space blocks differently.','Show what gets displaced before accepting new commitments.']},
 {page:'Tasks',href:'/tasks',role:'Execution only',upgrades:['Separate Today from Master Fluff / Nice-to-do / Future.','Rank needle-moving work above secondary tasks.','Support sequential “finish before next” mode for high-capacity days.']},
 {page:'Notes',href:'/notes',role:'Master capture + private thinking',upgrades:['Add Master Fluff template and Life Audit worksheet.','Capture identity letters, reflections and raw thoughts without forcing them into tasks.','Let Glow classify a note later rather than making capture complicated.']},
 {page:'Habits',href:'/habits',role:'Small repeatable identity practices',upgrades:['Add no-doom-scroll boundaries, first-20-min cue, 10-minute tidy, weekly reflection and optional 3-2-1 sprint check-in.','Use habit stacking and trigger/friction fields.','Track mental and physical energy correlations without declaring causation.']},
 {page:'Routines',href:'/routines',role:'SOP library',upgrades:['Add capacity-aware morning planning, weekly reflection, clean-slate reset and workday deep-focus SOPs.','Keep nighttime routine focused on reset, not squeezing in more productivity.','Let routines have Floor / Standard / Full versions.']},
 {page:'Brain',href:'/brain',role:'Pattern + identity intelligence',upgrades:['Add energy-map insights, procrastination trigger detection, what-worked/what-did-not review and identity-pattern autopsy.','Separate creator/source claims from personal evidence.','Surface patterns only after repeated data.']},
 {page:'Goals',href:'/goals',role:'Direction filter',upgrades:['Store yearly mission/why and departments.','Limit 30-day sprints to a few micro goals.','Show which daily priorities actually move goals.']},
 {page:'Projects',href:'/projects',role:'Outcome execution',upgrades:['Move multi-step glow-up or clean-slate efforts here instead of bloating habits.','Show next action, evidence and completion definition.']},
 {page:'Fitness',href:'/fitness',role:'Physical-energy system',upgrades:['Learn preferred workout windows separately from mental-focus windows.','Track posture practice and flexibility/mobility experiments where relevant.','Use energy/capacity to offer full or recovery versions.']},
 {page:'Wellness',href:'/wellness',role:'Energy + regulation',upgrades:['Track sleep, calm/overstimulation, recovery and self-talk context around productivity.','Support emotional-energy income/drain reflection without turning it into a score.']},
 {page:'Beauty',href:'/beauty',role:'Appearance command center',upgrades:['Connect the Study Yourself Hotter playbook to Get Ready recommendations.','Use only adopted “Works for me” rules for automatic suggestions.']},
 {page:'Skincare',href:'/skincare',role:'Skin routine truth',upgrades:['Track sun-protection adherence and active tolerance over months.','Keep source beauty claims in a review queue; never silently add a retinoid/acid/supplement because a transcript recommended it.']},
 {page:'Hair',href:'/hair',role:'Personal hair evidence lab',upgrades:['Track porosity/density/damage context, heat exposure, scalp care and outcomes.','Compare parts, volume, length/framing and conditioning results.','Avoid fake product-match percentages unless there is a real model/data source.']},
 {page:'Makeup',href:'/makeup',role:'Feature-enhancement lab',upgrades:['A/B test coverage, brow balance, lash emphasis, lip shades and symmetry strategies.','Save only repeatable personal recipes.']},
 {page:'Closet',href:'/closet',role:'Signature style + capsule',upgrades:['Build identity-aligned outfit formulas, proportion experiments, monochrome looks and context-aware red/color tests.','Track what gets worn rather than aspirational inventory only.']},
 {page:'Home',href:'/home',role:'Environment that reduces friction',upgrades:['Every object gets a home or an intentional holding zone.','Add 10-minute tidy and Clean Slate projects.','Track clutter recurrence so the storage system can be redesigned.']},
 {page:'Finance',href:'/finance',role:'Resource support',upgrades:['Connect yearly priorities to spending/investment choices.','Keep “invest in yourself” grounded in budgets and real tradeoffs, not permission for impulsive consumption.']},
 {page:'Work',href:'/work',role:'High-value output + career growth',upgrades:['Batch admin/deep work, use workday SOPs and identify what only you can do vs delegate.','Track career micro goals during sprints.']},
 {page:'Concierge',href:'/concierge',role:'Personal operator',upgrades:['Turn “I’m overwhelmed” into capacity → top priority → time block → what can wait.','Run clean-slate, weekly reset and identity-audit missions conversationally.']},
 {page:'Memory',href:'/memory',role:'Verified personal truth',upgrades:['Store adopted preferences and confirmed patterns, not every creator tip.','Keep source, date and whether a memory was explicit vs inferred.']},
 {page:'Timeline',href:'/timeline',role:'Visible proof over time',upgrades:['Save sprint evidence, experiments, identity shifts and before/after context as dated moments.','Review change across weeks/months instead of isolated “before/after” hype.']},
 {page:'Create',href:'/create',role:'Capture + proof',upgrades:['Let photos, screenshots, quotes, links and voice notes be routed into a Study packet or 30-day capsule.']},
 {page:'Settings',href:'/settings',role:'Friction + boundaries',upgrades:['Store preferred no-scroll windows, notification boundaries and default capacity behavior.']},
];

function uid(prefix:string){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function normalize(value:unknown):MemoryState{
 if(!value||typeof value!=='object')return DEFAULTS;
 const raw=value as Partial<MemoryState>;
 const notes=Array.isArray(raw.notes)?raw.notes.filter((x):x is StudyNote=>Boolean(x&&typeof x==='object'&&typeof (x as StudyNote).title==='string')).slice(-500):[];
 const experiments=Array.isArray(raw.experiments)?raw.experiments.filter((x):x is Experiment=>Boolean(x&&typeof x==='object'&&typeof (x as Experiment).title==='string')).slice(-200):[];
 const focusAreas=Array.isArray(raw.focusAreas)?raw.focusAreas.filter((x):x is StudyArea=>AREAS.includes(x as StudyArea)).slice(0,8):DEFAULTS.focusAreas;
 return {notes,experiments,focusAreas:focusAreas.length?focusAreas:DEFAULTS.focusAreas,adoptedPackKeys:Array.isArray(raw.adoptedPackKeys)?raw.adoptedPackKeys.filter(x=>typeof x==='string'):[],completedPackSteps:Array.isArray(raw.completedPackSteps)?raw.completedPackSteps.filter(x=>typeof x==='string'):[],favoriteLook:typeof raw.favoriteLook==='string'?raw.favoriteLook:''};
}
function openGlow(prompt:string){window.dispatchEvent(new CustomEvent('glow:open-conversation',{detail:{prompt}}))}

export function StudyYourselfHotterStudioV2(){
 const [mode,setMode]=useState<Mode>('Today');
 const [memory,setMemory]=useState<MemoryState>(DEFAULTS);
 const [hydrated,setHydrated]=useState(false);
 const [areaFilter,setAreaFilter]=useState<StudyArea|'All'>('All');
 const [search,setSearch]=useState('');
 const [draftArea,setDraftArea]=useState<StudyArea>('Identity');
 const [draftTitle,setDraftTitle]=useState('');
 const [draftDetail,setDraftDetail]=useState('');
 const [draftSource,setDraftSource]=useState('Personal observation');
 const [draftEvidence,setDraftEvidence]=useState('');
 const [showCapture,setShowCapture]=useState(false);
 const [sourceOpen,setSourceOpen]=useState(0);

 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_KEY);if(raw)setMemory(normalize(JSON.parse(raw)))}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(memory))}catch{}},[memory,hydrated]);

 const active=memory.notes.filter(n=>!n.archived);
 const playbook=active.filter(n=>n.confidence==='Works for me');
 const promising=active.filter(n=>n.confidence==='Promising');
 const trying=active.filter(n=>n.confidence==='Trying'||n.confidence==='Source idea');
 const inFlight=memory.experiments.filter(e=>e.status!=='Complete');
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return memory.notes.filter(n=>mode==='Archive'?n.archived||n.confidence==='Retired':!n.archived).filter(n=>areaFilter==='All'||n.area===areaFilter).filter(n=>!q||`${n.area} ${n.title} ${n.detail} ${n.source} ${n.evidence}`.toLowerCase().includes(q)).slice().reverse()},[memory.notes,mode,areaFilter,search]);

 function addNote(){if(!draftTitle.trim()&&!draftDetail.trim())return;const note:StudyNote={id:uid('note'),createdAt:new Date().toISOString(),area:draftArea,title:draftTitle.trim()||draftDetail.trim().slice(0,60),detail:draftDetail.trim(),source:draftSource.trim()||'Personal observation',confidence:draftSource==='Personal observation'?'Trying':'Source idea',evidence:draftEvidence.trim(),archived:false};setMemory(c=>({...c,notes:[...c.notes,note].slice(-500)}));setDraftTitle('');setDraftDetail('');setDraftEvidence('');setShowCapture(false)}
 function updateNote(id:string,patch:Partial<StudyNote>){setMemory(c=>({...c,notes:c.notes.map(n=>n.id===id?{...n,...patch}:n)}))}
 function startExperiment(note:StudyNote){const e:Experiment={id:uid('experiment'),createdAt:new Date().toISOString(),area:note.area,title:note.title,change:note.detail||note.title,measure:'Change one variable, keep context as similar as practical, then record what changed and whether you prefer it.',result:'',status:'Testing'};setMemory(c=>({...c,experiments:[...c.experiments,e].slice(-200)}));setMode('Experiments')}
 function updateExperiment(id:string,patch:Partial<Experiment>){setMemory(c=>({...c,experiments:c.experiments.map(e=>e.id===id?{...e,...patch}:e)}))}
 function toggleFocus(area:StudyArea){setMemory(c=>{const has=c.focusAreas.includes(area);const next=has?c.focusAreas.filter(x=>x!==area):[...c.focusAreas,area].slice(-8);return {...c,focusAreas:next.length?next:[area]}})}
 function adoptPack(key:string){setMemory(c=>({...c,adoptedPackKeys:c.adoptedPackKeys.includes(key)?c.adoptedPackKeys.filter(x=>x!==key):[...c.adoptedPackKeys,key]}))}
 function toggleStep(packKey:string,index:number){const id=`${packKey}:${index}`;setMemory(c=>({...c,completedPackSteps:c.completedPackSteps.includes(id)?c.completedPackSteps.filter(x=>x!==id):[...c.completedPackSteps,id]}))}

 return <div className="mx-auto max-w-[1520px] space-y-5 pb-28 text-[#2d2929]">
  <section className="relative overflow-hidden rounded-[38px] border border-[#e9ddda] bg-[radial-gradient(circle_at_12%_5%,rgba(255,235,242,.96),transparent_29%),radial-gradient(circle_at_88%_4%,rgba(237,232,249,.9),transparent_33%),radial-gradient(circle_at_48%_115%,rgba(228,220,204,.78),transparent_45%),linear-gradient(140deg,#fffdfb,#f8f2f1_48%,#f6f2f9)] px-5 py-7 shadow-[0_30px_110px_rgba(63,43,46,.09)] sm:px-8 sm:py-9">
   <div className="pointer-events-none absolute -right-24 -top-28 h-80 w-80 rounded-full border border-white/70 bg-white/15"/>
   <div className="relative flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><p className="text-[9px] uppercase tracking-[.28em] text-[#a96f80]">Personal Intelligence · Beauty + Life Blueprint</p><h1 className="mt-2 font-serif text-[40px] leading-[.96] sm:text-[58px]">Study Yourself Hotter</h1><p className="mt-4 max-w-2xl text-[12px] leading-6 text-[#766c69]">Study how you look, operate, feel and show up. Source → observe → test → adopt → route into the right Glow system → review what actually works.</p><p className="mt-3 text-[10px] leading-5 text-[#988d89]">Creator advice stays labeled as source material until you test or adopt it. Glow should never turn a transcript into a fact about you automatically.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>setShowCapture(true)} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#332c2d] px-5 py-3 text-[11px] text-white"><Sparkles size={14}/>Add what you noticed</button><button type="button" onClick={()=>openGlow('Open Study Yourself Hotter with me. Help me turn what I send into source notes, personal experiments, routines, habits, system changes, and only confirmed playbook rules when I explicitly say something works for me.')} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ded1ce] bg-white/80 px-5 py-3 text-[11px]"><Mic size={14}/>Study with Glow</button></div></div>
   <div className="relative mt-7 flex gap-2 overflow-x-auto pb-1">{MODES.map(item=><button type="button" key={item} onClick={()=>setMode(item)} aria-pressed={mode===item} className={`min-h-10 shrink-0 rounded-full px-4 text-[10px] transition ${mode===item?'bg-[#3a3233] text-white':'border border-[#e5d8d5] bg-white/72 text-[#746967]'}`}>{item}</button>)}</div>
  </section>

  {mode==='Today'&&<div className="grid gap-4 xl:grid-cols-[1.18fr_.82fr]">
   <section className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><div className="flex items-center gap-2"><Compass size={16} className="text-[#aa7180]"/><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Now</p></div><h2 className="mt-2 font-serif text-3xl">Hotter means more than appearance.</h2><p className="mt-3 max-w-3xl text-[12px] leading-6 text-[#756b68]">This version studies the full system underneath your best days: identity, priorities, energy, environment, digital friction, beauty, style, presence and proof. The goal is a personal operating manual, not a generic glow-up checklist.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Source / trying" value={`${trying.length}`} detail="not confirmed yet"/><Metric label="Promising" value={`${promising.length}`} detail="worth repeating"/><Metric label="Works for me" value={`${playbook.length}`} detail="confirmed personal rules"/><Metric label="Active tests" value={`${inFlight.length}`} detail="experiments in progress"/></div><div className="mt-6 grid gap-3 md:grid-cols-3"><ActionCard icon={<Target size={15}/>} title="Capacity before quantity" detail="Choose 1 / 3 / up to 6 priorities based on actual capacity, then time block them." onClick={()=>setMode('Routines + Habits')}/><ActionCard icon={<Brain size={15}/>} title="Study the system" detail="Track mental energy, physical energy, triggers and what repeatedly makes a day easier." onClick={()=>setMode('Study Map')}/><ActionCard icon={<FlaskConical size={15}/>} title="Test before adopting" detail="Hair, makeup, style, posture and creator claims can become controlled personal experiments." onClick={()=>setMode('Experiments')}/></div></section>
   <section className="rounded-[30px] border border-[#eadfdb] bg-[linear-gradient(145deg,#fff9fa,#f5f1f9)] p-5 sm:p-6"><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Imported blueprint</p><h3 className="mt-2 font-serif text-2xl">5 source packets organized</h3><div className="mt-4 space-y-2">{sourceLibrary.map((s,i)=><button type="button" key={s.source} onClick={()=>{setSourceOpen(i);setMode('Blueprint')}} className="w-full rounded-[18px] bg-white px-4 py-3 text-left"><p className="text-[10px] font-medium">{s.source}</p><p className="mt-1 text-[10px] text-[#8a7f7a]">{s.theme}</p></button>)}</div><div className="mt-5 rounded-[20px] bg-white/80 p-4"><p className="text-[9px] uppercase tracking-[.16em] text-[#9f858d]">Rule</p><p className="mt-2 text-[11px] leading-5 text-[#6e6461]">Sponsored products, study percentages, medical-adjacent skincare steps and universal attractiveness claims stay in the source layer until separately reviewed or personally tested.</p></div></section>
  </div>}

  {mode==='Blueprint'&&<section className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Source library</p><h2 className="mt-1 font-serif text-3xl">Every idea gets a home.</h2><p className="mt-2 max-w-3xl text-[11px] leading-5 text-[#7d726e]">These are structured from the transcripts you supplied. They are not silently corrected, independently verified or treated as facts about you.</p></div><div className="flex gap-2 overflow-x-auto">{sourceLibrary.map((s,i)=><button type="button" key={s.source} onClick={()=>setSourceOpen(i)} aria-pressed={sourceOpen===i} className={`shrink-0 rounded-full px-3 py-2 text-[9px] ${sourceOpen===i?'bg-[#352e2f] text-white':'bg-[#f8f3f2]'}`}>Source {i+1}</button>)}</div></div><div className="mt-6 grid gap-4 xl:grid-cols-[.72fr_1.28fr]"><div className="rounded-[24px] bg-[#fbf7f6] p-5"><p className="text-[9px] uppercase tracking-[.16em] text-[#a48982]">Current source</p><h3 className="mt-2 font-serif text-2xl">{sourceLibrary[sourceOpen].source}</h3><p className="mt-3 text-[11px] leading-5 text-[#796e6a]">{sourceLibrary[sourceOpen].theme}</p><button type="button" onClick={()=>openGlow(`Help me work through this source packet from Study Yourself Hotter: ${sourceLibrary[sourceOpen].source}. Keep source claims separate from verified facts and help me decide what belongs in observations, experiments, routines, habits or playbook.`)} className="mt-5 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-[10px]"><Mic size={13}/>Discuss with Glow</button></div><div className="space-y-2">{sourceLibrary[sourceOpen].points.map((p,i)=><div key={`${sourceOpen}-${i}`} className="flex gap-3 rounded-[20px] border border-[#eee5e2] bg-white p-4"><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#f7eff1] text-[9px] text-[#a06b78]">{i+1}</span><p className="text-[11px] leading-5 text-[#645c59]">{p}</p></div>)}</div></div></section>}

  {mode==='Study Map'&&<section className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Whole-self map</p><h2 className="mt-1 font-serif text-3xl">What can Glow study?</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{AREAS.map(area=>{const count=active.filter(n=>n.area===area).length;const selected=memory.focusAreas.includes(area);return <button type="button" key={area} onClick={()=>toggleFocus(area)} aria-pressed={selected} className={`rounded-[22px] p-4 text-left transition ${selected?'bg-[linear-gradient(145deg,#fff1f5,#f3eff8)] ring-1 ring-[#e5cbd2]':'bg-[#faf7f6]'}`}><div className="flex items-center justify-between gap-3"><h3 className="font-serif text-lg">{area}</h3><span className="text-[9px] text-[#9d8e89]">{count}</span></div><p className="mt-2 text-[10px] leading-5 text-[#7a706c]">{areaDescriptions[area]}</p></button>})}</div></section>}

  {(mode==='Observations'||mode==='Archive')&&<section className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">{mode}</p><h2 className="mt-1 font-serif text-3xl">{mode==='Archive'?'Retired and archived':'What you are noticing'}</h2></div><button type="button" onClick={()=>setShowCapture(true)} className="rounded-full bg-[#332c2d] px-4 py-2 text-[10px] text-white">Add note</button></div><div className="mt-5 flex flex-wrap gap-2"><select value={areaFilter} onChange={e=>setAreaFilter(e.target.value as StudyArea|'All')} className="min-h-10 rounded-full border border-[#e5d9d6] bg-white px-3 text-[10px]"><option>All</option>{AREAS.map(a=><option key={a}>{a}</option>)}</select><div className="relative min-w-[220px] flex-1"><Search size={13} className="absolute left-3 top-3.5 text-[#a28f89]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search notes, sources or evidence…" className="min-h-10 w-full rounded-full border border-[#e5d9d6] pl-9 pr-3 text-[10px] outline-none"/></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{visible.map(note=><div key={note.id} className="rounded-[22px] bg-[#faf7f6] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-[9px] uppercase tracking-[.14em] text-[#a27e87]">{note.area} · {note.confidence}</p><h3 className="mt-1 font-serif text-xl">{note.title}</h3></div><select value={note.confidence} onChange={e=>updateNote(note.id,{confidence:e.target.value as Confidence})} className="rounded-full border border-[#e5d9d6] bg-white px-2 py-1 text-[9px]">{CONFIDENCE.map(c=><option key={c}>{c}</option>)}</select></div>{note.detail&&<p className="mt-3 text-[11px] leading-5 text-[#6d6460]">{note.detail}</p>}<div className="mt-3 rounded-[15px] bg-white p-3 text-[9px] leading-4 text-[#8a7e79]"><strong>Source:</strong> {note.source}<br/><strong>Evidence:</strong> {note.evidence||'None recorded yet'}</div><div className="mt-3 flex flex-wrap gap-2">{mode!=='Archive'&&<button type="button" onClick={()=>startExperiment(note)} className="rounded-full bg-white px-3 py-1.5 text-[9px]">Test this</button>}<button type="button" onClick={()=>updateNote(note.id,{archived:!note.archived})} className="rounded-full bg-white px-3 py-1.5 text-[9px]">{note.archived?'Restore':'Archive'}</button><button type="button" onClick={()=>openGlow(`Study note: ${note.title}. Detail: ${note.detail}. Source: ${note.source}. Evidence: ${note.evidence||'none yet'}. Help me decide what would count as a fair test and do not treat this as confirmed unless I have evidence.`)} className="rounded-full bg-white px-3 py-1.5 text-[9px]">Ask Glow</button></div></div>)}{!visible.length&&<p className="text-[11px] text-[#887d78]">Nothing here yet.</p>}</div></section>}

  {mode==='Experiments'&&<section className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><div className="flex items-center gap-2"><FlaskConical size={16} className="text-[#a96f80]"/><div><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Experiment lab</p><h2 className="font-serif text-3xl">One variable at a time.</h2></div></div><p className="mt-3 max-w-3xl text-[11px] leading-5 text-[#786e69]">Use the same practical context where possible. Personal experiments can reveal preference or repeated association; they do not prove universal cause-and-effect.</p><div className="mt-6 space-y-3">{memory.experiments.slice().reverse().map(e=><div key={e.id} className="rounded-[22px] bg-[#faf7f6] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] uppercase tracking-[.14em] text-[#a27e87]">{e.area}</p><h3 className="mt-1 font-serif text-xl">{e.title}</h3></div><select value={e.status} onChange={x=>updateExperiment(e.id,{status:x.target.value as Experiment['status']})} className="rounded-full border border-[#e5d9d6] bg-white px-3 py-1.5 text-[9px]"><option>Planned</option><option>Testing</option><option>Complete</option></select></div><div className="mt-4 grid gap-3 lg:grid-cols-2"><label className="text-[9px] uppercase tracking-[.12em] text-[#9c8c86]">Change<textarea value={e.change} onChange={x=>updateExperiment(e.id,{change:x.target.value})} className="mt-1 min-h-24 w-full rounded-[16px] border border-[#e9dfdc] bg-white p-3 normal-case tracking-normal text-[10px] text-[#645b58]"/></label><label className="text-[9px] uppercase tracking-[.12em] text-[#9c8c86]">Measure<textarea value={e.measure} onChange={x=>updateExperiment(e.id,{measure:x.target.value})} className="mt-1 min-h-24 w-full rounded-[16px] border border-[#e9dfdc] bg-white p-3 normal-case tracking-normal text-[10px] text-[#645b58]"/></label></div><label className="mt-3 block text-[9px] uppercase tracking-[.12em] text-[#9c8c86]">Result<textarea value={e.result} onChange={x=>updateExperiment(e.id,{result:x.target.value})} placeholder="What actually happened? What did you prefer? What stayed uncertain?" className="mt-1 min-h-20 w-full rounded-[16px] border border-[#e9dfdc] bg-white p-3 normal-case tracking-normal text-[10px] text-[#645b58]"/></label></div>)}{!memory.experiments.length&&<div className="rounded-[22px] bg-[#faf7f6] p-5 text-[11px] text-[#7c716d]">Start from an Observation or use one of the proposed packs in Routines + Habits.</div>}</div></section>}

  {mode==='Playbook'&&<section className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><div className="flex items-center gap-2"><Heart size={16} className="text-[#a96f80]"/><div><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Personal truth only</p><h2 className="font-serif text-3xl">Works for me.</h2></div></div><p className="mt-3 text-[11px] leading-5 text-[#786e69]">Only notes you explicitly promote to “Works for me” belong here. This is the layer Glow can eventually use automatically when helping you plan, dress, get ready or structure a day.</p><div className="mt-6 grid gap-3 lg:grid-cols-2">{playbook.map(n=><div key={n.id} className="rounded-[22px] bg-[linear-gradient(145deg,#fff8fa,#f6f3fa)] p-5"><p className="text-[9px] uppercase tracking-[.14em] text-[#a27e87]">{n.area}</p><h3 className="mt-1 font-serif text-xl">{n.title}</h3><p className="mt-2 text-[11px] leading-5 text-[#6e6460]">{n.detail}</p><p className="mt-3 text-[9px] text-[#948782]">Evidence: {n.evidence||'Personal confirmation'}</p></div>)}{!playbook.length&&<p className="text-[11px] text-[#887d78]">Nothing has been promoted yet. That is intentional.</p>}</div></section>}

  {mode==='Routines + Habits'&&<section className="space-y-4"><div className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Proposed operating packs</p><h2 className="mt-1 font-serif text-3xl">Turn ideas into repeatable systems.</h2><p className="mt-3 max-w-3xl text-[11px] leading-5 text-[#786e69]">These packs organize the transcript details into routines, habits, reviews and experiments. “Adopt” means save as a Study preference on this page; server-backed Routines/Habits remain their own system and should not receive medical/product changes silently.</p></div><div className="grid gap-4 xl:grid-cols-2">{routinePacks.map(pack=>{const adopted=memory.adoptedPackKeys.includes(pack.key);const done=pack.steps.filter((_,i)=>memory.completedPackSteps.includes(`${pack.key}:${i}`)).length;return <article key={pack.key} className={`rounded-[28px] border p-5 ${adopted?'border-[#dfc7cf] bg-[linear-gradient(145deg,#fff8fa,#f7f4fb)]':'border-[#eadfdb] bg-white'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] uppercase tracking-[.15em] text-[#a7838d]">{pack.kind} · {pack.frequency}</p><h3 className="mt-1 font-serif text-2xl">{pack.title}</h3><p className="mt-2 text-[10px] leading-5 text-[#7c716d]">{pack.purpose}</p></div><button type="button" onClick={()=>adoptPack(pack.key)} aria-pressed={adopted} className={`rounded-full px-3 py-2 text-[9px] ${adopted?'bg-[#382f31] text-white':'bg-[#f8f3f2]'}`}>{adopted?'Adopted':'Adopt to Study'}</button></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#eee6e3]"><div className="h-full bg-[#b98593]" style={{width:`${Math.round(done/pack.steps.length*100)}%`}}/></div><div className="mt-4 space-y-2">{pack.steps.map((step,i)=>{const checked=memory.completedPackSteps.includes(`${pack.key}:${i}`);return <button type="button" key={i} onClick={()=>toggleStep(pack.key,i)} className={`flex w-full gap-3 rounded-[16px] px-3 py-2.5 text-left text-[10px] leading-5 ${checked?'bg-[#edf3eb] text-[#65705f]':'bg-[#faf7f6] text-[#665d5a]'}`}><span className="mt-0.5">{checked?<CheckCircle2 size={13}/>:<span className="flex h-[13px] w-[13px] rounded-full border border-[#cdbfbb]"/>}</span>{step}</button>})}</div>{pack.caution&&<div className="mt-4 rounded-[16px] bg-[#fff6ee] p-3 text-[9px] leading-4 text-[#846b58]"><ShieldCheck size={12} className="mb-1"/>{pack.caution}</div>}<div className="mt-4 flex flex-wrap gap-2">{pack.links.map(href=><Link key={href} href={href} className="rounded-full bg-white px-3 py-1.5 text-[9px] ring-1 ring-[#ebe1de]">{href.replace('/','')||'home'} <ArrowRight size={9} className="ml-1 inline"/></Link>)}</div></article>})}</div></section>}

  {mode==='System Map'&&<section className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><div className="flex items-center gap-2"><Layers3 size={16} className="text-[#aa7180]"/><div><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Glow OS routing</p><h2 className="font-serif text-3xl">Where every detail should go.</h2></div></div><div className="mt-6 grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{systemUpgrades.map(item=><Link key={item.page} href={item.href} className="rounded-[22px] bg-[#faf7f6] p-4 transition hover:-translate-y-0.5"><div className="flex items-center justify-between gap-2"><h3 className="font-serif text-xl">{item.page}</h3><ArrowRight size={13} className="text-[#aa7180]"/></div><p className="mt-1 text-[9px] uppercase tracking-[.12em] text-[#a48b84]">{item.role}</p><ul className="mt-3 space-y-2">{item.upgrades.map((u,i)=><li key={i} className="text-[10px] leading-5 text-[#6f6662]">• {u}</li>)}</ul></Link>)}</div></section>}

  {mode==='Evidence'&&<section className="grid gap-4 xl:grid-cols-[1.08fr_.92fr]"><div className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Evidence ladder</p><h2 className="mt-1 font-serif text-3xl">Do not confuse a source with a result.</h2><div className="mt-5 space-y-2">{[['Source idea','Someone said it, a transcript claims it, or a creator recommends it.'],['Trying','You are testing it.'],['Promising','You have repeated evidence or a clear preference, but want more data.'],['Works for me','You explicitly confirmed it belongs in your personal playbook.'],['Retired','It stopped working, no longer fits or you intentionally removed it.']].map(([a,b])=><div key={a} className="rounded-[18px] bg-[#faf7f6] p-4"><p className="text-[10px] font-medium">{a}</p><p className="mt-1 text-[10px] leading-5 text-[#7b706c]">{b}</p></div>)}</div></div><div className="rounded-[30px] border border-[#eadfdb] bg-[linear-gradient(145deg,#fff9fa,#f5f1f9)] p-5 sm:p-7"><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Useful proof</p><h3 className="mt-1 font-serif text-2xl">What can count?</h3><div className="mt-4 flex flex-wrap gap-2">{['Same-light photos','Repeated completion','Energy ratings','Time estimates vs actual','Wear tests','Hair outcome notes','Makeup comparisons','Outfit repeats','Compliments (context only)','Sleep context','Calendar load','Personal preference','Experiment result'].map(x=><span key={x} className="rounded-full bg-white px-3 py-2 text-[9px]">{x}</span>)}</div><p className="mt-5 text-[10px] leading-5 text-[#786e69]">A photo can document a difference but it does not automatically prove why the difference happened. Glow should record context such as lighting, angle, product, sleep, timing and routine changes.</p></div></section>}

  {mode==='Progress'&&<section className="rounded-[30px] border border-[#eadfdb] bg-white p-5 sm:p-7"><p className="text-[9px] uppercase tracking-[.2em] text-[#a87582]">Progress without a hotness score</p><h2 className="mt-1 font-serif text-3xl">Build a stronger personal manual.</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Notes" value={`${memory.notes.length}`} detail="captured observations"/><Metric label="Tests" value={`${memory.experiments.length}`} detail="experiments created"/><Metric label="Confirmed" value={`${playbook.length}`} detail="playbook rules"/><Metric label="Packs" value={`${memory.adoptedPackKeys.length}`} detail="systems adopted"/><Metric label="Sources" value={`${sourceLibrary.length}`} detail="organized transcript packets"/></div><div className="mt-6 rounded-[24px] bg-[#faf7f6] p-5"><p className="text-[9px] uppercase tracking-[.15em] text-[#a48b84]">Next evolution</p><p className="mt-2 text-[11px] leading-5 text-[#706662]">As you send more material, this page can grow new study areas, source packets, routine packs, experiments, system mappings and playbook rules without deleting previous context. New information should be merged by meaning, not pasted as duplicate advice.</p></div></section>}

  {showCapture&&<div className="fixed inset-0 z-[90] flex items-end justify-center bg-black/20 p-3 backdrop-blur-sm sm:items-center"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[30px] border border-[#eadfdb] bg-[#fffdfc] p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] uppercase tracking-[.18em] text-[#a87582]">Capture</p><h2 className="font-serif text-2xl">Add to the study</h2></div><button type="button" onClick={()=>setShowCapture(false)} className="rounded-full bg-[#f7f1ef] px-3 py-2 text-[10px]">Close</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-[9px] uppercase tracking-[.12em] text-[#9c8c86]">Area<select value={draftArea} onChange={e=>setDraftArea(e.target.value as StudyArea)} className="mt-1 min-h-11 w-full rounded-[16px] border border-[#e6dbd8] bg-white px-3 normal-case tracking-normal text-[10px]">{AREAS.map(a=><option key={a}>{a}</option>)}</select></label><label className="text-[9px] uppercase tracking-[.12em] text-[#9c8c86]">Source<input value={draftSource} onChange={e=>setDraftSource(e.target.value)} className="mt-1 min-h-11 w-full rounded-[16px] border border-[#e6dbd8] bg-white px-3 normal-case tracking-normal text-[10px]"/></label></div><label className="mt-3 block text-[9px] uppercase tracking-[.12em] text-[#9c8c86]">Finding<input value={draftTitle} onChange={e=>setDraftTitle(e.target.value)} placeholder="Example: I focus better before checking social media" className="mt-1 min-h-11 w-full rounded-[16px] border border-[#e6dbd8] px-3 normal-case tracking-normal text-[10px]"/></label><label className="mt-3 block text-[9px] uppercase tracking-[.12em] text-[#9c8c86]">Every detail<textarea value={draftDetail} onChange={e=>setDraftDetail(e.target.value)} className="mt-1 min-h-28 w-full rounded-[16px] border border-[#e6dbd8] p-3 normal-case tracking-normal text-[10px]"/></label><label className="mt-3 block text-[9px] uppercase tracking-[.12em] text-[#9c8c86]">Evidence / context<textarea value={draftEvidence} onChange={e=>setDraftEvidence(e.target.value)} placeholder="Photos, repeated result, timing, energy, context, what stayed constant…" className="mt-1 min-h-20 w-full rounded-[16px] border border-[#e6dbd8] p-3 normal-case tracking-normal text-[10px]"/></label><div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={()=>openGlow(`Help me structure this Study Yourself Hotter note. Area: ${draftArea}. Finding: ${draftTitle}. Details: ${draftDetail}. Source: ${draftSource}. Evidence: ${draftEvidence}. Keep source claims separate from personal conclusions.`)} className="rounded-full border border-[#e2d6d3] bg-white px-4 py-2 text-[10px]">Organize with Glow</button><button type="button" onClick={addNote} className="rounded-full bg-[#342d2e] px-4 py-2 text-[10px] text-white">Save to study</button></div></div></div>}
 </div>
}

function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="rounded-[20px] bg-[#faf7f6] p-4"><p className="text-[9px] uppercase tracking-[.14em] text-[#a28f89]">{label}</p><strong className="mt-2 block font-serif text-2xl font-normal">{value}</strong><p className="mt-1 text-[9px] text-[#8b7f7a]">{detail}</p></div>}
function ActionCard({icon,title,detail,onClick}:{icon:React.ReactNode;title:string;detail:string;onClick:()=>void}){return <button type="button" onClick={onClick} className="rounded-[22px] bg-[#faf7f6] p-4 text-left"><span className="text-[#a96f80]">{icon}</span><h3 className="mt-3 font-serif text-lg">{title}</h3><p className="mt-2 text-[10px] leading-5 text-[#796f6a]">{detail}</p></button>}
