import { auth } from '@/auth';
import { redirect } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { ClosetIntelligenceStudio } from '@/components/closet-intelligence-studio';
import { createClosetItemAction, updateClosetItemAction } from '@/app/actions/completion-v1';
import { getClosetItems } from '@/lib/data/completion-v1';
import { getCalendarEventsByUser } from '@/lib/data/calendar-events';

export const dynamic='force-dynamic';
const field='w-full rounded-[12px] border border-white/60 bg-white/65 px-3 py-2.5 text-[11px] outline-none backdrop-blur focus:border-[#c98d93]';

export default async function ClosetPage({searchParams}:{searchParams:Promise<{itemId?:string}>}){
 const session=await auth();
 if(!session?.user?.id)redirect('/sign-in');
 const userId=session.user.id;
 const [items,events,params]=await Promise.all([getClosetItems(userId),getCalendarEventsByUser(userId),searchParams]);
 const selected=params.itemId?items.find(x=>x.id===params.itemId)??null:null;
 return <AppShell><div className="couture-page space-y-5"><ClosetIntelligenceStudio items={items} events={events}/><details id="closet-manage" className="couture-panel mx-auto max-w-[1480px] p-5" open={items.length===0||Boolean(selected)}><summary className="cursor-pointer glow-display text-[17px] text-[#493b35]">Wardrobe record editor</summary><p className="mt-1 text-[9px] leading-4 text-[#927e77]">Keep the wardrobe truthful. These fields feed availability, wear intelligence and cost-per-wear.</p><form action={createClosetItemAction} className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><input name="name" required placeholder="Item name" className={field}/><input name="category" required placeholder="Category" className={field}/><input name="season" placeholder="Season" className={field}/><input name="weatherTags" placeholder="Weather tags" className={field}/><input name="purchaseDate" type="date" className={field}/><input name="purchasePrice" inputMode="decimal" placeholder="Purchase price" className={field}/><select name="laundryState" defaultValue="clean" className={field}><option value="clean">Clean · available</option><option value="dirty">Laundry</option><option value="dry_clean">Dry clean</option><option value="repair">Repair</option></select><label className="flex items-center gap-2 rounded-[12px] border border-white/60 bg-white/50 px-3 text-[10px]"><input name="favorite" type="checkbox"/> Favorite</label><button className="couture-primary w-fit" type="submit">Save item</button></form>{selected?<form action={updateClosetItemAction.bind(null,selected.id)} className="mt-6 grid gap-2 border-t border-white/55 pt-5 sm:grid-cols-2 lg:grid-cols-3"><strong className="glow-display text-[16px] text-[#493b35] sm:col-span-2 lg:col-span-3">Edit {selected.name}</strong><label className="text-[9px] text-[#83736c]">Wear count<input name="wearCount" type="number" min="0" defaultValue={selected.wearCount} className={`${field} mt-1`}/></label><label className="text-[9px] text-[#83736c]">Wardrobe status<select name="status" defaultValue={selected.status} className={`${field} mt-1`}><option value="active">Active</option><option value="wishlist">Wishlist</option><option value="donate">Donate</option><option value="sell">Sell</option><option value="archived">Archived</option></select></label><label className="text-[9px] text-[#83736c]">Care state<select name="laundryState" defaultValue={selected.laundryState} className={`${field} mt-1`}><option value="clean">Clean · available</option><option value="dirty">Laundry</option><option value="dry_clean">Dry clean</option><option value="repair">Repair</option></select></label><label className="flex items-center gap-2 rounded-[12px] border border-white/60 bg-white/50 px-3 text-[10px]"><input name="favorite" type="checkbox" defaultChecked={selected.favorite}/> Favorite</label><button className="couture-primary w-fit" type="submit">Update item</button></form>:null}</details></div></AppShell>;
}
