import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { AppShell } from '@/components/app-shell';
import { SectionPage } from '@/components/section-page';
import { Card } from '@/components/ui/card';
import { createClosetItemAction, incrementClosetWearAction, updateClosetItemAction } from '@/app/actions/completion-v1';
import { getClosetItems } from '@/lib/data/completion-v1';
import { Heart, Shirt, Sparkles } from 'lucide-react';

export const dynamic='force-dynamic';
const fieldClass='w-full border px-4 py-3 text-[10px]';

export default async function ClosetPage(){
  const session=await auth();if(!session?.user?.id)redirect('/sign-in');
  const items=await getClosetItems(session.user.id);
  const favorites=items.filter((item)=>item.favorite).length;
  const laundry=items.filter((item)=>item.laundryState!=='clean').length;
  return <AppShell><SectionPage eyebrow="Digital Closet" title="Know what you own and actually wear" description="Track wardrobe inventory, seasons, laundry state, weather fit, favorites, purchase cost, and wear count.">
    <div className="space-y-4">
      <div className="grid gap-3 md:grid-cols-[1.2fr_.8fr]"><Card className="relative overflow-hidden bg-[linear-gradient(145deg,#f1e4e7,#eee6df)] p-5"><Shirt size={58} strokeWidth={.75} className="absolute right-5 top-3 text-[#98727c]/16"/><p className="glow-eyebrow">Digital wardrobe</p><p className="glow-display mt-2 text-[25px] text-[#4c3c42]">Dress from what you already love.</p><p className="mt-2 text-[9px] leading-4 text-[#7b6870]">Your closet becomes easier to use when wear, laundry and favorites are visible at a glance.</p></Card><Card className="p-5"><div className="grid grid-cols-3 gap-2 text-center"><div><p className="glow-display text-[23px] text-[#54444a]">{items.length}</p><p className="text-[7px] text-[#8e7b82]">pieces</p></div><div><Heart size={13} className="mx-auto text-[#ad737d]"/><p className="glow-display mt-1 text-[19px] text-[#54444a]">{favorites}</p><p className="text-[7px] text-[#8e7b82]">favorites</p></div><div><p className="glow-display text-[23px] text-[#54444a]">{laundry}</p><p className="text-[7px] text-[#8e7b82]">care due</p></div></div></Card></div>
      <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]">
        <Card className="paper-card"><form action={createClosetItemAction} className="space-y-3"><div className="flex items-center gap-2"><Sparkles size={14} className="text-[#98727c]"/><h2 className="glow-display text-[20px] text-[#4c3c42]">Add closet item</h2></div><input name="name" required placeholder="Item name" className={fieldClass}/><input name="category" required placeholder="Category" className={fieldClass}/><input name="season" placeholder="Season" className={fieldClass}/><input name="weatherTags" placeholder="Weather tags" className={fieldClass}/><input name="purchaseDate" type="date" className={fieldClass}/><input name="purchasePrice" inputMode="decimal" placeholder="Purchase price" className={fieldClass}/><select name="laundryState" defaultValue="clean" className={fieldClass}><option value="clean">Clean</option><option value="dirty">Laundry</option><option value="dry_clean">Dry clean</option><option value="repair">Needs repair</option></select><label className="flex items-center gap-2 text-[9px] text-[#76636b]"><input name="favorite" type="checkbox"/>Favorite</label><button className="rounded-[6px] bg-[#49383f] px-4 py-2 text-[9px] text-white">Save item</button></form></Card>
        <div className="grid gap-3 sm:grid-cols-2">{items.length===0?<Card className="sm:col-span-2"><p className="py-8 text-center text-[9px] text-[#8d7b82]">No closet items yet.</p></Card>:items.map((item,index)=>{const cpw=item.purchasePriceCents&&item.wearCount>0?item.purchasePriceCents/item.wearCount:null;return <Card key={item.id} className="overflow-hidden p-0"><div className={`relative h-28 ${index%3===0?'bg-[linear-gradient(145deg,#d7c3c7,#f0e3df)]':index%3===1?'bg-[linear-gradient(145deg,#d8d0c7,#eee7df)]':'bg-[linear-gradient(145deg,#cfc6c3,#ead8da)]'}`}><Shirt size={38} strokeWidth={.9} className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-white/65"/>{item.favorite?<Heart size={13} className="absolute right-3 top-3 fill-white/65 text-white/70"/>:null}</div><form action={updateClosetItemAction.bind(null,item.id)} className="p-4"><div className="flex justify-between gap-3"><div><p className="glow-display text-[15px] text-[#4c3c42]">{item.name}</p><p className="mt-1 text-[7px] text-[#8d7a82]">{item.category}{item.season?` · ${item.season}`:''}</p></div><span className="h-fit rounded-full bg-[#f0e5e7] px-2 py-1 text-[7px] text-[#8f6570]">{item.laundryState.replace('_',' ')}</span></div><p className="mt-2 text-[7px] text-[#93828a]">{item.wearCount} wears{cpw?` · $${(cpw/100).toFixed(2)} per wear`:''}</p><details className="mt-3"><summary className="cursor-pointer text-[7px] text-[#806b73]">Edit wardrobe record</summary><div className="mt-3 grid gap-2"><input name="wearCount" type="number" min="0" defaultValue={item.wearCount} className={fieldClass}/><select name="laundryState" defaultValue={item.laundryState} className={fieldClass}><option value="clean">Clean</option><option value="dirty">Laundry</option><option value="dry_clean">Dry clean</option><option value="repair">Needs repair</option></select><select name="status" defaultValue={item.status} className={fieldClass}><option value="active">Active</option><option value="donate">Donate</option><option value="sell">Sell</option><option value="archived">Archived</option></select><label className="flex items-center gap-2 text-[8px] text-[#76636b]"><input name="favorite" type="checkbox" defaultChecked={item.favorite}/>Favorite</label><div className="flex gap-2"><button className="rounded-[5px] bg-[#49383f] px-3 py-2 text-[8px] text-white">Save</button><button formAction={incrementClosetWearAction.bind(null,item.id,item.wearCount)} className="rounded-[5px] border border-[#dfd1d5] px-3 py-2 text-[8px] text-[#745d67]">Wore today +1</button></div></div></details></form></Card>;})}</div>
      </div>
    </div>
  </SectionPage></AppShell>;
}
