import Link from 'next/link';
import { auth } from '@/auth';
import { redirect } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { refreshMaintenanceForecasts } from '@/lib/intelligence/maintenance-forecasts';
import { CalendarClock, Sparkles } from 'lucide-react';

export const dynamic='force-dynamic';

export default async function MaintenancePage(){const session=await auth();if(!session?.user?.id)redirect('/sign-in');let forecasts;try{forecasts=await refreshMaintenanceForecasts(session.user.id);}catch{return <AppShell><div className="mx-auto max-w-4xl rounded-[22px] border border-amber-200 bg-amber-50 p-6"><p className="text-sm font-semibold">Maintenance Forecasts need intelligence activation.</p><Link href="/settings/intelligence" className="mt-3 inline-block text-xs text-amber-900">Activate intelligence →</Link></div></AppShell>;}const sorted=[...forecasts].sort((a,b)=>(a.dueAt?.getTime()??Infinity)-(b.dueAt?.getTime()??Infinity));return <AppShell><div className="mx-auto max-w-5xl space-y-5"><header><div className="flex items-center gap-2 text-[#a36d72]"><CalendarClock size={17}/><p className="text-[9px] font-bold uppercase tracking-[.2em]">Coming Soon</p></div><h1 className="glow-display mt-2 text-[42px] leading-none text-[#392e2a]">Maintenance Forecasts</h1><p className="mt-2 max-w-2xl text-[10px] leading-5 text-[#7e6b64]">Glow turns product dates and maintenance history into an early-warning layer so care can happen before it becomes urgent.</p></header><section className="grid gap-3 md:grid-cols-2">{sorted.length?sorted.map(item=><article key={item.id} className={`rounded-[18px] border p-4 ${item.urgency==='high'?'border-rose-200 bg-rose-50/70':item.urgency==='soon'?'border-amber-200 bg-amber-50/60':'border-[#e4d7cf] bg-white/72'}`}><div className="flex items-center justify-between gap-2"><span className="text-[7px] font-bold uppercase tracking-[.15em] text-[#9b7771]">{item.domain}</span><span className="text-[7px] uppercase text-[#a18b84]">{item.dueAt?item.dueAt.toLocaleDateString('en-US',{month:'short',day:'numeric'}):item.urgency}</span></div><h2 className="glow-display mt-2 text-[18px] text-[#443832]">{item.title}</h2>{item.recommendation?<p className="mt-2 text-[9px] leading-4 text-[#7d6962]">{item.recommendation}</p>:null}</article>):<div className="col-span-full rounded-[20px] border border-emerald-100 bg-emerald-50/55 p-8 text-center"><Sparkles size={20} className="mx-auto text-emerald-700"/><p className="glow-display mt-2 text-[20px] text-[#3e493f]">Nothing is approaching maintenance yet.</p></div>}</section><div className="flex flex-wrap gap-2"><Link href="/beauty/lab" className="rounded-lg border border-[#dfd1c9] bg-white/70 px-3 py-2 text-[8px] text-[#6d5952]">Beauty Lab</Link><Link href="/hair" className="rounded-lg border border-[#dfd1c9] bg-white/70 px-3 py-2 text-[8px] text-[#6d5952]">Hair Studio</Link><Link href="/calendar" className="rounded-lg bg-[#40352f] px-3 py-2 text-[8px] text-white">Schedule maintenance</Link></div></div></AppShell>}
