import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { AppShell } from '@/components/app-shell';
import { SectionPage } from '@/components/section-page';
import { Card } from '@/components/ui/card';
import { generateExpandedBriefingAction, type BriefingKind } from '@/app/actions/briefings';
import { getBriefings } from '@/lib/data/completion-v1';
import { CalendarDays, MoonStar, Sparkles, Sun } from 'lucide-react';
export const dynamic='force-dynamic';
const options:[string,BriefingKind|'evening'][]=[['Morning Brief','morning'],['Evening Debrief','evening'],['Weekly Debrief','weekly'],['Monthly Debrief','monthly'],['Quarter Review','quarterly'],['Year Review','year']];
export default async function BriefingsPage(){const s=await auth();if(!s?.user?.id)redirect('/sign-in');const all=await getBriefings(s.user.id),latest=all[0];return <AppShell><SectionPage eyebrow="Briefings" title="Briefings" description="Clarity in the morning. Reflection at night. Growth always."><div className="space-y-4"><section className="grid gap-4 lg:grid-cols-[230px_1fr_280px]"><Card className="p-3">{options.map(([name,kind])=>kind==='evening'?<Link key={name} href="/briefings/evening" className="block rounded-[12px] p-3 hover:bg-[#FDF3F2]">{name}</Link>:<form key={name} action={generateExpandedBriefingAction.bind(null,kind)}><button className="w-full rounded-[12px] p-3 text-left hover:bg-[#FDF3F2]">{name}</button></form>)}</Card><Card><p className="text-[10px] uppercase tracking-[.14em] text-[#C9727E]">Featured</p><h2 className="glow-display mt-2 text-[31px] capitalize">{latest?.kind.replaceAll('_',' ')??'Morning Brief'}</h2><p className="mt-3 text-[11px] text-[#92867E]">{latest?latest.generatedAt.toLocaleString():'Ready when you are'}</p><p className="glow-display mt-8 text-[18px]">Good {new Date().getHours()<12?'morning':'evening'}, {s.user.name?.split(' ')[0]??'Tatiyana'} ✨</p><form action={generateExpandedBriefingAction.bind(null,'morning')} className="mt-6"><button className="rounded-[8px] bg-[#D76078] px-5 py-2.5 text-[11px] text-white">Open Brief →</button></form></Card><Card><div className="flex gap-2"><Sparkles size={14}/><h2 className="glow-display text-[17px]">Briefing Summary</h2></div><div className="mt-4 space-y-3 text-[10.5px]"><p><Sun size={12} className="inline"/> Morning Brief</p><p><MoonStar size={12} className="inline"/> Evening Debrief</p><p><CalendarDays size={12} className="inline"/> Weekly + Monthly</p><Link href="#history" className="text-[#C9727E]">History · {all.length} saved →</Link></div></Card></section><div id="history"><Card><h2 className="glow-display text-[17px]">Recent Completed Debriefs</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{all.slice(0,3).map(b=><article key={b.id} className="rounded-[12px] bg-[#FDF8F6] p-3"><p className="text-[10.5px] capitalize">{b.kind.replaceAll('_',' ')}</p><p className="text-[9px] text-[#92867E]">{b.generatedAt.toLocaleDateString()}</p></article>)}</div></Card></div></div></SectionPage></AppShell>}
