import Link from 'next/link';
import { ArrowRight, Check, Circle, CloudUpload, FileText, Heart, Home, PawPrint, Plane, Plus, Search, Sparkles } from 'lucide-react';
import { EditableRoomImage } from '@/components/media/editable-room-image';

type Task={id:string;title:string;dueDate:Date|null};
type Event={id:string;title:string;startAt:Date;endAt?:Date|null;location?:string|null};
type ClosetItem={id:string;name:string;category:string;favorite:boolean;status:string;wearCount:number;imageUrl?:string|null};
type GmailRow={id:string;from:string;subject:string;date?:string|null;priority?:string};
type ImportRow={id?:string|null;category?:string|null;summary?:string|null;status?:string|null};

const photo=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=88`;
const HOME_PHOTO=photo('photo-1600607687939-ce8a6c25118c');
const WORLD_PHOTO=photo('photo-1500530855697-b586d89ba3ee');
const TRAVEL_PHOTO=photo('photo-1507525428034-b723cf961d3e');
const PET_PHOTO=photo('photo-1552053831-71594a27632d');
const CLOSET_PHOTO=photo('photo-1551488831-00ddcb6c6bd3');

function Head({eyebrow,title,sub,action}:{eyebrow:string;title:string;sub:string;action?:React.ReactNode}){return <header className="b7-head"><div><p className="b7-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{sub}</p></div>{action}</header>}
function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`b7-card ${className}`}>{children}</section>}
function Ring({value,label}:{value:number;label:string}){const safe=Math.max(0,Math.min(100,value));return <div className="b7-ring" style={{background:`conic-gradient(var(--glow-user-accent) ${safe*3.6}deg,#eee7e2 0)`}}><div><strong>{safe}%</strong><span>{label}</span></div></div>}
function Empty({children}:{children:React.ReactNode}){return <div className="b7-empty"><Circle size={10}/><span>{children}</span></div>}

export function Batch7HomeView({tasks=[]}:{tasks?:Task[]}){
 const homeTasks=tasks.slice(0,5);const clarity=homeTasks.length===0?100:Math.max(20,100-homeTasks.length*12);
 return <div className="b7-root"><Head eyebrow="1. HOME" title="Home" sub="Your safe place. Reset. Recharge. Be present."/>
 <EditableRoomImage slot="batch7:home:hero" label="Home hero" fallbackUrl={HOME_PHOTO} className="b7-home-hero"/>
 <div className="b7-quick-row">{[['Daily Reset','/routines'],['Home Routines','/routines'],['Cleaning Plan','/tasks'],['Space Goals','/goals'],['Supplies','/tasks']].map(([label,href])=><Link key={label} href={href} className="b7-quick"><Home size={13}/><span>{label}</span></Link>)}</div>
 <div className="b7-home-grid"><Card><h2>Today at Home</h2><div className="b7-list">{homeTasks.length?homeTasks.map(t=><Link href={`/tasks?taskId=${encodeURIComponent(t.id)}`} key={t.id}><span><Check size={11}/>{t.title}</span><small>{t.dueDate?t.dueDate.toLocaleDateString('en-US',{month:'short',day:'numeric'}):''}</small></Link>):<Empty>No open home tasks. Your classified home queue is clear.</Empty>}</div></Card><Card className="b7-space-status"><div><h2>Space Status</h2><Ring value={clarity} label="Queue clarity"/><Link href="/tasks">View Details</Link></div><EditableRoomImage slot="batch7:home:status" label="Home detail" fallbackUrl={photo('photo-1494438639946-1ebd1d20bf85')} className="b7-side-image"/></Card></div></div>;
}

const rooms=[['Planning Room','/planning','photo-1497366754035-f200968a6e72'],['Wellness Garden','/wellness','photo-1497250681960-ef046c08a56e'],['Beauty Atelier','/beauty','photo-1522337360788-8b13dee7a37e'],['Financial Hub','/finance','photo-1486406146926-c627a92ad1ab'],['Creative Studio','/creative-studio','photo-1494438639946-1ebd1d20bf85'],['Brain Observatory','/brain','photo-1446776811953-b23d57bd21aa'],['Home Sanctuary','/home','photo-1600566753190-17f0baa2a6c3'],['Workout Studio','/fitness','photo-1534438327276-14e5300c3a48'],['Saint’s Space','/saint-space','photo-1552053831-71594a27632d'],['Dream Loft','/notes','photo-1600607687920-4e2a09cf159d'],['Travel Room','/travel','photo-1507525428034-b723cf961d3e11']];
export function Batch7AllRoomsView(){return <div className="b7-root"><Head eyebrow="2. ALL ROOMS" title="All Rooms" sub="Every part of your world, connected." action={<Link className="b7-soft-btn" href="/settings">Customize Rooms</Link>}/><nav className="b7-tabs" aria-label="Room categories"><Link className="active" href="/all-rooms">All</Link><Link href="/home">Life</Link><Link href="/brain">Mind</Link><Link href="/wellness">Wellness</Link><Link href="/finance">Money</Link><Link href="/home">Home</Link><Link href="/creative-studio">Create</Link><Link href="/settings">Other</Link></nav><div className="b7-room-grid">{rooms.map(([title,href,id],i)=><Link href={href} key={title} className="b7-room"><EditableRoomImage slot={`batch7:room:${i}`} label={title} fallbackUrl={photo(id)} className="b7-room-img"/><strong>{title}</strong><span>Open room</span></Link>)}<Link href="/settings" className="b7-room-add"><Plus size={22}/><span>Create New Room</span></Link></div><Card className="b7-banner"><div><h2>Design your world.</h2><p>Use Settings to shape the rooms and visual system that support your life.</p></div><Link href="/settings">Room Builder</Link></Card></div>}

export function Batch7WorldView({balance=null}:{balance?:number|null}){const nodes=[['Mind','/brain'],['Health','/wellness'],['Relationships','/connections'],['Home','/home'],['Finance','/finance'],['Career','/work'],['Growth','/goals'],['Creativity','/creative-studio']];const value=balance==null?0:Math.max(0,Math.min(100,balance));const bars=balance==null?[18,18,18,18,18]:[Math.max(18,value-28),Math.max(18,value-12),value,Math.max(18,value-20),Math.max(18,value-6)];return <div className="b7-root"><Head eyebrow="3. LIFE WORLD / ATRIUM" title="Life World" sub="Step back. See the big picture." action={<Link className="b7-soft-btn" href="/dashboard">World View</Link>}/><section className="b7-world"><EditableRoomImage slot="batch7:world:hero" label="Life World" fallbackUrl={WORLD_PHOTO} className="b7-world-bg"/><div className="b7-world-center"><EditableRoomImage slot="batch7:world:me" label="Profile" fallbackUrl={photo('photo-1494790108377-be9c29b29330')} className="b7-avatar"/><strong>Me</strong></div>{nodes.map(([n,href],i)=><Link key={n} href={href} className={`b7-world-node n${i+1}`}><Sparkles size={13}/><span>{n}</span></Link>)}</section><div className="b7-world-lower"><Card><h2>Today’s Intention</h2><p>Move with purpose.<br/>Protect your peace.</p></Card><Card><h2>World Balance</h2><div className="b7-bars">{bars.map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}<strong>{balance==null?'—':`${value}%`}<small>{balance==null?'Connect daily data':'Habit completion today'}</small></strong></div></Card></div></div>}

export function Batch7TravelView({events=[]}:{events?:Event[]}){const trip=events[0];return <div className="b7-root"><Head eyebrow="4. TRAVEL" title="Travel" sub="Plans. Adventures. Memories." action={<Link className="b7-primary" href="/calendar">+ New Trip</Link>}/><nav className="b7-tabs" aria-label="Travel views"><Link className="active" href="/travel">Upcoming</Link><Link href="/calendar">Past Trips</Link><Link href="/notes">Bucket List</Link><Link href="/calendar">Itineraries</Link></nav><div className="b7-travel-grid"><Card><EditableRoomImage slot="batch7:travel:hero" label="Travel destination" fallbackUrl={TRAVEL_PHOTO} className="b7-travel-image"/>{trip?<><h2>{trip.title}</h2><div className="b7-trip-meta"><span>{trip.startAt.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span><span>{trip.location||'Location not saved'}</span></div><Link className="b7-outline" href={`/calendar?eventId=${encodeURIComponent(trip.id)}`}>View Itinerary</Link></>:<><h2>No upcoming trip saved</h2><p className="b7-muted">Add a travel, flight, hotel, vacation, airport, or trip event to Calendar and it will appear here.</p><Link className="b7-outline" href="/calendar">Open Calendar</Link></>}</Card><Card><h2>Packing List</h2><Ring value={trip?100:0} label={trip?'Trip linked':'No trip linked'}/><div className="b7-checklist">{['Documents','Clothing','Toiletries','Electronics','Other'].map(x=><Link href="/tasks" key={x}><span><Circle size={10}/> {x}</span></Link>)}</div><Link href="/tasks">Manage packing tasks</Link></Card></div><div className="b7-travel-bottom"><Card><h2>Trip Essentials</h2><div className="b7-quick-row">{['Itinerary','Bookings','Budget','Packing','Notes'].map(x=><Link href={x==='Budget'?'/finance':x==='Notes'?'/notes':x==='Packing'?'/tasks':'/calendar'} key={x} className="b7-quick"><Plane size={12}/><span>{x}</span></Link>)}</div></Card><Card><h2>Next Up</h2>{trip?<><p className="b7-flight"><Plane size={16}/>{trip.title}</p><small>{trip.startAt.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></>:<Empty>No travel event is currently scheduled.</Empty>}</Card></div><div className="b7-quote">We travel not to escape life,<br/>but for life not to escape us.</div></div>}

export function Batch7SaintView({tasks=[]}:{tasks?:Task[]}){return <div className="b7-root"><Head eyebrow="5. SAINT’S SPACE" title="Saint’s Space" sub="For my best friend."/><div className="b7-pet-top"><EditableRoomImage slot="batch7:saint:hero" label="Saint" fallbackUrl={PET_PHOTO} className="b7-pet-image"/><Card><h2>Saint’s Info</h2><div className="b7-profile-empty"><p>Pet profile details are not stored in Glow OS yet.</p><p>Breed, birthday, age, and weight are intentionally left blank instead of being invented.</p><Link href="/notes">Keep profile notes</Link></div></Card></div><div className="b7-quick-row">{['Care Plan','Vet Visits','Medications','Meals'].map((x,i)=><Link href={i===1?'/calendar':'/tasks'} className="b7-quick" key={x}><PawPrint size={13}/><span>{x}</span></Link>)}</div><div className="b7-home-grid"><Card><h2>Today’s Care</h2><div className="b7-list">{tasks.length?tasks.slice(0,5).map(t=><Link href={`/tasks?taskId=${encodeURIComponent(t.id)}`} key={t.id}><span><Check size={11}/>{t.title}</span></Link>):<Empty>No open pet-care tasks are saved.</Empty>}</div></Card><Card className="b7-space-status"><div><h2>Health Overview</h2><Ring value={0} label="No health score"/><Link href="/tasks">Care tasks</Link></div><EditableRoomImage slot="batch7:saint:health" label="Saint health" fallbackUrl={photo('photo-1548199973-03cce0bbc87b')} className="b7-side-image"/></Card></div><div className="b7-banner"><Heart size={14}/><strong>You’re not just my dog,<br/>you’re family.</strong></div></div>}

export function Batch7ClosetView({items=[]}:{items?:ClosetItem[]}){const active=items.filter(x=>x.status==='active');const fav=active.filter(x=>x.favorite);const favoriteShare=active.length?Math.round((fav.length/active.length)*100):0;const inspiration=active.slice(0,6);const mostWorn=[...active].sort((a,b)=>b.wearCount-a.wearCount).slice(0,4);return <div className="b7-root"><Head eyebrow="6. CLOSET" title="Closet" sub="Organized. Curated. Yours." action={<Link className="b7-primary" href="#closet-manage">+ Add Item</Link>}/><nav className="b7-tabs" aria-label="Closet views"><Link className="active" href="/closet">All Items</Link><Link href="#closet-manage">Clothing</Link><Link href="#closet-manage">Shoes</Link><Link href="#closet-manage">Bags</Link><Link href="#closet-manage">Accessories</Link><Link href="#closet-manage">Jewelry</Link><Link href="#closet-manage">Active</Link></nav><div className="b7-metrics">{[['Items',items.length],['Active',active.length],['Favorites',fav.length],['On Wishlist',items.filter(x=>x.status==='wishlist').length]].map(([l,v])=><Card key={String(l)}><strong>{v}</strong><span>{l}</span></Card>)}</div><h2 className="b7-section-title">Outfit Inspiration</h2><div className="b7-closet-strip">{inspiration.length?inspiration.map(x=><div key={x.id} className="b7-clothing"><EditableRoomImage slot={`batch7:closet:${x.id}`} label={x.name} fallbackUrl={x.imageUrl||CLOSET_PHOTO} className="b7-clothing-img"/><span>{x.name}</span></div>):<div className="b7-empty-card">Add active closet pieces to build this strip.</div>}</div><h2 className="b7-section-title">Recently Added</h2><div className="b7-closet-strip small">{items.length?items.slice(0,6).map(x=><Link href={`/closet?itemId=${encodeURIComponent(x.id)}`} key={x.id} className="b7-clothing"><EditableRoomImage slot={`batch7:closet:recent:${x.id}`} label={x.name} fallbackUrl={x.imageUrl||CLOSET_PHOTO} className="b7-clothing-img"/><span>{x.name}</span></Link>):<div className="b7-empty-card">No closet items yet.</div>}</div><div className="b7-closet-bottom"><Card><h2>Favorite Share</h2><Ring value={favoriteShare} label="of active pieces"/></Card><Card><h2>Most Worn</h2><div className="b7-wear-list">{mostWorn.length?mostWorn.map(x=><Link key={x.id} href={`/closet?itemId=${encodeURIComponent(x.id)}`}><span>{x.name}</span><small>{x.wearCount} wears</small></Link>):<Empty>Log wears to see your most-used pieces.</Empty>}</div></Card><Card><h2>Style Profile</h2><p>{active.length?`${active.length} active pieces tracked`:'No active pieces tracked'}<br/><small>Glow will not invent a style label without saved wardrobe data.</small></p></Card></div></div>}

export function Batch7GmailView({rows=[],unread=0}:{rows?:GmailRow[];unread?:number}){const priority=rows.filter(x=>x.priority==='high').length;return <div className="b7-root"><Head eyebrow="7. GMAIL" title="Gmail" sub="All your important emails in one place." action={<a className="b7-primary" href="https://mail.google.com/mail/?view=cm&fs=1" target="_blank" rel="noreferrer">Compose</a>}/><div className="b7-tabs" aria-label="Gmail categories"><span className="active">Primary</span><span>Social</span><span>Updates</span><span>Promotions</span></div><Card className="b7-mail-table">{rows.length?rows.slice(0,8).map(r=><div className="b7-mail-row" key={r.id}><Circle size={10}/><strong>{r.from}</strong><span>{r.subject}</span><small>{r.date||''}</small></div>):<div className="b7-mail-empty">No recent inbox messages returned. Connect or refresh Gmail from Connections.</div>}</Card><div className="b7-mail-metrics">{[['Email Summary',rows.length,'Recent'],['Important',priority,'High priority'],['Unread',unread,'Inbox']].map(([l,v,s])=><Card key={String(l)}><h2>{l}</h2><strong>{v}</strong><span>{s}</span></Card>)}</div><Link href="/search" className="b7-search"><strong>Quick Search</strong><div><Search size={13}/><span>Search Glow...</span></div></Link></div>}

export function Batch7ImportView({recent=[]}:{recent?:ImportRow[]}){return <div className="b7-root"><Head eyebrow="8. IMPORT" title="Import" sub="Bring everything into Glow OS." action={<Link className="b7-primary" href="#import-tools">+ New Import</Link>}/><nav className="b7-tabs" aria-label="Import destinations"><Link className="active" href="/import">All</Link><Link href="/intake">Files</Link><Link href="/connections">Calendar</Link><Link href="/tasks">Tasks</Link><Link href="/notes">Notes</Link><Link href="/gmail">Emails</Link></nav><a href="#import-tools" className="b7-drop"><CloudUpload size={34}/><strong>Open import workspace</strong><span>Upload, review, and confirm imports below</span><small>Files are not imported until you use the real import tools.</small></a><h2 className="b7-section-title">Recent Imports</h2><Card className="b7-import-list">{recent.length?recent.slice(0,6).map((r,i)=><div key={r.id||i}><FileText size={13}/><strong>{r.category||`Import ${i+1}`}</strong><span>{r.summary||'Saved in Glow OS'}</span><small>{r.status||'ready'}</small></div>):<div className="b7-import-empty">No import batches yet.</div>}</Card><div className="b7-banner"><strong>Import once. Organized forever.</strong><ArrowRight size={14}/></div></div>}
