import Link from 'next/link';
import { Circle, Heart, PawPrint, Plane, Plus } from 'lucide-react';
import { EditableRoomImage } from '@/components/media/editable-room-image';

type Task={id:string;title:string;description:string|null;status:'pending'|'in_progress'|'done'|'cancelled';dueDate:Date|null};
type Event={id:string;title:string;startAt:Date;endAt:Date|null;location:string|null};
type ClosetItem={id:string;name:string;category:string;favorite:boolean;status:string;wearCount:number;imageUrl:string|null};
const photo=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=88`;
const TRAVEL_PHOTO=photo('photo-1507525428034-b723cf961d3e');
const PET_PHOTO=photo('photo-1552053831-71594a27632d');
const CLOSET_PHOTO=photo('photo-1551488831-00ddcb6c6bd3');
function Head({eyebrow,title,sub,action}:{eyebrow:string;title:string;sub:string;action?:React.ReactNode}){return <header className="b7-head"><div><p className="b7-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{sub}</p></div>{action}</header>}
function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`b7-card ${className}`}>{children}</section>}
function Empty({children}:{children:React.ReactNode}){return <div className="b7-empty"><Circle size={10}/><span>{children}</span></div>}
function safePct(done:number,total:number){return total?Math.round(done/total*100):0}

export function AuditedTravelView({events=[],tasks=[]}:{events?:Event[];tasks?:Task[]}){
 const trip=events[0];const packingWords=['pack','packing','passport','luggage','suitcase','toiletries','travel documents','flight documents'];const packing=tasks.filter(t=>packingWords.some(w=>`${t.title} ${t.description??''}`.toLowerCase().includes(w)));const completed=packing.filter(t=>t.status==='done').length;const packPct=safePct(completed,packing.length);
 return <div className="b7-root b7-audited"><Head eyebrow="4. TRAVEL" title="Travel" sub="Plans. Adventures. Memories." action={<Link className="b7-primary" href="/calendar">+ New Trip</Link>}/><nav className="b7-tabs" aria-label="Travel views"><Link className="active" href="/travel">Upcoming</Link><Link href="/calendar">Calendar</Link><Link href="/notes">Bucket List</Link><Link href="/tasks">Packing Tasks</Link></nav>
 <div className="b7-travel-grid"><Card><EditableRoomImage slot="batch7:travel:hero" label="Travel destination" fallbackUrl={TRAVEL_PHOTO} className="b7-travel-image"/>{trip?<><h2>{trip.title}</h2><div className="b7-trip-meta"><span>{trip.startAt.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span><span>{trip.location||'Location not saved'}</span></div><Link className="b7-outline" href={`/calendar?eventId=${encodeURIComponent(trip.id)}`}>View Calendar Event</Link></>:<><h2>No upcoming trip saved</h2><p className="b7-muted">Travel only appears here when a matching future calendar event exists.</p><Link className="b7-outline" href="/calendar">Open Calendar</Link></>}</Card>
 <Card className="b7-packing-audit"><h2>Packing Progress</h2>{packing.length?<><div className="b7-ring" style={{background:`conic-gradient(var(--glow-user-accent) ${packPct*3.6}deg,#eee7e2 0)`}}><div><strong>{packPct}%</strong><span>{completed}/{packing.length} tasks done</span></div></div><div className="b7-checklist">{packing.slice(0,5).map(t=><Link href={`/tasks?taskId=${encodeURIComponent(t.id)}`} key={t.id}><span><Circle size={10}/> {t.title}</span><small>{t.status==='done'?'Done':'Open'}</small></Link>)}</div></>:<Empty>No packing-related tasks are saved. Glow will not manufacture a packing percentage.</Empty>}<Link href="/tasks">Manage packing tasks</Link></Card></div>
 <div className="b7-travel-bottom"><Card><h2>Trip Essentials</h2><div className="b7-quick-row">{[['Itinerary','/calendar'],['Bookings','/notes'],['Budget','/finance'],['Packing','/tasks'],['Notes','/notes']].map(([label,href])=><Link href={href} key={label} className="b7-quick"><Plane size={12}/><span>{label}</span></Link>)}</div></Card><Card><h2>Next Up</h2>{trip?<><p className="b7-flight"><Plane size={16}/>{trip.title}</p><small>{trip.startAt.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></>:<Empty>No travel event is currently scheduled.</Empty>}</Card></div><div className="b7-quote">We travel not to escape life,<br/>but for life not to escape us.</div></div>
}

export function AuditedSaintView({tasks=[]}:{tasks?:Task[]}){
 const open=tasks.filter(t=>t.status!=='done'&&t.status!=='cancelled');const completed=tasks.filter(t=>t.status==='done');
 return <div className="b7-root b7-audited"><Head eyebrow="5. SAINT’S SPACE" title="Saint’s Space" sub="For my best friend."/><div className="b7-pet-top"><EditableRoomImage slot="batch7:saint:hero" label="Saint" fallbackUrl={PET_PHOTO} className="b7-pet-image"/><Card><h2>Saint’s Info</h2><div className="b7-profile-empty"><p>Glow does not currently store a structured pet profile for breed, birthday, age, weight, or veterinary health scoring.</p><p>Those fields remain blank until you save real source data.</p><Link href="/notes">Keep profile notes</Link></div></Card></div>
 <div className="b7-quick-row">{[['Care Plan','/tasks'],['Vet Visits','/calendar'],['Medications','/tasks'],['Meals','/tasks']].map(([label,href])=><Link href={href} className="b7-quick" key={label}><PawPrint size={13}/><span>{label}</span></Link>)}</div>
 <div className="b7-home-grid"><Card><h2>Open Care Tasks</h2><div className="b7-list">{open.length?open.slice(0,5).map(t=><Link href={`/tasks?taskId=${encodeURIComponent(t.id)}`} key={t.id}><span><Circle size={11}/>{t.title}</span><small>{t.dueDate?t.dueDate.toLocaleDateString('en-US',{month:'short',day:'numeric'}):''}</small></Link>):<Empty>No open pet-care tasks are saved.</Empty>}</div></Card><Card className="b7-space-status"><div><h2>Care Records</h2><div className="b7-record-count"><strong>{tasks.length}</strong><span>matched task records</span><small>{completed.length} completed</small></div><Link href="/tasks">Care tasks</Link></div><EditableRoomImage slot="batch7:saint:health" label="Saint health" fallbackUrl={photo('photo-1548199973-03cce0bbc87b')} className="b7-side-image"/></Card></div><div className="b7-banner"><Heart size={14}/><strong>You’re not just my dog,<br/>you’re family.</strong></div></div>
}

export function AuditedClosetView({items=[],filter='all'}:{items?:ClosetItem[];filter?:string}){
 const normalized=filter.toLowerCase();const active=items.filter(x=>x.status==='active');const fav=active.filter(x=>x.favorite);const wishlist=items.filter(x=>x.status==='wishlist');const allowed=['all','clothing','shoes','bags','accessories','jewelry','active','wishlist'];const selected=allowed.includes(normalized)?normalized:'all';const shown=items.filter(item=>{if(selected==='all')return true;if(selected==='active')return item.status==='active';if(selected==='wishlist')return item.status==='wishlist';const c=item.category.toLowerCase();if(selected==='shoes')return /shoe|boot|heel|sneaker|sandal/.test(c);if(selected==='bags')return /bag|purse|tote|clutch/.test(c);if(selected==='jewelry')return /jewel|necklace|ring|earring|bracelet/.test(c);if(selected==='accessories')return /accessor|scarf|belt|hat|glasses/.test(c);return /clothing|dress|top|shirt|pant|skirt|coat|jacket/.test(c)});const inspiration=shown.filter(x=>x.status==='active').slice(0,6);const mostWorn=[...active].sort((a,b)=>b.wearCount-a.wearCount).slice(0,4);const favoriteShare=active.length?Math.round(fav.length/active.length*100):0;
 const tabs=[['all','All Items'],['clothing','Clothing'],['shoes','Shoes'],['bags','Bags'],['accessories','Accessories'],['jewelry','Jewelry'],['active','Active'],['wishlist','Wishlist']];
 return <div className="b7-root b7-audited"><Head eyebrow="6. CLOSET" title="Closet" sub="Organized. Curated. Yours." action={<a className="b7-primary" href="#closet-manage"><Plus size={11}/> Add Item</a>}/><nav className="b7-tabs" aria-label="Closet filters">{tabs.map(([key,label])=><Link key={key} className={selected===key?'active':''} href={key==='all'?'/closet':`/closet?filter=${key}`}>{label}</Link>)}</nav><div className="b7-metrics">{[['Items',items.length],['Active',active.length],['Favorites',fav.length],['Wishlist',wishlist.length]].map(([label,value])=><Card key={String(label)}><strong>{value}</strong><span>{label}</span></Card>)}</div>
 <h2 className="b7-section-title">{selected==='all'?'Outfit Inspiration':`${tabs.find(t=>t[0]===selected)?.[1]} View`}</h2><div className="b7-closet-strip">{(selected==='all'?inspiration:shown.slice(0,6)).length?(selected==='all'?inspiration:shown.slice(0,6)).map(x=><Link href={`/closet?itemId=${encodeURIComponent(x.id)}${selected!=='all'?`&filter=${selected}`:''}`} key={x.id} className="b7-clothing"><EditableRoomImage slot={`batch7:closet:${x.id}`} label={x.name} fallbackUrl={x.imageUrl||CLOSET_PHOTO} className="b7-clothing-img"/><span>{x.name}</span></Link>):<div className="b7-empty-card">No wardrobe items match this filter.</div>}</div>
 <h2 className="b7-section-title">Recently Added</h2><div className="b7-closet-strip small">{shown.length?shown.slice(0,6).map(x=><Link href={`/closet?itemId=${encodeURIComponent(x.id)}${selected!=='all'?`&filter=${selected}`:''}`} key={x.id} className="b7-clothing"><EditableRoomImage slot={`batch7:closet:recent:${x.id}`} label={x.name} fallbackUrl={x.imageUrl||CLOSET_PHOTO} className="b7-clothing-img"/><span>{x.name}</span></Link>):<div className="b7-empty-card">No matching closet items.</div>}</div>
 <div className="b7-closet-bottom"><Card><h2>Favorite Share</h2><div className="b7-ring" style={{background:`conic-gradient(var(--glow-user-accent) ${favoriteShare*3.6}deg,#eee7e2 0)`}}><div><strong>{favoriteShare}%</strong><span>of active pieces</span></div></div></Card><Card><h2>Most Worn</h2><div className="b7-wear-list">{mostWorn.length?mostWorn.map(x=><Link key={x.id} href={`/closet?itemId=${encodeURIComponent(x.id)}`}><span>{x.name}</span><small>{x.wearCount} wears</small></Link>):<Empty>Log wears to see your most-used pieces.</Empty>}</div></Card><Card><h2>Style Data</h2><p>{active.length?`${active.length} active pieces tracked`:'No active pieces tracked'}<br/><small>Glow does not assign a style identity unless you save one.</small></p></Card></div></div>
}
