import Link from 'next/link';
import { ArrowRight, CalendarDays, Check, Circle, CloudUpload, FileText, Heart, Home, Mail, PawPrint, Plane, Plus, Search, Shirt, Sparkles } from 'lucide-react';
import { EditableRoomImage } from '@/components/media/editable-room-image';

type Task={id:string;title:string;dueDate:Date|null};
type Event={id:string;title:string;startAt:Date;endAt?:Date|null;location?:string|null};
type ClosetItem={id:string;name:string;category:string;favorite:boolean;status:string;wearCount:number;imageUrl?:string|null};
type GmailRow={id:string;from:string;subject:string;date?:string|null;priority?:string};
type ImportRow={id?:string|null;category?:string|null;summary?:string|null;status?:string|null};

const photo=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=88`;
const HOME_PHOTO=photo('photo-1600607687939-ce8a6c25118c');
const WORLD_PHOTO=photo('photo-1500530855697-b586d89ba3ee');
const TRAVEL_PHOTO=photo('photo-1507525428034-b723cf961d3e');
const PET_PHOTO=photo('photo-1552053831-71594a27632d');
const CLOSET_PHOTO=photo('photo-1551488831-00ddcb6c6bd3');

function Head({eyebrow,title,sub,action}:{eyebrow:string;title:string;sub:string;action?:React.ReactNode}){return <header className="b7-head"><div><p className="b7-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{sub}</p></div>{action}</header>}
function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`b7-card ${className}`}>{children}</section>}
function Ring({value,label}:{value:number;label:string}){return <div className="b7-ring" style={{background:`conic-gradient(var(--glow-user-accent) ${value*3.6}deg,#eee7e2 0)`}}><div><strong>{value}%</strong><span>{label}</span></div></div>}

export function Batch7HomeView({tasks=[]}:{tasks?:Task[]}){
 const homeTasks=tasks.slice(0,5);return <div className="b7-root"><Head eyebrow="1. HOME" title="Home" sub="Your safe place. Reset. Recharge. Be present."/>
 <EditableRoomImage slot="batch7:home:hero" label="Home hero" fallbackUrl={HOME_PHOTO} className="b7-home-hero"/>
 <div className="b7-quick-row">{[['Daily Reset','/routines'],['Home Routines','/routines'],['Cleaning Plan','/tasks'],['Space Goals','/goals'],['Supplies','/tasks']].map(([label,href])=><Link key={label} href={href} className="b7-quick"><Home size={13}/><span>{label}</span></Link>)}</div>
 <div className="b7-home-grid"><Card><h2>Today at Home</h2><div className="b7-list">{homeTasks.length?homeTasks.map((t,i)=><Link href={`/tasks?taskId=${t.id}`} key={t.id}><span><Check size={11}/>{t.title}</span><small>{t.dueDate?t.dueDate.toLocaleDateString('en-US',{month:'short',day:'numeric'}):i===0?'Today':''}</small></Link>):['Make bed & open windows','10 minute tidy','Laundry','Water plants','Evening reset'].map(x=><div key={x}><span><Circle size={10}/>{x}</span></div>)}</div></Card><Card className="b7-space-status"><div><h2>Space Status</h2><Ring value={82} label="Calm & Clear"/><Link href="/tasks">View Details</Link></div><EditableRoomImage slot="batch7:home:status" label="Home detail" fallbackUrl={photo('photo-1494438639946-1ebd1d20bf85')} className="b7-side-image"/></Card></div></div>;
}

const rooms=[['Planning Room','/planning','photo-1497366754035-f200968a6e72'],['Wellness Garden','/wellness','photo-1497250681960-ef046c08a56e'],['Beauty Atelier','/beauty','photo-1522337360788-8b13dee7a37e'],['Financial Hub','/finance','photo-1486406146926-c627a92ad1ab'],['Creative Studio','/creative-studio','photo-1494438639946-1ebd1d20bf85'],['Brain Observatory','/brain','photo-1446776811953-b23d57bd21aa'],['Home Sanctuary','/home','photo-1600566753190-17f0baa2a6c3'],['Workout Studio','/fitness','photo-1534438327276-14e5300c3a48'],['Saint’s Space','/saint-space','photo-1552053831-71594a27632d'],['Dream Loft','/notes','photo-1600607687920-4e2a09cf159d'],['Travel Room','/travel','photo-1507525428034-b723cf961d3e']];
export function Batch7AllRoomsView(){return <div className="b7-root"><Head eyebrow="2. ALL ROOMS" title="All Rooms" sub="Every part of your world, connected." action={<Link className="b7-soft-btn" href="/settings">Customize Rooms</Link>}/><div className="b7-tabs">{['All','Life','Mind','Wellness','Money','Home','Create','Other'].map((x,i)=><button key={x} className={i===0?'active':''}>{x}</button>)}</div><div className="b7-room-grid">{rooms.map(([title,href,id],i)=><Link href={href} key={title} className="b7-room"><EditableRoomImage slot={`batch7:room:${i}`} label={title} fallbackUrl={photo(id)} className="b7-room-img"/><strong>{title}</strong><span>{i%4+5} items</span></Link>)}<Link href="/settings" className="b7-room-add"><Plus size={22}/><span>Create New Room</span></Link></div><Card className="b7-banner"><div><h2>Design your world.</h2><p>Add, remove, or rearrange rooms that support your life.</p></div><Link href="/settings">Room Builder</Link></Card></div>}

export function Batch7WorldView({signals=[]}:{signals?:string[]}){const nodes=[['Mind','/brain'],['Health','/wellness'],['Relationships','/connections'],['Home','/home'],['Finance','/finance'],['Career','/work'],['Growth','/goals'],['Creativity','/creative-studio']];return <div className="b7-root"><Head eyebrow="3. LIFE WORLD / ATRIUM" title="Life World" sub="Step back. See the big picture." action={<button className="b7-soft-btn">World View⌄</button>}/><section className="b7-world"><EditableRoomImage slot="batch7:world:hero" label="Life World" fallbackUrl={WORLD_PHOTO} className="b7-world-bg"/><div className="b7-world-center"><EditableRoomImage slot="batch7:world:me" label="Profile" fallbackUrl={photo('photo-1494790108377-be9c29b29330')} className="b7-avatar"/><strong>Me</strong></div>{nodes.map(([n,href],i)=><Link key={n} href={href} className={`b7-world-node n${i+1}`}><Sparkles size={13}/><span>{n}</span></Link>)}</section><div className="b7-world-lower"><Card><h2>Today’s Intention</h2><p>Move with purpose.<br/>Protect your peace.</p></Card><Card><h2>World Balance</h2><div className="b7-bars">{[35,62,79,48,70].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}<strong>{signals[0]||'78%'}<small>Aligned</small></strong></div></Card></div></div>}

export function Batch7TravelView({events=[]}:{events?:Event[]}){const trip=events[0];return <div className="b7-root"><Head eyebrow="4. TRAVEL" title="Travel" sub="Plans. Adventures. Memories." action={<Link className="b7-primary" href="/calendar">+ New Trip</Link>}/><div className="b7-tabs"><button className="active">Upcoming</button><button>Past Trips</button><button>Bucket List</button><button>Itineraries</button></div><div className="b7-travel-grid"><Card><EditableRoomImage slot="batch7:travel:hero" label="Travel destination" fallbackUrl={TRAVEL_PHOTO} className="b7-travel-image"/><h2>{trip?.title||'Italy – Summer Escape'}</h2><div className="b7-trip-meta"><span>{trip?trip.startAt.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'May 20 – Jun 2, 2025'}</span><span>{trip?.location||'12 days'}</span></div><Link className="b7-outline" href={trip?`/calendar?eventId=${trip.id}`:'/calendar'}>View Itinerary</Link></Card><Card><h2>Packing List</h2><Ring value={76} label="Packed"/><div className="b7-checklist">{['Documents','Clothing','Toiletries','Electronics','Other'].map((x,i)=><div key={x}><span>{i<3?<Check size={11}/>:<Circle size={10}/>} {x}</span></div>)}</div><Link href="/tasks">View all</Link></Card></div><div className="b7-travel-bottom"><Card><h2>Trip Essentials</h2><div className="b7-quick-row">{['Itinerary','Bookings','Budget','Packing','Notes'].map(x=><Link href={x==='Budget'?'/finance':x==='Notes'?'/notes':'/calendar'} key={x} className="b7-quick"><Plane size={12}/><span>{x}</span></Link>)}</div></Card><Card><h2>Next Up</h2><p className="b7-flight"><Plane size={16}/> Flight to Rome</p><small>Check in 24h before</small></Card></div><div className="b7-quote">We travel not to escape life,<br/>but for life not to escape us.</div></div>}

export function Batch7SaintView({tasks=[]}:{tasks?:Task[]}){return <div className="b7-root"><Head eyebrow="5. SAINT’S SPACE" title="Saint’s Space" sub="For my best friend."/><div className="b7-pet-top"><EditableRoomImage slot="batch7:saint:hero" label="Saint" fallbackUrl={PET_PHOTO} className="b7-pet-image"/><Card><h2>Saint’s Info</h2><dl className="b7-dl"><dt>Breed</dt><dd>Golden Retriever</dd><dt>Birthday</dt><dd>Oct 12, 2021</dd><dt>Age</dt><dd>3 yrs</dd><dt>Weight</dt><dd>68 lbs</dd></dl></Card></div><div className="b7-quick-row">{['Care Plan','Vet Visits','Medications','Meals'].map((x,i)=><Link href={i===1?'/calendar':'/tasks'} className="b7-quick" key={x}><PawPrint size={13}/><span>{x}</span></Link>)}</div><div className="b7-home-grid"><Card><h2>Today’s Care</h2><div className="b7-list">{tasks.length?tasks.slice(0,5).map(t=><Link href={`/tasks?taskId=${t.id}`} key={t.id}><span><Check size={11}/>{t.title}</span></Link>):['Morning Walk','Breakfast','Brush & Play','Evening Walk','Night Treat'].map(x=><div key={x}><span><Check size={11}/>{x}</span></div>)}</div></Card><Card className="b7-space-status"><div><h2>Health Overview</h2><Ring value={95} label="Happy & Healthy"/></div><EditableRoomImage slot="batch7:saint:health" label="Saint health" fallbackUrl={photo('photo-1548199973-03cce0bbc87b')} className="b7-side-image"/></Card></div><div className="b7-banner"><Heart size={14}/><strong>You’re not just my dog,<br/>you’re family.</strong></div></div>}

export function Batch7ClosetView({items=[]}:{items?:ClosetItem[]}){const active=items.filter(x=>x.status==='active');const fav=active.filter(x=>x.favorite);return <div className="b7-root"><Head eyebrow="6. CLOSET" title="Closet" sub="Organized. Curated. Yours." action={<Link className="b7-primary" href="#closet-manage">+ Add Item</Link>}/><div className="b7-tabs">{['All Items','Clothing','Shoes','Bags','Accessories','Jewelry','Active'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div><div className="b7-metrics">{[['Items',items.length],['Outfits',Math.max(0,Math.floor(active.length/3))],['Favorites',fav.length],['On Wishlist',items.filter(x=>x.status==='wishlist').length]].map(([l,v])=><Card key={String(l)}><strong>{v}</strong><span>{l}</span></Card>)}</div><h2 className="b7-section-title">Outfit Inspiration</h2><div className="b7-closet-strip">{(active.length?active.slice(0,6):Array.from({length:6},(_,i)=>({id:String(i),name:'Wardrobe piece',imageUrl:null}))).map((x:any,i)=><div key={x.id} className="b7-clothing"><EditableRoomImage slot={`batch7:closet:${x.id}`} label={x.name} fallbackUrl={x.imageUrl||CLOSET_PHOTO} className="b7-clothing-img"/></div>)}</div><h2 className="b7-section-title">Recently Added</h2><div className="b7-closet-strip small">{items.slice(0,6).map((x,i)=><Link href={`/closet?itemId=${x.id}`} key={x.id} className="b7-clothing"><EditableRoomImage slot={`batch7:closet:recent:${x.id}`} label={x.name} fallbackUrl={x.imageUrl||photo('photo-1542291026-7eec264c27ff')} className="b7-clothing-img"/><span>{x.name}</span></Link>)}</div><div className="b7-closet-bottom"><Card><h2>Wardrobe Status</h2><Ring value={83} label="Well Balanced"/></Card><Card><h2>Most Worn Colors</h2><div className="b7-swatches">{['#e7dfd6','#b9a38d','#837363','#69717a'].map(x=><i style={{background:x}} key={x}/>)}</div></Card><Card><h2>Style Profile</h2><p>Classic Minimalist<br/><small>with a feminine edge</small></p></Card></div></div>}

export function Batch7GmailView({rows=[],unread=0}:{rows?:GmailRow[];unread?:number}){return <div className="b7-root"><Head eyebrow="7. GMAIL" title="Gmail" sub="All your important emails in one place." action={<a className="b7-primary" href="https://mail.google.com/mail/?view=cm&fs=1" target="_blank" rel="noreferrer">Compose</a>}/><div className="b7-tabs"><button className="active">Primary</button><button>Social</button><button>Updates</button><button>Promotions</button></div><Card className="b7-mail-table">{rows.length?rows.slice(0,8).map((r,i)=><div className="b7-mail-row" key={r.id}><Circle size={10}/><strong>{r.from}</strong><span>{r.subject}</span><small>{r.date||'Today'}</small></div>):['Interview Update – Bluemercury','Next Steps','Schedule Change Request','Your Weekly Update','Thank you for your interest','Project Files – Terrain Design','Lab Results Available','Your Order Has Shipped'].map((s,i)=><div className="b7-mail-row" key={s}><Circle size={10}/><strong>{['Andrea','Victoria','Bloomingdale’s HR','Sephora','Arhaus','Tatiyana (me)','Doctor Pearson','Amazon'][i]}</strong><span>{s}</span><small>{i<1?'9:15 AM':'Yesterday'}</small></div>)}</Card><div className="b7-mail-metrics">{[['Email Summary',unread||12,'Unread'],['Important',rows.filter(x=>x.priority==='high').length||4,'Needs Reply'],['Attachments',7,'This Week']].map(([l,v,s])=><Card key={String(l)}><h2>{l}</h2><strong>{v}</strong><span>{s}</span></Card>)}</div><Card className="b7-search"><strong>Quick Search</strong><div><Search size={13}/><span>Search emails...</span></div></Card></div>}

export function Batch7ImportView({recent=[]}:{recent?:ImportRow[]}){return <div className="b7-root"><Head eyebrow="8. IMPORT" title="Import" sub="Bring everything into Glow OS." action={<Link className="b7-primary" href="/intake">+ New Import</Link>}/><div className="b7-tabs"><button className="active">All</button><button>Files</button><button>Calendar</button><button>Tasks</button><button>Notes</button><button>Emails</button></div><Link href="/intake" className="b7-drop"><CloudUpload size={34}/><strong>Drag & drop files here</strong><span>or browse to import</span><small>Supports PDF, CSV, Images, Docs & more</small></Link><h2 className="b7-section-title">Recent Imports</h2><Card className="b7-import-list">{recent.length?recent.slice(0,6).map((r,i)=><div key={r.id||i}><FileText size={13}/><strong>{r.category||`Import ${i+1}`}</strong><span>{r.summary||'Saved in Glow OS'}</span><small>{r.status||'ready'}</small></div>):['Health Records.pdf','Workout Plan.csv','Budget 2025.xlsx','Travel Itinerary.pdf','Recipes Collection.pdf'].map((x,i)=><div key={x}><FileText size={13}/><strong>{x}</strong><span>{['Health','Fitness','Finance','Travel','Food'][i]}</span><small>May {13-i}, 2025</small></div>)}</Card><div className="b7-banner"><strong>Import once. Organized forever.</strong><ArrowRight size={14}/></div></div>}
