'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Clock3, Play, Sparkles } from 'lucide-react';

type Task={id:string;title:string;description:string|null;status:string;priority:string;dueDate:Date|null;completedAt:Date|null;archived:boolean};
type Event={id:string;title:string;startAt:Date;endAt:Date|null;allDay:boolean};
type Project={id:string;title:string;status:string;priority:string;progress:number;nextAction:string|null;deadline:Date|null;updatedAt:Date};
type Goal={id:string;title:string;status:string;category:string;progress:number;targetDate:Date|null};
type Routine={id:string;name:string;description:string|null;timeOfDay:string;daysOfWeek:string[]|null};
type RoutineStep={id:string;routineId:string;title:string;durationMinutes:number|null;order:number};
type PlanningBlock={id:string;sourceType:string;sourceId:string|null;title:string;reason:string;startAt:Date;endAt:Date;status:string};
type Period={id:string;level:string;title:string;focus:string|null;reflection:string|null;progress:number;startsAt:Date|null;endsAt:Date|null};
type Note={id:string;title:string;updatedAt:Date};
type BlockedTask={task:Task;blockedBy:string[]};
type Tab='today'|'week'|'priorities'|'budget'|'builder'|'batches'|'routines'|'scenarios'|'reviews'|'memory'|'insights';
type Horizon='Today'|'Tomorrow'|'This Week'|'Next Week'|'This Month'|'Season';
type DayMode='Very productive'|'Normal productive'|'Low productive'|'Cancel everything';
type BufferStyle='Minimal'|'Balanced'|'Spacious'|'Recovery-focused';
type Scenario='Productive'|'Balanced'|'Gentle';
type PlanMemory={drivers:string[];dayMode:DayMode;buffer:BufferStyle;scenario:Scenario;awakeHours:number;mealsTransitions:number;recoveryHours:number;notes:string[];feelings:string[]};

const KEY='glow:planning-intelligence:v1';
const tabs:Tab[]=['today','week','priorities','budget','builder','batches','routines','scenarios','reviews','memory','insights'];
const horizons:Horizon[]=['Today','Tomorrow','This Week','Next Week','This Month','Season'];
const defaults:PlanMemory={drivers:[],dayMode:'Normal productive',buffer:'Balanced',scenario:'Balanced',awakeHours:16,mealsTransitions:2.25,recoveryHours:2,notes:[],feelings:[]};
const TZ='America/New_York';

function keyFor(date:Date){const parts=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${map.year}-${map.month}-${map.day}`;}
function addDays(date:Date,days:number){const d=new Date(date);d.setDate(d.getDate()+days);return d;}
function durationHours(start:Date,end:Date|null){if(!end)return 0;return Math.max(0,(new Date(end).getTime()-new Date(start).getTime())/3600000);}
function fmtTime(date:Date){return new Intl.DateTimeFormat('en-US',{timeZone:TZ,hour:'numeric',minute:'2-digit'}).format(new Date(date));}
function fmtDay(date:Date){return new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'short',month:'short',day:'numeric'}).format(new Date(date));}
function openGlow(prompt:string){window.dispatchEvent(new CustomEvent('glow:open-conversation',{detail:{prompt}}));}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[28px] border border-white/75 bg-white/52 p-5 shadow-[0_18px_70px_rgba(72,82,96,.08)] backdrop-blur-xl"><div className="mb-4 text-[10px] uppercase tracking-[.25em] text-[#727984]">{title}</div>{children}</section>}
function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="rounded-[21px] border border-white/80 bg-white/45 p-4"><div className="text-[9px] uppercase tracking-[.18em] text-[#7d828b]">{label}</div><div className="mt-2 text-sm font-medium text-[#31343a]">{value}</div>{sub?<div className="mt-1 text-[10px] text-[#858993]">{sub}</div>:null}</div>}
function normalize(value:unknown):PlanMemory{if(!value||typeof value!=='object')return defaults;const v=value as Partial<PlanMemory>;return{drivers:Array.isArray(v.drivers)?v.drivers.filter((x):x is string=>typeof x==='string').slice(0,3):[],dayMode:['Very productive','Normal productive','Low productive','Cancel everything'].includes(v.dayMode??'')?v.dayMode as DayMode:defaults.dayMode,buffer:['Minimal','Balanced','Spacious','Recovery-focused'].includes(v.buffer??'')?v.buffer as BufferStyle:defaults.buffer,scenario:['Productive','Balanced','Gentle'].includes(v.scenario??'')?v.scenario as Scenario:defaults.scenario,awakeHours:typeof v.awakeHours==='number'?Math.min(20,Math.max(8,v.awakeHours)):16,mealsTransitions:typeof v.mealsTransitions==='number'?Math.min(6,Math.max(0,v.mealsTransitions)):2.25,recoveryHours:typeof v.recoveryHours==='number'?Math.min(8,Math.max(0,v.recoveryHours)):2,notes:Array.isArray(v.notes)?v.notes.filter((x):x is string=>typeof x==='string').slice(-30):[],feelings:Array.isArray(v.feelings)?v.feelings.filter((x):x is string=>typeof x==='string').slice(-20):[]};}
function classify(task:Task){const text=`${task.title} ${task.description??''}`.toLowerCase();if(/call|email|book|schedule|appointment|form|reply/.test(text))return'Phone / admin';if(/grocery|store|return|pickup|pick up|post office|pharmacy|target/.test(text))return'Out of house';if(/design|write|portfolio|website|research|computer|budget|document/.test(text))return'Computer / focus';if(/clean|laundry|organize|room|home/.test(text))return'At home';return'Flexible';}

export function PlanningIntelligenceStudio({tasks,events,projects,goals,routines,routineSteps,planningBlocks,periods,notes,blockedTasks,nowIso}:{tasks:Task[];events:Event[];projects:Project[];goals:Goal[];routines:Routine[];routineSteps:RoutineStep[];planningBlocks:PlanningBlock[];periods:Period[];notes:Note[];blockedTasks:BlockedTask[];nowIso:string}){
 const now=useMemo(()=>new Date(nowIso),[nowIso]);
 const [tab,setTab]=useState<Tab>('today');
 const [horizon,setHorizon]=useState<Horizon>('Tomorrow');
 const [memory,setMemory]=useState<PlanMemory>(defaults);
 const [hydrated,setHydrated]=useState(false);
 const [rescue,setRescue]=useState<string|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setMemory(normalize(JSON.parse(raw)));}catch{}setHydrated(true);},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(KEY,JSON.stringify(memory));}catch{}},[memory,hydrated]);

 const todayKey=keyFor(now);const tomorrow=addDays(now,1);const tomorrowKey=keyFor(tomorrow);
 const openTasks=tasks.filter(t=>!t.archived&&t.status!=='done'&&t.status!=='cancelled');
 const activeProjects=projects.filter(p=>p.status==='active');const activeGoals=goals.filter(g=>g.status==='active');
 const tomorrowEvents=events.filter(e=>keyFor(new Date(e.startAt))===tomorrowKey);
 const todayEvents=events.filter(e=>keyFor(new Date(e.startAt))===todayKey);
 const weekDates=Array.from({length:7},(_,i)=>addDays(now,i));
 const weekKeys=new Set(weekDates.map(keyFor));
 const weekEvents=events.filter(e=>weekKeys.has(keyFor(new Date(e.startAt))));
 const fixedTomorrow=tomorrowEvents.reduce((sum,e)=>sum+durationHours(new Date(e.startAt),e.endAt?new Date(e.endAt):null),0);
 const routineMinutes=routineSteps.reduce((sum,s)=>sum+(s.durationMinutes??0),0);
 const routineHours=routineMinutes/60;
 const discretionary=Math.max(0,memory.awakeHours-fixedTomorrow-routineHours-memory.mealsTransitions-memory.recoveryHours);
 const tomorrowDue=openTasks.filter(t=>t.dueDate&&keyFor(new Date(t.dueDate))===tomorrowKey);
 const urgent=openTasks.filter(t=>t.priority==='urgent'||t.priority==='high');
 const priorityProjects=activeProjects.slice().sort((a,b)=>({urgent:4,high:3,medium:2,low:1}[b.priority]??0)-({urgent:4,high:3,medium:2,low:1}[a.priority]??0)||(a.deadline?new Date(a.deadline).getTime():Infinity)-(b.deadline?new Date(b.deadline).getTime():Infinity));
 const derivedDrivers=[...activeGoals.map(g=>g.title),...priorityProjects.map(p=>p.title)].filter((v,i,a)=>a.indexOf(v)===i).slice(0,3);
 const drivers=memory.drivers.length?memory.drivers:derivedDrivers;
 const topPriority=priorityProjects[0]?.nextAction||tomorrowDue[0]?.title||urgent[0]?.title||openTasks[0]?.title||'Protect open space and choose one meaningful next move.';
 const capacityPct=Math.round(Math.min(140,((fixedTomorrow+routineHours+memory.mealsTransitions+memory.recoveryHours)/Math.max(1,memory.awakeHours))*100));
 const conflict=blockedTasks.length?`${blockedTasks.length} blocked task${blockedTasks.length===1?'':'s'} need prerequisites`:capacityPct>95?'Tomorrow is close to or over your planning capacity':tomorrowEvents.length>3?'Several fixed commitments may fragment the day':'No major conflict detected from recorded commitments';
 const confidence=capacityPct>100||blockedTasks.length>2?'Low':capacityPct>82||tomorrowEvents.length>4?'Medium':'High';
 const batches=Object.entries(openTasks.reduce<Record<string,Task[]>>((acc,t)=>{const k=classify(t);(acc[k]??=[]).push(t);return acc;},{}));
 const acceptedBlocks=planningBlocks.filter(b=>b.status==='accepted');
 const planItems=[...tomorrowEvents.map(e=>({time:fmtTime(new Date(e.startAt)),title:e.title,type:'FIXED'})),...acceptedBlocks.filter(b=>keyFor(new Date(b.startAt))===tomorrowKey).map(b=>({time:fmtTime(new Date(b.startAt)),title:b.title,type:'FLEXIBLE'}))].sort((a,b)=>a.time.localeCompare(b.time));
 const scenarioText:Record<Scenario,string>={Productive:'Protect one or two meaningful work blocks, then batch maintenance around them.',Balanced:'Protect one important move, normal life maintenance, and visible breathing room.',Gentle:'Keep genuine commitments, one small future-facing action, and extra recovery space.'};
 function record(note:string){setMemory(m=>({...m,notes:[...m.notes,`${new Intl.DateTimeFormat('en-US',{timeZone:TZ,month:'short',day:'numeric'}).format(now)} · ${note}`].slice(-30)}));}
 function ask(prompt:string){openGlow(prompt);record(prompt.slice(0,120));}

 return <div className="min-h-screen rounded-[36px] bg-[radial-gradient(circle_at_18%_4%,rgba(255,227,215,.72),transparent_28%),radial-gradient(circle_at_82%_10%,rgba(211,226,239,.84),transparent_34%),radial-gradient(circle_at_55%_80%,rgba(224,235,222,.7),transparent_30%),linear-gradient(150deg,#fbf8f1_0%,#f0f3f5_48%,#eef0ed_100%)] p-3 text-[#30343a] sm:p-5">
  <div className="rounded-[31px] border border-white/75 bg-white/35 p-5 shadow-[0_35px_100px_rgba(72,81,91,.11)] backdrop-blur-2xl sm:p-7">
   <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.32em] text-[#727984]">Planning · Life Orchestration</div><h1 className="mt-2 glow-display text-3xl sm:text-5xl">Shape time around what matters.</h1><p className="mt-3 max-w-2xl text-sm text-[#6e747c]">What matters most, what realistically fits, and how should I arrange my time so life actually works?</p></div><button onClick={()=>ask('Help me plan from right now. Use my real calendar, tasks, projects, goals, routines, blockers and available capacity. Keep the plan realistic.')} className="couture-secondary"><Sparkles className="mr-2 inline h-4 w-4"/>Ask Glow</button></div>
   <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{horizons.map(item=><button key={item} onClick={()=>setHorizon(item)} className={`shrink-0 rounded-full px-4 py-2 text-[10px] ${horizon===item?'bg-[#35414a] text-white':'border border-white/80 bg-white/48'}`}>{item}</button>)}</div>
   <div className="mt-3 flex gap-2 overflow-x-auto pb-1">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`shrink-0 rounded-full px-4 py-2 text-[10px] capitalize ${tab===item?'bg-[#56646e] text-white':'border border-white/75 bg-white/38'}`}>{item}</button>)}</div>
  </div>

  <div className="mt-4 space-y-4">
   {tab==='today'?<><Panel title={`Planning · ${horizon}`}><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div><div className="text-xs text-[#757b84]">{new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'long',month:'long',day:'numeric',hour:'numeric',minute:'2-digit'}).format(now)}</div><h2 className="mt-3 glow-display text-3xl">{topPriority}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Tomorrow" value={fmtDay(tomorrow)}/><Metric label="Available focus time" value={`${discretionary.toFixed(1)} h`} sub="Estimate from editable planning assumptions"/><Metric label="Unscheduled priorities" value={`${urgent.length}`}/><Metric label="Potential conflict" value={conflict}/></div><div className="mt-5 flex flex-wrap gap-2"><a href="#build-my-day" className="couture-primary"><Play className="mr-2 inline h-4 w-4"/>Plan my day</a><button onClick={()=>ask('What should happen next from the current time? Use my upcoming calendar event, unfinished priorities and energy-sensitive planning.')} className="couture-secondary">What next?</button><button onClick={()=>ask('Replan the rest of today from now. Keep fixed commitments, move flexible work, and do not carry impossible work forward.')} className="couture-secondary">Replan from now</button><button onClick={()=>setRescue(rescue?'': 'open')} className="couture-secondary">Help me plan</button></div></div><div className="rounded-[25px] border border-white/75 bg-white/45 p-5"><div className="text-[10px] uppercase tracking-[.2em]">Day mode</div><div className="mt-3 space-y-2">{(['Very productive','Normal productive','Low productive','Cancel everything'] as DayMode[]).map(m=><button key={m} onClick={()=>{setMemory(v=>({...v,dayMode:m}));record(`Day mode set to ${m}.`);}} className={`w-full rounded-2xl px-3 py-2 text-left text-xs ${memory.dayMode===m?'bg-[#45525b] text-white':'bg-white/55'}`}>{m}</button>)}</div></div></div>{rescue?<div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{['My week is chaos','Tomorrow is too busy','I am behind','I only have 20 minutes','I need a recovery day','I do not know what matters','Something came up','I keep procrastinating'].map(x=><button key={x} onClick={()=>ask(`Planning rescue: ${x}. Rebuild a realistic plan using my recorded commitments and priorities.`)} className="rounded-2xl border border-white/70 bg-white/48 p-3 text-left text-xs">{x}</button>)}</div>:null}</Panel><Panel title="Make tomorrow easier"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-lg font-medium">Reduce friction before tomorrow starts.</div><div className="mt-1 text-xs text-[#767c84]">Prep decisions, materials, travel and anything that can safely move.</div></div><button onClick={()=>ask('Make tomorrow easier. Look at tomorrow’s real events and tasks, then tell me what I can prepare tonight and what I should move.')} className="couture-primary">Prepare tomorrow</button></div></Panel></>:null}

   {tab==='week'?<><Panel title="This week · luminous timeway"><div className="grid gap-3 md:grid-cols-7">{weekDates.map(date=>{const k=keyFor(date);const dayEvents=events.filter(e=>keyFor(new Date(e.startAt))===k);const fixed=dayEvents.reduce((s,e)=>s+durationHours(new Date(e.startAt),e.endAt?new Date(e.endAt):null),0);const load=Math.min(100,Math.round((fixed/Math.max(1,memory.awakeHours))*100));return <div key={k} className="min-h-40 rounded-[24px] border border-white/75 bg-white/45 p-4"><div className="text-[10px] uppercase tracking-[.18em]">{fmtDay(date)}</div><div className="mt-4 h-20 rounded-full bg-white/55 p-1"><div className="w-full rounded-full bg-[#bacbd4]/75" style={{height:`${Math.max(5,load)}%`}}/></div><div className="mt-3 text-xs">{dayEvents.length} fixed · {fixed.toFixed(1)}h</div></div>})}</div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>ask('Balance my next seven days. Move only flexible work, protect fixed commitments, keep recovery space, and use my top three drivers.')} className="couture-primary">Balance week</button><button onClick={()=>ask('Build next week with a weekly reset: review calendar, goals, projects, task bank, three drivers, routines, deep work, errands and open space.')} className="couture-secondary">Build next week</button></div></Panel><Panel title="Three weekly drivers"><div className="grid gap-3 md:grid-cols-3">{[0,1,2].map(index=><div key={index} className="rounded-[22px] border border-white/75 bg-white/45 p-4"><div className="text-[9px] uppercase tracking-[.18em]">Driver {index+1}</div><input value={drivers[index]??''} onChange={e=>{const next=[...drivers];next[index]=e.target.value;setMemory(m=>({...m,drivers:next.filter(Boolean).slice(0,3)}));}} placeholder="Choose a driver" className="mt-3 w-full bg-transparent text-sm outline-none"/></div>)}</div><button onClick={()=>ask(`Simplify my week around these drivers: ${drivers.join('; ')||'help me choose three from my goals and projects'}.`)} className="couture-secondary mt-4">Simplify my week</button></Panel></>:null}

   {tab==='priorities'?<Panel title="Priority hierarchy"><div className="grid gap-4 lg:grid-cols-2"><Priority title="Must move" items={[...tomorrowDue,...urgent].filter((v,i,a)=>a.findIndex(x=>x.id===v.id)===i).slice(0,8).map(t=>t.title)} empty="No recorded urgent or tomorrow-due tasks."/><Priority title="Should move" items={priorityProjects.slice(0,6).map(p=>p.nextAction||p.title)} empty="No active project priorities recorded."/><Priority title="Maintenance" items={routines.slice(0,6).map(r=>r.name)} empty="No active routines recorded."/><Priority title="Later / task bank" items={openTasks.filter(t=>t.priority==='low').slice(0,8).map(t=>t.title)} empty="No low-priority tasks recorded."/></div></Panel>:null}

   {tab==='budget'?<><Panel title="Tomorrow · Time Budget"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Awake time" value={`${memory.awakeHours}h`} sub="Planning assumption"/><Metric label="Fixed commitments" value={`${fixedTomorrow.toFixed(1)}h`} sub={`${tomorrowEvents.length} calendar events`}/><Metric label="Recorded routines" value={`${routineHours.toFixed(1)}h`} sub={`${routineSteps.filter(s=>s.durationMinutes).length} timed steps`}/><Metric label="Meals + transitions" value={`${memory.mealsTransitions}h`} sub="Planning assumption"/><Metric label="Recovery" value={`${memory.recoveryHours}h`} sub="Planning assumption"/></div><div className="mt-5 rounded-[24px] bg-white/48 p-5"><div className="flex items-center justify-between"><div><div className="text-[10px] uppercase tracking-[.18em]">Real discretionary estimate</div><div className="mt-2 glow-display text-3xl">{discretionary.toFixed(1)}h</div></div><div className="text-right"><div className="text-[10px] uppercase tracking-[.18em]">Capacity</div><div className="mt-2 text-xl">{capacityPct}%</div></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-[#8da6b2]" style={{width:`${Math.min(100,capacityPct)}%`}}/></div></div></Panel><Panel title="Planning assumptions"><div className="grid gap-3 sm:grid-cols-3"><Assumption label="Awake hours" value={memory.awakeHours} set={v=>setMemory(m=>({...m,awakeHours:v}))}/><Assumption label="Meals + transitions" value={memory.mealsTransitions} set={v=>setMemory(m=>({...m,mealsTransitions:v}))}/><Assumption label="Recovery hours" value={memory.recoveryHours} set={v=>setMemory(m=>({...m,recoveryHours:v}))}/></div><div className="mt-4 text-xs text-[#777d84]">These are explicit planning assumptions, not inferred facts about your day.</div></Panel></>:null}

   {tab==='builder'?<><Panel title="Schedule Builder"><div className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div><div className="text-xl font-medium">Build around fixed commitments, then place flexible work.</div><div className="mt-4 space-y-2">{planItems.length?planItems.map((item,index)=><div key={`${item.time}-${item.title}-${index}`} className="flex items-center gap-3 rounded-[20px] bg-white/48 p-3"><div className="w-20 text-xs tabular-nums">{item.time}</div><div className="flex-1 text-sm">{item.title}</div><div className="text-[9px] uppercase tracking-[.15em]">{item.type}</div></div>):<div className="rounded-[20px] border border-dashed border-white p-5 text-sm text-[#777d84]">No recorded fixed or accepted planning blocks for tomorrow yet.</div>}</div></div><div className="rounded-[24px] bg-white/45 p-5"><Metric label="Plan confidence" value={confidence} sub={capacityPct>100?'Capacity estimate is overloaded':blockedTasks.length?'Some tasks have prerequisites':'Recorded commitments leave workable space'}/><div className="mt-4 space-y-2">{(['Minimal','Balanced','Spacious','Recovery-focused'] as BufferStyle[]).map(b=><button key={b} onClick={()=>setMemory(m=>({...m,buffer:b}))} className={`w-full rounded-2xl px-3 py-2 text-left text-xs ${memory.buffer===b?'bg-[#53636c] text-white':'bg-white/55'}`}>{b} buffers</button>)}</div></div></div><div className="mt-5 flex flex-wrap gap-2"><a href="#build-my-day" className="couture-primary">Open real Build My Day</a><button onClick={()=>ask('Make my proposed schedule lighter without moving fixed commitments. Preserve one important priority and more open space.')} className="couture-secondary">Make lighter</button><button onClick={()=>ask('Make my proposed schedule more productive without overloading it. Protect deep work and keep healthy buffers.')} className="couture-secondary">Make more productive</button></div></Panel><Panel title="Needs a home"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{openTasks.filter(t=>!t.dueDate).slice(0,12).map(t=><div key={t.id} className="rounded-[20px] bg-white/45 p-3"><div className="text-sm">{t.title}</div><button onClick={()=>ask(`Make this fit into my plan: ${t.title}. Find a realistic opening based on my calendar, energy, routines and buffers.`)} className="mt-2 text-[10px] underline">Make this fit</button></div>)}</div></Panel></>:null}

   {tab==='batches'?<Panel title="Task batches"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{batches.map(([name,items])=><div key={name} className="rounded-[24px] border border-white/70 bg-white/45 p-4"><div className="text-[10px] uppercase tracking-[.2em]">{name}</div><div className="mt-3 space-y-2">{items.slice(0,7).map(t=><div key={t.id} className="text-sm">{t.title}</div>)}</div><button onClick={()=>ask(`Batch these ${name} tasks into one realistic planning block: ${items.slice(0,7).map(t=>t.title).join('; ')}.`)} className="couture-secondary mt-4">Batch these</button></div>)}</div></Panel>:null}

   {tab==='routines'?<Panel title="Routine orchestration"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{routines.map(r=>{const steps=routineSteps.filter(s=>s.routineId===r.id);const mins=steps.reduce((sum,s)=>sum+(s.durationMinutes??0),0);return <Link key={r.id} href="/routines" className="rounded-[24px] border border-white/75 bg-white/45 p-4"><div className="text-[9px] uppercase tracking-[.18em]">{r.timeOfDay}</div><div className="mt-2 text-lg font-medium">{r.name}</div><div className="mt-2 text-xs text-[#777d84]">{steps.length} steps{mins?` · ${mins} min recorded`:''}</div></Link>})}</div><div className="mt-5 text-xs text-[#777d84]">Planning reserves the space. Routines remains the execution home for the actual routine steps.</div></Panel>:null}

   {tab==='scenarios'?<Panel title="Planning Scenarios"><div className="grid gap-4 md:grid-cols-3">{(['Productive','Balanced','Gentle'] as Scenario[]).map(s=><button key={s} onClick={()=>{setMemory(m=>({...m,scenario:s}));record(`Scenario changed to ${s}.`);}} className={`rounded-[26px] border p-5 text-left ${memory.scenario===s?'border-[#6e8793] bg-white/75':'border-white/70 bg-white/42'}`}><div className="glow-display text-2xl">{s}</div><div className="mt-3 text-sm text-[#707780]">{scenarioText[s]}</div></button>)}</div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>ask(`Rebuild tomorrow as a ${memory.scenario.toLowerCase()} scenario. ${scenarioText[memory.scenario]}`)} className="couture-primary">Preview this plan</button><button onClick={()=>ask('Compare a productive, balanced and gentle version of tomorrow. Compare focus time, recovery, transitions, open space and priority coverage without changing my calendar.')} className="couture-secondary">Compare plans</button><button onClick={()=>ask('Run a what-if planning conversation. Preview changes first and do not apply them until I approve.')} className="couture-secondary">What if…</button></div></Panel>:null}

   {tab==='reviews'?<><Panel title="Planning Review"><div className="text-xl font-medium">How did the plan feel?</div><div className="mt-4 flex flex-wrap gap-2">{['Too packed','About right','Too empty','Chaotic','Calm','Productive','Exhausting'].map(f=><button key={f} onClick={()=>{setMemory(m=>({...m,feelings:[...m.feelings,`${fmtDay(now)} · ${f}`].slice(-20)}));record(`Plan felt: ${f}.`);}} className="couture-secondary">{f}</button>)}</div></Panel><Panel title="Forecast vs reality"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Open tasks" value={`${openTasks.length}`}/><Metric label="Completed today" value={`${tasks.filter(t=>t.completedAt&&keyFor(new Date(t.completedAt))===todayKey).length}`}/><Metric label="Fixed events today" value={`${todayEvents.length}`}/></div><div className="mt-4 text-xs text-[#777d84]">Glow does not score you here. The review is for learning whether the plan was realistic or whether the day changed.</div></Panel></>:null}

   {tab==='memory'?<><Panel title="Planning Memory"><div className="space-y-2">{memory.notes.length?memory.notes.slice().reverse().map((n,i)=><div key={`${n}-${i}`} className="rounded-[20px] bg-white/45 p-3 text-sm">{n}</div>):<div className="text-sm text-[#777d84]">No planning decisions recorded in this studio yet.</div>}</div></Panel><Panel title="Saved planning layers"><div className="grid gap-3 md:grid-cols-2">{periods.slice(0,8).map(p=><Link href={`/planning?periodId=${p.id}#planning-${p.id}`} key={p.id} className="rounded-[22px] bg-white/45 p-4"><div className="text-[9px] uppercase tracking-[.18em]">{p.level} · {p.progress}%</div><div className="mt-2 text-base font-medium">{p.title}</div><div className="mt-1 text-xs text-[#777d84]">{p.focus||'No focus recorded.'}</div></Link>)}</div></Panel></>:null}

   {tab==='insights'?<Panel title="Planning Insights"><div className="grid gap-3 md:grid-cols-2"><Metric label="Blocked work" value={`${blockedTasks.length}`} sub={blockedTasks[0]?`${blockedTasks[0].task.title} waits on ${blockedTasks[0].blockedBy.join(', ')}`:'No active task dependencies are blocking open work.'}/><Metric label="Week fixed time" value={`${weekEvents.reduce((s,e)=>s+durationHours(new Date(e.startAt),e.endAt?new Date(e.endAt):null),0).toFixed(1)}h`} sub={`${weekEvents.length} recorded calendar events`}/><Metric label="Accepted planning blocks" value={`${acceptedBlocks.length}`}/><Metric label="Capture surface" value={`${notes.length} notes`} sub={notes[0]?`Most recent: ${notes[0].title}`:'No notes recorded.'}/></div><div className="mt-5 rounded-[22px] border border-white/70 bg-white/45 p-4 text-sm text-[#707780]">Personal planning-pattern claims are intentionally withheld until Glow has enough real history to support them. This page will not invent statements like “you work 2.3× better in the morning” without evidence.</div></Panel>:null}
  </div>
 </div>;
}

function Priority({title,items,empty}:{title:string;items:string[];empty:string}){return <div className="rounded-[24px] border border-white/75 bg-white/45 p-4"><div className="text-[10px] uppercase tracking-[.2em]">{title}</div><div className="mt-3 space-y-2">{items.length?items.map((x,i)=><div key={`${x}-${i}`} className="flex gap-2 text-sm"><ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0"/>{x}</div>):<div className="text-xs text-[#777d84]">{empty}</div>}</div></div>}
function Assumption({label,value,set}:{label:string;value:number;set:(value:number)=>void}){return <label className="rounded-[20px] bg-white/45 p-4"><div className="text-[9px] uppercase tracking-[.18em]">{label}</div><div className="mt-3 flex items-center gap-2"><Clock3 className="h-4 w-4"/><input type="number" min="0" max="24" step="0.25" value={value} onChange={e=>set(Number(e.target.value)||0)} className="w-full bg-transparent text-sm outline-none"/></div></label>}
