'use client';

import { useEffect, useState } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { X } from 'lucide-react';
import { Sidebar } from '@/components/ui/sidebar';
import { UniversalMobileNav } from '@/components/universal-mobile-nav';
import { Batch6Sidebar } from '@/components/batch6/batch6-sidebar';
import { Batch6TopControls } from '@/components/batch6/batch6-top-controls';
import { Batch9Sidebar } from '@/components/batch9/batch9-sidebar';
import { Batch10Sidebar } from '@/components/batch10/batch10-sidebar';
import { GlowCustomizationStudio } from '@/components/customization/glow-customization-studio';
import { GlowProvider } from '@/lib/context/glow-provider';
import { GlobalHeader } from '@/components/global-header';
import { DeferredGlobalControls } from '@/components/deferred-global-controls';
import { GlobalCommandSurface } from '@/components/global-command-surface';

function roomFor(pathname:string){
 if(pathname.startsWith('/system-overview'))return'system-overview';if(pathname.startsWith('/interview-mode'))return'interview-mode';if(pathname.startsWith('/workout-mode'))return'workout-mode';if(pathname.startsWith('/ambient-mode'))return'ambient-mode';if(pathname.startsWith('/focus'))return'focus-mode';if(pathname.startsWith('/beauty/lab'))return'beauty-lab';if(pathname.startsWith('/skincare')||pathname.startsWith('/makeup'))return'beauty';if(pathname.startsWith('/finance/brain'))return'financial-brain';if(pathname.startsWith('/calendar'))return'calendar';if(pathname.startsWith('/reminders'))return'reminders';if(pathname.startsWith('/alerts'))return'notices';if(pathname.startsWith('/tasks'))return'tasks';if(pathname.startsWith('/planning')||pathname.startsWith('/tomorrow')||pathname.startsWith('/day-mode'))return'planning';if(pathname.startsWith('/routines')||pathname.startsWith('/ritual'))return'routines';if(pathname.startsWith('/today')||pathname.startsWith('/dashboard'))return'dashboard';if(pathname.startsWith('/habits'))return'habits';if(pathname.startsWith('/fitness'))return'fitness';if(pathname.startsWith('/food'))return'food';if(pathname.startsWith('/beauty'))return'beauty';if(pathname.startsWith('/hair'))return'hair';if(pathname.startsWith('/wellness')||pathname.startsWith('/maintenance'))return'wellness';if(pathname.startsWith('/finance')||pathname.startsWith('/money'))return'finance';if(pathname.startsWith('/goals'))return'goals';if(pathname.startsWith('/creative-studio'))return'creative-studio';if(pathname.startsWith('/projects'))return'projects';if(pathname.startsWith('/brain/connections'))return'brain-connection';if(pathname.startsWith('/brain')||pathname.startsWith('/inbox')||pathname.startsWith('/rules')||pathname.startsWith('/knowledge'))return'brain';if(pathname.startsWith('/intake'))return'intake';if(pathname.startsWith('/concierge'))return'concierge';if(pathname.startsWith('/observations'))return'observations';if(pathname.startsWith('/memory'))return'memory';if(pathname.startsWith('/timeline'))return'timeline';if(pathname.startsWith('/briefings'))return'briefings';if(pathname.startsWith('/closet'))return'closet';if(pathname.startsWith('/travel'))return'travel';if(pathname.startsWith('/saint-space'))return'saint-space';if(pathname.startsWith('/world')||pathname.startsWith('/life-world'))return'world';if(pathname.startsWith('/home'))return'home';if(pathname.startsWith('/work'))return'work';if(pathname.startsWith('/graph'))return'graph';if(pathname.startsWith('/notices'))return'notices';if(pathname.startsWith('/all-rooms'))return'all-rooms';if(pathname.startsWith('/notes')||pathname.startsWith('/resources'))return'notes';if(pathname.startsWith('/connections'))return'connections';if(pathname.startsWith('/gmail'))return'gmail';if(pathname.startsWith('/import'))return'import';if(pathname.startsWith('/search'))return'search';if(pathname.startsWith('/settings'))return'settings';return'dashboard';
}
function isReferenceRoute(p:string){return p==='/dashboard'||p.startsWith('/dashboard/')||p==='/today'||p.startsWith('/today/')||p.startsWith('/briefings')||p.startsWith('/calendar')||p.startsWith('/timeline')||p.startsWith('/brain')||p.startsWith('/concierge')||p.startsWith('/memory')||p.startsWith('/observations')||p.startsWith('/graph')||p.startsWith('/notes')||p.startsWith('/wellness')||p.startsWith('/maintenance')||p.startsWith('/fitness')||p.startsWith('/food')||p.startsWith('/habits')||p.startsWith('/routines')||p.startsWith('/beauty')||p.startsWith('/hair')||p.startsWith('/finance')||p.startsWith('/goals')||p.startsWith('/projects')||p.startsWith('/creative-studio')||p==='/work'||p.startsWith('/work/')||p.startsWith('/home')||p.startsWith('/all-rooms')||p.startsWith('/world')||p.startsWith('/travel')||p.startsWith('/saint-space')||p.startsWith('/closet')||p.startsWith('/gmail')||p.startsWith('/import')||p.startsWith('/settings')||p.startsWith('/notices')||p.startsWith('/reminders')||p.startsWith('/search')||p.startsWith('/intake')||p.startsWith('/focus')||p.startsWith('/interview-mode')||p.startsWith('/workout-mode')||p.startsWith('/ambient-mode')||p.startsWith('/connections')||p.startsWith('/system-overview');}

export function AppShell({children}:{children:React.ReactNode}){
 const pathname=usePathname();const router=useRouter();const room=roomFor(pathname);const referenceRoute=isReferenceRoute(pathname);const isDashboard=pathname==='/dashboard'||pathname.startsWith('/dashboard/');const isImmersive=pathname==='/brain'||pathname==='/concierge';const isBatch6=pathname.startsWith('/projects')||pathname.startsWith('/creative-studio')||pathname==='/work'||pathname.startsWith('/work/');const isBatch7=pathname.startsWith('/home')||pathname.startsWith('/all-rooms')||pathname.startsWith('/world')||pathname.startsWith('/travel')||pathname.startsWith('/saint-space')||pathname.startsWith('/closet')||pathname.startsWith('/gmail')||pathname.startsWith('/import');const isBatch8=pathname.startsWith('/settings')||pathname.startsWith('/notices');const isBatch9=pathname.startsWith('/search')||pathname.startsWith('/intake')||pathname.startsWith('/focus')||pathname.startsWith('/interview-mode')||pathname.startsWith('/workout-mode')||pathname.startsWith('/ambient-mode')||pathname.startsWith('/connections')||pathname.startsWith('/system-overview');const isBatch10=pathname.startsWith('/reminders')||pathname.startsWith('/gmail')||pathname.startsWith('/import')||pathname.startsWith('/brain/connections')||pathname.startsWith('/all-rooms')||pathname.startsWith('/notices')||pathname.startsWith('/graph')||pathname.startsWith('/home');const compact=isBatch6||isBatch7||isBatch8||isBatch9||isBatch10;const[focus,setFocus]=useState(false);
 useEffect(()=>{const sync=()=>setFocus(new URLSearchParams(window.location.search).get('focus')==='1');sync();window.addEventListener('popstate',sync);document.addEventListener('glow:focus-changed',sync);return()=>{window.removeEventListener('popstate',sync);document.removeEventListener('glow:focus-changed',sync)}},[pathname]);
 function exitFocus(){const params=new URLSearchParams(window.location.search);params.delete('focus');router.replace(params.toString()?`${pathname}?${params.toString()}`:pathname);setFocus(false)}
 const content=<div key={pathname} className={(isDashboard||isImmersive)?'w-full min-w-0':referenceRoute?'glow-reference-route-stage mx-auto w-full min-w-0':'glow-v3-route-stage mx-auto w-full max-w-[1500px]'}>{children}</div>;
 if(referenceRoute&&!focus)return <GlowProvider><div className={`min-h-screen w-full overflow-x-clip text-[#25211f] ${(isDashboard||isImmersive)?'bg-[#eadbd8]':'bg-white'}`} data-room={room} data-glow-shell="v3" data-reference-shell="true" data-focus-mode="false"><div className={`flex min-h-screen w-full flex-col ${(isDashboard||isImmersive)?'bg-transparent':'bg-white xl:flex-row'}`}>{!(isDashboard||isImmersive)?<><div className={`sticky top-0 hidden h-screen shrink-0 overflow-y-auto overflow-x-hidden border-r border-[#ebe6e3] bg-white xl:block ${compact?'w-[202px]':'w-[238px]'}`}>{isBatch6?<Batch6Sidebar/>:isBatch9?<Batch9Sidebar/>:isBatch10?<Batch10Sidebar/>:<Sidebar variant="dashboard-reference"/>}</div><div className="w-full xl:hidden"><UniversalMobileNav/></div></>:null}<div className={`min-w-0 flex-1 ${(isDashboard||isImmersive)?'bg-transparent':'bg-white'}`}>{!(isDashboard||isImmersive)&&!compact?<GlobalHeader/>:null}<main className={`${compact?'relative ':''}${(isDashboard||isImmersive)?'min-w-0 w-full flex-1 overflow-x-clip bg-transparent p-0':'min-h-screen min-w-0 bg-white px-4 pb-20 pt-4 sm:px-5 md:px-6 lg:px-7 lg:pt-5'}`}>{compact&&!isImmersive?<Batch6TopControls/>:null}{content}</main></div></div><GlobalCommandSurface/>{!(isDashboard||isImmersive)?<DeferredGlobalControls/>:null}<GlowCustomizationStudio/></div></GlowProvider>;
 return <GlowProvider><div className="min-h-screen overflow-x-clip bg-white text-[#25211f]" data-room={room} data-glow-shell="v3" data-focus-mode={focus?'true':'false'}><div className="flex min-h-screen w-full flex-col bg-white xl:flex-row">{!focus?<><div className="w-full xl:hidden"><UniversalMobileNav/></div><div className="hidden xl:sticky xl:top-0 xl:block xl:h-screen xl:w-[238px] xl:shrink-0 xl:overflow-y-auto xl:overflow-x-hidden xl:border-r xl:border-[#ebe6e3] xl:bg-white"><Sidebar variant="dashboard-reference"/></div></>:null}<div className="min-w-0 flex-1 bg-white">{!focus?<GlobalHeader/>:null}<main className={focus?'min-h-screen px-4 py-8 sm:px-7 lg:px-10':'min-h-screen min-w-0 bg-white px-4 pb-24 pt-5 sm:px-6 md:px-7 lg:px-10 lg:pt-7'}>{content}</main></div></div></div>{focus?<button type="button" onClick={exitFocus} className="fixed right-5 top-5 z-[100] inline-flex h-10 items-center gap-2 rounded-full border border-[#E9E1DE] bg-white px-4 text-[13px] font-medium text-[#44403d] shadow-[0_8px_28px_rgba(53,38,31,.08)]"><X size={15}/>Exit Focus</button>:null}{!focus?<DeferredGlobalControls/>:null}{!focus?<GlobalCommandSurface/>:null}{!focus?<GlowCustomizationStudio/>:null}</GlowProvider>;
}
