'use client';

import { usePathname } from 'next/navigation';
import { ArrowRight, CalendarDays, Check, ChevronRight, Circle, Clock3, Droplets, Heart, Leaf, Mic2, MoreHorizontal, Plus, Search, Sparkles, Star } from 'lucide-react';
import { EditableRoomImage } from '@/components/media/editable-room-image';
import { blueprintForRoom, type ReferenceRoomBlueprint } from '@/lib/design/reference-room-blueprints';

function roomFor(pathname:string){
  if(pathname.startsWith('/beauty/lab')) return 'beauty-lab';
  if(pathname.startsWith('/finance/brain')) return 'financial-brain';
  if(pathname.startsWith('/tasks')) return 'tasks';
  if(pathname.startsWith('/calendar')) return 'calendar';
  if(pathname.startsWith('/planning')||pathname.startsWith('/tomorrow')) return 'planning';
  if(pathname.startsWith('/routines')) return 'routines';
  if(pathname.startsWith('/habits')) return 'habits';
  if(pathname.startsWith('/fitness')) return 'fitness';
  if(pathname.startsWith('/wellness')) return 'wellness';
  if(pathname.startsWith('/food')) return 'food';
  if(pathname.startsWith('/beauty')) return 'beauty';
  if(pathname.startsWith('/hair')) return 'hair';
  if(pathname.startsWith('/finance')) return 'finance';
  if(pathname.startsWith('/goals')) return 'goals';
  if(pathname.startsWith('/notes')||pathname.startsWith('/resources')) return 'notes';
  if(pathname.startsWith('/settings')) return 'settings';
  if(pathname.startsWith('/world')) return 'world';
  return 'dashboard';
}

function MiniDots({count=7}:{count?:number}){
  return <div className="flex items-center gap-1">{Array.from({length:count}).map((_,i)=><span key={i} className={`h-2 w-2 rounded-full border ${i<Math.ceil(count*.7)?'border-transparent bg-[var(--ref-accent)]':'border-[#d8cbc4] bg-transparent'}`}/>)}</div>;
}

function MetricStrip({spec}:{spec:ReferenceRoomBlueprint}){
  return <div className="ref-horizontal-rail grid auto-cols-[minmax(150px,1fr)] grid-flow-col gap-2 lg:grid-flow-row lg:grid-cols-4 xl:grid-cols-5">{spec.metrics.map(([label,value])=><div key={label} className="ref-card min-w-[150px] px-4 py-3"><p className="ref-kicker">{label}</p><p className="mt-1 glow-display text-[16px] text-[#342b27]">{value}</p></div>)}</div>;
}

function RightRail({spec}:{spec:ReferenceRoomBlueprint}){
  return <aside className="space-y-3 xl:sticky xl:top-4 xl:self-start">{spec.rail.map((item,i)=><section key={item} className="ref-card p-4"><div className="flex items-center justify-between gap-2"><p className="ref-kicker">{i===0?'Today':i===spec.rail.length-1?'Glow Intelligence':'Overview'}</p>{i===spec.rail.length-1?<Sparkles size={13} style={{color:spec.accent}}/>:<ChevronRight size={13} className="text-[#a9958e]"/>}</div><p className="mt-3 glow-display text-[15px] leading-5 text-[#3b302c]">{item}</p>{i===1?<div className="mt-3"><MiniDots/></div>:null}{i===spec.rail.length-1?<button type="button" data-glow-voice-open className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-[10px] px-3 py-2.5 text-[9px] font-semibold text-white" style={{background:spec.accent}}><Mic2 size={12}/>Ask Glow</button>:null}</section>)}</aside>;
}

function PhotoHero({room,spec}:{room:string;spec:ReferenceRoomBlueprint}){
  return <EditableRoomImage slot={`${room}:hero`} label={`${spec.title} hero image`} className="min-h-[285px] rounded-[16px] border border-white/60 shadow-[0_12px_34px_rgba(76,52,44,.08)]">
    <div className="flex h-full min-h-[285px] items-end bg-gradient-to-r from-[#fff9f4]/95 via-[#fff9f4]/68 to-transparent p-6 sm:p-8">
      <div className="max-w-[430px]"><p className="ref-kicker">Today in {spec.title}</p><h2 className="glow-display mt-2 text-[28px] leading-[1.05] text-[#322825] sm:text-[36px]">{spec.heroTitle}</h2><p className="mt-3 max-w-[390px] text-[10px] leading-5 text-[#6e5c55]">{spec.heroCopy}</p><button type="button" className="mt-5 inline-flex items-center gap-2 rounded-[10px] px-5 py-2.5 text-[9px] font-semibold text-white" style={{background:spec.accent}}>Open today’s flow<ArrowRight size={11}/></button></div>
    </div>
  </EditableRoomImage>;
}

function DeskLayout({room,spec}:{room:string;spec:ReferenceRoomBlueprint}){
  const columns=[['DO FIRST',...spec.primary.slice(0,4)],['DO TODAY',...spec.primary.slice(2,6)],['CAN WAIT','Organize Photos','Research Destinations','Update Budget','Plan Weekend Outfit']];
  return <div className="space-y-3"><section className="ref-desk-bg rounded-[18px] p-3 sm:p-5"><div className="ref-horizontal-rail grid auto-cols-[84%] grid-flow-col gap-4 md:auto-cols-[42%] xl:grid-flow-row xl:grid-cols-3">{columns.map(([title,...items],index)=><div key={title} className={`paper-note min-w-0 ${index===1?'notebook-edge':''}`}><p className="glow-display text-center text-[18px] tracking-wide">{title} <span style={{color:spec.accent}}>{index===0?'★':index===1?'☼':'☾'}</span></p><div className="mt-4 space-y-3">{items.map((item)=><div key={item} className="flex items-center gap-2 text-[10px]"><Circle size={13} className="shrink-0 text-[#b9a69e]"/><span className="flex-1">{item}</span></div>)}</div><button type="button" className="mt-5 inline-flex items-center gap-2 text-[9px] text-[#8f7770]"><Plus size={12}/>Add task</button></div>)}</div><div className="ref-horizontal-rail mt-4 grid auto-cols-[76%] grid-flow-col gap-3 md:auto-cols-[40%] xl:grid-flow-row xl:grid-cols-3">{spec.secondary.map((title)=><div key={title} className="paper-tray"><p className="glow-display text-center text-[15px]">{title}</p><div className="mt-3 space-y-2">{['Email from Brand','Project Inspiration','Client Feedback'].map(item=><div key={item} className="flex items-center gap-2 border-b border-[#eaded8] pb-2 text-[9px]"><Circle size={11}/>{item}</div>)}</div></div>)}</div></section></div>;
}

function CalendarLayout({spec}:{spec:ReferenceRoomBlueprint}){
  return <section className="ref-card overflow-hidden"><div className="flex items-center justify-between border-b border-[#eadfd9] px-4 py-3"><button type="button" className="rounded-lg border border-[#e5d8d1] px-3 py-2 text-[8px]">Today</button><h2 className="glow-display text-[18px]">{spec.heroTitle}</h2><button type="button" className="rounded-lg px-3 py-2 text-[8px] text-white" style={{background:spec.accent}}>+ Add Event</button></div><div className="overflow-x-auto"><div className="min-w-[980px]"><div className="grid grid-cols-[80px_repeat(7,1fr)] border-b border-[#eee3dd]"><div/><>{spec.secondary.map(day=><div key={day} className="border-l border-[#eee3dd] p-3 text-center text-[9px] font-semibold">{day}</div>)}</></div><div className="grid grid-cols-[80px_repeat(7,1fr)]">{['MORNING','AFTERNOON','EVENING','NIGHT'].map((part,pi)=><div key={part} className="contents"><div className="flex min-h-[150px] items-center justify-center border-b border-[#eee3dd] p-2 text-center text-[7px] font-semibold tracking-wider text-[#8c766e]">{part}</div>{spec.secondary.map((day,di)=><div key={`${day}-${part}`} className="min-h-[150px] space-y-1 border-b border-l border-[#eee3dd] p-1.5">{spec.primary.slice(pi*2,pi*2+3).map((event,ei)=><button type="button" key={`${event}-${di}-${ei}`} className="block w-full rounded-[7px] border border-white/60 px-2 py-2 text-left text-[7px] leading-3 shadow-sm" style={{background:[spec.soft,'#eee7f3','#eef1e7','#f2e7dc'][(pi+ei)%4]}}><b>{event}</b><br/><span className="text-[#8d7972]">{5+pi*4+ei}:00 – {6+pi*4+ei}:00</span></button>)}</div>)}</div>)}</div></div></div></section>;
}

function GardenLayout({room,spec}:{room:string;spec:ReferenceRoomBlueprint}){
  return <div className="space-y-3"><EditableRoomImage slot={`${room}:garden`} label="Habit garden image" className="min-h-[330px] rounded-[18px] border border-[#e5d8cf]"><div className="min-h-[330px] bg-[linear-gradient(90deg,rgba(255,250,246,.95),rgba(255,250,246,.25))] p-5 sm:p-7"><div className="max-w-[230px]"><h2 className="glow-display text-[26px]">{spec.heroTitle}</h2><p className="mt-2 text-[9px] leading-4 text-[#6f5f59]">{spec.heroCopy}</p></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{spec.primary.slice(0,8).map((habit,i)=><button type="button" key={habit} className="group rounded-[999px_999px_18px_18px] border border-white/80 bg-[#fffaf6]/82 px-3 pb-4 pt-6 text-center shadow-[0_10px_24px_rgba(70,55,45,.08)]"><Leaf size={24} className="mx-auto transition group-hover:-translate-y-1" style={{color:i%2? '#8f9f72':spec.accent}}/><p className="mt-2 text-[8px] font-medium">{habit}</p></button>)}</div></div></EditableRoomImage><MetricStrip spec={spec}/></div>;
}

function RitualLayout({room,spec}:{room:string;spec:ReferenceRoomBlueprint}){
  return <div className="space-y-3"><div className="ref-horizontal-rail grid auto-cols-[75%] grid-flow-col gap-3 sm:auto-cols-[38%] xl:grid-flow-row xl:grid-cols-5">{spec.secondary.map((ritual,i)=><EditableRoomImage key={ritual} slot={`${room}:ritual:${i}`} label={ritual} className="min-h-[155px] rounded-[14px] border border-[#eadcd5]"><div className="flex min-h-[155px] flex-col justify-end bg-gradient-to-t from-[#fff9f5]/95 via-[#fff9f5]/35 to-transparent p-3"><p className="glow-display text-[15px]">{ritual}</p><p className="mt-1 text-[8px] text-[#806d66]">{i===0?'5:00 – 9:30 AM':'Tap to open ritual'}</p></div></EditableRoomImage>)}</div><section className="ref-card overflow-hidden"><div className="grid lg:grid-cols-[260px_1fr]"><div className="border-b border-[#eaded8] p-4 lg:border-b-0 lg:border-r"><h3 className="glow-display text-[22px]">{spec.heroTitle}</h3><p className="mt-1 text-[9px] text-[#7e6962]">start your day with intention</p><div className="mt-4 space-y-2">{spec.primary.map((step,i)=><button type="button" key={step} className="flex w-full items-center gap-2 text-left text-[8px]"><span className={`flex h-4 w-4 items-center justify-center rounded-full border ${i<2?'border-transparent text-white':'border-[#d8c8c2]'}`} style={i<2?{background:spec.accent}:{}}>{i<2?<Check size={9}/>:null}</span><span className="flex-1">{step}</span><span className="text-[#9a8580]">{i===2?'20–30 min':'5 min'}</span></button>)}</div></div><div className="p-4 sm:p-6"><p className="ref-kicker">Step 3 of 11</p><h3 className="glow-display mt-2 text-[25px]">Movement</h3><p className="mt-2 text-[9px] leading-4 text-[#6f5d57]">Move your body to increase energy, improve mood and support physical and mental health.</p><div className="ref-horizontal-rail mt-5 grid auto-cols-[68%] grid-flow-col gap-3 sm:auto-cols-[38%] xl:grid-flow-row xl:grid-cols-4">{['Workout','Pilates','Yoga','Walk'].map((item,i)=><EditableRoomImage key={item} slot={`${room}:movement:${i}`} label={item} className="min-h-[125px] rounded-[12px]"><div className="flex min-h-[125px] items-end bg-gradient-to-t from-[#fff9f5]/95 to-transparent p-3"><div><p className="font-medium text-[9px]">{item}</p><p className="text-[7px] text-[#8b756e]">Choose movement</p></div></div></EditableRoomImage>)}</div></div></div></section></div>;
}

function GalleryLayout({room,spec}:{room:string;spec:ReferenceRoomBlueprint}){
  const isMoney=spec.layout==='money'||spec.layout==='money-brain';
  return <div className="space-y-3">{!isMoney?<PhotoHero room={room} spec={spec}/>:null}<div className={`grid gap-3 ${isMoney?'md:grid-cols-2 xl:grid-cols-3':'md:grid-cols-2'}`}>{spec.primary.map((title,i)=><section key={title} className={`ref-card min-h-[145px] p-4 ${i===0&&!isMoney?'md:col-span-1':''}`}><div className="flex items-center justify-between"><p className="ref-kicker">{title}</p><span className="text-[8px] text-[#9b8179]">View all →</span></div>{isMoney?<><p className="mt-4 glow-display text-[25px]">{i%3===0?'$78,540':i%3===1?'$2,693.42':'68%'}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#eee5df]"><div className="h-full rounded-full" style={{width:`${48+(i*7)%46}%`,background:spec.accent}}/></div><div className="mt-4 flex h-12 items-end gap-1">{[30,45,38,62,51,74,65,88].map((h,j)=><span key={j} className="flex-1 rounded-t-sm bg-[var(--ref-accent)]/45" style={{height:`${h}%`}}/>)}</div></>:<div className="mt-4 space-y-3">{(i===0?spec.secondary:spec.primary).slice(0,5).map((item,j)=><div key={`${item}-${j}`} className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[var(--ref-soft)]"><Star size={11} style={{color:spec.accent}}/></span><p className="min-w-0 flex-1 truncate text-[9px]">{item}</p><div className="h-1.5 w-20 overflow-hidden rounded-full bg-[#eee4df]"><div className="h-full rounded-full" style={{width:`${45+j*10}%`,background:spec.accent}}/></div></div>)}</div>}</section>)}</div></div>;
}

function NotesLayout({room,spec}:{room:string;spec:ReferenceRoomBlueprint}){
  return <div className="grid gap-3 lg:grid-cols-[250px_1fr]"><div className="space-y-3"><section className="ref-card p-4"><p className="ref-kicker">Recent Notes</p><div className="mt-3 space-y-3">{spec.primary.slice(0,6).map((item,i)=><button type="button" key={item} className="flex w-full items-center gap-3 text-left"><EditableRoomImage slot={`${room}:note-thumb:${i}`} label={`${item} image`} className="h-9 w-12 shrink-0 rounded-[6px]"/><span className="text-[9px]">{item}</span></button>)}</div></section><section className="ref-card p-4"><p className="ref-kicker">Notebooks</p><div className="mt-3 space-y-2">{spec.primary.slice(4).map(item=><div key={item} className="flex items-center justify-between text-[9px]"><span>{item}</span><span className="text-[#9a8780]">12 notes</span></div>)}</div></section></div><section className="ref-card overflow-hidden"><div className="border-b border-[#eadfd9] p-4"><p className="glow-display text-[21px]">{spec.heroTitle}</p><div className="mt-2 flex gap-4 text-[10px]"><b>B</b><i>I</i><u>U</u><span>☷</span><span>“”</span></div></div><div className="grid md:grid-cols-[1fr_260px]"><div className="p-5"><p className="glow-display text-[17px]">Good morning, Tatiyana. ☼</p><p className="mt-3 text-[9px] leading-5 text-[#63534e]">Today is a new chance to show up for yourself and your dreams.<br/>Focus on progress, not perfection.</p><p className="mt-4 text-[9px] font-semibold">Top 3 Intentions for Today:</p><ul className="mt-2 list-disc pl-4 text-[9px] leading-5"><li>Move my body</li><li>Work on my brand</li><li>Be present & grateful</li></ul><p className="glow-hand mt-5 text-[20px]" style={{color:spec.accent}}>Discipline today, freedom tomorrow.</p></div><EditableRoomImage slot={`${room}:editor`} label="Note editor image" className="min-h-[280px]"/></div></section></div>;
}

function SettingsLayout({spec}:{spec:ReferenceRoomBlueprint}){
  return <div className="grid gap-3 md:grid-cols-[.9fr_1.35fr]"><section className="ref-card p-5"><p className="ref-kicker">My Account</p><div className="mt-4 flex items-center gap-3"><div className="h-14 w-14 rounded-full bg-[var(--ref-soft)]"/><div><p className="glow-display text-[18px]">Tatiyana Curran</p><p className="text-[8px] text-[#806f68]">Modern American Princess</p></div></div><div className="mt-5 space-y-3 text-[9px]">{['Display Name · Tatiyana Curran','Username · princess.glow','Birthday · August 10','Location · Boston, Massachusetts','Time Zone · Eastern Time'].map(item=><div key={item} className="border-b border-[#ebdfd9] pb-2">{item}</div>)}</div><button type="button" className="mt-5 w-full rounded-[10px] py-2.5 text-[9px] text-white" style={{background:spec.accent}}>Save Changes</button></section><section className="ref-card divide-y divide-[#eadfd9]">{spec.primary.map((item,i)=><button type="button" key={item} className="flex w-full items-center gap-4 p-5 text-left"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--ref-soft)]"><Sparkles size={14} style={{color:spec.accent}}/></span><span className="flex-1"><b className="block text-[9px] uppercase tracking-wide">{item}</b><span className="mt-1 block text-[9px] text-[#7f6d66]">Customize your {item.toLowerCase()} settings</span></span><ChevronRight size={14}/></button>)}</section></div>;
}

function WorldLayout({room,spec}:{room:string;spec:ReferenceRoomBlueprint}){
  return <div className="space-y-3"><section className="overflow-hidden rounded-[20px] border border-[#d8cad9] bg-[linear-gradient(160deg,#342b50,#755478_45%,#d5878e)] text-white shadow-[0_18px_50px_rgba(53,35,69,.2)]"><div className="p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="glow-display text-[29px]">{spec.heroTitle} ✨</p><p className="mt-1 text-[10px] text-white/75">{spec.heroCopy}</p></div><div className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-[9px] backdrop-blur">Search anything in your world…</div></div><div className="ref-horizontal-rail mt-8 grid auto-cols-[72%] grid-flow-col gap-3 sm:auto-cols-[34%] xl:grid-flow-row xl:grid-cols-4">{spec.primary.map((world,i)=><EditableRoomImage key={world} slot={`${room}:world:${i}`} label={world} className="min-h-[245px] rounded-[100px_100px_16px_16px] border border-white/20"><div className="flex min-h-[245px] flex-col items-center justify-end bg-gradient-to-t from-[#1d1629]/80 via-transparent to-white/5 p-4 text-center text-white"><Sparkles size={22}/><p className="mt-2 glow-display text-[15px]">{world}</p><p className="mt-1 text-[8px] text-white/70">Enter room</p></div></EditableRoomImage>)}</div></div></section><div className="ref-horizontal-rail grid auto-cols-[82%] grid-flow-col gap-3 md:auto-cols-[45%] xl:grid-flow-row xl:grid-cols-3">{spec.secondary.map((item,i)=><section key={item} className="ref-card min-h-[150px] p-4"><p className="ref-kicker">{item}</p>{i===0?<div className="mt-4 h-20 rounded-[12px] bg-[radial-gradient(circle_at_30%_50%,rgba(189,119,139,.35),transparent_10%),linear-gradient(140deg,#efe2eb,#d6c5df)]"/>:<p className="glow-display mt-5 text-[20px] leading-6">{i===2?'Building My Dream Life ♡':i===3?'Focus on progress, not perfection.':'Your world keeps becoming more you.'}</p>}</section>)}</div></div>;
}

function MainWorkspace({room,spec}:{room:string;spec:ReferenceRoomBlueprint}){
  if(spec.layout==='desk') return <DeskLayout room={room} spec={spec}/>;
  if(spec.layout==='calendar') return <CalendarLayout spec={spec}/>;
  if(spec.layout==='garden') return <GardenLayout room={room} spec={spec}/>;
  if(spec.layout==='ritual') return <RitualLayout room={room} spec={spec}/>;
  if(spec.layout==='notes') return <NotesLayout room={room} spec={spec}/>;
  if(spec.layout==='settings') return <SettingsLayout spec={spec}/>;
  if(spec.layout==='world') return <WorldLayout room={room} spec={spec}/>;
  if(['money','money-brain'].includes(spec.layout)) return <GalleryLayout room={room} spec={spec}/>;
  return <GalleryLayout room={room} spec={spec}/>;
}

export function ReferenceRoomWorkspace(){
  const pathname=usePathname();
  const room=roomFor(pathname);
  const spec=blueprintForRoom(room);
  return <section className="reference-room mb-6" style={{'--ref-accent':spec.accent,'--ref-soft':spec.soft} as React.CSSProperties} data-reference-layout={spec.layout}>
    <header className="mb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="glow-display text-[31px] leading-none tracking-[-.03em] text-[#2e2522] sm:text-[38px]">{spec.title}</h1><p className="glow-hand mt-1 text-[24px] leading-none" style={{color:spec.accent}}>{spec.script}</p></div><div className="flex items-center gap-2"><button type="button" className="ref-icon-btn" aria-label="Search"><Search size={15}/></button><button type="button" className="ref-icon-btn" aria-label="More options"><MoreHorizontal size={16}/></button><button type="button" data-glow-voice-open className="ref-icon-btn text-white" style={{background:spec.accent}} aria-label="Speak to Glow"><Mic2 size={15}/></button></div></div><nav className="ref-horizontal-rail mt-4 flex gap-1 border-b border-[#e8dcd6]">{spec.tabs.map((tab,i)=><button type="button" key={tab} className={`shrink-0 border-b-2 px-3 py-2 text-[9px] ${i===0?'border-[var(--ref-accent)] text-[var(--ref-accent)]':'border-transparent text-[#67564f]'}`}>{tab}</button>)}</nav></header>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_255px]"><div className="min-w-0 space-y-3"><MainWorkspace room={room} spec={spec}/>{!['desk','calendar','garden','ritual','world'].includes(spec.layout)?<MetricStrip spec={spec}/>:null}{spec.layout==='board'?<div className="ref-horizontal-rail grid auto-cols-[62%] grid-flow-col gap-2 sm:auto-cols-[34%] xl:grid-flow-row xl:grid-cols-7">{spec.secondary.map(day=><div key={day} className="ref-card min-h-[110px] p-3"><p className="text-[8px] font-semibold">{day}</p><MiniDots count={5}/><p className="mt-3 text-[8px] text-[#8e7770]">Plan complete</p></div>)}</div>:null}</div><RightRail spec={spec}/></div>
    <div className="mt-4 flex flex-col gap-3 rounded-[14px] border border-[#eaded7] bg-[linear-gradient(90deg,var(--ref-soft),#fffaf6)] px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><Sparkles size={15} style={{color:spec.accent}}/><div><p className="text-[8px] font-bold uppercase tracking-[.16em]">Glow Intelligence</p><p className="mt-1 text-[9px] text-[#6f5d57]">This room understands its context, connects to the rest of Glow OS, and can turn an insight into an action.</p></div></div><button type="button" data-glow-voice-open className="inline-flex shrink-0 items-center justify-center gap-2 rounded-[10px] px-4 py-2.5 text-[9px] font-semibold text-white" style={{background:spec.accent}}><Mic2 size={12}/>Speak a command</button></div>
  </section>;
}
