'use client';

import { usePathname } from 'next/navigation';
import { Bell, Check, ChevronLeft, ChevronRight, Circle, Plus, Search } from 'lucide-react';
import { EditableRoomImage } from '@/components/media/editable-room-image';

const A='#BE5D72';
const G='#71896B';

function roomFor(pathname:string){
  if(pathname.startsWith('/beauty/lab')) return 'beauty-lab';
  if(pathname.startsWith('/finance/brain')) return 'financial-brain';
  if(pathname.startsWith('/tasks')) return 'tasks';
  if(pathname.startsWith('/calendar')) return 'calendar';
  if(pathname.startsWith('/planning')) return 'planning';
  if(pathname.startsWith('/routines')) return 'routines';
  if(pathname.startsWith('/habits')) return 'habits';
  if(pathname.startsWith('/food')) return 'food';
  if(pathname.startsWith('/wellness')) return 'wellness';
  if(pathname.startsWith('/beauty')) return 'beauty';
  if(pathname.startsWith('/hair')) return 'hair';
  if(pathname.startsWith('/finance')) return 'finance';
  if(pathname.startsWith('/goals')) return 'goals';
  if(pathname.startsWith('/projects')) return 'projects';
  if(pathname.startsWith('/notes')) return 'notes';
  if(pathname.startsWith('/settings')) return 'settings';
  if(pathname.startsWith('/inbox')) return 'inbox';
  if(pathname.startsWith('/briefings')) return 'briefings';
  if(pathname.startsWith('/world')) return 'world';
  if(pathname.startsWith('/brain')||pathname.startsWith('/concierge')||pathname.startsWith('/observations')||pathname.startsWith('/memory')||pathname.startsWith('/timeline')) return 'glow';
  return 'dashboard';
}

const view=(s:string)=>`view:${s.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;

function Img({slot,label,className='',children}:{slot:string;label:string;className?:string;children?:React.ReactNode}){
  return <EditableRoomImage slot={slot} label={label} className={`board-img ${className}`}>{children}</EditableRoomImage>;
}

function Top({kicker,title,tabs=[]}:{kicker:string;title:string;tabs?:string[]}){
  return <header className="board-top"><div><p className="board-kicker">{kicker}</p><h1>{title}</h1></div>{tabs.length?<nav className="board-tabs">{tabs.map((t,i)=><button key={t} type="button" data-ref-action={view(t)} className={i===0?'active':''}>{t}</button>)}</nav>:null}</header>;
}
function Card({title,children,className=''}:{title?:string;children:React.ReactNode;className?:string}){
  return <section className={`board-card ${className}`}>{title?<p className="board-label">{title}</p>:null}{children}</section>;
}
function Dot({on=false}:{on?:boolean}){return <span className={`dot ${on?'on':''}`}/>;}
function Btn({children,action='vault',outline=false}:{children:React.ReactNode;action?:string;outline?:boolean}){return <button type="button" data-ref-action={action} className={outline?'board-btn outline':'board-btn'}>{children}</button>}

function Dashboard(){
  return <div className="board-page dashboard-page"><div className="dashboard-greeting"><h1>Good morning, <em>Tatiyana</em></h1><p>Here&apos;s what matters today.</p></div><div className="section-heading"><b>TODAY AT A GLANCE</b><button data-ref-action="vault">See all</button></div><div className="dash-glance">
    <Card><p className="mini">Top Priority</p><h3>Finish Glow OS<br/>brand deck</h3><span className="danger">● High</span></Card>
    <Card><p className="mini">Next Appointment</p><h3>Hair Appointment</h3><span>2:30 PM – 3:30 PM</span></Card>
    <Card><p className="mini">Today&apos;s Routine</p><h3>Morning Glow Ritual</h3><span className="green">🌿 8 steps</span></Card>
    <Card><p className="mini">Important Alert</p><h3>Bill due tomorrow</h3><span>▲ Chase Sapphire</span></Card>
  </div><div className="dash-middle">
    <Card title="MORNING BRIEF"><blockquote>You&apos;re in a powerful<br/>building season.</blockquote><p>Focus on deep work, nourish your body, and protect your energy. You&apos;ve got this.</p><Btn action="navigate:/briefings">View Full Brief</Btn></Card>
    <Card title="TODAY'S SCHEDULE"><ul className="time-list"><li><span>9:00 AM</span>Deep Work Session</li><li><span>11:30 AM</span>Team Check-In</li><li><span>2:30 PM</span><b>● Hair Appointment</b></li><li><span>4:00 PM</span>Content Planning</li></ul></Card>
    <Card title="TOP TASKS"><ul className="check-lines"><li><Circle/>Finish Glow OS brand deck</li><li><Circle/>Review campaign strategy</li><li><Check className="filled"/>Workout – Glute Focus</li><li><Circle/>Reply to client email</li></ul><button className="link" data-ref-action="navigate:/tasks">View all tasks</button></Card>
  </div><div className="dash-strip"><div><small>WELLNESS</small><b>Energy</b><span>High</span></div><div><small>STEPS</small><b>6,842</b></div><div className="ring-cell"><small>HYDRATION</small><div className="small-ring">6 / 8<em>glasses</em></div></div><div><small>NUTRITION</small><b>1,350</b><span>cal / 2,000</span><i className="mini-progress"/></div><div><small>SLEEP</small><b>7h 32m</b><span>Good</span></div><Img slot="dashboard:quote" label="Dashboard botanical quote"><div className="photo-quote">Discipline today,<br/>freedom tomorrow.</div></Img></div></div>;
}

function Tasks(){return <div className="board-page"><Top kicker="PLAN" title="Tasks" tabs={['Do First','Do Today','Can Wait','Inbox','Waiting On','Someday']}/><div className="tasks-board"><div className="task-column">{[['Finish Glow OS brand deck','High Priority'],['Review campaign strategy','Due 10:00 AM'],['Send proposal to client','Due 12:00 PM']].map(([t,s])=><button key={t} data-ref-action="vault" className="task-item"><Circle/><span><b>{t}</b><small>{s}</small></span></button>)}<button className="add-row" data-ref-action="quick:task"><Plus/>Add new task</button></div><aside className="task-side"><Card title="FOCUS MODE"><p>See less. Do more.</p><Btn action="voice">Enter Focus Mode</Btn></Card><Card title="TASKS COMPLETED"><div className="big-ring"><b>8</b><small>of 14</small></div><strong className="pct">57%</strong><button className="link">View analytics</button></Card></aside></div></div>}

function Calendar(){
  const days=['MON\n12','TUE\n13','WED\n14','THU\n15','FRI\n16','SAT\n17','SUN\n18'];
  const ev=[['Deep Work',0,1,2],['Team\nCheck-In',1,2,1],['Hair\nAppointment',2,8,2],['Content Day',3,1,4],['Photoshoot',5,7,3],['Pilates',6,2,1]] as const;
  return <div className="board-page"><Top kicker="PLAN" title="Calendar"/><div className="cal-toolbar"><Btn outline action="view:today">Today</Btn><button><ChevronLeft/></button><button><ChevronRight/></button><b>May 12 – 18, 2025⌄</b><div className="seg"><button>Day</button><button className="active">Week</button><button>Month</button></div></div><div className="cal-wrap"><div className="cal-main"><div className="cal-days">{days.map(d=><span key={d}>{d.split('\n').map((x,i)=><i key={x} className={i?'date':''}>{x}</i>)}</span>)}</div><div className="cal-grid">{Array.from({length:70}).map((_,i)=><span key={i}/>) }{ev.map(([name,col,row,h])=><button key={name} data-ref-action="vault" className="cal-event" style={{gridColumn:col+1,gridRow:`${row} / span ${h}`}}>{name.split('\n').map(x=><i key={x}>{x}</i>)}</button>)}</div></div><aside className="cal-side"><Card title="MAY 2025"><div className="mini-month">{['S','M','T','W','T','F','S',...Array.from({length:31},(_,i)=>String(i+1))].map((x,i)=><span key={i} className={x==='14'?'today':''}>{x}</span>)}</div></Card><Card title="UP NEXT"><p><b>Hair Appointment</b><small>Today 2:30 PM</small></p><p><b>Client Call</b><small>Fri, May 16 11:00 AM</small></p><Btn outline action="quick:event"><Plus/> New Event</Btn></Card></aside></div></div>;
}

function Planning(){return <div className="board-page with-left-nav"><Top kicker="" title="Planning" tabs={['Overview','Lists','Meals','Projects','Shopping','Ideas','Notes']}/><div className="planning-board"><Card title="TOP THREE"><ol className="numbered"><li>Launch Glow OS<br/>brand deck</li><li>Hair appointment</li><li>Deep work on<br/>Terrain Design</li></ol><button className="link">Edit Top Three</button></Card><Card title="THIS WEEK"><ul className="tiny-list"><li>Brand deck due <small>May 14</small></li><li>Client call <small>May 16</small></li><li>Photo shoot <small>May 17</small></li></ul><button className="add-row"><Plus/>Add item</button></Card><Card title="APPOINTMENTS"><ul className="appointments"><li><b>Hair Appointment</b><small>May 14 · 2:30 PM</small></li><li><b>Team Call</b><small>May 16 · 11:00 AM</small></li><li><b>Pilates Class</b><small>May 17 · 10:00 AM</small></li></ul><button className="link">View calendar</button></Card><Card title="DEADLINES"><p className="deadline">Glow OS brand deck <small>May 14</small></p><p className="deadline">Terrain Design review <small>May 16</small></p></Card><Card title="SUNDAY RESET"><ul className="check-lines"><li><Circle/>Plan next week</li><li><Circle/>Review goals</li><li><Circle/>Prep meals</li></ul><button className="link">Start Reset</button></Card><Img slot="planning:quote" label="Planning quote"><div className="center-quote">A well planned week<br/>creates a calm mind<br/>and a beautiful life.</div></Img></div></div>}

function Routines(){const steps=['Hydrate','Movement','Skincare','Meditate','Journal','Plan Day','Affirm'];return <div className="board-page"><Top kicker="" title="Routines" tabs={['My Routines','Templates','History']}/><Img slot="routines:hero" label="Morning Glow Ritual" className="routine-banner"><div className="routine-copy"><h2>Morning Glow Ritual</h2><p>45 min · 7 steps</p><p>A complete morning ritual to energize your body, focus your mind, and set the tone.</p><Btn>Continue Ritual</Btn></div></Img><p className="board-label steps-label">STEPS</p><div className="step-strip">{steps.map((x,i)=><button key={x}><span>{i<2?<Check/>:<Circle/>}</span><b>{x}</b><small>{i===2?'10 min':'5 min'}</small></button>)}</div><p className="board-label steps-label">OTHER ROUTINES</p><div className="routine-cards">{['Evening Wind Down','Weekly Reset Ritual','Self Care Sunday'].map((x,i)=><Img key={x} slot={`routine:${i}`} label={x}><div className="img-caption"><b>{x}</b><small>{30+i*15} min</small></div></Img>)}</div></div>}

function Habits(){const habits=[['Drink 8 glasses of water',8,'9 day streak'],['Move my body',6,'6 day streak'],['Skincare morning',7,'12 day streak'],['Read 20 pages',5,'3 day streak'],['No phone first hour',4,'5 day streak']];return <div className="board-page"><Top kicker="" title="Habits Garden" tabs={['Garden','Habits','History','Insights']}/><div className="habit-hero"><Img slot="habits:garden" label="Habit flower garden" className="garden-img"/><aside><p className="board-label">GARDEN STATS</p><b>7</b><small>Active Habits</small><b>23</b><small>Total Streaks</small><b>8</b><small>Longest Streak (days)</small><p className="garden-strong">Strongest Streak<br/>Hydration · 9 days 🌿</p></aside></div><p className="board-label steps-label">TODAY'S HABITS</p><div className="habit-list">{habits.map(([h,n,s])=><div key={h}><span><Circle/>{h}</span><div className="dots">{Array.from({length:10}).map((_,i)=><Dot key={i} on={i<Number(n)}/>)}</div><small>{s}</small></div>)}</div></div>}

function Wellness(){const moods=['Amazing','Good','Okay','Low','Struggling'];return <div className="board-page"><Top kicker="HEALTH & CARE" title="Wellness"/><div className="wellness-grid"><section><h3>How are you feeling today?</h3><div className="moods">{moods.map((m,i)=><button className={i===1?'selected':''} key={m}><span>{['☺','☺','◡','◠','☹'][i]}</span>{m}</button>)}</div><p className="board-label steps-label">Recommended for you</p><div className="recommend">{[['Move','20 min Pilates'],['Breathe','5 min Meditation'],['Nourish','High-protein lunch'],['Reflect','Journal prompt']].map(([a,b])=><Card key={a}><b>{a}</b><small>{b}</small></Card>)}</div></section><Img slot="wellness:quote" label="Wellness botanical quote"><div className="photo-quote bottom">Small daily choices<br/>create big life shifts.</div></Img></div></div>}

function Food(){return <div className="board-page"><Top kicker="FOOD & NUTRITION" title="Food & Nutrition" tabs={['Today','Meal Plan','Groceries','Pantry','Recipes','Nutrition']}/><p className="board-label steps-label">TODAY'S MEALS</p><div className="meal-grid">{[['Breakfast','Greek yogurt bowl','8:00 AM'],['Lunch','Salmon quinoa bowl','12:30 PM'],['Dinner','Lemon pasta','6:20 PM']].map(([type,name,time],i)=><Card key={type}><b>{type}</b><Img slot={`food:${i}`} label={name}/><strong>{name}</strong><small>{time}</small><button className="add-row"><Plus/>Add Meal</button></Card>)}</div><div className="food-bottom"><Card title="WEEKLY PREVIEW"><div className="week-preview">{['M','T','W','T','F','S','S'].map((d,i)=><span key={i}><b>{d}</b><i>🍽️</i></span>)}</div></Card><Card title="GROCERY LIST"><ul className="grocery">{['Avocados','Salmon','Spinach','Blueberries','Quinoa'].map(x=><li key={x}><Circle/>{x}</li>)}</ul><button className="link">View all</button></Card></div></div>}

function Beauty(){return <div className="board-page"><Top kicker="BEAUTY" title="Beauty OS"/><p className="board-label steps-label">Today&apos;s Beauty</p><div className="beauty-top"><Card><small>AM</small><b>Hydrate & Protect</b><span>3 steps</span></Card><Card><small>Tonight</small><b>Treat & Repair</b><span>4 steps</span></Card><Card><small>Next Treatment</small><b>Hydrafacial</b><span>May 20</span></Card><Img slot="beauty:products" label="Beauty products"/></div><div className="beauty-body"><section><p className="board-label">Your Routine</p><div className="beauty-steps">{['Cleanse','Tone','Treat','Moisturize','SPF'].map((x,i)=><button key={x}><span>{i+1}</span><b>{x}</b></button>)}</div><div className="beauty-calendar"><span>Beauty Calendar</span><b>May 2025</b><button>+ Week ‹ ›</button></div></section><Img slot="beauty:quote" label="Beauty quote"><div className="center-quote bottom-left">You glow<br/>differently<br/>when you&apos;re<br/>aligned.</div></Img></div></div>}

function BeautyLab(){const products=['La Mer','The Ordinary','Kérastase','Tatcha'];return <div className="board-page"><Top kicker="" title="Beauty Lab" tabs={['Products','Ingredients','Compatibility','Experiments','Reactions','Repurchase']}/><div className="lab-layout"><section><p className="board-label">MY SHELVES</p><div className="product-shelf">{products.map((x,i)=><Card key={x}><Img slot={`lab:${i}`} label={x}/><b>{x}</b><small>{['Moisturizing Cream','Niacinamide 10%','Elixir Ultime Oil','The Essence'][i]}</small><em>✦ Skincare</em></Card>)}<button className="add-product"><Plus/>Add Product</button></div></section><aside><p className="board-label">PRODUCT SPOTLIGHT</p><Img slot="lab:spotlight" label="Product spotlight"/><h3>The Ordinary</h3><b>Niacinamide 10% + Zinc 1%</b><div className="chips"><span>Hydrating</span><span>Pore Care</span></div><p className="green">● 94 match score</p><small>Last used 2 days ago</small><button className="link">View Details</button></aside></div></div>}

function Hair(){return <div className="board-page"><Top kicker="HAIR" title="Hair Studio"/><div className="hair-layout"><section><p className="board-label steps-label">Your Hair Right Now</p><div className="hair-stats">{[['Current Phase','Growth'],['Next Wash','Thursday'],['Current Style','Silk Press'],['Next Treatment','Deep Conditioning\nMay 18']].map(([a,b])=><Card key={a}><small>{a}</small><b>{b}</b></Card>)}</div><p className="board-label steps-label">Hair Lifecycle</p><div className="lifecycle">{['Rest','Wash','Treat','Style','Refresh'].map((x,i)=><button className={i===2?'active':''} key={x}>{x}</button>)}</div><p className="board-label steps-label">Today&apos;s Plan</p><Card className="hair-plan"><span>🧴</span><b>Deep Conditioning Treatment</b><Btn>View Plan</Btn></Card></section><Img slot="hair:hero" label="Healthy glossy hair"><div className="hair-quote">Healthy hair<br/>is a reflection<br/>of consistent<br/>care.</div></Img></div></div>}

function Finance(){return <div className="board-page"><Top kicker="FINANCE" title="Finance"/><p className="board-label">This Month <span>May 1 – May 31</span></p><div className="finance-metrics">{[['Income','$8,450'],['Spent','$3,245'],['Saved','$2,890'],['Available','$2,315']].map(([a,b])=><Card key={a}><small>{a}</small><b>{b}</b></Card>)}</div><div className="finance-bottom"><Card title="TRANSACTIONS"><ul className="transactions"><li>Morning Matcha <small>May 16</small><b>– $6.50</b></li><li>Grocery Store <small>May 14</small><b>– $84.21</b></li><li>Client Payment <small>May 13</small><b className="green">+ $1,200.00</b></li></ul></Card><Card title="SPENDING BREAKDOWN"><div className="spend"><div className="donut"><b>$3,245</b><small>Total</small></div><ul><li>Living <b>40%</b></li><li>Food <b>25%</b></li><li>Transport <b>15%</b></li><li>Shopping <b>10%</b></li><li>Other <b>10%</b></li></ul></div><button className="link">View full report</button></Card></div></div>}

function Projects(){return <div className="board-page"><Top kicker="PROJECTS" title="Projects"/><div className="section-heading"><b>Active Projects</b><button>+ New Project</button></div><div className="project-cards">{[['Glow OS','Brand & Platform','75%','Due May 30'],['Terrain Design','Luxury Home','40%','Due Jun 12'],['Creative Branding','Client Project','25%','Due Jun 5']].map(([a,b,p,d])=><Card key={a}><b>{a}</b><span>{b}</span><div className="project-progress"><i style={{width:p}}/></div><small>{p}<em>{d}</em></small></Card>)}</div><p className="board-label steps-label">Recent Activity</p><div className="recent-grid">{[['Brand deck updated','Glow OS'],['Mood board added','Terrain Design'],['Client feedback','Creative Branding']].map(([a,b])=><Card key={a}><b>{a}</b><small>{b}</small><em>2h ago</em></Card>)}</div><button className="link right">View all</button></div>}

function FinancialBrain(){return <div className="board-page"><Top kicker="" title="Financial Brain" tabs={['Overview','Forecast','Scenarios','Recommendations']}/><div className="finance-metrics brain">{[['NET WORTH','$142,680'],['FREEDOM DATE','Dec 2031'],['MONTHLY SURPLUS','$2,890'],['FINANCIAL HEALTH','Great']].map(([a,b],i)=><Card key={a}><small>{a}</small><b>{b}</b><span className="green">● {i===0?'+8.2% this month':i===1?'On track':i===2?'42% of income':'Keep it up!'}</span></Card>)}</div><div className="brain-row"><Card title="CASH FLOW FORECAST"><div className="line-chart"><svg viewBox="0 0 600 150"><polyline points="0,85 55,72 110,92 165,74 220,88 275,50 330,68 385,43 440,62 495,32 550,50 600,22" fill="none" stroke={A} strokeWidth="2"/></svg><div>{['May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan'].map(x=><span key={x}>{x}</span>)}</div></div></Card><Card title="TOP RECOMMENDATION"><h3>Increase HYSA<br/>contribution</h3><p>You could earn an additional $1,240/year by increasing your automatic transfer.</p><Btn>Review</Btn></Card></div><p className="board-label steps-label">SCENARIO QUICK VIEW</p><div className="scenario-grid">{[['Buy House','Down payment in 18 mo','72% achievable'],['Quit Job','in 24 months','68% achievable'],['Early Retirement','in 10 years','55% achievable']].map(([a,b,c])=><Card key={a}><b>{a}</b><small>{b}</small><span>{c}</span></Card>)}</div></div>}

function Goals(){return <div className="board-page"><Top kicker="" title="Goals" tabs={['Overview','Timeline','Vision','Achievements','Reflections']}/><div className="goals-layout"><section><p className="board-label">THIS SEASON · 3 PRIORITIES</p>{[['Build Glow OS into a global brand','Why it matters: To create freedom and impact','75%','Due Jun 30'],['Travel the world with purpose','Why it matters: Experience + inspire','40%','Due Aug 15'],['Financial freedom','Why it matters: Time, choices, legacy','60%','Due Dec 31']].map(([a,b,p,d])=><Card key={a}><b>{a}</b><small>{b}</small><div className="project-progress"><i style={{width:p}}/></div><span>{p}<em>{d}</em></span></Card>)}</section><aside><p className="board-label">VISION BOARD</p><Img slot="goals:vision" label="Vision board" className="vision-board"/><button className="link">View Board</button></aside></div><p className="board-label steps-label">UPCOMING MILESTONES</p><div className="milestones">{['Brand deck\nMay 14','Bali trip\nJan 1','First retreat\nJul 20','Investment goal\nDec 31'].map(x=><span key={x}>{x.split('\n').map(a=><i key={a}>{a}</i>)}</span>)}</div></div>}

function LifeWorld(){return <div className="board-page"><Top kicker="LIFE WORLD" title="Life World" tabs={['Home','Map','Timeline','Digital Home','Collections']}/><Img slot="world:hero" label="Life World home" className="world-hero"><div className="world-copy"><h2>Welcome Home,<br/>Tatiyana.</h2><p>This is your space to dream,<br/>create, and live intentionally.</p><Btn>Enter Your World</Btn></div></Img><div className="section-heading"><b>RECENT SPACES</b><button>View all</button></div><div className="spaces">{['My Office','Creative Studio','Dream Closet','Wellness Room'].map((x,i)=><Img key={x} slot={`world:${i}`} label={x}><span>{x}</span></Img>)}</div></div>}

function Notes(){return <div className="board-page"><Top kicker="" title="Notes"/><div className="notes-grid"><aside><p className="board-label">NOTEBOOKS</p>{[['Personal','28'],['Work','15'],['Ideas','9'],['Journal','12'],['Recipes','6'],['Travel','4']].map(([a,b])=><button key={a}>{a}<b>{b}</b></button>)}<button className="link">+ New Notebook</button></aside><section><p className="board-label">RECENT NOTES</p>{['Doctor questions','Glow OS brand messaging','Bali trip ideas','Weekly reflection','Content ideas'].map((x,i)=><button className={i===0?'active':''} key={x}><b>{x}</b><small>{['May 12','May 12','May 11','May 11','May 10'][i]}</small><em>{['Personal','Work','Travel','Journal','Ideas'][i]}</em></button>)}</section><Card title="NOTE PREVIEW"><h3>Doctor questions</h3><ul><li>Bloodwork results</li><li>Hormone levels</li><li>Energy issues</li><li>Supplements</li></ul><small>Updated 1 hr ago</small><button className="link">Open Note</button></Card></div></div>}

function Settings(){return <div className="board-page"><Top kicker="SETTINGS" title="Settings"/><div className="settings-grid"><aside>{['Profile','Appearance','Notifications','Connections','Privacy & Security','Data & Storage','About Glow OS'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</aside><section><p className="board-label">PROFILE</p><Card className="profile-card"><div className="avatar">T</div><span><b>Tatiyana</b><small>Entrepreneur · Creator · Dreamer</small></span><button>Edit Profile</button></Card><p className="board-label steps-label">PREFERENCES</p><Card className="pref-card">{[['Language','English (US)'],['Time Zone','(UTC-5) Eastern Time'],['Date Format','May 12, 2025'],['Start Week On','Monday']].map(([a,b])=><div key={a}><b>{a}</b><span>{b}⌄</span></div>)}</Card></section></div></div>}

function Inbox(){return <div className="board-page"><Top kicker="" title="Inbox" tabs={['All','Tasks','Messages','Reminders','System']}/><p className="board-sub">All your incoming in one place</p><div className="inbox-list">{[['Client feedback received','Creative Branding Project','2m ago'],['Hair appointment reminder','May 14 at 2:10 PM','1h ago'],['Brand deck due tomorrow','Glow OS Project','2h ago'],['New message from Sarah','Re: Celebration','Yesterday'],['Pilates class booked','May 17 at 10:00 AM','Yesterday']].map(([a,b,c])=><button key={a}><span className="inbox-icon">□</span><span><b>{a}</b><small>{b}</small></span><em>{c}</em></button>)}</div><button className="link right">View all inbox</button></div>}

function Briefings(){return <div className="board-page"><Top kicker="" title="Briefings" tabs={['Morning Brief','Night Review','Weekly Brief']}/><p className="board-sub">Your daily intelligence from Glow.</p><Card className="brief-card"><section><h2>Good morning, <em>Tatiyana</em> ☀️</h2><p>Here are 5 things that matter today.</p><ol>{['Finish Glow OS brand deck (high priority)','Hair appointment at 2:30 PM','Client call at 11:00 AM','Deep work session at 9:00 AM','Drink more water today'].map(x=><li key={x}>{x}</li>)}</ol><Btn>Let&apos;s go</Btn></section><Img slot="briefings:quote" label="Morning briefing botanical"/></Card></div>}

function Glow(){return <div className="board-page"><Top kicker="GLOW" title="Glow"/><div className="glow-search"><span>Ask Glow anything...</span><button data-ref-action="voice">⌘</button></div><div className="prompt-chips">{['Morning Brief','What should I focus on?','Plan my day','Log a habit'].map(x=><button key={x} data-ref-action="voice">◉ {x}</button>)}</div><nav className="glow-tabs"><button className="active">Briefings</button><button>Insights</button><button>Inbox</button><button>Memory</button></nav><div className="glow-main"><Card><p className="board-label">Morning Brief</p><small>May 14, 2025</small><p>You have a productive day ahead. Focus on finishing your brand deck, move your body, and hydrate well.</p></Card><Img slot="glow:hero" label="Glow botanical"><div className="glow-quote">Glow is here<br/>to simplify,<br/>support, and<br/>elevate your<br/>every day.</div></Img></div></div>}

function Generic(){return <div className="board-page"><Top kicker="GLOW OS" title="Glow OS"/><Card><p>This room is connected to your Glow OS system.</p></Card></div>}

export function ReferenceRoomWorkspace(){const room=roomFor(usePathname());let page:React.ReactNode;switch(room){case'dashboard':page=<Dashboard/>;break;case'tasks':page=<Tasks/>;break;case'calendar':page=<Calendar/>;break;case'planning':page=<Planning/>;break;case'routines':page=<Routines/>;break;case'habits':page=<Habits/>;break;case'wellness':page=<Wellness/>;break;case'food':page=<Food/>;break;case'beauty':page=<Beauty/>;break;case'beauty-lab':page=<BeautyLab/>;break;case'hair':page=<Hair/>;break;case'finance':page=<Finance/>;break;case'financial-brain':page=<FinancialBrain/>;break;case'goals':page=<Goals/>;break;case'projects':page=<Projects/>;break;case'world':page=<LifeWorld/>;break;case'notes':page=<Notes/>;break;case'settings':page=<Settings/>;break;case'inbox':page=<Inbox/>;break;case'briefings':page=<Briefings/>;break;case'glow':page=<Glow/>;break;default:page=<Generic/>}return <div className="reference-room board-exact" data-room-board={room}>{page}</div>}
