'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { ArrowRight, BrainCircuit, CalendarDays, Check, ChevronRight, Circle, Clock3, Droplets, Dumbbell, FileText, Flower2, FolderKanban, HeartPulse, Home, Layers3, Mail, Network, NotebookText, PackageOpen, PiggyBank, Search, Settings, Shirt, Sparkles, Target, UploadCloud, Utensils, Wallet, WandSparkles } from 'lucide-react';

export type RoomSceneKey='tasks'|'calendar'|'planning'|'routines'|'habits'|'fitness'|'wellness'|'food'|'beauty'|'beauty-lab'|'hair'|'finance'|'financial-brain'|'goals'|'projects'|'brain'|'concierge'|'observations'|'memory'|'timeline'|'briefings'|'closet'|'gmail'|'world'|'home'|'connections'|'notes'|'import'|'settings';

type Scene={title:string;subtitle:string;label:string;accent:string;soft:string;icon:typeof Sparkles;links:Array<[string,string]>};

const SCENES:Record<RoomSceneKey,Scene>={
  tasks:{title:'The Life Control Desk',subtitle:'Move attention, not just check boxes.',label:'Decision desk',accent:'#9d6670',soft:'#f8e9e7',icon:Layers3,links:[['Do First','/tasks'],['Waiting On','/tasks'],['Fix My Day','/brain']]},
  calendar:{title:'The Time Gallery',subtitle:'Manipulate time as a visual story.',label:'Time intelligence',accent:'#8d6f7f',soft:'#efe7ee',icon:CalendarDays,links:[['Today','/calendar'],['Week','/calendar'],['Rebalance','/brain']]},
  planning:{title:'The Strategy Studio',subtitle:'Decide what matters before deciding when.',label:'Weekly architecture',accent:'#9a8062',soft:'#f5ecdf',icon:NotebookText,links:[['This Week','/planning'],['Reset Mode','/planning'],['Tomorrow','/tomorrow']]},
  routines:{title:'The Ritual Library',subtitle:'Open a ritual and let the rest of the interface fall away.',label:'Adaptive rituals',accent:'#a56e75',soft:'#f7e8e7',icon:Sparkles,links:[['Morning','/routines'],['Night','/routines'],['Emergency','/routines']]},
  habits:{title:'The Growth Garden',subtitle:'Consistency grows the environment instead of punishing misses.',label:'Living consistency',accent:'#758468',soft:'#edf2e7',icon:Flower2,links:[['Today','/habits'],['Month','/habits'],['Adjust Friction','/observations']]},
  fitness:{title:'The Body Sculpting Studio',subtitle:'Enter, train, log, rest, progress.',label:'Workout mode',accent:'#6b7f91',soft:'#e9eef2',icon:Dumbbell,links:[['Start Workout','/fitness'],['Recovery','/wellness'],['Progress','/fitness']]},
  wellness:{title:'The Sanctuary',subtitle:'Less information. More regulation.',label:'State reset',accent:'#668c8b',soft:'#e7f1ef',icon:HeartPulse,links:[['Check In','/wellness'],['I Need A Reset','/wellness'],['Make Today Lighter','/planning']]},
  food:{title:'The Nourishment Kitchen',subtitle:'Counter, fridge, pantry, cookbook and meal plan working together.',label:'Kitchen system',accent:'#8b7852',soft:'#f3ecdc',icon:Utensils,links:[['Today’s Meals','/food'],['Groceries','/food'],['Meal Prep','/planning']]},
  beauty:{title:'The Vanity Room',subtitle:'Routines become tactile, visual and guided.',label:'Interactive vanity',accent:'#b1767e',soft:'#f8e8ea',icon:Sparkles,links:[['Tonight','/beauty'],['Weekly Care','/beauty'],['Product Lab','/beauty/lab']]},
  'beauty-lab':{title:'The Product Laboratory',subtitle:'Every product has a lifecycle, history and place.',label:'Product science',accent:'#9d8a61',soft:'#f3eedf',icon:WandSparkles,links:[['Current Routine','/beauty/lab'],['Testing','/beauty/lab'],['Repurchase','/finance']]},
  hair:{title:'The Hair Atelier',subtitle:'See exactly where you are in the hair-care lifecycle.',label:'Salon lifecycle',accent:'#9b765e',soft:'#f2e8e0',icon:Sparkles,links:[['Current Style','/hair'],['Wash Day','/hair'],['Hair Forecast','/calendar']]},
  finance:{title:'The Private Money Journal',subtitle:'Money flows through envelopes, bills and savings jars.',label:'Private ledger',accent:'#607a68',soft:'#e9f0e9',icon:Wallet,links:[['August','/finance'],['Bills','/finance'],['Savings','/finance/brain']]},
  'financial-brain':{title:'The Money Intelligence Office',subtitle:'Interpret reality, compare scenarios and decide calmly.',label:'Money advisor',accent:'#586f61',soft:'#e7efea',icon:PiggyBank,links:[['Money Brief','/finance/brain'],['Can I Afford This?','/finance/brain'],['Ask','/brain']]},
  goals:{title:'The Dream Gallery',subtitle:'Every frame represents a future version of your life.',label:'Future-self gallery',accent:'#9a7b65',soft:'#f3ebe4',icon:Target,links:[['Active Dreams','/goals'],['Milestones','/goals'],['Next Move','/brain']]},
  projects:{title:'The Creative War Room',subtitle:'Active work, references, blockers and next actions spread across the studio.',label:'Creative command',accent:'#745f69',soft:'#eee7eb',icon:FolderKanban,links:[['Active Project','/projects'],['Next Action','/tasks'],['Ask Project Brain','/brain']]},
  brain:{title:'The Intelligence Chamber',subtitle:'One intelligence layer looking across the whole mansion.',label:'Central intelligence',accent:'#6d637e',soft:'#ece9f3',icon:BrainCircuit,links:[['What Now?','/brain'],['Signals','/observations'],['Do It For Me','/concierge']]},
  concierge:{title:'The Personal Service Desk',subtitle:'Requests become complete, reviewable service workflows.',label:'White-glove service',accent:'#9d7968',soft:'#f4ebe5',icon:Sparkles,links:[['Prepare Tomorrow','/concierge'],['Plan Errands','/concierge'],['Organize Week','/concierge']]},
  observations:{title:'The Observatory',subtitle:'Only signals worth your attention make it through.',label:'Attention budget',accent:'#697889',soft:'#e9edf1',icon:Search,links:[['Today’s Signals','/observations'],['Evidence','/observations'],['Act','/concierge']]},
  memory:{title:'The Digital Archive',subtitle:'Context rearranges around what you are trying to remember.',label:'Private archive',accent:'#776b62',soft:'#eeeae5',icon:FileText,links:[['2026','/memory'],['People + Places','/memory'],['Search Memory','/memory']]},
  timeline:{title:'The River of Your Life',subtitle:'Zoom from this hour to the story of your life.',label:'Life chronology',accent:'#657c7c',soft:'#e8efee',icon:Clock3,links:[['Today','/timeline'],['Year','/timeline'],['Lifetime','/timeline']]},
  briefings:{title:'The Glow Daily',subtitle:'Your life translated into an elegant personal newspaper.',label:'Daily edition',accent:'#786b62',soft:'#f0ebe7',icon:NotebookText,links:[['Morning Edition','/briefings'],['Evening Edition','/briefings'],['Tomorrow','/tomorrow']]},
  closet:{title:'The Digital Dressing Room',subtitle:'Racks, outfits, laundry and cost-per-wear in one wardrobe.',label:'Wardrobe lifecycle',accent:'#9b7378',soft:'#f5e9eb',icon:Shirt,links:[['Today’s Outfit','/closet'],['Wardrobe','/closet'],['Laundry','/home']]},
  gmail:{title:'The Communication Desk',subtitle:'Messages arrive in actionable piles instead of inbox overload.',label:'Action mail',accent:'#7d6f6a',soft:'#f1ece8',icon:Mail,links:[['Requires You','/gmail'],['Orders','/gmail'],['Create Task','/tasks']]},
  world:{title:'The Glow OS Mansion',subtitle:'A spatial second navigation system for the same living data.',label:'Digital world',accent:'#8a776b',soft:'#f1ebe5',icon:Home,links:[['Kitchen','/food'],['Vanity','/beauty'],['Office','/projects']]},
  home:{title:'The Physical Home Twin',subtitle:'A lightweight digital twin of your real environment.',label:'Home status',accent:'#827864',soft:'#f0ece2',icon:Home,links:[['Bedroom','/home'],['Kitchen','/food'],['Laundry','/home']]},
  connections:{title:'The Nervous System',subtitle:'See exactly how outside information reaches Glow OS.',label:'Connection graph',accent:'#667a82',soft:'#e8edef',icon:Network,links:[['Calendar','/connections'],['Gmail','/connections'],['Privacy','/settings']]},
  notes:{title:'The Thought Studio',subtitle:'Throw information here first. Organize it when you are ready.',label:'Creative capture',accent:'#a0776e',soft:'#f5eae5',icon:NotebookText,links:[['Capture','/notes'],['Organize This','/intake'],['Resources','/resources']]},
  import:{title:'The Intake Dock',subtitle:'Packages arrive, get understood, then move to the right systems.',label:'Customs checkpoint',accent:'#7a7484',soft:'#eceaf0',icon:PackageOpen,links:[['Upload','/intake'],['Review','/inbox'],['Connections','/connections']]},
  settings:{title:'The Control Room',subtitle:'Control the mansion, its intelligence and its visual behavior.',label:'System controls',accent:'#75665f',soft:'#eee9e5',icon:Settings,links:[['Appearance','/settings'],['Intelligence','/settings/intelligence'],['Privacy','/settings']]},
};

function Paper({children,className=''}:{children:React.ReactNode;className?:string}){return <div className={`rounded-[14px] border border-[#e7d9d1] bg-[#fffdf9] shadow-[0_12px_35px_rgba(76,55,47,.06)] ${className}`}>{children}</div>}
function Portal({href,label,accent}:{href:string;label:string;accent:string}){return <Link href={href} className="group inline-flex items-center gap-1.5 rounded-full border bg-white/75 px-3 py-2 text-[8px] font-medium transition hover:-translate-y-0.5" style={{borderColor:`${accent}45`,color:accent}}>{label}<ArrowRight size={9} className="transition group-hover:translate-x-0.5"/></Link>}

export function RoomExperienceStage({roomKey}:{roomKey:string}){
  const scene=SCENES[roomKey as RoomSceneKey];
  const [mode,setMode]=useState(0);
  const [active,setActive]=useState(0);
  const [reset,setReset]=useState(false);
  const modes=useMemo(()=>scene?.links??[],[scene]);
  if(!scene)return null;
  const Icon=scene.icon;
  const action=()=>setMode((v)=>(v+1)%Math.max(modes.length,1));

  const shell=(content:React.ReactNode)=><section className="mb-6 overflow-hidden rounded-[24px] border border-[#e7d9d1] shadow-[0_18px_60px_rgba(75,55,47,.07)]" style={{background:`linear-gradient(135deg,${scene.soft},#fffaf6 48%,#f8f0ea)`}}>
    <div className="flex flex-col gap-4 border-b border-white/70 px-5 py-5 sm:flex-row sm:items-end sm:justify-between">
      <div><div className="flex items-center gap-2" style={{color:scene.accent}}><Icon size={14}/><span className="text-[8px] font-bold uppercase tracking-[.2em]">{scene.label}</span></div><h2 className="glow-display mt-1 text-[28px] leading-none text-[#3d302c]">{scene.title}</h2><p className="mt-2 max-w-2xl text-[10px] leading-5 text-[#7d6962]">{scene.subtitle}</p></div>
      <div className="flex flex-wrap gap-2">{scene.links.map(([label,href])=><Portal key={label} label={label} href={href} accent={scene.accent}/>)}</div>
    </div>{content}</section>;

  if(roomKey==='tasks')return shell(<div className="grid gap-3 p-4 lg:grid-cols-[1fr_1.5fr_1fr]"><Paper className="p-4"><p className="text-[8px] font-bold uppercase tracking-[.17em] text-[#9b7771]">Inbox</p><p className="mt-4 text-[10px] text-[#715e57]">Unprocessed captures land here first.</p><Link href="/inbox" className="mt-5 inline-flex text-[8px] text-[#9d6670]">Process inbox →</Link></Paper><div className="grid gap-2 sm:grid-cols-3">{['DO FIRST','DO TODAY','CAN WAIT'].map((x,i)=><button key={x} type="button" onClick={()=>setActive(i)} className={`min-h-[190px] rounded-[12px] border p-4 text-left transition ${active===i?'scale-[1.01] bg-white shadow-lg':'bg-white/55'}`}><span className="text-[8px] font-bold tracking-[.16em]" style={{color:scene.accent}}>{x}</span><div className="mt-5 space-y-2">{[0,1,2].map(n=><div key={n} className="rounded-lg border border-[#eadfd8] bg-[#fffaf8] p-3 text-[9px] text-[#63514b]">{n===0&&i===0?'Most important next action':'Drag or tap a task here'}</div>)}</div></button>)}</div><Paper className="p-4"><p className="text-[8px] font-bold uppercase tracking-[.17em] text-[#9b7771]">Waiting On</p><p className="mt-4 text-[10px] text-[#715e57]">Dependencies stay visible without crowding today.</p><button type="button" onClick={action} className="mt-5 rounded-full px-3 py-2 text-[8px] text-white" style={{background:scene.accent}}>Fix My Day</button></Paper></div>);

  if(roomKey==='calendar')return shell(<div className="p-4"><div className="mb-4 flex gap-2">{['Today','Week','Month'].map((x,i)=><button key={x} type="button" onClick={()=>setActive(i)} className="rounded-full px-3 py-2 text-[8px]" style={{background:active===i?scene.accent:'#fff',color:active===i?'white':'#6f5d57'}}>{x}</button>)}</div><div className="grid gap-3 lg:grid-cols-[110px_1fr]"> <div className="space-y-5 pt-2 text-right text-[8px] text-[#927f78]">{['5 AM','8 AM','11 AM','2 PM','5 PM','8 PM','11 PM'].map(t=><p key={t}>{t}</p>)}</div><div className="relative min-h-[360px] border-l border-[#d8c8c2] pl-5"><div className="absolute left-[-4px] top-5 h-2 w-2 rounded-full" style={{background:scene.accent}}/>{['Morning Routine','Breakfast + prep','Deep work block','Appointment / work','Dinner','Night routine'].map((x,i)=><Link href="/calendar" key={x} className="mb-3 block rounded-[12px] border border-white/80 p-4 text-[10px] text-[#554641] shadow-sm" style={{background:i%2?scene.soft:'#fff'}}><span className="font-medium">{x}</span><span className="float-right text-[8px] text-[#9a857d]">{i%2?'45 min':'1h 15m'}</span></Link>)}</div></div></div>);

  if(roomKey==='planning')return shell(<div className="p-4">{reset?<div className="mx-auto max-w-xl py-8 text-center"><p className="text-[8px] uppercase tracking-[.18em]" style={{color:scene.accent}}>Sunday Reset</p><p className="glow-display mt-3 text-[30px] text-[#3e312d]">{active+1}/10 · {['Clean','Laundry','Fridge','Groceries','Meal Prep','Hair','Beauty','Finance','Calendar','Plan Week'][active]}</p><button type="button" onClick={()=>active<9?setActive(active+1):setReset(false)} className="mt-6 rounded-full px-5 py-3 text-[9px] text-white" style={{background:scene.accent}}>{active<9?'Complete + Next':'Your Week Is Ready'}</button></div>:<div className="grid gap-3 lg:grid-cols-[1fr_1.4fr_1fr]"><Paper className="p-4"><p className="glow-display text-[18px]">This Week</p><p className="mt-4 text-[8px] uppercase tracking-[.15em] text-[#9b7771]">Main intention</p><div className="mt-2 h-20 rounded-lg bg-[#f7eee8]"/></Paper><Paper className="p-4"><p className="glow-display text-[18px]">Weekly Map</p><div className="mt-4 grid grid-cols-7 gap-1">{['S','M','T','W','T','F','S'].map((d,i)=><div key={`${d}${i}`} className="min-h-[120px] rounded-md bg-[#f8f1ec] p-2 text-center text-[8px]">{d}<div className="mt-3 h-8 rounded bg-white"/></div>)}</div></Paper><Paper className="p-4"><p className="glow-display text-[18px]">Brain Dump</p><div className="mt-4 space-y-2">{['Waiting on','Things to buy','Ideas','Meals'].map(x=><div key={x} className="border-b border-[#eadfd8] pb-2 text-[9px] text-[#715e57]">{x}</div>)}</div><button type="button" onClick={()=>{setActive(0);setReset(true)}} className="mt-5 w-full rounded-full px-3 py-2 text-[8px] text-white" style={{background:scene.accent}}>Enter Reset Mode</button></Paper></div>}</div>);

  if(roomKey==='routines')return shell(<div className="grid gap-4 p-4 lg:grid-cols-[.8fr_1.4fr]"><div className="grid grid-cols-2 gap-2">{['Morning','Night','Wash Day','Everything Shower','Work Morning','Midday Reset'].map((x,i)=><button key={x} type="button" onClick={()=>setActive(i)} className={`min-h-[95px] rounded-[14px] border p-3 text-left ${active===i?'bg-white shadow-md':'bg-white/50'}`}><Sparkles size={13} style={{color:scene.accent}}/><p className="glow-display mt-2 text-[14px]">{x}</p></button>)}</div><Paper className="p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] uppercase tracking-[.15em]" style={{color:scene.accent}}>Adaptive Ritual</p><p className="glow-display mt-1 text-[24px]">{['Morning','Night','Wash Day','Everything Shower','Work Morning','Midday Reset'][active]??'Morning'}</p></div><span className="text-[9px] text-[#8c7770]">Step 4 of 11</span></div><div className="mt-6 rounded-[18px] p-5" style={{background:scene.soft}}><p className="text-[8px] font-bold uppercase tracking-[.15em]">How much time?</p><div className="mt-3 flex flex-wrap gap-2">{['Full','Normal','30 min','15 min','Emergency'].map((x,i)=><button key={x} type="button" onClick={()=>setMode(i)} className="rounded-full border px-3 py-2 text-[8px]" style={{background:mode===i?scene.accent:'white',color:mode===i?'white':'#6f5d57'}}>{x}</button>)}</div><p className="glow-display mt-6 text-[20px]">SKINCARE</p><p className="mt-2 text-[10px] text-[#6f5d57]">Cleanse → Treatment → Moisturize → SPF</p></div></Paper></div>);

  if(roomKey==='habits')return shell(<div className="p-4"><div className="mb-3 flex gap-2">{['Today','Week','Month','Year'].map((x,i)=><button key={x} type="button" onClick={()=>setActive(i)} className="rounded-full px-3 py-2 text-[8px]" style={{background:active===i?scene.accent:'white',color:active===i?'white':'#6f5d57'}}>{x}</button>)}</div><div className="relative min-h-[300px] overflow-hidden rounded-[20px] bg-[linear-gradient(180deg,#edf4e8,#f9f3e7)]"><div className="absolute bottom-0 h-20 w-full bg-[#c8d5b8]"/><div className="absolute bottom-16 left-[10%] h-24 w-24 rounded-full bg-[#a5b890]"/><div className="absolute bottom-12 left-[30%] h-40 w-4 rounded-full bg-[#879a73]"/><div className="absolute bottom-20 left-[25%] h-24 w-24 rounded-full bg-[#a9ba8f]"/><div className="absolute bottom-10 right-[12%] h-28 w-28 rounded-full bg-[#91a782]"/><div className="absolute left-1/2 top-8 -translate-x-1/2 text-center"><Flower2 size={36} className="mx-auto" style={{color:scene.accent}}/><p className="glow-display mt-2 text-[22px] text-[#42503d]">Your growth is visible.</p><p className="mt-2 text-[9px] text-[#687362]">Water grows the pond. Fitness grows the tree. Reading grows flowers.</p></div></div></div>);

  if(roomKey==='fitness')return shell(<div className="grid gap-3 p-4 lg:grid-cols-[.8fr_1.4fr_.8fr]"><Paper className="p-4"><p className="text-[8px] uppercase tracking-[.15em] text-[#8c7770]">Today</p><p className="glow-display mt-2 text-[22px]">Glutes + Hamstrings</p><p className="mt-2 text-[9px] text-[#7d6962]">48 min · 6 exercises</p><button type="button" onClick={()=>setActive(active?0:1)} className="mt-5 w-full rounded-full px-3 py-2 text-[8px] text-white" style={{background:scene.accent}}>{active?'End Workout':'Start Workout'}</button></Paper><div className="rounded-[22px] p-6 text-center text-white" style={{background:`linear-gradient(145deg,${scene.accent},#394a57)`}}><p className="text-[8px] uppercase tracking-[.18em] text-white/70">{active?'Active Exercise':'Ready'}</p><Dumbbell size={38} className="mx-auto mt-5"/><p className="glow-display mt-4 text-[30px]">HIP THRUST</p><p className="mt-3 text-[10px]">Previous 110 × 10 · Target 115 × 8–10</p><div className="mt-5 flex justify-center gap-2">{[0,1,2,3].map(i=><Circle key={i} size={14} className={i<2?'fill-white':'text-white/50'}/>)}</div></div><Paper className="p-4"><p className="glow-display text-[18px]">Studio Walls</p><div className="mt-4 space-y-2">{['Workout Library','Progress Photos','Strength','Steps','Mobility','Recovery'].map(x=><Link href="/fitness" key={x} className="block rounded-lg bg-[#f1f4f6] px-3 py-2 text-[9px]">{x}</Link>)}</div></Paper></div>);

  if(roomKey==='wellness')return shell(<div className="mx-auto max-w-3xl p-8 text-center"><Droplets size={30} className="mx-auto" style={{color:scene.accent}}/><p className="glow-display mt-4 text-[28px]">How are you right now?</p><div className="mx-auto mt-6 grid max-w-xl gap-3 sm:grid-cols-4">{[['Energy','●●●○○'],['Stress','●●○○○'],['Mood','🙂'],['Sleep','7h 21m']].map(([a,b])=><Paper key={a} className="p-4"><p className="text-[8px] uppercase tracking-[.15em] text-[#8c7770]">{a}</p><p className="mt-3 text-[15px]">{b}</p></Paper>)}</div><button type="button" onClick={()=>setReset(!reset)} className="mt-7 rounded-full px-5 py-3 text-[9px] text-white" style={{background:scene.accent}}>I Need A Reset</button>{reset?<div className="mt-6 rounded-[18px] bg-white/70 p-6 text-[12px] leading-8 text-[#5c6e6c]">Breathe. Drink water. Unclench your jaw. Lower your shoulders. Stand. Walk. Eat if needed. Choose one thing.</div>:null}</div>);

  if(roomKey==='food')return shell(<div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-4">{[['Counter','Today’s meals','Breakfast · Lunch · Dinner'],['Fridge','Inventory','Spinach · Use soon'],['Pantry','Staples','Rice · Pasta · Spices'],['Cookbook','Recipes','Saved favorites']].map(([a,b,c],i)=><button key={a} type="button" onClick={()=>setActive(i)} className={`min-h-[190px] rounded-[18px] border p-5 text-left transition ${active===i?'bg-white shadow-lg':'bg-white/55'}`}><Utensils size={18} style={{color:scene.accent}}/><p className="glow-display mt-4 text-[22px]">{a}</p><p className="mt-1 text-[8px] uppercase tracking-[.12em] text-[#9a857d]">{b}</p><p className="mt-8 text-[10px] text-[#6e5b54]">{c}</p></button>)}</div>);

  if(roomKey==='beauty')return shell(<div className="grid gap-4 p-4 lg:grid-cols-[.8fr_1.4fr_.8fr]"><Paper className="p-4"><p className="glow-display text-[18px]">Face Shelf</p>{['Cleanser','Treatment','Moisturizer','SPF'].map(x=><div key={x} className="mt-3 h-10 rounded-lg bg-[#f6e9e9] px-3 py-3 text-[9px]">{x}</div>)}</Paper><div className="rounded-[50%_50%_18%_18%] border-[8px] border-[#ead9d5] bg-[radial-gradient(circle_at_50%_30%,#fff,#f5e9e6)] p-8 text-center shadow-inner"><p className="text-[8px] uppercase tracking-[.18em]" style={{color:scene.accent}}>Tonight</p><p className="glow-display mt-3 text-[28px]">PM ROUTINE</p><p className="mt-4 text-[10px] leading-6 text-[#6d5952]">Cleanser<br/>Treatment<br/>Moisturizer</p><Link href="/beauty" className="mt-6 inline-flex rounded-full px-4 py-2 text-[8px] text-white" style={{background:scene.accent}}>Start Routine</Link></div><Paper className="p-4"><p className="glow-display text-[18px]">Weekly Drawer</p>{['Gua Sha','Everything Shower','Nails','Brows','Face Mask'].map(x=><div key={x} className="mt-2 border-b border-[#eadfd8] py-2 text-[9px]">{x}</div>)}</Paper></div>);

  if(roomKey==='beauty-lab')return shell(<div className="p-4"><div className="grid gap-3 md:grid-cols-4">{['Current Routine','Backups','Testing','Wishlist'].map((x,i)=><button key={x} onClick={()=>setActive(i)} type="button" className={`rounded-[14px] border p-4 text-left ${active===i?'bg-white shadow-md':'bg-white/55'}`}><p className="text-[8px] uppercase tracking-[.14em]" style={{color:scene.accent}}>{x}</p><div className="mt-5 flex items-end gap-2">{[36,52,42,64].map((h,n)=><span key={n} className="w-5 rounded-t-md bg-[#d6c7a7]" style={{height:h}}/>)}</div></button>)}</div><p className="mt-4 text-center text-[8px] text-[#8d7972]">Want → Purchased → Unopened → Open → Running Low → Empty → Repurchase / Retire</p></div>);

  if(roomKey==='hair')return shell(<div className="grid gap-4 p-4 lg:grid-cols-[1.1fr_.9fr]"><div className="relative min-h-[280px] rounded-[22px] bg-[linear-gradient(145deg,#6b5146,#b29483,#efe1d7)]"><div className="absolute bottom-5 left-5 rounded-xl bg-white/80 p-4"><p className="text-[8px] uppercase tracking-[.15em]">Current Style</p><p className="glow-display mt-1 text-[22px]">U-Part</p><p className="mt-1 text-[9px]">Installed Aug 3 · Day 7</p></div></div><Paper className="p-5"><p className="glow-display text-[18px]">Hair Cycle</p><div className="mt-5 space-y-4">{['Wash','Style','Maintain','Refresh','Wash'].map((x,i)=><div key={`${x}${i}`} className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full text-[8px] text-white" style={{background:i<=2?scene.accent:'#d8ccc5'}}>{i+1}</span><span className="text-[10px]">{x}</span>{i===2?<span className="ml-auto text-[8px]" style={{color:scene.accent}}>You are here</span>:null}</div>)}</div><Link href="/hair" className="mt-6 block rounded-full py-2 text-center text-[8px] text-white" style={{background:scene.accent}}>Begin Wash Day</Link></Paper></div>);

  if(roomKey==='finance')return shell(<div className="grid gap-4 p-4 lg:grid-cols-[1.2fr_.8fr]"><Paper className="p-5"><div className="flex items-end justify-between"><div><p className="text-[8px] uppercase tracking-[.15em] text-[#8d7972]">August</p><p className="glow-display mt-1 text-[28px]">Money Journal</p></div><Wallet size={24} style={{color:scene.accent}}/></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Income','$—'],['Spent','$—'],['Remaining','$—'],['Saved','$—']].map(([a,b])=><div key={a} className="rounded-xl bg-[#f1f5f0] p-3"><p className="text-[8px] text-[#7b6a63]">{a}</p><p className="glow-display mt-1 text-[18px]">{b}</p></div>)}</div><div className="mt-6 grid grid-cols-3 gap-2">{['Rent','Food','Beauty','Transportation','Saint','Fun','Savings'].map((x,i)=><button key={x} type="button" onClick={()=>setActive(i)} className="rounded-b-[16px] rounded-t-sm border border-[#d9e2d8] bg-[#edf4eb] px-3 py-4 text-[9px]">{x}</button>)}</div></Paper><Paper className="p-5"><p className="glow-display text-[18px]">Savings Jars</p>{['Travel','Emergency','Terrain Design','Future Home'].map((x,i)=><div key={x} className="mt-4"><div className="flex justify-between text-[8px]"><span>{x}</span><span>{20+i*13}%</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-[#e9e2dc]"><div className="h-full rounded-full" style={{width:`${20+i*13}%`,background:scene.accent}}/></div></div>)}</Paper></div>);

  if(roomKey==='financial-brain')return shell(<div className="grid gap-4 p-4 lg:grid-cols-[1.3fr_.7fr]"><Paper className="p-6"><p className="text-[8px] uppercase tracking-[.17em]" style={{color:scene.accent}}>August Money Brief</p><p className="glow-display mt-3 text-[25px]">What the numbers mean</p><div className="mt-5 space-y-3 text-[10px] leading-5 text-[#66544e]"><p>Overall pace → stable until live transaction data says otherwise.</p><p>Beauty → compare against your personal baseline.</p><p>Renewals → surface before they become surprises.</p><p>Savings → forecast against the dates that matter to you.</p></div></Paper><Paper className="p-5"><p className="glow-display text-[18px]">Ask the advisor</p>{['Can I afford this?','Where can I save $200?','What bills are coming?','What if I save more weekly?'].map(x=><Link href="/brain" key={x} className="mt-3 block rounded-xl bg-[#edf3ee] p-3 text-[9px]">{x}</Link>)}</Paper></div>);

  if(roomKey==='goals')return shell(<div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4">{['Glow OS','Career','Travel','Fitness','Home','Money','Beauty','Future'].map((x,i)=><button type="button" onClick={()=>setActive(i)} key={x} className={`min-h-[150px] border-[7px] p-3 text-center shadow-md ${active===i?'bg-white':'bg-[#faf4ee]'}`} style={{borderColor:i===active?scene.accent:'#d8c5b7'}}><Target className="mx-auto mt-3" size={18} style={{color:scene.accent}}/><p className="glow-display mt-3 text-[18px]">{x}</p><p className="mt-2 text-[8px] text-[#8d7972]">Vision → milestone → next action</p></button>)}</div>);

  if(roomKey==='projects')return shell(<div className="grid gap-3 p-4 lg:grid-cols-[.75fr_1.5fr_.75fr]"><Paper className="p-4"><p className="text-[8px] uppercase tracking-[.14em] text-[#8d7972]">Project Covers</p>{['Glow OS','Terrain Design','Branding Studio','Career'].map((x,i)=><button type="button" key={x} onClick={()=>setActive(i)} className={`mt-2 block w-full rounded-xl p-3 text-left text-[9px] ${active===i?'bg-[#eee7eb]':'bg-[#f8f3f0]'}`}>{x}</button>)}</Paper><div className="relative min-h-[300px] rounded-[20px] bg-[linear-gradient(135deg,#5f4d55,#8e7780)] p-5 text-white"><p className="text-[8px] uppercase tracking-[.18em] text-white/60">Active Studio</p><p className="glow-display mt-2 text-[30px]">{['Glow OS','Terrain Design','Branding Studio','Career'][active]}</p><div className="absolute bottom-5 left-5 right-5 rounded-xl bg-white/90 p-4 text-[#493c3f]"><p className="text-[8px] font-bold uppercase tracking-[.15em]">Next Action</p><p className="glow-display mt-2 text-[17px]">Choose the next unblocked move.</p><Link href="/tasks" className="mt-2 inline-flex text-[8px]" style={{color:scene.accent}}>Open task board →</Link></div></div><Paper className="p-4"><p className="glow-display text-[18px]">Studio Rail</p>{['References','Timeline','Notes','Files','Decisions'].map(x=><Link href="/projects" key={x} className="mt-3 block border-b border-[#eadfd8] pb-2 text-[9px]">{x}</Link>)}</Paper></div>);

  if(roomKey==='brain')return shell(<div className="mx-auto max-w-4xl p-5"><div className="rounded-[26px] bg-[radial-gradient(circle_at_50%_25%,#77708a,#443f50_55%,#29252f)] p-8 text-center text-white shadow-xl"><BrainCircuit size={34} className="mx-auto text-[#e3dff0]"/><p className="glow-display mt-4 text-[30px]">What do you need?</p><p className="mt-3 text-[10px] text-white/65">Calendar + Tasks + Food + Projects + Wellness + Money + Memory</p><div className="mx-auto mt-7 max-w-xl rounded-[18px] bg-white/10 p-5 text-left"><p className="text-[8px] uppercase tracking-[.15em] text-white/55">Right now</p><p className="mt-3 text-[11px] leading-6">Glow chooses a recommendation from the Life Graph, explains why, then prepares safe changes for approval.</p></div><Link href="/brain" className="mt-6 inline-flex rounded-full bg-white px-5 py-3 text-[9px] text-[#443f50]">Ask Glow</Link></div></div>);

  if(roomKey==='concierge')return shell(<div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4">{['Prepare Tomorrow','Plan My Errands','Build Grocery List','Prepare Appointment','Plan Outfit','Organize My Week'].map((x,i)=><button type="button" onClick={()=>setActive(i)} key={x} className={`min-h-[120px] rounded-[16px] border p-4 text-left ${active===i?'bg-white shadow-md':'bg-white/55'}`}><Sparkles size={16} style={{color:scene.accent}}/><p className="glow-display mt-3 text-[17px]">{x}</p><p className="mt-2 text-[8px] text-[#8d7972]">Review → prepare → approve</p></button>)}</div>);

  if(roomKey==='observations')return shell(<div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-4">{[['Hair','Wash Day approaching'],['Projects','One project has been quiet'],['Food','Use-soon inventory'],['Finance','Watch category drift']].map(([a,b],i)=><Paper key={a} className="p-4"><p className="text-[8px] uppercase tracking-[.15em]" style={{color:scene.accent}}>{a}</p><p className="glow-display mt-3 text-[17px]">{b}</p><div className="mt-5 flex gap-2">{['Act','Snooze','Dismiss'].map(x=><button type="button" key={x} onClick={()=>setActive(i)} className="rounded-full border border-[#e1d6d0] px-2 py-1 text-[7px]">{x}</button>)}</div></Paper>)}</div>);

  if(roomKey==='memory')return shell(<div className="grid gap-3 p-4 lg:grid-cols-[.7fr_1.3fr]"><div className="grid grid-cols-2 gap-2">{['2026','People','Places','Projects','Decisions','Photos','Journal','Milestones'].map((x,i)=><button type="button" onClick={()=>setActive(i)} key={x} className={`min-h-[85px] rounded-xl border p-3 text-left ${active===i?'bg-white shadow':'bg-white/50'}`}><FileText size={13} style={{color:scene.accent}}/><p className="glow-display mt-2 text-[15px]">{x}</p></button>)}</div><Paper className="p-5"><div className="flex items-center gap-2 rounded-full border border-[#e3d9d2] bg-white px-4 py-3"><Search size={13}/><span className="text-[9px] text-[#8d7972]">Show me everything about…</span></div><div className="mt-5 grid gap-2 sm:grid-cols-3">{['Photos','Notes','Decisions','Dates','Conversations','Milestones'].map(x=><div key={x} className="rounded-xl bg-[#f3efeb] p-4 text-[9px]">{x}</div>)}</div></Paper></div>);

  if(roomKey==='timeline')return shell(<div className="p-6"><div className="flex justify-center gap-2">{['Day','Week','Month','Year','Life'].map((x,i)=><button key={x} onClick={()=>setActive(i)} type="button" className="rounded-full px-3 py-2 text-[8px]" style={{background:active===i?scene.accent:'white',color:active===i?'white':'#6f5d57'}}>{x}</button>)}</div><div className="relative mt-12 h-[170px]"><div className="absolute left-0 right-0 top-1/2 h-[2px] bg-[#bdcbc7]"/>{['2024','2025','2026','Today'].map((x,i)=><div key={x} className="absolute top-1/2 -translate-x-1/2 -translate-y-1/2 text-center" style={{left:`${12+i*27}%`}}><div className="mx-auto h-4 w-4 rounded-full border-4 border-white" style={{background:scene.accent}}/><p className="mt-3 text-[9px]">{x}</p></div>)}</div></div>);

  if(roomKey==='briefings')return shell(<div className="p-4"><Paper className="mx-auto max-w-5xl p-6"><div className="border-b-2 border-[#4b403b] pb-3 text-center"><p className="glow-display text-[34px]">THE GLOW DAILY</p><p className="mt-1 text-[8px] uppercase tracking-[.25em]">Your personal edition</p></div><div className="mt-5 grid gap-5 md:grid-cols-[1.5fr_1fr_1fr]"><div><p className="text-[8px] font-bold uppercase tracking-[.15em]">Lead Story</p><p className="glow-display mt-2 text-[25px]">Your day, edited down to what matters.</p><p className="mt-4 text-[9px] leading-5 text-[#6d5b55]">Schedule, Top 3, meals, workout, money, messages, projects and one useful observation.</p></div>{['Schedule + Top 3','Meals + Workout','Money + Messages','Projects + Observation'].slice(0,2).map(x=><div key={x} className="border-l border-[#ded1c9] pl-4"><p className="glow-display text-[17px]">{x}</p><div className="mt-3 space-y-2">{[1,2,3].map(n=><div key={n} className="h-2 rounded bg-[#eee6df]"/>)}</div></div>)}</div></Paper></div>);

  if(roomKey==='closet')return shell(<div className="grid gap-4 p-4 lg:grid-cols-[1.5fr_.7fr]"><div className="rounded-[20px] bg-[#f7efeb] p-5"><div className="flex items-end gap-3 overflow-x-auto pb-4">{['Top','Dress','Jacket','Skirt','Pants','Bag'].map((x,i)=><button type="button" onClick={()=>setActive(i)} key={x} className={`flex h-[170px] min-w-[95px] flex-col items-center justify-end rounded-t-[45px] border p-3 ${active===i?'bg-white shadow-md':'bg-[#eadbd5]'}`}><Shirt size={25} style={{color:scene.accent}}/><span className="mt-5 text-[8px]">{x}</span></button>)}</div><p className="text-center text-[8px] text-[#8d7972]">Swipe the rack · tap a piece · build an outfit</p></div><Paper className="p-5 text-center"><p className="text-[8px] uppercase tracking-[.15em]" style={{color:scene.accent}}>Today’s Outfit</p><div className="mx-auto mt-5 h-36 w-20 rounded-t-full bg-[#ead8d9]"/><p className="mt-4 text-[9px] text-[#6d5b55]">Weather + event + dress code + plans</p><Link href="/closet" className="mt-4 inline-flex rounded-full px-4 py-2 text-[8px] text-white" style={{background:scene.accent}}>Build Outfit</Link></Paper></div>);

  if(roomKey==='gmail')return shell(<div className="grid gap-3 p-4 md:grid-cols-5">{['REQUIRES YOU','WAITING','ORDERS','APPOINTMENTS','FYI'].map((x,i)=><button type="button" onClick={()=>setActive(i)} key={x} className={`min-h-[180px] rounded-[6px] border p-4 text-left shadow-sm ${active===i?'rotate-0 bg-white shadow-lg':'bg-[#fffdf9]'}`} style={{transform:active===i?'none':`rotate(${i%2?1:-1}deg)`}}><Mail size={16} style={{color:scene.accent}}/><p className="mt-4 text-[8px] font-bold tracking-[.12em]">{x}</p><p className="mt-4 text-[9px] leading-4 text-[#74615a]">Messages become summary + need + deadline + action.</p></button>)}</div>);

  if(roomKey==='world')return shell(<div className="relative min-h-[360px] overflow-hidden bg-[radial-gradient(circle_at_50%_20%,#fff9f4,#dfcfc4_65%,#bea99b)] p-5"><div className="mx-auto grid max-w-5xl grid-cols-2 gap-3 pt-8 sm:grid-cols-4">{[['Kitchen','/food',Utensils],['Vanity','/beauty',Sparkles],['Closet','/closet',Shirt],['Gym','/fitness',Dumbbell],['Garden','/habits',Flower2],['Office','/projects',FolderKanban],['Library','/memory',FileText],['Control','/settings',Settings]].map(([x,href,I])=>{const IconX=I as typeof Sparkles;return <Link key={String(x)} href={String(href)} className="flex min-h-[120px] flex-col items-center justify-center rounded-[18px] border border-white/70 bg-white/45 text-center backdrop-blur-sm transition hover:-translate-y-1 hover:bg-white/75"><IconX size={20} style={{color:scene.accent}}/><p className="glow-display mt-2 text-[16px]">{String(x)}</p></Link>})}</div></div>);

  if(roomKey==='home')return shell(<div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4">{[['Bedroom','Clean ✓','Sheets: review Sunday'],['Kitchen','Needs review','Groceries + fridge'],['Laundry','2 loads','Move through cycle'],['Saint','Care','Food + supplies + routines']].map(([a,b,c],i)=><button type="button" onClick={()=>setActive(i)} key={a} className={`rounded-[18px] border p-5 text-left ${active===i?'bg-white shadow-md':'bg-white/55'}`}><Home size={18} style={{color:scene.accent}}/><p className="glow-display mt-3 text-[20px]">{a}</p><p className="mt-2 text-[9px] font-medium">{b}</p><p className="mt-1 text-[8px] text-[#8d7972]">{c}</p></button>)}</div>);

  if(roomKey==='connections')return shell(<div className="relative min-h-[330px] p-4"><div className="absolute left-1/2 top-1/2 flex h-28 w-28 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full text-center text-white shadow-lg" style={{background:scene.accent}}><div><Sparkles size={18} className="mx-auto"/><p className="glow-display mt-2 text-[15px]">GLOW OS</p></div></div>{[['Calendar',15,20],['Reminders',80,20],['Gmail',12,72],['Weather',82,72],['Health',50,86]].map(([x,l,t],i)=><Link href="/connections" key={String(x)} className="absolute flex h-20 w-24 flex-col items-center justify-center rounded-[15px] border bg-white/80 text-center shadow-sm" style={{left:`${l}%`,top:`${t}%`,transform:'translate(-50%,-50%)'}}><Network size={14} style={{color:i===1?'#b58a59':scene.accent}}/><p className="mt-1 text-[8px]">{String(x)}</p><span className="mt-1 text-[7px]" style={{color:i===1?'#b58a59':'#66806a'}}>{i===1?'Review':'Connected / manage'}</span></Link>)}</div>);

  if(roomKey==='notes')return shell(<div className="relative min-h-[320px] overflow-hidden p-5">{['Idea','Screenshot','Voice note','Link','Thought','Reference','Appointment?','Project idea'].map((x,i)=><button type="button" onClick={()=>setActive(i)} key={x} className="absolute h-24 w-28 rounded-[4px] p-3 text-left shadow-md" style={{left:`${6+(i%4)*23}%`,top:`${10+Math.floor(i/4)*47}%`,background:i%3===0?'#f7e7c2':i%3===1?'#f0d8dc':'#e7e1ef',transform:`rotate(${i%2?2:-2}deg)`}}><p className="glow-hand text-[18px]">{x}</p><p className="mt-3 text-[7px] text-[#7a6861]">Capture first. Decide later.</p></button>)}</div>);

  if(roomKey==='import')return shell(<div className="grid gap-4 p-4 lg:grid-cols-[1fr_1.4fr]"><div className="grid grid-cols-2 gap-2">{[['PDF',FileText],['Photo',Sparkles],['Receipt',Wallet],['CSV',FileText],['Recipe',Utensils],['Schedule',CalendarDays]].map(([x,I])=>{const IconX=I as typeof Sparkles;return <Link href="/intake" key={String(x)} className="flex min-h-[95px] flex-col items-center justify-center rounded-[15px] border bg-white/60"><IconX size={17} style={{color:scene.accent}}/><p className="mt-2 text-[9px]">{String(x)}</p></Link>})}</div><Paper className="p-5"><div className="flex items-center gap-2"><UploadCloud size={16} style={{color:scene.accent}}/><p className="text-[8px] uppercase tracking-[.16em]">Processing Dock</p></div><p className="glow-display mt-4 text-[24px]">I found…</p><div className="mt-4 grid grid-cols-2 gap-2 text-[9px]">{['Routines','Habits','Grocery items','Beauty products','Dates','Project references'].map(x=><div key={x} className="rounded-lg bg-[#f3eff3] p-3">{x}</div>)}</div><Link href="/intake" className="mt-5 inline-flex rounded-full px-4 py-2 text-[8px] text-white" style={{background:scene.accent}}>Open Universal Intake</Link></Paper></div>);

  if(roomKey==='settings')return shell(<div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-4">{[['Appearance Studio','Theme · fonts · photography · density'],['Dashboard Builder','Drag · resize · hide · pin'],['World Builder','Kitchen · bedroom · garden · office'],['Intelligence + Privacy','Quiet · balanced · proactive · permissions']].map(([a,b],i)=><button key={a} type="button" onClick={()=>setActive(i)} className={`rounded-[18px] border p-5 text-left ${active===i?'bg-white shadow-md':'bg-white/55'}`}><Settings size={17} style={{color:scene.accent}}/><p className="glow-display mt-3 text-[18px]">{a}</p><p className="mt-2 text-[9px] leading-4 text-[#806e67]">{b}</p></button>)}</div>);

  return shell(<div className="grid gap-3 p-4 md:grid-cols-3">{scene.links.map(([label,href],i)=><Link href={href} key={label} className="rounded-[16px] border bg-white/60 p-5"><Icon size={17} style={{color:scene.accent}}/><p className="glow-display mt-3 text-[18px]">{label}</p><p className="mt-2 text-[8px] text-[#8d7972]">Enter this part of the room <ChevronRight size={9} className="inline"/></p></Link>)}</div>);
}
