'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ArrowRight, CheckCircle2, Sparkles, WandSparkles } from 'lucide-react';
import { getSystemRoom } from '@/lib/intelligence/system-registry';

type RoomUpgrade = {
  hero: string;
  action: string;
  metrics: [string,string][];
  workspace: string[];
  intelligence: string;
  related: [string,string][];
};

const U: Record<string, RoomUpgrade> = {
  tasks:{hero:'Turn everything you need to do into a realistic, ordered day.',action:'Build my day',metrics:[['Top 3','3 priorities'],['Capacity','Balanced'],['Waiting','Review'],['Overdue','Triage']],workspace:['Inbox triage','Today','Upcoming','Waiting on','Someday','Dependencies'],intelligence:'Glow can compare task effort with your calendar and suggest the next action that actually fits.',related:[['Calendar','/calendar'],['Projects','/projects'],['Brain','/brain']]},
  calendar:{hero:'See time as a living plan, not a wall of appointments.',action:'Fix my day',metrics:[['Day load','Balanced'],['Focus space','Protected'],['Conflicts','Check'],['Buffers','On']],workspace:['Today','Week','Month','Year','Timeline','Calendar layers'],intelligence:'Glow can protect travel, preparation, meals, rituals and focus time when the day changes.',related:[['Tasks','/tasks'],['Planning','/planning'],['Food','/food']]},
  planning:{hero:'Connect today, this week and your long-range plans in one strategy studio.',action:'Plan my week',metrics:[['Top three','Ready'],['Week theme','Visible'],['Carry-over','Review'],['Capacity','Plan']],workspace:['Today','Week','Month','Quarter','Year','Sunday Reset'],intelligence:'Glow can pull unfinished work, appointments, routines, food prep and project milestones into one realistic draft.',related:[['Goals','/goals'],['Calendar','/calendar'],['Projects','/projects']]},
  habits:{hero:'Grow consistency with minimum versions, context and gentle recovery.',action:'Rescue today',metrics:[['Habit score','Today'],['Streak health','Steady'],['Minimums','Available'],['Patterns','Learning']],workspace:['Today','Weekly heat map','Monthly trends','Minimum habits','Correlations','History'],intelligence:'Instead of treating missed habits as failure, Glow can choose the smallest useful version and preserve momentum.',related:[['Routines','/planning'],['Wellness','/wellness'],['Fitness','/fitness']]},
  fitness:{hero:'Train around your time, energy, recovery and long-term physique goals.',action:"Build today's workout",metrics:[['Workout','Today'],['Steps','Track'],['Recovery','Check'],['Progress','Growing']],workspace:['Weekly split','Exercise library','Progressive overload','Cardio','Core','Progress photos'],intelligence:'Glow can create a shorter or lower-energy workout while preserving the purpose of the planned session.',related:[['Food','/food'],['Wellness','/wellness'],['Calendar','/calendar']]},
  wellness:{hero:'Turn your energy, sleep, hydration and stress into useful next actions.',action:'I need a reset',metrics:[['Energy','Check in'],['Hydration','Today'],['Sleep','Review'],['Stress','Notice']],workspace:['2-min reset','5-min reset','Midday reset','Recovery','Posture','Supplements'],intelligence:'Glow can lighten the day, recommend a reset and protect recovery when your capacity is lower.',related:[['Fitness','/fitness'],['Food','/food'],['Brain','/brain']]},
  food:{hero:'Plan meals, groceries, pantry, prep and food spending as one connected weekly workflow.',action:'Build my food week',metrics:[['Meals','Plan'],['Groceries','Stock'],['Use soon','Review'],['Budget','On track']],workspace:['Today','Meal Plan','Recipes','Groceries','Pantry','Meal Prep'],intelligence:'Glow can plan around your calendar, use what you already have, generate missing groceries and carry leftovers forward.',related:[['Fitness','/fitness'],['Finance','/finance'],['Home','/home']]},
  beauty:{hero:'Run today’s beauty maintenance from one calm editorial vanity.',action:"Start today's beauty",metrics:[['AM/PM','Scheduled'],['Maintenance','Upcoming'],['Treatments','Rotate'],['Progress','Track']],workspace:['Today','AM routine','PM routine','Body','Gua Sha','Maintenance calendar'],intelligence:'Glow can choose the right routine for tonight and avoid stacking incompatible treatment nights.',related:[['Beauty Lab','/beauty/lab'],['Hair','/hair'],['Wellness','/wellness']]},
  'beauty-lab':{hero:'Know what you own, what works, what is expiring and what deserves a repurchase.',action:'Review my shelf',metrics:[['Inventory','Track'],['Low stock','Review'],['Expiring','Watch'],['Repurchase','Decide']],workspace:['Shelf','Routine map','Expiring','Favorites','Do not repurchase','Wishlist'],intelligence:'Glow can connect products to routines, reactions, cost, usage and replacement timing.',related:[['Beauty','/beauty'],['Finance','/finance'],['Hair','/hair']]},
  hair:{hero:'Manage your complete hair lifecycle from wash day through styling, protection and growth history.',action:'Plan my hair week',metrics:[['Current style','Track'],['Next wash','Forecast'],['Heat','History'],['Growth','Progress']],workspace:['Current state','Morning','Night','Wash Day','Scalp & Ends','Timeline'],intelligence:'Glow can move maintenance around appointments and events while keeping wash, repair and protection cycles intact.',related:[['Beauty','/beauty'],['Calendar','/calendar'],['Beauty Lab','/beauty/lab']]},
  finance:{hero:'Understand where money went and what needs attention without turning finance into a spreadsheet wall.',action:'Review my money',metrics:[['Month','Snapshot'],['Budget','Status'],['Bills','Upcoming'],['Savings','Progress']],workspace:['Transactions','Budget','Bills','Subscriptions','Savings','Spending calendar'],intelligence:'Glow can connect grocery, beauty, closet and project purchases back to the systems that created them.',related:[['Financial Brain','/finance/brain'],['Food','/food'],['Goals','/goals']]},
  'financial-brain':{hero:'Turn money history into forecasts, scenarios and better decisions.',action:'Run a scenario',metrics:[['Cash flow','Forecast'],['Savings','Projection'],['Subscriptions','Review'],['Signals','Notice']],workspace:['Forecast','What if?','Subscriptions','Purchase analyzer','Savings scenarios','Observations'],intelligence:'Ask what changes if you save more, buy something, cancel a subscription or change a monthly category.',related:[['Finance','/finance'],['Goals','/goals'],['Brain','/brain']]},
  goals:{hero:'Turn a beautiful vision into milestones, projects, habits and actions.',action:'Move a goal forward',metrics:[['Active','Goals'],['On track','Health'],['Milestones','Next'],['Evidence','Progress']],workspace:['Vision gallery','Milestones','Supporting habits','Projects','Next action','Goal history'],intelligence:'Glow can reverse-plan from a target date and reveal which project or action moves the goal next.',related:[['Projects','/projects'],['Planning','/planning'],['Habits','/habits']]},
  projects:{hero:'See exactly where each project stands, what is blocked and what should happen next.',action:'Move project forward',metrics:[['Active','Projects'],['Next actions','Ready'],['Blockers','Review'],['Velocity','Trend']],workspace:['Overview','Milestones','Tasks','Decision log','Files','Activity timeline'],intelligence:'Glow can synthesize tasks, deadlines, files and decisions into one next meaningful action.',related:[['Tasks','/tasks'],['Goals','/goals'],['Brain','/brain']]},
  brain:{hero:'Ask one question and let Glow reason across your whole life system.',action:'What should I do now?',metrics:[['Context','Connected'],['Today','Aware'],['Systems','Linked'],['Actions','Ready']],workspace:['Build My Day','Lighten My Day','Plan Tomorrow','What am I neglecting?','Prioritize my week','Explain patterns'],intelligence:'Brain should answer with an executable recommendation and a short explanation of the evidence it used.',related:[['Concierge','/concierge'],['Observations','/observations'],['Dashboard','/dashboard']]},
  concierge:{hero:'Turn decisions into approved actions across Glow OS.',action:'Prepare tomorrow',metrics:[['Proposals','Review'],['Actions','Reversible'],['Recipes','Reusable'],['Approvals','Controlled']],workspace:['Prepare Tomorrow','Sunday Reset','Appointment Prep','Trip Prep','Shopping Prep','Morning Launch'],intelligence:'Concierge is the execution layer: it prepares a plan and performs supported actions after the appropriate approval.',related:[['Brain','/brain'],['Planning','/planning'],['Calendar','/calendar']]},
  observations:{hero:'See useful patterns only when there is evidence and a meaningful next step.',action:'Review what Glow noticed',metrics:[['Active','Notices'],['Confidence','Visible'],['Resolved','History'],['Snoozed','Later']],workspace:['Active','Evidence','Recommended actions','Snoozed','Resolved','Rules'],intelligence:'Every observation should explain why it matters, show evidence and disappear once the underlying issue is resolved.',related:[['Brain','/brain'],['Habits','/habits'],['Projects','/projects']]},
  memory:{hero:'Keep decisions, preferences, moments and lessons searchable without losing control.',action:'Search my memory',metrics:[['Memories','Private'],['Links','Connected'],['Corrections','Available'],['Timeline','Growing']],workspace:['Search','People','Places','Projects','Decisions','Journal memories'],intelligence:'Memory can surface related context inside other rooms while always allowing correction or deletion.',related:[['Timeline','/timeline'],['Notes','/notes'],['Brain','/brain']]},
  timeline:{hero:'Scroll through your life as a layered visual story.',action:'Explore my timeline',metrics:[['Today','Live'],['Milestones','Captured'],['Layers','Filter'],['Compare','Periods']],workspace:['Today','Week','Month','Year','Lifetime','Layer filters'],intelligence:'Compare periods, projects, beauty progress, fitness progress, work and memories without losing the original chronology.',related:[['Memory','/memory'],['Goals','/goals'],['Briefings','/briefings']]},
  briefings:{hero:'Let Glow publish the useful version of your day, week and changes.',action:'Read my briefing',metrics:[['Morning','Ready'],['Midday','Update'],['Night','Close'],['Sunday','Edition']],workspace:['Morning','Midday','Night','Weekly edition','Changes','Tomorrow'],intelligence:'Briefings should synthesize schedule, priorities, habits, food, money, projects, email and observations without forcing you into every room.',related:[['Dashboard','/dashboard'],['Planning','/planning'],['Brain','/brain']]},
  closet:{hero:'Turn your wardrobe into outfits, packing plans and cost-per-wear intelligence.',action:"Build today's outfit",metrics:[['Wardrobe','Inventory'],['Laundry','State'],['Favorites','Ready'],['Wear cost','Track']],workspace:['Closet','Outfits','Laundry','Packing','Wishlist','Donate'],intelligence:'Glow can combine weather, calendar, occasion and clothing state to suggest realistic looks.',related:[['Calendar','/calendar'],['Finance','/finance'],['World','/world']]},
  gmail:{hero:'Turn inbox noise into a short list of messages that actually require attention.',action:'Show what needs me',metrics:[['Needs reply','Triage'],['Action mail','Extract'],['Waiting for','Track'],['Orders','Route']],workspace:['Needs Reply','Needs Action','Information','Orders','Appointments','Waiting For'],intelligence:'Useful messages can become tasks, events, project notes or memories without copying information by hand.',related:[['Tasks','/tasks'],['Calendar','/calendar'],['Projects','/projects']]},
  world:{hero:'Walk through your life as connected rooms while keeping the fast flat interface available.',action:'Enter my world',metrics:[['Rooms','Connected'],['Systems','Live'],['Scenes','Editorial'],['Status','Visible']],workspace:['Bedroom','Vanity','Kitchen','Gym','Office','Library'],intelligence:'The spatial world is an optional visual layer over the same real data, never a separate duplicate system.',related:[['Dashboard','/dashboard'],['Home','/home'],['Memory','/memory']]},
  home:{hero:'Know what needs resetting, what is low and which room deserves attention first.',action:'Plan my home reset',metrics:[['Rooms','Status'],['Supplies','Watch'],['Reset score','Current'],['Maintenance','Upcoming']],workspace:['Bedroom','Bathroom','Kitchen','Closet','Laundry','Car'],intelligence:'Glow can choose the highest-impact 15-minute reset and add low household supplies to shopping.',related:[['Food','/food'],['Tasks','/tasks'],['Calendar','/calendar']]},
  connections:{hero:'See what is connected, what data flows where and what needs attention.',action:'Check sync health',metrics:[['Accounts','Status'],['Sync','Health'],['Permissions','Visible'],['Errors','Actionable']],workspace:['Calendar','Reminders','Gmail','Health','Weather','Data flow map'],intelligence:'Each connection should clearly show what information it contributes and which rooms use it.',related:[['Calendar','/calendar'],['Gmail','/gmail'],['Brain','/brain']]},
  notes:{hero:'Capture first. Organize second. Keep the original thought forever.',action:'Capture anything',metrics:[['Inbox','Ideas'],['Linked','Context'],['Unsorted','Review'],['Original','Preserved']],workspace:['Brain Dump','Ideas','Personal','Projects','Shopping','Unsorted'],intelligence:'Glow can suggest Task, Event, Project, Goal, Memory, Grocery Item or Note without deleting the raw capture.',related:[['Memory','/memory'],['Tasks','/tasks'],['Projects','/projects']]},
  import:{hero:'Bring documents, screenshots, lists and history into Glow without rebuilding them manually.',action:'Import into Glow',metrics:[['Preview','Before create'],['Dedupe','Safe'],['Undo','Available'],['Routing','Smart']],workspace:['PDF','Screenshot','Photo','CSV','Notes','Import history'],intelligence:'Glow should extract structured candidates, show a preview, let you approve, then preserve an undo path.',related:[['Notes','/notes'],['Connections','/connections'],['Brain','/brain']]},
  settings:{hero:'Customize Glow OS from inside Glow OS instead of editing code.',action:'Customize my world',metrics:[['Theme','Editable'],['Widgets','Arrange'],['Privacy','Control'],['Rooms','Personalize']],workspace:['Design Studio','Dashboard Editor','Room Themes','Notifications','AI behavior','Privacy'],intelligence:'You should be able to change imagery, density, typography, colors, widgets and room personality without touching the repository.',related:[['Dashboard','/dashboard'],['World','/world'],['Connections','/connections']]},
};

export function RoomActionConsole(){
  const pathname=usePathname();
  const room=getSystemRoom(pathname);
  if(!room||room.key==='dashboard'||room.key==='today')return null;
  const upgrade=U[room.key];
  if(!upgrade)return null;
  return <section className="mb-5 grid gap-3 xl:grid-cols-[1.25fr_.75fr]">
    <div className="paper-card overflow-hidden p-4 sm:p-5">
      <div className="flex items-start justify-between gap-4">
        <div><p className="text-[8px] font-bold uppercase tracking-[.18em] text-[var(--room-accent,#9c7470)]">DO IT FOR ME</p><h3 className="glow-display mt-1 max-w-2xl text-[20px] leading-tight text-[var(--glow-text)]">{upgrade.hero}</h3></div>
        <WandSparkles size={22} className="shrink-0 text-[var(--room-accent,#a67974)]"/>
      </div>
      <Link href="/brain" className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#2e2824] px-4 py-2 text-[9px] font-semibold text-white shadow-sm transition hover:-translate-y-px"><Sparkles size={11}/>{upgrade.action}<ArrowRight size={11}/></Link>
      <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{upgrade.metrics.map(([label,value])=><div key={label} className="rounded-[12px] border border-white/80 bg-white/50 p-3"><p className="text-[7px] font-bold uppercase tracking-[.14em] text-stone-400">{label}</p><p className="glow-display mt-1 text-[14px] text-stone-800">{value}</p></div>)}</div>
      <div className="mt-4 flex gap-1.5 overflow-x-auto pb-1">{upgrade.workspace.map(item=><span key={item} className="min-w-max rounded-full border border-[var(--glow-border)] bg-white/45 px-2.5 py-1.5 text-[8px] text-stone-600">{item}</span>)}</div>
    </div>
    <div className="paper-card flex flex-col justify-between p-4 sm:p-5">
      <div><div className="flex items-center gap-2"><Sparkles size={12} className="text-[var(--room-accent,#a67974)]"/><p className="text-[8px] font-bold uppercase tracking-[.18em] text-[var(--room-accent,#9c7470)]">Glow intelligence</p></div><p className="mt-3 text-[11px] leading-5 text-stone-600">{upgrade.intelligence}</p></div>
      <div className="mt-5"><p className="mb-2 text-[7px] font-bold uppercase tracking-[.16em] text-stone-400">Connected workflow</p><div className="flex flex-wrap gap-1.5">{upgrade.related.map(([label,href])=><Link key={href} href={href} className="inline-flex items-center gap-1 rounded-full bg-[#f1e5df] px-2.5 py-1.5 text-[8px] text-stone-700">{label}<ArrowRight size={8}/></Link>)}</div><Link href="/intake" className="mt-3 inline-flex items-center gap-1 text-[8px] font-semibold text-[#9a6d6d]">+ Quick add</Link><span className="ml-3 inline-flex items-center gap-1 text-[8px] text-stone-400"><CheckCircle2 size={10}/>History + undo ready</span></div>
    </div>
  </section>;
}
