import {Archive, Plus, Save} from 'lucide-react';
import {archiveUpgradeObjectAction, createUpgradeObjectAction, updateUpgradeObjectAction} from '@/app/actions/glow-upgrade-objects';
import type {UpgradeField} from '@/lib/upgrades/types';

type Item={id:string;title:string;summary:string|null;entityType:string;metadata:Record<string,unknown>};
type Props={room:string;tool:string;items:Item[];entityType?:string;fields?:readonly UpgradeField[]};

function Field({field,value}:{field:UpgradeField;value?:unknown}){
 const name=`meta:${field.key}`,base='w-full rounded-xl border border-[#E9DCD6] bg-white px-3 py-3 text-sm';
 if(field.type==='textarea')return <textarea name={name} rows={3} defaultValue={String(value??'')} placeholder={field.placeholder??field.label} className={base}/>;
 if(field.type==='select')return <select name={name} defaultValue={String(value??'')} className={base}><option value="">{field.label}</option>{(field.options??[]).map(option=><option key={option} value={option}>{option}</option>)}</select>;
 if(field.type==='checkbox')return <label className="flex items-center gap-2 rounded-xl border border-[#E9DCD6] bg-white px-3 py-3 text-sm text-[#655A54]"><input name={name} type="checkbox" defaultChecked={Boolean(value)}/>{field.label}</label>;
 return <input name={name} type={field.type==='number'?'number':field.type==='date'?'date':field.type==='time'?'time':'text'} defaultValue={String(value??'')} required={field.required} placeholder={field.placeholder??field.label} className={base}/>;
}

export function UpgradeObjectManager({room,tool,items,entityType='upgrade_item',fields=[]}:Props){
 return <section className="paper-card rounded-[24px] border border-[#EFE2DC] bg-white p-5 sm:p-6">
  <div className="flex items-center justify-between gap-3"><div><p className="glow-eyebrow">Collection</p><h2 className="glow-display mt-1 text-2xl">Saved items</h2></div><span className="text-xs text-[#9A8B84]">{items.length}</span></div>
  <form action={createUpgradeObjectAction.bind(null,room,tool,entityType)} className="mt-5 rounded-[18px] border border-[#EEE2DD] bg-[#FFF9F7] p-4"><div className="flex items-center gap-2 text-sm font-medium"><Plus size={14} className="text-[#C9727E]"/>Add item</div><input required name="title" placeholder="Title" className="mt-3 w-full rounded-xl border border-[#E9DCD6] bg-white px-3 py-3 text-sm"/><textarea name="summary" rows={3} placeholder="Details, checklist, ingredients, notes, decision, or context…" className="mt-2 w-full rounded-xl border border-[#E9DCD6] bg-white px-3 py-3 text-sm"/>{fields.length?<div className="mt-2 grid gap-2 sm:grid-cols-2">{fields.map(field=><Field key={field.key} field={field}/>)}</div>:<div className="mt-2 grid gap-2 sm:grid-cols-2"><input name="meta:category" placeholder="Category (optional)" className="rounded-xl border border-[#E9DCD6] bg-white px-3 py-3 text-sm"/><input name="meta:date" placeholder="Date / period (optional)" className="rounded-xl border border-[#E9DCD6] bg-white px-3 py-3 text-sm"/></div>}<button className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-full bg-[#C9727E] px-4 text-xs font-semibold text-white"><Plus size={13}/>Add</button></form>
  <div className="mt-4 grid gap-3 md:grid-cols-2">{items.length?items.map(item=><article key={item.id} className="rounded-[18px] border border-[#EEE2DD] bg-[#FFFCFA] p-4"><form action={updateUpgradeObjectAction.bind(null,item.id,room,tool)}><input name="title" defaultValue={item.title} className="w-full border-0 bg-transparent p-0 text-sm font-semibold text-[#342B27] outline-none"/><textarea name="summary" rows={4} defaultValue={item.summary??''} className="mt-2 w-full resize-y rounded-xl border border-[#EEE2DD] bg-white px-3 py-2.5 text-xs leading-5 text-[#766A63]"/>{fields.length?<div className="mt-2 grid gap-2">{fields.map(field=><Field key={field.key} field={field} value={item.metadata?.[field.key]}/>)}</div>:<input name="meta:category" defaultValue={String(item.metadata?.category??'')} placeholder="Category" className="mt-2 w-full rounded-xl border border-[#EEE2DD] bg-white px-3 py-2 text-xs"/>}<button className="mt-3 inline-flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[.1em] text-[#A8636C]"><Save size={11}/>Save</button></form><form action={archiveUpgradeObjectAction.bind(null,item.id,room,tool)}><button className="mt-2 inline-flex items-center gap-1.5 text-[10px] text-[#9A8B84]"><Archive size={11}/>Archive</button></form></article>):<p className="py-6 text-sm text-[#9A8B84]">Nothing saved here yet. Add the first real item above.</p>}</div>
 </section>;
}
