import Link from 'next/link';
import { ArrowLeft, Brain, Save, Search, ShieldCheck, Sparkles, Timer } from 'lucide-react';
import { createUpgradeProposalAction, startUpgradeFocusAction } from '@/app/actions/upgrade-actions';
import { createUpgradeRuleAction } from '@/app/actions/upgrade-rules';
import { saveUpgradeReviewAction } from '@/app/actions/upgrade-reviews';
import { saveUpgradeWorkspaceAction } from '@/app/actions/upgrade-workspace';
import { UpgradeRelationForm } from '@/components/upgrade-relation-form';
import type { UpgradeTool } from '@/lib/intelligence/room-upgrades';

type Entity={id:string;type:string;title:string};
type Props={room:string;tool:UpgradeTool;state?:{title:string;summary:string|null;status:string}|null;entities:Entity[];proposalCount:number;focusCount:number;relationCount:number};

export function UpgradeWorkspace({room,tool,state,entities,proposalCount,focusCount,relationCount}:Props){
  const back=tool.href??'/all-rooms';
  return <div className="mx-auto max-w-5xl space-y-6">
    <div className="flex items-center justify-between gap-4"><Link href={back} className="inline-flex items-center gap-2 text-xs font-medium text-[#9A7C76]"><ArrowLeft size={14}/>Back</Link><span className="glow-eyebrow">Glow Upgrade Workspace</span></div>
    <header className="editorial-surface rounded-[28px] border border-[#EFE2DC] bg-white p-6 sm:p-8">
      <p className="glow-eyebrow">{room.replaceAll('-',' ')}</p><h1 className="glow-display mt-2 text-4xl text-[#2B2420] sm:text-5xl">{tool.label}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#82756D]">{tool.description}</p>
      <div className="mt-5 flex flex-wrap gap-2 text-[10px] uppercase tracking-[.12em] text-[#9A8B84]"><span>{proposalCount} proposals</span><span>·</span><span>{relationCount} connections</span><span>·</span><span>{focusCount} focus sessions</span></div>
      {tool.href?<Link href={tool.href} className="mt-5 inline-flex rounded-full border border-[#E3D4CE] bg-[#FFF9F7] px-4 py-2.5 text-xs font-semibold text-[#A8646D]">Open native Glow feature →</Link>:null}
    </header>

    {tool.mode==='search'?<div className="paper-card rounded-[24px] border border-[#EFE2DC] bg-[#FFF9F6] p-5"><div className="flex items-center gap-2"><Search size={15} className="text-[#C9727E]"/><h2 className="font-medium">Ask Glow</h2></div><p className="mt-2 text-xs text-[#8B7C74]">Search across Glow OS using this upgrade as context.</p><Link href={`/search?q=${encodeURIComponent(tool.label)}`} className="mt-4 inline-flex rounded-full bg-[#302A27] px-4 py-2.5 text-xs font-medium text-white">Search {tool.label}</Link></div>:null}
    {tool.mode==='rule'?<form action={createUpgradeRuleAction} className="paper-card rounded-[24px] border border-[#EFE2DC] bg-[#FFF9F6] p-5"><input type="hidden" name="room" value={room}/><input type="hidden" name="toolId" value={tool.id}/><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#A56B68]"/><h2 className="font-medium">Create Personal Rule</h2></div><input name="title" defaultValue={tool.label} className="mt-3 w-full rounded-xl border border-[#E8DAD4] bg-white px-3 py-3 text-sm"/><textarea name="ruleText" required rows={4} placeholder="Describe exactly how Glow should behave…" className="mt-2 w-full rounded-xl border border-[#E8DAD4] bg-white px-3 py-3 text-sm"/><button className="mt-3 rounded-full bg-[#302A27] px-4 py-2.5 text-xs font-medium text-white">Save rule</button></form>:null}
    {tool.mode==='review'?<form action={saveUpgradeReviewAction} className="paper-card rounded-[24px] border border-[#EFE2DC] bg-[#FFF9F6] p-5"><input type="hidden" name="room" value={room}/><input type="hidden" name="toolId" value={tool.id}/><div className="flex items-center gap-2"><Sparkles size={15} className="text-[#C9727E]"/><h2 className="font-medium">Save Review</h2></div><input type="date" name="dateKey" defaultValue={new Date().toISOString().slice(0,10)} className="mt-3 rounded-xl border border-[#E8DAD4] bg-white px-3 py-2.5 text-sm"/><input name="wins" placeholder="What went well?" className="mt-2 w-full rounded-xl border border-[#E8DAD4] bg-white px-3 py-3 text-sm"/><input name="moved" placeholder="What needs to move or stay open?" className="mt-2 w-full rounded-xl border border-[#E8DAD4] bg-white px-3 py-3 text-sm"/><textarea name="reflection" rows={4} placeholder="Reflection…" className="mt-2 w-full rounded-xl border border-[#E8DAD4] bg-white px-3 py-3 text-sm"/><button className="mt-3 rounded-full bg-[#C9727E] px-4 py-2.5 text-xs font-medium text-white">Save review</button></form>:null}

    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <form action={saveUpgradeWorkspaceAction} className="paper-card rounded-[24px] border border-[#EFE2DC] bg-white p-5 sm:p-6">
        <input type="hidden" name="room" value={room}/><input type="hidden" name="toolId" value={tool.id}/><div className="flex items-center gap-2"><Save size={15} className="text-[#C9727E]"/><h2 className="font-medium text-[#342B27]">Workspace</h2></div>
        <label className="mt-5 block text-[10px] font-semibold uppercase tracking-[.14em] text-[#9A8B84]">Title<input name="title" defaultValue={state?.title??tool.label} className="mt-2 w-full rounded-2xl border border-[#EDE1DC] bg-[#FFFCFA] px-4 py-3 text-sm"/></label><label className="mt-4 block text-[10px] font-semibold uppercase tracking-[.14em] text-[#9A8B84]">Notes / plan<textarea name="notes" defaultValue={state?.summary??''} rows={9} className="mt-2 w-full resize-y rounded-2xl border border-[#EDE1DC] bg-[#FFFCFA] px-4 py-3 text-sm leading-6"/></label><input type="hidden" name="status" value="active"/><button className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-full bg-[#C9727E] px-5 text-sm font-medium text-white"><Save size={14}/>Save workspace</button>
      </form>
      <div className="space-y-5"><form action={createUpgradeProposalAction} className="paper-card rounded-[24px] border border-[#EFE2DC] bg-[#FFF8F6] p-5"><input type="hidden" name="room" value={room}/><input type="hidden" name="toolId" value={tool.id}/><div className="flex items-center gap-2"><Sparkles size={15} className="text-[#C9727E]"/><h2 className="font-medium">Ask Glow to propose</h2></div><textarea name="summary" rows={3} placeholder={`What should Glow propose for ${tool.label}?`} className="mt-3 w-full rounded-2xl border border-[#E9D8D4] bg-white px-4 py-3 text-sm"/><input name="reason" placeholder="Why this matters" className="mt-2 w-full rounded-2xl border border-[#E9D8D4] bg-white px-4 py-3 text-sm"/><button className="mt-3 rounded-full border border-[#DDB9BA] bg-white px-4 py-2.5 text-xs font-semibold text-[#A85F69]"><Brain size={13} className="mr-1 inline"/>Create approval proposal</button></form><form action={startUpgradeFocusAction} className="paper-card rounded-[24px] border border-[#EFE2DC] bg-white p-5"><input type="hidden" name="room" value={room}/><input type="hidden" name="toolId" value={tool.id}/><div className="flex items-center gap-2"><Timer size={15} className="text-[#A88B63]"/><h2 className="font-medium">Focus on this</h2></div><div className="mt-3 flex gap-2"><input type="number" min="1" max="480" name="plannedMinutes" defaultValue="25" className="min-w-0 flex-1 rounded-full border border-[#EDE1DC] px-4 py-2 text-sm"/><button className="rounded-full bg-[#302A27] px-4 text-xs font-medium text-white">Start session</button></div></form></div>
    </div>
    <UpgradeRelationForm room={room} toolId={tool.id} entities={entities}/>
  </div>;
}
