'use client';

import { useMemo, useState, useTransition } from 'react';
import Link from 'next/link';
import { Archive, ArrowRight, Check, CheckCircle2, ChevronRight, Circle, MoonStar, Sparkles, WandSparkles } from 'lucide-react';
import { closeEveningAction, moveTaskToTomorrowAction, saveEveningReflectionAction } from '@/app/actions/evening-debrief';
import { deleteTaskAction } from '@/app/actions/tasks';

type TaskLite = { id:string; title:string; priority:string; completed:boolean };
type EventLite = { id:string; title:string; startAt:string; allDay:boolean };
type Props = {
  modeName:string;
  completed:TaskLite[];
  open:TaskLite[];
  todayEvents:number;
  habitsDone:number;
  habitsTotal:number;
  focusMinutes:number;
  tomorrowEvents:EventLite[];
  alreadyClosed:boolean;
};

type Feeling = 'Great'|'Good'|'Okay'|'Hard';
const PREP_STEPS = ['Put clothes out','Pack bag','Charge devices','Fill water','Check first appointment','Beauty prep'];
function timeLabel(value:string){return new Date(value).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}

export function NightlyIntelligenceBriefing({modeName,completed,open,todayEvents,habitsDone,habitsTotal,focusMinutes,tomorrowEvents,alreadyClosed}:Props){
  const [preparing,setPreparing]=useState(false);
  const [prepDone,setPrepDone]=useState<string[]>([]);
  const [feeling,setFeeling]=useState<Feeling|null>(null);
  const [reflection,setReflection]=useState('');
  const [patternApplied,setPatternApplied]=useState(false);
  const [draftAccepted,setDraftAccepted]=useState(false);
  const [carryAccepted,setCarryAccepted]=useState(false);
  const [isPending,startTransition]=useTransition();

  const firstTomorrow=tomorrowEvents[0]??null;
  const carry=useMemo(()=>open.slice(0,3),[open]);
  const tomorrowDraft=useMemo(()=>open.slice(0,3),[open]);
  const importantDone=completed.slice(0,4);
  const estimatedPrep=PREP_STEPS.length*2;
  const morningNeed=58;
  const availableBeforeFirst=firstTomorrow&&!firstTomorrow.allDay?Math.max(20,Math.min(120,new Date(firstTomorrow.startAt).getHours()*60+new Date(firstTomorrow.startAt).getMinutes()-7*60)):90;
  const needsQuick=availableBeforeFirst<morningNeed;
  const narrative=completed.length?`You completed ${completed.length} important ${completed.length===1?'action':'actions'} and still have ${open.length} open ${open.length===1?'item':'items'}. Glow is separating what truly carries forward from what can leave your head tonight.`:'Today can close without forcing a completion score. Glow is keeping only what still needs a decision.';
  const pattern=focusMinutes>0?`You logged ${focusMinutes} minutes of focused work today. Protecting shorter, clearly bounded focus blocks is worth repeating.`:habitsTotal>0&&habitsDone>=Math.ceil(habitsTotal*.6)?`You completed ${habitsDone} of ${habitsTotal} tracked habits. Keep tomorrow’s routine simple enough to preserve that consistency.`:`Your unfinished list is the clearest signal tonight. Tomorrow should start with fewer visible priorities, not a larger list.`;

  function togglePrep(step:string){setPrepDone(current=>current.includes(step)?current.filter(item=>item!==step):[...current,step])}
  function acceptCarry(){startTransition(async()=>{for(const task of carry){const fd=new FormData();fd.set('taskId',task.id);await moveTaskToTomorrowAction(fd)}setCarryAccepted(true)})}
  function archiveTask(id:string){startTransition(async()=>{await deleteTaskAction(id)})}
  function acceptDraft(){const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);window.localStorage.setItem('glow-tomorrow-top3',JSON.stringify({date:tomorrow.toISOString().slice(0,10),titles:tomorrowDraft.map(item=>item.title)}));setDraftAccepted(true)}
  function applyPattern(){window.localStorage.setItem('glow-evening-pattern','Prefer shorter routines and fewer visible evening priorities.');setPatternApplied(true)}

  if(alreadyClosed){return <div className="mx-auto max-w-4xl pb-24"><section className="min-h-[72vh] rounded-[38px] border border-[#4d4657] bg-[radial-gradient(circle_at_top,#5d536b,#2e2937_58%,#211e28)] p-8 text-center text-[#f7f2f8] shadow-[0_30px_100px_rgba(28,22,36,.3)] sm:p-12"><div className="mx-auto mt-20 max-w-xl"><MoonStar size={24} className="mx-auto text-[#d9cce2]"/><p className="mt-6 text-[10px] uppercase tracking-[.18em] text-[#c7b9d1]">Today is closed</p><h1 className="mt-3 font-serif text-5xl sm:text-6xl">Tomorrow is prepared.</h1><p className="mt-5 text-sm leading-7 text-[#cfc5d4]">{firstTomorrow?`First fixed item: ${firstTomorrow.title} · ${firstTomorrow.allDay?'All day':timeLabel(firstTomorrow.startAt)}`:'Tomorrow currently has open space.'}</p><div className="mt-8 flex flex-wrap justify-center gap-2"><Link href="/ambient-mode" className="rounded-full bg-white px-5 py-3 text-sm text-[#352f3e]">Enter Ambient Mode</Link><Link href="/dashboard" className="rounded-full border border-white/25 px-5 py-3 text-sm">Dashboard</Link></div><p className="mt-12 font-serif text-2xl italic text-[#d8ccdf]">Sleep well.</p></div></section></div>}

  if(preparing){return <div className="mx-auto max-w-4xl pb-24"><section className="min-h-[72vh] rounded-[38px] border border-[#4d4657] bg-[radial-gradient(circle_at_top,#5a5068,#2e2938_62%,#24202b)] p-6 text-[#f7f2f8] sm:p-10"><div className="flex items-center justify-between"><p className="text-[10px] uppercase tracking-[.18em] text-[#c4b5ce]">Prepare Tomorrow · {prepDone.length}/{PREP_STEPS.length}</p><button type="button" onClick={()=>setPreparing(false)} className="text-xs text-[#cfc4d5]">Exit</button></div><div className="mx-auto mt-14 max-w-xl"><h1 className="font-serif text-5xl">Make tomorrow easier.</h1><p className="mt-3 text-sm text-[#c9becf]">About {estimatedPrep} minutes. Tap each item as you finish it.</p><div className="mt-8 space-y-3">{PREP_STEPS.map(step=><button type="button" key={step} onClick={()=>togglePrep(step)} className={`flex w-full items-center gap-3 rounded-[20px] border px-5 py-4 text-left ${prepDone.includes(step)?'border-[#8d7aa0] bg-white/12':'border-white/10 bg-white/5'}`}>{prepDone.includes(step)?<CheckCircle2 size={17}/>:<Circle size={17}/>}<span>{step}</span></button>)}</div><button type="button" onClick={()=>setPreparing(false)} className="mt-7 w-full rounded-full bg-[#f3eef5] px-5 py-3 text-sm text-[#352f3d]">{prepDone.length===PREP_STEPS.length?'Prep complete':'Done for now'}</button></div></section></div>}

  return <div className="mx-auto max-w-[1240px] space-y-7 pb-24 text-[#efeaf1]">
    <section className="relative overflow-hidden rounded-[38px] border border-[#4f4858] bg-[radial-gradient(circle_at_80%_5%,rgba(122,101,143,.55),transparent_30%),radial-gradient(circle_at_55%_0%,rgba(84,72,103,.7),transparent_35%),linear-gradient(145deg,#332e3d,#25212d)] p-6 shadow-[0_34px_110px_rgba(23,18,30,.32)] sm:p-10"><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#bcaec6]">Glow Night · {modeName}</p><h1 className="mt-3 font-serif text-5xl leading-none tracking-[-.04em] sm:text-6xl">Your day is almost done.</h1><p className="mt-3 text-sm text-[#c7bacd]">{new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})} · {new Date().toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</p><p className="mt-5 max-w-2xl text-[15px] leading-7 text-[#d4cad9]">{completed.length>0?'The important things are becoming clear.':'You do not need to manufacture productivity before bed.'} {open.length} {open.length===1?'thing needs':'things need'} a decision before tomorrow.</p><div className="mt-6 flex flex-wrap gap-2"><form action={closeEveningAction}><button className="rounded-full bg-[#f1edf3] px-5 py-3 text-sm text-[#332e3c]">Close My Day</button></form><button type="button" onClick={()=>setPreparing(true)} className="rounded-full border border-white/20 bg-white/7 px-5 py-3 text-sm">Prepare Tomorrow</button><Link href="/concierge" className="rounded-full border border-white/20 bg-white/7 px-5 py-3 text-sm">Ask Glow</Link></div></div><div className="rounded-[28px] border border-white/10 bg-white/7 p-5 backdrop-blur"><p className="text-[10px] uppercase tracking-[.16em] text-[#b7aabe]">Tonight at a glance</p><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="font-serif text-3xl">{completed.length}</p><p className="text-[10px] text-[#bcb1c2]">Completed</p></div><div><p className="font-serif text-3xl">{open.length}</p><p className="text-[10px] text-[#bcb1c2]">Open</p></div><div><p className="font-serif text-3xl">{habitsDone}/{habitsTotal}</p><p className="text-[10px] text-[#bcb1c2]">Habits</p></div><div><p className="font-serif text-3xl">{focusMinutes||'—'}</p><p className="text-[10px] text-[#bcb1c2]">Focus min</p></div></div></div></div></section>

    <section className="rounded-[30px] border border-[#48424f] bg-[#2b2732] p-5 sm:p-7"><p className="text-[10px] uppercase tracking-[.16em] text-[#aa9db3]">What happened today</p><h2 className="mt-2 font-serif text-3xl">A clean summary, not a score.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-[#c6bbc9]">{narrative}</p><div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-[18px] bg-white/5 p-4"><p className="font-serif text-2xl">{todayEvents}</p><p className="mt-1 text-[10px] text-[#a99fac]">Calendar items</p></div><div className="rounded-[18px] bg-white/5 p-4"><p className="font-serif text-2xl">{completed.length}</p><p className="mt-1 text-[10px] text-[#a99fac]">Tasks done</p></div><div className="rounded-[18px] bg-white/5 p-4"><p className="font-serif text-2xl">{habitsDone}</p><p className="mt-1 text-[10px] text-[#a99fac]">Habits logged</p></div><div className="rounded-[18px] bg-white/5 p-4"><p className="font-serif text-2xl">{focusMinutes?`${focusMinutes}m`:'—'}</p><p className="mt-1 text-[10px] text-[#a99fac]">Focused work</p></div></div></section>

    <section className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]">
      <div className="rounded-[30px] border border-[#48424f] bg-[#2b2732] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#aa9db3]">Intelligent unfinished items</p><h2 className="mt-1 font-serif text-2xl">Carry only what still matters.</h2></div>{carryAccepted?<span className="rounded-full bg-[#4d5c47] px-3 py-1.5 text-xs">Moved</span>:null}</div><div className="mt-5 space-y-3">{carry.length?carry.map((task,index)=><div key={task.id} className="rounded-[18px] border border-white/7 bg-white/4 p-4"><div className="flex items-start gap-3"><Circle size={14} className="mt-1 shrink-0 text-[#a99ab3]"/><div className="min-w-0 flex-1"><Link href={`/tasks?taskId=${encodeURIComponent(task.id)}&view=all`} className="text-sm text-[#eee9f0]">{task.title}</Link><p className="mt-1 text-[11px] text-[#9f94a6]">{index===0?'Glow recommends: move to tomorrow':task.priority==='low'?'Glow recommends: review or archive':'Glow recommends: carry forward only if still relevant'}</p></div><div className="flex gap-2"><form action={moveTaskToTomorrowAction}><input type="hidden" name="taskId" value={task.id}/><button className="text-[10px] text-[#cbbcd3]">Move</button></form>{task.priority==='low'?<button type="button" onClick={()=>archiveTask(task.id)} className="text-[10px] text-[#a9939f]">Archive</button>:null}</div></div></div>):<p className="py-6 text-sm text-[#a99fac]">Your unfinished list is clear.</p>}</div>{carry.length?<button type="button" onClick={acceptCarry} disabled={isPending} className="mt-5 rounded-full bg-[#eee9f0] px-4 py-2.5 text-xs text-[#342f3b] disabled:opacity-50">Accept recommendations</button>:null}</div>

      <div className="rounded-[30px] border border-[#48424f] bg-[#2b2732] p-5 sm:p-7"><p className="text-[10px] uppercase tracking-[.16em] text-[#aa9db3]">Tomorrow reality check</p><h2 className="mt-1 font-serif text-2xl">Tomorrow</h2>{firstTomorrow?<div className="mt-5 rounded-[20px] bg-white/5 p-4"><p className="text-[10px] text-[#9f94a6]">First event</p><p className="mt-1 font-serif text-2xl">{firstTomorrow.title}</p><p className="mt-1 text-xs text-[#b4a8ba]">{firstTomorrow.allDay?'All day':timeLabel(firstTomorrow.startAt)}</p></div>:<div className="mt-5 rounded-[20px] bg-white/5 p-4 text-sm text-[#b4a8ba]">No fixed first event yet. Glow can protect a slower morning.</div>}<div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-[18px] bg-white/4 p-4"><p className="text-[10px] text-[#9f94a6]">Morning plan</p><p className="mt-1 font-serif text-2xl">{morningNeed}m</p></div><div className="rounded-[18px] bg-white/4 p-4"><p className="text-[10px] text-[#9f94a6]">Available</p><p className="mt-1 font-serif text-2xl">{availableBeforeFirst}m</p></div></div>{needsQuick?<p className="mt-4 rounded-[18px] bg-[#453a4d] p-4 text-sm leading-6 text-[#d6c9dc]">Your current morning plan is longer than the available window. Create a Quick Morning before bed.</p>:<p className="mt-4 rounded-[18px] bg-[#343b34] p-4 text-sm leading-6 text-[#cbd5c8]">Tomorrow morning currently fits with buffer.</p>}<Link href="/briefings/morning" className="mt-4 inline-flex items-center gap-1 text-xs text-[#cbbcd3]">Preview Morning Briefing <ChevronRight size={13}/></Link></div>
    </section>

    <section className="grid gap-5 lg:grid-cols-2">
      <div className="rounded-[30px] border border-[#48424f] bg-[#2b2732] p-5 sm:p-7"><p className="text-[10px] uppercase tracking-[.16em] text-[#aa9db3]">Make tomorrow easier</p><h2 className="mt-1 font-serif text-2xl">Preparation · about {estimatedPrep} min</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{PREP_STEPS.map(step=><button type="button" key={step} onClick={()=>togglePrep(step)} className={`flex items-center gap-2 rounded-[16px] border px-4 py-3 text-left text-sm ${prepDone.includes(step)?'border-[#756681] bg-[#42394b]':'border-white/7 bg-white/4'}`}>{prepDone.includes(step)?<Check size={13}/>:<Circle size={13}/>} {step}</button>)}</div><button type="button" onClick={()=>setPreparing(true)} className="mt-5 rounded-full bg-[#eee9f0] px-4 py-2.5 text-xs text-[#342f3b]">Start Prep</button></div>
      <div className="rounded-[30px] border border-[#48424f] bg-[#2b2732] p-5 sm:p-7"><p className="text-[10px] uppercase tracking-[.16em] text-[#aa9db3]">Worth noticing</p><h2 className="mt-1 font-serif text-2xl">Real wins from today</h2><div className="mt-4 space-y-3">{importantDone.length?importantDone.map(task=><div key={task.id} className="flex gap-3 rounded-[16px] bg-white/4 p-4"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-[#9dad96]"/><p className="text-sm text-[#d7cfd9]">You finished {task.title}.</p></div>):<div className="rounded-[16px] bg-white/4 p-4 text-sm leading-6 text-[#b8adbD]">Tonight’s win may be simply closing the loop and preparing a lighter tomorrow.</div>}</div></div>
    </section>

    <section className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]">
      <div className="rounded-[30px] border border-[#48424f] bg-[#2b2732] p-5 sm:p-7"><p className="text-[10px] uppercase tracking-[.16em] text-[#aa9db3]">Reflection without homework</p><h2 className="mt-1 font-serif text-2xl">How did today feel?</h2><div className="mt-4 flex flex-wrap gap-2">{(['Great','Good','Okay','Hard'] as Feeling[]).map(item=><button type="button" key={item} onClick={()=>setFeeling(item)} className={`rounded-full px-4 py-2 text-sm ${feeling===item?'bg-[#eee9f0] text-[#342f3b]':'border border-white/10 text-[#c9becf]'}`}>{item}</button>)}</div><form action={saveEveningReflectionAction} className="mt-5"><input type="hidden" name="wentWell" value={reflection}/><input type="hidden" name="proudOf" value={feeling?`Day felt: ${feeling}`:''}/><input type="hidden" name="feltDifficult" value=""/><input type="hidden" name="doDifferently" value=""/><textarea value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="Optional: What made today easier or harder?" className="min-h-28 w-full rounded-[18px] border border-white/8 bg-white/5 p-4 text-sm text-[#eee9f0] outline-none placeholder:text-[#817687]"/><button className="mt-3 rounded-full border border-white/12 px-4 py-2.5 text-xs">Save reflection</button></form></div>
      <div className="rounded-[30px] border border-[#48424f] bg-[radial-gradient(circle_at_top_right,#4a3d55,transparent_40%),#2b2732] p-5 sm:p-7"><div className="flex items-center gap-2"><Sparkles size={15} className="text-[#c4b4ce]"/><p className="text-[10px] uppercase tracking-[.16em] text-[#aa9db3]">Glow pattern</p></div><h2 className="mt-3 font-serif text-2xl">One useful thing to carry forward</h2><p className="mt-3 text-sm leading-7 text-[#c5bac9]">{pattern}</p><button type="button" onClick={applyPattern} className="mt-5 rounded-full border border-white/12 px-4 py-2.5 text-xs">{patternApplied?'Saved for this device':'Use This Going Forward'}</button></div>
    </section>

    <section className="rounded-[30px] border border-[#48424f] bg-[#2b2732] p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#aa9db3]">Tomorrow’s Top 3 draft</p><h2 className="mt-1 font-serif text-2xl">Give Morning Briefing a starting point.</h2></div>{draftAccepted?<span className="inline-flex items-center gap-1 rounded-full bg-[#455242] px-3 py-1.5 text-xs"><Check size={12}/>Accepted</span>:null}</div><div className="mt-5 grid gap-3 md:grid-cols-3">{tomorrowDraft.length?tomorrowDraft.map((task,index)=><div key={task.id} className="rounded-[18px] bg-white/5 p-4"><p className="text-[10px] text-[#978b9e]">0{index+1}</p><p className="mt-2 text-sm text-[#eee9f0]">{task.title}</p></div>):<div className="text-sm text-[#aaa0ae]">No open tasks to draft yet.</div>}</div><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={acceptDraft} disabled={!tomorrowDraft.length} className="rounded-full bg-[#eee9f0] px-4 py-2.5 text-xs text-[#342f3b] disabled:opacity-40">Accept for tomorrow</button><Link href="/tasks" className="rounded-full border border-white/12 px-4 py-2.5 text-xs">Edit</Link><Link href="/briefings/morning" className="rounded-full border border-white/12 px-4 py-2.5 text-xs">Decide in morning</Link></div></section>

    <section className="rounded-[34px] border border-[#4b4453] bg-[linear-gradient(145deg,#302a39,#24202b)] p-6 sm:p-9"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2"><MoonStar size={16} className="text-[#bdafc6]"/><p className="text-[10px] uppercase tracking-[.16em] text-[#aa9db3]">Finish Day</p></div><h2 className="mt-3 font-serif text-3xl">Close the mental tabs.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#c3b8c7]">Closing the day generates the evening briefing record, keeps tomorrow visible, and gives you a clean exit into Ambient Mode.</p></div><form action={closeEveningAction}><button className="rounded-full bg-[#f2edf4] px-6 py-3 text-sm text-[#322d3a]">Finish Day</button></form></div></section>

    <section className="rounded-[24px] border border-[#48424f] bg-[#29252f] px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-[#a89cad]">Night prepares → Morning decides → Dashboard executes → Night learns</p><Link href="/dashboard" className="inline-flex items-center gap-1 text-xs text-[#c8bbcF]">Dashboard <ChevronRight size={13}/></Link></div></section>
  </div>
}
