'use client';

import { useEffect, useMemo, useRef, useState, useTransition } from 'react';
import { AudioLines, BrainCircuit, ExternalLink, FileVideo2, Link2, LoaderCircle, MessageCircleQuestion, Search, Sparkles, Upload } from 'lucide-react';
import { createNoteAction } from '@/app/actions/notes';
import { transcribeMediaFile } from '@/lib/notes/long-media-client';

type Source={id:string;title:string;sourceType:string;sourceUrl:string|null;platform:string|null;mimeType:string|null;status:string;error:string|null;createdAt:string|Date};
type Chunk={chunkIndex:number;startSeconds:number|null;endSeconds:number|null;text:string;analysis:string|null};
type Analysis={summary:string|null;keyPoints:string[];decisions:string[];actionItems:string[];questions:string[];themes:string[];status:string}|null;
type Question={id:string;question:string;answer:string;evidence:Array<{chunkIndex:number;quote:string}>;createdAt:string|Date};

function fmt(seconds:number|null){if(seconds==null)return'';const m=Math.floor(seconds/60),s=seconds%60;return `${m}:${String(s).padStart(2,'0')}`}
export function NotesTranscriptIntelligence(){
 const [sources,setSources]=useState<Source[]>([]);const [selectedId,setSelectedId]=useState('');const [chunks,setChunks]=useState<Chunk[]>([]);const [analysis,setAnalysis]=useState<Analysis>(null);const [questions,setQuestions]=useState<Question[]>([]);const [link,setLink]=useState('');const [ask,setAsk]=useState('');const [answer,setAnswer]=useState<{answer:string;evidence:Array<{chunkIndex:number;quote:string}>}|null>(null);const [apiKey,setApiKey]=useState('');const [showKey,setShowKey]=useState(false);const [busy,setBusy]=useState('');const [progress,setProgress]=useState(0);const [notice,setNotice]=useState('');const [pending,startTransition]=useTransition();const fileRef=useRef<HTMLInputElement|null>(null);
 const selected=useMemo(()=>sources.find(x=>x.id===selectedId)??null,[sources,selectedId]);const transcript=useMemo(()=>chunks.map(c=>c.text).join('\n\n'),[chunks]);
 useEffect(()=>{try{setApiKey(localStorage.getItem('glow-notes-openai-key')??'')}catch{} void refreshSources()},[]);
 useEffect(()=>{if(!selectedId){setChunks([]);setAnalysis(null);setQuestions([]);return}void loadSource(selectedId)},[selectedId]);
 useEffect(()=>{if(!notice)return;const t=window.setTimeout(()=>setNotice(''),5000);return()=>window.clearTimeout(t)},[notice]);
 async function refreshSources(){const res=await fetch('/api/notes/transcripts',{cache:'no-store'});const json=await res.json();if(res.ok){const list=json.data.sources as Source[];setSources(list);setSelectedId(x=>x||list[0]?.id||'')}}
 async function loadSource(id:string){const res=await fetch(`/api/notes/transcripts?sourceId=${encodeURIComponent(id)}`,{cache:'no-store'});const json=await res.json();if(res.ok){setChunks(json.data.chunks??[]);setAnalysis(json.data.analysis??null);setQuestions(json.data.questions??[])}}
 function headers(){return apiKey?{'x-glow-ai-key':apiKey}:{} as Record<string,string>}
 function saveKey(value:string){setApiKey(value);try{if(value)localStorage.setItem('glow-notes-openai-key',value);else localStorage.removeItem('glow-notes-openai-key')}catch{}}
 async function importFile(file:File){setBusy('file');setProgress(0);setAnswer(null);try{const sourceId=await transcribeMediaFile(file,apiKey||undefined,(message,ratio)=>{setNotice(message);setProgress(ratio)});await refreshSources();setSelectedId(sourceId);await loadSource(sourceId);setNotice('Every processed part is stored in order. You can analyze or ask questions now.')}catch(error){setNotice(error instanceof Error?error.message:'Could not transcribe this file.')}finally{setBusy('');setProgress(0)}}
 async function importLink(){const url=link.trim();if(!url)return;setBusy('link');setAnswer(null);try{const res=await fetch('/api/notes/url-import',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({url})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Could not import this link.');setLink('');await refreshSources();setSelectedId(json.data.sourceId);await loadSource(json.data.sourceId);setNotice(`${json.data.platform||'Video'} transcript imported.`)}catch(error){setNotice(error instanceof Error?error.message:'Could not import this link.')}finally{setBusy('')}}
 async function analyze(){if(!selectedId)return;setBusy('analyze');try{const res=await fetch('/api/notes/analyze-transcript',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({sourceId:selectedId})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Analysis failed.');setAnalysis(json.data);setNotice('Glow analyzed the complete stored transcript, section by section.')}catch(error){setNotice(error instanceof Error?error.message:'Analysis failed.')}finally{setBusy('')}}
 async function askTranscript(){const q=ask.trim();if(!selectedId||!q)return;setBusy('ask');try{const res=await fetch('/api/notes/ask-transcript',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({sourceId:selectedId,question:q})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Could not answer.');setAnswer(json.data);setAsk('');await loadSource(selectedId)}catch(error){setNotice(error instanceof Error?error.message:'Could not answer.')}finally{setBusy('')}}
 function saveAsNote(){if(!selected)return;const content=[`# Transcript Intelligence`,`Source: ${selected.sourceUrl??selected.title}`,analysis?.summary?`\n## Analysis\n${analysis.summary}`:'',analysis?.keyPoints?.length?`\n## Key Points\n${analysis.keyPoints.map(x=>`- ${x}`).join('\n')}`:'',analysis?.decisions?.length?`\n## Decisions\n${analysis.decisions.map(x=>`- ${x}`).join('\n')}`:'',analysis?.actionItems?.length?`\n## Action Items\n${analysis.actionItems.map(x=>`- ${x}`).join('\n')}`:'',`\n## Transcript\n${transcript}`].filter(Boolean).join('\n');startTransition(async()=>{const result=await createNoteAction({title:selected.title,content,tags:['smart-note','transcript',`transcript-source:${selected.id}`,selected.platform?`source:${selected.platform}`:'source:upload'],pinned:false});setNotice(result.data?'Saved as a searchable Smart Note.':'Could not save Smart Note.');})}
 return <section className="mx-auto max-w-[1420px] space-y-4 rounded-[30px] border border-[#e8dfd7] bg-[radial-gradient(circle_at_top_left,#fffdf9,#f4eee8_48%,#efe9f1)] p-4 shadow-[0_22px_70px_rgba(74,58,51,.06)] sm:p-6">
  {notice?<div role="status" className="fixed left-1/2 top-5 z-[300] max-w-[92vw] -translate-x-1/2 rounded-full border border-[#e5dbd3] bg-white px-4 py-2.5 text-center text-[10px] shadow-xl">{notice}</div>:null}
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[8px] font-semibold uppercase tracking-[.18em] text-[#8c7d73]">Transcript Intelligence</p><h2 className="mt-1 font-serif text-[34px] text-[#403b37] sm:text-[44px]">Import it. Transcribe every part. Ask it anything.</h2><p className="mt-2 max-w-3xl text-[9.5px] leading-5 text-[#7f746c]">Uploaded audio/video is stored as ordered transcript chunks. Long files have no preset minute cutoff: Glow splits decodable media into sequential audio parts. Public YouTube captions can import directly. TikTok/Instagram are supported when the public page exposes a fetchable media stream.</p></div><button onClick={()=>setShowKey(x=>!x)} className="rounded-full border border-[#ded4cc] bg-white/70 px-4 py-2.5 text-[9px]">{apiKey?'AI provider connected on this device':'Transcription Settings'}</button></div>
  {showKey?<div className="rounded-[20px] border border-[#e4dad2] bg-white/75 p-4"><p className="text-[9px] font-semibold">AI / transcription provider</p><p className="mt-1 text-[8.5px] leading-4 text-[#81766e]">If Vercel already has <code>OPENAI_API_KEY</code>, you can leave this empty. Otherwise paste your own OpenAI API key here. Glow stores it only in this browser's localStorage and sends it to Glow's authenticated proxy for transcription/analysis. Public YouTube caption import does not require a key.</p><input type="password" value={apiKey} onChange={e=>saveKey(e.target.value.trim())} placeholder="sk-…" className="mt-3 w-full rounded-xl border border-[#e3d9d1] bg-white px-3 py-2.5 text-[10px]"/><button onClick={()=>saveKey('')} className="mt-2 text-[8px] font-semibold text-[#8c6d75]">Clear device key</button></div>:null}
  <div className="grid gap-3 lg:grid-cols-2"><div className="rounded-[22px] border border-white/80 bg-white/68 p-4"><div className="flex items-center gap-2"><Upload size={15}/><b className="text-[10px]">Transcribe a file</b></div><p className="mt-2 text-[8.5px] leading-4 text-[#847a72]">Audio, Voice Memo, MP3, M4A, WAV, MP4, MOV and other browser-decodable audio/video. Files under 23 MB go directly. Larger files are decoded and sent as 8-minute WAV chunks.</p><input ref={fileRef} className="hidden" type="file" accept="audio/*,video/*" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.currentTarget.value=''}}/><button disabled={Boolean(busy)} onClick={()=>fileRef.current?.click()} className="mt-3 rounded-full bg-[#49433f] px-4 py-2.5 text-[9px] text-white disabled:opacity-40"><FileVideo2 size={12} className="mr-1 inline"/>{busy==='file'?'Transcribing…':'Choose audio or video'}</button>{busy==='file'?<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#eee7e1]"><div className="h-full bg-[#8a7783] transition-all" style={{width:`${Math.max(3,progress*100)}%`}}/></div>:null}</div>
   <div className="rounded-[22px] border border-white/80 bg-white/68 p-4"><div className="flex items-center gap-2"><Link2 size={15}/><b className="text-[10px]">Paste a video link</b></div><p className="mt-2 text-[8.5px] leading-4 text-[#847a72]">YouTube, TikTok, Instagram, or another public video page. Glow imports public captions/media only. It will not bypass a login, private account, DRM, or other access restriction.</p><div className="mt-3 flex gap-2"><input value={link} onChange={e=>setLink(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void importLink()}} placeholder="https://youtube.com/…" className="min-w-0 flex-1 rounded-xl border border-[#e3d9d1] px-3 py-2.5 text-[9px]"/><button disabled={Boolean(busy)||!link.trim()} onClick={()=>void importLink()} className="rounded-xl bg-[#756572] px-4 text-[9px] text-white disabled:opacity-40">{busy==='link'?'Importing…':'Import'}</button></div><a href="https://accuratescribe.ai/transcribe" target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-[8px] font-semibold text-[#7b6874]">Large/blocked-source fallback: AccurateScribe <ExternalLink size={9}/></a></div></div>
  <div className="grid gap-4 xl:grid-cols-[.36fr_.64fr]"><div className="rounded-[22px] border border-[#e7ddd5] bg-[#fffdfa] p-4"><div className="flex items-center justify-between"><b className="text-[10px]">Transcript Library</b><Search size={13}/></div><div className="mt-3 max-h-[430px] space-y-2 overflow-y-auto">{sources.length?sources.map(s=><button key={s.id} onClick={()=>setSelectedId(s.id)} className={`w-full rounded-[15px] p-3 text-left ${selectedId===s.id?'bg-[#ece5ee]':'bg-[#f8f4ef]'}`}><div className="flex items-start justify-between gap-2"><b className="line-clamp-2 text-[9px]">{s.title}</b><span className="rounded-full bg-white px-2 py-1 text-[7px] capitalize">{s.platform??s.sourceType}</span></div><p className="mt-1 text-[7.5px] capitalize text-[#8f837b]">{s.status}</p></button>):<p className="rounded-[14px] border border-dashed p-4 text-[8.5px] text-[#92867d]">Your transcribed videos and recordings will appear here.</p>}</div></div>
   <div className="space-y-3">{selected?<><div className="rounded-[22px] border border-[#e7ddd5] bg-[#fffdfa] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[7.5px] uppercase tracking-[.14em] text-[#8d8077]">{selected.platform??selected.sourceType} · {chunks.length} transcript part{chunks.length===1?'':'s'}</p><h3 className="mt-1 font-serif text-[26px]">{selected.title}</h3></div><div className="flex flex-wrap gap-2"><button disabled={busy==='analyze'||!chunks.length} onClick={()=>void analyze()} className="rounded-full bg-[#6f6578] px-4 py-2 text-[8.5px] text-white disabled:opacity-40"><BrainCircuit size={11} className="mr-1 inline"/>{busy==='analyze'?'Analyzing all parts…':'Analyze Everything'}</button><button disabled={pending||!chunks.length} onClick={saveAsNote} className="rounded-full border border-[#ded4cc] px-4 py-2 text-[8.5px]">Save Smart Note</button></div></div><div className="mt-4 max-h-[280px] space-y-3 overflow-y-auto rounded-[18px] bg-[#faf7f3] p-4">{chunks.map(c=><div key={c.chunkIndex}><p className="text-[7.5px] font-semibold uppercase text-[#978b82]">Part {c.chunkIndex+1}{c.startSeconds!=null?` · ${fmt(c.startSeconds)}${c.endSeconds!=null?`–${fmt(c.endSeconds)}`:''}`:''}</p><p className="mt-1 whitespace-pre-wrap text-[10px] leading-5">{c.text}</p></div>)}</div></div>
    <div className="grid gap-3 lg:grid-cols-2"><div className="rounded-[22px] border border-[#e7ddd5] bg-[#fffdfa] p-4"><div className="flex items-center gap-2"><Sparkles size={13}/><b className="text-[10px]">Analysis</b></div>{analysis?.status==='complete'?<div className="mt-3 space-y-3"><p className="text-[9.5px] leading-5">{analysis.summary}</p>{analysis.keyPoints.length?<List title="Key points" items={analysis.keyPoints}/>:null}{analysis.decisions.length?<List title="Decisions" items={analysis.decisions}/>:null}{analysis.actionItems.length?<List title="Action items" items={analysis.actionItems}/>:null}{analysis.themes.length?<List title="Themes" items={analysis.themes}/>:null}</div>:<p className="mt-3 text-[8.5px] leading-4 text-[#8f847c]">Run Analyze Everything after transcription. Glow analyzes each stored section before synthesizing the whole source, so long transcripts are not reduced to only the beginning.</p>}</div>
     <div className="rounded-[22px] border border-[#e7ddd5] bg-[#fffdfa] p-4"><div className="flex items-center gap-2"><MessageCircleQuestion size={13}/><b className="text-[10px]">Ask This Transcript</b></div><textarea value={ask} onChange={e=>setAsk(e.target.value)} placeholder="What exactly did they say about…? What were the steps? What decision was made?" className="mt-3 min-h-[82px] w-full rounded-[14px] border border-[#e2d9d1] p-3 text-[9px]"/><button disabled={!ask.trim()||busy==='ask'} onClick={()=>void askTranscript()} className="mt-2 rounded-full bg-[#4f4a46] px-4 py-2 text-[8.5px] text-white disabled:opacity-40">{busy==='ask'?<><LoaderCircle size={10} className="mr-1 inline animate-spin"/>Answering…</>:'Ask'}</button>{answer?<div className="mt-3 rounded-[15px] bg-[#f5f1ec] p-3"><p className="text-[9.5px] leading-5">{answer.answer}</p>{answer.evidence?.length?<p className="mt-2 text-[7.5px] text-[#8f837b]">Evidence: {answer.evidence.map(x=>`part ${x.chunkIndex+1}`).join(', ')}</p>:null}</div>:null}{questions.length?<div className="mt-3 border-t border-[#eee6df] pt-3"><p className="text-[7.5px] uppercase tracking-[.12em]">Recent questions</p>{questions.slice(0,3).map(q=><div key={q.id} className="mt-2"><b className="text-[8px]">{q.question}</b><p className="line-clamp-2 text-[8px] text-[#847970]">{q.answer}</p></div>)}</div>:null}</div></div></>:<div className="rounded-[22px] border border-dashed border-[#ddd3cb] bg-[#fffdfa] p-8 text-center"><AudioLines size={20} className="mx-auto"/><p className="mt-3 font-serif text-2xl">Choose a transcript</p></div>}</div></div>
 </section>
}
function List({title,items}:{title:string;items:string[]}){return <div><p className="text-[7.5px] font-semibold uppercase tracking-[.12em] text-[#8c7f77]">{title}</p><ul className="mt-1 space-y-1">{items.slice(0,12).map((x,i)=><li key={`${x}-${i}`} className="text-[8.5px] leading-4">• {x}</li>)}</ul></div>}
