import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { AppShell } from '@/components/app-shell';
import { Card } from '@/components/ui/card';
import { generateExpandedBriefingAction } from '@/app/actions/briefings';
import { getBriefings } from '@/lib/data/completion-v1';
import { getTasksByUser } from '@/lib/data/tasks';
import { getCalendarEventsByUser } from '@/lib/data/calendar-events';
import { getWellnessEntriesByUser } from '@/lib/data/wellness-entries';
import { getLifeModes } from '@/lib/intelligence/adaptive-os';
import { CheckCircle2, Sparkles, Utensils } from 'lucide-react';

export const dynamic='force-dynamic';
const heroImage='https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85';

const MODE_COPY: Record<string,{intro:string;limit:number;attention:string;advice:string}>={
 'deep-work':{intro:'You have a strong day ahead. Protect your best focus windows and use them for the work that matters most.',limit:3,attention:'Priorities worth your energy',advice:'Use your strongest window for the highest-value work before optional tasks enter the day.'},
 normal:{intro:'Here are the three things that matter today. Keep the day balanced and leave breathing room between commitments.',limit:3,attention:'What needs attention',advice:'A good day does not need every open minute filled. Protect the priorities and keep the rest flexible.'},
 'low-energy':{intro:'Keep today small. One priority, essential commitments, food, hydration, medication, and care are enough.',limit:1,attention:'Essential today',advice:'Reduce friction. Complete the one thing that truly matters and let Glow hold the rest for review.'},
 sick:{intro:'Today is about reducing pressure. Glow will keep only truly necessary commitments and care in view.',limit:0,attention:'Truly necessary',advice:'Recovery is the plan today. Protect care and immovable commitments; everything else can wait for review.'},
};

export default async function MorningBriefPage(){
 const s=await auth();if(!s?.user?.id)redirect('/sign-in');const id=s.user.id;
 const [all,tasks,events,wellnessEntries,modes]=await Promise.all([getBriefings(id),getTasksByUser(id),getCalendarEventsByUser(id),getWellnessEntriesByUser(id),getLifeModes(id)]);
 const activeMode=modes.find(mode=>mode.isActive);const mode=MODE_COPY[activeMode?.slug??'normal']??MODE_COPY.normal;
 const latest=all.find(b=>b.kind==='morning');const now=new Date();const todayKey=now.toISOString().slice(0,10);
 const todayEvents=events.filter(event=>event.startAt.toISOString().slice(0,10)===todayKey).sort((a,b)=>a.startAt.getTime()-b.startAt.getTime());
 const eligibleTasks=tasks.filter(task=>task.status!=='done'&&task.status!=='cancelled');
 const openTasks=mode.limit?eligibleTasks.slice(0,mode.limit):[];const priority=openTasks[0]??null;const nextEvent=todayEvents.find(event=>event.startAt.getTime()>=now.getTime())??todayEvents[0]??null;const wellness=wellnessEntries[0]??null;
 const dateLabel=now.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});
 return <AppShell><div className="batch1-morning-reference space-y-4">
  <section className="batch1-brief-hero relative min-h-[210px] overflow-hidden rounded-[22px] border border-[#eee7e3] bg-[#f8f2ef]"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:`linear-gradient(90deg,rgba(255,255,255,.96) 0%,rgba(255,255,255,.80) 38%,rgba(255,255,255,.10) 70%),url(${heroImage})`}}/><div className="relative z-10 max-w-[560px] p-7 sm:p-9"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#bc6d79]">Morning Brief · {activeMode?.name??'Normal Day'}</p><h1 className="glow-display mt-2 text-[42px] leading-none tracking-[-.03em] text-[#241f1c] sm:text-[50px]">Morning Brief</h1><p className="mt-3 text-[11px] font-medium text-[#b65f70]">{dateLabel}</p><p className="mt-2 max-w-[500px] text-[12px] leading-5 text-[#625b56]">{mode.intro}</p></div><div className="absolute right-5 top-5 z-10 flex gap-2"><Link href="/briefings" className="rounded-full border border-white/80 bg-white/85 px-3 py-2 text-[10px] text-[#6f6660] shadow-sm">All Briefings</Link><form action={generateExpandedBriefingAction.bind(null,'morning')}><button className="rounded-[7px] bg-[#a94761] px-4 py-2 text-[10px] font-medium text-white shadow-sm">Refresh Brief</button></form></div></section>
  <Card className="batch1-your-day overflow-hidden p-0"><div className="px-5 pt-5"><h2 className="glow-display text-[19px]">Your Day</h2><p className="mt-1 text-[10px] text-[#918782]">{activeMode?.slug==='sick'?`Only ${todayEvents.length} calendar commitment${todayEvents.length===1?'':'s'} and essential care stay in view.`:`You have ${todayEvents.length} event${todayEvents.length===1?'':'s'} and ${openTasks.length} visible priority task${openTasks.length===1?'':'s'}.`}</p></div><div className="relative mx-5 my-4 h-[38px] border-y border-[#efe5e2] bg-[linear-gradient(90deg,#fff_0%,#fff_10%,#f9e4e7_10%,#f9e4e7_34%,#f3dde3_34%,#f3dde3_60%,#edd8dc_60%,#edd8dc_82%,#fff_82%)]"/></Card>
  <div className="grid gap-3 lg:grid-cols-3"><Card className="p-4"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#8f837c]">{activeMode?.slug==='sick'?'Productivity':'Top Priority'}</p><h3 className="glow-display mt-3 text-[19px] leading-tight">{activeMode?.slug==='sick'?'Paused for recovery':priority?.title??'Choose your top priority'}</h3>{activeMode?.slug!=='sick'?<Link href={priority?`/tasks?taskId=${encodeURIComponent(priority.id)}&view=all`:'/tasks'} className="mt-5 inline-flex rounded-[6px] border border-[#f0d8dc] px-3 py-2 text-[9px] text-[#b45d70]">Go to Task →</Link>:<p className="mt-3 text-[9px] leading-4 text-[#958a83]">Only genuinely urgent work should re-enter today.</p>}</Card><Card className="p-4"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#8f837c]">Where You Need to Be</p><h3 className="glow-display mt-3 text-[19px] leading-tight">{nextEvent?.title??'No fixed appointment'}</h3><p className="mt-1 text-[10px] text-[#8f837c]">{nextEvent?nextEvent.startAt.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'Your calendar is open'}</p><Link href={nextEvent?`/calendar?eventId=${encodeURIComponent(nextEvent.id)}&view=day`:'/calendar?view=day'} className="mt-5 inline-flex rounded-[6px] border border-[#f0d8dc] px-3 py-2 text-[9px] text-[#b45d70]">Plan Around It →</Link></Card><Card className="p-4"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#8f837c]">Body + Energy</p><h3 className="glow-display mt-3 text-[19px] leading-tight">{wellness?.energy?`Energy is ${wellness.energy} today.`:'Log your energy to personalize today.'}</h3><Link href="/wellness" className="mt-5 inline-flex rounded-[6px] border border-[#f0d8dc] px-3 py-2 text-[9px] text-[#b45d70]">View Wellness →</Link></Card></div>
  <Card className="p-4"><div className="flex items-center gap-2"><Utensils size={14} className="text-[#b56a75]"/><h2 className="glow-display text-[18px]">Meals + Care</h2></div><Link href="/food" className="mt-3 inline-flex text-[9px] text-[#b45d70]">Open Food & Nutrition →</Link></Card>
  <div className="grid gap-3 lg:grid-cols-[1.15fr_.85fr]"><Card className="p-4"><h2 className="glow-display text-[18px]">{mode.attention}</h2><div className="mt-4 space-y-2">{openTasks.length?openTasks.map(task=><Link key={task.id} href={`/tasks?taskId=${encodeURIComponent(task.id)}&view=all`} className="flex items-center gap-2 rounded-[8px] px-2 py-2 text-[10px] hover:bg-[#fdf4f3]"><CheckCircle2 size={13} className="text-[#c66c7b]"/><span>{task.title}</span></Link>):<p className="text-[10px] leading-4 text-[#958a83]">{activeMode?.slug==='sick'?'No productivity list is being placed in front of you. Keep care and immovable commitments visible.':'Nothing else needs attention right now.'}</p>}</div></Card><Card className="relative overflow-hidden bg-[linear-gradient(135deg,#fff_0%,#f9e7e7_100%)] p-5"><Sparkles size={15} className="text-[#bd6976]"/><h2 className="glow-display mt-3 text-[19px]">Glow&apos;s Advice</h2><p className="glow-display mt-4 text-[18px] italic leading-7 text-[#514844]">{latest&&activeMode?.slug==='normal'?'Use the clarity already captured in your latest brief.':mode.advice}</p></Card></div>
 </div></AppShell>;
}
