import Link from 'next/link';
import { auth } from '@/auth';
import { redirect } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { dismissGlowNoticeAction, markGlowNoticeUsefulAction, snoozeGlowNoticeAction } from '@/app/actions/glow-notices';
import { ensureGlowNotices } from '@/lib/intelligence/glow-notices';
import { BellRing, Check, Clock3, Sparkles, X } from 'lucide-react';

export const dynamic='force-dynamic';

export default async function NoticesPage(){
  const session=await auth();if(!session?.user?.id)redirect('/sign-in');
  let notices;
  try{notices=await ensureGlowNotices(session.user.id);}catch{return <AppShell><div className="mx-auto max-w-4xl rounded-[22px] border border-amber-200 bg-amber-50 p-6"><p className="text-sm font-semibold text-stone-900">Glow Notices need intelligence activation.</p><Link href="/settings/intelligence" className="mt-3 inline-block text-xs text-amber-900">Activate intelligence →</Link></div></AppShell>;}
  const active=notices.filter(n=>n.status==='active');
  return <AppShell><div className="mx-auto max-w-5xl space-y-5"><header><div className="flex items-center gap-2 text-rose-700"><BellRing size={18}/><p className="text-[9px] font-bold uppercase tracking-[.2em]">What Glow noticed</p></div><h1 className="glow-display mt-2 text-[40px] leading-none text-[#392e2a]">Glow Notices</h1><p className="mt-2 max-w-2xl text-[10px] leading-5 text-[#7e6b64]">Evidence-based patterns from across your systems. Keep, snooze or dismiss them so Glow gets more useful over time.</p></header><section className="space-y-3">{active.length?active.map(n=><article key={n.id} className="rounded-[20px] border border-[#e5d8cf] bg-white/75 p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><Sparkles size={13} className="text-[#b46f79]"/><span className="text-[7px] font-bold uppercase tracking-[.15em] text-[#9c7e76]">{n.domain} · {Math.round(n.confidence*100)}% confidence</span></div><h2 className="glow-display mt-2 text-[21px] text-[#433631]">{n.title}</h2><p className="mt-2 text-[9px] leading-4 text-[#7f6c65]"><strong>Evidence:</strong> {n.evidence}</p>{n.recommendation?<p className="mt-2 rounded-xl bg-[#f7efea] p-3 text-[9px] leading-4 text-[#69544f]"><strong>Glow suggests:</strong> {n.recommendation}</p>:null}</div><div className="flex shrink-0 gap-2"><form action={markGlowNoticeUsefulAction.bind(null,n.id)}><button type="submit" title="Useful" className="rounded-full border border-emerald-200 bg-emerald-50 p-2 text-emerald-700"><Check size={12}/></button></form><form action={snoozeGlowNoticeAction.bind(null,n.id)}><button type="submit" title="Snooze 24 hours" className="rounded-full border border-amber-200 bg-amber-50 p-2 text-amber-700"><Clock3 size={12}/></button></form><form action={dismissGlowNoticeAction.bind(null,n.id)}><button type="submit" title="Dismiss" className="rounded-full border border-stone-200 bg-white p-2 text-stone-500"><X size={12}/></button></form></div></div></article>):<div className="rounded-[20px] border border-emerald-100 bg-emerald-50/60 p-8 text-center"><p className="glow-display text-[20px] text-[#3c463d]">Nothing needs your attention.</p><p className="mt-2 text-[9px] text-[#718073]">Glow will add a notice when cross-system evidence is strong enough to be useful.</p></div>}</section><Link href="/observations" className="inline-flex text-[9px] text-[#9d626b]">Open full Observations workspace →</Link></div></AppShell>;
}
