import type { InferSelectModel, InferInsertModel } from 'drizzle-orm';
import type { users, accounts, sessions } from '@/db/schema/auth';
import type { tasks } from '@/db/schema/tasks';
import type { habits, habitLogs } from '@/db/schema/habits';
import type { habitProfiles, habitCompletionDetails, habitTimingStats, habitTriggers, habitStacks, habitExperiments, habitSourceLinks } from '@/db/schema/advanced-habits';
import type { routines, routineSteps } from '@/db/schema/routines';
import type { routineRuns, routineStepRuns, routineStepStats, routineStepLinks, routineTriggers, routineStepRules, routineChains } from '@/db/schema/advanced-routines';
import type { goals } from '@/db/schema/goals';
import type { calendarEvents } from '@/db/schema/calendar-events';
import type { beautyRoutines } from '@/db/schema/beauty-routines';
import type { wellnessEntries } from '@/db/schema/wellness-entries';
import type { financeEntries } from '@/db/schema/finance-entries';
import type { notes } from '@/db/schema/notes';
import type { importantLinks } from '@/db/schema/important-links';
import type { appointments } from '@/db/schema/appointments';
import type { workSchedules } from '@/db/schema/work-schedules';

export type User = InferSelectModel<typeof users>;
export type NewUser = InferInsertModel<typeof users>;
export type Account = InferSelectModel<typeof accounts>;
export type Session = InferSelectModel<typeof sessions>;
export type Task = InferSelectModel<typeof tasks>;
export type NewTask = InferInsertModel<typeof tasks>;
export type Habit = InferSelectModel<typeof habits>;
export type NewHabit = InferInsertModel<typeof habits>;
export type HabitLog = InferSelectModel<typeof habitLogs>;
export type NewHabitLog = InferInsertModel<typeof habitLogs>;
export type HabitProfile = InferSelectModel<typeof habitProfiles>;
export type HabitCompletionDetail = InferSelectModel<typeof habitCompletionDetails>;
export type HabitTimingStat = InferSelectModel<typeof habitTimingStats>;
export type HabitTrigger = InferSelectModel<typeof habitTriggers>;
export type HabitStack = InferSelectModel<typeof habitStacks>;
export type HabitExperiment = InferSelectModel<typeof habitExperiments>;
export type HabitSourceLink = InferSelectModel<typeof habitSourceLinks>;
export type Routine = InferSelectModel<typeof routines>;
export type NewRoutine = InferInsertModel<typeof routines>;
export type RoutineStep = InferSelectModel<typeof routineSteps>;
export type NewRoutineStep = InferInsertModel<typeof routineSteps>;
export type RoutineRun = InferSelectModel<typeof routineRuns>;
export type RoutineStepRun = InferSelectModel<typeof routineStepRuns>;
export type RoutineStepStat = InferSelectModel<typeof routineStepStats>;
export type RoutineStepLink = InferSelectModel<typeof routineStepLinks>;
export type RoutineTrigger = InferSelectModel<typeof routineTriggers>;
export type RoutineStepRule = InferSelectModel<typeof routineStepRules>;
export type RoutineChain = InferSelectModel<typeof routineChains>;
export type Goal = InferSelectModel<typeof goals>;
export type NewGoal = InferInsertModel<typeof goals>;
export type CalendarEvent = InferSelectModel<typeof calendarEvents>;
export type NewCalendarEvent = InferInsertModel<typeof calendarEvents>;
export type BeautyRoutine = InferSelectModel<typeof beautyRoutines>;
export type NewBeautyRoutine = InferInsertModel<typeof beautyRoutines>;
export type WellnessEntry = InferSelectModel<typeof wellnessEntries>;
export type NewWellnessEntry = InferInsertModel<typeof wellnessEntries>;
export type FinanceEntry = InferSelectModel<typeof financeEntries>;
export type NewFinanceEntry = InferInsertModel<typeof financeEntries>;
export type Note = InferSelectModel<typeof notes>;
export type NewNote = InferInsertModel<typeof notes>;
export type ImportantLink = InferSelectModel<typeof importantLinks>;
export type NewImportantLink = InferInsertModel<typeof importantLinks>;
export type Appointment = InferSelectModel<typeof appointments>;
export type NewAppointment = InferInsertModel<typeof appointments>;
export type WorkSchedule = InferSelectModel<typeof workSchedules>;
export type NewWorkSchedule = InferInsertModel<typeof workSchedules>;
export type HabitWithLogs = Habit & { logs: HabitLog[] };
export type RoutineWithSteps = Routine & { steps: RoutineStep[] };
