import type { FoodIngredient, FoodRecipeStep } from '@/db/schema/food-intelligence';

export type MasterRecipe = {
  slug:string; title:string; primaryCategory:string; categories:string[]; tags?:string[]; recipeStatus:'complete'|'missing_measurements'; servings?:string; prepMinutes?:number; cookMinutes?:number; totalMinutes?:number; ingredients?:FoodIngredient[]; instructions?:FoodRecipeStep[]; notes?:string;
};

const step=(text:string,seconds?:number,parallelHint?:string):FoodRecipeStep=>({text,...(seconds?{seconds}:{}),...(parallelHint?{parallelHint}:{})});
const ing=(name:string,amount?:string,note?:string):FoodIngredient=>({name,...(amount?{amount}:{}),...(note?{note}:{})});

export const MASTER_RECIPES:MasterRecipe[]=[
{slug:'green-spinach-smoothie',title:'Green Spinach Smoothie',primaryCategory:'breakfast',categories:['Breakfast','Drinks & Smoothies'],tags:['quick','smoothie'],recipeStatus:'complete',servings:'1',ingredients:[ing('Water','½ cup'),ing('Coffee creamer','½ cup','Milk, almond milk, or another nondairy milk can replace the creamer'),ing('Spinach and kale mixture','1–2 handfuls'),ing('Frozen fruit','1½–2 cups'),ing('Splenda','1 packet'),ing('Honey',undefined,'optional'),ing('Collagen powder',undefined,'optional'),ing('Sea moss gel',undefined,'optional'),ing('Strawberries',undefined,'optional')],instructions:[step('Add the water and coffee creamer to the blender.'),step('Use approximately half water and half creamer.'),step('Add the spinach and kale.'),step('Add the frozen fruit.'),step('The liquid should come slightly more than halfway up the fruit.'),step('Add Splenda.'),step('Add honey, collagen, or sea moss if using.'),step('Blend until completely smooth.'),step('Add a little more liquid only if the blender needs help moving.')]},
{slug:'rice-lentil-quinoa-power-bowl',title:'Rice, Lentil and Quinoa Power Bowl',primaryCategory:'lunch',categories:['Lunch','Dinner'],tags:['meal prep','high protein','high fiber'],recipeStatus:'complete',servings:'4–6',ingredients:[ing('Brown rice or jasmine rice','1 cup'),ing('Quinoa','1 cup','rinsed'),ing('Green or brown lentils','1 cup dried','rinsed'),ing('Vegetable broth or water','7 cups'),ing('Olive oil','2 tablespoons'),ing('Onion','1 medium','diced'),ing('Garlic','3 cloves','minced'),ing('Paprika','1 teaspoon'),ing('Cumin','1 teaspoon'),ing('Turmeric','1 teaspoon'),ing('Black pepper','½ teaspoon'),ing('Salt','1½ teaspoons','or to taste'),ing('Spinach','2–3 handfuls','optional'),ing('Peas','1 cup','optional'),ing('Carrots','1 cup diced','optional'),ing('Mushrooms','1 cup','optional'),ing('Parsley or cilantro',undefined,'optional'),ing('Lemon','½','juice, optional')],instructions:[step('Rinse the rice, quinoa, and lentils thoroughly.'),step('Heat the olive oil in a large pot over medium heat.'),step('Add the onion and cook for 4–5 minutes, until soft.',270),step('Add the garlic and cook for approximately 30 seconds.',30),step('Stir in the paprika, cumin, turmeric, black pepper, and salt.'),step('Add the rice, lentils, and cooking liquid.'),step('Bring everything to a boil, then lower the heat and cover.'),step('Simmer for approximately 20 minutes.',1200,'Prepare optional vegetables while the pot simmers.'),step('Add the quinoa, stir, cover, and continue cooking for approximately 15–20 minutes.',1050),step('Check that the rice, lentils, and quinoa are tender; add more liquid if needed.'),step('Stir in optional vegetables during the final few minutes.'),step('Remove from heat and rest covered for 5–10 minutes.',450),step('Fluff and finish with lemon juice and fresh herbs.')]},
{slug:'tofu-summer-rolls-light-peanut-sauce',title:'Tofu Summer Rolls with Light Peanut Sauce',primaryCategory:'lunch',categories:['Lunch'],tags:['tofu','fresh'],recipeStatus:'complete',servings:'Approximately 6–8 rolls',ingredients:[ing('Rice-paper wrappers','6–8'),ing('Extra-firm tofu','8 ounces'),ing('Lettuce'),ing('Carrots','thinly sliced'),ing('Cucumber','thinly sliced'),ing('Fresh herbs','mint or cilantro'),ing('Powdered peanut butter','¼ cup'),ing('Honey or maple syrup','1 tablespoon'),ing('Soy sauce','2 tablespoons'),ing('Rice vinegar','2 tablespoons'),ing('Sesame oil','1 teaspoon'),ing('Garlic','1 clove','minced'),ing('Water',undefined,'as needed to thin sauce')],instructions:[step('Drain the tofu and press it for 20–30 minutes.',1500,'Prepare the vegetables and sauce while the tofu presses.'),step('Cut the tofu into strips.'),step('Bake, air-fry, or sauté it until golden.'),step('Prepare all vegetables before soaking the wrappers.'),step('Whisk powdered peanut butter, sweetener, soy sauce, rice vinegar, sesame oil, and garlic.'),step('Add water gradually until the sauce reaches a smooth dipping consistency.'),step('Fill a wide bowl or plate with warm water.'),step('Dip one rice-paper wrapper in the water for approximately 5–10 seconds.'),step('Place it on a damp cutting board or clean plate.'),step('Add lettuce, vegetables, herbs, and tofu near the lower third.'),step('Fold the bottom over the filling, fold both sides inward, then roll tightly but gently.'),step('Repeat with remaining wrappers and serve with the sauce.')]},
{slug:'charlie-birds-farro-salad',title:'Charlie Bird’s Farro Salad',primaryCategory:'lunch',categories:['Lunch'],tags:['salad','meal prep'],recipeStatus:'complete',servings:'Approximately 6',prepMinutes:15,cookMinutes:30,totalMinutes:60,ingredients:[ing('Pearled farro','1 cup'),ing('Apple cider','1 cup','or approved substitute'),ing('Water','2 cups'),ing('Bay leaves','2'),ing('Kosher salt','2 teaspoons'),ing('Olive oil','½ cup'),ing('Lemon juice or champagne vinegar','¼ cup'),ing('Salt','1 teaspoon','for vinaigrette'),ing('Black pepper','½ teaspoon'),ing('Pistachios or toasted pine nuts','½ cup'),ing('Parsley','1 cup chopped'),ing('Mint','1 cup chopped'),ing('Tomatoes'),ing('Radishes'),ing('Craisins','¼–½ cup'),ing('Mini mozzarella',undefined,'optional'),ing('Arugula',undefined,'optional'),ing('Parmesan',undefined,'optional'),ing('Flaky salt',undefined,'to finish')],instructions:[step('Add farro, apple cider, water, bay leaves, and 2 teaspoons salt to a medium saucepan.'),step('Bring to a boil, lower the heat, partially cover, and simmer for approximately 25–30 minutes.',1650,'Toast the nuts and make the vinaigrette while the farro cooks.'),step('Drain excess liquid and discard the bay leaves.'),step('Toast pine nuts in a dry skillet over medium-low heat for 3–5 minutes, stirring frequently.',240),step('Combine olive oil and lemon juice, add 1 teaspoon salt and ½ teaspoon black pepper, and whisk or shake.'),step('Transfer warm drained farro to a large bowl and toss with the vinaigrette.'),step('Let the dressed farro rest for at least 15 minutes.',900),step('Add parsley, mint, toasted nuts, tomatoes, radishes, and Craisins.'),step('Add mini mozzarella, arugula, or Parmesan if using.'),step('Toss gently and adjust with flaky salt, pepper, or additional lemon juice.'),step('Store refrigerated for up to 3 days.')],notes:'Apple cider substitutes preserved from your recipe: 1 additional cup water; 1 cup apple juice; ¾ cup water + ¼ cup apple juice; or vegetable broth for a savory version. Balsamic options: 3 tbsp balsamic instead of lemon, or 2 tbsp lemon + 1 tbsp balsamic.'},
{slug:'seasoned-crispy-peas',title:'Seasoned Crispy Peas',primaryCategory:'snack',categories:['Snacks'],tags:['air fryer','oven'],recipeStatus:'complete',ingredients:[ing('Peas','2 cups'),ing('Oil','1 teaspoon','optional'),ing('Salt'),ing('Pepper'),ing('Garlic powder, paprika, or another selected seasoning')],instructions:[step('Dry the peas thoroughly.'),step('Toss with oil if using and add seasonings.'),step('Air-fry at 400°F for 10–15 minutes, shaking halfway through.',750),step('For oven method, bake at 425°F for 20–25 minutes, stirring halfway through.',1350),step('Remove when crisp and lightly browned.')]},
{slug:'kool-aid-slush',title:'Kool-Aid Slush',primaryCategory:'drinks',categories:['Drinks & Smoothies'],tags:['quick','drink'],recipeStatus:'complete',servings:'1–2',ingredients:[ing('Kool-Aid drink mix','1 packet'),ing('Ice','1–2 cups'),ing('Water','½–1 cup'),ing('Sweetener',undefined,'optional')],instructions:[step('Put the ice in a blender.'),step('Add the Kool-Aid mix.'),step('Add ½ cup water.'),step('Add sweetener if desired.'),step('Blend until smooth and slushy.'),step('Add more water only if needed.')]},
{slug:'butter-beans-spinach-protein-pasta',title:'Butter Beans and Spinach Protein Pasta',primaryCategory:'dinner',categories:['Dinner'],tags:['protein pasta'],recipeStatus:'complete',ingredients:[ing('Protein pasta'),ing('Butter beans'),ing('Spinach'),ing('Garlic'),ing('Olive oil'),ing('Parmesan'),ing('Salt'),ing('Black pepper')],instructions:[step('Cook the protein pasta according to package directions.'),step('Reserve a little pasta water.'),step('Heat olive oil in a skillet.'),step('Add garlic and cook briefly.'),step('Add butter beans.'),step('Add spinach and cook until wilted.'),step('Add drained pasta and toss together.'),step('Add pasta water if the mixture needs moisture.'),step('Finish with Parmesan, salt, and black pepper.')]},
{slug:'thick-fruit-collagen-sea-moss-smoothie',title:'Thick Fruit, Collagen and Sea Moss Smoothie',primaryCategory:'drinks',categories:['Drinks & Smoothies'],tags:['smoothie'],recipeStatus:'complete',ingredients:[ing('Frozen fruit'),ing('Almond milk'),ing('Collagen powder'),ing('Sea moss gel'),ing('Honey',undefined,'optional')],instructions:[step('Add almond milk to the blender.'),step('Add frozen fruit.'),step('Add collagen powder.'),step('Add sea moss.'),step('Blend until thick and smooth.'),step('Add more almond milk only when necessary.')]},
{slug:'chinese-snow-fungus-soup',title:'Chinese Snow Fungus Soup',primaryCategory:'lunch',categories:['Lunch'],tags:['soup'],recipeStatus:'complete',ingredients:[ing('Dried snow fungus or tremella'),ing('Water'),ing('Rock sugar or coconut sugar'),ing('Red dates',undefined,'optional'),ing('Goji berries',undefined,'optional'),ing('Dried longan',undefined,'optional'),ing('Peach gum',undefined,'optional'),ing('Fresh ginger',undefined,'optional'),ing('Pear',undefined,'optional'),ing('Coconut milk',undefined,'optional')],instructions:[step('Soak the dried snow fungus in water until fully expanded.'),step('Cut away the hard yellow base and tear the fungus into small pieces.'),step('If using peach gum, soak it separately and clean away impurities.'),step('Add the snow fungus and water to a pot.'),step('Bring to a boil, lower the heat, and simmer until soft and slightly gelatinous.'),step('Add red dates, longan, ginger, or pear during cooking.'),step('Add goji berries near the end.'),step('Sweeten with rock sugar or coconut sugar.'),step('Add coconut milk at the end if using.'),step('Serve warm or chilled.')]},
];

const incomplete:[string,string,string[]][]=[
['high-protein-pesto-pasta','High-Protein Pesto Pasta',['Dinner']],['bone-broth-vegetable-soup','Bone Broth Vegetable Soup',['Dinner']],['high-protein-yogurt-bowl','High-Protein Yogurt Bowl',['Breakfast','Snacks']],['high-protein-triple-berry-buns','High-Protein Triple Berry Buns',['Breakfast','Desserts']],['butter-swim-biscuits','Butter Swim Biscuits',['Dinner']],['pumpkin-pancakes','Pumpkin Pancakes',['Breakfast']],['mango-cloud-pancakes','Mango Cloud Pancakes',['Breakfast']],['cloud-bread','Cloud Bread',['Breakfast']],['supermodel-bread','Supermodel Bread',['Breakfast']],['raspberry-cloud-roll','Raspberry Cloud Roll',['Breakfast','Desserts']],['funfetti-mug-cake','Funfetti Mug Cake',['Breakfast','Desserts']],['jello-yogurt-dessert','Jello Yogurt Dessert',['Breakfast','Desserts']],['smoothie-bowl','Smoothie Bowl',['Breakfast']],['chia-pudding','Chia Pudding',['Breakfast']],['egg-and-pesto','Egg and Pesto',['Breakfast']],['minimal-spinach-pasta-sauce','Minimal Spinach Pasta Sauce',['Lunch']],['one-pot-misir-wot','One-Pot Misir Wot',['Lunch']],['air-fried-sweet-tofu','Air-Fried Sweet Tofu',['Lunch']],['salmon-with-pesto','Salmon with Pesto',['Lunch']],['cottage-cheese-egg-lettuce-cups','Cottage-Cheese Egg Lettuce Cups',['Lunch']],['tofu-beans-vegetables-quinoa','Tofu, Beans, Vegetables and Quinoa Bowl',['Lunch','Dinner']],['sheet-pan-vegetables-tahini','Sheet-Pan Vegetables with Tahini',['Lunch']],['brussels-sprouts-beans','Brussels Sprouts and Beans',['Lunch']],['sticky-lemon-pepper-tofu','Sticky Lemon-Pepper Tofu',['Dinner']],['tofu-skin-noodles','Tofu Skin Noodles',['Dinner']],['crispy-potato-bites-salmon','Crispy Potato Bites with Salmon',['Dinner']],['tempura-chickpea-bites','Tempura Chickpea Bites',['Dinner']],['vegan-nuggets-plate','Vegan Nuggets Plate',['Dinner']],['sweet-tofu-bowl','Sweet Tofu Bowl',['Dinner']],['misir-wot-add-ins','Misir Wot with Add-Ins',['Dinner']],['rice-paper-crisps','Rice-Paper Crisps',['Snacks']],['carrot-chips','Carrot Chips',['Snacks']],['protein-cherries','Protein Cherries',['Snacks']],['low-calorie-protein-marshmallows','Low-Calorie Protein Marshmallows',['Snacks','Desserts']],['raspberry-crumb-cake','Raspberry Crumb Cake',['Desserts']],['sweet-potato-brulee','Sweet Potato Brûlée',['Desserts']],['erewhon-style-strawberry-smoothie','Erewhon-Style Strawberry Smoothie',['Drinks & Smoothies']],['erewhon-style-blue-smoothie','Erewhon-Style Blue Smoothie',['Drinks & Smoothies']],['erewhon-style-mango-smoothie','Erewhon-Style Mango Smoothie',['Drinks & Smoothies']],['erewhon-style-matcha-smoothie','Erewhon-Style Matcha Smoothie',['Drinks & Smoothies']],['erewhon-style-smoothies','Erewhon-Style Smoothies',['Breakfast','Drinks & Smoothies']],['coconut-cult-yogurt','Coconut Cult Yogurt',['Snacks']],['cape-cod-chips','Cape Cod Chips',['Snacks']]
];
for(const [slug,title,categories] of incomplete)MASTER_RECIPES.push({slug,title,primaryCategory:categories[0].toLowerCase(),categories,recipeStatus:'missing_measurements',notes:'Recipe title is preserved from the Food folder. Original complete measurements were not recoverable, so Glow must not invent them.'});

export const MASTER_GROCERY_GROUPS:Record<string,string[]>={
'Produce':['Apples or apple juice','Avocados','Bananas','Blueberries','Carrots','Cauliflower, fresh or frozen','Cilantro','Cucumbers','Fresh ginger','Garlic','Kale','Lemons','Lettuce','Mango','Mint','Mushrooms','Onions','Oranges or orange juice','Parsley','Pears','Pineapple','Potatoes','Radishes','Raspberries','Spinach','Strawberries','Sweet potatoes','Tomatoes','Vegetables for sheet-pan meals and soup','Brussels sprouts','Zucchini','Red cabbage','Green onion','Bell peppers','Basil','Limes'],
'Frozen foods':['Frozen fruit','Frozen strawberries','Frozen mango','Frozen pineapple','Frozen cauliflower','Frozen peas','Protein cherries','Ice','Frozen stir-fry vegetables'],
'Refrigerated and dairy':['Coffee creamer','Milk','Almond milk','Oat milk','Coconut milk','Coconut cream','Coconut yogurt','Coconut Cult yogurt','Greek yogurt','Cottage cheese','Eggs','Mini mozzarella','Parmesan','Butter','Pesto','Laughing Cow light cheese','Light butter'],
'Protein and plant-based foods':['Extra-firm tofu','Baked tofu','Sweet tofu','Tofu skin noodles','Butter beans','Chickpeas','Green or brown lentils','Beans for bowls and Brussels-sprout meals','Salmon','Vegan nuggets','Vanilla protein powder','Collagen powder','Powdered peanut butter','Almond butter','Peanut butter','Shrimp','Bone broth','Lean protein'],
'Rice, grains and pasta':['Brown rice','Jasmine rice','White rice','Quinoa','Pearled farro','Protein pasta','Rice-paper wrappers','Rice paper for crisps','Oats','Oat flour','Kelp noodles'],
'Baking supplies':['All-purpose flour','Baking powder','Baking soda','Granulated sugar','Brown sugar','Powdered sugar','Vanilla extract','Yeast, if required for the buns','Berry ingredients for Triple Berry Buns','Raspberry ingredients for crumb cake','Pancake ingredients','Marshmallow ingredients','Jello mix'],
'Nuts, seeds and toppings':['Pistachios','Pine nuts','Chia seeds','Hemp seeds','Cacao nibs','Craisins','Medjool dates','Goji berries','Red dates','Dried longan','Peach gum'],
'Broth and cooking liquids':['Vegetable broth','Bone broth','Apple cider','Apple juice','Coconut water','Orange juice','Berry tea bags','Water'],
'Oils and vinegars':['Olive oil','Sesame oil','Rice vinegar','Champagne vinegar','Balsamic vinegar','Tahini'],
'Sauces and sweeteners':['Soy sauce','Honey','Maple syrup','Sugar-free maple syrup','Rock sugar','Coconut sugar','Splenda','Kool-Aid drink mix','Miso paste','Nutritional yeast','Monk fruit sweetener','Mustard'],
'Seasonings':['Bay leaves','Kosher salt','Flaky salt','Black pepper','Paprika','Cumin','Turmeric','Garlic powder','Lemon-pepper seasoning','Onion powder','Ginger','Additional seasonings for crispy peas and vegetables'],
'Smoothie supplements and specialty items':['Sea moss gel','Maca powder','Lucuma powder','Lion’s mane powder','Blue spirulina or Blue Majik','Ceremonial matcha','Lemon electrolytes','Ionic mineral silica, optional','Cacao']
};

export const MEAL_ANCHORS={
 breakfast:['Greek yogurt + berries','Smoothie','Chia pudding','Eggs + side'],
 lunch:['Protein bowl','Leftovers','Quick wrap'],
 dinner:['Stir fry','Rice bowl','Protein + veg + carb'],
 snack:['Greek yogurt','Bone broth','Fruit','Carrots','Smoothie']
};

export const MEAL_PREP_QUEUE=[
{id:'scan',title:'Fridge + pantry scan',seconds:300,parallelHint:'Mark use-soon and out-of-stock items.'},
{id:'produce',title:'Wash produce',seconds:600,parallelHint:'Start grains first if they need a long simmer.'},
{id:'quinoa',title:'Cook quinoa or another base',seconds:1200,parallelHint:'Chop vegetables while the grain cooks.'},
{id:'protein',title:'Prepare protein',seconds:900,parallelHint:'Mix a sauce or dressing while it cooks.'},
{id:'vegetables',title:'Chop vegetables',seconds:600},
{id:'chia',title:'Make chia pudding',seconds:300,parallelHint:'It can chill while you finish the rest.'},
{id:'smoothies',title:'Portion smoothie packs',seconds:600},
{id:'store',title:'Store components + leftovers',seconds:300}
];
