'use server';

import { auth } from '@/auth';
import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import { z } from 'zod';
import * as data from '@/lib/data/advanced-beauty';

async function requireUser() { const session = await auth(); if (!session?.user?.id) redirect('/sign-in'); return session.user.id; }
function refreshBeauty() { ['/beauty','/beauty/lab','/beauty/progress','/beauty/calendar','/dashboard','/today','/tomorrow','/routines','/habits','/calendar'].forEach((path)=>revalidatePath(path)); }

const startSchema=z.object({ritualKey:z.string().min(1).max(80),title:z.string().min(1).max(160),mode:z.enum(['full','standard','quick','minimum']),queueRoutineIds:z.array(z.string().min(1)).min(1).max(100),context:z.record(z.unknown()).optional()});
const stepSchema=z.object({runId:z.string().min(1),routineId:z.string().min(1),status:z.enum(['completed','skipped']),actualSeconds:z.number().int().min(0).max(7200),notes:z.string().max(1200).optional()});
const treatmentSchema=z.object({treatmentKey:z.string().min(1).max(100),treatmentName:z.string().min(1).max(180),area:z.string().min(1).max(80),productId:z.string().nullable().optional(),response:z.enum(['comfortable','neutral','irritating']).nullable().optional(),notes:z.string().max(2000).optional()});
const treatmentScheduleSchema=z.object({treatmentKey:z.string().min(1).max(100),treatmentName:z.string().min(1).max(180),area:z.string().min(1).max(80),weekdays:z.array(z.number().int().min(0).max(6)).max(7).optional(),cadenceDays:z.number().int().min(1).max(3650).nullable().optional(),nextDueAt:z.coerce.date().nullable().optional(),strongTreatment:z.boolean().optional(),notes:z.string().max(1500).optional()});
const maintenanceSchema=z.object({title:z.string().min(1).max(180),category:z.string().min(1).max(80),cadenceDays:z.number().int().min(1).max(3650).nullable().optional(),nextDueAt:z.coerce.date().nullable().optional(),notes:z.string().max(1500).optional(),source:z.string().max(80).optional()});
const lookSchema=z.object({name:z.string().min(1).max(180),occasion:z.string().min(1).max(80),mood:z.string().min(1).max(80),plannedMinutes:z.number().int().min(5).max(180),steps:z.array(z.string().min(1).max(180)).max(50),productIds:z.array(z.string()).max(50).optional(),notes:z.string().max(2000).optional()});
const fragranceSchema=z.object({name:z.string().min(1).max(180),family:z.string().max(100).optional(),productId:z.string().nullable().optional(),dayparts:z.array(z.string().max(50)).max(20).optional(),seasons:z.array(z.string().max(50)).max(20).optional(),moods:z.array(z.string().max(50)).max(20).optional(),occasions:z.array(z.string().max(50)).max(20).optional(),favorite:z.boolean().optional(),notes:z.string().max(1500).optional()});
const readinessSchema=z.object({context:z.string().min(1).max(80),checks:z.record(z.boolean())});
const observationSchema=z.object({kind:z.string().min(1).max(80),subject:z.string().min(1).max(160),confidence:z.string().max(40).optional(),body:z.string().min(1).max(3000),evidence:z.record(z.unknown()).optional()});

export async function startBeautyRitualAction(input:unknown){const userId=await requireUser();const parsed=startSchema.safeParse(input);if(!parsed.success)return{data:null,error:'Beauty routine could not start because its plan was invalid.'};const row=await data.startBeautyRitual(userId,parsed.data);if(!row)return{data:null,error:'Beauty routine has no valid saved steps.'};refreshBeauty();return{data:row,error:null};}
export async function recordBeautyStepAction(input:unknown){const userId=await requireUser();const parsed=stepSchema.safeParse(input);if(!parsed.success)return{data:null,error:'Glow could not save this Beauty step.'};const row=await data.recordBeautyStep(userId,parsed.data);if(!row)return{data:null,error:'This step is not part of the active Beauty ritual.'};refreshBeauty();return{data:row,error:null};}
export async function completeBeautyRitualAction(runId:string){const userId=await requireUser();const row=await data.completeBeautyRitual(userId,runId);if(!row)return{data:null,error:'Finish or intentionally skip every Beauty step before closing the ritual.'};refreshBeauty();return{data:row,error:null};}
export async function abandonBeautyRitualAction(runId:string){const userId=await requireUser();const row=await data.abandonBeautyRitual(userId,runId);refreshBeauty();return row?{data:row,error:null}:{data:null,error:'This Beauty ritual is no longer active.'};}
export async function logBeautyTreatmentAction(input:unknown){const userId=await requireUser();const parsed=treatmentSchema.safeParse(input);if(!parsed.success)return{data:null,error:'Treatment note is incomplete.'};const row=await data.logBeautyTreatment(userId,parsed.data);if(!row)return{data:null,error:'Glow could not verify the selected Beauty product.'};refreshBeauty();return{data:row,error:null};}
export async function createBeautyTreatmentScheduleAction(input:unknown){const userId=await requireUser();const parsed=treatmentScheduleSchema.safeParse(input);if(!parsed.success)return{data:null,error:'Treatment schedule is incomplete.'};const row=await data.createTreatmentSchedule(userId,parsed.data);refreshBeauty();return{data:row,error:null};}
export async function toggleBeautyTreatmentScheduleAction(id:string,enabled:boolean){const userId=await requireUser();const row=await data.toggleTreatmentSchedule(userId,id,enabled);refreshBeauty();return row?{data:row,error:null}:{data:null,error:'Treatment schedule was not found.'};}
export async function createBeautyMaintenanceAction(input:unknown){const userId=await requireUser();const parsed=maintenanceSchema.safeParse(input);if(!parsed.success)return{data:null,error:'Maintenance item is incomplete.'};const row=await data.createMaintenanceItem(userId,parsed.data);refreshBeauty();return{data:row,error:null};}
export async function completeBeautyMaintenanceAction(id:string){const userId=await requireUser();const row=await data.completeMaintenanceItem(userId,id);refreshBeauty();return row?{data:row,error:null}:{data:null,error:'Maintenance item was not found.'};}
export async function createBeautyLookAction(input:unknown){const userId=await requireUser();const parsed=lookSchema.safeParse(input);if(!parsed.success)return{data:null,error:'Look details are incomplete.'};const row=await data.createBeautyLook(userId,parsed.data);refreshBeauty();return{data:row,error:null};}
export async function useBeautyLookAction(id:string){const userId=await requireUser();const row=await data.useBeautyLook(userId,id);revalidatePath('/beauty/lab');return row?{data:row,error:null}:{data:null,error:'Saved look was not found.'};}
export async function createBeautyFragranceAction(input:unknown){const userId=await requireUser();const parsed=fragranceSchema.safeParse(input);if(!parsed.success)return{data:null,error:'Fragrance details are incomplete.'};const row=await data.createFragrance(userId,parsed.data);refreshBeauty();return row?{data:row,error:null}:{data:null,error:'Glow could not verify the selected product.'};}
export async function logBeautyReadinessAction(input:unknown){const userId=await requireUser();const parsed=readinessSchema.safeParse(input);if(!parsed.success)return{data:null,error:'Polished Check is incomplete.'};const row=await data.logBeautyReadiness(userId,parsed.data);refreshBeauty();return{data:row,error:null};}
export async function saveBeautyObservationAction(input:unknown){const userId=await requireUser();const parsed=observationSchema.safeParse(input);if(!parsed.success)return{data:null,error:'Beauty note is incomplete.'};const row=await data.saveBeautyObservation(userId,parsed.data);refreshBeauty();return{data:row,error:null};}
export async function dismissBeautyObservationAction(id:string){const userId=await requireUser();const row=await data.dismissBeautyObservation(userId,id);refreshBeauty();return row?{data:row,error:null}:{data:null,error:'Beauty observation was not found.'};}
