'use server';
import { auth } from '@/auth';
import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import { z } from 'zod';
import * as data from '@/lib/data/food-intelligence';

async function requireUser(){const session=await auth();if(!session?.user?.id)redirect('/sign-in');return session.user.id}
function refresh(){['/food','/today','/routines','/wellness','/fitness'].forEach(p=>revalidatePath(p))}
const uuid=z.string().uuid();
const inventorySchema=z.object({id:uuid,state:z.enum(['in_stock','out','use_soon','review']),quantity:z.number().min(0).max(9999).nullable().optional(),unit:z.string().max(40).nullable().optional()});
const grocerySchema=z.object({name:z.string().trim().min(1).max(160),category:z.string().trim().min(1).max(80),status:z.enum(['draft','listed']).optional(),quantity:z.number().min(0).max(9999).nullable().optional(),unit:z.string().max(40).nullable().optional(),source:z.string().max(40).optional()});
const groceryStatusSchema=z.object({id:uuid,status:z.enum(['draft','listed','completed'])});
const recipePrefSchema=z.object({id:uuid,favorite:z.boolean().optional(),rotation:z.enum(['reliable','try_again','new','retired']).optional(),rating:z.enum(['loved','good','fine','wouldnt_repeat']).nullable().optional(),feedback:z.array(z.enum(['easy_to_make','too_much_work','good_leftovers'])).max(3).optional()});
const mealPlanSchema=z.object({mealDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),mealType:z.enum(['breakfast','lunch','dinner','snack']),recipeId:uuid.nullable().optional(),title:z.string().trim().min(1).max(180),status:z.enum(['planned','ate','changed']).optional()});
const leftoverSchema=z.object({recipeId:uuid.nullable().optional(),title:z.string().trim().min(1).max(180),servingsRemaining:z.number().min(.25).max(100),expiresAt:z.string().datetime().nullable().optional()});
const prepStepSchema=z.object({runId:uuid,stepId:z.string().min(1).max(80),status:z.enum(['completed','skipped']),actualSeconds:z.number().int().min(0).max(3600)});
const customRecipeSchema=z.object({title:z.string().trim().min(1).max(180),primaryCategory:z.string().trim().min(1).max(60),categories:z.array(z.string().trim().min(1).max(60)).min(1).max(8),tags:z.array(z.string().trim().min(1).max(60)).max(12).optional(),ingredients:z.array(z.string().trim().min(1).max(160)).min(1).max(40),notes:z.string().max(1200).optional()});

export async function updateFoodInventoryAction(input:unknown){const userId=await requireUser();const p=inventorySchema.safeParse(input);if(!p.success)return{data:null,error:'Glow could not validate this pantry update.'};const row=await data.updateInventory(userId,p.data.id,p.data);refresh();return row?{data:row,error:null}:{data:null,error:'This pantry item was not found.'}}
export async function addFoodGroceryAction(input:unknown){const userId=await requireUser();const p=grocerySchema.safeParse(input);if(!p.success)return{data:null,error:'Grocery item is incomplete.'};const row=await data.addGrocery(userId,p.data);refresh();return row?{data:row,error:null}:{data:null,error:'Glow could not add this grocery item.'}}
export async function setFoodGroceryStatusAction(input:unknown){const userId=await requireUser();const p=groceryStatusSchema.safeParse(input);if(!p.success)return{data:null,error:'Glow could not validate this grocery update.'};const row=await data.setGroceryStatus(userId,p.data.id,p.data.status);refresh();return row?{data:row,error:null}:{data:null,error:'This grocery item was not found.'}}
export async function addAllFoodDraftGroceriesAction(){const userId=await requireUser();const rows=await data.addAllDraftGroceries(userId);refresh();return{data:rows,error:null}}
export async function setFoodRecipePreferenceAction(input:unknown){const userId=await requireUser();const p=recipePrefSchema.safeParse(input);if(!p.success)return{data:null,error:'Glow could not validate this recipe feedback.'};const {id,...rest}=p.data;const row=await data.setRecipePreference(userId,id,rest);refresh();return row?{data:row,error:null}:{data:null,error:'This recipe was not found.'}}
export async function recordFoodRecipeUseAction(id:string){const userId=await requireUser();const parsed=uuid.safeParse(id);if(!parsed.success)return{data:null,error:'Recipe ID is invalid.'};const row=await data.recordRecipeUse(userId,parsed.data);refresh();return row?{data:row,error:null}:{data:null,error:'This recipe was not found.'}}
export async function saveFoodMealPlanAction(input:unknown){const userId=await requireUser();const p=mealPlanSchema.safeParse(input);if(!p.success)return{data:null,error:'Glow could not validate this meal.'};const row=await data.saveMealPlan(userId,p.data);refresh();return row?{data:row,error:null}:{data:null,error:'Glow could not save this meal.'}}
export async function addFoodLeftoverAction(input:unknown){const userId=await requireUser();const p=leftoverSchema.safeParse(input);if(!p.success)return{data:null,error:'Glow could not validate these leftovers.'};const row=await data.addLeftover(userId,{...p.data,expiresAt:p.data.expiresAt?new Date(p.data.expiresAt):null});refresh();return row?{data:row,error:null}:{data:null,error:'Glow could not save these leftovers.'}}
export async function useFoodLeftoverAction(id:string,amount=1){const userId=await requireUser();const parsed=uuid.safeParse(id);if(!parsed.success||!Number.isFinite(amount)||amount<=0)return{data:null,error:'Glow could not validate this leftover update.'};const row=await data.useLeftover(userId,parsed.data,amount);refresh();return row?{data:row,error:null}:{data:null,error:'These leftovers were not found.'}}
export async function startFoodMealPrepAction(){const userId=await requireUser();const row=await data.startMealPrep(userId);refresh();return row?{data:row,error:null}:{data:null,error:'Glow could not start Meal Prep.'}}
export async function recordFoodMealPrepStepAction(input:unknown){const userId=await requireUser();const p=prepStepSchema.safeParse(input);if(!p.success)return{data:null,error:'Glow could not validate this Meal Prep step.'};const row=await data.recordMealPrepStep(userId,p.data);refresh();return row?{data:row,error:null}:{data:null,error:'This step is not part of the active Meal Prep run.'}}
export async function completeFoodMealPrepAction(id:string){const userId=await requireUser();const parsed=uuid.safeParse(id);if(!parsed.success)return{data:null,error:'Meal Prep run is invalid.'};const row=await data.completeMealPrep(userId,parsed.data);refresh();return row?{data:row,error:null}:{data:null,error:'Finish or intentionally skip every Meal Prep step before closing it.'}}
export async function abandonFoodMealPrepAction(id:string){const userId=await requireUser();const parsed=uuid.safeParse(id);if(!parsed.success)return{data:null,error:'Meal Prep run is invalid.'};const row=await data.abandonMealPrep(userId,parsed.data);refresh();return row?{data:row,error:null}:{data:null,error:'Meal Prep is no longer active.'}}
export async function createFoodCustomRecipeAction(input:unknown){const userId=await requireUser();const p=customRecipeSchema.safeParse(input);if(!p.success)return{data:null,error:'Glow could not validate this recipe.'};const row=await data.createCustomRecipe(userId,p.data);refresh();return row?{data:row,error:null}:{data:null,error:'Glow could not save this recipe.'}}
