'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { z } from 'zod';
import { auth } from '@/auth';
import * as brain from '@/lib/data/second-brain';

async function requireUser(){const session=await auth();if(!session?.user?.id)redirect('/sign-in');return session.user.id}
function refresh(){['/second-brain','/brain','/tasks','/notes','/calendar','/goals','/projects','/memory','/today','/dashboard','/search'].forEach(path=>revalidatePath(path))}
const fail=(error:string)=>({data:null,error});
const ok=<T,>(data:T)=>({data,error:null as string|null});

export async function captureBrainDumpAction(raw:unknown){const userId=await requireUser();const parsed=z.object({text:z.string().min(2).max(12000),source:z.string().max(40).optional()}).safeParse(raw);if(!parsed.success)return fail('Glow needs something to capture.');const data=await brain.createCapture(userId,parsed.data.text,parsed.data.source);revalidatePath('/second-brain');return ok(data)}
export async function acceptBrainCaptureAction(raw:unknown){const userId=await requireUser();const parsed=z.object({captureId:z.string().min(1),kinds:z.array(z.enum(['task','decision','idea','loop','memory','note'])).min(1)}).safeParse(raw);if(!parsed.success)return fail('Choose what Glow should organize.');const data=await brain.acceptCaptureItems(userId,parsed.data.captureId,parsed.data.kinds);if(!data)return fail('That brain dump is unavailable.');refresh();return ok(data)}
export async function keepBrainDumpAction(captureId:string){const userId=await requireUser();const state=await brain.getBrainState(userId);const capture=state.captures.find(x=>x.id===captureId);if(!capture)return fail('Brain dump unavailable.');const data=await brain.addThought(userId,{title:brain.titleFromText(capture.rawText),body:capture.rawText,kind:'thought',captureId});refresh();return ok(data)}
export async function createBrainThoughtAction(raw:unknown){const userId=await requireUser();const parsed=z.object({title:z.string().min(1).max(300),body:z.string().max(6000).optional(),kind:z.enum(['thought','idea']).default('thought'),threadTitle:z.string().max(200).optional()}).safeParse(raw);if(!parsed.success)return fail('Glow could not save that thought.');const data=await brain.addThought(userId,parsed.data);refresh();return ok(data)}
export async function updateBrainThoughtAction(raw:unknown){const userId=await requireUser();const parsed=z.object({id:z.string().min(1),lifecycle:z.enum(['captured','exploring','decision_needed','decided','actioned','archived']).optional(),maturity:z.enum(['seed','growing','developed','ready','project','archived']).optional()}).safeParse(raw);if(!parsed.success)return fail('Glow could not update that thought.');let data=null;if(parsed.data.lifecycle)data=await brain.updateThoughtLifecycle(userId,parsed.data.id,parsed.data.lifecycle);if(parsed.data.maturity)data=await brain.updateIdeaMaturity(userId,parsed.data.id,parsed.data.maturity);refresh();return data?ok(data):fail('Thought unavailable.')}
export async function archiveBrainThoughtAction(id:string){const userId=await requireUser();const data=await brain.archiveThought(userId,id);refresh();return data?ok(data):fail('Thought unavailable.')}
export async function createBrainDecisionAction(raw:unknown){const userId=await requireUser();const parsed=z.object({question:z.string().min(2).max(500),threadTitle:z.string().max(200).optional(),decisionType:z.enum(['permanent','trial','temporary','until_date','revisit_later']).optional()}).safeParse(raw);if(!parsed.success)return fail('Glow could not create that decision.');const data=await brain.addDecision(userId,parsed.data);refresh();return ok(data)}
export async function decideBrainDecisionAction(raw:unknown){const userId=await requireUser();const parsed=z.object({id:z.string().min(1),outcome:z.string().min(1).max(1200),rationale:z.string().max(2400).optional(),decisionType:z.enum(['permanent','trial','temporary','until_date','revisit_later']).optional(),reviewAt:z.string().datetime().nullable().optional()}).safeParse(raw);if(!parsed.success)return fail('Glow could not save that decision.');const data=await brain.decide(userId,parsed.data.id,{outcome:parsed.data.outcome,rationale:parsed.data.rationale,decisionType:parsed.data.decisionType,reviewAt:parsed.data.reviewAt?new Date(parsed.data.reviewAt):null});refresh();return data?ok(data):fail('Decision unavailable.')}
export async function createBrainLoopAction(raw:unknown){const userId=await requireUser();const parsed=z.object({title:z.string().min(1).max(500),loopType:z.enum(['action','waiting','schedule','buy','research','finish']).optional(),waitingOn:z.string().max(200).optional(),followUpAt:z.string().datetime().nullable().optional()}).safeParse(raw);if(!parsed.success)return fail('Glow could not create that open loop.');const data=await brain.addLoop(userId,{...parsed.data,followUpAt:parsed.data.followUpAt?new Date(parsed.data.followUpAt):null});refresh();return ok(data)}
export async function updateBrainLoopAction(raw:unknown){const userId=await requireUser();const parsed=z.object({id:z.string().min(1),status:z.enum(['open','waiting','closed','dropped']),waitingOn:z.string().max(200).optional()}).safeParse(raw);if(!parsed.success)return fail('Glow could not update that loop.');const data=await brain.updateLoop(userId,parsed.data.id,parsed.data.status,parsed.data.waitingOn);refresh();return data?ok(data):fail('Open loop unavailable.')}
export async function addBrainPersonAction(raw:unknown){const userId=await requireUser();const parsed=z.object({name:z.string().min(1).max(160),context:z.string().max(1200).optional()}).safeParse(raw);if(!parsed.success)return fail('Glow could not save that person.');const data=await brain.addPerson(userId,parsed.data.name,parsed.data.context);refresh();return ok(data)}
export async function saveBrainMemoryAction(raw:unknown){const userId=await requireUser();const parsed=z.object({title:z.string().min(1).max(300),content:z.string().min(1).max(5000),memoryType:z.enum(['preference','important_fact','decision','relationship_context','long_term_goal']).optional(),sourceType:z.string().max(60).optional(),sourceId:z.string().max(100).optional(),reason:z.string().max(1000).optional()}).safeParse(raw);if(!parsed.success)return fail('Glow could not save that memory.');const data=await brain.addMemory(userId,parsed.data);refresh();return ok(data)}
export async function forgetBrainMemoryAction(id:string){const userId=await requireUser();const data=await brain.forgetMemory(userId,id);refresh();return data?ok(data):fail('Memory unavailable.')}
export async function connectBrainItemsAction(raw:unknown){const userId=await requireUser();const parsed=z.object({fromType:z.string().min(1).max(60),fromId:z.string().min(1),toType:z.string().min(1).max(60),toId:z.string().min(1),relation:z.enum(['supports','part_of','depends_on','related_to','created_by','blocked_by','inspired_by']),reason:z.string().max(1000).optional()}).safeParse(raw);if(!parsed.success)return fail('Glow could not connect those items.');const data=await brain.connect(userId,parsed.data);refresh();return ok(data??{existing:true})}
export async function createBrainWorkspaceAction(raw:unknown){const userId=await requireUser();const parsed=z.object({question:z.string().min(2).max(2000),criteria:z.array(z.string().min(1).max(120)).max(12).optional()}).safeParse(raw);if(!parsed.success)return fail('Glow needs a question to think through.');const data=await brain.createThinkingWorkspace(userId,parsed.data);refresh();return ok(data)}
export async function askMyBrainAction(raw:unknown){const userId=await requireUser();const parsed=z.object({query:z.string().min(2).max(1000)}).safeParse(raw);if(!parsed.success)return fail('Ask your Brain a question.');const state=await brain.getBrainState(userId);const data=await brain.deriveBrainAnswer(state,parsed.data.query);return ok(data)}
