import Link from 'next/link';
import { auth } from '@/auth';
import { redirect } from 'next/navigation';
import { desc, eq } from 'drizzle-orm';
import { AppShell } from '@/components/app-shell';
import { db } from '@/db';
import { entityRelations } from '@/db/schema/adaptive-os';
import { glowEntities } from '@/db/schema/interconnected-os';
import { getTasksByUser } from '@/lib/data/tasks';
import { Home, Search } from 'lucide-react';

export const dynamic='force-dynamic';
const networkPos=[[50,8],[76,18],[84,43],[78,70],[50,83],[21,70],[15,43],[23,18]] as const;
const SERIES=[['Productivity','#74556d'],['Wellness','#66755f'],['Mind','#cc8292'],['Other','#6d88a7']] as const;
function label(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}
function groupType(type:string){const t=type.toLowerCase();if(/well|habit|fitness|sleep|mood|food|med|beauty|hair/.test(t))return'Wellness';if(/task|project|goal|work|planning|calendar/.test(t))return'Productivity';if(/note|memory|brain|observation|decision|knowledge/.test(t))return'Mind';return'Other'}
function weekKey(date:Date,now:Date){const diff=Math.floor((now.getTime()-date.getTime())/86400000);return Math.min(4,Math.max(0,4-Math.floor(diff/7)))}
function pct(part:number,total:number){return total?Math.max(0,Math.min(100,Math.round(part/total*100))):0}

export default async function GraphPage({searchParams}:{searchParams:Promise<{view?:string}>}){
 const s=await auth();if(!s?.user?.id)redirect('/sign-in');const params=await searchParams;
 let entities;let relations;try{[entities,relations]=await Promise.all([db.select().from(glowEntities).where(eq(glowEntities.userId,s.user.id)).orderBy(desc(glowEntities.updatedAt)).limit(240),db.select().from(entityRelations).where(eq(entityRelations.userId,s.user.id)).orderBy(desc(entityRelations.createdAt)).limit(240)])}catch{return <AppShell><div className="b10-card p-5 text-[10px]">Graph needs intelligence activation. <Link href="/settings/intelligence" className="text-[#874555]">Activate →</Link></div></AppShell>}
 const tasks=await getTasksByUser(s.user.id);const done=tasks.filter(t=>t.status==='done').length;
 if(params.view==='connections'){
  const typeCounts=entities.reduce<Record<string,number>>((a,e)=>(a[e.entityType]=(a[e.entityType]??0)+1,a),{});const nodes=Object.entries(typeCounts).sort((a,b)=>b[1]-a[1]).slice(0,8);const center=entities[0];
  return <AppShell><div className="b10-root"><header className="b10-head"><div><p className="b10-eyebrow">7. GRAPH · CONNECTIONS</p><h1>Your Life Graph</h1><p>See how your Glow objects relate.</p></div><Link href="/graph" className="b10-soft">Activity View</Link></header><section className="batch2-card batch2-graph-stage"><svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><g stroke="#e7dcd6" strokeWidth=".25">{nodes.map((_,i)=><line key={i} x1="50" y1="50" x2={networkPos[i][0]} y2={networkPos[i][1]}/>)}</g></svg><Link href={center?`/search?q=${encodeURIComponent(center.title??center.entityType)}`:'/dashboard'} className="batch2-graph-center z-10"><div className="text-center text-white"><p className="font-serif text-[16px]">{center?.title||'Your Life'}</p><p className="mt-1 text-[7px] uppercase tracking-[.12em] opacity-80">{center?label(center.entityType):'Glow Graph'}</p></div></Link>{nodes.map(([name,count],i)=><Link key={name} href={`/search?q=${encodeURIComponent(name)}`} className="batch2-node z-20" style={{left:`calc(${networkPos[i][0]}% - 44px)`,top:`calc(${networkPos[i][1]}% - 32px)`}}><span><span className="block text-[8px] font-medium">{label(name)}</span><span className="mt-1 block text-[7px] text-[#a0958e]">{count} objects</span></span></Link>)}<div className="absolute bottom-3 left-3 flex gap-2"><Link href="/dashboard" className="batch2-btn p-2" aria-label="Dashboard"><Home size={11}/></Link><Link href="/search" className="batch2-btn p-2" aria-label="Search"><Search size={11}/></Link></div><div className="absolute bottom-3 right-3 text-[8px] text-[#9b9089]">{entities.length} objects · {relations.length} stored links</div></section></div></AppShell>;
 }
 const now=new Date();const counts:Record<string,number[]>=Object.fromEntries(SERIES.map(([name])=>[name,[0,0,0,0,0]]));for(const e of entities){const idx=weekKey(e.updatedAt,now);counts[groupType(e.entityType)][idx]++}
 const max=Math.max(1,...Object.values(counts).flat());const points=(name:string)=>counts[name].map((v,i)=>`${i*25},${92-(v/max)*72}`).join(' ');
 const productivity=entities.filter(e=>groupType(e.entityType)==='Productivity').length;const wellness=entities.filter(e=>groupType(e.entityType)==='Wellness').length;const mind=entities.filter(e=>groupType(e.entityType)==='Mind').length;const total=entities.length;
 const money=entities.filter(e=>/finance|money|transaction|budget/.test(e.entityType.toLowerCase())).length;
 const rings=[['Life',pct(productivity,total)],['Mind',pct(mind,total)],['Wellness',pct(wellness,total)],['Money',pct(money,total)],['Linked',pct(Math.min(relations.length,total),total)]] as const;
 return <AppShell><div className="b10-root b10-life-graph"><header className="b10-head"><div><p className="b10-eyebrow">7. GRAPH</p><h1>Your Life Graph</h1><p>Five weeks of recorded Glow object activity.</p></div><div className="b10-graph-controls"><span>5-week window</span><span>Connected objects</span><Link href="/graph?view=connections">Connections</Link></div></header><div className="b10-graph-metrics"><div><small>Productivity Objects</small><strong>{productivity}</strong><span>{entities.length?'Current graph':'No data'}</span></div><div><small>Wellness Objects</small><strong>{wellness}</strong><span>{entities.length?'Current graph':'No data'}</span></div><div><small>Mind Objects</small><strong>{mind}</strong><span>{entities.length?'Current graph':'No data'}</span></div><div><small>Tasks Done</small><strong>{done}</strong><span>{tasks.length?'Saved tasks':'No tasks'}</span></div></div><section className="b10-card b10-graph-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Five week Glow object activity"><g>{[20,40,60,80].map(y=><line key={y} x1="0" x2="100" y1={y} y2={y}/>)}</g>{SERIES.map(([name,color])=><polyline key={name} points={points(name)} stroke={color}/>)}</svg><div className="b10-graph-axis">{[28,21,14,7,0].map(d=><span key={d}>{new Date(now.getTime()-d*86400000).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span>)}</div><div className="b10-graph-legend">{SERIES.map(([name,color])=><span key={name}><i style={{background:color}}/>{name}</span>)}</div></section><h2 className="b10-section-title">Current Graph Mix</h2><div className="b10-graph-rings">{rings.map(([name,value])=><div key={name}><div className="b10-mini-ring" style={{background:`conic-gradient(#76516b ${value*3.6}deg,#eee7e2 0)`}}><span>{value}%</span></div><small>{name}</small></div>)}</div><Link href="/graph?view=connections" className="b10-view-all">View Connection Graph →</Link></div></AppShell>;
}
