import Link from 'next/link';
import { auth } from '@/auth';
import { redirect } from 'next/navigation';
import { desc, eq } from 'drizzle-orm';
import { AppShell } from '@/components/app-shell';
import { db } from '@/db';
import { entityRelations } from '@/db/schema/adaptive-os';
import { glowEntities } from '@/db/schema/interconnected-os';
import { Network, Sparkles } from 'lucide-react';

export const dynamic='force-dynamic';

export default async function GraphPage(){
  const session=await auth();if(!session?.user?.id)redirect('/sign-in');
  let entities;let relations;
  try{[entities,relations]=await Promise.all([db.select().from(glowEntities).where(eq(glowEntities.userId,session.user.id)).orderBy(desc(glowEntities.updatedAt)).limit(60),db.select().from(entityRelations).where(eq(entityRelations.userId,session.user.id)).orderBy(desc(entityRelations.createdAt)).limit(80)]);}catch{return <AppShell><div className="mx-auto max-w-4xl rounded-[22px] border border-amber-200 bg-amber-50 p-6"><p className="text-sm font-semibold">The Glow Relationship Graph needs intelligence activation.</p><Link href="/settings/intelligence" className="mt-3 inline-block text-xs text-amber-900">Activate intelligence →</Link></div></AppShell>;}
  const labels=new Map(entities.map(e=>[`${e.entityType}:${e.sourceId??e.id}`,e.title]));
  return <AppShell><div className="mx-auto max-w-6xl space-y-5"><header><div className="flex items-center gap-2 text-violet-700"><Network size={18}/><p className="text-[9px] font-bold uppercase tracking-[.2em]">Universal Intelligence Graph</p></div><h1 className="glow-display mt-2 text-[42px] leading-none text-[#392e2a]">Everything can understand everything else.</h1><p className="mt-2 max-w-3xl text-[10px] leading-5 text-[#7e6b64]">Glow stores relationships between captured information and the systems it creates. That lets a single appointment, purchase, project or memory become useful in more than one room without duplicate entry.</p></header><section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[22px] border border-[#e4d7cf] bg-white/72 p-5"><div className="flex items-center justify-between"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#7d675f]">Entities</p><span className="text-[8px] text-[#9c8780]">{entities.length}</span></div><div className="mt-3 flex flex-wrap gap-2">{entities.length?entities.map(entity=><span key={entity.id} className="rounded-full border border-[#e5d8d0] bg-[#faf5f1] px-3 py-1.5 text-[8px] text-[#6e5a53]">{entity.title}<span className="ml-1 text-[#aa9188]">· {entity.entityType}</span></span>):<p className="text-[9px] text-[#8d7972]">Use Universal Intake and route items to begin building the graph.</p>}</div></div><div className="rounded-[22px] border border-[#e4d7cf] bg-white/72"><div className="flex items-center justify-between border-b border-[#eadfd6] px-4 py-3"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#7d675f]">Relationships</p><span className="text-[8px] text-[#9c8780]">{relations.length}</span></div><div className="divide-y divide-[#eee4dd]">{relations.length?relations.map(rel=><div key={rel.id} className="grid gap-2 px-4 py-3 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><div><p className="text-[9px] font-medium text-[#4b3d37]">{labels.get(`${rel.fromType}:${rel.fromId}`)??rel.fromType}</p><p className="text-[7px] text-[#9c8780]">{rel.fromType}</p></div><span className="rounded-full bg-violet-50 px-2 py-1 text-center text-[7px] font-bold uppercase text-violet-700">{rel.relation}</span><div className="sm:text-right"><p className="text-[9px] font-medium text-[#4b3d37]">{labels.get(`${rel.toType}:${rel.toId}`)??rel.toType}</p><p className="text-[7px] text-[#9c8780]">{rel.toType}</p></div></div>):<div className="p-8 text-center"><Sparkles size={18} className="mx-auto text-violet-500"/><p className="mt-2 text-[9px] text-[#8d7972]">Relationships appear when Glow routes intake or connects systems.</p></div>}</div></div></section><div className="flex gap-2"><Link href="/intake" className="rounded-lg bg-[#40352f] px-3 py-2 text-[8px] text-white">Add Anything</Link><Link href="/inbox" className="rounded-lg border border-[#dfd1c9] bg-white/70 px-3 py-2 text-[8px] text-[#6d5952]">Route Inbox</Link></div></div></AppShell>;
}
