'use client';

import { useEffect, useState, type CSSProperties } from 'react';
import Link from 'next/link';
import { Accessibility, Bell, Bot, Cloud, Database, Eye, FlaskConical, LayoutPanelTop, Lock, Mic, Navigation, Palette, RotateCcw, Search, Sparkles, Waves } from 'lucide-react';
import { styles as shell } from '@/components/system-reference/utility-frame';
import styles from './appearance-reference.module.css';

const KEY='glow-appearance-v2';
type Mode='system'|'light'|'dark';
type Mood='serene'|'focused'|'creative'|'minimal';
type Backdrop='aurora'|'dawn'|'orbit'|'none';
type ToggleKey='reduceMotion'|'highContrast'|'gradients';
type Appearance={mode:Mode;accent:string;density:number;cornerRadius:number;glassDepth:number;reduceMotion:boolean;highContrast:boolean;gradients:boolean;mood:Mood;backdrop:Backdrop};
const defaults:Appearance={mode:'system',accent:'ocean',density:50,cornerRadius:18,glassDepth:64,reduceMotion:false,highContrast:false,gradients:true,mood:'serene',backdrop:'aurora'};
const accents=[['pearl','#d8cfe9'],['lilac','#cfc9e8'],['sky','#a9cbe7'],['sage','#a6cebd'],['ocean','#64afe1'],['violet','#aaa0df'],['rose','#daa6b7'],['sand','#d0af9b'],['graphite','#7e8793']] as const;
const moodThumbs:Record<Mood,string>={serene:'linear-gradient(145deg,#eef1ff,#f5dfe8,#ffe5c9)',focused:'linear-gradient(145deg,#eef3f7,#ccd9e8,#fafafa)',creative:'linear-gradient(145deg,#ffd9cb,#f1bdd7,#ffe3a9)',minimal:'linear-gradient(145deg,#f6f6f6,#dcdcdc,#fff)'};
const backdropThumbs:Record<Backdrop,string>={aurora:'linear-gradient(145deg,#cfe9ff,#e8c9f4,#ffd9c5)',dawn:'linear-gradient(145deg,#fff0da,#f6d9cf,#e5e8fa)',orbit:'linear-gradient(145deg,#cad1df,#aaa9c1,#ded9dc)',none:'linear-gradient(#f2efec,#f2efec)'};

function read():Appearance{try{const raw=localStorage.getItem(KEY);return raw?{...defaults,...JSON.parse(raw)}:defaults}catch{return defaults}}
function apply(value:Appearance){const root=document.documentElement;root.dataset.glowThemeMode=value.mode;root.dataset.glowAccent=value.accent;root.dataset.glowReduceMotion=String(value.reduceMotion);root.dataset.glowHighContrast=String(value.highContrast);root.dataset.glowGradients=String(value.gradients);root.dataset.glowMood=value.mood;root.dataset.glowBackdrop=value.backdrop;root.style.setProperty('--glow-user-radius',`${value.cornerRadius}px`);root.style.setProperty('--glow-glass-depth',String(value.glassDepth/100));root.style.setProperty('--glow-density-scale',String(.88+(value.density/100)*.24));root.style.setProperty('--glow-accent-color',accents.find(([name])=>name===value.accent)?.[1]??'#64afe1')}

export function AppearanceReference(){
  const [value,setValue]=useState<Appearance>(defaults);const [ready,setReady]=useState(false);
  useEffect(()=>{const next=read();setValue(next);apply(next);setReady(true)},[]);
  useEffect(()=>{if(!ready)return;localStorage.setItem(KEY,JSON.stringify(value));apply(value);document.dispatchEvent(new CustomEvent('glow:appearance-changed',{detail:value}))},[value,ready]);
  const set=<K extends keyof Appearance>(key:K,next:Appearance[K])=>setValue(current=>({...current,[key]:next}));
  const toggle=(key:ToggleKey)=>setValue(current=>({...current,[key]:!current[key]}));
  const reset=()=>setValue(defaults);
  const menu=[['Appearance',Palette,'/settings'],['Page climates',Cloud,'/settings/system#appearance'],['Motion',Waves,'/settings/system#appearance'],['Voice',Mic,'/settings/system#ai'],['Aura intensity',Sparkles,'/settings/system#appearance'],['Glow personality',Bot,'/settings/system#ai'],['AI initiative',Bot,'/settings/system#ai'],['Privacy',Lock,'/settings/system#privacy'],['Data',Database,'/settings/system#data'],['Notifications',Bell,'/settings/system#notifications'],['Accessibility',Accessibility,'/settings/system#privacy'],['Integrations',LayoutPanelTop,'/connections'],['Navigation',Navigation,'/settings/system'],['Page visibility',Eye,'/settings/system'],['Experimental features',FlaskConical,'/settings/system']] as const;
  const toggles:{label:string;note:string;key:ToggleKey}[]=[{label:'Reduce motion',note:'Minimize spatial animation.',key:'reduceMotion'},{label:'High contrast outlines',note:'Improve control clarity.',key:'highContrast'},{label:'Show page gradients',note:'Subtle atmospheric color.',key:'gradients'}];
  return <div className={styles.settings}>
    <aside className={`${shell.glass} ${styles.rail}`}><div className={styles.search}><Search size={15}/><input placeholder="Search settings…" aria-label="Search settings"/></div><nav className={styles.menu}>{menu.map(([label,Icon,href])=><Link key={label} href={href} data-active={label==='Appearance'?'true':'false'}><Icon size={17}/>{label}</Link>)}</nav><Link href="/settings/system" className={`${shell.well} ${styles.buildLink}`}><span className={shell.pearl}/><div><strong>Glow OS controls</strong><p className={shell.sectionNote}>AI, privacy, notifications, and data.</p></div></Link></aside>
    <main className={styles.main}>
      <header className={styles.hero}><div><h1>Appearance</h1><p>Shape your visual world.</p></div><div className={`${shell.glass} ${styles.quote}`}><p>A more peaceful you<br/>makes a brighter tomorrow.<br/><span className={shell.tiny}>— Glow</span></p><span className={shell.pearlLg}/></div></header>
      <div className={styles.previewGrid}><section className={`${shell.glass} ${styles.panel}`}><h2 className={styles.panelTitle}>Theme</h2><div className={styles.theme}>{(['system','light','dark'] as const).map(mode=><button key={mode} type="button" data-active={value.mode===mode?'true':'false'} onClick={()=>set('mode',mode)}>{mode[0].toUpperCase()+mode.slice(1)}</button>)}</div><h2 className={styles.panelTitle} style={{marginTop:18}}>Accent color</h2><div className={styles.accentRow}>{accents.map(([name,color])=><button key={name} type="button" className={styles.accentOption} data-active={value.accent===name?'true':'false'} onClick={()=>set('accent',name)}><span className={styles.swatch} style={{'--swatch':`radial-gradient(circle at 30% 24%,#fff,${color} 65%,#fff)`} as CSSProperties}/>{value.accent===name?<span>{name[0].toUpperCase()+name.slice(1)}</span>:null}</button>)}</div><div className={styles.density}><h2 className={styles.panelTitle}>Interface density</h2><input style={{width:'100%'}} type="range" min="0" max="100" value={value.density} onChange={e=>set('density',Number(e.target.value))}/><div className={styles.rangeLabels}><span>More compact</span><span>Balanced</span><span>More spacious</span></div></div></section><section className={`${shell.glass} ${styles.preview}`}><div className={styles.previewScreen}><div className={styles.previewRail}/><div className={styles.previewWorld}/></div><div className={styles.previewLabel}><strong>Live preview</strong><p className={shell.sectionNote}>Changes apply to shared Glow appearance tokens in real time.</p></div></section></div>
      <div className={styles.two}><section className={`${shell.glass} ${styles.control}`}><div className={styles.controlHead}><h3>Corner radius</h3><span className={styles.value}>{value.cornerRadius}</span></div><input style={{width:'100%',marginTop:12}} type="range" min="8" max="34" value={value.cornerRadius} onChange={e=>set('cornerRadius',Number(e.target.value))}/></section><section className={`${shell.glass} ${styles.control}`}><div className={styles.controlHead}><h3>Glass depth</h3><span className={styles.value}>{value.glassDepth}%</span></div><input style={{width:'100%',marginTop:12}} type="range" min="0" max="100" value={value.glassDepth} onChange={e=>set('glassDepth',Number(e.target.value))}/><div className={styles.rangeLabels}><span>Subtle</span><span>Clear</span><span>Deep</span></div></section></div>
      <section className={styles.toggleRows}>{toggles.map(item=><div key={item.key} className={`${shell.glass} ${styles.toggleCard}`}><div><strong>{item.label}</strong><p>{item.note}</p></div><button type="button" className={styles.switch} data-on={value[item.key]?'true':'false'} onClick={()=>toggle(item.key)} aria-label={`Toggle ${item.label}`}/></div>)}</section>
      <div className={styles.two}><section className={`${shell.glass} ${styles.control}`}><h3 className={styles.panelTitle}>Interface mood</h3><p className={shell.sectionNote}>Choose the feeling of the workspace, not a second architecture.</p><div className={styles.moods}>{(Object.keys(moodThumbs) as Mood[]).map(mood=><button key={mood} type="button" className={styles.visualChoice} data-active={value.mood===mood?'true':'false'} onClick={()=>set('mood',mood)}><div className={styles.thumb} style={{'--thumb':moodThumbs[mood]} as CSSProperties}/>{mood[0].toUpperCase()+mood.slice(1)}</button>)}</div></section><section className={`${shell.glass} ${styles.control}`}><h3 className={styles.panelTitle}>Ambient backdrop</h3><p className={shell.sectionNote}>Adds a soft, living atmosphere.</p><div className={styles.backdrops}>{(Object.keys(backdropThumbs) as Backdrop[]).map(backdrop=><button key={backdrop} type="button" className={styles.visualChoice} data-active={value.backdrop===backdrop?'true':'false'} onClick={()=>set('backdrop',backdrop)}><div className={styles.thumb} style={{'--thumb':backdropThumbs[backdrop]} as CSSProperties}/>{backdrop[0].toUpperCase()+backdrop.slice(1)}</button>)}</div></section></div>
      <footer className={styles.footer}><button type="button" className={shell.btn} onClick={reset}><RotateCcw size={13}/>Reset to defaults</button></footer>
    </main>
  </div>;
}
