import { planWholeAppMigration } from './batch-h-auto-migration';

export type CensusStatus='COMPLETE'|'NEEDS_MIGRATION'|'NEEDS_FUNCTION'|'NEEDS_DATA'|'NEEDS_VISUAL'|'EXCEPTION'|'OBSOLETE'|'BLOCKED';
export type GlowCensusEvidence={file:string;route?:string;family?:string;room?:string;experience?:string;build:boolean;canonicalData:boolean;functional:boolean;visual:boolean;exception?:boolean;obsolete?:boolean;blocked?:boolean;blockers?:string[]};
export type GlowCensusRecord=GlowCensusEvidence&{status:CensusStatus};
export function classifyCensus(e:GlowCensusEvidence):CensusStatus{if(e.blocked)return'BLOCKED';if(e.exception)return'EXCEPTION';if(e.obsolete)return'OBSOLETE';if(!e.build)return'NEEDS_MIGRATION';if(!e.canonicalData)return'NEEDS_DATA';if(!e.functional)return'NEEDS_FUNCTION';if(!e.visual)return'NEEDS_VISUAL';return'COMPLETE';}
export function buildGlowCensus(evidence:GlowCensusEvidence[]){const records:GlowCensusRecord[]=evidence.map(e=>({...e,status:classifyCensus(e)}));const counts=records.reduce<Record<CensusStatus,number>>((a,x)=>{a[x.status]=(a[x.status]??0)+1;return a;},{COMPLETE:0,NEEDS_MIGRATION:0,NEEDS_FUNCTION:0,NEEDS_DATA:0,NEEDS_VISUAL:0,EXCEPTION:0,OBSOLETE:0,BLOCKED:0});return {records,counts,total:records.length,complete:counts.COMPLETE,completionPercent:records.length?Math.round(counts.COMPLETE/records.length*100):0};}
export function repositoryCensusSeed(files:string[]){const migration=planWholeAppMigration(files);return {migration,routeCount:migration.scan.routes.length,surfaceCount:migration.scan.surfaces.length,automaticCount:migration.automatic.length,exceptionCount:migration.exceptions.length};}
export const BATCH_V={steps:{117:'real-glow-census',118:'authoritative-completion-registry',119:'surface-status-classification',120:'real-denominator-and-remaining-work'},law:'Glow completion is measured from repository and QA evidence. Unknown evidence remains unfinished; it is never converted into a fabricated pass.'} as const;

export type BlockerEvidence={surface:string;family:string;blocker:string;owner:string;severity:'BLOCKER'|'HIGH'|'MEDIUM';repairableAtAncestor:boolean};
export function rankGlowBlockers(items:BlockerEvidence[]){const groups=new Map<string,BlockerEvidence[]>();for(const x of items){const key=`${x.owner}::${x.blocker}`;(groups.get(key)??groups.set(key,[]).get(key)!).push(x);}return [...groups.entries()].map(([key,evidence])=>({key,owner:evidence[0].owner,blocker:evidence[0].blocker,severity:evidence.some(x=>x.severity==='BLOCKER')?'BLOCKER':evidence.some(x=>x.severity==='HIGH')?'HIGH':'MEDIUM',affectedSurfaces:[...new Set(evidence.map(x=>x.surface))],families:[...new Set(evidence.map(x=>x.family))],impact:new Set(evidence.map(x=>x.surface)).size,repairableAtAncestor:evidence.every(x=>x.repairableAtAncestor)})).sort((a,b)=>({BLOCKER:0,HIGH:1,MEDIUM:2}[a.severity]-{BLOCKER:0,HIGH:1,MEDIUM:2}[b.severity]||b.impact-a.impact);}
export function nextBlockerWave(items:BlockerEvidence[],limit=5){const ranked=rankGlowBlockers(items);return {ranked,top:ranked.slice(0,limit),estimatedSurfaceImpact:ranked.slice(0,limit).reduce((n,x)=>n+x.impact,0)};}
export const BATCH_W={steps:{121:'collect-real-blockers',122:'rank-by-severity-and-impact',123:'repair-highest-shared-ancestor',124:'retest-and-recalculate-census'},law:'The next unit of work is the highest-impact shared blocker, not the next arbitrary page. Repair ancestors once, retest descendants, then recalculate the census.'} as const;

export const V_W_LOOP=['scan-real-repository','build-census','collect-missing-evidence-as-unfinished','extract-blockers','group-by-shared-owner','rank-by-severity-and-impact','repair-top-shared-owner','retest-affected-descendants','recalculate-census','repeat'] as const;
