export type FamilyCompletionEvidence={family:string;experience:string;migrated:boolean;data:boolean;intelligence:boolean;functional:boolean;visual:boolean;qa:boolean;exception:boolean;locked:boolean;blockers:string[]};
export function buildFamilyCompletionWaves(items:FamilyCompletionEvidence[]){const families=new Map<string,FamilyCompletionEvidence[]>();for(const x of items){const group=families.get(x.family);if(group)group.push(x);else families.set(x.family,[x]);}return [...families.entries()].map(([family,experiences])=>{const ordinary=experiences.filter(x=>!x.exception);const exceptions=experiences.filter(x=>x.exception);const passed=ordinary.every(x=>x.migrated&&x.data&&x.intelligence&&x.functional&&x.visual&&x.qa);return {family,experiences,ordinary,exceptions,passed,canLock:passed&&exceptions.every(x=>x.qa)&&experiences.every(x=>x.locked||x.qa),blockers:[...new Set(experiences.flatMap(x=>x.blockers))]};});}
export const FAMILY_COMPLETION_ORDER=['beauty','today','planning','routines','closet','fitness-wellness','money','home','food','travel','career-life','brain','create'] as const;
export const BATCH_X={steps:{125:'family-wave-inventory',126:'inherited-bulk-completion',127:'family-exception-separation',128:'family-lock-after-qa'},order:FAMILY_COMPLETION_ORDER,law:'Finish families as inherited systems. Ordinary descendants complete in bulk; only true exceptions receive individual work.'} as const;

export type ExceptionKind='ARCHITECTURE'|'VISUAL'|'GOLDEN'|'DATA'|'FUNCTIONAL'|'RESPONSIVE'|'ACCESSIBILITY';
export type GlowException={id:string;kind:ExceptionKind;surface:string;family:string;capability:string;owner:string;details:string;resolved:boolean};
export function crushExceptions(items:GlowException[]){const open=items.filter(x=>!x.resolved);const groups=new Map<string,GlowException[]>();for(const x of open){const key=`${x.kind}::${x.owner}::${x.capability}`;const group=groups.get(key);if(group)group.push(x);else groups.set(key,[x]);}const clusters=[...groups.entries()].map(([key,exceptions])=>({key,kind:exceptions[0].kind,owner:exceptions[0].owner,capability:exceptions[0].capability,exceptions,affectedSurfaces:[...new Set(exceptions.map(x=>x.surface))],impact:new Set(exceptions.map(x=>x.surface)).size,sharedRepair:exceptions.length>1})).sort((a,b)=>b.impact-a.impact);return {open,clusters,sharedCapabilityRepairs:clusters.filter(x=>x.sharedRepair),uniqueExceptions:clusters.filter(x=>!x.sharedRepair)};}
export const BATCH_Y={steps:{129:'unified-exception-inbox',130:'exception-clustering',131:'shared-capability-repair',132:'true-unique-exception-review'},law:'Many exceptions with one missing capability are one system problem. Build the capability once; custom work is reserved for genuinely unique experiences.'} as const;

export type FinishState={architectureBlockers:number;functionalBlockers:number;canonicalDataBlockers:number;runtimeErrors:number;accessibilityFailures:number;responsiveFailures:number;goldenExceptionsPending:number;unaccountedExperiences:number;humanDecisionRequired?:string};
export type FinishAction={kind:'REPAIR'|'RETEST'|'HUMAN_DECISION'|'COMPLETE';owner?:string;blocker?:string;reason:string};
export function chooseFinishAction(state:FinishState,rankedBlockers:{owner:string;blocker:string;impact:number}[]):FinishAction{if(state.humanDecisionRequired)return{kind:'HUMAN_DECISION',reason:state.humanDecisionRequired};const remaining=state.architectureBlockers+state.functionalBlockers+state.canonicalDataBlockers+state.runtimeErrors+state.accessibilityFailures+state.responsiveFailures+state.goldenExceptionsPending+state.unaccountedExperiences;if(remaining===0)return{kind:'COMPLETE',reason:'All required completion gates have evidence and no required blockers remain.'};const next=rankedBlockers[0];if(next)return{kind:'REPAIR',owner:next.owner,blocker:next.blocker,reason:`Highest-impact remaining blocker affects ${next.impact} surfaces.`};return{kind:'RETEST',reason:'Completion is not proven but no ranked repair exists; collect/retest missing evidence before proceeding.'};}
export const AUTONOMOUS_FINISH_LOOP=['scan','recalculate-census','rank-root-blockers','choose-highest-correct-ancestor','repair-once','build','test-affected-surfaces','golden-compare','recalculate-completion','pause-only-for-human-decision','repeat-until-stop-conditions'] as const;
export const BATCH_Z={steps:{133:'finish-loop-controller',134:'automatic-next-repair-selection',135:'human-decision-pause-gate',136:'evidence-based-stop-condition'},loop:AUTONOMOUS_FINISH_LOOP,stopConditions:['zero-architecture-blockers','zero-functional-blockers','zero-canonical-data-blockers','zero-unexplained-runtime-errors','zero-required-accessibility-failures','zero-required-responsive-failures','golden-exceptions-reviewed','all-required-experiences-accounted-for'],law:'The finish loop never fabricates success and never guesses through a user decision. It repairs the highest-impact correct ancestor, retests affected surfaces and repeats until evidence satisfies every required stop condition.'} as const;

export const X_Z_BOUNDARY='Batches X-Z automate completion planning, exception consolidation and next-action selection. They do not authorize production shipping, destructive deletion, or silent resolution of user-dependent design decisions.' as const;
