export type FunctionalGate='render'|'navigate'|'button'|'form'|'search'|'filter'|'save'|'edit'|'delete'|'complete'|'history'|'calendar'|'ask-glow'|'shakti'|'what-now'|'relationships'|'connected-data';
export type FunctionalEvidence={experience:string;family:string;gate:FunctionalGate;passed:boolean;owner:string;details?:string};
export function functionalCompletionSweep(items:FunctionalEvidence[]){const failures=items.filter(x=>!x.passed);const byOwner=failures.reduce<Record<string,FunctionalEvidence[]>>((a,x)=>{(a[x.owner]??=[]).push(x);return a;},{});return {passed:failures.length===0,failures,byOwner,rootRepairCount:Object.keys(byOwner).length};}
export const BATCH_S={steps:{105:'interactive-surface-inventory',106:'functional-gate-run',107:'dead-ui-and-placeholder-queue',108:'functional-completion-gate'},law:'A Glow surface is not complete because it renders. Its promised actions, persistence, relationships and connected-data behavior must work.'} as const;

export type LifeModelProjection={experience:string;family:string;objectIds:string[];sourceIds:string[];readsCanonicalGraph:boolean;writesCanonicalGraph:boolean;historyConnected:boolean;intelligenceConsumers:('ask-glow'|'shakti'|'what-now'|'recommendation'|'planning'|'routine')[]};
export function auditLifeModelConvergence(items:LifeModelProjection[]){const failures=items.filter(x=>!x.readsCanonicalGraph||!x.historyConnected||x.objectIds.length===0);const disconnectedWrites=items.filter(x=>x.writesCanonicalGraph===false&&x.intelligenceConsumers.length>0);return {passed:failures.length===0&&disconnectedWrites.length===0,failures,disconnectedWrites,canonicalExperiences:items.filter(x=>x.readsCanonicalGraph&&x.historyConnected)};}
export const LIFE_LOOP=['life','sources','objects','graph','state','intent','intelligence','decision','action','result','learning','updated-life-model'] as const;
export const BATCH_T={steps:{109:'canonical-life-model-audit',110:'cross-world-identity-convergence',111:'intelligence-consumer-convergence',112:'life-loop-integrity-gate'},lifeLoop:LIFE_LOOP,law:'Today, Planning, Beauty, Closet, Fitness, Money, Brain, Create and every other projection must read the same canonical life model instead of maintaining disconnected copies.'} as const;

export type CompletionSurface={world:string;room:string;experience:string;build:boolean;data:boolean;functional:boolean;visual:boolean;responsive:boolean;accessibility:boolean;golden:boolean;production:boolean;blockers:string[]};
export function buildCompletionCommandCenter(items:CompletionSurface[]){const dimensions=['build','data','functional','visual','responsive','accessibility','golden','production'] as const;const complete=items.filter(x=>dimensions.every(d=>x[d]));const incomplete=items.filter(x=>!dimensions.every(d=>x[d]));const blockerCounts=new Map<string,number>();for(const x of incomplete)for(const b of x.blockers)blockerCounts.set(b,(blockerCounts.get(b)??0)+1);const rootBlockers=[...blockerCounts.entries()].map(([blocker,count])=>({blocker,count})).sort((a,b)=>b.count-a.count);return {total:items.length,complete:complete.length,incomplete:incomplete.length,completionPercent:items.length?Math.round(complete.length/items.length*100):0,rootBlockers,topFiveRootBlockers:rootBlockers.slice(0,5),surfaces:items};}
export const BATCH_U={steps:{113:'whole-glow-completion-registry',114:'dimension-status-rollup',115:'root-blocker-command-center',116:'completion-to-production-gate'},law:'Glow completion is measured per registered experience across build, data, function, visual, responsive, accessibility, Golden QA and production. Work is prioritized by shared root blocker, not by arbitrary next page.'} as const;

export const S_U_PIPELINE=['functional-sweep','repair-dead-ui','canonical-life-model-audit','repair-disconnected-identities','verify-intelligence-consumers','verify-life-loop','roll-up-completion','repair-top-root-blockers','retest-affected-surfaces','approve-production-only-after-all-required-gates'] as const;
