export const BATCH_I={steps:{65:'global-shell-runtime-conversion',66:'shared-engine-runtime-conversion',67:'canonical-data-runtime-conversion',68:'legacy-compatibility-layer'},laws:['global capabilities are owned once by Global Shell','local pages project canonical objects; they do not own duplicate identities','shared engines replace duplicate local implementations after parity','legacy links remain resolvable until replacement routes pass QA'],gates:['shell-parity','engine-parity','canonical-identity-integrity','history-preserved','legacy-links-resolve','runtime-errors-clear']} as const;

export type VisualInheritance={world:string;room:string;template:string;state:string;energy?:'low'|'normal'|'high'|'recovery'};
export function resolveVisualInheritance(input:VisualInheritance){return ['global-visual-laws',`world:${input.world}`,`room:${input.room}`,`template:${input.template}`,`state:${input.state}`,input.energy?`energy:${input.energy}`:'energy:normal'];}
export const BATCH_J={steps:{69:'visual-inheritance-resolver',70:'visual-drift-detector',71:'responsive-device-state-matrix',72:'ancestor-token-repair'},devices:['iphone','ipad','desktop'],states:['empty','populated','loading','error'],energy:['low','normal','high','recovery'],law:'Visual differences inherit from Global → World → Room → Template → Object → State. Repeated drift is repaired at the highest shared token/template ancestor.'} as const;

export type QaFailure={surface:string;family:string;gate:string;owner:string;message:string};
export const QA_GATES=['build','route','data','actions','state','history','responsive','accessibility','visual','runtime','regression'] as const;
export function dedupeQaFailures(failures:QaFailure[]){const groups=new Map<string,QaFailure[]>();for(const f of failures){const key=`${f.owner}:${f.gate}:${f.message}`;(groups.get(key)??groups.set(key,[]).get(key)!).push(f);}return [...groups.entries()].map(([rootCause,items])=>({rootCause,owner:items[0].owner,gate:items[0].gate,affected:items.map(x=>x.surface),families:[...new Set(items.map(x=>x.family))],count:items.length})).sort((a,b)=>b.count-a.count);}
export function evaluateQaFactory(failures:QaFailure[]){const rootCauses=dedupeQaFailures(failures);return {passed:failures.length===0,failures,rootCauses,repairCount:rootCauses.length,affectedSurfaceCount:new Set(failures.map(x=>x.surface)).size};}
export const BATCH_K={steps:{73:'automatic-qa-orchestrator',74:'root-cause-deduplication',75:'affected-surface-regression',76:'qa-release-gate'},gates:QA_GATES,law:'QA reports shared root causes, not a page-by-page failure pile. A release advances only when required gates pass and Golden exceptions are approved.'} as const;

export const I_K_RELEASE_LAW='Runtime conversion, visual inheritance and QA are preservation-first. No legacy retirement or production shipping is authorized by these contracts alone.' as const;
