export const WAVE_7=7 as const;
export const WAVE_7_NAME='Whole-App Visual Convergence' as const;
export type VisualFamily='today'|'planning'|'routines'|'beauty'|'closet'|'fitness-wellness'|'home'|'food'|'money'|'travel'|'career-life'|'brain'|'create';
export type VisualDimension='global-shell'|'world-environment'|'room-environment'|'template-composition'|'typography'|'spacing'|'materials'|'depth-light'|'imagery'|'controls'|'states'|'overlays'|'responsive'|'accessibility-visual'|'golden';
export type VisualEvidence={family:VisualFamily;dimension:VisualDimension;status:'PASS'|'FAIL'|'UNVERIFIED';source:string;blocker?:string};
export type VisualBlocker={id:string;owner:string;families:VisualFamily[];dimensions:VisualDimension[];severity:'blocker'|'high'|'medium';details:string;resolved:boolean};
export const WAVE_7_ENTRY={mode:'whole-app-convergence',priorFamilyEvidenceStillRequired:true,productionShippingAllowed:false} as const;
export const VISUAL_FAMILIES:readonly VisualFamily[]=['today','planning','routines','beauty','closet','fitness-wellness','home','food','money','travel','career-life','brain','create'];
export const VISUAL_DIMENSIONS:readonly VisualDimension[]=['global-shell','world-environment','room-environment','template-composition','typography','spacing','materials','depth-light','imagery','controls','states','overlays','responsive','accessibility-visual','golden'];
export const WAVE_7_VISUAL_LAWS={editorialDigitalMagazine:true,spatialNotDashboard:true,noSidebarAsPrimaryNavigation:true,noBottomTabsAsPrimaryNavigation:true,oneGlobalShell:true,worldsFeelLikePlaces:true,continuousRoomEnvironment:true,templateInheritance:true,stateDoesNotCreateNewPage:true,referencePrecedence:true,exceptionContract:true,repairHighestSharedAncestor:true,noPageByPagePatching:true} as const;
export function visualEvidenceStatus(items:VisualEvidence[]){const missing:string[]=[];const failed:string[]=[];for(const family of VISUAL_FAMILIES)for(const dimension of VISUAL_DIMENSIONS){const item=items.find(x=>x.family===family&&x.dimension===dimension);if(!item||item.status==='UNVERIFIED')missing.push(`${family}:${dimension}`);else if(item.status==='FAIL')failed.push(item.blocker??`${family}:${dimension}`);}return{required:VISUAL_FAMILIES.length*VISUAL_DIMENSIONS.length,provided:items.length,missing,failed:[...new Set(failed)],passed:missing.length===0&&failed.length===0};}
const rank={blocker:3,high:2,medium:1} as const;
export function rankVisualBlockers(items:VisualBlocker[]){return items.filter(x=>!x.resolved).map(x=>({...x,impact:x.families.length*x.dimensions.length,sharedRepair:x.families.length>1})).sort((a,b)=>rank[b.severity]-rank[a.severity]||b.impact-a.impact);}
export function nextVisualRepair(items:VisualBlocker[]){return rankVisualBlockers(items)[0]??null;}
export function wave7Checkpoint(evidence:VisualEvidence[],blockers:VisualBlocker[]){const e=visualEvidenceStatus(evidence);const open=rankVisualBlockers(blockers);const canLock=e.passed&&open.length===0;return{wave:WAVE_7,name:WAVE_7_NAME,evidence:e,openBlockers:open,canLock,status:canLock?'LOCKABLE':'BUILDING',nextRepair:open[0]??null}as const;}
export const WAVE_7_COMPLETION_ORDER=['global-shell','global-tokens-and-primitives','world-environments','room-environments','template-compositions','states-and-overlays','exception-surfaces','responsive-visuals','accessibility-visuals','golden-set','whole-app-lock'] as const;
export const WAVE_7_RULE='Converge Glow visually from the highest shared ancestor downward. Fix global shell, tokens, primitives, environments and templates before individual exceptions. Do not claim visual completion without evidence across every registered family.' as const;
