export const WAVE_8=8 as const;
export const WAVE_8_NAME='Whole-App Functional Sweep' as const;
export type FunctionalFamily='today'|'planning'|'routines'|'beauty'|'closet'|'fitness-wellness'|'home'|'food'|'money'|'travel'|'career-life'|'brain'|'create';
export type FunctionalDimension='navigation'|'object-read'|'object-create'|'object-update'|'object-delete'|'actions'|'state-transitions'|'history'|'relationships'|'search'|'ask-glow'|'attachments'|'persistence'|'auth-session'|'error-recovery'|'loading-empty'|'permissions'|'integrations'|'keyboard-touch'|'runtime';
export type FunctionalEvidence={family:FunctionalFamily;dimension:FunctionalDimension;status:'PASS'|'FAIL'|'UNVERIFIED';source:string;blocker?:string};
export type FunctionalBlocker={id:string;owner:string;families:FunctionalFamily[];dimensions:FunctionalDimension[];severity:'blocker'|'high'|'medium';details:string;resolved:boolean};
export const WAVE_8_ENTRY={mode:'whole-app-functional-sweep',priorVisualEvidenceStillRequired:true,productionShippingAllowed:false} as const;
export const FUNCTIONAL_FAMILIES:readonly FunctionalFamily[]=['today','planning','routines','beauty','closet','fitness-wellness','home','food','money','travel','career-life','brain','create'];
export const FUNCTIONAL_DIMENSIONS:readonly FunctionalDimension[]=['navigation','object-read','object-create','object-update','object-delete','actions','state-transitions','history','relationships','search','ask-glow','attachments','persistence','auth-session','error-recovery','loading-empty','permissions','integrations','keyboard-touch','runtime'];
export const WAVE_8_FUNCTIONAL_LAWS={oneGlowContext:true,canonicalObjectIdentity:true,sharedActions:true,sharedHistory:true,relationshipsPersist:true,stateTransitionsAreExplicit:true,authSessionStable:true,errorsRecoverable:true,loadingAndEmptyStatesRequired:true,permissionsRespected:true,keyboardAndTouchParity:true,noDeadControls:true,noFakeActions:true,repairHighestSharedAncestor:true,noPageByPagePatching:true} as const;
export function functionalEvidenceStatus(items:FunctionalEvidence[]){const missing:string[]=[];const failed:string[]=[];for(const family of FUNCTIONAL_FAMILIES)for(const dimension of FUNCTIONAL_DIMENSIONS){const item=items.find(x=>x.family===family&&x.dimension===dimension);if(!item||item.status==='UNVERIFIED')missing.push(`${family}:${dimension}`);else if(item.status==='FAIL')failed.push(item.blocker??`${family}:${dimension}`);}return{required:FUNCTIONAL_FAMILIES.length*FUNCTIONAL_DIMENSIONS.length,provided:items.length,missing,failed:[...new Set(failed)],passed:missing.length===0&&failed.length===0};}
const rank={blocker:3,high:2,medium:1} as const;
export function rankFunctionalBlockers(items:FunctionalBlocker[]){return items.filter(x=>!x.resolved).map(x=>({...x,impact:x.families.length*x.dimensions.length,sharedRepair:x.families.length>1})).sort((a,b)=>rank[b.severity]-rank[a.severity]||b.impact-a.impact);}
export function nextFunctionalRepair(items:FunctionalBlocker[]){return rankFunctionalBlockers(items)[0]??null;}
export function wave8Checkpoint(evidence:FunctionalEvidence[],blockers:FunctionalBlocker[]){const e=functionalEvidenceStatus(evidence);const open=rankFunctionalBlockers(blockers);const canLock=e.passed&&open.length===0;return{wave:WAVE_8,name:WAVE_8_NAME,evidence:e,openBlockers:open,canLock,status:canLock?'LOCKABLE':'BUILDING',nextRepair:open[0]??null}as const;}
export const WAVE_8_COMPLETION_ORDER=['navigation-and-context','canonical-object-crud','actions-and-state-transitions','history-and-relationships','search-and-ask-glow','attachments-and-persistence','auth-and-permissions','errors-loading-empty','integrations','keyboard-touch-parity','runtime-sweep','whole-app-functional-lock'] as const;
export const WAVE_8_RULE='Sweep every registered Glow family for real behavior. Every visible control must perform its intended action, persist through canonical objects and shared context where required, expose recoverable states, and work across keyboard and touch. Repair shared engines before individual surfaces and do not claim functional completion without evidence.' as const;
