import { WAVE_A_GATES, WAVE_A_SHARED_ANCESTORS, WAVE_A_TODAY_PLANNING_ROUTINES } from './wave-a-today-planning-routines';
export const WAVE_2_FAMILY='today-planning-routines' as const;
export type Wave2EnergyMode='low'|'normal'|'high'|'recovery'; export type Wave2Surface='today'|'planning'|'routines';
export const WAVE_2_CANONICAL_ROUTES:Record<Wave2Surface,string>={today:'/today',planning:'/planning',routines:'/routines'};
export const WAVE_2_TIME_WINDOWS={morning:{start:'05:00',end:'10:00'},between:{start:'10:00',end:'16:00'},evening:{start:'16:00',end:'20:30'},night:{start:'20:30',end:'23:00'}} as const;
export const WAVE_2_ENERGY_CAPACITY={low:{priorityLimit:1,protectOpenSpace:true},normal:{priorityLimit:3,protectOpenSpace:true},high:{priorityLimit:6,protectOpenSpace:true},recovery:{priorityLimit:1,protectOpenSpace:true,recoveryFirst:true}} as const;
export const WAVE_2_SHARED_RUNTIME={canonicalObjects:['task','event','routine','routine-session','habit','goal','project'],capabilities:['what-now','energy-mode','capacity','timeline','calendar','time-blocking','recurrence','guided-session','completion-history','recommendation'],ancestors:WAVE_A_SHARED_ANCESTORS,gates:WAVE_A_GATES,timeWindows:WAVE_2_TIME_WINDOWS,energyCapacity:WAVE_2_ENERGY_CAPACITY} as const;
export function wave2SurfaceForPath(p:string):Wave2Surface|null{if(p==='/today'||p.startsWith('/today/'))return'today';if(p==='/planning'||p.startsWith('/planning/'))return'planning';if(p==='/routines'||p.startsWith('/routines/'))return'routines';return null;}
export function wave2RuntimeContext(pathname:string){const surface=wave2SurfaceForPath(pathname);if(!surface)return null;const family=WAVE_A_TODAY_PLANNING_ROUTINES.find(e=>e.family===surface);return{family:WAVE_2_FAMILY,surface,route:WAVE_2_CANONICAL_ROUTES[surface],canonicalObjects:family?.canonicalObjects??[],sharedCapabilities:family?.sharedCapabilities??[],timeWindows:WAVE_2_TIME_WINDOWS,energyCapacity:WAVE_2_ENERGY_CAPACITY,preserveExistingRoutes:true,retireOnlyAfterQa:true}as const;}
export type Wave2QaEvidence={surface:Wave2Surface;route:boolean;data:boolean;sharedContext:boolean;energyCapacity:boolean;history:boolean;responsive:boolean;accessibility:boolean;visual:boolean;golden:boolean;runtime?:boolean;blockers?:string[]};
export function evaluateWave2Qa(e:Wave2QaEvidence[]){const ok=(x:Wave2QaEvidence)=>x.route&&x.data&&x.sharedContext&&x.energyCapacity&&x.history&&x.responsive&&x.accessibility&&x.visual&&x.golden&&x.runtime!==false;const failed=e.filter(x=>!ok(x));return{passed:e.length===3&&!failed.length,failedSurfaces:failed.map(x=>x.surface),blockers:[...new Set(failed.flatMap(x=>x.blockers??[]))],canLock:e.length===3&&!failed.length};}
export type Wave2ActionReceipt={id:string;surface:Wave2Surface;objectType:string;objectId:string;action:string;occurredAt:string;reversible:boolean}; export type Wave2ExecutionState={energy:Wave2EnergyMode;scheduledMinutes:number;availableMinutes:number;receipts:Wave2ActionReceipt[]};
export function wave2Capacity(s:Wave2ExecutionState){const p=WAVE_2_ENERGY_CAPACITY[s.energy];return{priorityLimit:p.priorityLimit,remainingMinutes:Math.max(0,s.availableMinutes-s.scheduledMinutes),overCapacity:s.scheduledMinutes>s.availableMinutes,protectOpenSpace:p.protectOpenSpace,recoveryFirst:'recoveryFirst'in p&&p.recoveryFirst===true};}
export function appendWave2Receipt(s:Wave2ExecutionState,r:Wave2ActionReceipt):Wave2ExecutionState{return{...s,receipts:[r,...s.receipts]};}
export type Wave2CompletionEvidence={buildReady:boolean;routesPreserved:boolean;canonicalDataPreserved:boolean;sharedRuntimeBound:boolean;historyConnected:boolean;responsiveVerified:boolean;accessibilityVerified:boolean;visualVerified:boolean;goldenVerified:boolean;runtimeVerified:boolean;blockers:string[]};
export function wave2CompletionStatus(e:Wave2CompletionEvidence){const passed=e.buildReady&&e.routesPreserved&&e.canonicalDataPreserved&&e.sharedRuntimeBound&&e.historyConnected&&e.responsiveVerified&&e.accessibilityVerified&&e.visualVerified&&e.goldenVerified&&e.runtimeVerified&&!e.blockers.length;return{passed,canLock:passed,status:passed?'LOCKABLE':'BUILDING'as const,blockers:e.blockers};}
export type Wave2Blocker={id:string;owner:string;surfaces:Wave2Surface[];severity:'blocker'|'high'|'medium';gate:string;details:string;resolved:boolean}; const severityRank={blocker:3,high:2,medium:1}as const;
export function rankWave2Blockers(bs:Wave2Blocker[]){return bs.filter(b=>!b.resolved).map(b=>({...b,impact:b.surfaces.length,sharedRepair:b.surfaces.length>1})).sort((a,b)=>severityRank[b.severity]-severityRank[a.severity]||b.impact-a.impact);}
export function nextWave2Repair(bs:Wave2Blocker[]){return rankWave2Blockers(bs)[0]??null;}
export function wave2Handoff(e:Wave2CompletionEvidence,bs:Wave2Blocker[]){const completion=wave2CompletionStatus({...e,blockers:[...new Set([...e.blockers,...rankWave2Blockers(bs).map(b=>b.id)])]});return{...completion,nextRepair:completion.canLock?null:nextWave2Repair(bs),nextWave:completion.canLock?3:2,rule:completion.canLock?'Wave 2 may lock and hand off to Beauty.':'Stay in Wave 2 and repair the highest-impact evidenced blocker.'}as const;}

export type Wave2EvidenceDimension='build'|'route'|'data'|'shared-context'|'energy-capacity'|'history'|'runtime'|'responsive'|'accessibility'|'visual'|'golden';
export type Wave2EvidenceItem={surface:Wave2Surface;dimension:Wave2EvidenceDimension;status:'PASS'|'FAIL'|'UNVERIFIED';source:string;blocker?:string};
export function convergeWave2Evidence(items:Wave2EvidenceItem[]){const surfaces:Wave2Surface[]=['today','planning','routines'];const dimensions:Wave2EvidenceDimension[]=['build','route','data','shared-context','energy-capacity','history','runtime','responsive','accessibility','visual','golden'];const missing:string[]=[];const failed:string[]=[];for(const surface of surfaces)for(const dimension of dimensions){const item=items.find(x=>x.surface===surface&&x.dimension===dimension);if(!item||item.status==='UNVERIFIED')missing.push(`${surface}:${dimension}`);else if(item.status==='FAIL')failed.push(item.blocker??`${surface}:${dimension}`);}return{accounted:surfaces.length*dimensions.length,provided:items.length,missing,failed:[...new Set(failed)],passed:missing.length===0&&failed.length===0};}
export const WAVE_3_BEAUTY_HANDOFF={wave:3,name:'Beauty',scope:['skincare','hair','makeup','body','nails','brows-lashes','oral','gua-sha','beauty-inventory','routines','maintenance','progress','intelligence'],requiresWave2Lock:true}as const;
export function finishWave2(items:Wave2EvidenceItem[],blockers:Wave2Blocker[]){const evidence=convergeWave2Evidence(items);const open=rankWave2Blockers(blockers);const canLock=evidence.passed&&open.length===0;return{canLock,status:canLock?'LOCKED':'OPEN',nextRepair:canLock?null:open[0]??null,handoff:canLock?WAVE_3_BEAUTY_HANDOFF:null,missingEvidence:evidence.missing,failedEvidence:evidence.failed}as const;}
export const WAVE_2_STEPS_36_40=[{step:36,action:'verify-31-35-build',owner:'wave-2'},{step:37,action:'converge-all-required-evidence',owner:'completion-registry'},{step:38,action:'select-next-real-blocker',owner:'convergence'},{step:39,action:'enforce-zero-unverified-lock-gate',owner:'factory-lock'},{step:40,action:'handoff-to-beauty-only-after-wave-2-lock',owner:'completion-waves'}]as const;
