export const WAVE_10=10 as const;
export const WAVE_10_NAME='Production Readiness' as const;
export type ReadinessArea='build'|'typecheck'|'lint'|'tests'|'migrations'|'data-integrity'|'auth'|'security'|'permissions'|'performance'|'observability'|'error-recovery'|'accessibility'|'responsive'|'visual-golden'|'functional'|'device-state'|'production-config'|'rollback'|'release-evidence';
export type ReadinessEvidence={area:ReadinessArea;status:'PASS'|'FAIL'|'UNVERIFIED';source:string;commit?:string;blocker?:string};
export type ReleaseBlocker={id:string;area:ReadinessArea;severity:'blocker'|'high'|'medium';details:string;resolved:boolean};
export const WAVE_10_ENTRY={mode:'production-readiness',requiresPriorWaveEvidence:true,mergeRequiresExplicitUserApproval:true,productionDeployRequiresExplicitUserApproval:true} as const;
export const READINESS_AREAS:readonly ReadinessArea[]=['build','typecheck','lint','tests','migrations','data-integrity','auth','security','permissions','performance','observability','error-recovery','accessibility','responsive','visual-golden','functional','device-state','production-config','rollback','release-evidence'];
export const WAVE_10_RELEASE_LAWS={noUnverifiedRelease:true,noKnownBlockers:true,canonicalDataPreserved:true,migrationsReversibleOrBackedUp:true,authStable:true,permissionsVerified:true,noSecretsInClient:true,errorRecoveryVerified:true,accessibilityVerified:true,responsiveVerified:true,goldenVerified:true,functionalSweepVerified:true,deviceStateMatrixVerified:true,productionConfigVerified:true,rollbackPlanRequired:true,releaseEvidenceImmutable:true,explicitMergeApprovalRequired:true,explicitProductionApprovalRequired:true} as const;
export function readinessStatus(items:ReadinessEvidence[]){const missing:string[]=[];const failed:string[]=[];for(const area of READINESS_AREAS){const item=items.find(x=>x.area===area);if(!item||item.status==='UNVERIFIED')missing.push(area);else if(item.status==='FAIL')failed.push(item.blocker??area);}return{required:READINESS_AREAS.length,provided:items.length,missing,failed:[...new Set(failed)],passed:missing.length===0&&failed.length===0};}
const rank={blocker:3,high:2,medium:1} as const;
export function rankReleaseBlockers(items:ReleaseBlocker[]){return items.filter(x=>!x.resolved).sort((a,b)=>rank[b.severity]-rank[a.severity]);}
export function wave10Checkpoint(evidence:ReadinessEvidence[],blockers:ReleaseBlocker[]){const e=readinessStatus(evidence);const open=rankReleaseBlockers(blockers);const ready=e.passed&&open.length===0;return{wave:WAVE_10,name:WAVE_10_NAME,evidence:e,openBlockers:open,ready,status:ready?'READY_FOR_EXPLICIT_RELEASE_APPROVAL':'BUILDING',nextRepair:open[0]??null,mayMerge:false,mayDeployProduction:false}as const;}
export const WAVE_10_COMPLETION_ORDER=['freeze-release-candidate','build-typecheck-lint','automated-tests','migration-and-data-integrity','auth-security-permissions','performance-observability','error-recovery','accessibility-responsive','visual-golden','functional-evidence','device-state-evidence','production-config','rollback-plan','release-evidence','explicit-user-release-approval'] as const;
export const RELEASE_RECEIPT_FIELDS=['candidateCommit','branch','buildEvidence','testEvidence','migrationEvidence','dataIntegrityEvidence','authEvidence','securityEvidence','accessibilityEvidence','responsiveEvidence','visualGoldenEvidence','functionalEvidence','deviceStateEvidence','productionConfigEvidence','rollbackPlan','knownIssues','approvedBy','approvedAt'] as const;
export const WAVE_10_RULE='Production readiness is evidence, not a label. Freeze a release candidate, prove every readiness area, resolve every blocker, preserve rollback capability, then wait for explicit user approval before merge or production deployment.' as const;
