import { WAVE_A_GATES, WAVE_A_SHARED_ANCESTORS, WAVE_A_TODAY_PLANNING_ROUTINES } from './wave-a-today-planning-routines';
export const WAVE_2_FAMILY='today-planning-routines' as const;
export type Wave2EnergyMode='low'|'normal'|'high'|'recovery'; export type Wave2Surface='today'|'planning'|'routines';
export const WAVE_2_CANONICAL_ROUTES:Record<Wave2Surface,string>={today:'/today',planning:'/planning',routines:'/routines'};
export const WAVE_2_TIME_WINDOWS={morning:{start:'05:00',end:'10:00'},between:{start:'10:00',end:'16:00'},evening:{start:'16:00',end:'20:30'},night:{start:'20:30',end:'23:00'}} as const;
export const WAVE_2_ENERGY_CAPACITY={low:{priorityLimit:1,protectOpenSpace:true},normal:{priorityLimit:3,protectOpenSpace:true},high:{priorityLimit:6,protectOpenSpace:true},recovery:{priorityLimit:1,protectOpenSpace:true,recoveryFirst:true}} as const;
export const WAVE_2_SHARED_RUNTIME={canonicalObjects:['task','event','routine','routine-session','habit','goal','project'],capabilities:['what-now','energy-mode','capacity','timeline','calendar','time-blocking','recurrence','guided-session','completion-history','recommendation'],ancestors:WAVE_A_SHARED_ANCESTORS,gates:WAVE_A_GATES,timeWindows:WAVE_2_TIME_WINDOWS,energyCapacity:WAVE_2_ENERGY_CAPACITY} as const;
export function wave2SurfaceForPath(p:string):Wave2Surface|null{if(p==='/today'||p.startsWith('/today/'))return'today';if(p==='/planning'||p.startsWith('/planning/'))return'planning';if(p==='/routines'||p.startsWith('/routines/'))return'routines';return null;}
export function wave2RuntimeContext(pathname:string){const surface=wave2SurfaceForPath(pathname);if(!surface)return null;const family=WAVE_A_TODAY_PLANNING_ROUTINES.find(e=>e.family===surface);return{family:WAVE_2_FAMILY,surface,route:WAVE_2_CANONICAL_ROUTES[surface],canonicalObjects:family?.canonicalObjects??[],sharedCapabilities:family?.sharedCapabilities??[],timeWindows:WAVE_2_TIME_WINDOWS,energyCapacity:WAVE_2_ENERGY_CAPACITY,preserveExistingRoutes:true,retireOnlyAfterQa:true}as const;}
export type Wave2QaEvidence={surface:Wave2Surface;route:boolean;data:boolean;sharedContext:boolean;energyCapacity:boolean;history:boolean;responsive:boolean;accessibility:boolean;visual:boolean;golden:boolean;runtime?:boolean;blockers?:string[]};
export function evaluateWave2Qa(e:Wave2QaEvidence[]){const ok=(x:Wave2QaEvidence)=>x.route&&x.data&&x.sharedContext&&x.energyCapacity&&x.history&&x.responsive&&x.accessibility&&x.visual&&x.golden&&x.runtime!==false;const failed=e.filter(x=>!ok(x));return{passed:e.length===3&&!failed.length,failedSurfaces:failed.map(x=>x.surface),blockers:[...new Set(failed.flatMap(x=>x.blockers??[]))],canLock:e.length===3&&!failed.length};}
export type Wave2ActionReceipt={id:string;surface:Wave2Surface;objectType:string;objectId:string;action:string;occurredAt:string;reversible:boolean}; export type Wave2ExecutionState={energy:Wave2EnergyMode;scheduledMinutes:number;availableMinutes:number;receipts:Wave2ActionReceipt[]};
export function wave2Capacity(s:Wave2ExecutionState){const p=WAVE_2_ENERGY_CAPACITY[s.energy];return{priorityLimit:p.priorityLimit,remainingMinutes:Math.max(0,s.availableMinutes-s.scheduledMinutes),overCapacity:s.scheduledMinutes>s.availableMinutes,protectOpenSpace:p.protectOpenSpace,recoveryFirst:'recoveryFirst'in p&&p.recoveryFirst===true};}
export function appendWave2Receipt(s:Wave2ExecutionState,r:Wave2ActionReceipt):Wave2ExecutionState{return{...s,receipts:[r,...s.receipts]};}
export type Wave2CompletionEvidence={buildReady:boolean;routesPreserved:boolean;canonicalDataPreserved:boolean;sharedRuntimeBound:boolean;historyConnected:boolean;responsiveVerified:boolean;accessibilityVerified:boolean;visualVerified:boolean;goldenVerified:boolean;runtimeVerified:boolean;blockers:string[]};
export function wave2CompletionStatus(e:Wave2CompletionEvidence){const passed=e.buildReady&&e.routesPreserved&&e.canonicalDataPreserved&&e.sharedRuntimeBound&&e.historyConnected&&e.responsiveVerified&&e.accessibilityVerified&&e.visualVerified&&e.goldenVerified&&e.runtimeVerified&&!e.blockers.length;return{passed,canLock:passed,status:passed?'LOCKABLE':'BUILDING'as const,blockers:e.blockers};}
export type Wave2Blocker={id:string;owner:string;surfaces:Wave2Surface[];severity:'blocker'|'high'|'medium';gate:string;details:string;resolved:boolean}; const severityRank={blocker:3,high:2,medium:1}as const;
export function rankWave2Blockers(bs:Wave2Blocker[]){return bs.filter(b=>!b.resolved).map(b=>({...b,impact:b.surfaces.length,sharedRepair:b.surfaces.length>1})).sort((a,b)=>severityRank[b.severity]-severityRank[a.severity]||b.impact-a.impact);}
export function nextWave2Repair(bs:Wave2Blocker[]){return rankWave2Blockers(bs)[0]??null;}
export type Wave2EvidenceDimension='build'|'route'|'data'|'shared-context'|'energy-capacity'|'history'|'runtime'|'responsive'|'accessibility'|'visual'|'golden';
export type Wave2EvidenceItem={surface:Wave2Surface;dimension:Wave2EvidenceDimension;status:'PASS'|'FAIL'|'UNVERIFIED';source:string;blocker?:string};
export const WAVE_2_REQUIRED_DIMENSIONS:readonly Wave2EvidenceDimension[]=['build','route','data','shared-context','energy-capacity','history','runtime','responsive','accessibility','visual','golden'];
export function convergeWave2Evidence(items:Wave2EvidenceItem[]){const surfaces:Wave2Surface[]=['today','planning','routines'];const missing:string[]=[];const failed:string[]=[];for(const surface of surfaces)for(const dimension of WAVE_2_REQUIRED_DIMENSIONS){const item=items.find(x=>x.surface===surface&&x.dimension===dimension);if(!item||item.status==='UNVERIFIED')missing.push(`${surface}:${dimension}`);else if(item.status==='FAIL')failed.push(item.blocker??`${surface}:${dimension}`);}return{accounted:surfaces.length*WAVE_2_REQUIRED_DIMENSIONS.length,provided:items.length,missing,failed:[...new Set(failed)],passed:missing.length===0&&failed.length===0};}
export const WAVE_3_BEAUTY_HANDOFF={wave:3,name:'Beauty',scope:['skincare','hair','makeup','body','nails','brows-lashes','oral','gua-sha','beauty-inventory','routines','maintenance','progress','intelligence'],requiresWave2Lock:true}as const;
export function finishWave2(items:Wave2EvidenceItem[],blockers:Wave2Blocker[]){const evidence=convergeWave2Evidence(items);const open=rankWave2Blockers(blockers);const canLock=evidence.passed&&!open.length;return{canLock,status:canLock?'LOCKED':'OPEN',nextRepair:canLock?null:open[0]??null,handoff:canLock?WAVE_3_BEAUTY_HANDOFF:null,missingEvidence:evidence.missing,failedEvidence:evidence.failed}as const;}
export type EvidenceRepair={key:string;dimension:Wave2EvidenceDimension;surfaces:Wave2Surface[];owner:string;reason:'FAILED'|'UNVERIFIED';impact:number};
const EVIDENCE_OWNER:Record<Wave2EvidenceDimension,string>={build:'build-system',route:'route-registry',data:'canonical-object-layer','shared-context':'global-context','energy-capacity':'planner-engine',history:'history-layer',runtime:'runtime',responsive:'responsive-system',accessibility:'accessibility-system',visual:'visual-inheritance',golden:'golden-qa'};
export function buildEvidenceRepairQueue(items:Wave2EvidenceItem[]){const surfaces:Wave2Surface[]=['today','planning','routines'];const repairs:EvidenceRepair[]=[];for(const dimension of WAVE_2_REQUIRED_DIMENSIONS){const affected=surfaces.filter(surface=>{const item=items.find(x=>x.surface===surface&&x.dimension===dimension);return !item||item.status!=='PASS';});if(affected.length)repairs.push({key:`${dimension}:${affected.join('+')}`,dimension,surfaces:affected,owner:EVIDENCE_OWNER[dimension],reason:affected.some(surface=>items.find(x=>x.surface===surface&&x.dimension===dimension)?.status==='FAIL')?'FAILED':'UNVERIFIED',impact:affected.length});}return repairs.sort((a,b)=>b.impact-a.impact||a.dimension.localeCompare(b.dimension));}
export function nextEvidenceRepair(items:Wave2EvidenceItem[]){return buildEvidenceRepairQueue(items)[0]??null;}
export const WAVE_3_BEAUTY_ENTRY={family:'beauty',routeRoots:['/beauty','/beauty/skincare','/beauty/hair','/beauty/makeup','/beauty/body','/beauty/nails'],canonicalObjects:['product','routine','routine-step','routine-session','beauty-tool','treatment','progress-record','photo','appointment'],entryCondition:'wave-2-locked'}as const;
export function completionTransition(items:Wave2EvidenceItem[],blockers:Wave2Blocker[]){const finish=finishWave2(items,blockers);return finish.canLock?{wave:3,mode:'ENTER_BEAUTY',manifest:WAVE_3_BEAUTY_ENTRY}:{wave:2,mode:'REPAIR',repair:nextWave2Repair(blockers)??nextEvidenceRepair(items)}as const;}
export type Wave2Checkpoint={buildReady:boolean;evidence:Wave2EvidenceItem[];blockers:Wave2Blocker[]};
export function wave2CompletionCheckpoint(checkpoint:Wave2Checkpoint){const evidence=convergeWave2Evidence(checkpoint.evidence);const repairQueue=buildEvidenceRepairQueue(checkpoint.evidence);const openBlockers=rankWave2Blockers(checkpoint.blockers);const canLock=checkpoint.buildReady&&evidence.passed&&openBlockers.length===0;return{buildReady:checkpoint.buildReady,evidencePassed:evidence.passed,openEvidenceRepairs:repairQueue.length,openBlockers:openBlockers.length,canLock,nextAction:canLock?'ENTER_BEAUTY':openBlockers[0]??repairQueue[0]??'VERIFY_BUILD'}as const;}
export const WAVE_2_STEPS_46_50=[{step:46,action:'repair-step-41-45-build-error',owner:'build-system'},{step:47,action:'centralize-required-evidence-dimensions',owner:'completion-registry'},{step:48,action:'recalculate-evidence-repair-queue',owner:'qa-pipeline'},{step:49,action:'run-wave-2-completion-checkpoint',owner:'factory-lock'},{step:50,action:'hold-or-enter-beauty-from-evidence',owner:'completion-waves'}]as const;
