import Link from 'next/link';
import { Card } from '@/components/ui/card';
import { ArrowRight, BedDouble, HeartPulse, Moon, Sparkles } from 'lucide-react';

type WellnessEntry={id:string;entryDate:string;mood:string|null;energy:string|null;stressLevel:number|null;sleepHours:number|null;waterGlasses:number|null;notes:string|null};

function avg(values:number[]){return values.length?values.reduce((a,b)=>a+b,0)/values.length:null}
function n(value:number|null,digits=1){return value==null?'—':value.toFixed(digits)}

export function ReferenceWellnessView({mode,entries}:{mode:'sleep'|'symptoms';entries:WellnessEntry[]}){
  const sleep=entries.filter(e=>e.sleepHours!=null);
  const recent=entries.slice(0,14);
  const avgSleep=avg(sleep.slice(0,7).map(e=>e.sleepHours as number));
  const avgStress=avg(recent.filter(e=>e.stressLevel!=null).map(e=>e.stressLevel as number));
  const lowEnergy=recent.filter(e=>e.energy==='low'||e.energy==='exhausted').length;
  const noteEntries=entries.filter(e=>Boolean(e.notes?.trim()));
  if(mode==='sleep')return <div className="space-y-5">
    <header><p className="glow-eyebrow text-[#6E8064]">Wellness</p><h1 className="glow-display mt-1 text-[44px] leading-none sm:text-[56px]">Sleep</h1><p className="mt-2 text-[12.5px] text-[#8A8078]">Rest deeply. Recover fully. Built from your real wellness check-ins.</p></header>
    <section className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><Card><div className="flex items-center gap-2"><Moon size={15} className="text-[#7C6B9C]"/><h2 className="glow-display text-[18px]">Recent Sleep</h2></div><div className="mt-5 flex min-h-[170px] items-end gap-2">{sleep.slice(0,7).reverse().map(e=>{const hours=e.sleepHours??0;return <div key={e.id} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-[8px] bg-[#DCD7E8]" style={{height:`${Math.max(12,Math.min(120,hours*13))}px`}}/><span className="text-[8.5px] text-[#9A9088]">{e.entryDate.slice(5)}</span></div>})}{sleep.length===0?<p className="self-center text-[11px] text-[#9A9088]">Log sleep hours in Wellness to build this chart.</p>:null}</div></Card><Card><p className="text-[10px] uppercase tracking-[.12em] text-[#9A9088]">Average recent sleep</p><p className="glow-display mt-3 text-[36px]">{n(avgSleep)}{avgSleep!=null?<span className="ml-1 text-[14px] text-[#9A9088]">hours</span>:null}</p><p className="mt-4 text-[10.5px] leading-5 text-[#8A8078]">Glow shows only what you have logged. No sleep quality or stages are invented.</p><Link href="/wellness" className="mt-5 inline-flex items-center gap-1 text-[11px] text-[#6E8064]">Log wellness <ArrowRight size={11}/></Link></Card></section>
    <section className="grid gap-4 sm:grid-cols-3"><Card><BedDouble size={14} className="text-[#7C6B9C]"/><p className="glow-display mt-3 text-[22px]">{sleep.length}</p><p className="text-[10px] text-[#9A9088]">sleep logs</p></Card><Card><p className="text-[10px] text-[#9A9088]">Most recent energy</p><p className="glow-display mt-3 text-[22px] capitalize">{entries[0]?.energy??'—'}</p></Card><Card><p className="text-[10px] text-[#9A9088]">Most recent mood</p><p className="glow-display mt-3 text-[22px] capitalize">{entries[0]?.mood??'—'}</p></Card></section>
    <Card className="bg-[linear-gradient(90deg,#FFF,#F6F3FA)]"><div className="flex items-center gap-2"><Sparkles size={13} className="text-[#7C6B9C]"/><p className="text-[10px] uppercase tracking-[.12em] text-[#7C6B9C]">Glow Insight</p></div><p className="glow-display mt-2 text-[17px] italic">Sleep becomes more useful when it can be compared with energy, stress and your daily patterns.</p></Card>
  </div>;

  return <div className="space-y-5">
    <header><p className="glow-eyebrow text-[#6E8064]">Wellness</p><h1 className="glow-display mt-1 text-[44px] leading-none sm:text-[56px]">Symptoms & Recovery</h1><p className="mt-2 text-[12.5px] text-[#8A8078]">Track how you feel and look for patterns without turning notes into made-up diagnoses.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card><p className="text-[10px] text-[#9A9088]">Recent check-ins</p><p className="glow-display mt-2 text-[25px]">{recent.length}</p></Card><Card><p className="text-[10px] text-[#9A9088]">Low-energy days</p><p className="glow-display mt-2 text-[25px]">{lowEnergy}</p></Card><Card><p className="text-[10px] text-[#9A9088]">Average stress logged</p><p className="glow-display mt-2 text-[25px]">{n(avgStress)}</p></Card><Card><p className="text-[10px] text-[#9A9088]">Notes with context</p><p className="glow-display mt-2 text-[25px]">{noteEntries.length}</p></Card></section>
    <section className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><Card><div className="flex items-center gap-2"><HeartPulse size={14} className="text-[#6E8064]"/><h2 className="glow-display text-[18px]">Recent Wellness Notes</h2></div><div className="mt-4 divide-y divide-[#EFEAE6]">{noteEntries.length?noteEntries.slice(0,10).map(e=><div key={e.id} className="py-3"><div className="flex items-center justify-between gap-3"><p className="text-[10px] text-[#9A9088]">{e.entryDate}</p><p className="text-[9px] capitalize text-[#9A9088]">{e.energy??'energy not logged'} · {e.mood??'mood not logged'}</p></div><p className="mt-1 text-[11.5px] leading-5 text-[#4A4440]">{e.notes}</p></div>):<p className="py-6 text-[11px] text-[#9A9088]">Add notes to Wellness check-ins to build your recovery history.</p>}</div></Card><Card><h2 className="glow-display text-[18px]">What Glow Can Compare</h2><div className="mt-4 space-y-3 text-[11px] text-[#6F655F]"><p>Sleep hours ↔ energy</p><p>Stress level ↔ mood</p><p>Hydration ↔ how you felt that day</p><p>Freeform notes ↔ date and wellness context</p></div><p className="mt-5 text-[10px] leading-5 text-[#9A9088]">Structured symptom names and severity are not in the current wellness schema, so this page does not pretend they are. They can be added later as a dedicated health data model.</p></Card></section>
  </div>;
}
